UnstructuredSolidProblem< ELEMENT > Class Template Reference
Unstructured solid problem.
Public Member Functions
UnstructuredSolidProblem ()
Constructor:
~UnstructuredSolidProblem ()
Destructor (empty)
void set_incompressible ()
Set the problem to be incompressible.
void doc_solution (DocInfo &doc_info)
Doc the solution.
double get_strain_energy ()
Calculate the strain energy.
void actions_before_adapt ()
Remove Traction Mesh.
void actions_after_adapt ()
Add on the traction elements after adaptation.
Private Attributes
RefineableSolidTriangleMesh< ELEMENT > * Solid_mesh_pt
Bulk mesh.
SolidMesh * Traction_mesh_pt
Pointer to mesh of traction elements.
TriangleMeshPolygon * Outer_boundary_polyline_pt
Triangle mesh polygon for outer boundary.
bool Incompressible
Boolean flag used in an incompressible problem.
Detailed Description
template<class ELEMENT>
class UnstructuredSolidProblem< ELEMENT >
Unstructured solid problem.
Definition at line 89 of file unstructured_adaptive_solid.cc.
Constructor & Destructor Documentation
UnstructuredSolidProblem()
template<class ELEMENT >
UnstructuredSolidProblem< ELEMENT >::UnstructuredSolidProblem ()
Constructor:
Constructor for unstructured solid problem.
Definition at line 137 of file unstructured_adaptive_solid.cc.
References UnstructuredSolidProblem< ELEMENT >::actions_after_adapt(), UnstructuredSolidProblem< ELEMENT >::Outer_boundary_polyline_pt, UnstructuredSolidProblem< ELEMENT >::Solid_mesh_pt, and UnstructuredSolidProblem< ELEMENT >::Traction_mesh_pt.
 UnstructuredSolidProblem()
template<class ELEMENT>
UnstructuredSolidProblem< ELEMENT >::~UnstructuredSolidProblem () [inline]
Destructor (empty)
Definition at line 98 of file unstructured_adaptive_solid.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void UnstructuredSolidProblem< ELEMENT >::actions_after_adapt ()
Add on the traction elements after adaptation.
Need to add on the traction elements after adaptation.
Definition at line 352 of file unstructured_adaptive_solid.cc.
References Global_Physical_Variables::constant_pressure(), Global_Physical_Variables::Constitutive_law_pt, UnstructuredSolidProblem< ELEMENT >::Incompressible, UnstructuredSolidProblem< ELEMENT >::set_incompressible(), UnstructuredSolidProblem< ELEMENT >::Solid_mesh_pt, and UnstructuredSolidProblem< ELEMENT >::Traction_mesh_pt.
Referenced by UnstructuredSolidProblem< ELEMENT >::UnstructuredSolidProblem().
actions_before_adapt()
template<class ELEMENT >
void UnstructuredSolidProblem< ELEMENT >::actions_before_adapt ()
Remove Traction Mesh.
Actions before adapt: remove the traction elements in the surface mesh.
Definition at line 335 of file unstructured_adaptive_solid.cc.
References UnstructuredSolidProblem< ELEMENT >::Traction_mesh_pt.
doc_solution()
template<class ELEMENT >
void UnstructuredSolidProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 274 of file unstructured_adaptive_solid.cc.
References UnstructuredSolidProblem< ELEMENT >::Solid_mesh_pt, and UnstructuredSolidProblem< ELEMENT >::Traction_mesh_pt.
Referenced by main().
get_strain_energy()
template<class ELEMENT >
double UnstructuredSolidProblem< ELEMENT >::get_strain_energy ()
Calculate the strain energy.
Calculate the strain energy in the entire elastic solid.
Definition at line 313 of file unstructured_adaptive_solid.cc.
References UnstructuredSolidProblem< ELEMENT >::Solid_mesh_pt.
Referenced by main().
set_incompressible()
template<class ELEMENT>
void UnstructuredSolidProblem< ELEMENT >::set_incompressible () [inline]
Set the problem to be incompressible.
Definition at line 101 of file unstructured_adaptive_solid.cc.
Referenced by UnstructuredSolidProblem< ELEMENT >::actions_after_adapt(), and main().
Member Data Documentation
Incompressible
template<class ELEMENT>
bool UnstructuredSolidProblem< ELEMENT >::Incompressible [private]
Boolean flag used in an incompressible problem.
Definition at line 127 of file unstructured_adaptive_solid.cc.
Referenced by UnstructuredSolidProblem< ELEMENT >::actions_after_adapt().
Outer_boundary_polyline_pt
template<class ELEMENT>
TriangleMeshPolygon* UnstructuredSolidProblem< ELEMENT >::Outer_boundary_polyline_pt [private]
Triangle mesh polygon for outer boundary.
Definition at line 124 of file unstructured_adaptive_solid.cc.
Referenced by UnstructuredSolidProblem< ELEMENT >::UnstructuredSolidProblem().
Solid_mesh_pt
template<class ELEMENT>
RefineableSolidTriangleMesh<ELEMENT>* UnstructuredSolidProblem< ELEMENT >::Solid_mesh_pt [private]
Bulk mesh.
Definition at line 118 of file unstructured_adaptive_solid.cc.
Referenced by UnstructuredSolidProblem< ELEMENT >::actions_after_adapt(), UnstructuredSolidProblem< ELEMENT >::doc_solution(), UnstructuredSolidProblem< ELEMENT >::get_strain_energy(), and UnstructuredSolidProblem< ELEMENT >::UnstructuredSolidProblem().
Traction_mesh_pt
template<class ELEMENT>
SolidMesh* UnstructuredSolidProblem< ELEMENT >::Traction_mesh_pt [private]
Pointer to mesh of traction elements.
Definition at line 121 of file unstructured_adaptive_solid.cc.
Referenced by UnstructuredSolidProblem< ELEMENT >::actions_after_adapt(), UnstructuredSolidProblem< ELEMENT >::actions_before_adapt(), UnstructuredSolidProblem< ELEMENT >::doc_solution(), and UnstructuredSolidProblem< ELEMENT >::UnstructuredSolidProblem().
The documentation for this class was generated from the following file:
unstructured_adaptive_solid.cc