YoungLaplaceProblem< ELEMENT > Class Template Reference
Public Member Functions
YoungLaplaceProblem ()
Constructor:
~YoungLaplaceProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem before solve.
void actions_after_newton_solve ()
Update the problem after solve: Empty.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
YoungLaplaceProblem ()
Constructor:
~YoungLaplaceProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_newton_solve ()
Update the problem after solve: Empty.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
Private Member Functions
void create_contact_angle_elements (const unsigned &b)
Create YoungLaplace contact angle elements on the b-th boundary of the problem's mesh and add them to mesh.
Private Attributes
Node * Control_node_pt
Node at which the height (displacement along spine) is controlled/doced.
Data * Kappa_pt
Pointer to Data object that stores the prescribed curvature.
unsigned N_bulk_elements
Number of YoungLaplace `bulk` elements (We're attaching the contact angle elements to the bulk mesh --> only the first N_bulk_elements elements in the mesh are bulk elements!)
unsigned Last_element_on_boundary1
Number of last FaceElement on boundary 1.
unsigned Last_element_on_boundary3
Number of last FaceElement on boundary 3.
Detailed Description
template<class ELEMENT>
class YoungLaplaceProblem< ELEMENT >
2D YoungLaplace problem on rectangular domain, discretised with 2D QYoungLaplace elements. The specific type of element is specified via the template parameter.
Definition at line 143 of file barrel.cc.
Constructor & Destructor Documentation
YoungLaplaceProblem() [1/2]
template<class ELEMENT >
YoungLaplaceProblem< ELEMENT >::YoungLaplaceProblem ()
Constructor:
Constructor for YoungLaplace problem. Add height control element to mesh at the very end
Definition at line 184 of file barrel.cc.
References GlobalParameters::Controlled_height, GlobalParameters::Kappa_pt, GlobalParameters::spine_base_function(), and GlobalParameters::spine_function().
 YoungLaplaceProblem() [1/2]
template<class ELEMENT>
YoungLaplaceProblem< ELEMENT >::~YoungLaplaceProblem () [inline]
Destructor (empty)
Definition at line 152 of file barrel.cc.
YoungLaplaceProblem() [2/2]
template<class ELEMENT>
YoungLaplaceProblem< ELEMENT >::YoungLaplaceProblem ()
Constructor:
 YoungLaplaceProblem() [2/2]
template<class ELEMENT>
YoungLaplaceProblem< ELEMENT >::~YoungLaplaceProblem () [inline]
Destructor (empty)
Definition at line 66 of file young_laplace.cc.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT>
void YoungLaplaceProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve: Empty.
Definition at line 72 of file young_laplace.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT>
void YoungLaplaceProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve: Empty.
Definition at line 163 of file barrel.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT>
void YoungLaplaceProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void YoungLaplaceProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem before solve.
Update the problem specs before solve: (Re-)set boundary conditions to the values from the exact solution.
Definition at line 155 of file barrel.cc.
References GlobalParameters::Kappa_pt.
Referenced by YoungLaplaceProblem< ELEMENT >::create_contact_angle_elements().
create_contact_angle_elements()
template<class ELEMENT >
void YoungLaplaceProblem< ELEMENT >::create_contact_angle_elements (const unsigned & b) [private]
Create YoungLaplace contact angle elements on the b-th boundary of the problem's mesh and add them to mesh.
Create YoungLaplace contact angle elements on the b-th boundary of the Mesh.
Definition at line 283 of file young_laplace.cc.
References YoungLaplaceProblem< ELEMENT >::actions_before_newton_solve(), GlobalParameters::Case, GlobalParameters::Controlled_height, GlobalParameters::Controlled_height_increment, YoungLaplaceProblem< ELEMENT >::doc_solution(), GlobalParameters::get_exact_kappa(), GlobalParameters::Kappa_increment, GlobalParameters::Kappa_pt, GlobalParameters::T_junction_with_nonzero_contact_angle, and GlobalParameters::Use_height_control.
doc_solution() [1/2]
template<class ELEMENT>
void YoungLaplaceProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
doc_solution() [2/2]
template<class ELEMENT >
void YoungLaplaceProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 295 of file barrel.cc.
References GlobalParameters::get_exact_kappa(), and GlobalParameters::Kappa_pt.
Referenced by YoungLaplaceProblem< ELEMENT >::create_contact_angle_elements(), main(), and run_it().
Member Data Documentation
Control_node_pt
template<class ELEMENT>
Node * YoungLaplaceProblem< ELEMENT >::Control_node_pt [private]
Node at which the height (displacement along spine) is controlled/doced.
Definition at line 172 of file barrel.cc.
Kappa_pt
template<class ELEMENT>
Data* YoungLaplaceProblem< ELEMENT >::Kappa_pt [private]
Pointer to Data object that stores the prescribed curvature.
Definition at line 175 of file barrel.cc.
Last_element_on_boundary1
template<class ELEMENT>
unsigned YoungLaplaceProblem< ELEMENT >::Last_element_on_boundary1 [private]
Number of last FaceElement on boundary 1.
Definition at line 90 of file young_laplace.cc.
Last_element_on_boundary3
template<class ELEMENT>
unsigned YoungLaplaceProblem< ELEMENT >::Last_element_on_boundary3 [private]
Number of last FaceElement on boundary 3.
Definition at line 93 of file young_laplace.cc.
N_bulk_elements
template<class ELEMENT>
unsigned YoungLaplaceProblem< ELEMENT >::N_bulk_elements [private]
Number of YoungLaplace `bulk` elements (We're attaching the contact angle elements to the bulk mesh --> only the first N_bulk_elements elements in the mesh are bulk elements!)
Definition at line 87 of file young_laplace.cc.
The documentation for this class was generated from the following files:
barrel.cc
young_laplace.cc