TwoMeshFluxPoissonProblem< ELEMENT > Class Template Reference
Public Member Functions
TwoMeshFluxPoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~TwoMeshFluxPoissonProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution: doc_info contains labels/output directory etc.
Private Member Functions
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void create_flux_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
Create Poisson flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Private Attributes
SimpleRectangularQuadMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Surface_mesh_pt
Pointer to the `surface` mesh.
PoissonEquations< 2 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT>
class TwoMeshFluxPoissonProblem< ELEMENT >
2D Poisson problem on rectangular domain, discretised with 2D QPoisson elements. Flux boundary conditions are applied along boundary 1 (the boundary where x=L). The specific type of element is specified via the template parameter.
Definition at line 94 of file two_d_poisson_flux_bc2.cc.
Constructor & Destructor Documentation
TwoMeshFluxPoissonProblem()
template<class ELEMENT >
TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
Constructor for Poisson problem: Pass pointer to source function.
Definition at line 144 of file two_d_poisson_flux_bc2.cc.
References TwoMeshFluxPoissonProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(), TwoMeshFluxPoissonProblem< ELEMENT >::Source_fct_pt, and TwoMeshFluxPoissonProblem< ELEMENT >::Surface_mesh_pt.
 TwoMeshFluxPoissonProblem()
template<class ELEMENT>
TwoMeshFluxPoissonProblem< ELEMENT >::~TwoMeshFluxPoissonProblem () [inline]
Destructor (empty)
Definition at line 103 of file two_d_poisson_flux_bc2.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void TwoMeshFluxPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline], [private]
Update the problem specs after solve (empty)
Definition at line 117 of file two_d_poisson_flux_bc2.cc.
actions_before_newton_solve()
template<class ELEMENT >
void TwoMeshFluxPoissonProblem< ELEMENT >::actions_before_newton_solve () [private]
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Definition at line 243 of file two_d_poisson_flux_bc2.cc.
References TwoMeshFluxPoissonProblem< ELEMENT >::Bulk_mesh_pt, and TanhSolnForPoisson::get_exact_u().
create_flux_elements()
template<class ELEMENT >
void TwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt) [private]
Create Poisson flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Create Poisson Flux Elements on the b-th boundary of the Mesh object pointed to by bulk_mesh_pt and add the elements to the Mesh object pointeed to by surface_mesh_pt.
Definition at line 337 of file two_d_poisson_flux_bc2.cc.
Referenced by TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), and TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem().
doc_solution()
template<class ELEMENT >
void TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution: doc_info contains labels/output directory etc.
Doc the solution. DocInfo object stores flags/labels for where the output gets written to
Definition at line 285 of file two_d_poisson_flux_bc2.cc.
References TwoMeshFluxPoissonProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), and TanhSolnForPoisson::get_exact_u().
Referenced by main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT>
SimpleRectangularQuadMesh<ELEMENT>* TwoMeshFluxPoissonProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 126 of file two_d_poisson_flux_bc2.cc.
Referenced by TwoMeshFluxPoissonProblem< ELEMENT >::actions_before_newton_solve(), TwoMeshFluxPoissonProblem< ELEMENT >::doc_solution(), and TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem().
Source_fct_pt
template<class ELEMENT>
PoissonEquations<2>::PoissonSourceFctPt TwoMeshFluxPoissonProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 132 of file two_d_poisson_flux_bc2.cc.
Referenced by TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem().
Surface_mesh_pt
template<class ELEMENT>
Mesh* TwoMeshFluxPoissonProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the `surface` mesh.
Definition at line 129 of file two_d_poisson_flux_bc2.cc.
Referenced by TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem().
The documentation for this class was generated from the following file:
two_d_poisson_flux_bc2.cc