TanhSolnForPoisson Namespace Reference
Namespace for exact solution for Poisson equation with sharp step.
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
Variables
double Alpha
Parameter for steepness of step.
double Beta
Parameter for angle of step.
double X_shift =8.0
Shift of step along x-direction.
bool TanhSoln =false
Flag for zero TanhSolution.
Detailed Description
Namespace for exact solution for Poisson equation with sharp step.
Function Documentation
get_exact_u() [1/2]
void TanhSolnForPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
Definition at line 68 of file mesh_from_xfig_poisson.cc.
Referenced by PoissonProblem< ELEMENT >::actions_before_newton_solve(), and PoissonProblem< ELEMENT >::doc_solution().
get_exact_u() [2/2]
void TanhSolnForPoisson::get_exact_u (const Vector< double > & x, double & u)
Exact solution as a scalar.
Definition at line 82 of file mesh_from_xfig_poisson.cc.
get_source()
void TanhSolnForPoisson::get_source (const Vector< double > & x, double & source)
Source function to make it an exact solution.
Definition at line 96 of file mesh_from_xfig_poisson.cc.
Referenced by main().
Variable Documentation
Alpha
double TanhSolnForPoisson::Alpha
Parameter for steepness of step.
Definition at line 56 of file mesh_from_xfig_poisson.cc.
Referenced by PoissonProblem< ELEMENT >::PoissonProblem().
Beta
double TanhSolnForPoisson::Beta
Parameter for angle of step.
Definition at line 59 of file mesh_from_xfig_poisson.cc.
Referenced by PoissonProblem< ELEMENT >::PoissonProblem().
TanhSoln
bool TanhSolnForPoisson::TanhSoln =false
Flag for zero TanhSolution.
Definition at line 65 of file mesh_from_xfig_poisson.cc.
Referenced by PoissonProblem< ELEMENT >::doc_solution(), and main().
X_shift
double TanhSolnForPoisson::X_shift =8.0
Shift of step along x-direction.
Definition at line 62 of file mesh_from_xfig_poisson.cc.