FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT > Class Template Reference
Public Member Functions
FourierDecomposedTimeHarmonicLinearElasticityProblem (const unsigned &nr, const unsigned &nz, const double &rmin, const double &rmax, const double &zmin, const double &zmax)
Constructor: Pass number of elements in r and z directions and boundary locations.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void doc_solution (DocInfo &doc_info)
Doc the solution.
FourierDecomposedTimeHarmonicLinearElasticityProblem (const unsigned &nr, const unsigned &nz, const double &rmin, const double &rmax, const double &zmin, const double &zmax)
Constructor: Pass number of elements in r and z directions and boundary locations.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void delete_traction_elements ()
Delete traction elements.
void complete_problem_setup ()
Helper function to complete problem setup.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
FourierDecomposedTimeHarmonicLinearElasticityProblem (const double &rmin, const double &rmax, const double &zmin, const double &zmax)
Constructor: Pass boundary locations.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void assign_traction_elements ()
Allocate traction elements on the bottom surface.
void assign_traction_elements ()
Allocate traction elements on the bottom surface.
void assign_traction_elements ()
Allocate traction elements on the bottom surface.
void delete_traction_elements ()
Delete traction elements.
void complete_problem_setup ()
Helper function to complete problem setup.
Private Attributes
Mesh * Bulk_mesh_pt
Pointer to the bulk mesh.
Mesh * Surface_mesh_pt
Pointer to the mesh of traction elements.
RefineableTriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the bulk mesh.
Detailed Description
template<class ELEMENT>
class FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >
Class to validate time harmonic linear elasticity (Fourier decomposed)
Definition at line 137 of file cylinder.cc.
Constructor & Destructor Documentation
FourierDecomposedTimeHarmonicLinearElasticityProblem() [1/3]
template<class ELEMENT >
FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem (const unsigned & nr, const unsigned & nz, const double & rmin, const double & rmax, const double & zmin, const double & zmax)
Constructor: Pass number of elements in r and z directions and boundary locations.
Problem constructor: Pass number of elements in coordinate directions and size of domain.
Definition at line 178 of file cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements(), Global_Parameters::body_force(), Global_Parameters::boundary_traction(), Global_Parameters::E(), Global_Parameters::exact_solution(), Global_Parameters::Fourier_wavenumber, Global_Parameters::Nu(), Global_Parameters::Omega_sq(), Global_Parameters::rmax, Global_Parameters::rmin, Global_Parameters::zmax, and Global_Parameters::zmin.
Referenced by FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_adapt().
FourierDecomposedTimeHarmonicLinearElasticityProblem() [2/3]
template<class ELEMENT >
FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem (const unsigned & nr, const unsigned & nz, const double & rmin, const double & rmax, const double & zmin, const double & zmax)
Constructor: Pass number of elements in r and z directions and boundary locations.
FourierDecomposedTimeHarmonicLinearElasticityProblem() [3/3]
template<class ELEMENT >
FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem (const double & rmin, const double & rmax, const double & zmin, const double & zmax)
Constructor: Pass boundary locations.
Problem constructor: Pass size of domain.
Definition at line 218 of file unstructured_cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements(), Global_Parameters::body_force(), Global_Parameters::boundary_traction(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution(), Global_Parameters::E(), Global_Parameters::exact_solution(), Global_Parameters::Fourier_wavenumber, Global_Parameters::Nu(), Global_Parameters::Omega_sq(), Global_Parameters::rmax, Global_Parameters::rmin, Global_Parameters::zmax, and Global_Parameters::zmin.
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 139 of file pressure_loaded_cylinder.cc.
actions_after_adapt() [2/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 167 of file unstructured_cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem().
actions_after_newton_solve() [1/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 119 of file pressure_loaded_cylinder.cc.
actions_after_newton_solve() [2/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 152 of file unstructured_cylinder.cc.
actions_after_newton_solve() [3/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 153 of file cylinder.cc.
actions_before_adapt() [1/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 128 of file pressure_loaded_cylinder.cc.
actions_before_adapt() [2/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 156 of file unstructured_cylinder.cc.
actions_before_newton_solve() [1/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 116 of file pressure_loaded_cylinder.cc.
actions_before_newton_solve() [2/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 149 of file unstructured_cylinder.cc.
actions_before_newton_solve() [3/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 150 of file cylinder.cc.
assign_traction_elements() [1/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements () [private]
Allocate traction elements on the bottom surface.
assign_traction_elements() [2/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements () [private]
Allocate traction elements on the bottom surface.
Make traction elements along the boundary r=rmin.
Definition at line 293 of file cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution().
Referenced by FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup(), and FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem().
assign_traction_elements() [3/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements () [private]
Allocate traction elements on the bottom surface.
complete_problem_setup() [1/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup ()
Helper function to complete problem setup.
Complete problem setup.
Definition at line 292 of file pressure_loaded_cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements(), Global_Parameters::boundary_traction(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements(), Global_Parameters::E(), Global_Parameters::Fourier_wavenumber, Global_Parameters::Nu(), and Global_Parameters::Omega_sq().
Referenced by FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem().
complete_problem_setup() [2/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup () [private]
Helper function to complete problem setup.
delete_traction_elements() [1/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements ()
Delete traction elements.
Definition at line 397 of file pressure_loaded_cylinder.cc.
References FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution().
Referenced by FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup(), and FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem().
delete_traction_elements() [2/2]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements () [private]
Delete traction elements.
doc_solution() [1/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [2/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 322 of file cylinder.cc.
References Global_Parameters::exact_solution().
Referenced by FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::assign_traction_elements(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements(), and FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem().
doc_solution() [3/3]
template<class ELEMENT >
void FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Member Data Documentation
Bulk_mesh_pt [1/2]
template<class ELEMENT >
RefineableTriangleMesh<ELEMENT>* FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the bulk mesh.
Definition at line 163 of file pressure_loaded_cylinder.cc.
Bulk_mesh_pt [2/2]
template<class ELEMENT >
Mesh * FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the bulk mesh.
Definition at line 164 of file cylinder.cc.
Surface_mesh_pt
template<class ELEMENT >
Mesh * FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the mesh of traction elements.
Definition at line 167 of file cylinder.cc.
The documentation for this class was generated from the following files:
cylinder.cc
pressure_loaded_cylinder.cc
unstructured_cylinder.cc