OneDPoissonProblem< ELEMENT > Class Template Reference
1D Poisson problem in unit interval.
Public Member Functions
OneDPoissonProblem (const unsigned &n_element, PoissonEquations< 1 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass number of elements and pointer to source function.
~OneDPoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void doc_solution (const unsigned &label)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Private Attributes
PoissonEquations< 1 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT>
class OneDPoissonProblem< ELEMENT >
1D Poisson problem in unit interval.
Definition at line 82 of file one_d_poisson.cc.
Constructor & Destructor Documentation
OneDPoissonProblem()
template<class ELEMENT >
OneDPoissonProblem< ELEMENT >::OneDPoissonProblem (const unsigned & n_element, PoissonEquations< 1 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass number of elements and pointer to source function.
Constructor for 1D Poisson problem in unit interval. Discretise the 1D domain with n_element elements of type ELEMENT. Specify function pointer to source function.
Definition at line 124 of file one_d_poisson.cc.
References OneDPoissonProblem< ELEMENT >::Source_fct_pt.
 OneDPoissonProblem()
template<class ELEMENT>
OneDPoissonProblem< ELEMENT >::~OneDPoissonProblem () [inline]
Destructor (empty)
Definition at line 92 of file one_d_poisson.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void OneDPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 101 of file one_d_poisson.cc.
actions_before_newton_solve()
template<class ELEMENT >
void OneDPoissonProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
Update the problem specs before solve: (Re)set boundary values from the exact solution.
Definition at line 174 of file one_d_poisson.cc.
References FishSolnOneDPoisson::get_exact_u().
doc_solution()
template<class ELEMENT >
void OneDPoissonProblem< ELEMENT >::doc_solution (const unsigned & label)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Doc the solution in tecplot format. Label files with label.
Definition at line 220 of file one_d_poisson.cc.
References FishSolnOneDPoisson::get_exact_u().
Referenced by main().
Member Data Documentation
Source_fct_pt
template<class ELEMENT>
PoissonEquations<1>::PoissonSourceFctPt OneDPoissonProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 110 of file one_d_poisson.cc.
Referenced by OneDPoissonProblem< ELEMENT >::OneDPoissonProblem().
The documentation for this class was generated from the following file:
one_d_poisson.cc