UnstructuredFluidProblem< ELEMENT > Class Template Reference
Unstructured fluid problem.
Public Member Functions
UnstructuredFluidProblem ()
Constructor:
~UnstructuredFluidProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: empty.
void actions_after_newton_solve ()
Update the problem specs before solve: empty.
void doc_solution (DocInfo &doc_info)
Doc the solution.
unsigned nfluid_inflow_traction_boundary ()
Return total number of fluid inflow traction boundaries.
unsigned nfluid_outflow_traction_boundary ()
Return total number of fluid outflow traction boundaries.
unsigned nfluid_traction_boundary ()
Return total number of fluid outflow traction boundaries.
Private Member Functions
void create_parallel_outflow_lagrange_elements ()
Create Lagrange multiplier elements that enforce parallel outflow.
Private Attributes
TetgenMesh< ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Vector< Mesh * > Parallel_outflow_lagrange_multiplier_mesh_pt
Meshes of FaceElements imposing parallel outflow and a pressure at the in/outflow.
Vector< unsigned > Inflow_boundary_id
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Vector< unsigned > Outflow_boundary_id
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Detailed Description
template<class ELEMENT>
class UnstructuredFluidProblem< ELEMENT >
Unstructured fluid problem.
Definition at line 72 of file vmtk_fluid.cc.
Constructor & Destructor Documentation
UnstructuredFluidProblem()
template<class ELEMENT >
UnstructuredFluidProblem< ELEMENT >::UnstructuredFluidProblem ()
Constructor:
Constructor for unstructured 3D fluid problem.
Definition at line 138 of file vmtk_fluid.cc.
References UnstructuredFluidProblem< ELEMENT >::create_parallel_outflow_lagrange_elements(), and Global_Parameters::Re.
 UnstructuredFluidProblem()
template<class ELEMENT>
UnstructuredFluidProblem< ELEMENT >::~UnstructuredFluidProblem () [inline]
Destructor (empty)
Definition at line 81 of file vmtk_fluid.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void UnstructuredFluidProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs before solve: empty.
Definition at line 87 of file vmtk_fluid.cc.
actions_before_newton_solve()
template<class ELEMENT>
void UnstructuredFluidProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: empty.
Definition at line 84 of file vmtk_fluid.cc.
create_parallel_outflow_lagrange_elements()
template<class ELEMENT >
void UnstructuredFluidProblem< ELEMENT >::create_parallel_outflow_lagrange_elements () [private]
Create Lagrange multiplier elements that enforce parallel outflow.
Create Lagrange multiplier elements that impose parallel outflow.
Definition at line 333 of file vmtk_fluid.cc.
References Global_Parameters::P_in, and Global_Parameters::P_out.
Referenced by UnstructuredFluidProblem< ELEMENT >::UnstructuredFluidProblem().
doc_solution()
template<class ELEMENT >
void UnstructuredFluidProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 400 of file vmtk_fluid.cc.
Referenced by main().
nfluid_inflow_traction_boundary()
template<class ELEMENT>
unsigned UnstructuredFluidProblem< ELEMENT >::nfluid_inflow_traction_boundary () [inline]
Return total number of fluid inflow traction boundaries.
Definition at line 93 of file vmtk_fluid.cc.
nfluid_outflow_traction_boundary()
template<class ELEMENT>
unsigned UnstructuredFluidProblem< ELEMENT >::nfluid_outflow_traction_boundary () [inline]
Return total number of fluid outflow traction boundaries.
Definition at line 99 of file vmtk_fluid.cc.
nfluid_traction_boundary()
template<class ELEMENT>
unsigned UnstructuredFluidProblem< ELEMENT >::nfluid_traction_boundary () [inline]
Return total number of fluid outflow traction boundaries.
Definition at line 105 of file vmtk_fluid.cc.
Member Data Documentation
Fluid_mesh_pt
template<class ELEMENT>
TetgenMesh<ELEMENT>* UnstructuredFluidProblem< ELEMENT >::Fluid_mesh_pt [private]
Bulk fluid mesh.
Definition at line 116 of file vmtk_fluid.cc.
Inflow_boundary_id
template<class ELEMENT>
Vector<unsigned> UnstructuredFluidProblem< ELEMENT >::Inflow_boundary_id [private]
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Definition at line 124 of file vmtk_fluid.cc.
Outflow_boundary_id
template<class ELEMENT>
Vector<unsigned> UnstructuredFluidProblem< ELEMENT >::Outflow_boundary_id [private]
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Definition at line 128 of file vmtk_fluid.cc.
Parallel_outflow_lagrange_multiplier_mesh_pt
template<class ELEMENT>
Vector<Mesh*> UnstructuredFluidProblem< ELEMENT >::Parallel_outflow_lagrange_multiplier_mesh_pt [private]
Meshes of FaceElements imposing parallel outflow and a pressure at the in/outflow.
Definition at line 120 of file vmtk_fluid.cc.
The documentation for this class was generated from the following file:
vmtk_fluid.cc