PMLFourierDecomposedHelmholtzProblem< ELEMENT > Class Template Reference
Problem class.
Public Member Functions
PMLFourierDecomposedHelmholtzProblem ()
Constructor.
~PMLFourierDecomposedHelmholtzProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
void create_pml_meshes ()
Create PML meshes.
void create_power_monitor_mesh ()
Create mesh of face elements that monitor the radiated power.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed flux elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed flux elements.
void complete_problem_setup ()
Private Member Functions
void create_flux_elements_on_inner_boundary ()
Create flux elements on inner boundary.
void delete_face_elements (Mesh *const &boundary_mesh_pt)
Delete boundary face elements and wipe the surface mesh.
void apply_zero_dirichlet_boundary_conditions ()
void setup_point_source ()
Set point source.
Private Attributes
Mesh * Power_monitor_mesh_pt
Pointer to mesh that stores the power monitor elements.
RefineableTriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the refineable `bulk` mesh.
MeshAsGeomObject * Mesh_as_geom_obj_pt
Mesh as geometric object representation of bulk mesh.
TriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Helmholtz_inner_boundary_mesh_pt
Mesh of FaceElements that apply the flux bc on the inner boundary.
Mesh * PML_right_mesh_pt
Pointer to the right PML mesh.
Mesh * PML_top_mesh_pt
Pointer to the top PML mesh.
Mesh * PML_bottom_mesh_pt
Pointer to the bottom PML mesh.
Mesh * PML_top_right_mesh_pt
Pointer to the top right corner PML mesh.
Mesh * PML_bottom_right_mesh_pt
Pointer to the bottom right corner PML mesh.
ofstream Trace_file
Trace file.
Detailed Description
template<class ELEMENT>
class PMLFourierDecomposedHelmholtzProblem< ELEMENT >
Problem class.
Definition at line 433 of file oscillating_sphere.cc.
Constructor & Destructor Documentation
PMLFourierDecomposedHelmholtzProblem()
template<class ELEMENT >
PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem ()
Constructor.
Constructor for Pml Fourier-decomposed Helmholtz problem. Setup `bulk` mesh
Definition at line 794 of file oscillating_sphere.cc.
References ProblemParameters::Directory, PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), ProblemParameters::Element_area, and ProblemParameters::K_squared.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::apply_zero_dirichlet_boundary_conditions().
 PMLFourierDecomposedHelmholtzProblem()
template<class ELEMENT >
PMLFourierDecomposedHelmholtzProblem< ELEMENT >::~PMLFourierDecomposedHelmholtzProblem () [inline]
Destructor (empty)
Definition at line 442 of file oscillating_sphere.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed flux elements.
Actions after adapt: Rebuild the face element meshes.
Definition at line 623 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::complete_problem_setup().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_adapt().
actions_after_newton_solve()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 448 of file oscillating_sphere.cc.
actions_before_adapt()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed flux elements.
Actions before adapt: Wipe the mesh of face elements.
Definition at line 585 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_adapt().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_power_monitor_mesh().
actions_before_newton_solve()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 445 of file oscillating_sphere.cc.
apply_zero_dirichlet_boundary_conditions()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::apply_zero_dirichlet_boundary_conditions () [private]
Definition at line 736 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().
complete_problem_setup()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::complete_problem_setup ()
Definition at line 653 of file oscillating_sphere.cc.
References ProblemParameters::K_squared, ProblemParameters::N_fourier, and PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_adapt().
create_flux_elements_on_inner_boundary()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary () [private]
Create flux elements on inner boundary.
Definition at line 1076 of file oscillating_sphere.cc.
References ProblemParameters::exact_minus_dudr().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution().
create_pml_meshes()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes ()
Create PML meshes.
Create PML meshes and add them to the problem's sub-meshes.
Definition at line 1114 of file oscillating_sphere.cc.
References ProblemParameters::Nel_pml, and ProblemParameters::PML_thickness.
create_power_monitor_mesh()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_power_monitor_mesh ()
Create mesh of face elements that monitor the radiated power.
Create BC elements on outer boundary.
Definition at line 548 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_adapt().
delete_face_elements()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::delete_face_elements (Mesh *const & boundary_mesh_pt) [inline], [private]
Delete boundary face elements and wipe the surface mesh.
Definition at line 480 of file oscillating_sphere.cc.
doc_solution()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 979 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary(), and ProblemParameters::get_exact_u().
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem().
setup_point_source()
template<class ELEMENT >
void PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source () [private]
Set point source.
Definition at line 694 of file oscillating_sphere.cc.
References PMLFourierDecomposedHelmholtzProblem< ELEMENT >::apply_zero_dirichlet_boundary_conditions(), ProblemParameters::Magnitude(), ProblemParameters::N_fourier, ProblemParameters::R_source, and ProblemParameters::Z_source.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::complete_problem_setup().
Member Data Documentation
Bulk_mesh_pt [1/2]
template<class ELEMENT >
RefineableTriangleMesh<ELEMENT>* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the refineable `bulk` mesh.
Definition at line 507 of file oscillating_sphere.cc.
Bulk_mesh_pt [2/2]
template<class ELEMENT >
TriangleMesh<ELEMENT>* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 515 of file oscillating_sphere.cc.
Helmholtz_inner_boundary_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Helmholtz_inner_boundary_mesh_pt [private]
Mesh of FaceElements that apply the flux bc on the inner boundary.
Definition at line 520 of file oscillating_sphere.cc.
Mesh_as_geom_obj_pt
template<class ELEMENT >
MeshAsGeomObject* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Mesh_as_geom_obj_pt [private]
Mesh as geometric object representation of bulk mesh.
Definition at line 510 of file oscillating_sphere.cc.
PML_bottom_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PML_bottom_mesh_pt [private]
Pointer to the bottom PML mesh.
Definition at line 529 of file oscillating_sphere.cc.
PML_bottom_right_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PML_bottom_right_mesh_pt [private]
Pointer to the bottom right corner PML mesh.
Definition at line 535 of file oscillating_sphere.cc.
PML_right_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PML_right_mesh_pt [private]
Pointer to the right PML mesh.
Definition at line 523 of file oscillating_sphere.cc.
PML_top_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PML_top_mesh_pt [private]
Pointer to the top PML mesh.
Definition at line 526 of file oscillating_sphere.cc.
PML_top_right_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PML_top_right_mesh_pt [private]
Pointer to the top right corner PML mesh.
Definition at line 532 of file oscillating_sphere.cc.
Power_monitor_mesh_pt
template<class ELEMENT >
Mesh* PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Power_monitor_mesh_pt [private]
Pointer to mesh that stores the power monitor elements.
Definition at line 498 of file oscillating_sphere.cc.
Trace_file
template<class ELEMENT >
ofstream PMLFourierDecomposedHelmholtzProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 538 of file oscillating_sphere.cc.
The documentation for this class was generated from the following file:
oscillating_sphere.cc