oomph::SimpleCubicMesh< ELEMENT > Class Template Reference
Simple cubic 3D Brick mesh class.
#include <simple_cubic_mesh.template.h>
Public Member Functions
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &lx, const double &ly, const double &lz, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in the x, y, and z directions, and the corresponding dimensions. Assume that the back lower left corner is located at (0,0,0) Timestepper defaults to Steady.
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const double &zmin, const double &zmax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass the number of elements in the x,y and z directions and the correspoding minimum and maximum values of the coordinates in each direction.
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
const unsigned & nz () const
Access function for number of elements in y directions.
Protected Member Functions
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
Protected Attributes
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y direction.
unsigned Nz
Number of elements in y direction.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Minimum value of y coordinate.
double Zmin
Minimum value of z coordinate.
double Zmax
Maximum value of z coordinate.
Detailed Description
template<class ELEMENT>
class oomph::SimpleCubicMesh< ELEMENT >
Simple cubic 3D Brick mesh class.
Definition at line 52 of file simple_cubic_mesh.template.h.
Constructor & Destructor Documentation
SimpleCubicMesh() [1/2]
template<class ELEMENT >
oomph::SimpleCubicMesh< ELEMENT >::SimpleCubicMesh (const unsigned & nx, const unsigned & ny, const unsigned & nz, const double & lx, const double & ly, const double & lz, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in the x, y, and z directions, and the corresponding dimensions. Assume that the back lower left corner is located at (0,0,0) Timestepper defaults to Steady.
Definition at line 61 of file simple_cubic_mesh.template.h.
References oomph::SimpleCubicMesh< ELEMENT >::build_mesh().
SimpleCubicMesh() [2/2]
template<class ELEMENT >
oomph::SimpleCubicMesh< ELEMENT >::SimpleCubicMesh (const unsigned & nx, const unsigned & ny, const unsigned & nz, const double & xmin, const double & xmax, const double & ymin, const double & ymax, const double & zmin, const double & zmax, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass the number of elements in the x,y and z directions and the correspoding minimum and maximum values of the coordinates in each direction.
Definition at line 77 of file simple_cubic_mesh.template.h.
References oomph::SimpleCubicMesh< ELEMENT >::build_mesh().
Member Function Documentation
build_mesh()
template<class ELEMENT >
void oomph::SimpleCubicMesh< ELEMENT >::build_mesh (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [protected]
Generic mesh construction function: contains all the hard work.
Generic mesh construction. This function contains all the details of the mesh generation process, including all the tedious loops, counting spacing and boundary functions.
Definition at line 45 of file simple_cubic_mesh.template.cc.
Referenced by oomph::SimpleCubicMesh< ELEMENT >::SimpleCubicMesh().
nx()
template<class ELEMENT >
const unsigned& oomph::SimpleCubicMesh< ELEMENT >::nx () const [inline]
Access function for number of elements in x directions.
Definition at line 93 of file simple_cubic_mesh.template.h.
References oomph::SimpleCubicMesh< ELEMENT >::Nx.
ny()
template<class ELEMENT >
const unsigned& oomph::SimpleCubicMesh< ELEMENT >::ny () const [inline]
Access function for number of elements in y directions.
Definition at line 96 of file simple_cubic_mesh.template.h.
References oomph::SimpleCubicMesh< ELEMENT >::Ny.
nz()
template<class ELEMENT >
const unsigned& oomph::SimpleCubicMesh< ELEMENT >::nz () const [inline]
Access function for number of elements in y directions.
Definition at line 99 of file simple_cubic_mesh.template.h.
References oomph::SimpleCubicMesh< ELEMENT >::Nx.
Referenced by oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), and oomph::RefineableQuarterPipeMesh< ELEMENT >::RefineableQuarterPipeMesh().
Member Data Documentation
Nx
template<class ELEMENT >
unsigned oomph::SimpleCubicMesh< ELEMENT >::Nx [protected]
Number of elements in x direction.
Definition at line 104 of file simple_cubic_mesh.template.h.
Referenced by oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SimpleCubicMesh< ELEMENT >::nx(), and oomph::SimpleCubicMesh< ELEMENT >::nz().
Ny
template<class ELEMENT >
unsigned oomph::SimpleCubicMesh< ELEMENT >::Ny [protected]
Number of elements in y direction.
Definition at line 107 of file simple_cubic_mesh.template.h.
Referenced by oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), and oomph::SimpleCubicMesh< ELEMENT >::ny().
Nz
template<class ELEMENT >
unsigned oomph::SimpleCubicMesh< ELEMENT >::Nz [protected]
Number of elements in y direction.
Definition at line 110 of file simple_cubic_mesh.template.h.
Referenced by oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh().
Xmax
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Xmax [protected]
Maximum value of x coordinate.
Definition at line 116 of file simple_cubic_mesh.template.h.
Xmin
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Xmin [protected]
Minimum value of x coordinate.
Definition at line 113 of file simple_cubic_mesh.template.h.
Ymax
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Ymax [protected]
Minimum value of y coordinate.
Definition at line 122 of file simple_cubic_mesh.template.h.
Ymin
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Ymin [protected]
Minimum value of y coordinate.
Definition at line 119 of file simple_cubic_mesh.template.h.
Zmax
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Zmax [protected]
Maximum value of z coordinate.
Definition at line 128 of file simple_cubic_mesh.template.h.
Zmin
template<class ELEMENT >
double oomph::SimpleCubicMesh< ELEMENT >::Zmin [protected]
Minimum value of z coordinate.
Definition at line 125 of file simple_cubic_mesh.template.h.
Referenced by oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update().
The documentation for this class was generated from the following files:
simple_cubic_mesh.template.h
simple_cubic_mesh.template.cc