CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT > Class Template Reference
Coated disk FSI.
Public Member Functions
CoatedDiskProblem ()
Constructor:
void actions_before_newton_solve ()
Update function (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_convergence_check ()
Recompute gamma integral before checking Newton residuals.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution ()
Doc the solution.
CoatedDiskProblem ()
Constructor:
void actions_before_newton_solve ()
Update function (empty)
void actions_after_newton_solve ()
Update function (empty)
void actions_before_adapt ()
Actions before adapt: Wipe the face meshes.
void actions_after_adapt ()
Actions after adapt: Rebuild the face meshes.
void doc_solution ()
Doc the solution.
Private Member Functions
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_helmholtz_fsi_flux_elements ()
Create Helmholtz FSI flux elements.
void delete_face_elements (Mesh *const &boundary_mesh_pt)
Delete (face) elements in specified mesh.
void create_helmholtz_DtN_elements ()
Create DtN face elements.
void setup_interaction ()
Setup interaction.
void complete_problem_setup ()
void create_solid_traction_elements ()
Create solid traction elements.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_helmholtz_fsi_flux_elements ()
Create Helmholtz FSI flux elements.
void delete_face_elements (Mesh *const &boundary_mesh_pt)
Delete (face) elements in specified mesh.
void create_helmholtz_ABC_elements ()
Create ABC face elements.
void setup_interaction ()
Setup interaction.
Private Attributes
TreeBasedRefineableMeshBase * Solid_mesh_pt
Pointer to solid mesh.
Mesh * FSI_traction_mesh_pt
Pointer to mesh of FSI traction elements.
TreeBasedRefineableMeshBase * Helmholtz_mesh_pt
Pointer to Helmholtz mesh.
Mesh * Helmholtz_fsi_flux_mesh_pt
Pointer to mesh of Helmholtz FSI flux elements.
HelmholtzDtNMesh< HELMHOLTZ_ELEMENT > * Helmholtz_outer_boundary_mesh_pt
Pointer to mesh containing the DtN elements.
DocInfo Doc_info
DocInfo object for output.
ofstream Trace_file
Trace file.
RefineableTriangleMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to refineable solid mesh.
Mesh * Solid_traction_mesh_pt
Pointer to mesh of solid traction elements.
Mesh * Helmholtz_outer_boundary_mesh_pt
Pointer to mesh containing the ABC elements.
unsigned Upper_symmetry_boundary_id
Boundary ID of upper symmetry boundary.
unsigned Lower_symmetry_boundary_id
Boundary ID of lower symmetry boundary.
unsigned Upper_inner_boundary_id
Boundary ID of upper inner boundary.
unsigned Lower_inner_boundary_id
Boundary ID of lower inner boundary.
unsigned Outer_boundary_id
Boundary ID of outer boundary.
unsigned Rib_divider_boundary_id
Detailed Description
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
class CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated disk FSI.
Definition at line 239 of file acoustic_fsi.cc.
Constructor & Destructor Documentation
CoatedDiskProblem() [1/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem ()
Constructor:
Constructor.
Definition at line 313 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_adapt(), Global_Parameters::Directory, Global_Parameters::E(), Global_Parameters::El_multiplier, Global_Parameters::H_coating, Global_Parameters::K_squared, Global_Parameters::Omega_sq, Global_Parameters::Outer_radius, and Global_Parameters::solid_boundary_displacement().
CoatedDiskProblem() [2/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem ()
Constructor:
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the face meshes.
actions_after_adapt() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
Actions after adapt: Rebuild the meshes of face elements.
Definition at line 528 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_adapt().
actions_after_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 195 of file unstructured_acoustic_fsi.cc.
actions_after_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 251 of file acoustic_fsi.cc.
actions_before_adapt() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the face meshes.
actions_before_adapt() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
Actions before adapt: Wipe the meshes face elements.
Definition at line 505 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_adapt().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedDiskProblem().
actions_before_newton_convergence_check()
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_convergence_check () [inline]
Recompute gamma integral before checking Newton residuals.
Definition at line 254 of file acoustic_fsi.cc.
actions_before_newton_solve() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 192 of file unstructured_acoustic_fsi.cc.
actions_before_newton_solve() [2/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 248 of file acoustic_fsi.cc.
complete_problem_setup()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup () [private]
Complete problem setup: Apply boundary conditions and set physical properties
Definition at line 774 of file unstructured_acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements(), Global_Parameters::E_pt, and Global_Parameters::Omega_sq.
create_fsi_traction_elements() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements () [private]
Create FSI traction elements.
create_fsi_traction_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements () [private]
Create FSI traction elements.
Create fsi traction elements.
Definition at line 579 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), and Global_Parameters::Q.
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), and CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements().
create_helmholtz_ABC_elements()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements () [private]
Create ABC face elements.
Create ABC elements on the outer boundary of the Helmholtz mesh
Definition at line 1025 of file unstructured_acoustic_fsi.cc.
References Global_Parameters::ABC_order, Global_Parameters::Density_ratio, CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), Global_Parameters::K_squared, Global_Parameters::Omega_sq, Global_Parameters::Outer_radius, Global_Parameters::Q, and CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements().
create_helmholtz_DtN_elements()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements () [private]
Create DtN face elements.
Create DtN elements on the outer boundary of the Helmholtz mesh
Definition at line 669 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements().
create_helmholtz_fsi_flux_elements() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements () [private]
Create Helmholtz FSI flux elements.
create_helmholtz_fsi_flux_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements () [private]
Create Helmholtz FSI flux elements.
Create Helmholtz fsi flux elements.
Create Helmholtz fsii flux elements.
Definition at line 625 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), and CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements().
create_solid_traction_elements()
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements () [private]
Create solid traction elements.
Definition at line 871 of file unstructured_acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), Global_Parameters::pressure_load(), and Global_Parameters::Q.
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup().
delete_face_elements() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements (Mesh *const & boundary_mesh_pt) [private]
Delete (face) elements in specified mesh.
delete_face_elements() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements (Mesh *const & boundary_mesh_pt) [private]
Delete (face) elements in specified mesh.
Delete face elements and wipe the mesh.
Definition at line 555 of file acoustic_fsi.cc.
References CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements().
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::actions_after_adapt(), and CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup().
doc_solution() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 731 of file acoustic_fsi.cc.
References Global_Parameters::Density_ratio, Global_Parameters::exact_axisym_potential(), Global_Parameters::exact_axisym_radiated_power(), Global_Parameters::K_squared, Global_Parameters::Omega_sq, and Global_Parameters::Q.
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements(), and main().
setup_interaction() [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction () [private]
Setup interaction.
setup_interaction() [2/2]
template<class ELASTICITY_ELEMENT , class HELMHOLTZ_ELEMENT >
void CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::setup_interaction () [private]
Setup interaction.
Setup interaction between two fields.
Definition at line 710 of file acoustic_fsi.cc.
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements(), and CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements().
Member Data Documentation
Doc_info
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
DocInfo CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Doc_info [private]
DocInfo object for output.
Definition at line 301 of file acoustic_fsi.cc.
FSI_traction_mesh_pt
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
Mesh * CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::FSI_traction_mesh_pt [private]
Pointer to mesh of FSI traction elements.
Definition at line 289 of file acoustic_fsi.cc.
Helmholtz_fsi_flux_mesh_pt
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
Mesh * CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_fsi_flux_mesh_pt [private]
Pointer to mesh of Helmholtz FSI flux elements.
Definition at line 295 of file acoustic_fsi.cc.
Helmholtz_mesh_pt
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
TreeBasedRefineableMeshBase * CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_mesh_pt [private]
Pointer to Helmholtz mesh.
Definition at line 292 of file acoustic_fsi.cc.
Helmholtz_outer_boundary_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
Mesh* CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_outer_boundary_mesh_pt [private]
Pointer to mesh containing the ABC elements.
Definition at line 245 of file unstructured_acoustic_fsi.cc.
Helmholtz_outer_boundary_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
HelmholtzDtNMesh<HELMHOLTZ_ELEMENT>* CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Helmholtz_outer_boundary_mesh_pt [private]
Pointer to mesh containing the DtN elements.
Definition at line 298 of file acoustic_fsi.cc.
Lower_inner_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Lower_inner_boundary_id [private]
Boundary ID of lower inner boundary.
Definition at line 257 of file unstructured_acoustic_fsi.cc.
Lower_symmetry_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Lower_symmetry_boundary_id [private]
Boundary ID of lower symmetry boundary.
Definition at line 251 of file unstructured_acoustic_fsi.cc.
Outer_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Outer_boundary_id [private]
Boundary ID of outer boundary.
Definition at line 260 of file unstructured_acoustic_fsi.cc.
Rib_divider_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Rib_divider_boundary_id [private]
Definition at line 263 of file unstructured_acoustic_fsi.cc.
Solid_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
RefineableTriangleMesh<ELASTICITY_ELEMENT>* CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_mesh_pt [private]
Pointer to refineable solid mesh.
Definition at line 230 of file unstructured_acoustic_fsi.cc.
Solid_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
TreeBasedRefineableMeshBase* CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 286 of file acoustic_fsi.cc.
Solid_traction_mesh_pt
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
Mesh* CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Solid_traction_mesh_pt [private]
Pointer to mesh of solid traction elements.
Definition at line 233 of file unstructured_acoustic_fsi.cc.
Trace_file
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
ofstream CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Trace_file [private]
Trace file.
Definition at line 304 of file acoustic_fsi.cc.
Upper_inner_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Upper_inner_boundary_id [private]
Boundary ID of upper inner boundary.
Definition at line 254 of file unstructured_acoustic_fsi.cc.
Upper_symmetry_boundary_id
template<class ELASTICITY_ELEMENT, class HELMHOLTZ_ELEMENT>
unsigned CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::Upper_symmetry_boundary_id [private]
Boundary ID of upper symmetry boundary.
Definition at line 248 of file unstructured_acoustic_fsi.cc.
The documentation for this class was generated from the following files:
acoustic_fsi.cc
unstructured_acoustic_fsi.cc