UnsteadyHeatProblem< ELEMENT > Class Template Reference
UnsteadyHeat problem.
Public Member Functions
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
void set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
~UnsteadyHeatProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after solve (empty)
void actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
void set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void dump_it (ofstream &dump_file)
Dump problem to disk to allow for restart.
void restart (ifstream &restart_file)
Read problem for restart from specified restart file.
Private Attributes
UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function.
Node * Control_node_pt
Pointer to control node at which the solution is documented.
Detailed Description
template<class ELEMENT>
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Definition at line 95 of file two_d_unsteady_heat.cc.
Constructor & Destructor Documentation
UnsteadyHeatProblem() [1/2]
template<class ELEMENT >
UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
Constructor for UnsteadyHeat problem in square domain.
Definition at line 142 of file two_d_unsteady_heat.cc.
References UnsteadyHeatProblem< ELEMENT >::Control_node_pt, ExactSolnForUnsteadyHeat::K, and UnsteadyHeatProblem< ELEMENT >::Source_fct_pt.
Referenced by UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep().
 UnsteadyHeatProblem() [1/2]
template<class ELEMENT>
UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () [inline]
Destructor (empty)
Definition at line 105 of file two_d_unsteady_heat.cc.
UnsteadyHeatProblem() [2/2]
template<class ELEMENT>
UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor.
 UnsteadyHeatProblem() [2/2]
template<class ELEMENT>
UnsteadyHeatProblem< ELEMENT >::~UnsteadyHeatProblem () [inline]
Destructor (empty)
Definition at line 105 of file two_d_unsteady_heat_restarted.cc.
Member Function Documentation
actions_after_implicit_timestep() [1/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () [inline]
Update the problem specs after solve (empty)
Definition at line 114 of file two_d_unsteady_heat.cc.
actions_after_implicit_timestep() [2/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () [inline]
Update the problem specs after solve (empty)
Definition at line 114 of file two_d_unsteady_heat_restarted.cc.
References UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), ExactSolnForUnsteadyHeat::get_exact_u(), ExactSolnForUnsteadyHeat::K, UnsteadyHeatProblem< ELEMENT >::set_initial_condition(), and UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
actions_after_newton_solve() [1/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 108 of file two_d_unsteady_heat.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 108 of file two_d_unsteady_heat_restarted.cc.
actions_before_implicit_timestep() [1/2]
template<class ELEMENT >
void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Actions before timestep: update the domain, then reset the boundary conditions for the current time.
Definition at line 232 of file two_d_unsteady_heat.cc.
References ExactSolnForUnsteadyHeat::get_exact_u().
Referenced by UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep().
actions_before_implicit_timestep() [2/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
actions_before_newton_solve() [1/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 111 of file two_d_unsteady_heat_restarted.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 111 of file two_d_unsteady_heat.cc.
doc_solution() [1/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
doc_solution() [2/2]
template<class ELEMENT >
void UnsteadyHeatProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
Definition at line 331 of file two_d_unsteady_heat.cc.
References UnsteadyHeatProblem< ELEMENT >::Control_node_pt, and ExactSolnForUnsteadyHeat::get_exact_u().
Referenced by UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep(), main(), and UnsteadyHeatProblem< ELEMENT >::set_initial_condition().
dump_it()
template<class ELEMENT >
void UnsteadyHeatProblem< ELEMENT >::dump_it (ofstream & dump_file)
Dump problem to disk to allow for restart.
Dump the solution to disk to allow for restart.
Definition at line 500 of file two_d_unsteady_heat_restarted.cc.
restart()
template<class ELEMENT >
void UnsteadyHeatProblem< ELEMENT >::restart (ifstream & restart_file)
Read problem for restart from specified restart file.
Read solution from disk for restart.
Definition at line 514 of file two_d_unsteady_heat_restarted.cc.
set_initial_condition() [1/2]
template<class ELEMENT>
void UnsteadyHeatProblem< ELEMENT >::set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
set_initial_condition() [2/2]
template<class ELEMENT >
void UnsteadyHeatProblem< ELEMENT >::set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
Set initial condition: Assign previous and current values from exact solution or from restart file.
Set initial condition: Assign previous and current values from exact solution.
Definition at line 265 of file two_d_unsteady_heat.cc.
References UnsteadyHeatProblem< ELEMENT >::doc_solution(), and ExactSolnForUnsteadyHeat::get_exact_u().
Referenced by UnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep(), and main().
Member Data Documentation
Control_node_pt
template<class ELEMENT>
Node * UnsteadyHeatProblem< ELEMENT >::Control_node_pt [private]
Pointer to control node at which the solution is documented.
Definition at line 133 of file two_d_unsteady_heat.cc.
Referenced by UnsteadyHeatProblem< ELEMENT >::doc_solution(), and UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Source_fct_pt
template<class ELEMENT>
UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt UnsteadyHeatProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 130 of file two_d_unsteady_heat.cc.
Referenced by UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
The documentation for this class was generated from the following files:
two_d_unsteady_heat.cc
two_d_unsteady_heat_restarted.cc