UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT > Class Template Reference
Unstructured 3D FSI problem.
Public Member Functions
UnstructuredFSIProblem ()
Constructor:
~UnstructuredFSIProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void create_fluid_traction_elements ()
Create fluid traction elements at inflow.
void create_fsi_traction_elements ()
Create FSI traction elements.
void create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers.
Private Member Functions
void doc_solid_boundary_coordinates (const unsigned &i)
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
unsigned nfluid_inflow_traction_boundary ()
Return total number of mesh boundaries that make up the inflow boundary.
unsigned nfluid_outflow_traction_boundary ()
Return total number of mesh boundaries that make up the outflow boundary.
unsigned nfluid_traction_boundary ()
Return total number of mesh boundaries that make up the in- and outflow boundaries where a traction has to be applied.
unsigned nsolid_fsi_boundary ()
Return total number of mesh boundaries in the solid mesh that make up the FSI interface.
unsigned nfluid_fsi_boundary ()
Return total number of mesh boundaries in the fluid mesh that make up the FSI interface.
unsigned npinned_solid_boundary ()
Return total number of mesh boundaries in the solid mesh where the position is pinned.
Private Attributes
MySolidTetgenMesh< SOLID_ELEMENT > * Solid_mesh_pt
Bulk solid mesh.
Vector< SolidMesh * > Solid_fsi_traction_mesh_pt
Meshes of FSI traction elements.
FluidTetMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Bulk fluid mesh.
Vector< Mesh * > Fluid_traction_mesh_pt
Meshes of fluid traction elements that apply pressure at in/outflow.
Vector< SolidMesh * > Lagrange_multiplier_mesh_pt
Meshes of Lagrange multiplier elements.
Vector< MeshAsGeomObject * > Solid_fsi_boundary_pt
GeomObject incarnations of the FSI boundary in the solid mesh.
Vector< unsigned > Pinned_solid_boundary_id
IDs of solid mesh boundaries where displacements are pinned.
Vector< unsigned > Solid_fsi_boundary_id
IDs of solid mesh boundaries which make up the FSI interface.
Vector< unsigned > Inflow_boundary_id
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Vector< unsigned > Outflow_boundary_id
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Vector< unsigned > Fluid_fsi_boundary_id
IDs of fluid mesh boundaries which make up the FSI interface.
Detailed Description
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
class UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Unstructured 3D FSI problem.
Definition at line 216 of file unstructured_three_d_fsi.cc.
Constructor & Destructor Documentation
UnstructuredFSIProblem()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem ()
Constructor:
Constructor for unstructured 3D FSI problem. IDs of solid mesh boundaries where displacements are pinned
Definition at line 322 of file unstructured_three_d_fsi.cc.
References Global_Parameters::Constitutive_law_pt, UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), and Global_Parameters::Re.
 UnstructuredFSIProblem()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~UnstructuredFSIProblem () [inline]
Destructor (empty)
Definition at line 225 of file unstructured_three_d_fsi.cc.
Member Function Documentation
create_fluid_traction_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements ()
Create fluid traction elements at inflow.
Create fluid traction elements.
Definition at line 810 of file unstructured_three_d_fsi.cc.
References UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), Global_Parameters::prescribed_inflow_traction(), and Global_Parameters::prescribed_outflow_traction().
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements().
create_fsi_traction_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements ()
Create FSI traction elements.
Definition at line 709 of file unstructured_three_d_fsi.cc.
References UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), and Global_Parameters::Q.
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem().
create_lagrange_multiplier_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion for the pseudo-solid fluid mesh by Lagrange multipliers.
Create elements that impose the prescribed boundary displacement for the pseudo-solid fluid mesh
Definition at line 756 of file unstructured_three_d_fsi.cc.
References UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements().
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements().
doc_solid_boundary_coordinates()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates (const unsigned & i) [private]
Sanity check: Doc boundary coordinates on i-th solid FSI interface.
Doc boundary coordinates of i-th solid FSI boundary.
Definition at line 882 of file unstructured_three_d_fsi.cc.
References UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution().
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements().
doc_solution()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 939 of file unstructured_three_d_fsi.cc.
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), and main().
nfluid_fsi_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_fsi_boundary () [inline], [private]
Return total number of mesh boundaries in the fluid mesh that make up the FSI interface.
Definition at line 268 of file unstructured_three_d_fsi.cc.
nfluid_inflow_traction_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_inflow_traction_boundary () [inline], [private]
Return total number of mesh boundaries that make up the inflow boundary.
Definition at line 248 of file unstructured_three_d_fsi.cc.
nfluid_outflow_traction_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_outflow_traction_boundary () [inline], [private]
Return total number of mesh boundaries that make up the outflow boundary.
Definition at line 253 of file unstructured_three_d_fsi.cc.
nfluid_traction_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nfluid_traction_boundary () [inline], [private]
Return total number of mesh boundaries that make up the in- and outflow boundaries where a traction has to be applied.
Definition at line 258 of file unstructured_three_d_fsi.cc.
npinned_solid_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::npinned_solid_boundary () [inline], [private]
Return total number of mesh boundaries in the solid mesh where the position is pinned.
Definition at line 273 of file unstructured_three_d_fsi.cc.
nsolid_fsi_boundary()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
unsigned UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::nsolid_fsi_boundary () [inline], [private]
Return total number of mesh boundaries in the solid mesh that make up the FSI interface.
Definition at line 263 of file unstructured_three_d_fsi.cc.
Member Data Documentation
Fluid_fsi_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_fsi_boundary_id [private]
IDs of fluid mesh boundaries which make up the FSI interface.
Definition at line 312 of file unstructured_three_d_fsi.cc.
Fluid_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
FluidTetMesh<FLUID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt [private]
Bulk fluid mesh.
Definition at line 285 of file unstructured_three_d_fsi.cc.
Fluid_traction_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<Mesh*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_traction_mesh_pt [private]
Meshes of fluid traction elements that apply pressure at in/outflow.
Definition at line 288 of file unstructured_three_d_fsi.cc.
Inflow_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Inflow_boundary_id [private]
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Definition at line 305 of file unstructured_three_d_fsi.cc.
Lagrange_multiplier_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<SolidMesh*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Lagrange_multiplier_mesh_pt [private]
Meshes of Lagrange multiplier elements.
Definition at line 291 of file unstructured_three_d_fsi.cc.
Outflow_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Outflow_boundary_id [private]
IDs of fluid mesh boundaries along which inflow boundary conditions are applied.
Definition at line 309 of file unstructured_three_d_fsi.cc.
Pinned_solid_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Pinned_solid_boundary_id [private]
IDs of solid mesh boundaries where displacements are pinned.
Definition at line 298 of file unstructured_three_d_fsi.cc.
Solid_fsi_boundary_id
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<unsigned> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_boundary_id [private]
IDs of solid mesh boundaries which make up the FSI interface.
Definition at line 301 of file unstructured_three_d_fsi.cc.
Solid_fsi_boundary_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<MeshAsGeomObject*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_boundary_pt [private]
GeomObject incarnations of the FSI boundary in the solid mesh.
Definition at line 295 of file unstructured_three_d_fsi.cc.
Solid_fsi_traction_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
Vector<SolidMesh*> UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_fsi_traction_mesh_pt [private]
Meshes of FSI traction elements.
Definition at line 282 of file unstructured_three_d_fsi.cc.
Solid_mesh_pt
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
MySolidTetgenMesh<SOLID_ELEMENT>* UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt [private]
Bulk solid mesh.
Definition at line 279 of file unstructured_three_d_fsi.cc.
The documentation for this class was generated from the following file:
unstructured_three_d_fsi.cc