PoissonProblem< ELEMENT > Class Template Reference
Public Member Functions
PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~PoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~PoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt, const unsigned &nel_1d, const bool &mess_up_order)
Constructor: Pass pointer to source function and flag to indicate if order of elements should be messed up. nel_1d is the number of elements along the 1d mesh edges -- total number of elements is nel_1d x nel_1d.
~PoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Private Attributes
PoissonEquations< 2 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT>
class PoissonProblem< ELEMENT >
2D Poisson problem on rectangular domain, discretised with 2D QPoisson elements. The specific type of element is specified via the template parameter.
Definition at line 88 of file two_d_poisson.cc.
Constructor & Destructor Documentation
PoissonProblem() [1/3]
template<class ELEMENT >
PoissonProblem< ELEMENT >::PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
Constructor for Poisson problem: Pass pointer to source function.
Definition at line 125 of file two_d_poisson.cc.
References PoissonProblem< ELEMENT >::Source_fct_pt.
Referenced by PoissonProblem< ELEMENT >::actions_after_newton_solve().
 PoissonProblem() [1/3]
template<class ELEMENT>
PoissonProblem< ELEMENT >::~PoissonProblem () [inline]
Destructor (empty)
Definition at line 97 of file two_d_poisson.cc.
PoissonProblem() [2/3]
template<class ELEMENT>
PoissonProblem< ELEMENT >::PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
 PoissonProblem() [2/3]
template<class ELEMENT>
PoissonProblem< ELEMENT >::~PoissonProblem () [inline]
Destructor (empty)
Definition at line 99 of file two_d_poisson2.cc.
PoissonProblem() [3/3]
template<class ELEMENT >
PoissonProblem< ELEMENT >::PoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt, const unsigned & nel_1d, const bool & mess_up_order)
Constructor: Pass pointer to source function and flag to indicate if order of elements should be messed up. nel_1d is the number of elements along the 1d mesh edges -- total number of elements is nel_1d x nel_1d.
Constructor for Poisson problem: Pass pointer to source function and a flag that specifies if the order of the elements should be messed up. nel_1d is the number of elements along the 1d mesh edges -- total number of elements is nel_1d x nel_1d.
Definition at line 132 of file two_d_poisson_compare_solvers.cc.
References PoissonProblem< ELEMENT >::actions_before_newton_solve(), PoissonProblem< ELEMENT >::doc_solution(), TanhSolnForPoisson::get_exact_u(), and PoissonProblem< ELEMENT >::Source_fct_pt.
 PoissonProblem() [3/3]
template<class ELEMENT>
PoissonProblem< ELEMENT >::~PoissonProblem () [inline]
Destructor (empty)
Definition at line 101 of file two_d_poisson_compare_solvers.cc.
Member Function Documentation
actions_after_newton_solve() [1/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 104 of file two_d_poisson.cc.
actions_after_newton_solve() [2/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 106 of file two_d_poisson2.cc.
References PoissonProblem< ELEMENT >::actions_before_newton_solve(), PoissonProblem< ELEMENT >::doc_solution(), TanhSolnForPoisson::get_exact_u(), and PoissonProblem< ELEMENT >::PoissonProblem().
actions_after_newton_solve() [3/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 108 of file two_d_poisson_compare_solvers.cc.
References PoissonProblem< ELEMENT >::PoissonProblem().
actions_before_newton_solve() [1/3]
template<class ELEMENT >
void PoissonProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Update the problem specs before solve: (Re-)set boundary conditions to the values from the exact solution.
Definition at line 187 of file two_d_poisson.cc.
References TanhSolnForPoisson::get_exact_u().
Referenced by PoissonProblem< ELEMENT >::actions_after_newton_solve(), and PoissonProblem< ELEMENT >::PoissonProblem().
actions_before_newton_solve() [2/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
actions_before_newton_solve() [3/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
doc_solution() [1/3]
template<class ELEMENT >
void PoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 225 of file two_d_poisson.cc.
References TanhSolnForPoisson::get_exact_u().
Referenced by PoissonProblem< ELEMENT >::actions_after_newton_solve(), main(), PoissonProblem< ELEMENT >::PoissonProblem(), and run().
doc_solution() [2/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
doc_solution() [3/3]
template<class ELEMENT>
void PoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Member Data Documentation
Source_fct_pt
template<class ELEMENT>
PoissonEquations< 2 >::PoissonSourceFctPt PoissonProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 113 of file two_d_poisson.cc.
Referenced by PoissonProblem< ELEMENT >::PoissonProblem().
The documentation for this class was generated from the following files:
two_d_poisson.cc
two_d_poisson2.cc
two_d_poisson_compare_solvers.cc