ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT > Class Template Reference
Public Member Functions
ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
double alpha ()
Return the adsorption number.
double k ()
Return the solubility nubmer.
double *& alpha_pt ()
Access function for pointer to adsorption number.
double *& k_pt ()
Access function for pointer to solubility number.
void output (std::ostream &outfile, const unsigned &n_plot)
Overload the output function.
Protected Member Functions
double interpolated_C_bulk (const Vector< double > &s)
Get the bulk surfactant concentration.
double dc_bulk_dt_surface (const unsigned &l) const
The time derivative of the bulk surface concentration.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifdS_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop.
Private Attributes
double * Alpha_pt
Pointer to adsorption number.
double * K_pt
Pointer to solubility number.
unsigned C_bulk_index
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >
Interface class to handle the mass transport between bulk and surface as well as the surfactant transport along the
Definition at line 146 of file rayleigh_instability_soluble_surfactant.cc.
Constructor & Destructor Documentation
ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement()
template<class ELEMENT>
ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor that passes the bulk element and face index down to the underlying
Definition at line 332 of file rayleigh_instability_soluble_surfactant.cc.
Member Function Documentation
add_additional_residual_contributions_interface()
template<class ELEMENT>
void ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag, const Shape & psif, const DShape & dpsifds, const DShape & dpsifdS, const DShape & dpsifdS_div, const Vector< double > & s, const Vector< double > & interpolated_x, const Vector< double > & interpolated_n, const double & W, const double & J) [inline], [protected], [virtual]
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop.
Reimplemented from oomph::FluidInterfaceElement.
Definition at line 216 of file rayleigh_instability_soluble_surfactant.cc.
References oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >::add_additional_residual_contributions_interface().
alpha()
template<class ELEMENT>
double ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::alpha () [inline]
Return the adsorption number.
Definition at line 347 of file rayleigh_instability_soluble_surfactant.cc.
alpha_pt()
template<class ELEMENT>
double* & ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::alpha_pt () [inline]
Access function for pointer to adsorption number.
Definition at line 353 of file rayleigh_instability_soluble_surfactant.cc.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface().
dc_bulk_dt_surface()
template<class ELEMENT>
double ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::dc_bulk_dt_surface (const unsigned & l) const [inline], [protected]
The time derivative of the bulk surface concentration.
Definition at line 189 of file rayleigh_instability_soluble_surfactant.cc.
interpolated_C_bulk()
template<class ELEMENT>
double ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::interpolated_C_bulk (const Vector< double > & s) [inline], [protected]
Get the bulk surfactant concentration.
Definition at line 162 of file rayleigh_instability_soluble_surfactant.cc.
k()
template<class ELEMENT>
double ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::k () [inline]
Return the solubility nubmer.
Definition at line 350 of file rayleigh_instability_soluble_surfactant.cc.
k_pt()
template<class ELEMENT>
double* & ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::k_pt () [inline]
Access function for pointer to solubility number.
Definition at line 356 of file rayleigh_instability_soluble_surfactant.cc.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface().
output()
template<class ELEMENT>
void ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Overload the output function.
Definition at line 359 of file rayleigh_instability_soluble_surfactant.cc.
Member Data Documentation
Alpha_pt
template<class ELEMENT>
double* ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::Alpha_pt [private]
Pointer to adsorption number.
Definition at line 151 of file rayleigh_instability_soluble_surfactant.cc.
C_bulk_index
template<class ELEMENT>
unsigned ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::C_bulk_index [private]
Storage for the index at which the bulk concentration is stored
Definition at line 157 of file rayleigh_instability_soluble_surfactant.cc.
K_pt
template<class ELEMENT>
double* ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::K_pt [private]
Pointer to solubility number.
Definition at line 153 of file rayleigh_instability_soluble_surfactant.cc.
The documentation for this class was generated from the following file:
rayleigh_instability_soluble_surfactant.cc