RefineableYoungLaplaceProblem< ELEMENT > Class Template Reference
Public Member Functions
RefineableYoungLaplaceProblem ()
Constructor:
~RefineableYoungLaplaceProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Empty.
void actions_after_newton_solve ()
Update the problem after solve: Empty.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of contact angle elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of contact angle elements.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
RefineableYoungLaplaceProblem ()
Constructor:
~RefineableYoungLaplaceProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Empty.
void actions_after_newton_solve ()
Update the problem after solve: Empty.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of contact angle elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of contact angle elements.
void increment_parameters ()
Increase the problem parameters before each solve.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
RefineableYoungLaplaceProblem ()
Constructor:
~RefineableYoungLaplaceProblem ()
Destructor (empty)
void actions_before_solve ()
Update the problem specs before solve: Empty.
void actions_after_solve ()
Update the problem after solve: Empty.
void increment_parameters ()
Increment problem parameters.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
Private Member Functions
void create_contact_angle_elements (const unsigned &b)
Create YoungLaplace contact angle elements on the b-th boundary of the bulk mesh and add them to contact angle mesh.
void delete_contact_angle_elements ()
Delete contact angle elements.
void create_contact_angle_elements (const unsigned &b)
Create YoungLaplace contact angle elements on the b-th boundary of the bulk mesh and add them to contact angle mesh.
void delete_contact_angle_elements ()
Delete contact angle elements.
Private Attributes
RefineableRectangularQuadMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Contact_angle_mesh_pt
Pointer to the contact angle mesh.
Mesh * Height_control_mesh_pt
Pointer to mesh containing the height control element.
Node * Control_node_pt
Node at which the height (displacement along spine) is controlled/doced.
Data * Kappa_pt
Pointer to Data object that stores the prescribed curvature.
HeightControlElement * Height_control_element_pt
Pointer to height control element.
GeomObject * Boundary_pt
Pointer to GeomObject that specifies the domain bondary.
RefineableQuarterCircleSectorMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Detailed Description
template<class ELEMENT>
class RefineableYoungLaplaceProblem< ELEMENT >
2D RefineableYoungLaplace problem on rectangular domain, discretised with 2D QRefineableYoungLaplace elements. The specific type of element is specified via the template parameter.
2D RefineableYoungLaplace problem on a circle sector, discretised with 2D QRefineableYoungLaplace elements. The specific type of element is specified via the template parameter.
Definition at line 142 of file refineable_t_junction.cc.
Constructor & Destructor Documentation
RefineableYoungLaplaceProblem() [1/3]
template<class ELEMENT >
RefineableYoungLaplaceProblem< ELEMENT >::RefineableYoungLaplaceProblem ()
Constructor:
Constructor for RefineableYoungLaplace problem.
Definition at line 230 of file refineable_t_junction.cc.
References GlobalParameters::Controlled_height, GlobalParameters::Cos_gamma, GlobalParameters::Kappa_pt, GlobalParameters::L_x, GlobalParameters::L_y, GlobalParameters::spine_base_function(), and GlobalParameters::spine_function().
 RefineableYoungLaplaceProblem() [1/3]
template<class ELEMENT>
RefineableYoungLaplaceProblem< ELEMENT >::~RefineableYoungLaplaceProblem () [inline]
Destructor (empty)
Definition at line 151 of file refineable_t_junction.cc.
RefineableYoungLaplaceProblem() [2/3]
template<class ELEMENT>
RefineableYoungLaplaceProblem< ELEMENT >::RefineableYoungLaplaceProblem ()
Constructor:
 RefineableYoungLaplaceProblem() [2/3]
template<class ELEMENT>
RefineableYoungLaplaceProblem< ELEMENT >::~RefineableYoungLaplaceProblem () [inline]
Destructor (empty)
Definition at line 63 of file refineable_young_laplace.cc.
RefineableYoungLaplaceProblem() [3/3]
template<class ELEMENT>
RefineableYoungLaplaceProblem< ELEMENT >::RefineableYoungLaplaceProblem ()
Constructor:
 RefineableYoungLaplaceProblem() [3/3]
template<class ELEMENT>
RefineableYoungLaplaceProblem< ELEMENT >::~RefineableYoungLaplaceProblem () [inline]
Destructor (empty)
Definition at line 66 of file spherical_cap_in_cylinder.cc.
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Rebuild the mesh of contact angle elements.
Definition at line 83 of file refineable_young_laplace.cc.
References GlobalParameters::Case, GlobalParameters::Cos_gamma, and GlobalParameters::T_junction_with_nonzero_contact_angle.
actions_after_adapt() [2/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Rebuild the mesh of contact angle elements.
Definition at line 171 of file refineable_t_junction.cc.
References GlobalParameters::Cos_gamma.
actions_after_newton_solve() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve: Empty.
Definition at line 69 of file refineable_young_laplace.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve: Empty.
Definition at line 157 of file refineable_t_junction.cc.
actions_after_solve()
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_after_solve () [inline]
Update the problem after solve: Empty.
Definition at line 72 of file spherical_cap_in_cylinder.cc.
actions_before_adapt() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Wipe the mesh of contact angle elements.
Definition at line 72 of file refineable_young_laplace.cc.
actions_before_adapt() [2/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Wipe the mesh of contact angle elements.
Definition at line 160 of file refineable_t_junction.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Empty.
Definition at line 66 of file refineable_young_laplace.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Empty.
Definition at line 154 of file refineable_t_junction.cc.
actions_before_solve()
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::actions_before_solve () [inline]
Update the problem specs before solve: Empty.
Definition at line 69 of file spherical_cap_in_cylinder.cc.
create_contact_angle_elements() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::create_contact_angle_elements (const unsigned & b) [private]
Create YoungLaplace contact angle elements on the b-th boundary of the bulk mesh and add them to contact angle mesh.
create_contact_angle_elements() [2/2]
template<class ELEMENT >
void RefineableYoungLaplaceProblem< ELEMENT >::create_contact_angle_elements (const unsigned & b) [private]
Create YoungLaplace contact angle elements on the b-th boundary of the bulk mesh and add them to contact angle mesh.
Create YoungLaplace contact angle elements on the b-th boundary of the bulk mesh and add them to the contact angle mesh
Definition at line 377 of file refineable_t_junction.cc.
delete_contact_angle_elements() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::delete_contact_angle_elements () [private]
Delete contact angle elements.
delete_contact_angle_elements() [2/2]
template<class ELEMENT >
void RefineableYoungLaplaceProblem< ELEMENT >::delete_contact_angle_elements () [private]
Delete contact angle elements.
Delete YoungLaplace contact angle elements.
Definition at line 409 of file refineable_t_junction.cc.
doc_solution() [1/3]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
doc_solution() [2/3]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
doc_solution() [3/3]
template<class ELEMENT >
void RefineableYoungLaplaceProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to and the trace file.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 434 of file refineable_t_junction.cc.
References GlobalParameters::Kappa_pt.
Referenced by RefineableYoungLaplaceProblem< ELEMENT >::increment_parameters(), main(), and run_it().
increment_parameters() [1/2]
template<class ELEMENT>
void RefineableYoungLaplaceProblem< ELEMENT >::increment_parameters ()
Increment problem parameters.
increment_parameters() [2/2]
template<class ELEMENT >
void RefineableYoungLaplaceProblem< ELEMENT >::increment_parameters ()
Increase the problem parameters before each solve.
Update (increase/decrease) parameters.
Definition at line 395 of file refineable_young_laplace.cc.
References GlobalParameters::Case, GlobalParameters::Controlled_height, GlobalParameters::Controlled_height_increment, RefineableYoungLaplaceProblem< ELEMENT >::doc_solution(), GlobalParameters::get_exact_kappa(), GlobalParameters::Kappa_increment, GlobalParameters::Kappa_pt, GlobalParameters::T_junction_with_nonzero_contact_angle, and GlobalParameters::Use_height_control.
Referenced by main(), and run_it().
Member Data Documentation
Boundary_pt
template<class ELEMENT>
GeomObject* RefineableYoungLaplaceProblem< ELEMENT >::Boundary_pt [private]
Pointer to GeomObject that specifies the domain bondary.
Definition at line 84 of file spherical_cap_in_cylinder.cc.
Bulk_mesh_pt [1/2]
template<class ELEMENT>
RefineableQuarterCircleSectorMesh<ELEMENT>* RefineableYoungLaplaceProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 87 of file spherical_cap_in_cylinder.cc.
Bulk_mesh_pt [2/2]
template<class ELEMENT>
RefineableRectangularQuadMesh< ELEMENT > * RefineableYoungLaplaceProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 209 of file refineable_t_junction.cc.
Contact_angle_mesh_pt
template<class ELEMENT>
Mesh * RefineableYoungLaplaceProblem< ELEMENT >::Contact_angle_mesh_pt [private]
Pointer to the contact angle mesh.
Definition at line 212 of file refineable_t_junction.cc.
Control_node_pt
template<class ELEMENT>
Node * RefineableYoungLaplaceProblem< ELEMENT >::Control_node_pt [private]
Node at which the height (displacement along spine) is controlled/doced.
Definition at line 218 of file refineable_t_junction.cc.
Height_control_element_pt
template<class ELEMENT>
HeightControlElement * RefineableYoungLaplaceProblem< ELEMENT >::Height_control_element_pt [private]
Pointer to height control element.
Definition at line 138 of file refineable_young_laplace.cc.
Height_control_mesh_pt
template<class ELEMENT>
Mesh * RefineableYoungLaplaceProblem< ELEMENT >::Height_control_mesh_pt [private]
Pointer to mesh containing the height control element.
Definition at line 215 of file refineable_t_junction.cc.
Kappa_pt
template<class ELEMENT>
Data* RefineableYoungLaplaceProblem< ELEMENT >::Kappa_pt [private]
Pointer to Data object that stores the prescribed curvature.
Definition at line 221 of file refineable_t_junction.cc.
The documentation for this class was generated from the following files:
refineable_t_junction.cc
refineable_young_laplace.cc
spherical_cap_in_cylinder.cc