ShellProblem< ELEMENT > Class Template Reference
Public Member Functions
ShellProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor.
ShellMesh< ELEMENT > * mesh_pt ()
Overload Access function for the mesh.
void actions_after_newton_solve ()
Actions after solve empty.
void actions_before_newton_solve ()
Actions before solve empty.
void solve ()
ShellProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor.
~ShellProblem ()
Destructor: delete mesh, geometric object.
ShellMesh< ELEMENT > * mesh_pt ()
Overload Access function for the mesh.
void actions_after_newton_solve ()
Actions after solve empty.
void actions_before_newton_solve ()
Actions before solve empty.
void solve ()
Private Attributes
GeomObject * Undeformed_midplane_pt
Pointer to GeomObject that specifies the undeformed midplane.
Node * Trace_node_pt
First trace node.
Node * Trace_node2_pt
Second trace node.
Detailed Description
template<class ELEMENT>
class ShellProblem< ELEMENT >
Definition at line 218 of file clamped_shell.cc.
Constructor & Destructor Documentation
ShellProblem() [1/2]
template<class ELEMENT >
ShellProblem< ELEMENT >::ShellProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor.
Definition at line 259 of file clamped_shell.cc.
References ShellMesh< ELEMENT >::assign_undeformed_positions(), Global_Physical_Variables::Pext_data_pt, Global_Physical_Variables::Prescribed_y, and Global_Physical_Variables::press_load().
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve().
ShellProblem() [2/2]
template<class ELEMENT>
ShellProblem< ELEMENT >::ShellProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor.
 ShellProblem()
template<class ELEMENT>
ShellProblem< ELEMENT >::~ShellProblem () [inline]
Destructor: delete mesh, geometric object.
Definition at line 329 of file clamped_shell_with_arclength_cont.cc.
References ShellProblem< ELEMENT >::Undeformed_midplane_pt.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT>
void ShellProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve empty.
Definition at line 232 of file clamped_shell.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT>
void ShellProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve empty.
Definition at line 341 of file clamped_shell_with_arclength_cont.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT>
void ShellProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve empty.
Definition at line 235 of file clamped_shell.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT>
void ShellProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve empty.
Definition at line 344 of file clamped_shell_with_arclength_cont.cc.
References Global_Physical_Variables::external_pressure(), ShellProblem< ELEMENT >::mesh_pt(), Global_Physical_Variables::Pext_data_pt, Global_Physical_Variables::Prescribed_y, Global_Physical_Variables::press_load(), ShellProblem< ELEMENT >::ShellProblem(), ShellProblem< ELEMENT >::solve(), ShellProblem< ELEMENT >::Trace_node2_pt, ShellProblem< ELEMENT >::Trace_node_pt, and ShellProblem< ELEMENT >::Undeformed_midplane_pt.
mesh_pt() [1/2]
template<class ELEMENT>
ShellMesh<ELEMENT>* ShellProblem< ELEMENT >::mesh_pt () [inline]
Overload Access function for the mesh.
Definition at line 228 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve().
mesh_pt() [2/2]
template<class ELEMENT>
ShellMesh<ELEMENT>* ShellProblem< ELEMENT >::mesh_pt () [inline]
Overload Access function for the mesh.
Definition at line 337 of file clamped_shell_with_arclength_cont.cc.
solve() [1/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::solve ()
Definition at line 489 of file clamped_shell.cc.
References Global_Physical_Variables::external_pressure(), Global_Physical_Variables::Pcos, and Global_Physical_Variables::Prescribed_y.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), and main().
solve() [2/2]
template<class ELEMENT>
void ShellProblem< ELEMENT >::solve ()
Member Data Documentation
Trace_node2_pt
template<class ELEMENT>
Node * ShellProblem< ELEMENT >::Trace_node2_pt [private]
Second trace node.
Definition at line 249 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve().
Trace_node_pt
template<class ELEMENT>
Node * ShellProblem< ELEMENT >::Trace_node_pt [private]
First trace node.
Definition at line 246 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve().
Undeformed_midplane_pt
template<class ELEMENT>
GeomObject * ShellProblem< ELEMENT >::Undeformed_midplane_pt [private]
Pointer to GeomObject that specifies the undeformed midplane.
Definition at line 243 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), and ShellProblem< ELEMENT >::~ShellProblem().
The documentation for this class was generated from the following files:
clamped_shell.cc
clamped_shell_with_arclength_cont.cc