Global_Physical_Variables Namespace Reference
Global variables that represent physical properties.
Functions
double external_pressure ()
Return a reference to the external pressure load on the elastic tube.
void press_load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function, normal pressure loading.
Variables
double Prescribed_y = 1.0
Prescribed position of control point.
Data * Pext_data_pt
Pointer to pressure load (stored in Data so it can become an unknown in the problem when displacement control is used.
double Pcos =1.0
Perturbation pressure.
Detailed Description
Global variables that represent physical properties.
Function Documentation
external_pressure()
double Global_Physical_Variables::external_pressure ()
Return a reference to the external pressure load on the elastic tube.
Definition at line 70 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), press_load(), and ShellProblem< ELEMENT >::solve().
press_load()
void Global_Physical_Variables::press_load (const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load)
Load function, normal pressure loading.
Definition at line 75 of file clamped_shell.cc.
References external_pressure().
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), and ShellProblem< ELEMENT >::ShellProblem().
Variable Documentation
Pcos
double Global_Physical_Variables::Pcos =1.0
Perturbation pressure.
Definition at line 65 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::solve().
Pext_data_pt
Data * Global_Physical_Variables::Pext_data_pt
Pointer to pressure load (stored in Data so it can become an unknown in the problem when displacement control is used.
Definition at line 62 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), and ShellProblem< ELEMENT >::ShellProblem().
Prescribed_y
double Global_Physical_Variables::Prescribed_y = 1.0
Prescribed position of control point.
Definition at line 58 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::actions_before_newton_solve(), ShellProblem< ELEMENT >::ShellProblem(), and ShellProblem< ELEMENT >::solve().