RayleighTractionProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Rayleigh-type problem: 2D channel flow driven by traction bc.
Public Member Functions
RayleighTractionProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Problem constructor.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void actions_before_implicit_timestep ()
Actions before timestep (empty)
void unsteady_run (DocInfo &doc_info)
Run an unsteady simulation.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
void create_traction_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
Create traction elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Private Attributes
RectangularQuadMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Surface_mesh_pt
Pointer to the `surface` mesh.
ofstream Trace_file
Trace file.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class RayleighTractionProblem< ELEMENT, TIMESTEPPER >
Rayleigh-type problem: 2D channel flow driven by traction bc.
Definition at line 129 of file rayleigh_traction_channel.cc.
Constructor & Destructor Documentation
RayleighTractionProblem()
template<class ELEMENT , class TIMESTEPPER >
RayleighTractionProblem< ELEMENT, TIMESTEPPER >::RayleighTractionProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Problem constructor.
Constructor: Pass number of elements in x and y directions and lengths
Definition at line 184 of file rayleigh_traction_channel.cc.
References ExactSoln::prescribed_traction(), Global_Parameters::Re, and Global_Parameters::ReSt.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT, class TIMESTEPPER>
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 142 of file rayleigh_traction_channel.cc.
actions_before_implicit_timestep()
template<class ELEMENT, class TIMESTEPPER>
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () [inline]
Actions before timestep (empty)
Definition at line 145 of file rayleigh_traction_channel.cc.
actions_before_newton_solve()
template<class ELEMENT, class TIMESTEPPER>
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 139 of file rayleigh_traction_channel.cc.
create_traction_elements()
template<class ELEMENT , class TIMESTEPPER >
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::create_traction_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt)
Create traction elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Create Navier-Stokes traction elements on the b-th boundary of the Mesh object pointed to by bulk_mesh_pt and add the elements to the Mesh object pointeed to by surface_mesh_pt.
Definition at line 429 of file rayleigh_traction_channel.cc.
Referenced by RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution().
doc_solution()
template<class ELEMENT , class TIMESTEPPER >
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 343 of file rayleigh_traction_channel.cc.
References RayleighTractionProblem< ELEMENT, TIMESTEPPER >::create_traction_elements(), and ExactSoln::get_exact_u().
set_initial_condition()
template<class ELEMENT , class TIMESTEPPER >
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
Set initial condition: Assign previous and current values from exact solution.
Definition at line 276 of file rayleigh_traction_channel.cc.
References ExactSoln::get_exact_u().
unsteady_run()
template<class ELEMENT , class TIMESTEPPER >
void RayleighTractionProblem< ELEMENT, TIMESTEPPER >::unsteady_run (DocInfo & doc_info)
Run an unsteady simulation.
Unsteady run...
Definition at line 462 of file rayleigh_traction_channel.cc.
References Global_Parameters::Impulsive_start_flag, and Global_Parameters::Long_run_flag.
Referenced by main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT, class TIMESTEPPER>
RectangularQuadMesh<ELEMENT>* RayleighTractionProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 167 of file rayleigh_traction_channel.cc.
Surface_mesh_pt
template<class ELEMENT, class TIMESTEPPER>
Mesh* RayleighTractionProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt [private]
Pointer to the `surface` mesh.
Definition at line 170 of file rayleigh_traction_channel.cc.
Trace_file
template<class ELEMENT, class TIMESTEPPER>
ofstream RayleighTractionProblem< ELEMENT, TIMESTEPPER >::Trace_file [private]
Trace file.
Definition at line 173 of file rayleigh_traction_channel.cc.
The documentation for this class was generated from the following file:
rayleigh_traction_channel.cc