oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT > Class Template Reference
Collapsible channel mesh with algebraic node update.
#include <my_alg_channel_mesh.h>
Public Member Functions
MyAlgebraicCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment, and pointer to TimeStepper (defaults to the default timestepper, Steady).
MyAlgebraicCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, CollapsibleChannelDomain::BLSquashFctPt bl_squash_function_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment, function pointer to `boundary layer squash function`, and pointer to TimeStepper (defaults to the default timestepper, Steady).
virtual ~MyAlgebraicCollapsibleChannelMesh ()
Destructor: empty.
CollapsibleChannelDomain::BLSquashFctPt & bl_squash_fct_pt ()
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. This (deliberately broken) function overloads the one in the CollapsibleChannelMesh base class.
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
Update nodal position at time level t (t=0: present; t>0: previous)
void update_node_update (AlgebraicNode *&node_pt)
Update the geometric references that are used to update node after mesh adaptation. Empty -- no update of node update required.
Protected Member Functions
void setup_algebraic_node_update ()
Function to setup the algebraic node update.
Protected Attributes
CollapsibleChannelDomain::BLSquashFctPt Dummy_fct_pt
Dummy function pointer.
Detailed Description
template<class ELEMENT>
class oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >
Collapsible channel mesh with algebraic node update.
Definition at line 52 of file my_alg_channel_mesh.h.
Constructor & Destructor Documentation
MyAlgebraicCollapsibleChannelMesh() [1/2]
template<class ELEMENT>
oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::MyAlgebraicCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment, and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 64 of file my_alg_channel_mesh.h.
References oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update().
MyAlgebraicCollapsibleChannelMesh() [2/2]
template<class ELEMENT>
oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::MyAlgebraicCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, CollapsibleChannelDomain::BLSquashFctPt bl_squash_function_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment, function pointer to `boundary layer squash function`, and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 92 of file my_alg_channel_mesh.h.
References oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update().
 MyAlgebraicCollapsibleChannelMesh()
template<class ELEMENT>
virtual oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::~MyAlgebraicCollapsibleChannelMesh () [inline], [virtual]
Destructor: empty.
Definition at line 122 of file my_alg_channel_mesh.h.
Member Function Documentation
algebraic_node_update()
template<class ELEMENT >
void oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt)
Update nodal position at time level t (t=0: present; t>0: previous)
Perform algebraic mesh update at time level t (t=0: present; t>0: previous)
Definition at line 359 of file my_alg_channel_mesh.h.
Referenced by oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt().
bl_squash_fct_pt()
template<class ELEMENT>
CollapsibleChannelDomain::BLSquashFctPt& oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt () [inline]
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. This (deliberately broken) function overloads the one in the CollapsibleChannelMesh base class.
Definition at line 130 of file my_alg_channel_mesh.h.
References oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::algebraic_node_update(), and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::Dummy_fct_pt.
setup_algebraic_node_update()
template<class ELEMENT >
void oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update () [protected]
Function to setup the algebraic node update.
Setup algebraic mesh update -- assumes that mesh has initially been set up with the wall in its undeformed position.
Definition at line 272 of file my_alg_channel_mesh.h.
Referenced by oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::MyAlgebraicCollapsibleChannelMesh(), and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::update_node_update().
update_node_update()
template<class ELEMENT>
void oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) [inline]
Update the geometric references that are used to update node after mesh adaptation. Empty -- no update of node update required.
Definition at line 156 of file my_alg_channel_mesh.h.
References oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update().
Member Data Documentation
Dummy_fct_pt
template<class ELEMENT>
CollapsibleChannelDomain::BLSquashFctPt oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::Dummy_fct_pt [protected]
Dummy function pointer.
Definition at line 165 of file my_alg_channel_mesh.h.
Referenced by oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt().
The documentation for this class was generated from the following file:
my_alg_channel_mesh.h