oomph::GeneralPurposeBlockPreconditioner< MATRIX > Class Template Reference
#include <general_purpose_block_preconditioners.h>
Public Types
typedef Preconditioner *(* SubsidiaryPreconditionerFctPt) ()
typedef for a function that allows other preconditioners to be employed to solve the subsidiary linear systems. The function should return a pointer to the required subsidiary preconditioner generated using new. This preconditioner is responsible for the destruction of the subsidiary preconditioners.
Public Member Functions
GeneralPurposeBlockPreconditioner ()
constructor
virtual ~GeneralPurposeBlockPreconditioner ()
virtual void clean_up_memory ()
??ds I think clean_up_memory is supposed to clear out any stuff that doesn't need to be stored between solves. Call clean up on any non-null subsidiary preconditioners.
GeneralPurposeBlockPreconditioner (const GeneralPurposeBlockPreconditioner &)
Broken copy constructor.
void operator= (const GeneralPurposeBlockPreconditioner &)
Broken assignment operator.
void set_subsidiary_preconditioner_function (SubsidiaryPreconditionerFctPt sub_prec_fn)
access function to set the subsidiary preconditioner function.
void reset_subsidiary_preconditioner_function_to_default ()
Reset the subsidiary preconditioner function to its default.
void set_subsidiary_preconditioner_pt (Preconditioner *prec, const unsigned &i)
Set the subsidiary preconditioner to use for block i. The subsidiary preconditioner should have been created using new (the general purpose block preconditioner will delete it later). If null the general purpose block preconditioner will use the Subsidiary_preconditioner_creation_function_pt to create the preconditioner during setup().
Preconditioner * subsidiary_preconditioner_pt (const unsigned &i) const
Get the subsidiary precondtioner pointer in block i (is allowed to be null if not yet set).
void set_dof_to_block_map (Vector< unsigned > &dof_to_block_map)
Specify a DOF to block map.
void add_mesh (const Mesh *mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
Adds a mesh to be used by the block preconditioning framework for classifying DOF types. Optional boolean argument (default: false) allows the mesh to contain multiple element types.
unsigned gp_nmesh ()
Returns the number of meshes currently set in the GeneralPurposeBlockPreconditioner base class.
Protected Member Functions
void gp_preconditioner_set_all_meshes ()
Set the mesh in the block preconditioning framework.
void gp_preconditioner_block_setup ()
Modified block setup for general purpose block preconditioners.
void fill_in_subsidiary_preconditioners (const unsigned &nprec_needed)
Create any subsidiary preconditioners needed. Usually nprec_needed = nblock_types, except for the ExactBlockPreconditioner which only requires one preconditioner.
Protected Attributes
Vector< Preconditioner * > Subsidiary_preconditioner_pt
List of preconditioners to use for the blocks to be solved.
SubsidiaryPreconditionerFctPt Subsidiary_preconditioner_creation_function_pt
Private Attributes
Vector< unsigned > Dof_to_block_map
the set of dof to block maps for this preconditioner
Vector< std::pair< const Mesh *, bool > > Gp_mesh_pt
Detailed Description
template<typename MATRIX>
class oomph::GeneralPurposeBlockPreconditioner< MATRIX >
Base class for general purpose block preconditioners. Deals with setting subsidiary preconditioners and dof to block maps. Subsidiary preconditioners can be set in two ways: 1) A pointer to a subsidiary preconditioner for block i can be passed to set_subsidiary_preconditioner_pt(prec, i). 2) A default subsidiary preconditioner can be set up by providing a function pointer to a function which creates a preconditioner. During setup() all unset subsidiary preconditioner pointers will be filled in using this function. By default this uses SuperLU.
Definition at line 79 of file general_purpose_block_preconditioners.h.
Member Typedef Documentation
SubsidiaryPreconditionerFctPt
template<typename MATRIX>
typedef Preconditioner*(* oomph::GeneralPurposeBlockPreconditioner< MATRIX >::SubsidiaryPreconditionerFctPt) ()
typedef for a function that allows other preconditioners to be employed to solve the subsidiary linear systems. The function should return a pointer to the required subsidiary preconditioner generated using new. This preconditioner is responsible for the destruction of the subsidiary preconditioners.
Definition at line 89 of file general_purpose_block_preconditioners.h.
Constructor & Destructor Documentation
GeneralPurposeBlockPreconditioner() [1/2]
template<typename MATRIX>
oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner () [inline]
constructor
Definition at line 92 of file general_purpose_block_preconditioners.h.
 GeneralPurposeBlockPreconditioner()
template<typename MATRIX>
virtual oomph::GeneralPurposeBlockPreconditioner< MATRIX >::~GeneralPurposeBlockPreconditioner () [inline], [virtual]
Destructor: clean up memory then delete all subsidiary preconditioners.
Definition at line 103 of file general_purpose_block_preconditioners.h.
GeneralPurposeBlockPreconditioner() [2/2]
template<typename MATRIX>
oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner (const GeneralPurposeBlockPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 132 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
add_mesh()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh (const Mesh * mesh_pt, const bool & allow_multiple_element_type_in_mesh = false) [inline]
Adds a mesh to be used by the block preconditioning framework for classifying DOF types. Optional boolean argument (default: false) allows the mesh to contain multiple element types.
Definition at line 195 of file general_purpose_block_preconditioners.h.
clean_up_memory()
template<typename MATRIX>
virtual void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory () [inline], [virtual]
??ds I think clean_up_memory is supposed to clear out any stuff that doesn't need to be stored between solves. Call clean up on any non-null subsidiary preconditioners.
Reimplemented from oomph::Preconditioner.
Reimplemented in oomph::BlockTriangularPreconditioner< MATRIX >, and oomph::BlockDiagonalPreconditioner< MATRIX >.
Definition at line 116 of file general_purpose_block_preconditioners.h.
Referenced by oomph::BlockDiagonalPreconditioner< MATRIX >::clean_up_memory(), and oomph::BlockTriangularPreconditioner< MATRIX >::clean_up_memory().
fill_in_subsidiary_preconditioners()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners (const unsigned & nprec_needed) [inline], [protected]
Create any subsidiary preconditioners needed. Usually nprec_needed = nblock_types, except for the ExactBlockPreconditioner which only requires one preconditioner.
Definition at line 264 of file general_purpose_block_preconditioners.h.
References oomph::Global_string_for_annotation::string(), and oomph::StringConversion::to_string().
Referenced by oomph::BlockDiagonalPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners().
gp_nmesh()
template<typename MATRIX>
unsigned oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_nmesh () [inline]
Returns the number of meshes currently set in the GeneralPurposeBlockPreconditioner base class.
Definition at line 216 of file general_purpose_block_preconditioners.h.
gp_preconditioner_block_setup()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_block_setup () [inline], [protected]
Modified block setup for general purpose block preconditioners.
Definition at line 249 of file general_purpose_block_preconditioners.h.
References oomph::BlockPreconditioner< MATRIX >::block_setup().
gp_preconditioner_set_all_meshes()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_set_all_meshes () [inline], [protected]
Set the mesh in the block preconditioning framework.
Definition at line 224 of file general_purpose_block_preconditioners.h.
operator=()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::operator= (const GeneralPurposeBlockPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 138 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_assign().
reset_subsidiary_preconditioner_function_to_default()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::reset_subsidiary_preconditioner_function_to_default () [inline]
Reset the subsidiary preconditioner function to its default.
Definition at line 151 of file general_purpose_block_preconditioners.h.
References oomph::PreconditionerCreationFunctions::create_super_lu_preconditioner().
set_dof_to_block_map()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_dof_to_block_map (Vector< unsigned > & dof_to_block_map) [inline]
Specify a DOF to block map.
Definition at line 187 of file general_purpose_block_preconditioners.h.
Referenced by oomph::PseudoElasticPreconditioner::setup().
set_subsidiary_preconditioner_function()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function (SubsidiaryPreconditionerFctPt sub_prec_fn) [inline]
access function to set the subsidiary preconditioner function.
Definition at line 145 of file general_purpose_block_preconditioners.h.
Referenced by oomph::PseudoElasticPreconditioner::setup().
set_subsidiary_preconditioner_pt()
template<typename MATRIX>
void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_pt (Preconditioner * prec, const unsigned & i) [inline]
Set the subsidiary preconditioner to use for block i. The subsidiary preconditioner should have been created using new (the general purpose block preconditioner will delete it later). If null the general purpose block preconditioner will use the Subsidiary_preconditioner_creation_function_pt to create the preconditioner during setup().
Definition at line 162 of file general_purpose_block_preconditioners.h.
References i.
subsidiary_preconditioner_pt()
template<typename MATRIX>
Preconditioner* oomph::GeneralPurposeBlockPreconditioner< MATRIX >::subsidiary_preconditioner_pt (const unsigned & i) const [inline]
Get the subsidiary precondtioner pointer in block i (is allowed to be null if not yet set).
Definition at line 183 of file general_purpose_block_preconditioners.h.
References i.
Member Data Documentation
Dof_to_block_map
template<typename MATRIX>
Vector<unsigned> oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Dof_to_block_map [private]
the set of dof to block maps for this preconditioner
Definition at line 312 of file general_purpose_block_preconditioners.h.
Gp_mesh_pt
template<typename MATRIX>
Vector<std::pair<const Mesh*, bool> > oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt [private]
Vector of mesh pointers and a boolean indicating if we allow multiple element types in the same mesh.
Definition at line 316 of file general_purpose_block_preconditioners.h.
Subsidiary_preconditioner_creation_function_pt
template<typename MATRIX>
SubsidiaryPreconditionerFctPt oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_creation_function_pt [protected]
Function to create any subsidiary preconditioners not set in Subsidiary_preconditioner_pt.
Definition at line 307 of file general_purpose_block_preconditioners.h.
Subsidiary_preconditioner_pt
template<typename MATRIX>
Vector<Preconditioner*> oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt [protected]
List of preconditioners to use for the blocks to be solved.
Definition at line 303 of file general_purpose_block_preconditioners.h.
The documentation for this class was generated from the following file:
general_purpose_block_preconditioners.h