oomph::BiharmonicProblem< DIM > Class Template Reference
Biharmonic Plate Problem Class - for problems where the load can be assumed to be acting normal to the surface of the plate and the deflections are small relative to the thickness of the plate. Developed for the topologically rectangular Hermite Element Mesh. Contains functions allowing the following boundary conditions to be applied (on a given edge):
#include <biharmonic_problem.h>
Public Types
typedef void(* DirichletBCFctPt) (const double &s, double &u)
Definition of a dirichlet boundary condition function pointer. Takes the position along a boundary (s) in the macro element coordinate scheme and returns the value of the boundary condition at that point (u).
typedef void(* BiharmonicSourceFctPt) (const Vector< double > &x, double &f)
Definition of the Source Function.
Public Member Functions
BiharmonicProblem ()
Constructor.
virtual ~BiharmonicProblem ()
Destructor. Delete the meshes.
void actions_before_newton_solve ()
actions before solve, performs self test
void actions_after_newton_solve ()
action after solve
void doc_solution (DocInfo &doc_info, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt=0)
documents the solution, and if an exact solution is provided, then the error between the numerical and exact solution is presented
Mesh * bulk_element_mesh_pt ()
Access function to the bulk element mesh pt.
Public Attributes
Mesh * Bulk_element_mesh_pt
Mesh for BiharmonicElement<DIM> only - the block preconditioner assemble the global equation number to block number mapping from elements in this mesh only.
Mesh * Face_element_mesh_pt
mesh for face elements
Protected Member Functions
void build_bulk_mesh (const unsigned n_x, const unsigned n_y, TopologicallyRectangularDomain *domain_pt, HermiteQuadMesh< BiharmonicElement< 2 > >::MeshSpacingFnPtr spacing_fn=0)
builds the bulk mesh on a prescribed domain with a node spacing defined by spacing fn with n_x by n_y elements
void build_global_mesh_and_assign_eqn_numbers ()
void set_source_function (const BiharmonicSourceFctPt source_fct_pt)
Impose a load to the surface of the plate. note : MUST be called before neumann boundary conditions are imposed, i.e. a free edge or a simply supported edge with laplacian(u) imposed.
void set_dirichlet_boundary_condition (const unsigned &b, DirichletBCFctPt u_fn=0, DirichletBCFctPt dudn_fn=0)
Imposes the prescribed dirichlet BCs u (u_fn) and du/dn (dudn_fn) dirichlet BCs by 'pinning'.
void set_neumann_boundary_condition (const unsigned &b, BiharmonicFluxElement< 2 >::FluxFctPt flux0_fct_pt, BiharmonicFluxElement< 2 >::FluxFctPt flux1_fct_pt=0)
Imposes the prescribed Neumann BCs laplacian(u) (flux0_fct_pt) and dlaplacian(u)/dn (flux1_fct_pt) with flux edge elements.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::BiharmonicProblem< DIM >
Biharmonic Plate Problem Class - for problems where the load can be assumed to be acting normal to the surface of the plate and the deflections are small relative to the thickness of the plate. Developed for the topologically rectangular Hermite Element Mesh. Contains functions allowing the following boundary conditions to be applied (on a given edge):
clamped : u and du/dn imposed
simply supported : u and laplacian(u) imposed
free : laplacian(u) and dlaplacian(u)/dn imposed
Definition at line 70 of file biharmonic_problem.h.
Member Typedef Documentation
BiharmonicSourceFctPt
template<unsigned DIM>
typedef void(* oomph::BiharmonicProblem< DIM >::BiharmonicSourceFctPt) (const Vector< double > &x, double &f)
Definition of the Source Function.
Definition at line 83 of file biharmonic_problem.h.
DirichletBCFctPt
template<unsigned DIM>
typedef void(* oomph::BiharmonicProblem< DIM >::DirichletBCFctPt) (const double &s, double &u)
Definition of a dirichlet boundary condition function pointer. Takes the position along a boundary (s) in the macro element coordinate scheme and returns the value of the boundary condition at that point (u).
Definition at line 79 of file biharmonic_problem.h.
Constructor & Destructor Documentation
BiharmonicProblem()
template<unsigned DIM>
oomph::BiharmonicProblem< DIM >::BiharmonicProblem () [inline]
Constructor.
Definition at line 86 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt, and oomph::BiharmonicProblem< DIM >::Face_element_mesh_pt.
 BiharmonicProblem()
template<unsigned DIM>
virtual oomph::BiharmonicProblem< DIM >::~BiharmonicProblem () [inline], [virtual]
Destructor. Delete the meshes.
Definition at line 93 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt, and oomph::BiharmonicProblem< DIM >::Face_element_mesh_pt.
Member Function Documentation
actions_after_newton_solve()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::actions_after_newton_solve () [inline], [virtual]
action after solve
Reimplemented from oomph::Problem.
Definition at line 115 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::doc_solution().
actions_before_newton_solve()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::actions_before_newton_solve () [inline], [virtual]
actions before solve, performs self test
Reimplemented from oomph::Problem.
Definition at line 100 of file biharmonic_problem.h.
References oomph::oomph_info, and oomph::Problem::self_test().
build_bulk_mesh()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::build_bulk_mesh (const unsigned n_x, const unsigned n_y, TopologicallyRectangularDomain * domain_pt, HermiteQuadMesh< BiharmonicElement< 2 > >::MeshSpacingFnPtr spacing_fn = 0) [inline], [protected]
builds the bulk mesh on a prescribed domain with a node spacing defined by spacing fn with n_x by n_y elements
Definition at line 133 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt.
build_global_mesh_and_assign_eqn_numbers()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::build_global_mesh_and_assign_eqn_numbers () [inline], [protected]
Definition at line 154 of file biharmonic_problem.h.
References oomph::Problem::add_sub_mesh(), oomph::Problem::assign_eqn_numbers(), oomph::Problem::build_global_mesh(), oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt, and oomph::BiharmonicProblem< DIM >::Face_element_mesh_pt.
bulk_element_mesh_pt()
template<unsigned DIM>
Mesh* oomph::BiharmonicProblem< DIM >::bulk_element_mesh_pt () [inline]
Access function to the bulk element mesh pt.
Definition at line 124 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt.
doc_solution()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::doc_solution (DocInfo & doc_info, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt = 0)
documents the solution, and if an exact solution is provided, then the error between the numerical and exact solution is presented
Definition at line 351 of file biharmonic_problem.cc.
References oomph::DocInfo::directory(), oomph::BiharmonicFluidBoundaryElement::fill_in_generic_residual_contribution_biharmonic_boundary(), oomph::DocInfo::number(), and oomph::oomph_info.
Referenced by oomph::BiharmonicProblem< DIM >::actions_after_newton_solve(), oomph::BiharmonicFluidProblem< DIM >::actions_after_newton_solve(), and oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition().
set_dirichlet_boundary_condition()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition (const unsigned & b, DirichletBCFctPt u_fn = 0, DirichletBCFctPt dudn_fn = 0) [protected]
Imposes the prescribed dirichlet BCs u (u_fn) and du/dn (dudn_fn) dirichlet BCs by 'pinning'.
Impose a Clamped Edge. Imposes the prescribed dirichlet BCs u and du/dn dirichlet BCs by pinning.
Definition at line 48 of file biharmonic_problem.cc.
References e, s, and oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition().
Referenced by oomph::BiharmonicProblem< DIM >::set_source_function().
set_neumann_boundary_condition()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition (const unsigned & b, BiharmonicFluxElement< 2 >::FluxFctPt flux0_fct_pt, BiharmonicFluxElement< 2 >::FluxFctPt flux1_fct_pt = 0) [protected]
Imposes the prescribed Neumann BCs laplacian(u) (flux0_fct_pt) and dlaplacian(u)/dn (flux1_fct_pt) with flux edge elements.
Imposes a 'free' edge. Imposes the prescribed Neumann BCs laplacian(u) and dlaplacian(u)/dn with flux edge elements.
Definition at line 299 of file biharmonic_problem.cc.
References oomph::BiharmonicProblem< DIM >::doc_solution(), e, oomph::BiharmonicFluxElement< DIM >::flux0_fct_pt(), and oomph::BiharmonicFluxElement< DIM >::flux1_fct_pt().
Referenced by oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), and oomph::BiharmonicProblem< DIM >::set_source_function().
set_source_function()
template<unsigned DIM>
void oomph::BiharmonicProblem< DIM >::set_source_function (const BiharmonicSourceFctPt source_fct_pt) [inline], [protected]
Impose a load to the surface of the plate. note : MUST be called before neumann boundary conditions are imposed, i.e. a free edge or a simply supported edge with laplacian(u) imposed.
Definition at line 168 of file biharmonic_problem.h.
References oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt, oomph::Mesh::element_pt(), i, oomph::Mesh::nelement(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition(), oomph::source_fct_pt(), and oomph::BiharmonicEquations< DIM >::source_fct_pt().
Member Data Documentation
Bulk_element_mesh_pt
template<unsigned DIM>
Mesh* oomph::BiharmonicProblem< DIM >::Bulk_element_mesh_pt
Mesh for BiharmonicElement<DIM> only - the block preconditioner assemble the global equation number to block number mapping from elements in this mesh only.
Definition at line 207 of file biharmonic_problem.h.
Referenced by oomph::BiharmonicProblem< DIM >::BiharmonicProblem(), oomph::BiharmonicProblem< DIM >::build_bulk_mesh(), oomph::BiharmonicProblem< DIM >::build_global_mesh_and_assign_eqn_numbers(), oomph::BiharmonicProblem< DIM >::bulk_element_mesh_pt(), oomph::BiharmonicProblem< DIM >::set_source_function(), and oomph::BiharmonicProblem< DIM >::~BiharmonicProblem().
Face_element_mesh_pt
template<unsigned DIM>
Mesh* oomph::BiharmonicProblem< DIM >::Face_element_mesh_pt
mesh for face elements
Definition at line 210 of file biharmonic_problem.h.
Referenced by oomph::BiharmonicProblem< DIM >::BiharmonicProblem(), oomph::BiharmonicProblem< DIM >::build_global_mesh_and_assign_eqn_numbers(), and oomph::BiharmonicProblem< DIM >::~BiharmonicProblem().
The documentation for this class was generated from the following files:
biharmonic_problem.h
biharmonic_problem.cc