oomph::PMLFourierDecomposedHelmholtzEquationsBase Class Reference
#include <pml_fourier_decomposed_helmholtz_elements.h>
Public Types
typedef void(* PMLFourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
PMLFourierDecomposedHelmholtzEquationsBase ()
Constructor.
PMLFourierDecomposedHelmholtzEquationsBase (const PMLFourierDecomposedHelmholtzEquationsBase &dummy)
Broken copy constructor.
virtual std::complex< unsigned > u_index_pml_fourier_decomposed_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to frequency.
double k_squared () const
Get k squared.
double *& alpha_pt ()
Get pointer to complex shift.
double alpha ()
Get complex shift.
int *& pml_fourier_wavenumber_pt ()
Get pointer to Fourier wavenumber.
int pml_fourier_wavenumber ()
Get the Fourier wavenumber.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
void compute_norm (double &norm)
Compute norm of fe solution.
PMLFourierDecomposedHelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PMLFourierDecomposedHelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_pml_fourier_decomposed_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
void get_flux (const Vector< double > &s, Vector< std::complex< double > > &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
std::complex< double > interpolated_u_pml_fourier_decomposed_helmholtz (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Attributes
PMLFourierDecomposedHelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to k^2 (wavenumber squared)
double * Alpha_pt
Pointer to wavenumber complex shift.
int * N_pml_fourier_pt
Pointer to Fourier wave number.
Static Protected Attributes
static double Default_Physical_Constant_Value
Static default value for the physical constants (initialised to zero)
Additional Inherited Members
Detailed Description
A class for all isoparametric elements that solve the Helmholtz equations with pml capabilities. in Fourier decomposed form (cylindrical polars):
 U(r,\varphi,z) = \Re( u^{(n)}(r,z) \exp(-i n \varphi)) 
 We are solving for $ u^{(n)}(r,z)$ for given parameters $ k^2 $ and $ n $ . This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 94 of file pml_fourier_decomposed_helmholtz_elements.h.
Member Typedef Documentation
PMLFourierDecomposedHelmholtzSourceFctPt
typedef void(* oomph::PMLFourierDecomposedHelmholtzEquationsBase::PMLFourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 102 of file pml_fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
PMLFourierDecomposedHelmholtzEquationsBase() [1/2]
oomph::PMLFourierDecomposedHelmholtzEquationsBase::PMLFourierDecomposedHelmholtzEquationsBase () [inline]
Constructor.
Definition at line 107 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value.
PMLFourierDecomposedHelmholtzEquationsBase() [2/2]
oomph::PMLFourierDecomposedHelmholtzEquationsBase::PMLFourierDecomposedHelmholtzEquationsBase (const PMLFourierDecomposedHelmholtzEquationsBase & dummy) [inline]
Broken copy constructor.
Definition at line 116 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha()
double oomph::PMLFourierDecomposedHelmholtzEquationsBase::alpha () [inline]
Get complex shift.
Definition at line 172 of file pml_fourier_decomposed_helmholtz_elements.h.
alpha_pt()
double*& oomph::PMLFourierDecomposedHelmholtzEquationsBase::alpha_pt () [inline]
Get pointer to complex shift.
Definition at line 165 of file pml_fourier_decomposed_helmholtz_elements.h.
compute_error() [1/2]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 748 of file pml_fourier_decomposed_helmholtz_elements.cc.
References compute_norm(), i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 264 of file pml_fourier_decomposed_helmholtz_elements.h.
compute_norm()
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 830 of file pml_fourier_decomposed_helmholtz_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by compute_error().
dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz()
virtual double oomph::PMLFourierDecomposedHelmholtzEquationsBase::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz()
virtual double oomph::PMLFourierDecomposedHelmholtzEquationsBase::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
get_flux()
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::get_flux (const Vector< double > & s, Vector< std::complex< double > > & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 324 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::get_Z2_flux().
get_source_pml_fourier_decomposed_helmholtz()
virtual void oomph::PMLFourierDecomposedHelmholtzEquationsBase::get_source_pml_fourier_decomposed_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 292 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::Source_fct_pt.
interpolated_u_pml_fourier_decomposed_helmholtz()
std::complex<double> oomph::PMLFourierDecomposedHelmholtzEquationsBase::interpolated_u_pml_fourier_decomposed_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 365 of file pml_fourier_decomposed_helmholtz_elements.h.
References s, oomph::self_test(), and oomph::OneDimLagrange::shape().
k_squared()
double oomph::PMLFourierDecomposedHelmholtzEquationsBase::k_squared () const [inline]
Get k squared.
Definition at line 150 of file pml_fourier_decomposed_helmholtz_elements.h.
k_squared_pt()
double*& oomph::PMLFourierDecomposedHelmholtzEquationsBase::k_squared_pt () [inline]
Get pointer to frequency.
Definition at line 143 of file pml_fourier_decomposed_helmholtz_elements.h.
output() [1/4]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 198 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::output().
Referenced by self_test().
output() [2/4]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
Output function:
r,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 507 of file pml_fourier_decomposed_helmholtz_elements.cc.
References output_real(), and s.
output() [3/4]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 217 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::output(), and oomph::output_fct().
output() [4/4]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 594 of file pml_fourier_decomposed_helmholtz_elements.cc.
References s.
output_fct() [1/2]
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_re_exact,u_im_exact at n_plot^2 plot points
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 640 of file pml_fourier_decomposed_helmholtz_elements.cc.
References i, and s.
output_fct() [2/2]
virtual void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >.
Definition at line 234 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::compute_error().
output_real()
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 554 of file pml_fourier_decomposed_helmholtz_elements.cc.
References s.
Referenced by output(), and oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_real().
output_real_fct()
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 695 of file pml_fourier_decomposed_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_real_fct().
pml_fourier_wavenumber()
int oomph::PMLFourierDecomposedHelmholtzEquationsBase::pml_fourier_wavenumber () [inline]
Get the Fourier wavenumber.
Definition at line 184 of file pml_fourier_decomposed_helmholtz_elements.h.
pml_fourier_wavenumber_pt()
int*& oomph::PMLFourierDecomposedHelmholtzEquationsBase::pml_fourier_wavenumber_pt () [inline]
Get pointer to Fourier wavenumber.
Definition at line 178 of file pml_fourier_decomposed_helmholtz_elements.h.
self_test()
unsigned oomph::PMLFourierDecomposedHelmholtzEquationsBase::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 475 of file pml_fourier_decomposed_helmholtz_elements.cc.
References output(), and oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
PMLFourierDecomposedHelmholtzSourceFctPt& oomph::PMLFourierDecomposedHelmholtzEquationsBase::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 279 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::Source_fct_pt.
source_fct_pt() [2/2]
PMLFourierDecomposedHelmholtzSourceFctPt oomph::PMLFourierDecomposedHelmholtzEquationsBase::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 284 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::Source_fct_pt.
u_index_pml_fourier_decomposed_helmholtz()
virtual std::complex<unsigned> oomph::PMLFourierDecomposedHelmholtzEquationsBase::u_index_pml_fourier_decomposed_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored: Real/imag part of index contains (real) index of real/imag part.
Definition at line 137 of file pml_fourier_decomposed_helmholtz_elements.h.
values_to_be_pinned_on_outer_pml_boundary()
void oomph::PMLFourierDecomposedHelmholtzEquationsBase::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Definition at line 312 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::PMLFourierDecomposedHelmholtzEquations< PML_ELEMENT >::values_to_be_pinned_on_outer_pml_boundary().
Member Data Documentation
Alpha_pt
double* oomph::PMLFourierDecomposedHelmholtzEquationsBase::Alpha_pt [protected]
Pointer to wavenumber complex shift.
Definition at line 434 of file pml_fourier_decomposed_helmholtz_elements.h.
Default_Physical_Constant_Value
double oomph::PMLFourierDecomposedHelmholtzEquationsBase::Default_Physical_Constant_Value [static], [protected]
Static default value for the physical constants (initialised to zero)
Definition at line 437 of file pml_fourier_decomposed_helmholtz_elements.h.
K_squared_pt
double* oomph::PMLFourierDecomposedHelmholtzEquationsBase::K_squared_pt [protected]
Pointer to k^2 (wavenumber squared)
Definition at line 431 of file pml_fourier_decomposed_helmholtz_elements.h.
N_pml_fourier_pt
int* oomph::PMLFourierDecomposedHelmholtzEquationsBase::N_pml_fourier_pt [protected]
Pointer to Fourier wave number.
Definition at line 440 of file pml_fourier_decomposed_helmholtz_elements.h.
Source_fct_pt
PMLFourierDecomposedHelmholtzSourceFctPt oomph::PMLFourierDecomposedHelmholtzEquationsBase::Source_fct_pt [protected]
Pointer to source function:
Definition at line 428 of file pml_fourier_decomposed_helmholtz_elements.h.
The documentation for this class was generated from the following files:
pml_fourier_decomposed_helmholtz_elements.h
pml_fourier_decomposed_helmholtz_elements.cc