oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations Class Reference
A version of the GeneralisedAxisymAdvectionDiffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_gen_axisym_advection_diffusion_elements.h>
Public Member Functions
RefineableGeneralisedAxisymAdvectionDiffusionEquations ()
Empty Constructor.
RefineableGeneralisedAxisymAdvectionDiffusionEquations (const RefineableGeneralisedAxisymAdvectionDiffusionEquations &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAxisymAdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: Copy source function pointer from father element.
Protected Member Functions
void fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
A version of the GeneralisedAxisymAdvectionDiffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 59 of file refineable_gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableGeneralisedAxisymAdvectionDiffusionEquations() [1/2]
oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::RefineableGeneralisedAxisymAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 67 of file refineable_gen_axisym_advection_diffusion_elements.h.
RefineableGeneralisedAxisymAdvectionDiffusionEquations() [2/2]
oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::RefineableGeneralisedAxisymAdvectionDiffusionEquations (const RefineableGeneralisedAxisymAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_cons_axisym_adv_diff()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Definition at line 42 of file refineable_gen_axisym_advection_diffusion_elements.cc.
References oomph::ALE_is_disabled, oomph::OcTreeNames::D, oomph::FiniteElement::dnodal_position_dt(), oomph::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff(), oomph::du_dt_cons_axisym_adv_diff(), oomph::get_conserved_wind_cons_axisym_adv_diff(), oomph::get_diff_cons_axisym_adv_diff(), oomph::get_source_cons_axisym_adv_diff(), oomph::get_wind_cons_axisym_adv_diff(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::pe(), oomph::pe_st(), s, oomph::Data::time_stepper_pt(), oomph::u_index_cons_axisym_adv_diff(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by further_build().
further_build()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 171 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::ALE_is_disabled, oomph::conserved_wind_fct_pt(), oomph::Conserved_wind_fct_pt, oomph::Diff_fct_pt, oomph::RefineableElement::father_element_pt(), fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::Pe_pt, oomph::PeSt_pt, oomph::Source_fct_pt, and oomph::Wind_fct_pt.
geometric_jacobian()
double oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
Definition at line 166 of file refineable_gen_axisym_advection_diffusion_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 106 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::u_index_cons_axisym_adv_diff().
get_interpolated_values() [2/2]
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 137 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::u_index_cons_axisym_adv_diff().
get_Z2_flux()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAxisymAdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 98 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::get_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 94 of file refineable_gen_axisym_advection_diffusion_elements.h.
The documentation for this class was generated from the following files:
refineable_gen_axisym_advection_diffusion_elements.h
refineable_gen_axisym_advection_diffusion_elements.cc