oomph::DGSpectralEulerElement< 1, NNODE_1D > Class Template Reference
#include <euler_elements.h>
Public Member Functions
unsigned required_nflux ()
Overload the required number of fluxes for the DGElement.
void calculate_element_averages (double *&average_value)
Calculate the averages in the element.
DGSpectralEulerElement ()
Integral * face_integration_pt () const
~DGSpectralEulerElement ()
void build_all_faces ()
void fill_in_generic_residual_contribution_flux_transport (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
Vector< double > Inverse_mass_diagonal
Friends
class DGEulerFaceElement< DGSpectralEulerElement< 1, NNODE_1D > >
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::DGSpectralEulerElement< 1, NNODE_1D >
Definition at line 739 of file euler_elements.h.
Constructor & Destructor Documentation
DGSpectralEulerElement()
template<unsigned NNODE_1D>
oomph::DGSpectralEulerElement< 1, NNODE_1D >::DGSpectralEulerElement () [inline]
Definition at line 758 of file euler_elements.h.
References oomph::FiniteElement::set_integration_scheme().
 DGSpectralEulerElement()
template<unsigned NNODE_1D>
oomph::DGSpectralEulerElement< 1, NNODE_1D >::~DGSpectralEulerElement () [inline]
Definition at line 770 of file euler_elements.h.
Member Function Documentation
build_all_faces()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 1, NNODE_1D >::build_all_faces () [inline], [virtual]
Implements oomph::DGElement.
Definition at line 774 of file euler_elements.h.
calculate_element_averages()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 1, NNODE_1D >::calculate_element_averages (double *& average_values) [inline], [virtual]
Calculate the averages in the element.
Reimplemented from oomph::DGElement.
Definition at line 753 of file euler_elements.h.
References oomph::FluxTransportEquations< DIM >::calculate_element_averages().
face_integration_pt()
template<unsigned NNODE_1D>
Integral* oomph::DGSpectralEulerElement< 1, NNODE_1D >::face_integration_pt () const [inline]
Definition at line 767 of file euler_elements.h.
fill_in_generic_residual_contribution_flux_transport()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [inline], [virtual]
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 793 of file euler_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
required_nflux()
template<unsigned NNODE_1D>
unsigned oomph::DGSpectralEulerElement< 1, NNODE_1D >::required_nflux () [inline], [virtual]
Overload the required number of fluxes for the DGElement.
Reimplemented from oomph::DGElement.
Definition at line 750 of file euler_elements.h.
References oomph::EulerEquations< DIM >::nflux().
Friends And Related Function Documentation
DGEulerFaceElement< DGSpectralEulerElement< 1, NNODE_1D > >
template<unsigned NNODE_1D>
friend class DGEulerFaceElement< DGSpectralEulerElement< 1, NNODE_1D > > [friend]
Definition at line 743 of file euler_elements.h.
Member Data Documentation
Inverse_mass_diagonal
template<unsigned NNODE_1D>
Vector<double> oomph::DGSpectralEulerElement< 1, NNODE_1D >::Inverse_mass_diagonal [private]
Definition at line 745 of file euler_elements.h.
The documentation for this class was generated from the following file:
euler_elements.h