oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT > Class Template Reference
#include <pml_time_harmonic_linear_elasticity_elements.h>
Public Member Functions
PMLTimeHarmonicLinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals for the solid equations (the discretised principle of virtual displacements)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double > > &sigma) const
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt)
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output_total_real (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double &phi, const unsigned &nplot)
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
Private Member Functions
virtual void fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Additional Inherited Members
Detailed Description
template<unsigned DIM, class PML_ELEMENT>
class oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >
A class for elements that solve the equations of linear elasticity in cartesian coordinates.
Definition at line 357 of file pml_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
PMLTimeHarmonicLinearElasticityEquations()
template<unsigned DIM, class PML_ELEMENT >
oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::PMLTimeHarmonicLinearElasticityEquations () [inline]
Constructor.
Definition at line 363 of file pml_time_harmonic_linear_elasticity_elements.h.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Definition at line 944 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 459 of file pml_time_harmonic_linear_elasticity_elements.h.
compute_norm()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::compute_norm (double & norm) [virtual]
Compute norm of solution: square of the L2 norm.
Compute norm of the solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 883 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
fill_in_contribution_to_jacobian()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element
Reimplemented from oomph::FiniteElement.
Definition at line 379 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_stress(), oomph::FiniteElement::output_fct(), and s.
fill_in_contribution_to_residuals()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals for the solid equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
Definition at line 370 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Compute the residuals for the linear elasticity equations in cartesian coordinates. Flag indicates if we want Jacobian too. All the PML weights that participate in the assemby process are computed here. pml_inverse_jacobian_diagonals are are used to transform derivatives in real x to derivatives in transformed space $\tilde x $. pml_jacobian_det allows us to transform volume integrals in transformed space to real space. If the PML is not enabled via enable_pml, both default to 1.0.
Definition at line 209 of file pml_time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::get_stress().
get_stress()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double > > & stress) const [virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
Compute the Cauchy stress tensor at local coordinate s for displacement formulation.
Implements oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >.
Definition at line 163 of file pml_time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), and i.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_strain().
output() [1/4]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 399 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::FiniteElement::output().
Referenced by oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::output(), and oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D, PML_ELEMENT >::output().
output() [2/4]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 609 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 410 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::FiniteElement::compute_error(), oomph::GeneralisedElement::compute_norm(), and oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
C-style output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 837 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output_fct()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Definition at line 555 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output_imag()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_imag (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 788 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_real().
output_real()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 731 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_imag(), and s.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_total_real().
output_total_real()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_total_real (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
Output function for real part of full time-dependent solution constructed by adding the scattered field
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 666 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output_real(), and s.
required_nvalue()
template<unsigned DIM, class PML_ELEMENT >
unsigned oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 366 of file pml_time_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
pml_time_harmonic_linear_elasticity_elements.h
pml_time_harmonic_linear_elasticity_elements.cc