oomph::TAxisymmetricLinearElasticityElement< NNODE_1D > Class Template Reference
#include <Taxisym_linear_elasticity_elements.h>
Public Member Functions
TAxisymmetricLinearElasticityElement ()
Constructor: Call constructors for TElement and AxisymmetricLinearElasticity equations.
TAxisymmetricLinearElasticityElement (const TAxisymmetricLinearElasticityElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const TAxisymmetricLinearElasticityElement< NNODE_1D > &)
Broken assignment operator.
void output (std::ostream &outfile)
Output function:
void output (std::ostream &outfile, const unsigned &nplot)
Output function:
void output (FILE *file_pt)
C-style output function:
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function:
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >
TAxisymAxisymmetricLinearElasticityElement<NNODE_1D> elements are isoparametric triangular AxisymmetricLinearElasticity elements with NNODE_1D nodal points along each element edge. Inherits from TElement and AxisymmetricLinearElasticityEquations
Definition at line 67 of file Taxisym_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TAxisymmetricLinearElasticityElement() [1/2]
template<unsigned NNODE_1D>
oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::TAxisymmetricLinearElasticityElement () [inline]
Constructor: Call constructors for TElement and AxisymmetricLinearElasticity equations.
Definition at line 77 of file Taxisym_linear_elasticity_elements.h.
TAxisymmetricLinearElasticityElement() [2/2]
template<unsigned NNODE_1D>
oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::TAxisymmetricLinearElasticityElement (const TAxisymmetricLinearElasticityElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 82 of file Taxisym_linear_elasticity_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_Z2_flux()
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 141 of file Taxisym_linear_elasticity_elements.h.
References oomph::AxisymmetricLinearElasticityEquations::get_strain(), and i.
nrecovery_order()
template<unsigned NNODE_1D>
unsigned oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 131 of file Taxisym_linear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned NNODE_1D>
unsigned oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 134 of file Taxisym_linear_elasticity_elements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 120 of file Taxisym_linear_elasticity_elements.h.
operator=()
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::operator= (const TAxisymmetricLinearElasticityElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 89 of file Taxisym_linear_elasticity_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function:
Reimplemented from oomph::AxisymmetricLinearElasticityEquations.
Definition at line 95 of file Taxisym_linear_elasticity_elements.h.
References oomph::AxisymmetricLinearElasticityEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function:
Reimplemented from oomph::AxisymmetricLinearElasticityEquations.
Definition at line 101 of file Taxisym_linear_elasticity_elements.h.
References oomph::AxisymmetricLinearElasticityEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function:
Reimplemented from oomph::AxisymmetricLinearElasticityEquations.
Definition at line 108 of file Taxisym_linear_elasticity_elements.h.
References oomph::AxisymmetricLinearElasticityEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function:
Reimplemented from oomph::AxisymmetricLinearElasticityEquations.
Definition at line 114 of file Taxisym_linear_elasticity_elements.h.
References oomph::AxisymmetricLinearElasticityEquations::output().
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 124 of file Taxisym_linear_elasticity_elements.h.
The documentation for this class was generated from the following file:
Taxisym_linear_elasticity_elements.h