VorticityRecoveryHelpers::RecoveryHelper Class Reference
Class to indicate which derivatives of the vorticity/ velocity we want to recover. We choose to immediately instantiate an object of this class by dropping the semi-colon after the class description.
#include <vorticity_smoother.h>
Public Member Functions
RecoveryHelper ()
Constructor.
int maximum_order_of_vorticity_derivative () const
The maximum order of derivatives calculated in the vorticity recovery.
int maximum_order_of_velocity_derivative () const
The maximum order of derivatives calculated in the velocity recovery.
void set_maximum_order_of_vorticity_derivative (const int &max_deriv)
The maximum order of derivatives calculated in the vorticity recovery.
void set_maximum_order_of_velocity_derivative (const int &max_deriv)
The maximum order of derivatives calculated in the velocity recovery.
void calculate_number_of_values_per_field ()
Calculates the number of values per field given the number of vorticity and velocity derivatives to recover (stored as private data)
unsigned npartial_derivative (const unsigned &n) const
Helper function that determines the number of n-th order partial derivatives in d-dimensions. Specifically there are (n+d-1)(choose)(d-1) possible n-th order partial derivatives in d-dimensions. Implementation makes use of the code found at: www.geeksforgeeks.org/space-and-time-efficient-binomial-coefficient/.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values:
Private Attributes
unsigned Number_of_values_per_field
Number of values per field; how many of the following do we want: u,v,p,omega,d/dx,d/dy, d^2/dx^2,d^2/dxdy,d^2/dy^2, d^3/dx^3,d^3/dx^2dy,d^3/dxdy^2,d^3/dy^3, du/dx,du/dy,dv/dx,dv/dy.
int Maximum_order_of_vorticity_derivative
Maximum number of derivatives to retain in the vorticity recovery. Note, the value -1 means we ONLY output u,v[,w],p.
int Maximum_order_of_velocity_derivative
Maximum number of derivatives to retain in the velocity recovery. Note, the value 0 means we don't calculate the derivatives of the velocity.
Detailed Description
Class to indicate which derivatives of the vorticity/ velocity we want to recover. We choose to immediately instantiate an object of this class by dropping the semi-colon after the class description.
Definition at line 61 of file vorticity_smoother.h.
Constructor & Destructor Documentation
RecoveryHelper()
VorticityRecoveryHelpers::RecoveryHelper::RecoveryHelper () [inline]
Constructor.
Definition at line 65 of file vorticity_smoother.h.
References Maximum_order_of_velocity_derivative, and Maximum_order_of_vorticity_derivative.
Member Function Documentation
calculate_number_of_values_per_field()
void VorticityRecoveryHelpers::RecoveryHelper::calculate_number_of_values_per_field () [inline]
Calculates the number of values per field given the number of vorticity and velocity derivatives to recover (stored as private data)
Definition at line 132 of file vorticity_smoother.h.
References i, Maximum_order_of_velocity_derivative, Maximum_order_of_vorticity_derivative, npartial_derivative(), and Number_of_values_per_field.
Referenced by set_maximum_order_of_velocity_derivative(), and set_maximum_order_of_vorticity_derivative().
maximum_order_of_velocity_derivative()
int VorticityRecoveryHelpers::RecoveryHelper::maximum_order_of_velocity_derivative () const [inline]
The maximum order of derivatives calculated in the velocity recovery.
Definition at line 82 of file vorticity_smoother.h.
References Maximum_order_of_velocity_derivative.
Referenced by oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
maximum_order_of_vorticity_derivative()
int VorticityRecoveryHelpers::RecoveryHelper::maximum_order_of_vorticity_derivative () const [inline]
The maximum order of derivatives calculated in the vorticity recovery.
Definition at line 75 of file vorticity_smoother.h.
References Maximum_order_of_vorticity_derivative.
Referenced by oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
ncont_interpolated_values()
unsigned VorticityRecoveryHelpers::RecoveryHelper::ncont_interpolated_values () const [inline]
Number of continuously interpolated values:
Definition at line 193 of file vorticity_smoother.h.
References Number_of_values_per_field.
Referenced by oomph::VorticitySmootherElement< ELEMENT >::nscalar_paraview(), oomph::VorticitySmootherElement< ELEMENT >::scalar_value_paraview(), and oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
npartial_derivative()
unsigned VorticityRecoveryHelpers::RecoveryHelper::npartial_derivative (const unsigned & n) const [inline]
Helper function that determines the number of n-th order partial derivatives in d-dimensions. Specifically there are (n+d-1)(choose)(d-1) possible n-th order partial derivatives in d-dimensions. Implementation makes use of the code found at: www.geeksforgeeks.org/space-and-time-efficient-binomial-coefficient/.
Definition at line 157 of file vorticity_smoother.h.
References i.
Referenced by calculate_number_of_values_per_field(), oomph::VorticitySmootherElement< ELEMENT >::create_container_for_vorticity_and_derivatives(), oomph::VorticitySmootherElement< ELEMENT >::npartial_derivative(), oomph::VorticitySmootherElement< ELEMENT >::nvelocity_derivatives_to_recover(), oomph::VorticitySmootherElement< ELEMENT >::nvorticity_derivatives_to_recover(), oomph::VorticitySmootherElement< ELEMENT >::recovered_dof_to_container_id(), oomph::VorticitySmootherElement< ELEMENT >::stored_dof_to_recoverable_dof(), and oomph::VorticitySmootherElement< ELEMENT >::vorticity_dof_to_container_id().
set_maximum_order_of_velocity_derivative()
void VorticityRecoveryHelpers::RecoveryHelper::set_maximum_order_of_velocity_derivative (const int & max_deriv) [inline]
The maximum order of derivatives calculated in the velocity recovery.
Definition at line 109 of file vorticity_smoother.h.
References calculate_number_of_values_per_field(), and Maximum_order_of_velocity_derivative.
set_maximum_order_of_vorticity_derivative()
void VorticityRecoveryHelpers::RecoveryHelper::set_maximum_order_of_vorticity_derivative (const int & max_deriv) [inline]
The maximum order of derivatives calculated in the vorticity recovery.
Definition at line 89 of file vorticity_smoother.h.
References calculate_number_of_values_per_field(), and Maximum_order_of_vorticity_derivative.
Member Data Documentation
Maximum_order_of_velocity_derivative
int VorticityRecoveryHelpers::RecoveryHelper::Maximum_order_of_velocity_derivative [private]
Maximum number of derivatives to retain in the velocity recovery. Note, the value 0 means we don't calculate the derivatives of the velocity.
Definition at line 215 of file vorticity_smoother.h.
Referenced by calculate_number_of_values_per_field(), oomph::VorticitySmootherElement< ELEMENT >::create_container_for_vorticity_and_derivatives(), oomph::VorticitySmootherElement< ELEMENT >::get_maximum_order_of_velocity_derivative(), maximum_order_of_velocity_derivative(), oomph::VorticitySmootherElement< ELEMENT >::nvelocity_derivatives_to_recover(), oomph::VorticitySmootherElement< ELEMENT >::recovered_dof_to_container_id(), RecoveryHelper(), set_maximum_order_of_velocity_derivative(), oomph::VorticitySmootherElement< ELEMENT >::vorticity_dof_to_container_id(), and oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
Maximum_order_of_vorticity_derivative
int VorticityRecoveryHelpers::RecoveryHelper::Maximum_order_of_vorticity_derivative [private]
Maximum number of derivatives to retain in the vorticity recovery. Note, the value -1 means we ONLY output u,v[,w],p.
Definition at line 210 of file vorticity_smoother.h.
Referenced by calculate_number_of_values_per_field(), oomph::VorticitySmootherElement< ELEMENT >::create_container_for_vorticity_and_derivatives(), oomph::VorticitySmootherElement< ELEMENT >::get_maximum_order_of_vorticity_derivative(), maximum_order_of_vorticity_derivative(), oomph::VorticitySmootherElement< ELEMENT >::nvorticity_derivatives_to_recover(), oomph::VorticitySmootherElement< ELEMENT >::recovered_dof_to_container_id(), RecoveryHelper(), set_maximum_order_of_vorticity_derivative(), oomph::VorticitySmootherElement< ELEMENT >::stored_dof_to_recoverable_dof(), oomph::VorticitySmootherElement< ELEMENT >::vorticity_dof_to_container_id(), and oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
Number_of_values_per_field
unsigned VorticityRecoveryHelpers::RecoveryHelper::Number_of_values_per_field [private]
Number of values per field; how many of the following do we want: u,v,p,omega,d/dx,d/dy, d^2/dx^2,d^2/dxdy,d^2/dy^2, d^3/dx^3,d^3/dx^2dy,d^3/dxdy^2,d^3/dy^3, du/dx,du/dy,dv/dx,dv/dy.
Definition at line 206 of file vorticity_smoother.h.
Referenced by calculate_number_of_values_per_field(), oomph::VorticitySmootherElement< ELEMENT >::get_interpolated_values(), ncont_interpolated_values(), oomph::VorticitySmootherElement< ELEMENT >::ncont_interpolated_values(), oomph::VorticitySmootherElement< ELEMENT >::pin_smoothed_vorticity(), oomph::VorticitySmootherElement< ELEMENT >::required_nvalue(), and oomph::VorticitySmootherElement< ELEMENT >::VorticitySmootherElement().
The documentation for this class was generated from the following file:
vorticity_smoother.h