oomph::DiagonalComplexMatrix Class Reference
#include <complex_matrices.h>
Public Member Functions
DiagonalComplexMatrix (const unsigned long n)
DiagonalComplexMatrix (const unsigned long n, std::complex< double > &z)
virtual std::complex< double > operator() (const unsigned long &i, const unsigned long &j) const
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
virtual std::complex< double > & operator() (const unsigned long &i, const unsigned long &j)
void multiply (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &result)
Multiply the matrix by the vector x: soln=Ax.
void multiply_transpose (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &result)
Multiply the transposed matrix by the vector x: soln=A^T x.
virtual void residual (const Vector< std::complex< double > > &x, const Vector< std::complex< double > > &b, Vector< std::complex< double > > &residual)
Find the residual, i.e. r=b-Ax the residual.
void resize (const unsigned &N, const unsigned &M)
void resize (const unsigned &N, const unsigned &M, std::complex< double > z)
unsigned long nrow () const
Return the number of rows of the matrix.
unsigned long ncol () const
Return the number of columns of the matrix.
Private Attributes
Vector< std::complex< double > > Matrixdata
Detailed Description
Definition at line 161 of file complex_matrices.h.
Constructor & Destructor Documentation
DiagonalComplexMatrix() [1/2]
oomph::DiagonalComplexMatrix::DiagonalComplexMatrix (const unsigned long n) [inline]
Definition at line 165 of file complex_matrices.h.
DiagonalComplexMatrix() [2/2]
oomph::DiagonalComplexMatrix::DiagonalComplexMatrix (const unsigned long n, std::complex< double > & z) [inline]
Definition at line 167 of file complex_matrices.h.
References i, oomph::ComplexMatrixBase::multiply(), and oomph::ComplexMatrixBase::operator()().
Member Function Documentation
multiply()
void oomph::DiagonalComplexMatrix::multiply (const Vector< std::complex< double > > & x, Vector< std::complex< double > > & soln) [virtual]
Multiply the matrix by the vector x: soln=Ax.
Implements oomph::ComplexMatrixBase.
Definition at line 144 of file complex_matrices.cc.
References i, oomph::QuadTreeNames::N, and oomph::ComplexMatrixBase::ncol().
multiply_transpose()
void oomph::DiagonalComplexMatrix::multiply_transpose (const Vector< std::complex< double > > & x, Vector< std::complex< double > > & soln) [inline], [virtual]
Multiply the transposed matrix by the vector x: soln=A^T x.
Implements oomph::ComplexMatrixBase.
Definition at line 182 of file complex_matrices.h.
References oomph::ComplexMatrixBase::multiply().
ncol()
unsigned long oomph::DiagonalComplexMatrix::ncol () const [inline], [virtual]
Return the number of columns of the matrix.
Implements oomph::ComplexMatrixBase.
Definition at line 200 of file complex_matrices.h.
nrow()
unsigned long oomph::DiagonalComplexMatrix::nrow () const [inline], [virtual]
Return the number of rows of the matrix.
Implements oomph::ComplexMatrixBase.
Definition at line 198 of file complex_matrices.h.
Referenced by oomph::DenseComplexMatrix::DenseComplexMatrix().
operator()() [1/2]
std::complex< double > oomph::DiagonalComplexMatrix::operator() (const unsigned long & i, const unsigned long & j) const [virtual]
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
Implements oomph::ComplexMatrixBase.
Definition at line 87 of file complex_matrices.cc.
References i.
operator()() [2/2]
std::complex< double > & oomph::DiagonalComplexMatrix::operator() (const unsigned long & i, const unsigned long & j) [virtual]
Definition at line 100 of file complex_matrices.cc.
References i.
residual()
virtual void oomph::DiagonalComplexMatrix::residual (const Vector< std::complex< double > > & x, const Vector< std::complex< double > > & b, Vector< std::complex< double > > & residual) [inline], [virtual]
Find the residual, i.e. r=b-Ax the residual.
Implements oomph::ComplexMatrixBase.
Definition at line 189 of file complex_matrices.h.
References oomph::QuadTreeNames::N.
resize() [1/2]
void oomph::DiagonalComplexMatrix::resize (const unsigned & N, const unsigned & M)
Definition at line 116 of file complex_matrices.cc.
Referenced by oomph::PMLElementBase< 2 >::compute_jacobian_inverse_and_det(), and oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det().
resize() [2/2]
void oomph::DiagonalComplexMatrix::resize (const unsigned & N, const unsigned & M, std::complex< double > z)
Definition at line 129 of file complex_matrices.cc.
Member Data Documentation
Matrixdata
Vector<std::complex<double> > oomph::DiagonalComplexMatrix::Matrixdata [private]
Definition at line 204 of file complex_matrices.h.
The documentation for this class was generated from the following files:
complex_matrices.h
complex_matrices.cc