oomph::ScalarAdvectionEquations< DIM > Class Template Reference
Base class for advection equations.
#include <scalar_advection_elements.h>
Public Member Functions
ScalarAdvectionEquations ()
Constructor.
ScalarAdvectionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
ScalarAdvectionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
unsigned required_nvalue (const unsigned &n) const
The number of unknowns at each node is the number of values.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt initial_condition_pt, const double &t, Vector< double > &error, Vector< double > &norm)
Protected Member Functions
unsigned nflux () const
A single flux is interpolated.
void flux (const Vector< double > &u, DenseMatrix< double > &f)
Return the flux as a function of the unknown.
void dflux_du (const Vector< double > &u, RankThreeTensor< double > &df_du)
Return the flux derivatives as a function of the unknowns.
virtual void get_wind_scalar_adv (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Return the wind at a given position.
Private Types
typedef void(* ScalarAdvectionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Typedef for a wind function as a possible function of position.
Private Attributes
ScalarAdvectionWindFctPt Wind_fct_pt
Function pointer to the wind function.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::ScalarAdvectionEquations< DIM >
Base class for advection equations.
Definition at line 52 of file scalar_advection_elements.h.
Member Typedef Documentation
ScalarAdvectionWindFctPt
template<unsigned DIM>
typedef void(* oomph::ScalarAdvectionEquations< DIM >::ScalarAdvectionWindFctPt) (const Vector< double > &x, Vector< double > &wind) [private]
Typedef for a wind function as a possible function of position.
Definition at line 55 of file scalar_advection_elements.h.
Constructor & Destructor Documentation
ScalarAdvectionEquations()
template<unsigned DIM>
oomph::ScalarAdvectionEquations< DIM >::ScalarAdvectionEquations () [inline]
Constructor.
Definition at line 93 of file scalar_advection_elements.h.
Member Function Documentation
compute_error()
template<unsigned DIM>
void oomph::ScalarAdvectionEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt initial_condition_pt, const double & t, Vector< double > & error, Vector< double > & norm) [inline], [virtual]
Compute the error and norm of solution integrated over the element Does not plot the error in the outfile
Reimplemented from oomph::FiniteElement.
Definition at line 107 of file scalar_advection_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), oomph::ScalarAdvectionEquations< DIM >::get_wind_scalar_adv(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::ScalarAdvectionEquations< DIM >::nflux(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), s, t, oomph::QuadTreeNames::W, and oomph::Integral::weight().
dflux_du()
template<unsigned DIM>
void oomph::ScalarAdvectionEquations< DIM >::dflux_du (const Vector< double > & u, RankThreeTensor< double > & df_du) [protected], [virtual]
Return the flux derivatives as a function of the unknowns.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 59 of file scalar_advection_elements.cc.
References i, oomph::RankThreeTensor< T >::initialise(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::ScalarAdvectionEquations< DIM >::flux(), and oomph::ScalarAdvectionEquations< DIM >::nflux().
flux()
template<unsigned DIM>
void oomph::ScalarAdvectionEquations< DIM >::flux (const Vector< double > & u, DenseMatrix< double > & f) [protected], [virtual]
Return the flux as a function of the unknown.
Return the flux as a function of the unknowns.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 41 of file scalar_advection_elements.cc.
References oomph::ScalarAdvectionEquations< DIM >::dflux_du(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::ScalarAdvectionEquations< DIM >::nflux().
get_wind_scalar_adv()
template<unsigned DIM>
virtual void oomph::ScalarAdvectionEquations< DIM >::get_wind_scalar_adv (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [protected], [virtual]
Return the wind at a given position.
Definition at line 73 of file scalar_advection_elements.h.
References i.
Referenced by oomph::ScalarAdvectionEquations< DIM >::compute_error(), and oomph::DGScalarAdvectionFaceElement< ELEMENT >::numerical_flux().
nflux()
template<unsigned DIM>
unsigned oomph::ScalarAdvectionEquations< DIM >::nflux () const [inline], [protected], [virtual]
A single flux is interpolated.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 64 of file scalar_advection_elements.h.
References oomph::ScalarAdvectionEquations< DIM >::dflux_du(), and oomph::ScalarAdvectionEquations< DIM >::flux().
Referenced by oomph::ScalarAdvectionEquations< DIM >::compute_error().
required_nvalue()
template<unsigned DIM>
unsigned oomph::ScalarAdvectionEquations< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
The number of unknowns at each node is the number of values.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, oomph::QScalarAdvectionElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, and oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >.
Definition at line 103 of file scalar_advection_elements.h.
wind_fct_pt() [1/2]
template<unsigned DIM>
ScalarAdvectionWindFctPt& oomph::ScalarAdvectionEquations< DIM >::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 97 of file scalar_advection_elements.h.
References oomph::ScalarAdvectionEquations< DIM >::Wind_fct_pt.
wind_fct_pt() [2/2]
template<unsigned DIM>
ScalarAdvectionWindFctPt oomph::ScalarAdvectionEquations< DIM >::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 100 of file scalar_advection_elements.h.
References oomph::ScalarAdvectionEquations< DIM >::Wind_fct_pt.
Member Data Documentation
Wind_fct_pt
template<unsigned DIM>
ScalarAdvectionWindFctPt oomph::ScalarAdvectionEquations< DIM >::Wind_fct_pt [private]
Function pointer to the wind function.
Definition at line 59 of file scalar_advection_elements.h.
Referenced by oomph::ScalarAdvectionEquations< DIM >::wind_fct_pt().
The documentation for this class was generated from the following files:
scalar_advection_elements.h
scalar_advection_elements.cc