oomph::NewMumpsPreconditioner Class Reference
An interface to allow Mumps to be used as an (exact) Preconditioner.
#include <mumps_solver.h>
Public Member Functions
NewMumpsPreconditioner ()
Constructor.
~NewMumpsPreconditioner ()
Destructor.
NewMumpsPreconditioner (const NewMumpsPreconditioner &)
Broken copy constructor.
void operator= (const NewMumpsPreconditioner &)
Broken assignment operator.
void setup ()
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Function applies Mumps to vector r for (exact) preconditioning, this requires a call to setup(...) first.
void clean_up_memory ()
Clean up memory -- forward the call to the version in Mumps in its LinearSolver incarnation.
void enable_doc_time ()
Enable documentation of timings.
void disable_doc_time ()
Disable the documentation of timings.
Private Attributes
MumpsSolver Solver
the Mumps solver emplyed by this preconditioner
Additional Inherited Members
Detailed Description
An interface to allow Mumps to be used as an (exact) Preconditioner.
Definition at line 258 of file mumps_solver.h.
Constructor & Destructor Documentation
NewMumpsPreconditioner() [1/2]
oomph::NewMumpsPreconditioner::NewMumpsPreconditioner () [inline]
Constructor.
Definition at line 263 of file mumps_solver.h.
 NewMumpsPreconditioner()
oomph::NewMumpsPreconditioner::~NewMumpsPreconditioner () [inline]
Destructor.
Definition at line 267 of file mumps_solver.h.
NewMumpsPreconditioner() [2/2]
oomph::NewMumpsPreconditioner::NewMumpsPreconditioner (const NewMumpsPreconditioner &) [inline]
Broken copy constructor.
Definition at line 271 of file mumps_solver.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
void oomph::NewMumpsPreconditioner::clean_up_memory () [inline], [virtual]
Clean up memory -- forward the call to the version in Mumps in its LinearSolver incarnation.
Reimplemented from oomph::Preconditioner.
Definition at line 323 of file mumps_solver.h.
disable_doc_time()
void oomph::NewMumpsPreconditioner::disable_doc_time () [inline]
Disable the documentation of timings.
Definition at line 333 of file mumps_solver.h.
enable_doc_time()
void oomph::NewMumpsPreconditioner::enable_doc_time () [inline]
Enable documentation of timings.
Definition at line 330 of file mumps_solver.h.
operator=()
void oomph::NewMumpsPreconditioner::operator= (const NewMumpsPreconditioner &) [inline]
Broken assignment operator.
Definition at line 278 of file mumps_solver.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
void oomph::NewMumpsPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Function applies Mumps to vector r for (exact) preconditioning, this requires a call to setup(...) first.
Implements oomph::Preconditioner.
Definition at line 315 of file mumps_solver.h.
setup()
void oomph::NewMumpsPreconditioner::setup () [inline], [virtual]
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 288 of file mumps_solver.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), and oomph::oomph_info.
Member Data Documentation
Solver
MumpsSolver oomph::NewMumpsPreconditioner::Solver [private]
the Mumps solver emplyed by this preconditioner
Definition at line 338 of file mumps_solver.h.
The documentation for this class was generated from the following file:
mumps_solver.h