oomph::AxisymmetricSolidTractionElement< ELEMENT > Class Template Reference
#include <axisym_solid_traction_elements.h>
Public Member Functions
AxisymmetricSolidTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Return the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Public Attributes
void(*&)(const double &, const Vector< double > &, const Vector< double > &, Vector< double > &) traction_fct_pt ()
Return the imposed traction pointer.
Protected Member Functions
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) const
Return the surface traction force.
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::AxisymmetricSolidTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction in the principle of virtual displacements. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 56 of file axisym_solid_traction_elements.h.
Constructor & Destructor Documentation
AxisymmetricSolidTractionElement()
template<class ELEMENT >
oomph::AxisymmetricSolidTractionElement< ELEMENT >::AxisymmetricSolidTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 90 of file axisym_solid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), and oomph::AxisymmetricSolidTractionElement< ELEMENT >::Traction_fct_pt.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Return the jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 111 of file axisym_solid_traction_elements.h.
References oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Return the residuals.
Return the residuals for the AxisymmetricSolidTractionElements.
Reimplemented from oomph::GeneralisedElement.
Definition at line 147 of file axisym_solid_traction_elements.h.
References oomph::FaceElement::bulk_position_type(), oomph::FiniteElement::dshape_local_at_knot(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::get_traction(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), oomph::FaceElement::normal_sign(), oomph::Integral::nweight(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::AxisymmetricSolidTractionElement< ELEMENT >::output().
get_traction()
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) const [inline], [protected]
Return the surface traction force.
Definition at line 69 of file axisym_solid_traction_elements.h.
References i, and oomph::AxisymmetricSolidTractionElement< ELEMENT >::Traction_fct_pt.
Referenced by oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
output() [1/4]
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 120 of file axisym_solid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 123 of file axisym_solid_traction_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 127 of file axisym_solid_traction_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::AxisymmetricSolidTractionElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 130 of file axisym_solid_traction_elements.h.
References oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::FiniteElement::output().
Member Data Documentation
Traction_fct_pt
template<class ELEMENT >
void(* oomph::AxisymmetricSolidTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 62 of file axisym_solid_traction_elements.h.
Referenced by oomph::AxisymmetricSolidTractionElement< ELEMENT >::AxisymmetricSolidTractionElement(), and oomph::AxisymmetricSolidTractionElement< ELEMENT >::get_traction().
traction_fct_pt
template<class ELEMENT >
void(* &)(const double&, const Vector<double> &, const Vector<double> &, Vector<double> &) oomph::AxisymmetricSolidTractionElement< ELEMENT >::traction_fct_pt() [inline]
Return the imposed traction pointer.
Definition at line 103 of file axisym_solid_traction_elements.h.
The documentation for this class was generated from the following file:
axisym_solid_traction_elements.h