oomph::ImmersedRigidBodyTriangleMeshPolygon Class Reference
#include <immersed_rigid_body_elements.h>
Public Member Functions
ImmersedRigidBodyTriangleMeshPolygon (const Vector< double > &hole_center, const Vector< TriangleMeshCurveSection *> &boundary_polyline_pt, TimeStepper *const &time_stepper_pt, Data *const &centre_displacement_data_pt=0)
Constructor: Specify coordinates of a point inside the hole and a vector of pointers to TriangleMeshPolyLines that define the boundary segments of the polygon. Each TriangleMeshPolyLine has its own boundary ID and can contain multiple (straight-line) segments. The optional final argument is a pointer to a Data object whose three values represent the two displacements of and the rotation angle about the polygon's centre of mass.
~ImmersedRigidBodyTriangleMeshPolygon ()
Empty Destuctor.
void position (const Vector< double > &xi, Vector< double > &r) const
Overload (again) the position to apply the rotation and translation.
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Overload (again) the position to apply the rotation and translation.
void reset_reference_configuration ()
Update the reference configuration by re-setting the original position of the vertices to their current ones, re-set the original position of the centre of mass, and the displacements and rotations relative to it.
Private Member Functions
void get_initial_position (const Vector< double > &xi, Vector< double > &r) const
Get the initial position of the polygon.
void assign_zeta ()
Private Attributes
Vector< Vector< double > > Zeta_vertex
Vector of intrisic coordinate values at the nodes.
Additional Inherited Members
Detailed Description
Class upgrading a TriangleMeshPolygon to a `hole` for use during triangle mesh generation. For mesh generation purposes, the main (and only) addition to the base class is the provision of the coordinates of a hole inside the polygon. To faciliate the movement of the `hole` through the domain we also provide a Data object whose three values represent the x and y displacements of its centre of gravity and the polygon's rotation about its centre of gravity. If added to a mesh in the Problem (in its incarnation as a GeneralisedElement) the displacement/rotation of the polygon is computed in response to (i) user-specifiable applied forces and a torque and (ii) the net drag (and associated torque) from a mesh of elements that can exert a drag onto the polygon (typically Navier-Stokes FaceElements that apply a viscous drag to an immersed body, represented by the polygon.)
Definition at line 586 of file immersed_rigid_body_elements.h.
Constructor & Destructor Documentation
ImmersedRigidBodyTriangleMeshPolygon()
oomph::ImmersedRigidBodyTriangleMeshPolygon::ImmersedRigidBodyTriangleMeshPolygon (const Vector< double > & hole_center, const Vector< TriangleMeshCurveSection *> & boundary_polyline_pt, TimeStepper *const & time_stepper_pt, Data *const & centre_displacement_data_pt = 0)
Constructor: Specify coordinates of a point inside the hole and a vector of pointers to TriangleMeshPolyLines that define the boundary segments of the polygon. Each TriangleMeshPolyLine has its own boundary ID and can contain multiple (straight-line) segments. The optional final argument is a pointer to a Data object whose three values represent the two displacements of and the rotation angle about the polygon's centre of mass.
Definition at line 386 of file immersed_rigid_body_elements.cc.
References assign_zeta(), oomph::TriangleMeshPolygon::Can_update_configuration, i, oomph::ImmersedRigidBodyElement::Initial_centre_of_mass, oomph::ImmersedRigidBodyElement::Initial_Phi, oomph::ImmersedRigidBodyElement::Mass, oomph::ImmersedRigidBodyElement::Moment_of_inertia, oomph::TriangleMeshPolygon::polyline_pt(), reset_reference_configuration(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by oomph::ImmersedRigidBodyElement::get_residuals_rigid_body_generic().
 ImmersedRigidBodyTriangleMeshPolygon()
oomph::ImmersedRigidBodyTriangleMeshPolygon::~ImmersedRigidBodyTriangleMeshPolygon () [inline]
Empty Destuctor.
Definition at line 609 of file immersed_rigid_body_elements.h.
Member Function Documentation
assign_zeta()
void oomph::ImmersedRigidBodyTriangleMeshPolygon::assign_zeta () [inline], [private]
Helper function to assign the values of the (scaled) arc-length to each node of each polyline. The direction will be the natural order of the vertices within the polyline.
Definition at line 740 of file immersed_rigid_body_elements.h.
References oomph::TriangleMeshPolyLine::nvertex(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by ImmersedRigidBodyTriangleMeshPolygon().
get_initial_position()
void oomph::ImmersedRigidBodyTriangleMeshPolygon::get_initial_position (const Vector< double > & xi, Vector< double > & r) const [inline], [private]
Get the initial position of the polygon.
Definition at line 643 of file immersed_rigid_body_elements.h.
References i.
position() [1/2]
void oomph::ImmersedRigidBodyTriangleMeshPolygon::position (const Vector< double > & xi, Vector< double > & r) const [inline], [virtual]
Overload (again) the position to apply the rotation and translation.
Reimplemented from oomph::ImmersedRigidBodyElement.
Definition at line 615 of file immersed_rigid_body_elements.h.
References oomph::ImmersedRigidBodyElement::apply_rigid_body_motion().
position() [2/2]
void oomph::ImmersedRigidBodyTriangleMeshPolygon::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const [inline], [virtual]
Overload (again) the position to apply the rotation and translation.
Reimplemented from oomph::ImmersedRigidBodyElement.
Definition at line 624 of file immersed_rigid_body_elements.h.
References oomph::ImmersedRigidBodyElement::apply_rigid_body_motion().
reset_reference_configuration()
void oomph::ImmersedRigidBodyTriangleMeshPolygon::reset_reference_configuration () [virtual]
Update the reference configuration by re-setting the original position of the vertices to their current ones, re-set the original position of the centre of mass, and the displacements and rotations relative to it.
Reimplemented from oomph::TriangleMeshPolygon.
Definition at line 548 of file immersed_rigid_body_elements.cc.
References oomph::ImmersedRigidBodyElement::apply_rigid_body_motion(), oomph::ImmersedRigidBodyElement::Centre_displacement_data_pt, i, oomph::ImmersedRigidBodyElement::Initial_centre_of_mass, oomph::ImmersedRigidBodyElement::Initial_Phi, oomph::TriangleMeshClosedCurve::internal_point(), oomph::TriangleMeshPolygon::ncurve_section(), oomph::TimeStepper::nprev_values(), oomph::TriangleMeshPolyLine::nvertex(), oomph::TriangleMeshPolygon::polyline_pt(), t, oomph::Data::time_stepper_pt(), oomph::Data::value(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by ImmersedRigidBodyTriangleMeshPolygon().
Member Data Documentation
Zeta_vertex
Vector<Vector<double> > oomph::ImmersedRigidBodyTriangleMeshPolygon::Zeta_vertex [private]
Vector of intrisic coordinate values at the nodes.
Definition at line 793 of file immersed_rigid_body_elements.h.
The documentation for this class was generated from the following files:
immersed_rigid_body_elements.h
immersed_rigid_body_elements.cc