oomph::NewmarkBDF< NSTEPS > Class Template Reference
Newmark scheme for second time deriv with first derivatives calculated using BDF. . Stored data represents.
#include <timesteppers.h>
Public Member Functions
NewmarkBDF ()
Constructor: Pass pointer to global time. We set up a timestepping scheme with NSTEPS+2 doubles to represent the history and the highest deriv is 2.
NewmarkBDF (const NewmarkBDF &)
Broken copy constructor.
void operator= (const NewmarkBDF &)
Broken assignment operator.
void set_weights ()
Set weights.
void shift_time_values (Data *const &data_pt)
This function updates the Data's time history so that we can advance to the next timestep.
void shift_time_positions (Node *const &node_pt)
This function updates a nodal time history so that we can advance to the next timestep.
void enable_degrade_first_derivatives_to_bdf1 ()
Degrade scheme to first order BDF (for first derivs/veloc); usually for start-up.
void disable_degrade_first_derivatives_to_bdf1 ()
Disable degradation to first order BDF.
template<>
void set_weights ()
Set weights.
template<>
void set_weights ()
Set weights.
template<>
void set_weights ()
Set weights.
Private Member Functions
void set_newmark_veloc_weights (const double &dt)
Set original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Private Attributes
bool Degrade_to_bdf1_for_first_derivs
Boolean flag to indicate degradation of scheme to first order BDF (for first derivs/veloc); usually for start-up.
Vector< double > Newmark_veloc_weight
Original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Additional Inherited Members
Detailed Description
template<unsigned NSTEPS>
class oomph::NewmarkBDF< NSTEPS >
Newmark scheme for second time deriv with first derivatives calculated using BDF. . Stored data represents.
t=0: value at at present time, Time_pt->time()
t=1: value at previous time, Time_pt->time()-dt
...
t=NSTEPS: value at previous time, Time_pt->time()-NSTEPS*dt
t=NSTEPS+1: 1st time deriv (= `velocity`) at previous time, Time_pt->time()-dt
t=NSTEPS+2: 2nd time deriv (= `acceleration`) at previous time, Time_pt->time()-dt
NSTEPS=1 gives normal Newmark.
Definition at line 1039 of file timesteppers.h.
Constructor & Destructor Documentation
NewmarkBDF() [1/2]
template<unsigned NSTEPS>
oomph::NewmarkBDF< NSTEPS >::NewmarkBDF () [inline]
Constructor: Pass pointer to global time. We set up a timestepping scheme with NSTEPS+2 doubles to represent the history and the highest deriv is 2.
Definition at line 1046 of file timesteppers.h.
NewmarkBDF() [2/2]
template<unsigned NSTEPS>
oomph::NewmarkBDF< NSTEPS >::NewmarkBDF (const NewmarkBDF< NSTEPS > &) [inline]
Broken copy constructor.
Definition at line 1054 of file timesteppers.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
disable_degrade_first_derivatives_to_bdf1()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::disable_degrade_first_derivatives_to_bdf1 () [inline]
Disable degradation to first order BDF.
Definition at line 1085 of file timesteppers.h.
enable_degrade_first_derivatives_to_bdf1()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::enable_degrade_first_derivatives_to_bdf1 () [inline]
Degrade scheme to first order BDF (for first derivs/veloc); usually for start-up.
Definition at line 1078 of file timesteppers.h.
operator=()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::operator= (const NewmarkBDF< NSTEPS > &) [inline]
Broken assignment operator.
Definition at line 1060 of file timesteppers.h.
References oomph::BrokenCopy::broken_assign().
set_newmark_veloc_weights()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::set_newmark_veloc_weights (const double & dt) [inline], [private]
Set original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Definition at line 1097 of file timesteppers.h.
References t.
set_weights() [1/4]
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
set_weights() [2/4]
template<>
void oomph::NewmarkBDF< 1 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1206 of file timesteppers.cc.
References oomph::Time::dt(), oomph::TimeStepper::Time_pt, and oomph::TimeStepper::Weight.
set_weights() [3/4]
template<>
void oomph::NewmarkBDF< 2 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1229 of file timesteppers.cc.
References oomph::Time::dt(), i, oomph::DenseMatrix< T >::ncol(), oomph::TimeStepper::Time_pt, and oomph::TimeStepper::Weight.
set_weights() [4/4]
template<>
void oomph::NewmarkBDF< 4 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1268 of file timesteppers.cc.
References oomph::Time::dt(), i, oomph::DenseMatrix< T >::ncol(), oomph::Time::ndt(), oomph::TimeStepper::Time_pt, and oomph::TimeStepper::Weight.
shift_time_positions()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::shift_time_positions (Node *const & node_pt) [virtual]
This function updates a nodal time history so that we can advance to the next timestep.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1149 of file timesteppers.cc.
References i, oomph::Node::ndim(), oomph::Node::nposition_type(), oomph::TimeStepper::ntstorage(), oomph::Node::position_is_a_copy(), t, oomph::TimeStepper::weight(), and oomph::Node::x_gen().
shift_time_values()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::shift_time_values (Data *const & data_pt) [virtual]
This function updates the Data's time history so that we can advance to the next timestep.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1103 of file timesteppers.cc.
References i, oomph::Data::is_a_copy(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::Data::set_value(), t, oomph::Data::value(), and oomph::TimeStepper::weight().
Member Data Documentation
Degrade_to_bdf1_for_first_derivs
template<unsigned NSTEPS>
bool oomph::NewmarkBDF< NSTEPS >::Degrade_to_bdf1_for_first_derivs [private]
Boolean flag to indicate degradation of scheme to first order BDF (for first derivs/veloc); usually for start-up.
Definition at line 1113 of file timesteppers.h.
Newmark_veloc_weight
template<unsigned NSTEPS>
Vector<double> oomph::NewmarkBDF< NSTEPS >::Newmark_veloc_weight [private]
Original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Definition at line 1119 of file timesteppers.h.
The documentation for this class was generated from the following files:
timesteppers.h
timesteppers.cc