oomph::OcTreeRoot Class Reference
#include <octree.h>
Public Member Functions
OcTreeRoot (RefineableElement *const &object_pt)
Constructor for the root octree: Pass pointer to the RefineableQElement<3> that is represented by the OcTree.
OcTreeRoot (const OcTreeRoot &dummy)
Broken copy constructor.
void operator= (const OcTreeRoot &)
Broken assignment operator.
Vector< TreeRoot * > edge_neighbour_pt (const unsigned &edge_direction)
Return vector of pointers to the edge-neighbouring TreeRoots in the (enumerated) (edge) direction.
unsigned nedge_neighbour (const unsigned &edge_direction)
Return number of edge-neighbouring OcTreeRoot in the (enumerated) (edge) direction.
void add_edge_neighbour_pt (TreeRoot *oc_tree_root_pt, const unsigned &edge_direction)
Add pointer to the edge-neighbouring [Oc]TreeRoot in the (enumerated) (edge) direction -- maintains uniqueness.
int up_equivalent (TreeRoot *tree_root_pt)
Return up equivalent of the neighbours specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree (around the back-front axis) say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc. Returns OMEGA if the Octree specified by the pointer argument is not a neighbour.
void set_up_equivalent (TreeRoot *tree_root_pt, const int &dir)
Set up equivalent of the neighbours specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree (around the back-front axis) say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc.
int right_equivalent (TreeRoot *tree_root_pt)
The same thing as up_equivalent, but for the right direction: When viewed from the current octree neighbour, our right direction is the neighbour's Right_equivalent[neighbour_pt] direction. Returns OMEGA if the Octree specified by the pointer argument is not a neighbour.
void set_right_equivalent (TreeRoot *tree_root_pt, const int &dir)
The same thing as up_equivalent, but for the right direction: When viewed from the current octree neighbour, our right direction is the neighbour's Right_equivalent[neighbour_pt] direction.
int direction_of_neighbour (TreeRoot *octree_root_pt)
If octree_root_pt is a neighbour, return the direction [faces L/R/F/B/U/D or edges DB/UP/...] in which it is found, otherwise return OMEGA.
Private Attributes
std::map< int, Vector< TreeRoot * > > Edge_neighbour_pt
Map of pointers to the edge-neighbouring [Oc]TreeRoots: Edge_neighbour_pt[direction] is Vector to the pointers to the [Oc]TreeRoot's edge neighbours in the (enumerated) (edge) direction.
std::map< TreeRoot *, int > Up_equivalent
Map giving the Up equivalent of the neighbour specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree(around the back-front axis), say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc.
std::map< TreeRoot *, int > Right_equivalent
Map giving the Right equivalent of the neighbour specified by pointer: When viewed from the current octree's neighbour, our right direction is the neighbour's right_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Right_equivalent[neighbour_pt]=R (read as: `in my
neighbour, my Right is its Right`).
Additional Inherited Members
Detailed Description
OcTreeRoot is a OcTree that forms the root of a (recursive) octree. The `root node` is special as it holds additional information about its neighbours and their relative rotation (inside a OcTreeForest).
Definition at line 603 of file octree.h.
Constructor & Destructor Documentation
OcTreeRoot() [1/2]
oomph::OcTreeRoot::OcTreeRoot (RefineableElement *const & object_pt) [inline]
Constructor for the root octree: Pass pointer to the RefineableQElement<3> that is represented by the OcTree.
Definition at line 636 of file octree.h.
References oomph::Global_string_for_annotation::string().
OcTreeRoot() [2/2]
oomph::OcTreeRoot::OcTreeRoot (const OcTreeRoot & dummy) [inline]
Broken copy constructor.
Definition at line 660 of file octree.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
add_edge_neighbour_pt()
void oomph::OcTreeRoot::add_edge_neighbour_pt (TreeRoot * oc_tree_root_pt, const unsigned & edge_direction) [inline]
Add pointer to the edge-neighbouring [Oc]TreeRoot in the (enumerated) (edge) direction -- maintains uniqueness.
Definition at line 726 of file octree.h.
References oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
Referenced by oomph::OcTreeForest::find_neighbours().
direction_of_neighbour()
int oomph::OcTreeRoot::direction_of_neighbour (TreeRoot * octree_root_pt) [inline]
If octree_root_pt is a neighbour, return the direction [faces L/R/F/B/U/D or edges DB/UP/...] in which it is found, otherwise return OMEGA.
Definition at line 826 of file octree.h.
References oomph::OcTreeNames::B, oomph::OcTreeNames::D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, e, oomph::OcTreeNames::F, oomph::OcTreeNames::L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::OMEGA, oomph::OcTreeNames::R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::U, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents().
edge_neighbour_pt()
Vector<TreeRoot*> oomph::OcTreeRoot::edge_neighbour_pt (const unsigned & edge_direction) [inline]
Return vector of pointers to the edge-neighbouring TreeRoots in the (enumerated) (edge) direction.
Definition at line 674 of file octree.h.
References oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
nedge_neighbour()
unsigned oomph::OcTreeRoot::nedge_neighbour (const unsigned & edge_direction) [inline]
Return number of edge-neighbouring OcTreeRoot in the (enumerated) (edge) direction.
Definition at line 701 of file octree.h.
References oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
operator=()
void oomph::OcTreeRoot::operator= (const OcTreeRoot &) [inline]
Broken assignment operator.
Definition at line 666 of file octree.h.
References oomph::BrokenCopy::broken_assign().
right_equivalent()
int oomph::OcTreeRoot::right_equivalent (TreeRoot * tree_root_pt) [inline]
The same thing as up_equivalent, but for the right direction: When viewed from the current octree neighbour, our right direction is the neighbour's Right_equivalent[neighbour_pt] direction. Returns OMEGA if the Octree specified by the pointer argument is not a neighbour.
Definition at line 802 of file octree.h.
References oomph::OcTreeNames::OMEGA.
Referenced by oomph::OcTree::gteq_face_neighbour(), and oomph::OcTree::gteq_true_edge_neighbour().
set_right_equivalent()
void oomph::OcTreeRoot::set_right_equivalent (TreeRoot * tree_root_pt, const int & dir) [inline]
The same thing as up_equivalent, but for the right direction: When viewed from the current octree neighbour, our right direction is the neighbour's Right_equivalent[neighbour_pt] direction.
Definition at line 818 of file octree.h.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents().
set_up_equivalent()
void oomph::OcTreeRoot::set_up_equivalent (TreeRoot * tree_root_pt, const int & dir) [inline]
Set up equivalent of the neighbours specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree (around the back-front axis) say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc.
Definition at line 791 of file octree.h.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents().
up_equivalent()
int oomph::OcTreeRoot::up_equivalent (TreeRoot * tree_root_pt) [inline]
Return up equivalent of the neighbours specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree (around the back-front axis) say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc. Returns OMEGA if the Octree specified by the pointer argument is not a neighbour.
Definition at line 769 of file octree.h.
References oomph::OcTreeNames::OMEGA.
Referenced by oomph::OcTree::gteq_face_neighbour(), and oomph::OcTree::gteq_true_edge_neighbour().
Member Data Documentation
Edge_neighbour_pt
std::map<int,Vector<TreeRoot*> > oomph::OcTreeRoot::Edge_neighbour_pt [private]
Map of pointers to the edge-neighbouring [Oc]TreeRoots: Edge_neighbour_pt[direction] is Vector to the pointers to the [Oc]TreeRoot's edge neighbours in the (enumerated) (edge) direction.
Definition at line 610 of file octree.h.
Right_equivalent
std::map<TreeRoot*,int> oomph::OcTreeRoot::Right_equivalent [private]
Map giving the Right equivalent of the neighbour specified by pointer: When viewed from the current octree's neighbour, our right direction is the neighbour's right_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Right_equivalent[neighbour_pt]=R (read as: `in my
neighbour, my Right is its Right`).
Definition at line 629 of file octree.h.
Up_equivalent
std::map<TreeRoot*,int> oomph::OcTreeRoot::Up_equivalent [private]
Map giving the Up equivalent of the neighbour specified by pointer: When viewed from the current octree's neighbour, our up direction is the neighbour's Up_equivalent[neighbour_pt] direction. If there's no rotation, this map contains the identify so that, e.g. Up_equivalent[neighbour_pt]=U (read as: `in my
neighbour, my Up is its Up`). If the neighbour is rotated by 180 degrees relative to the current octree(around the back-front axis), say, we have Up_equivalent[neighbour_pt]=D (read as: `in my
neighbour, my Up is its Down`); etc.
Definition at line 621 of file octree.h.
The documentation for this class was generated from the following file:
octree.h