oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM > Class Template Reference
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianQCrouzeixRaviartElement ()
Constructor, there are DIM+1 internal values (for the pressure)
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
double p_nst (const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
double p_nst (const unsigned &t, const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_nst () const
Return number of pressure values.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Protected Attributes
unsigned P_nst_internal_index
Private Member Functions
template<>
const unsigned Initial_Nvalue [9]
2D Crouzeix-Raviart elements
template<>
const unsigned Initial_Nvalue [27]
3D Crouzeix-Raviart elements
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >
Crouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation. They can be used within oomph-lib's block preconditioning framework.
Definition at line 1222 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianQCrouzeixRaviartElement()
template<unsigned DIM>
oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::GeneralisedNewtonianQCrouzeixRaviartElement () [inline]
Constructor, there are DIM+1 internal values (for the pressure)
Definition at line 1281 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data(), oomph::FiniteElement::required_nvalue(), and s.
Member Function Documentation
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst().
dpshape_and_dptest_eulerian_nst() [2/3]
template<>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1566 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst(), and oomph::FiniteElement::transform_derivatives().
dpshape_and_dptest_eulerian_nst() [3/3]
template<>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1654 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), and oomph::FiniteElement::transform_derivatives().
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1429 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst().
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
template<>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1455 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1503 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst().
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1408 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::FiniteElement::dshape_eulerian().
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::ndof_types().
fix_pressure()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1321 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
full_output() [1/2]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 1371 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
full_output() [2/2]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile, const unsigned & nplot) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Definition at line 1377 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the DOF that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 2707 of file generalised_newtonian_navier_stokes_elements.cc.
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_pressure_data().
identify_load_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 2645 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_pressure_data().
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::required_nvalue().
identify_pressure_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressue_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2680 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns().
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data().
Initial_Nvalue() [1/2]
template<>
const unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::Initial_Nvalue () [private]
2D Crouzeix-Raviart elements
Definition at line 2616 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
template<>
const unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::Initial_Nvalue () [private]
3D Crouzeix-Raviart elements
Definition at line 2622 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::required_nvalue().
ndof_types()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1383 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst(), and oomph::GeneralisedElement::get_dof_numbers_for_unknowns().
npres_nst()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1313 of file generalised_newtonian_navier_stokes_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1351 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1355 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1360 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1364 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_local_eqn (const unsigned & n) const [inline], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase.
Definition at line 1317 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn().
p_nst() [1/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1303 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_nst() [2/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & t, const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1309 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
pshape_nst() [1/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [2/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Ppressure shape and test functions.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1618 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [3/4]
template<>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1547 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst().
pshape_nst() [4/4]
template<>
void oomph::GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1635 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst().
required_nvalue()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [virtual]
Number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 2630 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data().
Referenced by oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::Initial_Nvalue().
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold required number of variables at nodes.
Definition at line 1229 of file generalised_newtonian_navier_stokes_elements.h.
P_nst_internal_index
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::P_nst_internal_index [protected]
Internal index that indicates at which internal data the pressure is stored
Definition at line 1235 of file generalised_newtonian_navier_stokes_elements.h.
The documentation for this class was generated from the following files:
generalised_newtonian_navier_stokes_elements.h
generalised_newtonian_navier_stokes_elements.cc