oomph::WarpedCircularDisk Class Reference
Warped disk in 3d: zeta[0]=x; zeta[1]=y (so it doesn't have coordinate singularities), with specification of two boundaries (b=0,1) that turn the whole thing into a circular disk.
#include <geom_obj_with_boundary.h>
Public Member Functions
WarpedCircularDisk (const double &epsilon, const unsigned &n, const double &z_offset=0.0)
WarpedCircularDisk ()
Empty default constructor.
WarpedCircularDisk (const WarpedCircularDisk &dummy)
Broken copy constructor.
void operator= (const WarpedCircularDisk &)
Broken assignment operator.
virtual ~WarpedCircularDisk ()
Destructor.
double & epsilon ()
Access fct to amplitude of disk warping.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Object is steady so calls time-independent version.
void boundary_triad (const unsigned &b, const double &zeta_bound, Vector< double > &r, Vector< double > &tangent, Vector< double > &normal, Vector< double > &binormal)
Boundary triad on boundary b at boundary coordinate zeta_bound.
Private Member Functions
double w (const double &r, const double &phi) const
Vertical deflection.
double dwdr (const double &r, const double &phi) const
Deriv of vertical deflection w.r.t. radius.
double dwdphi (const double &r, const double &phi) const
Deriv of vertical deflection w.r.t. angle.
Private Attributes
double Epsilon
Amplitude of non-axisymmetric deformation.
unsigned N
Wavenumber of non-axisymmetric deformation.
double Z_offset
Vertical offset.
Additional Inherited Members
Detailed Description
Warped disk in 3d: zeta[0]=x; zeta[1]=y (so it doesn't have coordinate singularities), with specification of two boundaries (b=0,1) that turn the whole thing into a circular disk.
Definition at line 380 of file geom_obj_with_boundary.h.
Constructor & Destructor Documentation
WarpedCircularDisk() [1/3]
oomph::WarpedCircularDisk::WarpedCircularDisk (const double & epsilon, const unsigned & n, const double & z_offset = 0.0) [inline]
Constructor. Pass amplitude and azimuthal wavenumber of warping as arguments. Can specify vertical offset as final, optional argument.
Definition at line 388 of file geom_obj_with_boundary.h.
References oomph::DiskLikeGeomObjectWithBoundaries::Boundary_parametrising_geom_object_pt, oomph::MathematicalConstants::Pi, oomph::DiskLikeGeomObjectWithBoundaries::Zeta_boundary_end, and oomph::DiskLikeGeomObjectWithBoundaries::Zeta_boundary_start.
WarpedCircularDisk() [2/3]
oomph::WarpedCircularDisk::WarpedCircularDisk () [inline]
Empty default constructor.
Definition at line 411 of file geom_obj_with_boundary.h.
WarpedCircularDisk() [3/3]
oomph::WarpedCircularDisk::WarpedCircularDisk (const WarpedCircularDisk & dummy) [inline]
Broken copy constructor.
Definition at line 420 of file geom_obj_with_boundary.h.
References oomph::BrokenCopy::broken_copy().
 WarpedCircularDisk()
virtual oomph::WarpedCircularDisk::~WarpedCircularDisk () [inline], [virtual]
Destructor.
Definition at line 432 of file geom_obj_with_boundary.h.
References oomph::DiskLikeGeomObjectWithBoundaries::Boundary_parametrising_geom_object_pt, and oomph::DiskLikeGeomObjectWithBoundaries::nboundary().
Member Function Documentation
boundary_triad()
void oomph::WarpedCircularDisk::boundary_triad (const unsigned & b, const double & zeta_bound, Vector< double > & r, Vector< double > & tangent, Vector< double > & normal, Vector< double > & binormal) [inline], [virtual]
Boundary triad on boundary b at boundary coordinate zeta_bound.
Reimplemented from oomph::DiskLikeGeomObjectWithBoundaries.
Definition at line 471 of file geom_obj_with_boundary.h.
dwdphi()
double oomph::WarpedCircularDisk::dwdphi (const double & r, const double & phi) const [inline], [private]
Deriv of vertical deflection w.r.t. angle.
Definition at line 531 of file geom_obj_with_boundary.h.
References oomph::QuadTreeNames::N.
dwdr()
double oomph::WarpedCircularDisk::dwdr (const double & r, const double & phi) const [inline], [private]
Deriv of vertical deflection w.r.t. radius.
Definition at line 525 of file geom_obj_with_boundary.h.
References oomph::QuadTreeNames::N.
epsilon()
double& oomph::WarpedCircularDisk::epsilon () [inline]
Access fct to amplitude of disk warping.
Definition at line 443 of file geom_obj_with_boundary.h.
operator=()
void oomph::WarpedCircularDisk::operator= (const WarpedCircularDisk &) [inline]
Broken assignment operator.
Definition at line 426 of file geom_obj_with_boundary.h.
References oomph::BrokenCopy::broken_assign().
position() [1/2]
void oomph::WarpedCircularDisk::position (const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
Definition at line 449 of file geom_obj_with_boundary.h.
position() [2/2]
void oomph::WarpedCircularDisk::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Object is steady so calls time-independent version.
Reimplemented from oomph::GeomObject.
Definition at line 463 of file geom_obj_with_boundary.h.
References oomph::GeomObject::position().
w()
double oomph::WarpedCircularDisk::w (const double & r, const double & phi) const [inline], [private]
Vertical deflection.
Definition at line 519 of file geom_obj_with_boundary.h.
References oomph::QuadTreeNames::N.
Member Data Documentation
Epsilon
double oomph::WarpedCircularDisk::Epsilon [private]
Amplitude of non-axisymmetric deformation.
Definition at line 537 of file geom_obj_with_boundary.h.
N
unsigned oomph::WarpedCircularDisk::N [private]
Wavenumber of non-axisymmetric deformation.
Definition at line 540 of file geom_obj_with_boundary.h.
Z_offset
double oomph::WarpedCircularDisk::Z_offset [private]
Vertical offset.
Definition at line 543 of file geom_obj_with_boundary.h.
The documentation for this class was generated from the following file:
geom_obj_with_boundary.h