oomph::RefineableQSpectralElement< 1 > Class Template Reference
#include <refineable_line_spectral_element.h>
Public Member Functions
RefineableQSpectralElement ()
Constructor.
RefineableQSpectralElement (const RefineableQSpectralElement< 1 > &dummy)
Broken copy constructor.
virtual ~RefineableQSpectralElement ()
Broken assignment operator.
void rebuild_from_sons (Mesh *&mesh_pt)
The only thing to add is rebuild from sons.
virtual bool nodes_built ()
Overload the nodes built function.
Additional Inherited Members
Detailed Description
template<>
class oomph::RefineableQSpectralElement< 1 >
Refineable version of LineElements that add functionality for spectral Elements.
Definition at line 55 of file refineable_line_spectral_element.h.
Constructor & Destructor Documentation
RefineableQSpectralElement() [1/2]
oomph::RefineableQSpectralElement< 1 >::RefineableQSpectralElement () [inline]
Constructor.
Definition at line 61 of file refineable_line_spectral_element.h.
References oomph::LeakCheckNames::_build.
RefineableQSpectralElement() [2/2]
oomph::RefineableQSpectralElement< 1 >::RefineableQSpectralElement (const RefineableQSpectralElement< 1 > & dummy) [inline]
Broken copy constructor.
Definition at line 69 of file refineable_line_spectral_element.h.
References oomph::BrokenCopy::broken_copy().
 RefineableQSpectralElement()
virtual oomph::RefineableQSpectralElement< 1 >::~RefineableQSpectralElement () [inline], [virtual]
Broken assignment operator.
Destructor
Definition at line 85 of file refineable_line_spectral_element.h.
References oomph::LeakCheckNames::_build.
Member Function Documentation
nodes_built()
virtual bool oomph::RefineableQSpectralElement< 1 >::nodes_built () [inline], [virtual]
Overload the nodes built function.
Reimplemented from oomph::RefineableElement.
Definition at line 274 of file refineable_line_spectral_element.h.
rebuild_from_sons()
void oomph::RefineableQSpectralElement< 1 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
The only thing to add is rebuild from sons.
Implements oomph::RefineableElement.
Definition at line 93 of file refineable_line_spectral_element.h.
References oomph::Mesh::add_node_pt(), oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_x(), oomph::BinaryTreeNames::L, oomph::TimeStepper::ntstorage(), oomph::BinaryTreeNames::R, s, oomph::Global_string_for_annotation::string(), and t.
The documentation for this class was generated from the following file:
refineable_line_spectral_element.h