oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied flux on the boundaries of Fourier decomposed Helmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <pml_fourier_decomposed_helmholtz_flux_elements.h>
Public Types
typedef void(* PMLFourierDecomposedHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex.
Public Member Functions
PMLFourierDecomposedHelmholtzFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
PMLFourierDecomposedHelmholtzFluxElement ()
Broken empty constructor.
PMLFourierDecomposedHelmholtzFluxElement (const PMLFourierDecomposedHelmholtzFluxElement &dummy)
Broken copy constructor.
PMLFourierDecomposedHelmholtzPrescribedFluxFctPt & flux_fct_pt ()
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
virtual std::complex< unsigned > u_index_pml_fourier_decomposed_helmholtz () const
Return the index at which the unknown value is stored. (Real/imag part gives real index of real/imag part).
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const Vector< double > &x, std::complex< double > &flux)
virtual void fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Protected Attributes
std::complex< unsigned > U_index_pml_fourier_decomposed_helmholtz
The index at which the real and imag part of the unknown is stored at the nodes.
PMLFourierDecomposedHelmholtzPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied flux on the boundaries of Fourier decomposed Helmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 58 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Member Typedef Documentation
PMLFourierDecomposedHelmholtzPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex.
Definition at line 69 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Constructor & Destructor Documentation
PMLFourierDecomposedHelmholtzFluxElement() [1/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 258 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt, oomph::Global_string_for_annotation::string(), and oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz.
PMLFourierDecomposedHelmholtzFluxElement() [2/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement () [inline]
Broken empty constructor.
Definition at line 78 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
PMLFourierDecomposedHelmholtzFluxElement() [3/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement (const PMLFourierDecomposedHelmholtzFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 87 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 123 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 112 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux().
fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux()
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 303 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), s, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement().
flux_fct_pt()
template<class ELEMENT >
PMLFourierDecomposedHelmholtzPrescribedFluxFctPt& oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::flux_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-flux function pointer
Definition at line 107 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux (const Vector< double > & x, std::complex< double > & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position
Definition at line 209 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt.
Referenced by oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux().
output() [1/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 133 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 137 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 143 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 148 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 168 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 189 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
u_index_pml_fourier_decomposed_helmholtz()
template<class ELEMENT >
virtual std::complex<unsigned> oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz () const [inline], [virtual]
Return the index at which the unknown value is stored. (Real/imag part gives real index of real/imag part).
Definition at line 155 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz.
Referenced by oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution().
Member Data Documentation
Flux_fct_pt
template<class ELEMENT >
PMLFourierDecomposedHelmholtzPrescribedFluxFctPt oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt [protected]
Function pointer to the (global) prescribed-flux function.
Definition at line 239 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Referenced by oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::flux_fct_pt(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux(), and oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement().
U_index_pml_fourier_decomposed_helmholtz
template<class ELEMENT >
std::complex<unsigned> oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz [protected]
The index at which the real and imag part of the unknown is stored at the nodes.
Definition at line 226 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Referenced by oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz(), and oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz().
The documentation for this class was generated from the following file:
pml_fourier_decomposed_helmholtz_flux_elements.h