oomph::PVDEquationsBase< DIM > Class Template Reference
#include <solid_elements.h>
Public Types
typedef void(* IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
Function pointer to function that specifies the isotropic growth as a function of the Lagrangian coordinates FCT(xi,gamma(xi)) -- xi is a Vector!
typedef double(* PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
Function pointer to function that specifies the pre-stress sigma_0(i,j) as a function of the Lagrangian coordinates FCT(i,j,xi) -- xi is a Vector!
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Lagrangian coordinates and time FCT(t,xi,b) -- xi and b are Vectors!
Public Member Functions
PVDEquationsBase ()
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, enable inertia and set body force to zero. Default evaluation of Jacobian: analytically rather than by FD.
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
IsotropicGrowthFctPt & isotropic_growth_fct_pt ()
Access function: Pointer to isotropic growth function.
PrestressFctPt & prestress_fct_pt ()
Access function: Pointer to pre-stress function.
IsotropicGrowthFctPt isotropic_growth_fct_pt () const
Access function: Pointer to isotropic growth function (const version)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
virtual unsigned npres_solid () const
Return the number of solid pressure degrees of freedom Default is that there are no solid pressures.
virtual int solid_p_local_eqn (const unsigned &i) const
Return the local degree of freedom associated with the i-th solid pressure. Default is that there are none.
virtual int solid_p_nodal_index () const
Return the index at which the solid pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
virtual void unpin_elemental_solid_pressure_dofs ()=0
Unpin all solid pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_solid_pressures ()
Pin the element's redundant solid pressures (needed for refinement)
virtual void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma)=0
Return the 2nd Piola Kirchoff stress tensor, as calculated from the constitutive law at specified local coordinate (needed by get_principal_stress(...), so I'm afraid I will have to insist that you implement it...
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy.
void get_deformed_covariant_basis_vectors (const Vector< double > &s, DenseMatrix< double > &def_covariant_basis)
Return the deformed covariant basis vectors at specified local coordinate: def_covariant_basis(i,j) is the j-th component of the i-th basis vector.
void get_principal_stress (const Vector< double > &s, DenseMatrix< double > &principal_stress_vector, Vector< double > &principal_stress)
Compute principal stress vectors and (scalar) principal stresses at specified local coordinate. principal_stress_vector(i,j) is the j-th component of the i-th principal stress vector.
virtual void get_isotropic_growth (const unsigned &ipt, const Vector< double > &s, const Vector< double > &xi, double &gamma) const
Evaluate isotropic growth function at Lagrangian coordinate xi and/or local coordinate s. (returns 1, i.e. no growth, if no function pointer has been set) This function is virtual to allow overloading in multi-physics problems where the growth function might be determined by another system of equations.
void body_force (const Vector< double > &xi, Vector< double > &b) const
Evaluate body force at Lagrangian coordinate xi at present time (returns zero vector if no body force function pointer has been set)
unsigned ndof_types () const
returns the number of DOF types associated with this element.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) E.g. in a 3D problem there are 3 types of DOF: 0 - x displacement 1 - y displacement 2 - z displacement.
void enable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated by FD? Else: Analytically.
void disable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated analytically Else: by FD.
bool is_jacobian_evaluated_by_fd () const
Return the flag indicating whether the jacobian is evaluated by fd.
double prestress (const unsigned &i, const unsigned &j, const Vector< double > xi)
Return (i,j)-th component of second Piola Kirchhoff membrane prestress at Lagrangian coordinate xi.
Static Public Member Functions
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement *> &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a refineable solid mesh) and pin the nodal solid pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement *> &element_pt)
Unpin all pressure dofs in elements listed in vector.
Protected Attributes
IsotropicGrowthFctPt Isotropic_growth_fct_pt
Pointer to isotropic growth function.
PrestressFctPt Prestress_fct_pt
Pointer to prestress function.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
bool Evaluate_jacobian_by_fd
Use FD to evaluate Jacobian.
Static Protected Attributes
static double Default_lambda_sq_value =1.0
Static default value for timescale ratio (1.0 -- for natural scaling)
Static Private Attributes
static int Solid_pressure_not_stored_at_node = -100
Static `magic` number that indicates that the solid pressure is not stored at a node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PVDEquationsBase< DIM >
A base class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in Cartesian coordinates. Combines a few generic functions that are shared by PVDEquations and PVDEquationsWithPressure.
Definition at line 63 of file solid_elements.h.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM>
typedef void(* oomph::PVDEquationsBase< DIM >::BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Lagrangian coordinates and time FCT(t,xi,b) -- xi and b are Vectors!
Definition at line 88 of file solid_elements.h.
IsotropicGrowthFctPt
template<unsigned DIM>
typedef void(* oomph::PVDEquationsBase< DIM >::IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
Function pointer to function that specifies the isotropic growth as a function of the Lagrangian coordinates FCT(xi,gamma(xi)) -- xi is a Vector!
Definition at line 77 of file solid_elements.h.
PrestressFctPt
template<unsigned DIM>
typedef double(* oomph::PVDEquationsBase< DIM >::PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
Function pointer to function that specifies the pre-stress sigma_0(i,j) as a function of the Lagrangian coordinates FCT(i,j,xi) -- xi is a Vector!
Definition at line 83 of file solid_elements.h.
Constructor & Destructor Documentation
PVDEquationsBase()
template<unsigned DIM>
oomph::PVDEquationsBase< DIM >::PVDEquationsBase () [inline]
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, enable inertia and set body force to zero. Default evaluation of Jacobian: analytically rather than by FD.
Definition at line 96 of file solid_elements.h.
Member Function Documentation
body_force()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::body_force (const Vector< double > & xi, Vector< double > & b) const [inline]
Evaluate body force at Lagrangian coordinate xi at present time (returns zero vector if no body force function pointer has been set)
Definition at line 249 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Body_force_fct_pt, oomph::FiniteElement::dim(), i, oomph::FiniteElement::node_pt(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::Data::time_stepper_pt().
body_force_fct_pt() [1/2]
template<unsigned DIM>
BodyForceFctPt& oomph::PVDEquationsBase< DIM >::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 127 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Body_force_fct_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
body_force_fct_pt() [2/2]
template<unsigned DIM>
BodyForceFctPt oomph::PVDEquationsBase< DIM >::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 130 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Body_force_fct_pt.
constitutive_law_pt()
template<unsigned DIM>
ConstitutiveLaw* & oomph::PVDEquationsBase< DIM >::constitutive_law_pt () [inline]
Return the constitutive law pointer.
Definition at line 103 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Constitutive_law_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
disable_evaluate_jacobian_by_fd()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::disable_evaluate_jacobian_by_fd () [inline]
Set Jacobian to be evaluated analytically Else: by FD.
Definition at line 345 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
disable_inertia()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::disable_inertia () [inline]
Switch off solid inertia.
Definition at line 136 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Unsteady.
enable_evaluate_jacobian_by_fd()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::enable_evaluate_jacobian_by_fd () [inline]
Set Jacobian to be evaluated by FD? Else: Analytically.
Definition at line 342 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
enable_inertia()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::enable_inertia () [inline]
Switch on solid inertia.
Definition at line 133 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Unsteady.
get_deformed_covariant_basis_vectors()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::get_deformed_covariant_basis_vectors (const Vector< double > & s, DenseMatrix< double > & def_covariant_basis)
Return the deformed covariant basis vectors at specified local coordinate: def_covariant_basis(i,j) is the j-th component of the i-th basis vector.
Return the deformed covariant basis vectors at specified local coordinate: def_covariant_basis(i,j) is the j-th component of the i-th basis vector.
Definition at line 1165 of file solid_elements.cc.
References oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and i.
Referenced by oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) E.g. in a 3D problem there are 3 types of DOF: 0 - x displacement 1 - y displacement 2 - z displacement.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PVDEquationsWithPressure< DIM >.
Definition at line 295 of file solid_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), and oomph::SolidFiniteElement::position_local_eqn().
get_energy()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::get_energy (double & pot_en, double & kin_en)
Get potential (strain) and kinetic energy.
Definition at line 811 of file solid_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
get_isotropic_growth()
template<unsigned DIM>
virtual void oomph::PVDEquationsBase< DIM >::get_isotropic_growth (const unsigned & ipt, const Vector< double > & s, const Vector< double > & xi, double & gamma) const [inline], [virtual]
Evaluate isotropic growth function at Lagrangian coordinate xi and/or local coordinate s. (returns 1, i.e. no growth, if no function pointer has been set) This function is virtual to allow overloading in multi-physics problems where the growth function might be determined by another system of equations.
Definition at line 232 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
get_principal_stress()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::get_principal_stress (const Vector< double > & s, DenseMatrix< double > & principal_stress_vector, Vector< double > & principal_stress)
Compute principal stress vectors and (scalar) principal stresses at specified local coordinate. principal_stress_vector(i,j) is the j-th component of the i-th principal stress vector.
Compute principal stress vectors and (scalar) principal stresses at specified local coordinate: principal_stress_vector(i,j) is the j-th component of the i-th principal stress vector.
Definition at line 1042 of file solid_elements.cc.
References oomph::DenseDoubleMatrix::eigenvalues_by_jacobi(), i, and oomph::DoubleMatrixBase::solve().
Referenced by oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
get_strain()
template<unsigned DIM>
void oomph::PVDEquationsBase< DIM >::get_strain (const Vector< double > & s, DenseMatrix< double > & strain) const
Return the strain tensor.
Compute the strain tensor at local coordinate s.
Definition at line 54 of file solid_elements.cc.
References oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), i, oomph::DenseMatrix< T >::ncol(), and oomph::DenseMatrix< T >::nrow().
Referenced by oomph::RefineablePVDEquations< DIM >::get_Z2_flux(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_Z2_flux(), oomph::TPVDElement< DIM, NNODE_1D >::get_Z2_flux(), oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >::get_Z2_flux(), oomph::TPVDElementWithContinuousPressure< DIM >::get_Z2_flux(), and oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
get_stress()
template<unsigned DIM>
virtual void oomph::PVDEquationsBase< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & sigma) [pure virtual]
Return the 2nd Piola Kirchoff stress tensor, as calculated from the constitutive law at specified local coordinate (needed by get_principal_stress(...), so I'm afraid I will have to insist that you implement it...
Implemented in oomph::PVDEquationsWithPressure< DIM >, and oomph::PVDEquations< DIM >.
Referenced by oomph::PVDEquations< DIM >::PVDEquations(), oomph::PVDEquationsWithPressure< DIM >::PVDEquationsWithPressure(), and oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
is_inertia_enabled()
template<unsigned DIM>
bool oomph::PVDEquationsBase< DIM >::is_inertia_enabled () const [inline]
Access function to flag that switches inertia on/off (const version)
Definition at line 139 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Unsteady.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
is_jacobian_evaluated_by_fd()
template<unsigned DIM>
bool oomph::PVDEquationsBase< DIM >::is_jacobian_evaluated_by_fd () const [inline]
Return the flag indicating whether the jacobian is evaluated by fd.
Definition at line 348 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
isotropic_growth_fct_pt() [1/2]
template<unsigned DIM>
IsotropicGrowthFctPt& oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt () [inline]
Access function: Pointer to isotropic growth function.
Definition at line 115 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
isotropic_growth_fct_pt() [2/2]
template<unsigned DIM>
IsotropicGrowthFctPt oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt () const [inline]
Access function: Pointer to isotropic growth function (const version)
Definition at line 123 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt.
lambda_sq()
template<unsigned DIM>
const double& oomph::PVDEquationsBase< DIM >::lambda_sq () const [inline]
Access function for timescale ratio (nondim density)
Definition at line 107 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Lambda_sq_pt.
lambda_sq_pt()
template<unsigned DIM>
double* & oomph::PVDEquationsBase< DIM >::lambda_sq_pt () [inline]
Access function for pointer to timescale ratio (nondim density)
Definition at line 111 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Lambda_sq_pt.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
ndof_types()
template<unsigned DIM>
unsigned oomph::PVDEquationsBase< DIM >::ndof_types () const [inline], [virtual]
returns the number of DOF types associated with this element.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PVDEquationsWithPressure< DIM >.
Definition at line 280 of file solid_elements.h.
npres_solid()
template<unsigned DIM>
virtual unsigned oomph::PVDEquationsBase< DIM >::npres_solid () const [inline], [virtual]
Return the number of solid pressure degrees of freedom Default is that there are no solid pressures.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
Definition at line 143 of file solid_elements.h.
Referenced by oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::data_values_of_field(), oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nvalue_of_field(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures(), oomph::TPVDElementWithContinuousPressure< DIM >::set_solid_p(), oomph::RefineableQPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs(), and oomph::QPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs().
pin_elemental_redundant_nodal_solid_pressures()
template<unsigned DIM>
virtual void oomph::PVDEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures () [inline], [virtual]
Pin the element's redundant solid pressures (needed for refinement)
Reimplemented in oomph::RefineableQPVDElementWithContinuousPressure< DIM >.
Definition at line 160 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::pin_redundant_nodal_solid_pressures().
pin_redundant_nodal_solid_pressures()
template<unsigned DIM>
static void oomph::PVDEquationsBase< DIM >::pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a refineable solid mesh) and pin the nodal solid pressure degrees of freedom that are not being used. Function uses the member function.
PVDEquationsBase<DIM>:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal solid pressure degrees of freedom (e.g. solid elements with continuous pressure interpolation.)
Definition at line 172 of file solid_elements.h.
References e, and oomph::PVDEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures().
prestress()
template<unsigned DIM>
double oomph::PVDEquationsBase< DIM >::prestress (const unsigned & i, const unsigned & j, const Vector< double > xi) [inline]
Return (i,j)-th component of second Piola Kirchhoff membrane prestress at Lagrangian coordinate xi.
Definition at line 352 of file solid_elements.h.
References i, and oomph::PVDEquationsBase< DIM >::Prestress_fct_pt.
prestress_fct_pt()
template<unsigned DIM>
PrestressFctPt& oomph::PVDEquationsBase< DIM >::prestress_fct_pt () [inline]
Access function: Pointer to pre-stress function.
Definition at line 119 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Prestress_fct_pt.
solid_p_local_eqn()
template<unsigned DIM>
virtual int oomph::PVDEquationsBase< DIM >::solid_p_local_eqn (const unsigned & i) const [inline], [virtual]
Return the local degree of freedom associated with the i-th solid pressure. Default is that there are none.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithPressure< DIM >.
Definition at line 147 of file solid_elements.h.
Referenced by oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), and oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::local_equation().
solid_p_nodal_index()
template<unsigned DIM>
virtual int oomph::PVDEquationsBase< DIM >::solid_p_nodal_index () const [inline], [virtual]
Return the index at which the solid pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in oomph::TPVDElementWithContinuousPressure< DIM >, and oomph::QPVDElementWithContinuousPressure< DIM >.
Definition at line 152 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::Solid_pressure_not_stored_at_node, and oomph::PVDEquationsBase< DIM >::unpin_elemental_solid_pressure_dofs().
Referenced by oomph::QPVDElementWithContinuousPressure< DIM >::fix_solid_pressure(), oomph::TPVDElementWithContinuousPressure< DIM >::fix_solid_pressure(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::further_setup_hanging_nodes(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures(), oomph::QPVDElementWithContinuousPressure< DIM >::set_solid_p(), oomph::TPVDElementWithContinuousPressure< DIM >::set_solid_p(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p(), oomph::TPVDElementWithContinuousPressure< DIM >::solid_p(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p_local_eqn(), oomph::TPVDElementWithContinuousPressure< DIM >::solid_p_local_eqn(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::QPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), and oomph::TPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs().
unpin_all_solid_pressure_dofs()
template<unsigned DIM>
static void oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 185 of file solid_elements.h.
References e, oomph::PVDEquationsBase< DIM >::get_deformed_covariant_basis_vectors(), oomph::PVDEquationsBase< DIM >::get_energy(), oomph::PVDEquationsBase< DIM >::get_principal_stress(), oomph::PVDEquationsBase< DIM >::get_strain(), oomph::PVDEquationsBase< DIM >::get_stress(), s, and oomph::PVDEquationsBase< DIM >::unpin_elemental_solid_pressure_dofs().
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM>
virtual void oomph::PVDEquationsBase< DIM >::unpin_elemental_solid_pressure_dofs () [pure virtual]
Unpin all solid pressure dofs in the element.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::PVDEquations< DIM >, and oomph::RefineableQPVDElementWithPressure< DIM >.
Referenced by oomph::PVDEquationsBase< DIM >::solid_p_nodal_index(), and oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs().
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM>
BodyForceFctPt oomph::PVDEquationsBase< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 384 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force_fct_pt(), oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
Constitutive_law_pt
template<unsigned DIM>
ConstitutiveLaw* oomph::PVDEquationsBase< DIM >::Constitutive_law_pt [protected]
Pointer to the constitutive law.
Definition at line 375 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::constitutive_law_pt(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquations< DIM >::get_d_stress_dG_upper(), oomph::PVDEquationsWithPressure< DIM >::get_d_stress_dG_upper(), oomph::PVDEquations< DIM >::get_stress(), and oomph::PVDEquationsWithPressure< DIM >::get_stress().
Default_lambda_sq_value
template<unsigned DIM>
double oomph::PVDEquationsBase< DIM >::Default_lambda_sq_value =1.0 [static], [protected]
Static default value for timescale ratio (1.0 -- for natural scaling)
Definition at line 387 of file solid_elements.h.
Evaluate_jacobian_by_fd
template<unsigned DIM>
bool oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd [protected]
Use FD to evaluate Jacobian.
Definition at line 390 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::disable_evaluate_jacobian_by_fd(), oomph::PVDEquationsBase< DIM >::enable_evaluate_jacobian_by_fd(), oomph::PVDEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), and oomph::PVDEquationsBase< DIM >::is_jacobian_evaluated_by_fd().
Isotropic_growth_fct_pt
template<unsigned DIM>
IsotropicGrowthFctPt oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt [protected]
Pointer to isotropic growth function.
Definition at line 369 of file solid_elements.h.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsBase< DIM >::get_isotropic_growth(), and oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt().
Lambda_sq_pt
template<unsigned DIM>
double* oomph::PVDEquationsBase< DIM >::Lambda_sq_pt [protected]
Timescale ratio (non-dim. density)
Definition at line 378 of file solid_elements.h.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsBase< DIM >::lambda_sq(), and oomph::PVDEquationsBase< DIM >::lambda_sq_pt().
Prestress_fct_pt
template<unsigned DIM>
PrestressFctPt oomph::PVDEquationsBase< DIM >::Prestress_fct_pt [protected]
Pointer to prestress function.
Definition at line 372 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::prestress(), and oomph::PVDEquationsBase< DIM >::prestress_fct_pt().
Solid_pressure_not_stored_at_node
template<unsigned DIM>
int oomph::PVDEquationsBase< DIM >::Solid_pressure_not_stored_at_node = -100 [static], [private]
Static `magic` number that indicates that the solid pressure is not stored at a node.
`Magic` number that indicates that the solid pressure is not stored at a node. It is a negative number that cannot be -1 because that is used to represent the positional hanging scheme in Hanging_pt objects
Definition at line 69 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
Unsteady
template<unsigned DIM>
bool oomph::PVDEquationsBase< DIM >::Unsteady [protected]
Flag that switches inertia on/off.
Definition at line 381 of file solid_elements.h.
Referenced by oomph::PVDEquationsBase< DIM >::disable_inertia(), oomph::PVDEquationsBase< DIM >::enable_inertia(), oomph::RefineablePVDEquations< DIM >::further_build(), oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), and oomph::PVDEquationsBase< DIM >::is_inertia_enabled().
The documentation for this class was generated from the following files:
solid_elements.h
solid_elements.cc