oomph::RefineableSolidQElement< 1 > Class Template Reference
Refineable version of Solid line elements.
#include <refineable_line_element.h>
Public Member Functions
RefineableSolidQElement ()
Constructor, just call the constructor of the RefineableQElement<1>
RefineableSolidQElement (const RefineableSolidQElement< 1 > &dummy)
Broken copy constructor.
virtual ~RefineableSolidQElement ()
Broken assignment operator.
void set_macro_elem_pt (MacroElement *macro_elem_pt)
Final over-ride: Use version in QSolidElementBase.
void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
Final over-ride: Use version in QSolidElementBase.
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Use the generic finite difference routine defined in RefineableSolidElement to calculate the Jacobian matrix.
void build (Mesh *&mesh_pt, Vector< Node *> &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
Build the element, i.e. give it nodal positions, apply BCs, etc. Incl. documention into new_nodes_file.
Additional Inherited Members
Detailed Description
template<>
class oomph::RefineableSolidQElement< 1 >
Refineable version of Solid line elements.
Definition at line 187 of file refineable_line_element.h.
Constructor & Destructor Documentation
RefineableSolidQElement() [1/2]
oomph::RefineableSolidQElement< 1 >::RefineableSolidQElement () [inline]
Constructor, just call the constructor of the RefineableQElement<1>
Definition at line 195 of file refineable_line_element.h.
References oomph::Global_string_for_annotation::string().
RefineableSolidQElement() [2/2]
oomph::RefineableSolidQElement< 1 >::RefineableSolidQElement (const RefineableSolidQElement< 1 > & dummy) [inline]
Broken copy constructor.
Definition at line 213 of file refineable_line_element.h.
References oomph::BrokenCopy::broken_copy().
 RefineableSolidQElement()
virtual oomph::RefineableSolidQElement< 1 >::~RefineableSolidQElement () [inline], [virtual]
Broken assignment operator.
Virtual Destructor
Definition at line 225 of file refineable_line_element.h.
Member Function Documentation
build()
void oomph::RefineableSolidQElement< 1 >::build (Mesh *& mesh_pt, Vector< Node *> & new_node_pt, bool & was_already_built, std::ofstream & new_nodes_file) [inline], [virtual]
Build the element, i.e. give it nodal positions, apply BCs, etc. Incl. documention into new_nodes_file.
Reimplemented from oomph::RefineableQElement< 1 >.
Definition at line 251 of file refineable_line_element.h.
get_jacobian()
void oomph::RefineableSolidQElement< 1 >::get_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Use the generic finite difference routine defined in RefineableSolidElement to calculate the Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 244 of file refineable_line_element.h.
References oomph::GeneralisedElement::get_jacobian().
set_macro_elem_pt() [1/2]
void oomph::RefineableSolidQElement< 1 >::set_macro_elem_pt (MacroElement * macro_elem_pt) [inline], [virtual]
Final over-ride: Use version in QSolidElementBase.
Reimplemented from oomph::QSolidElementBase.
Definition at line 229 of file refineable_line_element.h.
References oomph::QSolidElementBase::set_macro_elem_pt().
set_macro_elem_pt() [2/2]
void oomph::RefineableSolidQElement< 1 >::set_macro_elem_pt (MacroElement * macro_elem_pt, MacroElement * undeformed_macro_elem_pt) [inline], [virtual]
Final over-ride: Use version in QSolidElementBase.
Reimplemented from oomph::QSolidElementBase.
Definition at line 235 of file refineable_line_element.h.
References oomph::QSolidElementBase::set_macro_elem_pt().
The documentation for this class was generated from the following file:
refineable_line_element.h