oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <axisym_advection_diffusion_elements.h>
Public Types
typedef void(* AxisymAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
typedef void(* AxisymAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Public Member Functions
AxisymAdvectionDiffusionFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
AxisymAdvectionDiffusionFluxElement ()
Broken empty constructor.
AxisymAdvectionDiffusionFluxElement (const AxisymAdvectionDiffusionFluxElement &dummy)
Broken copy constructor.
AxisymAdvectionDiffusionPrescribedBetaFctPt & beta_fct_pt ()
Broken assignment operator.
AxisymAdvectionDiffusionPrescribedAlphaFctPt & alpha_fct_pt ()
Access function for the prescribed-alpha function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &nplot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_beta (const Vector< double > &x, double &beta)
Function to calculate the prescribed beta at a given spatial position.
void get_alpha (const Vector< double > &x, double &alpha)
Function to calculate the prescribed alpha at a given spatial position.
Private Member Functions
void fill_in_generic_residual_contribution_axi_adv_diff_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
AxisymAdvectionDiffusionPrescribedBetaFctPt Beta_fct_pt
Function pointer to the (global) prescribed-beta function.
AxisymAdvectionDiffusionPrescribedAlphaFctPt Alpha_fct_pt
Function pointer to the (global) prescribed-alpha function.
unsigned U_index_adv_diff
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 789 of file axisym_advection_diffusion_elements.h.
Member Typedef Documentation
AxisymAdvectionDiffusionPrescribedAlphaFctPt
template<class ELEMENT >
typedef void(* oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Definition at line 805 of file axisym_advection_diffusion_elements.h.
AxisymAdvectionDiffusionPrescribedBetaFctPt
template<class ELEMENT >
typedef void(* oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
Definition at line 799 of file axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
AxisymAdvectionDiffusionFluxElement() [1/3]
template<class ELEMENT >
oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Definition at line 1014 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt, oomph::FiniteElement::build_face_element(), oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux(), oomph::FiniteElement::has_hanging_nodes(), oomph::Global_string_for_annotation::string(), oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, and oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff().
AxisymAdvectionDiffusionFluxElement() [2/3]
template<class ELEMENT >
oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement () [inline]
Broken empty constructor.
Definition at line 817 of file axisym_advection_diffusion_elements.h.
AxisymAdvectionDiffusionFluxElement() [3/3]
template<class ELEMENT >
oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement (const AxisymAdvectionDiffusionFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 826 of file axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha_fct_pt()
template<class ELEMENT >
AxisymAdvectionDiffusionPrescribedAlphaFctPt& oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::alpha_fct_pt () [inline]
Access function for the prescribed-alpha function pointer.
Definition at line 845 of file axisym_advection_diffusion_elements.h.
beta_fct_pt()
template<class ELEMENT >
AxisymAdvectionDiffusionPrescribedBetaFctPt& oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::beta_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-beta function pointer
Definition at line 839 of file axisym_advection_diffusion_elements.h.
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 864 of file axisym_advection_diffusion_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 852 of file axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_residual_contribution_axi_adv_diff_flux()
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix for the Robin boundary condition:
 \Delta u \cdot \mathbf{n} + \alpha (\mathbf{x}) = \beta (\mathbf{x}) 
.
Definition at line 1097 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::get_alpha(), oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::get_beta(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), s, oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement().
get_alpha()
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::get_alpha (const Vector< double > & x, double & alpha) [inline], [protected]
Function to calculate the prescribed alpha at a given spatial position.
Definition at line 966 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux().
get_beta()
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::get_beta (const Vector< double > & x, double & beta) [inline], [protected]
Function to calculate the prescribed beta at a given spatial position.
Definition at line 950 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux().
output() [1/2]
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 886 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 893 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 904 of file axisym_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 928 of file axisym_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
zeta_nodal()
template<class ELEMENT >
double oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 878 of file axisym_advection_diffusion_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Alpha_fct_pt
template<class ELEMENT >
AxisymAdvectionDiffusionPrescribedAlphaFctPt oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::Alpha_fct_pt [private]
Function pointer to the (global) prescribed-alpha function.
Definition at line 994 of file axisym_advection_diffusion_elements.h.
Beta_fct_pt
template<class ELEMENT >
AxisymAdvectionDiffusionPrescribedBetaFctPt oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt [private]
Function pointer to the (global) prescribed-beta function.
Definition at line 991 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement().
U_index_adv_diff
template<class ELEMENT >
unsigned oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff [private]
The index at which the unknown is stored at the nodes.
Definition at line 997 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement(), and oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_axi_adv_diff_flux().
The documentation for this class was generated from the following file:
axisym_advection_diffusion_elements.h