oomph::ProjectablePoissonElement< POISSON_ELEMENT > Class Template Reference
Poisson upgraded to become projectable.
#include <poisson_elements.h>
Public Member Functions
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just one.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field (includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class POISSON_ELEMENT>
class oomph::ProjectablePoissonElement< POISSON_ELEMENT >
Poisson upgraded to become projectable.
Definition at line 816 of file poisson_elements.h.
Member Function Documentation
data_values_of_field()
template<class POISSON_ELEMENT >
Vector<std::pair<Data*,unsigned> > oomph::ProjectablePoissonElement< POISSON_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 825 of file poisson_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class POISSON_ELEMENT >
double oomph::ProjectablePoissonElement< POISSON_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 922 of file poisson_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::PoissonEquations< DIM >::u_index_poisson().
jacobian_and_shape_of_field()
template<class POISSON_ELEMENT >
double oomph::ProjectablePoissonElement< POISSON_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 892 of file poisson_elements.h.
References oomph::FiniteElement::dim(), oomph::PoissonEquations< DIM >::dshape_and_dtest_eulerian_poisson(), and oomph::FiniteElement::nnode().
local_equation()
template<class POISSON_ELEMENT >
int oomph::ProjectablePoissonElement< POISSON_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 984 of file poisson_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), and oomph::PoissonEquations< DIM >::u_index_poisson().
nfields_for_projection()
template<class POISSON_ELEMENT >
unsigned oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just one.
Implements oomph::ProjectableElementBase.
Definition at line 858 of file poisson_elements.h.
nhistory_values_for_coordinate_projection()
template<class POISSON_ELEMENT >
unsigned oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 885 of file poisson_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class POISSON_ELEMENT >
unsigned oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field (includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 865 of file poisson_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class POISSON_ELEMENT >
unsigned oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 964 of file poisson_elements.h.
References oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
poisson_elements.h