oomph::TrilinosMLPreconditioner Class Reference
An interface to the Trilinos ML class - provides a function to construct a serial ML object, and functions to modify some of the ML paramaters.
#include <trilinos_preconditioners.h>
Public Member Functions
TrilinosMLPreconditioner ()
Constructor. Build with Smooth Aggretation (SA) default settings, but our own default number of V cycles (initialised to 1 to replicate TrilinosML's own behaviour).
virtual ~TrilinosMLPreconditioner ()
Destructor empty -- clean up is done in base class.
TrilinosMLPreconditioner (const TrilinosMLPreconditioner &)
Broken copy constructor.
void set_NSSA_default_values ()
Broken assignment operator.
void set_DD_default_values ()
Set control flags to values for classical smoothed aggregation- based 2-level domain decomposition.
void set_DDML_default_values ()
Set control flags to values 3-level algebraic domain decomposition.
void set_SA_default_values ()
Set control flags to values for classical smoothed aggregation preconditioning.
void set_max_levels (int max_levels)
Function to set maximum number of levels.
void set_n_cycles (int n_cycles)
Function to set the number of cycles used.
void set_smoother_damping (double smoother_damping)
Function to set Smoother_damping.
void set_smoother_sweeps (int smoother_sweeps)
Function to set Smoother_sweeps.
void set_smoother_jacobi ()
Function to set smoother type to `Jacobi`.
void set_smoother_gauss_seidel ()
Function to set smoother type to `symmetric Gauss-Seidel`.
void set_output (int output)
Function to set output - controls level of information output by ML.
Static Public Attributes
static int Default_n_cycles =1
Default number of V cycles (one to be consistent with previous default) (It's an int because Trilinos wants it to be!)
Protected Member Functions
void setup_trilinos_preconditioner (Epetra_CrsMatrix *epetra_matrix_pt)
Function to set up the ML preconditioner. It is assumed Trilinos_matrix_pt points to a suitable matrix.
Protected Attributes
Teuchos::ParameterList ML_parameters
Detailed Description
An interface to the Trilinos ML class - provides a function to construct a serial ML object, and functions to modify some of the ML paramaters.
Definition at line 165 of file trilinos_preconditioners.h.
Constructor & Destructor Documentation
TrilinosMLPreconditioner() [1/2]
oomph::TrilinosMLPreconditioner::TrilinosMLPreconditioner () [inline]
Constructor. Build with Smooth Aggretation (SA) default settings, but our own default number of V cycles (initialised to 1 to replicate TrilinosML's own behaviour).
Definition at line 172 of file trilinos_preconditioners.h.
 TrilinosMLPreconditioner()
virtual oomph::TrilinosMLPreconditioner::~TrilinosMLPreconditioner () [inline], [virtual]
Destructor empty -- clean up is done in base class.
Definition at line 182 of file trilinos_preconditioners.h.
TrilinosMLPreconditioner() [2/2]
oomph::TrilinosMLPreconditioner::TrilinosMLPreconditioner (const TrilinosMLPreconditioner &) [inline]
Broken copy constructor.
Definition at line 185 of file trilinos_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
set_DD_default_values()
void oomph::TrilinosMLPreconditioner::set_DD_default_values () [inline]
Set control flags to values for classical smoothed aggregation- based 2-level domain decomposition.
Definition at line 206 of file trilinos_preconditioners.h.
set_DDML_default_values()
void oomph::TrilinosMLPreconditioner::set_DDML_default_values () [inline]
Set control flags to values 3-level algebraic domain decomposition.
Definition at line 213 of file trilinos_preconditioners.h.
set_max_levels()
void oomph::TrilinosMLPreconditioner::set_max_levels (int max_levels) [inline]
Function to set maximum number of levels.
Definition at line 226 of file trilinos_preconditioners.h.
set_n_cycles()
void oomph::TrilinosMLPreconditioner::set_n_cycles (int n_cycles) [inline]
Function to set the number of cycles used.
Definition at line 232 of file trilinos_preconditioners.h.
set_NSSA_default_values()
void oomph::TrilinosMLPreconditioner::set_NSSA_default_values () [inline]
Broken assignment operator.
Set control flags to values for Petrov-Galerkin preconditioning - for non symmetric systems
Definition at line 198 of file trilinos_preconditioners.h.
set_output()
void oomph::TrilinosMLPreconditioner::set_output (int output) [inline]
Function to set output - controls level of information output by ML.
Definition at line 262 of file trilinos_preconditioners.h.
set_SA_default_values()
void oomph::TrilinosMLPreconditioner::set_SA_default_values () [inline]
Set control flags to values for classical smoothed aggregation preconditioning.
Definition at line 220 of file trilinos_preconditioners.h.
set_smoother_damping()
void oomph::TrilinosMLPreconditioner::set_smoother_damping (double smoother_damping) [inline]
Function to set Smoother_damping.
Definition at line 238 of file trilinos_preconditioners.h.
set_smoother_gauss_seidel()
void oomph::TrilinosMLPreconditioner::set_smoother_gauss_seidel () [inline]
Function to set smoother type to `symmetric Gauss-Seidel`.
Definition at line 256 of file trilinos_preconditioners.h.
set_smoother_jacobi()
void oomph::TrilinosMLPreconditioner::set_smoother_jacobi () [inline]
Function to set smoother type to `Jacobi`.
Definition at line 250 of file trilinos_preconditioners.h.
set_smoother_sweeps()
void oomph::TrilinosMLPreconditioner::set_smoother_sweeps (int smoother_sweeps) [inline]
Function to set Smoother_sweeps.
Definition at line 244 of file trilinos_preconditioners.h.
setup_trilinos_preconditioner()
void oomph::TrilinosMLPreconditioner::setup_trilinos_preconditioner (Epetra_CrsMatrix * epetra_matrix_pt) [protected], [virtual]
Function to set up the ML preconditioner. It is assumed Trilinos_matrix_pt points to a suitable matrix.
Implements oomph::TrilinosPreconditionerBase.
Definition at line 209 of file trilinos_preconditioners.cc.
References oomph::TrilinosPreconditionerBase::Epetra_preconditioner_pt, oomph::oomph_info, oomph::TrilinosIFPACKPreconditioner::setup_trilinos_preconditioner(), and oomph::TimingHelpers::timer().
Referenced by oomph::TrilinosPreconditionerBase::preconditioner_solve().
Member Data Documentation
Default_n_cycles
int oomph::TrilinosMLPreconditioner::Default_n_cycles =1 [static]
Default number of V cycles (one to be consistent with previous default) (It's an int because Trilinos wants it to be!)
(Static) default number of V cycles (one to be consistent with previous default). (It's an int because Trilinos wants it to be!)
Definition at line 270 of file trilinos_preconditioners.h.
Referenced by oomph::TrilinosPreconditionerBase::preconditioner_solve().
ML_parameters
Teuchos::ParameterList oomph::TrilinosMLPreconditioner::ML_parameters [protected]
Definition at line 279 of file trilinos_preconditioners.h.
The documentation for this class was generated from the following files:
trilinos_preconditioners.h
trilinos_preconditioners.cc