oomph::ExactSubBiharmonicPreconditioner Class Reference
Sub Biharmonic Preconditioner - an exact preconditioner for the 3x3 top left hand corner sub block matrix. Used as part of the BiharmonicPreconditioner<MATRIX> . By default this uses the BBD (block-bordered-diagonal/arrow-shaped) preconditioner; can also switch to full BD version (in which case all the 3x3 blocks are retained)
#include <biharmonic_preconditioner.h>
Public Member Functions
ExactSubBiharmonicPreconditioner (BiharmonicPreconditioner *master_prec_pt, const bool &retain_all_blocks=false)
Constructor - for a preconditioner acting as a sub preconditioner.
~ExactSubBiharmonicPreconditioner ()
destructor deletes the exact preconditioner
void clean_up_memory ()
delete the subsidiary preconditioner pointer
ExactSubBiharmonicPreconditioner (const ExactSubBiharmonicPreconditioner &)
Broken copy constructor.
void operator= (const ExactSubBiharmonicPreconditioner &)
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
Public Attributes
Preconditioner * Sub_preconditioner_pt
bool Retain_all_blocks
Boolean indicating that all blocks are to be retained (defaults to false)
Additional Inherited Members
Detailed Description
Sub Biharmonic Preconditioner - an exact preconditioner for the 3x3 top left hand corner sub block matrix. Used as part of the BiharmonicPreconditioner<MATRIX> . By default this uses the BBD (block-bordered-diagonal/arrow-shaped) preconditioner; can also switch to full BD version (in which case all the 3x3 blocks are retained)
Definition at line 204 of file biharmonic_preconditioner.h.
Constructor & Destructor Documentation
ExactSubBiharmonicPreconditioner() [1/2]
oomph::ExactSubBiharmonicPreconditioner::ExactSubBiharmonicPreconditioner (BiharmonicPreconditioner * master_prec_pt, const bool & retain_all_blocks = false) [inline]
Constructor - for a preconditioner acting as a sub preconditioner.
Definition at line 211 of file biharmonic_preconditioner.h.
 ExactSubBiharmonicPreconditioner()
oomph::ExactSubBiharmonicPreconditioner::~ExactSubBiharmonicPreconditioner () [inline]
destructor deletes the exact preconditioner
Definition at line 230 of file biharmonic_preconditioner.h.
ExactSubBiharmonicPreconditioner() [2/2]
oomph::ExactSubBiharmonicPreconditioner::ExactSubBiharmonicPreconditioner (const ExactSubBiharmonicPreconditioner &) [inline]
Broken copy constructor.
Definition at line 242 of file biharmonic_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
void oomph::ExactSubBiharmonicPreconditioner::clean_up_memory () [inline], [virtual]
delete the subsidiary preconditioner pointer
Reimplemented from oomph::Preconditioner.
Definition at line 236 of file biharmonic_preconditioner.h.
operator=()
void oomph::ExactSubBiharmonicPreconditioner::operator= (const ExactSubBiharmonicPreconditioner &) [inline]
Broken assignment operator.
Definition at line 248 of file biharmonic_preconditioner.h.
References oomph::BrokenCopy::broken_assign(), and oomph::TerminateHelper::setup().
preconditioner_solve()
void oomph::ExactSubBiharmonicPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
preconditioner solve for the exact sub biharmonic preconditioner
Implements oomph::Preconditioner.
Definition at line 347 of file biharmonic_preconditioner.cc.
Referenced by setup().
setup()
void oomph::ExactSubBiharmonicPreconditioner::setup () [virtual]
Setup the preconditioner.
setup for the exact sub biharmonic preconditioner
Implements oomph::Preconditioner.
Definition at line 284 of file biharmonic_preconditioner.cc.
References preconditioner_solve(), and oomph::SuperLUPreconditioner::setup().
Member Data Documentation
Retain_all_blocks
bool oomph::ExactSubBiharmonicPreconditioner::Retain_all_blocks
Boolean indicating that all blocks are to be retained (defaults to false)
Definition at line 266 of file biharmonic_preconditioner.h.
Sub_preconditioner_pt
Preconditioner* oomph::ExactSubBiharmonicPreconditioner::Sub_preconditioner_pt
Definition at line 262 of file biharmonic_preconditioner.h.
The documentation for this class was generated from the following files:
biharmonic_preconditioner.h
biharmonic_preconditioner.cc