oomph::AxisymmetricTCrouzeixRaviartElement Class Reference
#include <Taxisym_navier_stokes_elements.h>
Public Member Functions
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
void unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
AxisymmetricTCrouzeixRaviartElement ()
Constructor, there are 3 internal values (for the pressure)
AxisymmetricTCrouzeixRaviartElement (const AxisymmetricTCrouzeixRaviartElement &dummy)
Broken copy constructor.
virtual unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
double p_axi_nst (const unsigned &i) const
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as unenriched shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_axi_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Protected Attributes
unsigned P_axi_nst_internal_index
Additional Inherited Members
Detailed Description
AxisymmetricTCrouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions enriched by a single cubic bubble function, but a discontinuous linear pressure interpolation
Definition at line 64 of file Taxisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
AxisymmetricTCrouzeixRaviartElement() [1/2]
oomph::AxisymmetricTCrouzeixRaviartElement::AxisymmetricTCrouzeixRaviartElement () [inline]
Constructor, there are 3 internal values (for the pressure)
Definition at line 136 of file Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data().
AxisymmetricTCrouzeixRaviartElement() [2/2]
oomph::AxisymmetricTCrouzeixRaviartElement::AxisymmetricTCrouzeixRaviartElement (const AxisymmetricTCrouzeixRaviartElement & dummy) [inline]
Broken copy constructor.
Definition at line 145 of file Taxisym_navier_stokes_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dpshape_and_dptest_eulerian_axi_nst()
double oomph::AxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Definition at line 479 of file Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), and oomph::FiniteElement::transform_derivatives().
Referenced by pshape_axi_nst().
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
double oomph::AxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 402 of file Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by dshape_and_dtest_eulerian_axi_nst().
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
double oomph::AxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 426 of file Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
dshape_and_dtest_eulerian_axi_nst()
double oomph::AxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 381 of file Taxisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_at_knot_axi_nst(), and oomph::FiniteElement::dshape_eulerian().
Referenced by get_dof_numbers_for_unknowns().
fix_pressure()
void oomph::AxisymmetricTCrouzeixRaviartElement::fix_pressure (const unsigned & p_dof, const double & p_value) [inline]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Definition at line 178 of file Taxisym_navier_stokes_elements.h.
References identify_load_data(), identify_pressure_data(), oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::AxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 306 of file Taxisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Data::nvalue(), and p_local_eqn().
get_Z2_flux()
void oomph::AxisymmetricTCrouzeixRaviartElement::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 251 of file Taxisym_navier_stokes_elements.h.
References i, and oomph::AxisymmetricNavierStokesEquations::strain_rate().
identify_load_data()
void oomph::AxisymmetricTCrouzeixRaviartElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Add to the set paired_load_data pairs of pointers to data objects and unsignedegers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 70 of file Taxisym_navier_stokes_elements.cc.
References i, identify_pressure_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst().
Referenced by fix_pressure(), oomph::AxisymmetricTTaylorHoodElement::fix_pressure(), and unpin_all_internal_pressure_dofs().
identify_pressure_data()
void oomph::AxisymmetricTCrouzeixRaviartElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressue_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
Definition at line 103 of file Taxisym_navier_stokes_elements.cc.
References oomph::AxisymmetricTTaylorHoodElement::Initial_Nvalue, oomph::GeneralisedElement::internal_data_pt(), oomph::GeneralisedElement::ninternal_data(), oomph::Data::nvalue(), and oomph::AxisymmetricTTaylorHoodElement::Pconv.
Referenced by fix_pressure(), oomph::AxisymmetricTTaylorHoodElement::fix_pressure(), identify_load_data(), and oomph::AxisymmetricTTaylorHoodElement::identify_load_data().
ndof_types()
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 295 of file Taxisym_navier_stokes_elements.h.
npres_axi_nst()
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::npres_axi_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 175 of file Taxisym_navier_stokes_elements.h.
Referenced by get_dof_numbers_for_unknowns(), oomph::AxisymmetricTTaylorHoodElement::identify_pressure_data(), unpin_all_internal_pressure_dofs(), and oomph::AxisymmetricTTaylorHoodElement::unpin_proper_nodal_pressure_dofs().
nrecovery_order()
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as unenriched shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 232 of file Taxisym_navier_stokes_elements.h.
num_Z2_flux_terms()
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 243 of file Taxisym_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 235 of file Taxisym_navier_stokes_elements.h.
output() [1/4]
void oomph::AxisymmetricTCrouzeixRaviartElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 214 of file Taxisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::AxisymmetricTCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 218 of file Taxisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::AxisymmetricTCrouzeixRaviartElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 222 of file Taxisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::AxisymmetricTCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 226 of file Taxisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
p_axi_nst()
double oomph::AxisymmetricTCrouzeixRaviartElement::p_axi_nst (const unsigned & i) const [inline], [virtual]
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 171 of file Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_local_eqn()
int oomph::AxisymmetricTCrouzeixRaviartElement::p_local_eqn (const unsigned & n) const [inline], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 130 of file Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn().
Referenced by get_dof_numbers_for_unknowns().
pshape_axi_nst() [1/2]
void oomph::AxisymmetricTCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 450 of file Taxisym_navier_stokes_elements.h.
Referenced by pshape_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::pshape_axi_nst(), and oomph::AxisymmetricTTaylorHoodElement::required_nvalue().
pshape_axi_nst() [2/2]
void oomph::AxisymmetricTCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 462 of file Taxisym_navier_stokes_elements.h.
References dpshape_and_dptest_eulerian_axi_nst(), and pshape_axi_nst().
required_nvalue()
virtual unsigned oomph::AxisymmetricTCrouzeixRaviartElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Number of values (pinned or dofs) required at local node n.
Reimplemented from oomph::FiniteElement.
Definition at line 164 of file Taxisym_navier_stokes_elements.h.
Referenced by oomph::AxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns().
unpin_all_internal_pressure_dofs()
void oomph::AxisymmetricTCrouzeixRaviartElement::unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
Definition at line 48 of file Taxisym_navier_stokes_elements.cc.
References identify_load_data(), oomph::GeneralisedElement::internal_data_pt(), npres_axi_nst(), P_axi_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt()
Node* oomph::AxisymmetricTCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 239 of file Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt().
Member Data Documentation
P_axi_nst_internal_index
unsigned oomph::AxisymmetricTCrouzeixRaviartElement::P_axi_nst_internal_index [protected]
Internal index that indicates at which internal datum the pressure is stored
Definition at line 74 of file Taxisym_navier_stokes_elements.h.
Referenced by unpin_all_internal_pressure_dofs().
The documentation for this class was generated from the following files:
Taxisym_navier_stokes_elements.h
Taxisym_navier_stokes_elements.cc