oomph::NavierStokesTractionElement< ELEMENT > Class Template Reference
#include <fluid_traction_elements.h>
Public Member Functions
NavierStokesTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
~NavierStokesTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Public Attributes
void(*&)(const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) traction_fct_pt ()
Protected Member Functions
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Function to calculate the traction applied to the fluid.
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Protected Attributes
unsigned Dim
The highest dimension of the problem.
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 58 of file fluid_traction_elements.h.
Constructor & Destructor Documentation
NavierStokesTractionElement()
template<class ELEMENT >
oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit
Definition at line 136 of file fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::NavierStokesTractionElement< ELEMENT >::Traction_fct_pt.
 NavierStokesTractionElement()
template<class ELEMENT >
oomph::NavierStokesTractionElement< ELEMENT >::~NavierStokesTractionElement () [inline]
Destructor should not delete anything.
Definition at line 181 of file fluid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableNavierStokesTractionElement< ELEMENT >.
Definition at line 198 of file fluid_traction_elements.h.
References oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesTractionElement< ELEMENT >.
Definition at line 189 of file fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_generic_residual_contribution_fluid_traction()
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Function that returns the residuals for the imposed traction Navier_Stokes equations
Definition at line 229 of file fluid_traction_elements.h.
References oomph::NavierStokesTractionElement< ELEMENT >::Dim, oomph::NavierStokesTractionElement< ELEMENT >::get_traction(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::NavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::NavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::NavierStokesTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesTractionElement< ELEMENT >::output().
get_traction()
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 104 of file fluid_traction_elements.h.
References oomph::NavierStokesTractionElement< ELEMENT >::Dim, oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), i, and oomph::NavierStokesTractionElement< ELEMENT >::Traction_fct_pt.
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
output() [1/2]
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 206 of file fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::NavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 209 of file fluid_traction_elements.h.
References oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::FiniteElement::output().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::NavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 88 of file fluid_traction_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
u_local_eqn()
template<class ELEMENT >
virtual int oomph::NavierStokesTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 83 of file fluid_traction_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
zeta_nodal()
template<class ELEMENT >
double oomph::NavierStokesTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [protected], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 74 of file fluid_traction_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::NavierStokesTractionElement< ELEMENT >::Dim [protected]
The highest dimension of the problem.
Definition at line 130 of file fluid_traction_elements.h.
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesTractionElement< ELEMENT >::get_traction(), and oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
Traction_fct_pt
template<class ELEMENT >
void(* oomph::NavierStokesTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 65 of file fluid_traction_elements.h.
Referenced by oomph::NavierStokesTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double& t, const Vector<double>& x, const Vector<double> &n, Vector<double>& result) oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt() [inline]
Definition at line 184 of file fluid_traction_elements.h.
The documentation for this class was generated from the following file:
fluid_traction_elements.h