oomph::SphericalAdvectionDiffusionEquations Class Reference
A class for all elements that solve the Advection Diffusion equations in a spherical polar coordinate system using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
#include <spherical_advection_diffusion_elements.h>
Public Types
typedef void(* SphericalAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
typedef void(* SphericalAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Public Member Functions
SphericalAdvectionDiffusionEquations ()
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
SphericalAdvectionDiffusionEquations (const SphericalAdvectionDiffusionEquations &dummy)
Broken copy constructor.
void operator= (const SphericalAdvectionDiffusionEquations &)
Broken assignment operator.
virtual unsigned u_index_spherical_adv_diff () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the spherical advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double du_dt_spherical_adv_diff (const unsigned &n) const
du/dt at local node n.
void disable_ALE ()
Disable ALE -- empty overload to suppress warning. ALE isn't implemented anyway.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: r,z,u at nplot^2 plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,u_exact at nplot^2 plot points.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
SphericalAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SphericalAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
SphericalAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
SphericalAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_spherical_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_wind_spherical_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux:
 \mbox{flux}[i] = \nabla u = \mbox{d}u / \mbox{d} r + 1/r \mbox{d}u / \mbox{d} \theta 
.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper) and mass matrix.
double interpolated_u_spherical_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_spherical_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_spherical_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_spherical_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
SphericalAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
SphericalAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
Static Private Attributes
static double Default_peclet_number = 0.0
Static default value for the Peclet number.
Additional Inherited Members
Detailed Description
A class for all elements that solve the Advection Diffusion equations in a spherical polar coordinate system using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 61 of file spherical_advection_diffusion_elements.h.
Member Typedef Documentation
SphericalAdvectionDiffusionSourceFctPt
typedef void(* oomph::SphericalAdvectionDiffusionEquations::SphericalAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 69 of file spherical_advection_diffusion_elements.h.
SphericalAdvectionDiffusionWindFctPt
typedef void(* oomph::SphericalAdvectionDiffusionEquations::SphericalAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Definition at line 74 of file spherical_advection_diffusion_elements.h.
Constructor & Destructor Documentation
SphericalAdvectionDiffusionEquations() [1/2]
oomph::SphericalAdvectionDiffusionEquations::SphericalAdvectionDiffusionEquations () [inline]
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
Definition at line 80 of file spherical_advection_diffusion_elements.h.
References Default_peclet_number, Pe_pt, and PeSt_pt.
SphericalAdvectionDiffusionEquations() [2/2]
oomph::SphericalAdvectionDiffusionEquations::SphericalAdvectionDiffusionEquations (const SphericalAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 88 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error()
void oomph::SphericalAdvectionDiffusionEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 405 of file spherical_advection_diffusion_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_spherical_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output().
dinterpolated_u_adv_diff_ddata()
virtual void oomph::SphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
Reimplemented in oomph::RefineableSphericalAdvectionDiffusionEquations.
Definition at line 367 of file spherical_advection_diffusion_elements.h.
References dshape_and_dtest_eulerian_at_knot_spherical_adv_diff(), dshape_and_dtest_eulerian_spherical_adv_diff(), oomph::Data::eqn_number(), fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, self_test(), oomph::FiniteElement::shape(), and u_index_spherical_adv_diff().
disable_ALE()
void oomph::SphericalAdvectionDiffusionEquations::disable_ALE () [inline], [virtual]
Disable ALE -- empty overload to suppress warning. ALE isn't implemented anyway.
Reimplemented from oomph::FiniteElement.
Definition at line 142 of file spherical_advection_diffusion_elements.h.
dshape_and_dtest_eulerian_at_knot_spherical_adv_diff()
virtual double oomph::SphericalAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_spherical_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), fill_in_generic_residual_contribution_spherical_adv_diff(), and oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_spherical_adv_diff()
virtual double oomph::SphericalAdvectionDiffusionEquations::dshape_and_dtest_eulerian_spherical_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_adv_diff_ddata(), and oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output_fct().
du_dt_spherical_adv_diff()
double oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff (const unsigned & n) const [inline]
du/dt at local node n.
Uses suitably interpolated value for hanging nodes.
Definition at line 115 of file spherical_advection_diffusion_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_spherical_adv_diff(), and oomph::TimeStepper::weight().
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), and fill_in_generic_residual_contribution_spherical_adv_diff().
fill_in_contribution_to_jacobian()
void oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 308 of file spherical_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_spherical_adv_diff().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper) and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 320 of file spherical_advection_diffusion_elements.h.
References fill_in_generic_residual_contribution_spherical_adv_diff().
fill_in_contribution_to_residuals()
void oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 294 of file spherical_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_spherical_adv_diff().
fill_in_generic_residual_contribution_spherical_adv_diff()
void oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableSphericalAdvectionDiffusionEquations.
Definition at line 53 of file spherical_advection_diffusion_elements.cc.
References dshape_and_dtest_eulerian_at_knot_spherical_adv_diff(), du_dt_spherical_adv_diff(), get_source_spherical_adv_diff(), get_wind_spherical_adv_diff(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), pe(), pe_st(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, oomph::Data::time_stepper_pt(), u_index_spherical_adv_diff(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by dinterpolated_u_adv_diff_ddata(), fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
get_flux()
void oomph::SphericalAdvectionDiffusionEquations::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux:
 \mbox{flux}[i] = \nabla u = \mbox{d}u / \mbox{d} r + 1/r \mbox{d}u / \mbox{d} \theta 
.
Definition at line 263 of file spherical_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), and u_index_spherical_adv_diff().
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::get_Z2_flux().
get_source_spherical_adv_diff()
virtual void oomph::SphericalAdvectionDiffusionEquations::get_source_spherical_adv_diff (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 217 of file spherical_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), and fill_in_generic_residual_contribution_spherical_adv_diff().
get_wind_spherical_adv_diff()
virtual void oomph::SphericalAdvectionDiffusionEquations::get_wind_spherical_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 238 of file spherical_advection_diffusion_elements.h.
References i, and Wind_fct_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), fill_in_generic_residual_contribution_spherical_adv_diff(), and output().
interpolated_u_spherical_adv_diff()
double oomph::SphericalAdvectionDiffusionEquations::interpolated_u_spherical_adv_diff (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 335 of file spherical_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_spherical_adv_diff().
Referenced by compute_error(), and output().
operator=()
void oomph::SphericalAdvectionDiffusionEquations::operator= (const SphericalAdvectionDiffusionEquations &) [inline]
Broken assignment operator.
Definition at line 95 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
void oomph::SphericalAdvectionDiffusionEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Definition at line 145 of file spherical_advection_diffusion_elements.h.
Referenced by output(), and oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output().
output() [2/4]
void oomph::SphericalAdvectionDiffusionEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: r,z,u at nplot^2 plot points.
Output function:
r,z,u,w_r,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Definition at line 252 of file spherical_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), get_wind_spherical_adv_diff(), i, interpolated_u_spherical_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::SphericalAdvectionDiffusionEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Definition at line 157 of file spherical_advection_diffusion_elements.h.
References compute_error(), output(), and output_fct().
output() [4/4]
void oomph::SphericalAdvectionDiffusionEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Definition at line 309 of file spherical_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_spherical_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct()
void oomph::SphericalAdvectionDiffusionEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_exact at nplot^2 plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >.
Definition at line 352 of file spherical_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output(), and oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output_fct().
pe()
const double& oomph::SphericalAdvectionDiffusionEquations::pe () const [inline]
Peclet number.
Definition at line 202 of file spherical_advection_diffusion_elements.h.
References Pe_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), and fill_in_generic_residual_contribution_spherical_adv_diff().
pe_pt()
double* & oomph::SphericalAdvectionDiffusionEquations::pe_pt () [inline]
Pointer to Peclet number.
Definition at line 205 of file spherical_advection_diffusion_elements.h.
References Pe_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build().
pe_st()
const double& oomph::SphericalAdvectionDiffusionEquations::pe_st () const [inline]
Peclet number multiplied by Strouhal number.
Definition at line 208 of file spherical_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), and fill_in_generic_residual_contribution_spherical_adv_diff().
pe_st_pt()
double* & oomph::SphericalAdvectionDiffusionEquations::pe_st_pt () [inline]
Pointer to Peclet number multipled by Strouha number.
Definition at line 211 of file spherical_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build().
self_test()
unsigned oomph::SphericalAdvectionDiffusionEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 220 of file spherical_advection_diffusion_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by dinterpolated_u_adv_diff_ddata().
source_fct_pt() [1/2]
SphericalAdvectionDiffusionSourceFctPt& oomph::SphericalAdvectionDiffusionEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 181 of file spherical_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build().
source_fct_pt() [2/2]
SphericalAdvectionDiffusionSourceFctPt oomph::SphericalAdvectionDiffusionEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 186 of file spherical_advection_diffusion_elements.h.
References Source_fct_pt.
u_index_spherical_adv_diff()
virtual unsigned oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the spherical advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 107 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), dinterpolated_u_adv_diff_ddata(), du_dt_spherical_adv_diff(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), fill_in_generic_residual_contribution_spherical_adv_diff(), get_flux(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), interpolated_u_spherical_adv_diff(), and oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement().
wind_fct_pt() [1/2]
SphericalAdvectionDiffusionWindFctPt& oomph::SphericalAdvectionDiffusionEquations::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 191 of file spherical_advection_diffusion_elements.h.
References Wind_fct_pt.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build().
wind_fct_pt() [2/2]
SphericalAdvectionDiffusionWindFctPt oomph::SphericalAdvectionDiffusionEquations::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 196 of file spherical_advection_diffusion_elements.h.
References Wind_fct_pt.
Member Data Documentation
Default_peclet_number
double oomph::SphericalAdvectionDiffusionEquations::Default_peclet_number = 0.0 [static], [private]
Static default value for the Peclet number.
2D Steady Axisymmetric Advection Diffusion elements
Default value for Peclet number
Definition at line 468 of file spherical_advection_diffusion_elements.h.
Referenced by SphericalAdvectionDiffusionEquations().
Pe_pt
double* oomph::SphericalAdvectionDiffusionEquations::Pe_pt [protected]
Pointer to global Peclet number.
Definition at line 454 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build(), pe(), pe_pt(), and SphericalAdvectionDiffusionEquations().
PeSt_pt
double* oomph::SphericalAdvectionDiffusionEquations::PeSt_pt [protected]
Pointer to global Peclet number multiplied by Strouhal number.
Definition at line 457 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build(), pe_st(), pe_st_pt(), and SphericalAdvectionDiffusionEquations().
Source_fct_pt
SphericalAdvectionDiffusionSourceFctPt oomph::SphericalAdvectionDiffusionEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 460 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build(), get_source_spherical_adv_diff(), and source_fct_pt().
Wind_fct_pt
SphericalAdvectionDiffusionWindFctPt oomph::SphericalAdvectionDiffusionEquations::Wind_fct_pt [protected]
Pointer to wind function:
Definition at line 463 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::RefineableSphericalAdvectionDiffusionEquations::further_build(), get_wind_spherical_adv_diff(), and wind_fct_pt().
The documentation for this class was generated from the following files:
spherical_advection_diffusion_elements.h
spherical_advection_diffusion_elements.cc