oomph::RefineableYoungLaplaceEquations Class Reference
#include <refineable_young_laplace_elements.h>
Public Member Functions
RefineableYoungLaplaceEquations (const int &refine_level=0)
Constructor: Pass refinement level to refineable element (default 0 = root)
RefineableYoungLaplaceEquations (const RefineableYoungLaplaceEquations &dummy)
Broken copy constructor.
void operator= (const RefineableYoungLaplaceEquations &)
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual vector taking hanging nodes into account.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux from YoungLaplace equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy function pointers to spine and spine base functions from father. Kappa is passed across with set_kappa(...) to ensure that it's added to the element's external Data.
Additional Inherited Members
Detailed Description
Refineable version of YoungLaplace equations
Definition at line 60 of file refineable_young_laplace_elements.h.
Constructor & Destructor Documentation
RefineableYoungLaplaceEquations() [1/2]
oomph::RefineableYoungLaplaceEquations::RefineableYoungLaplaceEquations (const int & refine_level = 0) [inline]
Constructor: Pass refinement level to refineable element (default 0 = root)
Definition at line 68 of file refineable_young_laplace_elements.h.
RefineableYoungLaplaceEquations() [2/2]
oomph::RefineableYoungLaplaceEquations::RefineableYoungLaplaceEquations (const RefineableYoungLaplaceEquations & dummy) [inline]
Broken copy constructor.
Definition at line 76 of file refineable_young_laplace_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_residuals()
void oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Compute element residual vector taking hanging nodes into account.
`Simple` case
Spine case
Get the unnormalized normal
Tmp storage
Reimplemented from oomph::GeneralisedElement.
Definition at line 41 of file refineable_young_laplace_elements.cc.
References oomph::YoungLaplaceEquations::allocate_vector_of_vectors(), oomph::YoungLaplaceEquations::cross_product(), oomph::FiniteElement::dshape_eulerian_at_knot(), oomph::YoungLaplaceEquations::get_kappa(), oomph::YoungLaplaceEquations::get_spine(), oomph::YoungLaplaceEquations::get_spine_base(), oomph::Node::hanging_pt(), oomph::FiniteElement::integral_pt(), oomph::YoungLaplaceEquations::interpolated_u(), oomph::FiniteElement::interpolated_zeta(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::YoungLaplaceEquations::scalar_product(), oomph::YoungLaplaceEquations::scalar_times_vector(), oomph::YoungLaplaceEquations::two_norm(), oomph::YoungLaplaceEquations::u(), oomph::YoungLaplaceEquations::u_local_eqn(), oomph::YoungLaplaceEquations::use_spines(), oomph::YoungLaplaceEquations::vector_sum(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by operator=().
further_build()
void oomph::RefineableYoungLaplaceEquations::further_build () [inline], [virtual]
Further build: Copy function pointers to spine and spine base functions from father. Kappa is passed across with set_kappa(...) to ensure that it's added to the element's external Data.
Reimplemented from oomph::RefineableElement.
Definition at line 151 of file refineable_young_laplace_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::YoungLaplaceEquations::kappa_pt(), oomph::YoungLaplaceEquations::set_kappa(), oomph::YoungLaplaceEquations::spine_base_fct_pt(), oomph::YoungLaplaceEquations::Spine_base_fct_pt, oomph::YoungLaplaceEquations::spine_fct_pt(), and oomph::YoungLaplaceEquations::Spine_fct_pt.
get_interpolated_values() [1/2]
void oomph::RefineableYoungLaplaceEquations::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 102 of file refineable_young_laplace_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::shape(), and oomph::YoungLaplaceEquations::u().
Referenced by get_interpolated_values().
get_interpolated_values() [2/2]
void oomph::RefineableYoungLaplaceEquations::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 131 of file refineable_young_laplace_elements.h.
References get_interpolated_values().
get_Z2_flux()
void oomph::RefineableYoungLaplaceEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux from YoungLaplace equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 95 of file refineable_young_laplace_elements.h.
References oomph::YoungLaplaceEquations::get_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableYoungLaplaceEquations::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 91 of file refineable_young_laplace_elements.h.
operator=()
void oomph::RefineableYoungLaplaceEquations::operator= (const RefineableYoungLaplaceEquations &) [inline]
Broken assignment operator.
Definition at line 82 of file refineable_young_laplace_elements.h.
References oomph::BrokenCopy::broken_assign(), and fill_in_contribution_to_residuals().
The documentation for this class was generated from the following files:
refineable_young_laplace_elements.h
refineable_young_laplace_elements.cc