oomph::AxisymmetricPoroelasticityEquations Class Reference
Class implementing the generic maths of the axisym poroelasticity equations: axisym linear elasticity coupled with axisym Darcy equations (using Raviart-Thomas elements with both edge and internal degrees of freedom) including inertia in both.
#include <axisym_poroelasticity_elements.h>
Public Types
typedef void(* SourceFctPt) (const double &time, const Vector< double > &x, Vector< double > &f)
Source function pointer typedef.
typedef void(* MassSourceFctPt) (const double &time, const Vector< double > &x, double &f)
Mass source function pointer typedef.
Public Member Functions
AxisymmetricPoroelasticityEquations ()
Constructor.
const double & youngs_modulus () const
Access function to non-dim Young's modulus (ratio of actual Young's modulus to reference stress used to non-dim the equations. (const version)
double *& youngs_modulus_pt ()
Pointer to non-dim Young's modulus (ratio of actual Young's modulus to reference stress used to non-dim the equations.
const double & nu () const
Access function for Poisson's ratio.
double *& nu_pt ()
Access function for pointer to Poisson's ratio.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
const double & density_ratio () const
Access function for the density ratio (fluid to solid)
double *& density_ratio_pt ()
Access function for pointer to the density ratio (fluid to solid)
const double & permeability () const
Access function for the nondim permeability.
double *& permeability_pt ()
Access function for pointer to the nondim permeability.
const double & permeability_ratio () const
Access function for the ratio of the material's actual permeability to the permeability used in the non-dimensionalisation of the equations.
double *& permeability_ratio_pt ()
const double & alpha () const
Access function for alpha, the Biot parameter.
double *& alpha_pt ()
Access function for pointer to alpha, the Biot parameter.
const double & porosity () const
Access function for the porosity.
double *& porosity_pt ()
Access function for pointer to the porosity.
SourceFctPt & solid_body_force_fct_pt ()
Access function: Pointer to solid body force function.
SourceFctPt solid_body_force_fct_pt () const
Access function: Pointer to solid body force function (const version)
SourceFctPt & fluid_body_force_fct_pt ()
Access function: Pointer to fluid force function.
SourceFctPt fluid_body_force_fct_pt () const
Access function: Pointer to fluid force function (const version)
MassSourceFctPt & mass_source_fct_pt ()
Access function: Pointer to mass source function.
MassSourceFctPt mass_source_fct_pt () const
Access function: Pointer to mass source function (const version)
void solid_body_force (const double &time, const Vector< double > &x, Vector< double > &b) const
Indirect access to the solid body force function - returns 0 if no forcing function has been set.
void fluid_body_force (const double &time, const Vector< double > &x, Vector< double > &b) const
Indirect access to the fluid body force function - returns 0 if no forcing function has been set.
void mass_source (const double &time, const Vector< double > &x, double &b) const
Indirect access to the mass source function - returns 0 if no mass source function has been set.
virtual unsigned required_nvalue (const unsigned &n) const =0
Number of values required at node n.
virtual unsigned u_index_axisym_poroelasticity (const unsigned &j) const =0
Return the nodal index of the j-th solid displacement unknown.
virtual int q_edge_local_eqn (const unsigned &j) const =0
Return the equation number of the j-th edge (flux) degree of freedom.
virtual int q_internal_local_eqn (const unsigned &j) const =0
Return the equation number of the j-th internal degree of freedom.
virtual Vector< Data * > q_edge_data_pt () const =0
Return vector of pointers to the Data objects that store the edge flux values.
virtual Data * q_internal_data_pt () const =0
Return pointer to the Data object that stores the internal flux values.
virtual unsigned q_edge_index (const unsigned &j) const =0
Return the nodal index at which the jth edge unknown is stored.
virtual unsigned q_internal_index () const =0
Return the index of the internal data where the q internal degrees of freedom are stored.
virtual unsigned q_edge_node_number (const unsigned &j) const =0
Return the number of the node where the jth edge unknown is stored.
virtual double q_edge (const unsigned &j) const =0
Return the values of the j-th edge (flux) degree of freedom.
virtual double q_edge (const unsigned &t, const unsigned &j) const =0
Return the values of the j-th edge (flux) degree of freedom at time history level t.
virtual unsigned face_index_of_q_edge_basis_fct (const unsigned &j) const =0
Return the face index associated with j-th edge flux degree of freedom.
virtual unsigned face_index_of_edge (const unsigned &j) const =0
Return the face index associated with specified edge.
virtual void face_local_coordinate_of_flux_interpolation_point (const unsigned &edge, const unsigned &n, Vector< double > &s) const =0
Compute the face element coordinates of the nth flux interpolation point along an edge.
virtual double q_internal (const unsigned &j) const =0
Return the values of the j-th internal degree of freedom.
virtual double q_internal (const unsigned &t, const unsigned &j) const =0
Return the values of the j-th internal degree of freedom at time history level t.
virtual void set_q_edge (const unsigned &j, const double &value)=0
Set the values of the j-th edge (flux) degree of freedom.
virtual void set_q_internal (const unsigned &j, const double &value)=0
Set the values of the j-th internal degree of freedom.
virtual void set_q_edge (const unsigned &t, const unsigned &j, const double &value)=0
Set the values of the j-th edge (flux) degree of freedom at time history level t.
virtual void set_q_internal (const unsigned &t, const unsigned &j, const double &value)=0
Set the values of the j-th internal degree of freedom at time history level t.
virtual unsigned nq_basis () const
Return the total number of computational basis functions for q.
virtual unsigned nq_basis_edge () const =0
Return the number of edge basis functions for q.
virtual unsigned nq_basis_internal () const =0
Return the number of internal basis functions for q.
virtual void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const =0
Comute the local form of the q basis at local coordinate s.
virtual void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const =0
Compute the local form of the q basis and dbasis/ds at local coordinate s.
void get_q_basis (const Vector< double > &s, Shape &q_basis) const
Compute the transformed basis at local coordinate s.
virtual unsigned nedge_flux_interpolation_point () const =0
Returns the number of flux_interpolation points along each edge of the element.
virtual Vector< double > edge_flux_interpolation_point (const unsigned &edge, const unsigned &j) const =0
Returns the local coordinate of the jth flux_interpolation point along the specified edge.
virtual void edge_flux_interpolation_point_global (const unsigned &edge, const unsigned &j, Vector< double > &x) const =0
Compute the global coordinates of the jth flux_interpolation point along an edge.
virtual void pin_q_internal_value (const unsigned &j, const double &value)=0
Pin the jth internal q value and set it to specified value.
virtual void pin_q_edge_value (const unsigned &j, const double &value)=0
Pin the j-th edge (flux) degree of freedom and set it to specified value.
virtual int p_local_eqn (const unsigned &j) const =0
Return the equation number of the j-th pressure degree of freedom.
virtual double p_value (const unsigned &j) const =0
Return the jth pressure value.
virtual unsigned np_basis () const =0
Return the total number of pressure basis functions.
virtual void get_p_basis (const Vector< double > &s, Shape &p_basis) const =0
Compute the pressure basis.
virtual void pin_p_value (const unsigned &j, const double &p)=0
Pin the jth pressure value and set it to p.
virtual void set_p_value (const unsigned &j, const double &value)=0
Set the jth pressure value.
virtual Data * p_data_pt () const =0
Return pointer to the Data object that stores the pressure values.
virtual void scale_basis (Shape &basis) const =0
Scale the edge basis to allow arbitrary edge mappings.
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, DShape &dpsi, Shape &q_basis) const
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element.
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, Shape &q_basis) const
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in contribution to residuals for the Darcy equations.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the Jacobian matrix for the Newton method.
double interpolated_div_du_dt (const Vector< double > &s, Vector< double > &div_dudt_components) const
double interpolated_div_u (const Vector< double > &s, Vector< double > &div_u_components) const
void interpolated_u (const Vector< double > &s, Vector< double > &disp) const
Calculate the FE representation of u.
double interpolated_u (const Vector< double > &s, const unsigned &i) const
Calculate the FE representation of the i-th component of u.
double interpolated_u (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Calculate the FE representation of the i-th component of u at time level t (t=0: current)
void interpolated_du_dt (const Vector< double > &s, Vector< double > &du_dt) const
Calculate the FE representation of du_dt.
void interpolated_q (const Vector< double > &s, Vector< double > &q) const
Calculate the FE representation of q.
void interpolated_q (const unsigned &t, const Vector< double > &s, Vector< double > &q) const
Calculate the FE representation of q at time level t (t=0: current)
double interpolated_q (const Vector< double > &s, const unsigned i) const
Calculate the FE representation of the i-th component of q.
double interpolated_q (const unsigned &t, const Vector< double > &s, const unsigned i) const
void interpolated_div_q (const Vector< double > &s, double &div_q) const
Calculate the FE representation of div u.
double interpolated_div_q (const Vector< double > &s) const
Calculate the FE representation of div q and return it.
void interpolated_p (const Vector< double > &s, double &p) const
Calculate the FE representation of p.
double interpolated_p (const Vector< double > &s) const
Calculate the FE representation of p and return it.
double du_dt (const unsigned &n, const unsigned &i) const
du/dt at local node n
double d2u_dt2 (const unsigned &n, const unsigned &i) const
d^2u/dt^2 at local node n
double dq_edge_dt (const unsigned &n) const
dq_edge/dt for the n-th edge degree of freedom
double dq_internal_dt (const unsigned &n) const
dq_internal/dt for the n-th internal degree of freedom
void set_q_internal_timestepper (TimeStepper *const time_stepper_pt)
Set the timestepper of the q internal data object.
bool darcy_is_switched_off ()
Is Darcy flow switched off?
void switch_off_darcy ()
Switch off Darcy flow.
unsigned self_test ()
Self test.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: r,z,u_r,u_z,q_r,q_z,div_q,p,durdt,duzdt.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^2 plot points.
void output_with_projected_flux (std::ostream &outfile, const unsigned &nplot, const Vector< double > unit_normal)
Output incl. projection of fluxes into direction of the specified unit vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^2 plot points. Unsteady version.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p. Unsteady version.
unsigned num_Z2_flux_terms ()
Number off flux terms for Z2 error estimator (use Darcy flux)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Z2 flux (use Darcy flux)
Protected Member Functions
virtual double shape_basis_test_local (const Vector< double > &s, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const =0
Compute the geometric basis, and the q, p and divergence basis functions and test functions at local coordinate s.
virtual double shape_basis_test_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const =0
Compute the geometric basis, and the q, p and divergence basis functions and test functions at integration point ipt.
virtual void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, bool flag)
Fill in residuals and, if flag==true, jacobian.
Private Attributes
SourceFctPt Solid_body_force_fct_pt
Pointer to solid body force function.
SourceFctPt Fluid_body_force_fct_pt
Pointer to fluid source function.
MassSourceFctPt Mass_source_fct_pt
Pointer to the mass source function.
double * Youngs_modulus_pt
Pointer to the nondim Young's modulus.
double * Nu_pt
Pointer to Poisson's ratio.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
double * Density_ratio_pt
Density ratio.
double * Permeability_pt
permeability
double * Permeability_ratio_pt
Ratio of the material's actual permeability to the permeability used in the non-dimensionalisation of the equations.
double * Alpha_pt
Alpha -- the biot parameter.
double * Porosity_pt
Porosity.
bool Darcy_is_switched_off
Boolean to record that darcy has been switched off.
Static Private Attributes
static double Default_youngs_modulus_value
static double Default_lambda_sq_value
Static default value for timescale ratio.
static double Default_density_ratio_value
Static default value for the density ratio.
static double Default_permeability_value
Static default value for the permeability (1.0 for natural scaling; i.e. timescale is given by L^2/(k^* E)
static double Default_permeability_ratio_value
Static default value for the ratio of the material's actual permeability to the permeability used to non-dimensionalise the equations.
static double Default_alpha_value
Static default value for alpha, the biot parameter.
static double Default_porosity_value
Static default value for the porosity.
Additional Inherited Members
Detailed Description
Class implementing the generic maths of the axisym poroelasticity equations: axisym linear elasticity coupled with axisym Darcy equations (using Raviart-Thomas elements with both edge and internal degrees of freedom) including inertia in both.
Definition at line 53 of file axisym_poroelasticity_elements.h.
Member Typedef Documentation
MassSourceFctPt
typedef void(* oomph::AxisymmetricPoroelasticityEquations::MassSourceFctPt) (const double &time, const Vector< double > &x, double &f)
Mass source function pointer typedef.
Definition at line 64 of file axisym_poroelasticity_elements.h.
SourceFctPt
typedef void(* oomph::AxisymmetricPoroelasticityEquations::SourceFctPt) (const double &time, const Vector< double > &x, Vector< double > &f)
Source function pointer typedef.
Definition at line 59 of file axisym_poroelasticity_elements.h.
Constructor & Destructor Documentation
AxisymmetricPoroelasticityEquations()
oomph::AxisymmetricPoroelasticityEquations::AxisymmetricPoroelasticityEquations () [inline]
Constructor.
Definition at line 69 of file axisym_poroelasticity_elements.h.
Member Function Documentation
alpha()
const double& oomph::AxisymmetricPoroelasticityEquations::alpha () const [inline]
Access function for alpha, the Biot parameter.
Definition at line 142 of file axisym_poroelasticity_elements.h.
References Alpha_pt.
Referenced by fill_in_generic_residual_contribution().
alpha_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::alpha_pt () [inline]
Access function for pointer to alpha, the Biot parameter.
Definition at line 145 of file axisym_poroelasticity_elements.h.
References Alpha_pt.
compute_error() [1/2]
void oomph::AxisymmetricPoroelasticityEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > & error, Vector< double > & norm) [virtual]
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p.
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for u and p.
Reimplemented from oomph::FiniteElement.
Definition at line 318 of file axisym_poroelasticity_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_div_q(), interpolated_p(), interpolated_q(), interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output().
compute_error() [2/2]
void oomph::AxisymmetricPoroelasticityEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm) [virtual]
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p. Unsteady version.
Compute the error between the FE solution and the exact solution using the H(div) norm for u and L^2 norm for p. Unsteady version.
Reimplemented from oomph::FiniteElement.
Definition at line 425 of file axisym_poroelasticity_elements.cc.
References fill_in_generic_residual_contribution(), i, oomph::FiniteElement::integral_pt(), interpolated_div_q(), interpolated_p(), interpolated_q(), interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
d2u_dt2()
double oomph::AxisymmetricPoroelasticityEquations::d2u_dt2 (const unsigned & n, const unsigned & i) const [inline]
d^2u/dt^2 at local node n
Definition at line 863 of file axisym_poroelasticity_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axisym_poroelasticity(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution().
darcy_is_switched_off()
bool oomph::AxisymmetricPoroelasticityEquations::darcy_is_switched_off () [inline]
Is Darcy flow switched off?
Definition at line 960 of file axisym_poroelasticity_elements.h.
References Darcy_is_switched_off.
density_ratio()
const double& oomph::AxisymmetricPoroelasticityEquations::density_ratio () const [inline]
Access function for the density ratio (fluid to solid)
Definition at line 121 of file axisym_poroelasticity_elements.h.
References Density_ratio_pt.
Referenced by fill_in_generic_residual_contribution().
density_ratio_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::density_ratio_pt () [inline]
Access function for pointer to the density ratio (fluid to solid)
Definition at line 124 of file axisym_poroelasticity_elements.h.
References Density_ratio_pt.
dq_edge_dt()
double oomph::AxisymmetricPoroelasticityEquations::dq_edge_dt (const unsigned & n) const [inline]
dq_edge/dt for the n-th edge degree of freedom
Definition at line 893 of file axisym_poroelasticity_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), q_edge(), q_edge_node_number(), oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution().
dq_internal_dt()
double oomph::AxisymmetricPoroelasticityEquations::dq_internal_dt (const unsigned & n) const [inline]
dq_internal/dt for the n-th internal degree of freedom
Definition at line 922 of file axisym_poroelasticity_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::TimeStepper::is_steady(), oomph::TimeStepper::ntstorage(), q_internal(), q_internal_index(), oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution().
du_dt()
double oomph::AxisymmetricPoroelasticityEquations::du_dt (const unsigned & n, const unsigned & i) const [inline]
du/dt at local node n
Definition at line 833 of file axisym_poroelasticity_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axisym_poroelasticity(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution(), interpolated_div_du_dt(), interpolated_du_dt(), output(), point_output_data(), and scalar_value_paraview().
edge_flux_interpolation_point()
virtual Vector<double> oomph::AxisymmetricPoroelasticityEquations::edge_flux_interpolation_point (const unsigned & edge, const unsigned & j) const [pure virtual]
Returns the local coordinate of the jth flux_interpolation point along the specified edge.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis().
edge_flux_interpolation_point_global()
virtual void oomph::AxisymmetricPoroelasticityEquations::edge_flux_interpolation_point_global (const unsigned & edge, const unsigned & j, Vector< double > & x) const [pure virtual]
Compute the global coordinates of the jth flux_interpolation point along an edge.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis().
face_index_of_edge()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::face_index_of_edge (const unsigned & j) const [pure virtual]
Return the face index associated with specified edge.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
face_index_of_q_edge_basis_fct()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::face_index_of_q_edge_basis_fct (const unsigned & j) const [pure virtual]
Return the face index associated with j-th edge flux degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
face_local_coordinate_of_flux_interpolation_point()
virtual void oomph::AxisymmetricPoroelasticityEquations::face_local_coordinate_of_flux_interpolation_point (const unsigned & edge, const unsigned & n, Vector< double > & s) const [pure virtual]
Compute the face element coordinates of the nth flux interpolation point along an edge.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricPoroelasticityEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in the Jacobian matrix for the Newton method.
Reimplemented from oomph::GeneralisedElement.
Definition at line 413 of file axisym_poroelasticity_elements.h.
References fill_in_generic_residual_contribution().
fill_in_contribution_to_residuals()
void oomph::AxisymmetricPoroelasticityEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in contribution to residuals for the Darcy equations.
Reimplemented from oomph::GeneralisedElement.
Definition at line 406 of file axisym_poroelasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution().
fill_in_generic_residual_contribution()
void oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, bool flag) [protected], [virtual]
Fill in residuals and, if flag==true, jacobian.
Definition at line 533 of file axisym_poroelasticity_elements.cc.
References alpha(), d2u_dt2(), density_ratio(), dq_edge_dt(), dq_internal_dt(), du_dt(), fluid_body_force(), i, oomph::FiniteElement::integral_pt(), oomph::GeneralisedElement::internal_data_pt(), interpolated_p(), interpolated_q(), interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), lambda_sq(), mass_source(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), np_basis(), nq_basis(), nq_basis_edge(), nu(), oomph::Integral::nweight(), p_local_eqn(), p_value(), permeability(), permeability_ratio(), porosity(), q_edge(), q_edge_local_eqn(), q_edge_node_number(), q_internal(), q_internal_index(), q_internal_local_eqn(), oomph::FiniteElement::raw_nodal_value(), s, shape_basis_test_local_at_knot(), solid_body_force(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axisym_poroelasticity(), oomph::Integral::weight(), oomph::TimeStepper::weight(), and youngs_modulus().
Referenced by compute_error(), fill_in_contribution_to_jacobian(), fill_in_contribution_to_residuals(), and get_Z2_flux().
fluid_body_force()
void oomph::AxisymmetricPoroelasticityEquations::fluid_body_force (const double & time, const Vector< double > & x, Vector< double > & b) const [inline]
Indirect access to the fluid body force function - returns 0 if no forcing function has been set.
Definition at line 195 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dim(), Fluid_body_force_fct_pt, and i.
Referenced by fill_in_generic_residual_contribution().
fluid_body_force_fct_pt() [1/2]
SourceFctPt& oomph::AxisymmetricPoroelasticityEquations::fluid_body_force_fct_pt () [inline]
Access function: Pointer to fluid force function.
Definition at line 160 of file axisym_poroelasticity_elements.h.
References Fluid_body_force_fct_pt.
fluid_body_force_fct_pt() [2/2]
SourceFctPt oomph::AxisymmetricPoroelasticityEquations::fluid_body_force_fct_pt () const [inline]
Access function: Pointer to fluid force function (const version)
Definition at line 163 of file axisym_poroelasticity_elements.h.
References Fluid_body_force_fct_pt.
get_div_q_basis_local()
virtual void oomph::AxisymmetricPoroelasticityEquations::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const [pure virtual]
Compute the local form of the q basis and dbasis/ds at local coordinate s.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by interpolated_div_q(), and nq_basis().
get_p_basis()
virtual void oomph::AxisymmetricPoroelasticityEquations::get_p_basis (const Vector< double > & s, Shape & p_basis) const [pure virtual]
Compute the pressure basis.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and interpolated_p().
get_q_basis()
void oomph::AxisymmetricPoroelasticityEquations::get_q_basis (const Vector< double > & s, Shape & q_basis) const [inline]
Compute the transformed basis at local coordinate s.
Definition at line 325 of file axisym_poroelasticity_elements.h.
References edge_flux_interpolation_point(), edge_flux_interpolation_point_global(), get_p_basis(), get_q_basis_local(), nedge_flux_interpolation_point(), oomph::FiniteElement::nnode(), np_basis(), nq_basis(), p_data_pt(), p_local_eqn(), p_value(), pin_p_value(), pin_q_edge_value(), pin_q_internal_value(), scale_basis(), set_p_value(), and transform_basis().
Referenced by interpolated_q().
get_q_basis_local()
virtual void oomph::AxisymmetricPoroelasticityEquations::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const [pure virtual]
Comute the local form of the q basis at local coordinate s.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and nq_basis().
get_Z2_flux()
void oomph::AxisymmetricPoroelasticityEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Z2 flux (use Darcy flux)
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1231 of file axisym_poroelasticity_elements.h.
References fill_in_generic_residual_contribution(), interpolated_q(), shape_basis_test_local(), and shape_basis_test_local_at_knot().
interpolated_div_du_dt()
double oomph::AxisymmetricPoroelasticityEquations::interpolated_div_du_dt (const Vector< double > & s, Vector< double > & div_dudt_components) const [inline]
Calculate the FE representation of the divergence of the skeleton velocity, div(du/dt), and its components: 1/r diff(r*du_r/dt,r) and diff(du_z/dt,z).
Definition at line 423 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dshape_eulerian(), du_dt(), i, oomph::FiniteElement::interpolated_x(), and oomph::FiniteElement::nnode().
Referenced by point_output_data().
interpolated_div_q() [1/2]
void oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q (const Vector< double > & s, double & div_q) const [inline]
Calculate the FE representation of div u.
Definition at line 731 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dshape_local(), e, get_div_q_basis_local(), interpolated_q(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), nq_basis(), nq_basis_edge(), q_edge(), and q_internal().
Referenced by compute_error(), interpolated_div_q(), output(), point_output_data(), and scalar_value_paraview().
interpolated_div_q() [2/2]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q (const Vector< double > & s) const [inline]
Calculate the FE representation of div q and return it.
Definition at line 784 of file axisym_poroelasticity_elements.h.
References interpolated_div_q().
interpolated_div_u()
double oomph::AxisymmetricPoroelasticityEquations::interpolated_div_u (const Vector< double > & s, Vector< double > & div_u_components) const [inline]
Calculate the FE representation of the divergence of the skeleton displ, div(u), and its components: 1/r diff(r*u_r,r) and diff(u_z,z).
Definition at line 471 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axisym_poroelasticity().
Referenced by point_output_data().
interpolated_du_dt()
void oomph::AxisymmetricPoroelasticityEquations::interpolated_du_dt (const Vector< double > & s, Vector< double > & du_dt) const [inline]
Calculate the FE representation of du_dt.
Definition at line 610 of file axisym_poroelasticity_elements.h.
References du_dt(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by output(), point_output_data(), and scalar_value_paraview().
interpolated_p() [1/2]
void oomph::AxisymmetricPoroelasticityEquations::interpolated_p (const Vector< double > & s, double & p) const [inline]
Calculate the FE representation of p.
Definition at line 797 of file axisym_poroelasticity_elements.h.
References get_p_basis(), np_basis(), and p_value().
Referenced by compute_error(), fill_in_generic_residual_contribution(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::get_field(), interpolated_p(), output(), point_output_data(), and scalar_value_paraview().
interpolated_p() [2/2]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_p (const Vector< double > & s) const [inline]
Calculate the FE representation of p and return it.
Definition at line 820 of file axisym_poroelasticity_elements.h.
References interpolated_p().
interpolated_q() [1/4]
void oomph::AxisymmetricPoroelasticityEquations::interpolated_q (const Vector< double > & s, Vector< double > & q) const [inline]
Calculate the FE representation of q.
Definition at line 636 of file axisym_poroelasticity_elements.h.
References get_q_basis(), i, nq_basis(), nq_basis_edge(), q_edge(), and q_internal().
Referenced by compute_error(), fill_in_generic_residual_contribution(), get_Z2_flux(), interpolated_div_q(), output(), point_output_data(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), and scalar_value_paraview().
interpolated_q() [2/4]
void oomph::AxisymmetricPoroelasticityEquations::interpolated_q (const unsigned & t, const Vector< double > & s, Vector< double > & q) const [inline]
Calculate the FE representation of q at time level t (t=0: current)
Definition at line 659 of file axisym_poroelasticity_elements.h.
References get_q_basis(), i, nq_basis(), nq_basis_edge(), q_edge(), and q_internal().
interpolated_q() [3/4]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_q (const Vector< double > & s, const unsigned i) const [inline]
Calculate the FE representation of the i-th component of q.
Definition at line 682 of file axisym_poroelasticity_elements.h.
References get_q_basis(), nq_basis(), nq_basis_edge(), q_edge(), and q_internal().
interpolated_q() [4/4]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_q (const unsigned & t, const Vector< double > & s, const unsigned i) const [inline]
Calculate the FE representation of the i-th component of q at time level t (t=0: current)
Definition at line 706 of file axisym_poroelasticity_elements.h.
References get_q_basis(), nq_basis(), nq_basis_edge(), q_edge(), and q_internal().
interpolated_u() [1/3]
void oomph::AxisymmetricPoroelasticityEquations::interpolated_u (const Vector< double > & s, Vector< double > & disp) const [inline]
Calculate the FE representation of u.
Definition at line 521 of file axisym_poroelasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_axisym_poroelasticity().
Referenced by compute_error(), fill_in_generic_residual_contribution(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::get_field(), interpolated_u(), output(), point_output_data(), and scalar_value_paraview().
interpolated_u() [2/3]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_u (const Vector< double > & s, const unsigned & i) const [inline]
Calculate the FE representation of the i-th component of u.
Definition at line 550 of file axisym_poroelasticity_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_axisym_poroelasticity().
interpolated_u() [3/3]
double oomph::AxisymmetricPoroelasticityEquations::interpolated_u (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Calculate the FE representation of the i-th component of u at time level t (t=0: current)
Definition at line 580 of file axisym_poroelasticity_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_axisym_poroelasticity().
lambda_sq()
const double& oomph::AxisymmetricPoroelasticityEquations::lambda_sq () const [inline]
Access function for timescale ratio (nondim density)
Definition at line 115 of file axisym_poroelasticity_elements.h.
References Lambda_sq_pt.
Referenced by fill_in_generic_residual_contribution().
lambda_sq_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::lambda_sq_pt () [inline]
Access function for pointer to timescale ratio (nondim density)
Definition at line 118 of file axisym_poroelasticity_elements.h.
References Lambda_sq_pt.
mass_source()
void oomph::AxisymmetricPoroelasticityEquations::mass_source (const double & time, const Vector< double > & x, double & b) const [inline]
Indirect access to the mass source function - returns 0 if no mass source function has been set.
Definition at line 217 of file axisym_poroelasticity_elements.h.
References face_index_of_edge(), face_index_of_q_edge_basis_fct(), face_local_coordinate_of_flux_interpolation_point(), Mass_source_fct_pt, q_edge(), q_edge_data_pt(), q_edge_index(), q_edge_local_eqn(), q_edge_node_number(), q_internal(), q_internal_data_pt(), q_internal_index(), q_internal_local_eqn(), required_nvalue(), s, set_q_edge(), set_q_internal(), t, and u_index_axisym_poroelasticity().
Referenced by fill_in_generic_residual_contribution().
mass_source_fct_pt() [1/2]
MassSourceFctPt& oomph::AxisymmetricPoroelasticityEquations::mass_source_fct_pt () [inline]
Access function: Pointer to mass source function.
Definition at line 166 of file axisym_poroelasticity_elements.h.
References Mass_source_fct_pt.
mass_source_fct_pt() [2/2]
MassSourceFctPt oomph::AxisymmetricPoroelasticityEquations::mass_source_fct_pt () const [inline]
Access function: Pointer to mass source function (const version)
Definition at line 169 of file axisym_poroelasticity_elements.h.
References Mass_source_fct_pt.
nedge_flux_interpolation_point()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::nedge_flux_interpolation_point () const [pure virtual]
Returns the number of flux_interpolation points along each edge of the element.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), and get_q_basis().
np_basis()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::np_basis () const [pure virtual]
Return the total number of pressure basis functions.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), get_q_basis(), interpolated_p(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nvalue_of_field(), and switch_off_darcy().
nq_basis()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::nq_basis () const [inline], [virtual]
Return the total number of computational basis functions for q.
Definition at line 305 of file axisym_poroelasticity_elements.h.
References get_div_q_basis_local(), get_q_basis_local(), nq_basis_edge(), and nq_basis_internal().
Referenced by fill_in_generic_residual_contribution(), get_q_basis(), interpolated_div_q(), interpolated_q(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nvalue_of_field(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local(), and transform_basis().
nq_basis_edge()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::nq_basis_edge () const [pure virtual]
Return the number of edge basis functions for q.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), interpolated_div_q(), interpolated_q(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), nq_basis(), and switch_off_darcy().
nq_basis_internal()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::nq_basis_internal () const [pure virtual]
Return the number of internal basis functions for q.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, and oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), nq_basis(), and switch_off_darcy().
nscalar_paraview()
unsigned oomph::AxisymmetricPoroelasticityEquations::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 1004 of file axisym_poroelasticity_elements.h.
nu()
const double& oomph::AxisymmetricPoroelasticityEquations::nu () const [inline]
Access function for Poisson's ratio.
Definition at line 95 of file axisym_poroelasticity_elements.h.
References Nu_pt.
Referenced by fill_in_generic_residual_contribution().
nu_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::nu_pt () [inline]
Access function for pointer to Poisson's ratio.
Definition at line 112 of file axisym_poroelasticity_elements.h.
References Nu_pt.
num_Z2_flux_terms()
unsigned oomph::AxisymmetricPoroelasticityEquations::num_Z2_flux_terms () [inline], [virtual]
Number off flux terms for Z2 error estimator (use Darcy flux)
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1225 of file axisym_poroelasticity_elements.h.
output() [1/2]
void oomph::AxisymmetricPoroelasticityEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Definition at line 1177 of file axisym_poroelasticity_elements.h.
References compute_error(), output_fct(), and output_with_projected_flux().
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::output().
output() [2/2]
void oomph::AxisymmetricPoroelasticityEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^2 plot points.
Output FE representation of soln: x,y,u1,u2,q1,q2,div_q,p at Nplot^2 plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Definition at line 154 of file axisym_poroelasticity_elements.cc.
References du_dt(), oomph::FiniteElement::get_s_plot(), i, interpolated_div_q(), interpolated_du_dt(), interpolated_p(), interpolated_q(), interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::AxisymmetricPoroelasticityEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^2 plot points.
Output FE representation of exact soln at Nplot^2 plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 215 of file axisym_poroelasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output().
output_fct() [2/2]
void oomph::AxisymmetricPoroelasticityEquations::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^2 plot points. Unsteady version.
Output FE representation of exact soln at Nplot^2 plot points. Unsteady version.
Reimplemented from oomph::FiniteElement.
Definition at line 266 of file axisym_poroelasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_with_projected_flux()
void oomph::AxisymmetricPoroelasticityEquations::output_with_projected_flux (std::ostream & outfile, const unsigned & nplot, const Vector< double > unit_normal)
Output incl. projection of fluxes into direction of the specified unit vector.
Referenced by output().
p_data_pt()
virtual Data* oomph::AxisymmetricPoroelasticityEquations::p_data_pt () const [pure virtual]
Return pointer to the Data object that stores the pressure values.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), and get_q_basis().
p_local_eqn()
virtual int oomph::AxisymmetricPoroelasticityEquations::p_local_eqn (const unsigned & j) const [pure virtual]
Return the equation number of the j-th pressure degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), get_q_basis(), and oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation().
p_value()
virtual double oomph::AxisymmetricPoroelasticityEquations::p_value (const unsigned & j) const [pure virtual]
Return the jth pressure value.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), get_q_basis(), and interpolated_p().
permeability()
const double& oomph::AxisymmetricPoroelasticityEquations::permeability () const [inline]
Access function for the nondim permeability.
Definition at line 127 of file axisym_poroelasticity_elements.h.
References Permeability_pt.
Referenced by fill_in_generic_residual_contribution().
permeability_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::permeability_pt () [inline]
Access function for pointer to the nondim permeability.
Definition at line 130 of file axisym_poroelasticity_elements.h.
References Permeability_pt.
permeability_ratio()
const double& oomph::AxisymmetricPoroelasticityEquations::permeability_ratio () const [inline]
Access function for the ratio of the material's actual permeability to the permeability used in the non-dimensionalisation of the equations.
Definition at line 135 of file axisym_poroelasticity_elements.h.
References Permeability_ratio_pt.
Referenced by fill_in_generic_residual_contribution().
permeability_ratio_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::permeability_ratio_pt () [inline]
Access function for pointer to ratio of the material's actual permeability to the permeability used in the non-dimensionalisation of the equations
Definition at line 139 of file axisym_poroelasticity_elements.h.
References Permeability_ratio_pt.
pin_p_value()
virtual void oomph::AxisymmetricPoroelasticityEquations::pin_p_value (const unsigned & j, const double & p) [pure virtual]
Pin the jth pressure value and set it to p.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and switch_off_darcy().
pin_q_edge_value()
virtual void oomph::AxisymmetricPoroelasticityEquations::pin_q_edge_value (const unsigned & j, const double & value) [pure virtual]
Pin the j-th edge (flux) degree of freedom and set it to specified value.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and switch_off_darcy().
pin_q_internal_value()
virtual void oomph::AxisymmetricPoroelasticityEquations::pin_q_internal_value (const unsigned & j, const double & value) [pure virtual]
Pin the jth internal q value and set it to specified value.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and switch_off_darcy().
point_output_data()
void oomph::AxisymmetricPoroelasticityEquations::point_output_data (const Vector< double > & s, Vector< double > & data) [inline], [virtual]
Output solution in data vector at local cordinates s: r,z,u_r,u_z,q_r,q_z,div_q,p,durdt,duzdt.
Reimplemented from oomph::FiniteElement.
Definition at line 1129 of file axisym_poroelasticity_elements.h.
References du_dt(), i, interpolated_div_du_dt(), interpolated_div_q(), interpolated_div_u(), interpolated_du_dt(), interpolated_p(), interpolated_q(), interpolated_u(), and oomph::FiniteElement::interpolated_x().
porosity()
const double& oomph::AxisymmetricPoroelasticityEquations::porosity () const [inline]
Access function for the porosity.
Definition at line 148 of file axisym_poroelasticity_elements.h.
References Porosity_pt.
Referenced by fill_in_generic_residual_contribution().
porosity_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::porosity_pt () [inline]
Access function for pointer to the porosity.
Definition at line 151 of file axisym_poroelasticity_elements.h.
References Porosity_pt.
q_edge() [1/2]
virtual double oomph::AxisymmetricPoroelasticityEquations::q_edge (const unsigned & j) const [pure virtual]
Return the values of the j-th edge (flux) degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by dq_edge_dt(), fill_in_generic_residual_contribution(), interpolated_div_q(), interpolated_q(), and mass_source().
q_edge() [2/2]
virtual double oomph::AxisymmetricPoroelasticityEquations::q_edge (const unsigned & t, const unsigned & j) const [pure virtual]
Return the values of the j-th edge (flux) degree of freedom at time history level t.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
q_edge_data_pt()
virtual Vector<Data*> oomph::AxisymmetricPoroelasticityEquations::q_edge_data_pt () const [pure virtual]
Return vector of pointers to the Data objects that store the edge flux values.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), and mass_source().
q_edge_index()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::q_edge_index (const unsigned & j) const [pure virtual]
Return the nodal index at which the jth edge unknown is stored.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), and mass_source().
q_edge_local_eqn()
virtual int oomph::AxisymmetricPoroelasticityEquations::q_edge_local_eqn (const unsigned & j) const [pure virtual]
Return the equation number of the j-th edge (flux) degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), and mass_source().
q_edge_node_number()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::q_edge_node_number (const unsigned & j) const [pure virtual]
Return the number of the node where the jth edge unknown is stored.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by dq_edge_dt(), fill_in_generic_residual_contribution(), and mass_source().
q_internal() [1/2]
virtual double oomph::AxisymmetricPoroelasticityEquations::q_internal (const unsigned & j) const [pure virtual]
Return the values of the j-th internal degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by dq_internal_dt(), fill_in_generic_residual_contribution(), interpolated_div_q(), interpolated_q(), and mass_source().
q_internal() [2/2]
virtual double oomph::AxisymmetricPoroelasticityEquations::q_internal (const unsigned & t, const unsigned & j) const [pure virtual]
Return the values of the j-th internal degree of freedom at time history level t.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
q_internal_data_pt()
virtual Data* oomph::AxisymmetricPoroelasticityEquations::q_internal_data_pt () const [pure virtual]
Return pointer to the Data object that stores the internal flux values.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), and mass_source().
q_internal_index()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::q_internal_index () const [pure virtual]
Return the index of the internal data where the q internal degrees of freedom are stored.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by dq_internal_dt(), fill_in_generic_residual_contribution(), mass_source(), and set_q_internal_timestepper().
q_internal_local_eqn()
virtual int oomph::AxisymmetricPoroelasticityEquations::q_internal_local_eqn (const unsigned & j) const [pure virtual]
Return the equation number of the j-th internal degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), and mass_source().
required_nvalue()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::required_nvalue (const unsigned & n) const [pure virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
scalar_name_paraview()
std::string oomph::AxisymmetricPoroelasticityEquations::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 1075 of file axisym_poroelasticity_elements.h.
scalar_value_paraview()
void oomph::AxisymmetricPoroelasticityEquations::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 1011 of file axisym_poroelasticity_elements.h.
References du_dt(), oomph::FiniteElement::get_s_plot(), interpolated_div_q(), interpolated_du_dt(), interpolated_p(), interpolated_q(), interpolated_u(), oomph::FiniteElement::nplot_points_paraview(), and s.
scale_basis()
virtual void oomph::AxisymmetricPoroelasticityEquations::scale_basis (Shape & basis) const [pure virtual]
Scale the edge basis to allow arbitrary edge mappings.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis(), and transform_basis().
self_test()
unsigned oomph::AxisymmetricPoroelasticityEquations::self_test () [inline], [virtual]
Self test.
Reimplemented from oomph::FiniteElement.
Definition at line 996 of file axisym_poroelasticity_elements.h.
set_p_value()
virtual void oomph::AxisymmetricPoroelasticityEquations::set_p_value (const unsigned & j, const double & value) [pure virtual]
Set the jth pressure value.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_q_basis().
set_q_edge() [1/2]
virtual void oomph::AxisymmetricPoroelasticityEquations::set_q_edge (const unsigned & j, const double & value) [pure virtual]
Set the values of the j-th edge (flux) degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
set_q_edge() [2/2]
virtual void oomph::AxisymmetricPoroelasticityEquations::set_q_edge (const unsigned & t, const unsigned & j, const double & value) [pure virtual]
Set the values of the j-th edge (flux) degree of freedom at time history level t.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
set_q_internal() [1/2]
virtual void oomph::AxisymmetricPoroelasticityEquations::set_q_internal (const unsigned & j, const double & value) [pure virtual]
Set the values of the j-th internal degree of freedom.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by mass_source().
set_q_internal() [2/2]
virtual void oomph::AxisymmetricPoroelasticityEquations::set_q_internal (const unsigned & t, const unsigned & j, const double & value) [pure virtual]
Set the values of the j-th internal degree of freedom at time history level t.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
set_q_internal_timestepper()
void oomph::AxisymmetricPoroelasticityEquations::set_q_internal_timestepper (TimeStepper *const time_stepper_pt) [inline]
Set the timestepper of the q internal data object.
Definition at line 952 of file axisym_poroelasticity_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), q_internal_index(), and oomph::Data::set_time_stepper().
shape_basis_test_local()
virtual double oomph::AxisymmetricPoroelasticityEquations::shape_basis_test_local (const Vector< double > & s, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const [protected], [pure virtual]
Compute the geometric basis, and the q, p and divergence basis functions and test functions at local coordinate s.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by get_Z2_flux(), and oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field().
shape_basis_test_local_at_knot()
virtual double oomph::AxisymmetricPoroelasticityEquations::shape_basis_test_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const [protected], [pure virtual]
Compute the geometric basis, and the q, p and divergence basis functions and test functions at integration point ipt.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by fill_in_generic_residual_contribution(), and get_Z2_flux().
solid_body_force()
void oomph::AxisymmetricPoroelasticityEquations::solid_body_force (const double & time, const Vector< double > & x, Vector< double > & b) const [inline]
Indirect access to the solid body force function - returns 0 if no forcing function has been set.
Definition at line 173 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dim(), i, and Solid_body_force_fct_pt.
Referenced by fill_in_generic_residual_contribution().
solid_body_force_fct_pt() [1/2]
SourceFctPt& oomph::AxisymmetricPoroelasticityEquations::solid_body_force_fct_pt () [inline]
Access function: Pointer to solid body force function.
Definition at line 154 of file axisym_poroelasticity_elements.h.
References Solid_body_force_fct_pt.
solid_body_force_fct_pt() [2/2]
SourceFctPt oomph::AxisymmetricPoroelasticityEquations::solid_body_force_fct_pt () const [inline]
Access function: Pointer to solid body force function (const version)
Definition at line 157 of file axisym_poroelasticity_elements.h.
References Solid_body_force_fct_pt.
switch_off_darcy()
void oomph::AxisymmetricPoroelasticityEquations::switch_off_darcy () [inline]
Switch off Darcy flow.
Definition at line 967 of file axisym_poroelasticity_elements.h.
References Darcy_is_switched_off, np_basis(), nq_basis_edge(), nq_basis_internal(), pin_p_value(), pin_q_edge_value(), and pin_q_internal_value().
transform_basis() [1/2]
double oomph::AxisymmetricPoroelasticityEquations::transform_basis (const Vector< double > & s, const Shape & q_basis_local, Shape & psi, DShape & dpsi, Shape & q_basis) const
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element.
Definition at line 89 of file axisym_poroelasticity_elements.cc.
References oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::local_to_eulerian_mapping(), nq_basis(), scale_basis(), and oomph::FiniteElement::transform_derivatives().
Referenced by get_q_basis(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local(), and transform_basis().
transform_basis() [2/2]
double oomph::AxisymmetricPoroelasticityEquations::transform_basis (const Vector< double > & s, const Shape & q_basis_local, Shape & psi, Shape & q_basis) const [inline]
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element.
Definition at line 395 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::nnode(), and transform_basis().
u_index_axisym_poroelasticity()
virtual unsigned oomph::AxisymmetricPoroelasticityEquations::u_index_axisym_poroelasticity (const unsigned & j) const [pure virtual]
Return the nodal index of the j-th solid displacement unknown.
Implemented in oomph::TAxisymmetricPoroelasticityElement< ORDER >.
Referenced by d2u_dt2(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), du_dt(), fill_in_generic_residual_contribution(), interpolated_div_u(), interpolated_u(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), and mass_source().
youngs_modulus()
const double& oomph::AxisymmetricPoroelasticityEquations::youngs_modulus () const [inline]
Access function to non-dim Young's modulus (ratio of actual Young's modulus to reference stress used to non-dim the equations. (const version)
Definition at line 88 of file axisym_poroelasticity_elements.h.
References Youngs_modulus_pt.
Referenced by fill_in_generic_residual_contribution().
youngs_modulus_pt()
double* & oomph::AxisymmetricPoroelasticityEquations::youngs_modulus_pt () [inline]
Pointer to non-dim Young's modulus (ratio of actual Young's modulus to reference stress used to non-dim the equations.
Definition at line 92 of file axisym_poroelasticity_elements.h.
References Youngs_modulus_pt.
Member Data Documentation
Alpha_pt
double* oomph::AxisymmetricPoroelasticityEquations::Alpha_pt [private]
Alpha -- the biot parameter.
Definition at line 1307 of file axisym_poroelasticity_elements.h.
Referenced by alpha(), and alpha_pt().
Darcy_is_switched_off
bool oomph::AxisymmetricPoroelasticityEquations::Darcy_is_switched_off [private]
Boolean to record that darcy has been switched off.
Definition at line 1313 of file axisym_poroelasticity_elements.h.
Referenced by darcy_is_switched_off(), and switch_off_darcy().
Default_alpha_value
double oomph::AxisymmetricPoroelasticityEquations::Default_alpha_value [static], [private]
Static default value for alpha, the biot parameter.
Definition at line 1339 of file axisym_poroelasticity_elements.h.
Default_density_ratio_value
double oomph::AxisymmetricPoroelasticityEquations::Default_density_ratio_value [static], [private]
Static default value for the density ratio.
Definition at line 1327 of file axisym_poroelasticity_elements.h.
Default_lambda_sq_value
double oomph::AxisymmetricPoroelasticityEquations::Default_lambda_sq_value [static], [private]
Static default value for timescale ratio.
Definition at line 1324 of file axisym_poroelasticity_elements.h.
Default_permeability_ratio_value
double oomph::AxisymmetricPoroelasticityEquations::Default_permeability_ratio_value [static], [private]
Static default value for the ratio of the material's actual permeability to the permeability used to non-dimensionalise the equations.
Definition at line 1336 of file axisym_poroelasticity_elements.h.
Default_permeability_value
double oomph::AxisymmetricPoroelasticityEquations::Default_permeability_value [static], [private]
Static default value for the permeability (1.0 for natural scaling; i.e. timescale is given by L^2/(k^* E)
Definition at line 1331 of file axisym_poroelasticity_elements.h.
Default_porosity_value
double oomph::AxisymmetricPoroelasticityEquations::Default_porosity_value [static], [private]
Static default value for the porosity.
Definition at line 1342 of file axisym_poroelasticity_elements.h.
Default_youngs_modulus_value
double oomph::AxisymmetricPoroelasticityEquations::Default_youngs_modulus_value [static], [private]
Static default value for Young's modulus (1.0 -- for natural scaling, i.e. all stresses have been non-dimensionalised by the same reference Young's modulus. Setting the `non-dimensional` Young's modulus (obtained by de-referencing Youngs_modulus_pt) to a number larger than one means that the material is stiffer than assumed in the non-dimensionalisation.
Definition at line 1321 of file axisym_poroelasticity_elements.h.
Density_ratio_pt
double* oomph::AxisymmetricPoroelasticityEquations::Density_ratio_pt [private]
Density ratio.
Definition at line 1297 of file axisym_poroelasticity_elements.h.
Referenced by density_ratio(), and density_ratio_pt().
Fluid_body_force_fct_pt
SourceFctPt oomph::AxisymmetricPoroelasticityEquations::Fluid_body_force_fct_pt [private]
Pointer to fluid source function.
Definition at line 1282 of file axisym_poroelasticity_elements.h.
Referenced by fluid_body_force(), and fluid_body_force_fct_pt().
Lambda_sq_pt
double* oomph::AxisymmetricPoroelasticityEquations::Lambda_sq_pt [private]
Timescale ratio (non-dim. density)
Definition at line 1294 of file axisym_poroelasticity_elements.h.
Referenced by lambda_sq(), and lambda_sq_pt().
Mass_source_fct_pt
MassSourceFctPt oomph::AxisymmetricPoroelasticityEquations::Mass_source_fct_pt [private]
Pointer to the mass source function.
Definition at line 1285 of file axisym_poroelasticity_elements.h.
Referenced by mass_source(), and mass_source_fct_pt().
Nu_pt
double* oomph::AxisymmetricPoroelasticityEquations::Nu_pt [private]
Pointer to Poisson's ratio.
Definition at line 1291 of file axisym_poroelasticity_elements.h.
Referenced by nu(), and nu_pt().
Permeability_pt
double* oomph::AxisymmetricPoroelasticityEquations::Permeability_pt [private]
permeability
Definition at line 1300 of file axisym_poroelasticity_elements.h.
Referenced by permeability(), and permeability_pt().
Permeability_ratio_pt
double* oomph::AxisymmetricPoroelasticityEquations::Permeability_ratio_pt [private]
Ratio of the material's actual permeability to the permeability used in the non-dimensionalisation of the equations.
Definition at line 1304 of file axisym_poroelasticity_elements.h.
Referenced by permeability_ratio(), and permeability_ratio_pt().
Porosity_pt
double* oomph::AxisymmetricPoroelasticityEquations::Porosity_pt [private]
Porosity.
Definition at line 1310 of file axisym_poroelasticity_elements.h.
Referenced by porosity(), and porosity_pt().
Solid_body_force_fct_pt
SourceFctPt oomph::AxisymmetricPoroelasticityEquations::Solid_body_force_fct_pt [private]
Pointer to solid body force function.
Definition at line 1279 of file axisym_poroelasticity_elements.h.
Referenced by solid_body_force(), and solid_body_force_fct_pt().
Youngs_modulus_pt
double* oomph::AxisymmetricPoroelasticityEquations::Youngs_modulus_pt [private]
Pointer to the nondim Young's modulus.
Definition at line 1288 of file axisym_poroelasticity_elements.h.
Referenced by youngs_modulus(), and youngs_modulus_pt().
The documentation for this class was generated from the following files:
axisym_poroelasticity_elements.h
axisym_poroelasticity_elements.cc