oomph::NetFluxControlElementForWomersleyPressureControl Class Reference
#include <womersley_elements.h>
Public Member Functions
NetFluxControlElementForWomersleyPressureControl (Mesh *flux_control_mesh_pt, NavierStokesWomersleyPressureControlElement *pressure_control_element_pt)
Constructor takes the mesh of TemplateFreeNavierStokesFluxControlElementBase which impose the pressure to controls the flux, plus a pointer to the PressureControlElement whoes internal data is the prescribed flux.
~NetFluxControlElementForWomersleyPressureControl ()
Empty Destructor - Data gets deleted automatically.
NetFluxControlElementForWomersleyPressureControl (const NetFluxControlElementForWomersleyPressureControl &dummy)
Broken copy constructor.
void operator= (const NetFluxControlElementForWomersleyPressureControl &)
Broken assignment operator.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into - set to 1.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Additional Inherited Members
Detailed Description
A class for an element to control net fluid flux across a boundary by imposing an applied pressure to the Navier-Stokes equations. This element is used with a mesh of NavierStokesFluxControlElements attached to the boundary. The flux imposed by this element is given by a NavierStokesWomersleyPressureControlElement. Note: fill_in_contribution_to_jacobian() does not calculate any Jacobian contributions for this element as they are calculated by NavierStokesFluxControlElement::fill_in_contribution_to_jacobian(...) and NavierStokesWomersleyPressureControlElement:: fill_in_contribution_to_jacobian(...)
Definition at line 2813 of file womersley_elements.h.
Constructor & Destructor Documentation
NetFluxControlElementForWomersleyPressureControl() [1/2]
oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl (Mesh * flux_control_mesh_pt, NavierStokesWomersleyPressureControlElement * pressure_control_element_pt) [inline]
Constructor takes the mesh of TemplateFreeNavierStokesFluxControlElementBase which impose the pressure to controls the flux, plus a pointer to the PressureControlElement whoes internal data is the prescribed flux.
Definition at line 2823 of file womersley_elements.h.
References oomph::NavierStokesWomersleyPressureControlElement::add_pressure_data().
 NetFluxControlElementForWomersleyPressureControl()
oomph::NetFluxControlElementForWomersleyPressureControl::~NetFluxControlElementForWomersleyPressureControl () [inline]
Empty Destructor - Data gets deleted automatically.
Definition at line 2841 of file womersley_elements.h.
NetFluxControlElementForWomersleyPressureControl() [2/2]
oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl (const NetFluxControlElementForWomersleyPressureControl & dummy) [inline]
Broken copy constructor.
Definition at line 2844 of file womersley_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_dof_numbers_for_unknowns()
void oomph::NetFluxControlElementForWomersleyPressureControl::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::NetFluxControlElement.
Definition at line 2874 of file womersley_elements.h.
ndof_types()
unsigned oomph::NetFluxControlElementForWomersleyPressureControl::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into - set to 1.
Reimplemented from oomph::NetFluxControlElement.
Definition at line 2863 of file womersley_elements.h.
operator=()
void oomph::NetFluxControlElementForWomersleyPressureControl::operator= (const NetFluxControlElementForWomersleyPressureControl &) [inline]
Broken assignment operator.
Definition at line 2854 of file womersley_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
womersley_elements.h