oomph::QSpectralPoissonElement< DIM, NNODE_1D > Class Template Reference
#include <spectral_poisson_elements.h>
Public Member Functions
QSpectralPoissonElement ()
Constructor: Call constructors for QSpectralElement and Poisson equations.
QSpectralPoissonElement (const QSpectralPoissonElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QSpectralPoissonElement< DIM, NNODE_1D >
QSpectralPoissonElement elements are linear/quadrilateral/brick-shaped Poisson elements with isoparametric spectral interpolation for the function. Note that the implementation is PoissonEquations<DIM> does not use sum factorisation for the evaluation of the residuals and is, therefore, not optimal for higher dimensions.
Definition at line 54 of file spectral_poisson_elements.h.
Constructor & Destructor Documentation
QSpectralPoissonElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QSpectralPoissonElement< DIM, NNODE_1D >::QSpectralPoissonElement () [inline]
Constructor: Call constructors for QSpectralElement and Poisson equations.
Definition at line 69 of file spectral_poisson_elements.h.
QSpectralPoissonElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QSpectralPoissonElement< DIM, NNODE_1D >::QSpectralPoissonElement (const QSpectralPoissonElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 74 of file spectral_poisson_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_poisson() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 210 of file spectral_poisson_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson(), and oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_at_knot_poisson() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 238 of file spectral_poisson_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
dshape_and_dtest_eulerian_poisson()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 176 of file spectral_poisson_elements.h.
References oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output_fct().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 96 of file spectral_poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 101 of file spectral_poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 107 of file spectral_poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 113 of file spectral_poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 119 of file spectral_poisson_elements.h.
References oomph::PoissonEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 128 of file spectral_poisson_elements.h.
References oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson(), oomph::QSpectralPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson(), oomph::PoissonEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QSpectralPoissonElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 91 of file spectral_poisson_elements.h.
References oomph::QSpectralPoissonElement< DIM, NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QSpectralPoissonElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 62 of file spectral_poisson_elements.h.
Referenced by oomph::QSpectralPoissonElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
spectral_poisson_elements.h
spectral_poisson_elements.cc