oomph::TriangleMeshOpenCurve Class Reference
#include <unstructured_two_d_mesh_geometry_base.h>
Public Member Functions
TriangleMeshOpenCurve (const Vector< TriangleMeshCurveSection *> &curve_section_pt)
Constructor.
virtual ~TriangleMeshOpenCurve ()
Empty destructor.
unsigned nvertices () const
Number of vertices.
unsigned nsegments () const
Total number of segments.
void output (std::ostream &outfile, const unsigned &n_sample=50)
Output each sub-boundary at n_sample (default: 50) points.
TriangleMeshPolyLine * polyline_pt (const unsigned &i) const
Pointer to i-th constituent polyline.
TriangleMeshPolyLine * polyline_pt (const unsigned &i)
Pointer to i-th constituent polyline.
Additional Inherited Members
Detailed Description
Base class defining an open curve for the Triangle mesh generation Basically used to define internal boundaries on the mesh
Definition at line 1512 of file unstructured_two_d_mesh_geometry_base.h.
Constructor & Destructor Documentation
TriangleMeshOpenCurve()
oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve (const Vector< TriangleMeshCurveSection *> & curve_section_pt)
Constructor.
Class defining an open curve for the Triangle mesh generation.
Definition at line 1870 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshCurve::Curve_section_pt, i, oomph::TriangleMeshPolyLine::nvertex(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::TriangleMeshPolyLine::vertex_coordinate().
 TriangleMeshOpenCurve()
virtual oomph::TriangleMeshOpenCurve::~TriangleMeshOpenCurve () [inline], [virtual]
Empty destructor.
Definition at line 1522 of file unstructured_two_d_mesh_geometry_base.h.
Member Function Documentation
nsegments()
unsigned oomph::TriangleMeshOpenCurve::nsegments () const [inline], [virtual]
Total number of segments.
Implements oomph::TriangleMeshCurve.
Definition at line 1537 of file unstructured_two_d_mesh_geometry_base.h.
nvertices()
unsigned oomph::TriangleMeshOpenCurve::nvertices () const [inline], [virtual]
Number of vertices.
Implements oomph::TriangleMeshCurve.
Definition at line 1525 of file unstructured_two_d_mesh_geometry_base.h.
References i.
output()
void oomph::TriangleMeshOpenCurve::output (std::ostream & outfile, const unsigned & n_sample = 50) [inline], [virtual]
Output each sub-boundary at n_sample (default: 50) points.
Implements oomph::TriangleMeshCurve.
Definition at line 1547 of file unstructured_two_d_mesh_geometry_base.h.
References i.
polyline_pt() [1/2]
TriangleMeshPolyLine* oomph::TriangleMeshOpenCurve::polyline_pt (const unsigned & i) const [inline]
Pointer to i-th constituent polyline.
Definition at line 1558 of file unstructured_two_d_mesh_geometry_base.h.
References i.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_vertices_for_non_deletion(), oomph::RefineableTriangleMesh< ELEMENT >::create_temporary_boundary_connections(), oomph::RefineableTriangleMesh< ELEMENT >::restore_boundary_connections(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area(), and oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh().
polyline_pt() [2/2]
TriangleMeshPolyLine* oomph::TriangleMeshOpenCurve::polyline_pt (const unsigned & i) [inline]
Pointer to i-th constituent polyline.
Definition at line 1581 of file unstructured_two_d_mesh_geometry_base.h.
References i.
The documentation for this class was generated from the following files:
unstructured_two_d_mesh_geometry_base.h
unstructured_two_d_mesh_geometry_base.cc