oomph::TRaviartThomasDarcyElement< ORDER > Class Template Reference
#include <Tdarcy_elements.h>
Public Member Functions
TRaviartThomasDarcyElement ()
Constructor.
~TRaviartThomasDarcyElement ()
Destructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
unsigned face_index_of_edge (const unsigned &j) const
Return the face index associated with specified edge.
void face_local_coordinate_of_flux_interpolation_point (const unsigned &edge, const unsigned &n, Vector< double > &s) const
Compute the face element coordinates of the nth flux interpolation point along specified edge.
unsigned face_index_of_q_edge_basis_fct (const unsigned &j) const
Return the face index associated with edge flux degree of freedom.
int q_edge_local_eqn (const unsigned &n) const
Return the equation nunmber of the n-th edge (flux) degree of freedom.
int q_internal_local_eqn (const unsigned &n) const
Return the equation number of the n-th internal degree of freedom.
Vector< Data * > q_edge_data_pt () const
Return vector of pointers to the Data objects that store the edge flux values.
Data * q_internal_data_pt () const
Return pointer to the Data object that stores the internal flux values.
unsigned q_internal_index () const
Return the index of the internal data where the q_internal degrees of freedom are stored.
unsigned q_edge_index (const unsigned &n) const
Return the nodal index at which the nth edge unknown is stored.
unsigned q_edge_node_number (const unsigned &n) const
Return the local node number of the node where the nth edge unknown is stored.
Node * edge_flux_node_pt (const unsigned &edge)
Get pointer to node that stores the edge flux dofs for specified edge.
double q_edge (const unsigned &n) const
Return the values of the edge (flux) degree of freedom.
double q_internal (const unsigned &n) const
Return the values of the internal degree of freedom.
void set_q_edge (const unsigned &n, const double &value)
Set the values of the edge (flux) degree of freedom.
void set_q_internal (const unsigned &n, const double &value)
Set the values of the internal degree of freedom.
unsigned nq_basis_edge () const
Return the number of edge basis functions for q.
unsigned nq_basis_internal () const
Return the number of internal basis functions for q.
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Return the local form of the q basis at local coordinate s.
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
Return the local form of the q basis and dbasis/ds at local coordinate s.
unsigned nedge_flux_interpolation_point () const
Return the number of flux interpolation points along each edge of the element.
Vector< double > edge_flux_interpolation_point (const unsigned &edge, const unsigned &n) const
void edge_flux_interpolation_point_global (const unsigned &j, Vector< double > &x) const
Compute the global coordinates of the flux interpolation point associated with the j-th edge-based q basis fct.
void edge_flux_interpolation_point_global (const unsigned &edge, const unsigned &n, Vector< double > &x) const
Compute the global coordinates of the nth flux interpolation point along an edge.
void pin_q_internal_value (const unsigned &n)
Pin the nth internal q value.
int p_local_eqn (const unsigned &n) const
Return the equation number of the n-th pressure degree of freedom.
double p_value (const unsigned &n) const
Return the nth pressure value.
unsigned np_basis () const
Return the total number of pressure basis functions.
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Compute the pressure basis.
void pin_p_value (const unsigned &n)
Pin the nth pressure value.
Data * p_data_pt () const
Return pointer to the Data object that stores the pressure values.
void set_p_value (const unsigned &n, const double &value)
Set the nth pressure value.
void scale_basis (Shape &basis) const
Scale the edge basis to allow arbitrary edge mappings.
const short & sign_edge (const unsigned &n) const
Accessor for the unit normal sign of edge n (const version)
short & sign_edge (const unsigned &n)
Accessor for the unit normal sign of edge n.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &Nplot)
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Recovery order for Z2 error estimator.
template<>
TRaviartThomasDarcyElement ()
Constructor. Order 0 elements have 1 pressure dof and no internal velocity dofs.
template<>
~TRaviartThomasDarcyElement ()
Destructor.
template<>
unsigned nq_basis_edge () const
Return the number of edge basis functions for q.
template<>
unsigned nq_basis_internal () const
Return the number of internal basis functions for q.
template<>
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Compute the local form of the q basis at local coordinate s.
template<>
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
Compute the local form of the q basis and dbasis/ds at local coordinate s.
template<>
unsigned nedge_flux_interpolation_point () const
template<>
int p_local_eqn (const unsigned &n) const
Return the equation number of the n-th pressure degree of freedom.
template<>
double p_value (const unsigned &n) const
Return the nth pressure value.
template<>
unsigned np_basis () const
Return the total number of pressure basis functions.
template<>
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Compute the pressure basis.
template<>
unsigned nrecovery_order ()
Recovery order for Z2 error estimator.
template<>
TRaviartThomasDarcyElement ()
Constructor. Order 1 elements have 3 pressure dofs and 2 internal velocity dofs.
template<>
~TRaviartThomasDarcyElement ()
Destructor.
template<>
unsigned nq_basis_edge () const
Return the number of edge basis functions for q.
template<>
unsigned nq_basis_internal () const
Return the number of internal basis functions for q.
template<>
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Compute the local form of the q basis at local coordinate s.
template<>
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
Compute the local form of the q basis and dbasis/ds at local coordinate s.
template<>
unsigned nedge_flux_interpolation_point () const
template<>
int p_local_eqn (const unsigned &n) const
Return the equation number of the n-th pressure degree of freedom.
template<>
double p_value (const unsigned &n) const
Return the nth pressure value.
template<>
unsigned np_basis () const
Return the total number of pressure basis functions.
template<>
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Compute the pressure basis.
template<>
unsigned nrecovery_order ()
Recovery order for Z2 error estimator.
Protected Member Functions
double shape_basis_test_local (const Vector< double > &s, Shape &psi, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const
Return the geometric basis, and the q, p and divergence basis functions and test functions at local coordinate s.
double shape_basis_test_local_at_knot (const unsigned &ipt, Shape &psi, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const
Return the geometric basis, and the q, p and divergence basis functions and test functions at integration point ipt.
template<>
const unsigned Initial_Nvalue [6]
template<>
const unsigned Initial_Nvalue [6]
Static Protected Attributes
static const unsigned Initial_Nvalue []
The number of values stored at each node.
Private Member Functions
template<>
const unsigned Face_index_of_edge_flux [3]
Face index associated with edge flux degree of freedom.
template<>
const unsigned Q_edge_conv [3]
Fluxes are stored at mid-side nodes.
template<>
const double Flux_interpolation_point [1]
The points along each edge where the fluxes are taken to be.
template<>
const unsigned Face_index_of_edge_flux [6]
Face index associated with edge flux degree of freedom.
template<>
const unsigned Q_edge_conv [3]
Fluxes are stored at midside nodes.
template<>
const double Flux_interpolation_point [2]
The points along each edge where the fluxes are taken to be.
Private Attributes
unsigned Q_internal_data_index
The internal data index where the internal q degrees of freedom are stored.
unsigned P_internal_data_index
The internal data index where the p degrees of freedom are stored.
std::vector< short > Sign_edge
Unit normal signs associated with each edge to ensure inter-element continuity of the flux.
Static Private Attributes
static const unsigned Face_index_of_edge_flux []
Face index associated with edge flux degree of freedom.
static const unsigned Q_edge_conv []
Conversion scheme from an edge degree of freedom to the node it's stored at.
static const double Flux_interpolation_point []
The points along each edge where the fluxes are interpolated.
Additional Inherited Members
Detailed Description
template<unsigned ORDER>
class oomph::TRaviartThomasDarcyElement< ORDER >
Element which solves the Darcy equations using TElements. Geometrically the element is always a six noded triangle. We use the mid-side nodes to store edge-based flux degrees of freedom and internal data for the discontinuous pressure and internal flux dofs.
Definition at line 53 of file Tdarcy_elements.h.
Constructor & Destructor Documentation
TRaviartThomasDarcyElement() [1/3]
template<unsigned ORDER>
oomph::TRaviartThomasDarcyElement< ORDER >::TRaviartThomasDarcyElement ()
Constructor.
 TRaviartThomasDarcyElement() [1/3]
template<unsigned ORDER>
oomph::TRaviartThomasDarcyElement< ORDER >::~TRaviartThomasDarcyElement ()
Destructor.
TRaviartThomasDarcyElement() [2/3]
template<>
oomph::TRaviartThomasDarcyElement< 0 >::TRaviartThomasDarcyElement ()
Constructor. Order 0 elements have 1 pressure dof and no internal velocity dofs.
Lowest-order Raviart-Thomas based Darcy equation element
Definition at line 48 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::add_internal_data(), and oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index.
 TRaviartThomasDarcyElement() [2/3]
template<>
oomph::TRaviartThomasDarcyElement< 0 >::~TRaviartThomasDarcyElement ()
Destructor.
Definition at line 58 of file Tdarcy_elements.cc.
TRaviartThomasDarcyElement() [3/3]
template<>
oomph::TRaviartThomasDarcyElement< 1 >::TRaviartThomasDarcyElement ()
Constructor. Order 1 elements have 3 pressure dofs and 2 internal velocity dofs.
Second-order Raviart-Thomas based Darcy equation element
Definition at line 225 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::add_internal_data(), oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index, and oomph::TRaviartThomasDarcyElement< ORDER >::Q_internal_data_index.
 TRaviartThomasDarcyElement() [3/3]
template<>
oomph::TRaviartThomasDarcyElement< 1 >::~TRaviartThomasDarcyElement ()
Destructor.
Definition at line 237 of file Tdarcy_elements.cc.
Member Function Documentation
edge_flux_interpolation_point()
template<unsigned ORDER>
Vector<double> oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point (const unsigned & edge, const unsigned & n) const [inline], [virtual]
Return the local coordinate of the nth flux interpolation point along an edge
Implements oomph::DarcyEquations< 2 >.
Definition at line 237 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::sign_edge().
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global(), oomph::TRaviartThomasDarcyElement< ORDER >::face_local_coordinate_of_flux_interpolation_point(), oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local(), and oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local().
edge_flux_interpolation_point_global() [1/2]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global (const unsigned & j, Vector< double > & x) const [inline], [virtual]
Compute the global coordinates of the flux interpolation point associated with the j-th edge-based q basis fct.
Implements oomph::DarcyEquations< 2 >.
Definition at line 249 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::nedge_flux_interpolation_point().
edge_flux_interpolation_point_global() [2/2]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global (const unsigned & edge, const unsigned & n, Vector< double > & x) const [inline], [virtual]
Compute the global coordinates of the nth flux interpolation point along an edge.
Implements oomph::DarcyEquations< 2 >.
Definition at line 260 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point(), and oomph::FiniteElement::interpolated_x().
edge_flux_node_pt()
template<unsigned ORDER>
Node* oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_node_pt (const unsigned & edge) [inline]
Get pointer to node that stores the edge flux dofs for specified edge.
Definition at line 188 of file Tdarcy_elements.h.
References oomph::FiniteElement::node_pt().
face_index_of_edge()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::face_index_of_edge (const unsigned & j) const [inline], [virtual]
Return the face index associated with specified edge.
Implements oomph::DarcyEquations< 2 >.
Definition at line 93 of file Tdarcy_elements.h.
Face_index_of_edge_flux() [1/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 0 >::Face_index_of_edge_flux () [private]
Face index associated with edge flux degree of freedom.
Definition at line 190 of file Tdarcy_elements.cc.
Face_index_of_edge_flux() [2/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 1 >::Face_index_of_edge_flux () [private]
Face index associated with edge flux degree of freedom.
Definition at line 423 of file Tdarcy_elements.cc.
face_index_of_q_edge_basis_fct()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::face_index_of_q_edge_basis_fct (const unsigned & j) const [inline], [virtual]
Return the face index associated with edge flux degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 132 of file Tdarcy_elements.h.
face_local_coordinate_of_flux_interpolation_point()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::face_local_coordinate_of_flux_interpolation_point (const unsigned & edge, const unsigned & n, Vector< double > & s) const [inline], [virtual]
Compute the face element coordinates of the nth flux interpolation point along specified edge.
Implements oomph::DarcyEquations< 2 >.
Definition at line 100 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point().
Flux_interpolation_point() [1/2]
template<>
const double oomph::TRaviartThomasDarcyElement< 0 >::Flux_interpolation_point () [private]
The points along each edge where the fluxes are taken to be.
Definition at line 207 of file Tdarcy_elements.cc.
Flux_interpolation_point() [2/2]
template<>
const double oomph::TRaviartThomasDarcyElement< 1 >::Flux_interpolation_point () [private]
The points along each edge where the fluxes are taken to be.
Definition at line 438 of file Tdarcy_elements.cc.
get_div_q_basis_local() [1/3]
template<>
void oomph::TRaviartThomasDarcyElement< 0 >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const [virtual]
Compute the local form of the q basis and dbasis/ds at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Definition at line 105 of file Tdarcy_elements.cc.
References oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), and oomph::TRaviartThomasDarcyElement< ORDER >::Sign_edge.
get_div_q_basis_local() [2/3]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const [virtual]
Return the local form of the q basis and dbasis/ds at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal(), and oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local().
get_div_q_basis_local() [3/3]
template<>
void oomph::TRaviartThomasDarcyElement< 1 >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const [virtual]
Compute the local form of the q basis and dbasis/ds at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Definition at line 314 of file Tdarcy_elements.cc.
References oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), and oomph::TRaviartThomasDarcyElement< ORDER >::Sign_edge.
get_p_basis() [1/3]
template<>
void oomph::TRaviartThomasDarcyElement< 0 >::get_p_basis (const Vector< double > & s, Shape & p_basis) const [virtual]
Compute the pressure basis.
Implements oomph::DarcyEquations< 2 >.
Definition at line 160 of file Tdarcy_elements.cc.
get_p_basis() [2/3]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::get_p_basis (const Vector< double > & s, Shape & p_basis) const [virtual]
Compute the pressure basis.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value(), and oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local().
get_p_basis() [3/3]
template<>
void oomph::TRaviartThomasDarcyElement< 1 >::get_p_basis (const Vector< double > & s, Shape & p_basis) const [virtual]
Compute the pressure basis.
Implements oomph::DarcyEquations< 2 >.
Definition at line 392 of file Tdarcy_elements.cc.
get_q_basis_local() [1/3]
template<>
void oomph::TRaviartThomasDarcyElement< 0 >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const [virtual]
Compute the local form of the q basis at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Definition at line 87 of file Tdarcy_elements.cc.
References oomph::TRaviartThomasDarcyElement< ORDER >::Sign_edge.
get_q_basis_local() [2/3]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const [virtual]
Return the local form of the q basis at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal(), and oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local().
get_q_basis_local() [3/3]
template<>
void oomph::TRaviartThomasDarcyElement< 1 >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const [virtual]
Compute the local form of the q basis at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Definition at line 265 of file Tdarcy_elements.cc.
References oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point(), and oomph::TRaviartThomasDarcyElement< ORDER >::Sign_edge.
Initial_Nvalue() [1/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 0 >::Initial_Nvalue () [protected]
The number of values stored at each node: A single flux dof is stored at each midside node
Definition at line 182 of file Tdarcy_elements.cc.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::required_nvalue().
Initial_Nvalue() [2/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 1 >::Initial_Nvalue () [protected]
The number of values stored at each node. Two flux values are stored at each midside node.
Definition at line 415 of file Tdarcy_elements.cc.
nedge_flux_interpolation_point() [1/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 0 >::nedge_flux_interpolation_point () const [virtual]
Return the number of flux interpolation points along each edge of the element
Implements oomph::DarcyEquations< 2 >.
Definition at line 124 of file Tdarcy_elements.cc.
nedge_flux_interpolation_point() [2/3]
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::nedge_flux_interpolation_point () const [virtual]
Return the number of flux interpolation points along each edge of the element.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global(), and oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal().
nedge_flux_interpolation_point() [3/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 1 >::nedge_flux_interpolation_point () const [virtual]
Return the number of flux_interpolation points along each edge of the element
Implements oomph::DarcyEquations< 2 >.
Definition at line 356 of file Tdarcy_elements.cc.
np_basis() [1/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 0 >::np_basis () const [virtual]
Return the total number of pressure basis functions.
Implements oomph::DarcyEquations< 2 >.
Definition at line 151 of file Tdarcy_elements.cc.
np_basis() [2/3]
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::np_basis () const [virtual]
Return the total number of pressure basis functions.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value().
np_basis() [3/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 1 >::np_basis () const [virtual]
Return the total number of pressure basis functions.
Implements oomph::DarcyEquations< 2 >.
Definition at line 383 of file Tdarcy_elements.cc.
nq_basis_edge() [1/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 0 >::nq_basis_edge () const [virtual]
Return the number of edge basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Definition at line 67 of file Tdarcy_elements.cc.
nq_basis_edge() [2/3]
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::nq_basis_edge () const [virtual]
Return the number of edge basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), and oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal().
nq_basis_edge() [3/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 1 >::nq_basis_edge () const [virtual]
Return the number of edge basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Definition at line 246 of file Tdarcy_elements.cc.
nq_basis_internal() [1/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 0 >::nq_basis_internal () const [virtual]
Return the number of internal basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Definition at line 78 of file Tdarcy_elements.cc.
nq_basis_internal() [2/3]
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::nq_basis_internal () const [virtual]
Return the number of internal basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal().
nq_basis_internal() [3/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 1 >::nq_basis_internal () const [virtual]
Return the number of internal basis functions for q.
Implements oomph::DarcyEquations< 2 >.
Definition at line 256 of file Tdarcy_elements.cc.
nrecovery_order() [1/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 0 >::nrecovery_order () [virtual]
Recovery order for Z2 error estimator.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 172 of file Tdarcy_elements.cc.
nrecovery_order() [2/3]
template<>
unsigned oomph::TRaviartThomasDarcyElement< 1 >::nrecovery_order () [virtual]
Recovery order for Z2 error estimator.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 405 of file Tdarcy_elements.cc.
nrecovery_order() [3/3]
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::nrecovery_order () [virtual]
Recovery order for Z2 error estimator.
Implements oomph::ElementWithZ2ErrorEstimator.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::vertex_node_pt().
nvertex_node()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 403 of file Tdarcy_elements.h.
output() [1/2]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 390 of file Tdarcy_elements.h.
References oomph::DarcyEquations< DIM >::output().
output() [2/2]
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::output (std::ostream & outfile, const unsigned & Nplot) [inline], [virtual]
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 397 of file Tdarcy_elements.h.
References oomph::DarcyEquations< DIM >::output().
p_data_pt()
template<unsigned ORDER>
Data* oomph::TRaviartThomasDarcyElement< ORDER >::p_data_pt () const [inline], [virtual]
Return pointer to the Data object that stores the pressure values.
Implements oomph::DarcyEquations< 2 >.
Definition at line 324 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_data_pt().
p_local_eqn() [1/3]
template<>
int oomph::TRaviartThomasDarcyElement< 0 >::p_local_eqn (const unsigned & n) const [virtual]
Return the equation number of the n-th pressure degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 133 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::internal_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index.
p_local_eqn() [2/3]
template<unsigned ORDER>
int oomph::TRaviartThomasDarcyElement< ORDER >::p_local_eqn (const unsigned & n) const [virtual]
Return the equation number of the n-th pressure degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value().
p_local_eqn() [3/3]
template<>
int oomph::TRaviartThomasDarcyElement< 1 >::p_local_eqn (const unsigned & n) const [virtual]
Return the equation number of the n-th pressure degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 365 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::internal_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index.
p_value() [1/3]
template<>
double oomph::TRaviartThomasDarcyElement< 0 >::p_value (const unsigned & n) const [virtual]
Return the nth pressure value.
Implements oomph::DarcyEquations< 2 >.
Definition at line 142 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::internal_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index, and oomph::Data::value().
p_value() [2/3]
template<unsigned ORDER>
double oomph::TRaviartThomasDarcyElement< ORDER >::p_value (const unsigned & n) const [virtual]
Return the nth pressure value.
Implements oomph::DarcyEquations< 2 >.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value().
p_value() [3/3]
template<>
double oomph::TRaviartThomasDarcyElement< 1 >::p_value (const unsigned & n) const [virtual]
Return the nth pressure value.
Implements oomph::DarcyEquations< 2 >.
Definition at line 374 of file Tdarcy_elements.cc.
References oomph::GeneralisedElement::internal_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index, and oomph::Data::value().
pin_p_value()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::pin_p_value (const unsigned & n) [inline], [virtual]
Pin the nth pressure value.
Implements oomph::DarcyEquations< 2 >.
Definition at line 318 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::pin().
pin_q_internal_value()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value (const unsigned & n) [inline], [virtual]
Pin the nth internal q value.
Implements oomph::DarcyEquations< 2 >.
Definition at line 299 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::get_p_basis(), oomph::GeneralisedElement::internal_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::np_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::p_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::p_value(), oomph::Data::pin(), and oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index().
q_edge()
template<unsigned ORDER>
double oomph::TRaviartThomasDarcyElement< ORDER >::q_edge (const unsigned & n) const [inline], [virtual]
Return the values of the edge (flux) degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 194 of file Tdarcy_elements.h.
References oomph::FiniteElement::nodal_value(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_index(), and oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_node_number().
Q_edge_conv() [1/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 0 >::Q_edge_conv () [private]
Fluxes are stored at mid-side nodes.
Conversion scheme from an edge degree of freedom to the node it's stored at
Definition at line 199 of file Tdarcy_elements.cc.
Q_edge_conv() [2/2]
template<>
const unsigned oomph::TRaviartThomasDarcyElement< 1 >::Q_edge_conv () [private]
Fluxes are stored at midside nodes.
Conversion scheme from an edge degree of freedom to the node it's stored at
Definition at line 431 of file Tdarcy_elements.cc.
q_edge_data_pt()
template<unsigned ORDER>
Vector<Data*> oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_data_pt () const [inline], [virtual]
Return vector of pointers to the Data objects that store the edge flux values.
Implements oomph::DarcyEquations< 2 >.
Definition at line 151 of file Tdarcy_elements.h.
References oomph::FiniteElement::node_pt().
q_edge_index()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_index (const unsigned & n) const [inline], [virtual]
Return the nodal index at which the nth edge unknown is stored.
Implements oomph::DarcyEquations< 2 >.
Definition at line 175 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge().
q_edge_local_eqn()
template<unsigned ORDER>
int oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_local_eqn (const unsigned & n) const [inline], [virtual]
Return the equation nunmber of the n-th edge (flux) degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 138 of file Tdarcy_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_index(), and oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_node_number().
q_edge_node_number()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_node_number (const unsigned & n) const [inline], [virtual]
Return the local node number of the node where the nth edge unknown is stored.
Implements oomph::DarcyEquations< 2 >.
Definition at line 182 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge().
q_internal()
template<unsigned ORDER>
double oomph::TRaviartThomasDarcyElement< ORDER >::q_internal (const unsigned & n) const [inline], [virtual]
Return the values of the internal degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 200 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index(), and oomph::Data::value().
q_internal_data_pt()
template<unsigned ORDER>
Data* oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_data_pt () const [inline], [virtual]
Return pointer to the Data object that stores the internal flux values.
Implements oomph::DarcyEquations< 2 >.
Definition at line 162 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_data_pt().
q_internal_index()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index () const [inline], [virtual]
Return the index of the internal data where the q_internal degrees of freedom are stored.
Implements oomph::DarcyEquations< 2 >.
Definition at line 169 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::Q_internal_data_index.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::pin_q_internal_value(), oomph::TRaviartThomasDarcyElement< ORDER >::q_internal(), oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal().
q_internal_local_eqn()
template<unsigned ORDER>
int oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_local_eqn (const unsigned & n) const [inline], [virtual]
Return the equation number of the n-th internal degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 144 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_local_eqn(), and oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index().
required_nvalue()
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Implements oomph::DarcyEquations< 2 >.
Definition at line 87 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::Initial_Nvalue().
scale_basis()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis (Shape & basis) const [inline], [virtual]
Scale the edge basis to allow arbitrary edge mappings.
Implements oomph::DarcyEquations< 2 >.
Definition at line 337 of file Tdarcy_elements.h.
References i, oomph::Shape::nindex2(), oomph::FiniteElement::node_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::nq_basis_edge(), and oomph::Node::x().
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local().
set_p_value()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::set_p_value (const unsigned & n, const double & value) [inline], [virtual]
Set the nth pressure value.
Implements oomph::DarcyEquations< 2 >.
Definition at line 330 of file Tdarcy_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::set_value().
set_q_edge()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge (const unsigned & n, const double & value) [inline], [virtual]
Set the values of the edge (flux) degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 206 of file Tdarcy_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_index(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_node_number(), and oomph::Data::set_value().
set_q_internal()
template<unsigned ORDER>
void oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal (const unsigned & n, const double & value) [inline], [virtual]
Set the values of the internal degree of freedom.
Implements oomph::DarcyEquations< 2 >.
Definition at line 212 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local(), oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local(), oomph::GeneralisedElement::internal_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::nedge_flux_interpolation_point(), oomph::TRaviartThomasDarcyElement< ORDER >::nq_basis_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::nq_basis_internal(), oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index(), s, and oomph::Data::set_value().
shape_basis_test_local()
template<unsigned ORDER>
double oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local (const Vector< double > & s, Shape & psi, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const [inline], [protected], [virtual]
Return the geometric basis, and the q, p and divergence basis functions and test functions at local coordinate s.
Implements oomph::DarcyEquations< 2 >.
Definition at line 418 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local(), oomph::TRaviartThomasDarcyElement< ORDER >::get_p_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local(), oomph::DarcyEquations< 2 >::nq_basis(), and oomph::DarcyEquations< 2 >::transform_basis().
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local_at_knot().
shape_basis_test_local_at_knot()
template<unsigned ORDER>
double oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local_at_knot (const unsigned & ipt, Shape & psi, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const [inline], [protected], [virtual]
Return the geometric basis, and the q, p and divergence basis functions and test functions at integration point ipt.
Implements oomph::DarcyEquations< 2 >.
Definition at line 445 of file Tdarcy_elements.h.
References i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local().
sign_edge() [1/2]
template<unsigned ORDER>
const short& oomph::TRaviartThomasDarcyElement< ORDER >::sign_edge (const unsigned & n) const [inline]
Accessor for the unit normal sign of edge n (const version)
Definition at line 378 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point().
sign_edge() [2/2]
template<unsigned ORDER>
short& oomph::TRaviartThomasDarcyElement< ORDER >::sign_edge (const unsigned & n) [inline]
Accessor for the unit normal sign of edge n.
Definition at line 384 of file Tdarcy_elements.h.
vertex_node_pt()
template<unsigned ORDER>
Node* oomph::TRaviartThomasDarcyElement< ORDER >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 407 of file Tdarcy_elements.h.
References oomph::TRaviartThomasDarcyElement< ORDER >::nrecovery_order().
Member Data Documentation
Face_index_of_edge_flux
template<unsigned ORDER>
const unsigned oomph::TRaviartThomasDarcyElement< ORDER >::Face_index_of_edge_flux[] [static], [private]
Face index associated with edge flux degree of freedom.
Definition at line 59 of file Tdarcy_elements.h.
Flux_interpolation_point
template<unsigned ORDER>
const double oomph::TRaviartThomasDarcyElement< ORDER >::Flux_interpolation_point[] [static], [private]
The points along each edge where the fluxes are interpolated.
Definition at line 66 of file Tdarcy_elements.h.
Initial_Nvalue
template<unsigned ORDER>
const unsigned oomph::TRaviartThomasDarcyElement< ORDER >::Initial_Nvalue[] [static], [protected]
The number of values stored at each node.
Definition at line 462 of file Tdarcy_elements.h.
P_internal_data_index
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::P_internal_data_index [private]
The internal data index where the p degrees of freedom are stored.
Definition at line 72 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::p_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::p_value(), and oomph::TRaviartThomasDarcyElement< ORDER >::TRaviartThomasDarcyElement().
Q_edge_conv
template<unsigned ORDER>
const unsigned oomph::TRaviartThomasDarcyElement< ORDER >::Q_edge_conv[] [static], [private]
Conversion scheme from an edge degree of freedom to the node it's stored at.
Definition at line 63 of file Tdarcy_elements.h.
Q_internal_data_index
template<unsigned ORDER>
unsigned oomph::TRaviartThomasDarcyElement< ORDER >::Q_internal_data_index [private]
The internal data index where the internal q degrees of freedom are stored.
Definition at line 69 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_index(), and oomph::TRaviartThomasDarcyElement< ORDER >::TRaviartThomasDarcyElement().
Sign_edge
template<unsigned ORDER>
std::vector<short> oomph::TRaviartThomasDarcyElement< ORDER >::Sign_edge [private]
Unit normal signs associated with each edge to ensure inter-element continuity of the flux.
Definition at line 76 of file Tdarcy_elements.h.
Referenced by oomph::TRaviartThomasDarcyElement< ORDER >::get_div_q_basis_local(), and oomph::TRaviartThomasDarcyElement< ORDER >::get_q_basis_local().
The documentation for this class was generated from the following file:
Tdarcy_elements.h