oomph::ReflectedIntegral Class Reference
#include <integral.h>
Public Member Functions
ReflectedIntegral (const Integral *integral_to_reflect_pt, const unsigned index_s, const double s_reflect, const double s_min, const double s_max)
Construct reflected integral, note s refers to local coordinate.
unsigned nweight () const
Number of integration points of the scheme, two times the base scheme.
double knot (const unsigned &i, const unsigned &j) const
Return local coordinate s[j] of i-th integration point.
double weight (const unsigned &i) const
Return weight of i-th integration point.
Private Member Functions
double local_to_fraction (const double &local_coord) const
Helper function to convert from local coordinate (s in [-1,1] for quads) to fraction [0,1].
double fraction_to_local (const double &fraction) const
Helper function to convert from fraction [0,1] to local coordinate (s in [-1,1] for quads)
Private Attributes
const Integral * Integral_pt
Pointer to integral which we will reflect.
const unsigned Index_s
Index of local coord (s) which scheme will be reflected along.
const double S_reflect
Value of local coord (s) where scheme will be reflected.
const double S_min
Minimum value of local coord (s) over whole domain.
const double S_max
Maximum value of local coord (s) over whole domain.
const double S_reflect_fraction
Position where scheme will be reflected as of fraction of domain [0,1].
Detailed Description
Wrapper for an integral that reflects one integral at point inside the domain, such that the integral is used on both sides of the line of reflection | . . .| . . . |
Definition at line 107 of file integral.h.
Constructor & Destructor Documentation
ReflectedIntegral()
oomph::ReflectedIntegral::ReflectedIntegral (const Integral * integral_to_reflect_pt, const unsigned index_s, const double s_reflect, const double s_min, const double s_max) [inline]
Construct reflected integral, note s refers to local coordinate.
Definition at line 112 of file integral.h.
Member Function Documentation
fraction_to_local()
double oomph::ReflectedIntegral::fraction_to_local (const double & fraction) const [private]
Helper function to convert from fraction [0,1] to local coordinate (s in [-1,1] for quads)
Definition at line 74 of file integral.cc.
References S_max, and S_min.
Referenced by knot().
knot()
double oomph::ReflectedIntegral::knot (const unsigned & i, const unsigned & j) const [virtual]
Return local coordinate s[j] of i-th integration point.
Implements oomph::Integral.
Definition at line 38 of file integral.cc.
References fraction_to_local(), Index_s, Integral_pt, oomph::Integral::knot(), local_to_fraction(), oomph::Integral::nweight(), and S_reflect_fraction.
local_to_fraction()
double oomph::ReflectedIntegral::local_to_fraction (const double & local_coord) const [private]
Helper function to convert from local coordinate (s in [-1,1] for quads) to fraction [0,1].
Definition at line 69 of file integral.cc.
References S_max, and S_min.
Referenced by knot().
nweight()
unsigned oomph::ReflectedIntegral::nweight () const [inline], [virtual]
Number of integration points of the scheme, two times the base scheme.
Implements oomph::Integral.
Definition at line 123 of file integral.h.
References i, oomph::Integral::knot(), and oomph::Integral::weight().
Referenced by weight().
weight()
double oomph::ReflectedIntegral::weight (const unsigned & i) const [virtual]
Return weight of i-th integration point.
Implements oomph::Integral.
Definition at line 79 of file integral.cc.
References Integral_pt, oomph::Integral::nweight(), nweight(), S_reflect_fraction, and oomph::Integral::weight().
Member Data Documentation
Index_s
const unsigned oomph::ReflectedIntegral::Index_s [private]
Index of local coord (s) which scheme will be reflected along.
Definition at line 145 of file integral.h.
Referenced by knot().
Integral_pt
const Integral* oomph::ReflectedIntegral::Integral_pt [private]
Pointer to integral which we will reflect.
Definition at line 142 of file integral.h.
Referenced by knot(), and weight().
S_max
const double oomph::ReflectedIntegral::S_max [private]
Maximum value of local coord (s) over whole domain.
Definition at line 154 of file integral.h.
Referenced by fraction_to_local(), and local_to_fraction().
S_min
const double oomph::ReflectedIntegral::S_min [private]
Minimum value of local coord (s) over whole domain.
Definition at line 151 of file integral.h.
Referenced by fraction_to_local(), and local_to_fraction().
S_reflect
const double oomph::ReflectedIntegral::S_reflect [private]
Value of local coord (s) where scheme will be reflected.
Definition at line 148 of file integral.h.
S_reflect_fraction
const double oomph::ReflectedIntegral::S_reflect_fraction [private]
Position where scheme will be reflected as of fraction of domain [0,1].
Definition at line 157 of file integral.h.
Referenced by knot(), and weight().
The documentation for this class was generated from the following files:
integral.h
integral.cc