oomph::StorableShapeElementBase Class Reference
#include <stored_shape_function_elements.h>
Public Member Functions
StorableShapeElementBase ()
Constructor, set most storage pointers to NULL.
virtual ~StorableShapeElementBase ()
The destructor cleans up the static memory allocated for shape function storage. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
StorableShapeElementBase (const StorableShapeElementBase &)
Broken copy constructor.
void operator= (const StorableShapeElementBase &)
Broken assignment operator.
void delete_all_shape_local_stored ()
Delete all the objects stored in the [...]_local_stored_pt vectors and delete the vectors themselves.
void delete_shape_local_stored ()
Delete stored shape functions.
void delete_dshape_local_stored ()
Delete stored derivatives of shape functions w.r.t. to local coordinates.
void delete_d2shape_local_stored ()
Delete stored 2nd derivatives of shape functions w.r.t. to local coordinates.
void delete_all_dshape_eulerian_stored ()
Delete all storage related to deriatives of shape fcts w.r.t. to global Eulerian coords.
void delete_dshape_eulerian_stored ()
Delete stored deriatives of shape fcts w.r.t. to global Eulerian coords.
void delete_d2shape_eulerian_stored ()
Delete stored second derivatives of shape functions w.r.t. to global Eulerian coordinates.
void delete_J_eulerian_stored ()
Delete stored Jacobian of mapping between local and global (Eulerian) coordinates.
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme -- overloaded from the finite element base class since a change in the integration scheme forces a recomputation of the shape fcts at the integration points.
Vector< Shape * > *& shape_stored_pt ()
Return a pointer to the vector of pointers to the stored shape functions.
Vector< Shape * > *const & shape_stored_pt () const
Return a pointer to the vector of pointers to the stored shape functions (const version)
Shape *& shape_stored_pt (const unsigned &ipt)
Return a pointer to the stored shape function at the ipt-th integration point.
Shape *const & shape_stored_pt (const unsigned &ipt) const
Return a pointer to the stored shape function at the ipt-th integration point (const version)
Vector< DShape * > *& dshape_local_stored_pt ()
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the local coordinates.
Vector< DShape * > *const & dshape_local_stored_pt () const
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the local coordinates (const version)
Vector< DShape * > *& d2shape_local_stored_pt ()
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the local coordinates.
Vector< DShape * > *const & d2shape_local_stored_pt () const
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the local coordinates (const version)
Vector< DShape * > *& dshape_eulerian_stored_pt ()
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the global (eulerian) coordinates.
Vector< DShape * > *const & dshape_eulerian_stored_pt () const
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the global (eulerian) coordinates (const version)
Vector< DShape * > *& d2shape_eulerian_stored_pt ()
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the global (eulerian) coordinates.
Vector< DShape * > *const & d2shape_eulerian_stored_pt () const
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the global (eulerian) coordinates (const version)
Vector< double > *& jacobian_eulerian_stored_pt ()
Return a pointer to the vector of Jacobians of the mapping between the local and global (eulerian) coordinates.
Vector< double > *const & jacobian_eulerian_stored_pt () const
Return a pointer to the vector of Jacobians of the mapping between the local and global (eulerian) coordinates (const version)
void set_shape_local_stored_from_element (StorableShapeElementBase *const &element_pt)
Set the shape functions pointed to internally to be those pointed to by the FiniteElement element_pt (In most cases all elements of the same type have the same number of integration points so the shape function values and their local derivatives are the same --> They only need to be stored by one element). Calling this function deletes the locally created storage and re-directs the pointers to the stored shape function of the specified element.
void set_dshape_eulerian_stored_from_element (StorableShapeElementBase *const &element_pt)
Set the derivatives of stored shape functions with respect to the global coordinates to be the same as those pointed to by the FiniteElement element_pt. Note that this function also calls set_shape_local_stored_from_element(element_pt). so that the local derivatives are also stored. Calling this function only makes sense for uniformly-spaced meshes with elements of equal sizes.
void pre_compute_shape_at_knots ()
Calculate the shape functions at the integration points and store the results internally.
void shape_at_knot (const unsigned &ipt, Shape &psi) const
Return the geometric shape function at the ipt-th integration point.
void pre_compute_dshape_local_at_knots ()
Calculate the shape functions and first derivatives w.r.t. local coordinatess at the integration points and store the results internally.
void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the geometric shape function and its derivative w.r.t. the local coordinates at the ipt-th integration point. If pre-computed values have been stored, they will be used.
void pre_compute_d2shape_local_at_knots ()
Calculate the second derivatives of the shape functions w.r.t. local coordinates at the integration points and store the results internally.
void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
Return the geometric shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point. If pre-computed values have been stored, they will be used.
void pre_compute_J_eulerian_at_knots ()
Calculate the Jacobian of the mapping from local to global coordinates at the integration points and store the results internally.
double J_eulerian_at_knot (const unsigned &ipt) const
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point.
void pre_compute_dshape_eulerian_at_knots ()
Calculate the first derivatives of the shape functions w.r.t the global coordinates at the integration points and store the results internally.
double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
Return the geometric shape functions and also first derivatives w.r.t. global coordinates at the ipt-th integration point. If the values of the shape functions and derivatives have been pre-computed, these will be used.
void pre_compute_d2shape_eulerian_at_knots ()
Calculate the first and second derivatives of the shape functions w.r.t global coordinates at the integration points and store the results internally.
double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
Return the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point. If the values of the shape functions and derivatives have been pre-computred, these will be used.
Private Attributes
Vector< Shape * > * Shape_stored_pt
Pointer to storage for the pointers to the nodal shape functions at the integration points (knots)
Vector< DShape * > * DShape_local_stored_pt
Pointer to storage for the pointers to the derivatives of the nodal shape functions w.r.t. the local coordinates at integration points.
Vector< DShape * > * D2Shape_local_stored_pt
Pointer to storage for the pointers to the second derivatives of the nodal shape functions w.r.t. the local coordinates at integration points.
bool Can_delete_shape_local_stored
Boolean to determine whether the element can delete the stored local shape functions.
Vector< DShape * > * DShape_eulerian_stored_pt
Pointer to storage for the derivatives of the shape functions w.r.t. global coordinates at integration points.
Vector< DShape * > * D2Shape_eulerian_stored_pt
Pointer to storage for the second derivatives of the shape functions w.r.t. global coordinates at integration points.
Vector< double > * Jacobian_eulerian_stored_pt
Pointer to storage for the Jacobian of the element w.r.t global coordinates.
bool Can_delete_dshape_eulerian_stored
Boolean to determine whether the element can delete the stored derivatives of shape functions w.r.t. global coordinates.
Additional Inherited Members
Detailed Description
Base class for elements that allow storage of precomputed shape functions and their derivatives w.r.t to the local and global (Eulerian) coordinates at the element's integration points.
Definition at line 59 of file stored_shape_function_elements.h.
Constructor & Destructor Documentation
StorableShapeElementBase() [1/2]
oomph::StorableShapeElementBase::StorableShapeElementBase () [inline]
Constructor, set most storage pointers to NULL.
Definition at line 107 of file stored_shape_function_elements.h.
References ~StorableShapeElementBase().
 StorableShapeElementBase()
oomph::StorableShapeElementBase::~StorableShapeElementBase () [virtual]
The destructor cleans up the static memory allocated for shape function storage. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
The destructor cleans up the memory allocated for shape function storage.
Definition at line 214 of file stored_shape_function_elements.cc.
References delete_all_dshape_eulerian_stored(), delete_all_shape_local_stored(), and set_integration_scheme().
Referenced by StorableShapeElementBase().
StorableShapeElementBase() [2/2]
oomph::StorableShapeElementBase::StorableShapeElementBase (const StorableShapeElementBase &) [inline]
Broken copy constructor.
Definition at line 121 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
d2shape_eulerian_at_knot()
double oomph::StorableShapeElementBase::d2shape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsidx, DShape & d2psidx) const [virtual]
Return the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point. If the values of the shape functions and derivatives have been pre-computred, these will be used.
Return the geometric shape functions, first and second derivatives w.r.t eulerian coordinates at the ipt-th integration point. If the values have already been computed, return the stored values.
Reimplemented from oomph::FiniteElement.
Definition at line 753 of file stored_shape_function_elements.cc.
References oomph::FiniteElement::d2shape_eulerian_at_knot(), D2Shape_eulerian_stored_pt, and Jacobian_eulerian_stored_pt.
Referenced by dshape_eulerian_at_knot(), and jacobian_eulerian_stored_pt().
d2shape_eulerian_stored_pt() [1/2]
Vector<DShape*>* & oomph::StorableShapeElementBase::d2shape_eulerian_stored_pt () [inline]
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the global (eulerian) coordinates.
Definition at line 224 of file stored_shape_function_elements.h.
References D2Shape_eulerian_stored_pt.
Referenced by set_dshape_eulerian_stored_from_element().
d2shape_eulerian_stored_pt() [2/2]
Vector<DShape*>* const& oomph::StorableShapeElementBase::d2shape_eulerian_stored_pt () const [inline]
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the global (eulerian) coordinates (const version)
Definition at line 230 of file stored_shape_function_elements.h.
References D2Shape_eulerian_stored_pt.
d2shape_local_at_knot()
void oomph::StorableShapeElementBase::d2shape_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [virtual]
Return the geometric shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point. If pre-computed values have been stored, they will be used.
Return the shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point.
Reimplemented from oomph::FiniteElement.
Definition at line 702 of file stored_shape_function_elements.cc.
References oomph::FiniteElement::d2shape_local_at_knot(), D2Shape_local_stored_pt, and dshape_eulerian_at_knot().
Referenced by dshape_local_at_knot(), and jacobian_eulerian_stored_pt().
d2shape_local_stored_pt() [1/2]
Vector<DShape*>* & oomph::StorableShapeElementBase::d2shape_local_stored_pt () [inline]
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the local coordinates.
Definition at line 200 of file stored_shape_function_elements.h.
References D2Shape_local_stored_pt.
Referenced by set_shape_local_stored_from_element().
d2shape_local_stored_pt() [2/2]
Vector<DShape*>* const& oomph::StorableShapeElementBase::d2shape_local_stored_pt () const [inline]
Return a pointer to the vector of pointers to the stored second derivatives of the shape functions w.r.t the local coordinates (const version)
Definition at line 206 of file stored_shape_function_elements.h.
References D2Shape_local_stored_pt.
delete_all_dshape_eulerian_stored()
void oomph::StorableShapeElementBase::delete_all_dshape_eulerian_stored ()
Delete all storage related to deriatives of shape fcts w.r.t. to global Eulerian coords.
Delete all stored quantities related to derivatives of shape fcts w.r.t. to global Eulerian coordinates
Definition at line 136 of file stored_shape_function_elements.cc.
References delete_d2shape_eulerian_stored(), delete_dshape_eulerian_stored(), and delete_J_eulerian_stored().
Referenced by operator=(), set_dshape_eulerian_stored_from_element(), and ~StorableShapeElementBase().
delete_all_shape_local_stored()
void oomph::StorableShapeElementBase::delete_all_shape_local_stored ()
Delete all the objects stored in the [...]_local_stored_pt vectors and delete the vectors themselves.
Delete all the objects stored in the vectors: Shape_stored, DShape_local_stored, and D2Shape_local_stored
Definition at line 53 of file stored_shape_function_elements.cc.
References delete_d2shape_local_stored(), delete_dshape_local_stored(), and delete_shape_local_stored().
Referenced by operator=(), set_shape_local_stored_from_element(), and ~StorableShapeElementBase().
delete_d2shape_eulerian_stored()
void oomph::StorableShapeElementBase::delete_d2shape_eulerian_stored ()
Delete stored second derivatives of shape functions w.r.t. to global Eulerian coordinates.
Delete stored 2nd derivatives w.r.t. Eulerian coordinates.
Definition at line 172 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, and D2Shape_eulerian_stored_pt.
Referenced by delete_all_dshape_eulerian_stored(), operator=(), and pre_compute_d2shape_eulerian_at_knots().
delete_d2shape_local_stored()
void oomph::StorableShapeElementBase::delete_d2shape_local_stored ()
Delete stored 2nd derivatives of shape functions w.r.t. to local coordinates.
Delete stored second derivatives of shape functions w.r.t. to local coordinates
Definition at line 113 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, and D2Shape_local_stored_pt.
Referenced by delete_all_shape_local_stored(), operator=(), and pre_compute_d2shape_local_at_knots().
delete_dshape_eulerian_stored()
void oomph::StorableShapeElementBase::delete_dshape_eulerian_stored ()
Delete stored deriatives of shape fcts w.r.t. to global Eulerian coords.
Delete stored derivatives w.r.t. Eulerian coordinates.
Definition at line 146 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, and DShape_eulerian_stored_pt.
Referenced by delete_all_dshape_eulerian_stored(), operator=(), pre_compute_d2shape_eulerian_at_knots(), and pre_compute_dshape_eulerian_at_knots().
delete_dshape_local_stored()
void oomph::StorableShapeElementBase::delete_dshape_local_stored ()
Delete stored derivatives of shape functions w.r.t. to local coordinates.
Delete stored derivatives of shape functions w.r.t. to local coordinates
Definition at line 90 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, and DShape_local_stored_pt.
Referenced by delete_all_shape_local_stored(), operator=(), pre_compute_d2shape_local_at_knots(), and pre_compute_dshape_local_at_knots().
delete_J_eulerian_stored()
void oomph::StorableShapeElementBase::delete_J_eulerian_stored ()
Delete stored Jacobian of mapping between local and global (Eulerian) coordinates.
Delete stored Jacobian of mapping between local and global Eulerian coordinates
Definition at line 197 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, and Jacobian_eulerian_stored_pt.
Referenced by delete_all_dshape_eulerian_stored(), operator=(), pre_compute_d2shape_eulerian_at_knots(), pre_compute_dshape_eulerian_at_knots(), and pre_compute_J_eulerian_at_knots().
delete_shape_local_stored()
void oomph::StorableShapeElementBase::delete_shape_local_stored ()
Delete stored shape functions.
Definition at line 64 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, and Shape_stored_pt.
Referenced by delete_all_shape_local_stored(), operator=(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_local_at_knots(), and pre_compute_shape_at_knots().
dshape_eulerian_at_knot()
double oomph::StorableShapeElementBase::dshape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsidx) const [virtual]
Return the geometric shape functions and also first derivatives w.r.t. global coordinates at the ipt-th integration point. If the values of the shape functions and derivatives have been pre-computed, these will be used.
Compute the geometric shape functions, and derivatives w.r.t eulerian coordinates at the ipt-th integration point. If the values have already been computed, return the stored values.
Reimplemented from oomph::FiniteElement.
Definition at line 728 of file stored_shape_function_elements.cc.
References d2shape_eulerian_at_knot(), oomph::FiniteElement::dshape_eulerian_at_knot(), DShape_eulerian_stored_pt, and Jacobian_eulerian_stored_pt.
Referenced by d2shape_local_at_knot(), and jacobian_eulerian_stored_pt().
dshape_eulerian_stored_pt() [1/2]
Vector<DShape*>* & oomph::StorableShapeElementBase::dshape_eulerian_stored_pt () [inline]
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the global (eulerian) coordinates.
Definition at line 212 of file stored_shape_function_elements.h.
References DShape_eulerian_stored_pt.
Referenced by set_dshape_eulerian_stored_from_element().
dshape_eulerian_stored_pt() [2/2]
Vector<DShape*>* const& oomph::StorableShapeElementBase::dshape_eulerian_stored_pt () const [inline]
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the global (eulerian) coordinates (const version)
Definition at line 218 of file stored_shape_function_elements.h.
References DShape_eulerian_stored_pt.
dshape_local_at_knot()
void oomph::StorableShapeElementBase::dshape_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids) const [virtual]
Return the geometric shape function and its derivative w.r.t. the local coordinates at the ipt-th integration point. If pre-computed values have been stored, they will be used.
Return the shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Reimplemented from oomph::FiniteElement.
Definition at line 680 of file stored_shape_function_elements.cc.
References d2shape_local_at_knot(), oomph::FiniteElement::dshape_local_at_knot(), and DShape_local_stored_pt.
Referenced by jacobian_eulerian_stored_pt(), and shape_at_knot().
dshape_local_stored_pt() [1/2]
Vector<DShape*>* & oomph::StorableShapeElementBase::dshape_local_stored_pt () [inline]
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the local coordinates.
Definition at line 189 of file stored_shape_function_elements.h.
References DShape_local_stored_pt.
Referenced by set_shape_local_stored_from_element().
dshape_local_stored_pt() [2/2]
Vector<DShape*>* const& oomph::StorableShapeElementBase::dshape_local_stored_pt () const [inline]
Return a pointer to the vector of pointers to the stored first derivatives of the shape functions w.r.t the local coordinates (const version)
Definition at line 195 of file stored_shape_function_elements.h.
References DShape_local_stored_pt.
J_eulerian_at_knot()
double oomph::StorableShapeElementBase::J_eulerian_at_knot (const unsigned & ipt) const [virtual]
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point.
Return the Jacobian of the mapping between the local and global coordinates. If the value has been precomputed return that.
Reimplemented from oomph::FiniteElement.
Definition at line 777 of file stored_shape_function_elements.cc.
References oomph::FiniteElement::J_eulerian_at_knot(), Jacobian_eulerian_stored_pt, and set_shape_local_stored_from_element().
Referenced by jacobian_eulerian_stored_pt().
jacobian_eulerian_stored_pt() [1/2]
Vector<double>* & oomph::StorableShapeElementBase::jacobian_eulerian_stored_pt () [inline]
Return a pointer to the vector of Jacobians of the mapping between the local and global (eulerian) coordinates.
Definition at line 235 of file stored_shape_function_elements.h.
References Jacobian_eulerian_stored_pt.
Referenced by set_dshape_eulerian_stored_from_element().
jacobian_eulerian_stored_pt() [2/2]
Vector<double>* const& oomph::StorableShapeElementBase::jacobian_eulerian_stored_pt () const [inline]
Return a pointer to the vector of Jacobians of the mapping between the local and global (eulerian) coordinates (const version)
Definition at line 241 of file stored_shape_function_elements.h.
References d2shape_eulerian_at_knot(), d2shape_local_at_knot(), dshape_eulerian_at_knot(), dshape_local_at_knot(), J_eulerian_at_knot(), Jacobian_eulerian_stored_pt, pre_compute_d2shape_eulerian_at_knots(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_eulerian_at_knots(), pre_compute_dshape_local_at_knots(), pre_compute_J_eulerian_at_knots(), pre_compute_shape_at_knots(), set_dshape_eulerian_stored_from_element(), set_shape_local_stored_from_element(), and shape_at_knot().
operator=()
void oomph::StorableShapeElementBase::operator= (const StorableShapeElementBase &) [inline]
Broken assignment operator.
Definition at line 127 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_assign(), delete_all_dshape_eulerian_stored(), delete_all_shape_local_stored(), delete_d2shape_eulerian_stored(), delete_d2shape_local_stored(), delete_dshape_eulerian_stored(), delete_dshape_local_stored(), delete_J_eulerian_stored(), delete_shape_local_stored(), oomph::FiniteElement::integral_pt(), and set_integration_scheme().
pre_compute_d2shape_eulerian_at_knots()
void oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots ()
Calculate the first and second derivatives of the shape functions w.r.t global coordinates at the integration points and store the results internally.
Calculate the values of the first and second derivatives of the shape functions at the integration points and store in the internal storage of the element
Definition at line 579 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, oomph::FiniteElement::d2shape_eulerian_at_knot(), D2Shape_eulerian_stored_pt, delete_d2shape_eulerian_stored(), delete_dshape_eulerian_stored(), delete_J_eulerian_stored(), DShape_eulerian_stored_pt, i, oomph::FiniteElement::integral_pt(), Jacobian_eulerian_stored_pt, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::oomph_info, and pre_compute_shape_at_knots().
Referenced by jacobian_eulerian_stored_pt(), and set_integration_scheme().
pre_compute_d2shape_local_at_knots()
void oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots ()
Calculate the second derivatives of the shape functions w.r.t. local coordinates at the integration points and store the results internally.
Calculate the shape functions and thir first and second derivatives w.r.t. local coordinates at the integration points and store in internal storage of the element
Definition at line 406 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, oomph::FiniteElement::d2shape_local_at_knot(), D2Shape_local_stored_pt, delete_d2shape_local_stored(), delete_dshape_local_stored(), delete_shape_local_stored(), oomph::Multi_domain_functions::Dim, oomph::FiniteElement::dim(), DShape_local_stored_pt, i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::oomph_info, Shape_stored_pt, and oomph::Global_string_for_annotation::string().
Referenced by jacobian_eulerian_stored_pt(), and set_integration_scheme().
pre_compute_dshape_eulerian_at_knots()
void oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots ()
Calculate the first derivatives of the shape functions w.r.t the global coordinates at the integration points and store the results internally.
Calculate the values of the derivatives of the shape functions at the integration points and store in the internal storage of the element
Definition at line 521 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, delete_dshape_eulerian_stored(), delete_J_eulerian_stored(), oomph::FiniteElement::dshape_eulerian_at_knot(), DShape_eulerian_stored_pt, i, oomph::FiniteElement::integral_pt(), Jacobian_eulerian_stored_pt, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), and pre_compute_shape_at_knots().
Referenced by jacobian_eulerian_stored_pt(), and set_integration_scheme().
pre_compute_dshape_local_at_knots()
void oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots ()
Calculate the shape functions and first derivatives w.r.t. local coordinatess at the integration points and store the results internally.
Calculate the shape functions and thir first derivatives w.r.t. local coordinates at the integration points and store in internal storage of the element
Definition at line 333 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, delete_dshape_local_stored(), delete_shape_local_stored(), oomph::Multi_domain_functions::Dim, oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), DShape_local_stored_pt, i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), Shape_stored_pt, and oomph::Global_string_for_annotation::string().
Referenced by jacobian_eulerian_stored_pt(), and set_integration_scheme().
pre_compute_J_eulerian_at_knots()
void oomph::StorableShapeElementBase::pre_compute_J_eulerian_at_knots ()
Calculate the Jacobian of the mapping from local to global coordinates at the integration points and store the results internally.
Calculate the value of the Jacobian of the mapping from local to global coordinates at the integration points and store internally
Definition at line 497 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, delete_J_eulerian_stored(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::J_eulerian_at_knot(), Jacobian_eulerian_stored_pt, and oomph::Integral::nweight().
Referenced by jacobian_eulerian_stored_pt(), and set_integration_scheme().
pre_compute_shape_at_knots()
void oomph::StorableShapeElementBase::pre_compute_shape_at_knots ()
Calculate the shape functions at the integration points and store the results internally.
Calculate the shape functions at the integration points and store in internal storage of the element
Definition at line 272 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, delete_shape_local_stored(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::FiniteElement::shape_at_knot(), Shape_stored_pt, and oomph::Global_string_for_annotation::string().
Referenced by jacobian_eulerian_stored_pt(), pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), pre_compute_dshape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), and set_integration_scheme().
set_dshape_eulerian_stored_from_element()
void oomph::StorableShapeElementBase::set_dshape_eulerian_stored_from_element (StorableShapeElementBase *const & element_pt)
Set the derivatives of stored shape functions with respect to the global coordinates to be the same as those pointed to by the FiniteElement element_pt. Note that this function also calls set_shape_local_stored_from_element(element_pt). so that the local derivatives are also stored. Calling this function only makes sense for uniformly-spaced meshes with elements of equal sizes.
Set the stored derivatives of shape functions w.r.t Eulerian coordinates to be those stored in the StorableShapeElementBase pointed to by element_pt. Using this function will allow a saving in the storage required for integration schemes in the (most common) case when a large number of elements have the same integration scheme
Definition at line 842 of file stored_shape_function_elements.cc.
References Can_delete_dshape_eulerian_stored, D2Shape_eulerian_stored_pt, d2shape_eulerian_stored_pt(), delete_all_dshape_eulerian_stored(), DShape_eulerian_stored_pt, dshape_eulerian_stored_pt(), Jacobian_eulerian_stored_pt, jacobian_eulerian_stored_pt(), and set_shape_local_stored_from_element().
Referenced by jacobian_eulerian_stored_pt(), and set_shape_local_stored_from_element().
set_integration_scheme()
void oomph::StorableShapeElementBase::set_integration_scheme (Integral *const & integral_pt) [virtual]
Set the spatial integration scheme -- overloaded from the finite element base class since a change in the integration scheme forces a recomputation of the shape fcts at the integration points.
Set the spatial integration scheme and also calculate the values of the shape functions and their derivatives w.r.t. the local coordinates, placing the values into storage so that they may be re-used, without recalculation
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::StorableShapeSolidElementBase.
Definition at line 228 of file stored_shape_function_elements.cc.
References D2Shape_eulerian_stored_pt, D2Shape_local_stored_pt, DShape_eulerian_stored_pt, DShape_local_stored_pt, Jacobian_eulerian_stored_pt, pre_compute_d2shape_eulerian_at_knots(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_eulerian_at_knots(), pre_compute_dshape_local_at_knots(), pre_compute_J_eulerian_at_knots(), pre_compute_shape_at_knots(), oomph::FiniteElement::set_integration_scheme(), and Shape_stored_pt.
Referenced by operator=(), oomph::StorableShapeSolidElementBase::set_integration_scheme(), oomph::StorableShapeElement< ELEMENT >::StorableShapeElement(), oomph::StorableShapeSolidElement< ELEMENT >::StorableShapeSolidElement(), and ~StorableShapeElementBase().
set_shape_local_stored_from_element()
void oomph::StorableShapeElementBase::set_shape_local_stored_from_element (StorableShapeElementBase *const & element_pt)
Set the shape functions pointed to internally to be those pointed to by the FiniteElement element_pt (In most cases all elements of the same type have the same number of integration points so the shape function values and their local derivatives are the same --> They only need to be stored by one element). Calling this function deletes the locally created storage and re-directs the pointers to the stored shape function of the specified element.
Set the shape functions referenced in the internal vectors to be those stored in the StorableShapeElementBase pointed to by element_pt. Using this function will allow a saving in the storage required for integration schemes in the (most common) case when a large number of elements have the same integration scheme
Definition at line 799 of file stored_shape_function_elements.cc.
References Can_delete_shape_local_stored, D2Shape_local_stored_pt, d2shape_local_stored_pt(), delete_all_shape_local_stored(), DShape_local_stored_pt, dshape_local_stored_pt(), set_dshape_eulerian_stored_from_element(), Shape_stored_pt, shape_stored_pt(), and oomph::Global_string_for_annotation::string().
Referenced by J_eulerian_at_knot(), jacobian_eulerian_stored_pt(), set_dshape_eulerian_stored_from_element(), and oomph::StorableShapeSolidElementBase::set_dshape_lagrangian_stored_from_element().
shape_at_knot()
void oomph::StorableShapeElementBase::shape_at_knot (const unsigned & ipt, Shape & psi) const [virtual]
Return the geometric shape function at the ipt-th integration point.
Return the shape function stored at the ipt-th integration point.
Reimplemented from oomph::FiniteElement.
Definition at line 658 of file stored_shape_function_elements.cc.
References dshape_local_at_knot(), oomph::FiniteElement::shape_at_knot(), and Shape_stored_pt.
Referenced by jacobian_eulerian_stored_pt().
shape_stored_pt() [1/4]
Vector<Shape*>* & oomph::StorableShapeElementBase::shape_stored_pt () [inline]
Return a pointer to the vector of pointers to the stored shape functions.
Definition at line 170 of file stored_shape_function_elements.h.
References Shape_stored_pt.
Referenced by oomph::StorableShapeSolidElementBase::d2shape_lagrangian_at_knot(), oomph::StorableShapeSolidElementBase::dshape_lagrangian_at_knot(), and set_shape_local_stored_from_element().
shape_stored_pt() [2/4]
Vector<Shape*>* const& oomph::StorableShapeElementBase::shape_stored_pt () const [inline]
Return a pointer to the vector of pointers to the stored shape functions (const version)
Definition at line 174 of file stored_shape_function_elements.h.
References Shape_stored_pt.
shape_stored_pt() [3/4]
Shape* & oomph::StorableShapeElementBase::shape_stored_pt (const unsigned & ipt) [inline]
Return a pointer to the stored shape function at the ipt-th integration point.
Definition at line 179 of file stored_shape_function_elements.h.
shape_stored_pt() [4/4]
Shape* const& oomph::StorableShapeElementBase::shape_stored_pt (const unsigned & ipt) const [inline]
Return a pointer to the stored shape function at the ipt-th integration point (const version)
Definition at line 184 of file stored_shape_function_elements.h.
Member Data Documentation
Can_delete_dshape_eulerian_stored
bool oomph::StorableShapeElementBase::Can_delete_dshape_eulerian_stored [private]
Boolean to determine whether the element can delete the stored derivatives of shape functions w.r.t. global coordinates.
Definition at line 101 of file stored_shape_function_elements.h.
Referenced by delete_d2shape_eulerian_stored(), delete_dshape_eulerian_stored(), delete_J_eulerian_stored(), pre_compute_d2shape_eulerian_at_knots(), pre_compute_dshape_eulerian_at_knots(), pre_compute_J_eulerian_at_knots(), and set_dshape_eulerian_stored_from_element().
Can_delete_shape_local_stored
bool oomph::StorableShapeElementBase::Can_delete_shape_local_stored [private]
Boolean to determine whether the element can delete the stored local shape functions.
Definition at line 85 of file stored_shape_function_elements.h.
Referenced by delete_d2shape_local_stored(), delete_dshape_local_stored(), delete_shape_local_stored(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_local_at_knots(), pre_compute_shape_at_knots(), and set_shape_local_stored_from_element().
D2Shape_eulerian_stored_pt
Vector<DShape*>* oomph::StorableShapeElementBase::D2Shape_eulerian_stored_pt [private]
Pointer to storage for the second derivatives of the shape functions w.r.t. global coordinates at integration points.
Definition at line 93 of file stored_shape_function_elements.h.
Referenced by d2shape_eulerian_at_knot(), d2shape_eulerian_stored_pt(), delete_d2shape_eulerian_stored(), pre_compute_d2shape_eulerian_at_knots(), set_dshape_eulerian_stored_from_element(), and set_integration_scheme().
D2Shape_local_stored_pt
Vector<DShape*>* oomph::StorableShapeElementBase::D2Shape_local_stored_pt [private]
Pointer to storage for the pointers to the second derivatives of the nodal shape functions w.r.t. the local coordinates at integration points.
Definition at line 81 of file stored_shape_function_elements.h.
Referenced by d2shape_local_at_knot(), d2shape_local_stored_pt(), delete_d2shape_local_stored(), pre_compute_d2shape_local_at_knots(), set_integration_scheme(), and set_shape_local_stored_from_element().
DShape_eulerian_stored_pt
Vector<DShape*>* oomph::StorableShapeElementBase::DShape_eulerian_stored_pt [private]
Pointer to storage for the derivatives of the shape functions w.r.t. global coordinates at integration points.
Definition at line 89 of file stored_shape_function_elements.h.
Referenced by delete_dshape_eulerian_stored(), dshape_eulerian_at_knot(), dshape_eulerian_stored_pt(), pre_compute_d2shape_eulerian_at_knots(), pre_compute_dshape_eulerian_at_knots(), set_dshape_eulerian_stored_from_element(), and set_integration_scheme().
DShape_local_stored_pt
Vector<DShape*>* oomph::StorableShapeElementBase::DShape_local_stored_pt [private]
Pointer to storage for the pointers to the derivatives of the nodal shape functions w.r.t. the local coordinates at integration points.
Definition at line 76 of file stored_shape_function_elements.h.
Referenced by delete_dshape_local_stored(), dshape_local_at_knot(), dshape_local_stored_pt(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_local_at_knots(), set_integration_scheme(), and set_shape_local_stored_from_element().
Jacobian_eulerian_stored_pt
Vector<double>* oomph::StorableShapeElementBase::Jacobian_eulerian_stored_pt [private]
Pointer to storage for the Jacobian of the element w.r.t global coordinates.
Definition at line 97 of file stored_shape_function_elements.h.
Referenced by d2shape_eulerian_at_knot(), delete_J_eulerian_stored(), dshape_eulerian_at_knot(), J_eulerian_at_knot(), jacobian_eulerian_stored_pt(), pre_compute_d2shape_eulerian_at_knots(), pre_compute_dshape_eulerian_at_knots(), pre_compute_J_eulerian_at_knots(), set_dshape_eulerian_stored_from_element(), and set_integration_scheme().
Shape_stored_pt
Vector<Shape*>* oomph::StorableShapeElementBase::Shape_stored_pt [private]
Pointer to storage for the pointers to the nodal shape functions at the integration points (knots)
Definition at line 72 of file stored_shape_function_elements.h.
Referenced by delete_shape_local_stored(), pre_compute_d2shape_local_at_knots(), pre_compute_dshape_local_at_knots(), pre_compute_shape_at_knots(), set_integration_scheme(), set_shape_local_stored_from_element(), shape_at_knot(), and shape_stored_pt().
The documentation for this class was generated from the following files:
stored_shape_function_elements.h
stored_shape_function_elements.cc