oomph::PoissonFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied flux on the boundaries of Poisson elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <poisson_flux_elements.h>
Public Types
typedef void(* PoissonPrescribedFluxFctPt) (const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Public Member Functions
PoissonFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
PoissonFluxElement ()
Broken empty constructor.
PoissonFluxElement (const PoissonFluxElement &dummy)
Broken copy constructor.
void operator= (const PoissonFluxElement &)
Broken assignment operator.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
PoissonPrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function.
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const Vector< double > &x, double &flux)
Private Member Functions
void fill_in_generic_residual_contribution_poisson_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Private Attributes
PoissonPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
unsigned Dim
The spatial dimension of the problem.
unsigned U_index_poisson
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PoissonFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied flux on the boundaries of Poisson elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 54 of file poisson_flux_elements.h.
Member Typedef Documentation
PoissonPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::PoissonFluxElement< ELEMENT >::PoissonPrescribedFluxFctPt) (const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Definition at line 63 of file poisson_flux_elements.h.
Constructor & Destructor Documentation
PoissonFluxElement() [1/3]
template<class ELEMENT >
oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 276 of file poisson_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::PoissonFluxElement< ELEMENT >::Dim, oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), oomph::PoissonFluxElement< ELEMENT >::Flux_fct_pt, oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), oomph::PoissonEquations< DIM >::u_index_poisson(), and oomph::PoissonFluxElement< ELEMENT >::U_index_poisson.
PoissonFluxElement() [2/3]
template<class ELEMENT >
oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement () [inline]
Broken empty constructor.
Definition at line 71 of file poisson_flux_elements.h.
PoissonFluxElement() [3/3]
template<class ELEMENT >
oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement (const PoissonFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 80 of file poisson_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 116 of file poisson_flux_elements.h.
References oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 105 of file poisson_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux().
fill_in_generic_residual_contribution_poisson_flux()
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 431 of file poisson_flux_elements.h.
References oomph::PoissonFluxElement< ELEMENT >::Dim, oomph::PoissonFluxElement< ELEMENT >::get_flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), s, oomph::PoissonFluxElement< ELEMENT >::shape_and_test(), oomph::PoissonFluxElement< ELEMENT >::U_index_poisson, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PoissonFluxElement< ELEMENT >::get_flux(), and oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement().
flux_fct_pt()
template<class ELEMENT >
PoissonPrescribedFluxFctPt& oomph::PoissonFluxElement< ELEMENT >::flux_fct_pt () [inline]
Access function for the prescribed-flux function pointer.
Definition at line 101 of file poisson_flux_elements.h.
References oomph::PoissonFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::get_flux (const Vector< double > & x, double & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position
Definition at line 224 of file poisson_flux_elements.h.
References oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), and oomph::PoissonFluxElement< ELEMENT >::Flux_fct_pt.
Referenced by oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), and oomph::PoissonFluxElement< ELEMENT >::output().
operator=()
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::operator= (const PoissonFluxElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 86 of file poisson_flux_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 124 of file poisson_flux_elements.h.
output() [2/4]
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 131 of file poisson_flux_elements.h.
References oomph::FiniteElement::dim(), oomph::PoissonFluxElement< ELEMENT >::get_flux(), oomph::FiniteElement::get_s_plot(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 170 of file poisson_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::PoissonFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 175 of file poisson_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::PoissonFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 184 of file poisson_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::PoissonFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 204 of file poisson_flux_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
zeta_nodal()
template<class ELEMENT >
double oomph::PoissonFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 96 of file poisson_flux_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::PoissonFluxElement< ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 253 of file poisson_flux_elements.h.
Referenced by oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), and oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement().
Flux_fct_pt
template<class ELEMENT >
PoissonPrescribedFluxFctPt oomph::PoissonFluxElement< ELEMENT >::Flux_fct_pt [private]
Function pointer to the (global) prescribed-flux function.
Definition at line 250 of file poisson_flux_elements.h.
Referenced by oomph::PoissonFluxElement< ELEMENT >::flux_fct_pt(), oomph::PoissonFluxElement< ELEMENT >::get_flux(), and oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement().
U_index_poisson
template<class ELEMENT >
unsigned oomph::PoissonFluxElement< ELEMENT >::U_index_poisson [private]
The index at which the unknown is stored at the nodes.
Definition at line 256 of file poisson_flux_elements.h.
Referenced by oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), and oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement().
The documentation for this class was generated from the following file:
poisson_flux_elements.h