oomph::RectangleWithHoleMesh< ELEMENT > Class Template Reference
Domain-based mesh for rectangular mesh with circular hole.
#include <rectangle_with_hole_mesh.template.h>
Public Member Functions
RectangleWithHoleMesh (GeomObject *cylinder_pt, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
RectangleWithHoleDomain * domain_pt ()
Access function to the domain.
Protected Attributes
RectangleWithHoleDomain * Domain_pt
Pointer to the domain.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RectangleWithHoleMesh< ELEMENT >
Domain-based mesh for rectangular mesh with circular hole.
Definition at line 54 of file rectangle_with_hole_mesh.template.h.
Constructor & Destructor Documentation
RectangleWithHoleMesh()
template<class ELEMENT >
oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh (GeomObject * cylinder_pt, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
Definition at line 66 of file rectangle_with_hole_mesh.template.h.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::convert_to_boundary_node(), oomph::RectangleWithHoleMesh< ELEMENT >::Domain_pt, e, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), oomph::Domain::macro_element_pt(), oomph::MacroElement::macro_map(), oomph::Domain::nmacro_element(), oomph::Mesh::Node_pt, oomph::FiniteElement::node_pt(), s, and oomph::Mesh::set_nboundary().
Member Function Documentation
domain_pt()
template<class ELEMENT >
RectangleWithHoleDomain* oomph::RectangleWithHoleMesh< ELEMENT >::domain_pt () [inline]
Access function to the domain.
Definition at line 243 of file rectangle_with_hole_mesh.template.h.
References oomph::RectangleWithHoleMesh< ELEMENT >::Domain_pt.
Member Data Documentation
Domain_pt
template<class ELEMENT >
RectangleWithHoleDomain* oomph::RectangleWithHoleMesh< ELEMENT >::Domain_pt [protected]
Pointer to the domain.
Definition at line 248 of file rectangle_with_hole_mesh.template.h.
Referenced by oomph::RectangleWithHoleMesh< ELEMENT >::domain_pt(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), and oomph::RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh().
The documentation for this class was generated from the following file:
rectangle_with_hole_mesh.template.h