oomph::BinArrayParameters Class Reference
Helper object for dealing with the parameters used for the BinArray objects.
#include <sample_point_parameters.h>
Public Member Functions
BinArrayParameters (const BinArrayParameters &data)
Broken copy constructor.
void operator= (const BinArrayParameters &)
Broken assignment operator.
virtual ~BinArrayParameters ()
Empty destructor.
Vector< unsigned > & dimensions_of_bin_array ()
Number of bins in each coordinate direction.
Vector< unsigned > dimensions_of_bin_array () const
Number of bins in each coordinate direction. Const version.
Protected Attributes
Vector< unsigned > Dimensions_of_bin_array
Number of bins in each coordinate direction.
Private Member Functions
BinArrayParameters (Mesh *mesh_pt)
Constructor: Pass mesh. Constructor is private and can only be called by the derived friends.
BinArrayParameters ()
Broken default constructor; needed for broken copy constructors. Don't call. It will die.
Friends
class RefineableBinArrayParameters
Constructor is private and only accessible by friends.
class NonRefineableBinArrayParameters
Additional Inherited Members
Detailed Description
Helper object for dealing with the parameters used for the BinArray objects.
Definition at line 288 of file sample_point_parameters.h.
Constructor & Destructor Documentation
BinArrayParameters() [1/3]
oomph::BinArrayParameters::BinArrayParameters (const BinArrayParameters & data) [inline]
Broken copy constructor.
Definition at line 298 of file sample_point_parameters.h.
References oomph::BrokenCopy::broken_copy().
 BinArrayParameters()
virtual oomph::BinArrayParameters::~BinArrayParameters () [inline], [virtual]
Empty destructor.
Definition at line 311 of file sample_point_parameters.h.
BinArrayParameters() [2/3]
oomph::BinArrayParameters::BinArrayParameters (Mesh * mesh_pt) [inline], [private]
Constructor: Pass mesh. Constructor is private and can only be called by the derived friends.
Definition at line 334 of file sample_point_parameters.h.
BinArrayParameters() [3/3]
oomph::BinArrayParameters::BinArrayParameters () [inline], [private]
Broken default constructor; needed for broken copy constructors. Don't call. It will die.
Definition at line 339 of file sample_point_parameters.h.
Member Function Documentation
dimensions_of_bin_array() [1/2]
Vector<unsigned>& oomph::BinArrayParameters::dimensions_of_bin_array () [inline]
Number of bins in each coordinate direction.
Definition at line 314 of file sample_point_parameters.h.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
dimensions_of_bin_array() [2/2]
Vector<unsigned> oomph::BinArrayParameters::dimensions_of_bin_array () const [inline]
Number of bins in each coordinate direction. Const version.
Definition at line 320 of file sample_point_parameters.h.
operator=()
void oomph::BinArrayParameters::operator= (const BinArrayParameters &) [inline]
Broken assignment operator.
Definition at line 305 of file sample_point_parameters.h.
References oomph::BrokenCopy::broken_assign().
Friends And Related Function Documentation
NonRefineableBinArrayParameters
friend class NonRefineableBinArrayParameters [friend]
Definition at line 295 of file sample_point_parameters.h.
RefineableBinArrayParameters
friend class RefineableBinArrayParameters [friend]
Constructor is private and only accessible by friends.
Definition at line 294 of file sample_point_parameters.h.
Member Data Documentation
Dimensions_of_bin_array
Vector<unsigned> oomph::BinArrayParameters::Dimensions_of_bin_array [protected]
Number of bins in each coordinate direction.
Definition at line 328 of file sample_point_parameters.h.
The documentation for this class was generated from the following file:
sample_point_parameters.h