oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT > Class Template Reference
A class for elements that allow the imposition of an prescribed flux (determined from the normal displacements of an adjacent linearly elastic solid. Normal derivative for displacement potential is given by normal displacement of adjacent solid multiplies by FSI parameter (q = k^2 B/E). The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <pml_helmholtz_time_harmonic_linear_elasticity_interaction.h>
Public Member Functions
PMLHelmholtzFluxFromNormalDisplacementBCElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached.
PMLHelmholtzFluxFromNormalDisplacementBCElement (const PMLHelmholtzFluxFromNormalDisplacementBCElement &dummy)
Broken copy constructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Broken assignment operator.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: flux etc at Gauss points; n_plot is ignored.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return.
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz_flux_from_displacement (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Private Attributes
unsigned Dim
The spatial dimension of the problem.
std::complex< unsigned > U_index_helmholtz_from_displacement
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class HELMHOLTZ_BULK_ELEMENT, class ELASTICITY_BULK_ELEMENT>
class oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >
A class for elements that allow the imposition of an prescribed flux (determined from the normal displacements of an adjacent linearly elastic solid. Normal derivative for displacement potential is given by normal displacement of adjacent solid multiplies by FSI parameter (q = k^2 B/E). The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 698 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Constructor & Destructor Documentation
PMLHelmholtzFluxFromNormalDisplacementBCElement() [1/2]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached.
Constructor, takes the pointer to the `bulk` element, and the face index that identifies the face of the bulk element to which this face element is to be attached.
Definition at line 917 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FiniteElement::build_face_element(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::ElementWithExternalElement::set_ninteraction(), oomph::Global_string_for_annotation::string(), oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz(), and oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::U_index_helmholtz_from_displacement.
PMLHelmholtzFluxFromNormalDisplacementBCElement() [2/2]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement (const PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 714 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 746 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd().
fill_in_contribution_to_residuals()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Broken assignment operator.
Add the element's contribution to its residual vector
Reimplemented from oomph::GeneralisedElement.
Definition at line 735 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_residual_contribution_helmholtz_flux_from_displacement()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Helper function to compute the element's residual vector and the Jacobian matrix.
Definition at line 1085 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim, oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::U_index_helmholtz_from_displacement, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement().
output() [1/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 758 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output().
output() [2/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: flux etc at Gauss points; n_plot is ignored.
Reimplemented from oomph::FiniteElement.
Definition at line 766 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::Multi_domain_functions::Dim, oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::Integral::knot(), oomph::Integral::nweight(), and oomph::FaceElement::outer_unit_normal().
output() [3/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 830 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::output().
output() [4/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 834 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::output().
shape_and_test()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
double oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 844 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement().
shape_and_test_at_knot()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
double oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return.
the Jacobian of mapping between local and global (Eulerian) coordinates
Definition at line 865 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Member Data Documentation
Dim
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
unsigned oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 895 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), and oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement().
U_index_helmholtz_from_displacement
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
std::complex<unsigned> oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::U_index_helmholtz_from_displacement [private]
The index at which the unknown is stored at the nodes.
Definition at line 898 of file pml_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), and oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement().
The documentation for this class was generated from the following file:
pml_helmholtz_time_harmonic_linear_elasticity_interaction.h