oomph::TPVDElementWithContinuousPressure< DIM > Class Template Reference
#include <solid_elements.h>
Public Member Functions
TPVDElementWithContinuousPressure ()
Constructor.
TPVDElementWithContinuousPressure (const TPVDElementWithContinuousPressure< DIM > &dummy)
Broken copy constructor.
int solid_p_nodal_index () const
Broken assignment operator.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
double solid_p (const unsigned &l)
void set_solid_p (const unsigned &l, const double &p_value)
Set the l-th solid pressure value to p_value.
unsigned npres_solid () const
Return number of pressure values.
void fix_solid_pressure (const unsigned &l, const double &pvalue)
Fix the pressure dof l to be the value pvalue.
void output (std::ostream &outfile)
Generic FiniteElement output function.
void output (std::ostream &outfile, const unsigned &n_plot)
PVDEquationsWithPressure output function.
void output (FILE *file_pt)
C-style generic FiniteElement output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style PVDEquationsWithPressure output function.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
template<>
unsigned npres_solid () const
template<>
unsigned npres_solid () const
Protected Member Functions
int solid_p_local_eqn (const unsigned &i) const
Overload the access function that is used to return local equation corresponding to the i-th solid pressure value.
void solid_pshape (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
template<>
const unsigned Pconv [3]
Data for the pressure conversion array.
template<>
const unsigned Pconv [4]
Data for the pressure conversion array.
template<>
void solid_pshape (const Vector< double > &s, Shape &psi) const
template<>
void solid_pshape (const Vector< double > &s, Shape &psi) const
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
void unpin_elemental_solid_pressure_dofs ()
Unpin all solid pressure dofs in the element.
template<>
const unsigned Initial_Nvalue [6]
Data for the number of variables at each node.
template<>
const unsigned Initial_Nvalue [10]
Data for the number of variables at each node.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::TPVDElementWithContinuousPressure< DIM >
An Element that solves the solid mechanics equations in an (near) incompressible formulation with quadratic interpolation for velocities and positions and continous linear pressure interpolation. This is equivalent to the TTaylorHoodElement element for fluids.
Definition at line 1997 of file solid_elements.h.
Constructor & Destructor Documentation
TPVDElementWithContinuousPressure() [1/2]
template<unsigned DIM>
oomph::TPVDElementWithContinuousPressure< DIM >::TPVDElementWithContinuousPressure () [inline]
Constructor.
Definition at line 2035 of file solid_elements.h.
TPVDElementWithContinuousPressure() [2/2]
template<unsigned DIM>
oomph::TPVDElementWithContinuousPressure< DIM >::TPVDElementWithContinuousPressure (const TPVDElementWithContinuousPressure< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 2041 of file solid_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fix_solid_pressure()
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::fix_solid_pressure (const unsigned & l, const double & pvalue) [inline]
Fix the pressure dof l to be the value pvalue.
Definition at line 2078 of file solid_elements.h.
References oomph::FiniteElement::node_pt(), oomph::Data::pin(), oomph::Data::set_value(), and oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
get_Z2_flux()
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 2120 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::get_strain(), and i.
Initial_Nvalue() [1/2]
template<>
const unsigned oomph::TPVDElementWithContinuousPressure< 2 >::Initial_Nvalue () [private]
Data for the number of variables at each node.
Definition at line 2411 of file solid_elements.cc.
Initial_Nvalue() [2/2]
template<>
const unsigned oomph::TPVDElementWithContinuousPressure< 3 >::Initial_Nvalue () [private]
Data for the number of variables at each node.
Definition at line 2424 of file solid_elements.cc.
npres_solid() [1/3]
template<unsigned DIM>
unsigned oomph::TPVDElementWithContinuousPressure< DIM >::npres_solid () const [virtual]
Return number of pressure values.
Reimplemented from oomph::PVDEquationsBase< DIM >.
npres_solid() [2/3]
template<>
unsigned oomph::TPVDElementWithContinuousPressure< 2 >::npres_solid () const [inline], [virtual]
2D : Number of pressure values
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 2172 of file solid_elements.h.
npres_solid() [3/3]
template<>
unsigned oomph::TPVDElementWithContinuousPressure< 3 >::npres_solid () const [inline], [virtual]
3D : Number of pressure values
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 2180 of file solid_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::TPVDElementWithContinuousPressure< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 2101 of file solid_elements.h.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::TPVDElementWithContinuousPressure< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 2112 of file solid_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::TPVDElementWithContinuousPressure< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 2104 of file solid_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::output (std::ostream & outfile) [inline], [virtual]
Generic FiniteElement output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2085 of file solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
PVDEquationsWithPressure output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2088 of file solid_elements.h.
References oomph::PVDEquationsWithPressure< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style generic FiniteElement output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2093 of file solid_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style PVDEquationsWithPressure output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2096 of file solid_elements.h.
References oomph::PVDEquationsWithPressure< DIM >::output().
Pconv() [1/2]
template<>
const unsigned oomph::TPVDElementWithContinuousPressure< 2 >::Pconv () [protected]
Data for the pressure conversion array.
Definition at line 2417 of file solid_elements.cc.
Pconv() [2/2]
template<>
const unsigned oomph::TPVDElementWithContinuousPressure< 3 >::Pconv () [protected]
Data for the pressure conversion array.
Definition at line 2430 of file solid_elements.cc.
required_nvalue()
template<unsigned DIM>
virtual unsigned oomph::TPVDElementWithContinuousPressure< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Definition at line 2062 of file solid_elements.h.
set_solid_p()
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::set_solid_p (const unsigned & l, const double & p_value) [inline], [virtual]
Set the l-th solid pressure value to p_value.
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2071 of file solid_elements.h.
References oomph::FiniteElement::node_pt(), oomph::PVDEquationsBase< DIM >::npres_solid(), oomph::Data::set_value(), and oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
solid_p()
template<unsigned DIM>
double oomph::TPVDElementWithContinuousPressure< DIM >::solid_p (const unsigned & l) [inline], [virtual]
Return the l-th pressure value, make sure to use the hanging representation if there is one!
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2067 of file solid_elements.h.
References oomph::FiniteElement::nodal_value(), and oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
solid_p_local_eqn()
template<unsigned DIM>
int oomph::TPVDElementWithContinuousPressure< DIM >::solid_p_local_eqn (const unsigned & i) const [inline], [protected], [virtual]
Overload the access function that is used to return local equation corresponding to the i-th solid pressure value.
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 2026 of file solid_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), s, and oomph::PVDEquationsBase< DIM >::solid_p_nodal_index().
solid_p_nodal_index()
template<unsigned DIM>
int oomph::TPVDElementWithContinuousPressure< DIM >::solid_p_nodal_index () const [inline], [virtual]
Broken assignment operator.
Set the value at which the solid pressure is stored in the nodes
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 2058 of file solid_elements.h.
solid_pshape() [1/3]
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
Implements oomph::PVDEquationsWithPressure< DIM >.
solid_pshape() [2/3]
template<>
void oomph::TPVDElementWithContinuousPressure< 2 >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
2D : Pressure shape functions
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2189 of file solid_elements.h.
solid_pshape() [3/3]
template<>
void oomph::TPVDElementWithContinuousPressure< 3 >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
3D : Pressure shape functions
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 2202 of file solid_elements.h.
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM>
void oomph::TPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs () [inline], [private], [virtual]
Unpin all solid pressure dofs in the element.
Implements oomph::PVDEquationsBase< DIM >.
Definition at line 2007 of file solid_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::PVDEquationsBase< DIM >::solid_p_nodal_index(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::TPVDElementWithContinuousPressure< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 2108 of file solid_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned oomph::TPVDElementWithContinuousPressure< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 2004 of file solid_elements.h.
Pconv
template<unsigned DIM>
const unsigned oomph::TPVDElementWithContinuousPressure< DIM >::Pconv[] [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 2021 of file solid_elements.h.
The documentation for this class was generated from the following file:
solid_elements.h