oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT > Class Template Reference
#include <Tpml_time_harmonic_linear_elasticity_elements.h>
Public Member Functions
TPMLTimeHarmonicLinearElasticityElement ()
Constructor: Call constructors for TElement and PMLTimeHarmonicLinearElasticity equations.
TPMLTimeHarmonicLinearElasticityElement (const TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT > &dummy)
Broken copy constructor.
void operator= (const TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT > &)
Broken assignment operator.
void output (std::ostream &outfile)
Output function:
void output (std::ostream &outfile, const unsigned &nplot)
Output function:
void output (FILE *file_pt)
C-style output function:
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function:
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
class oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >
TPMLTimeHarmonicLinearElasticityElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional PMLTimeHarmonicLinearElasticity elements with NNODE_1D nodal points along each element edge. Inherits from TElement and PMLTimeHarmonicLinearElasticityEquations
Definition at line 69 of file Tpml_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TPMLTimeHarmonicLinearElasticityElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::TPMLTimeHarmonicLinearElasticityElement () [inline]
Constructor: Call constructors for TElement and PMLTimeHarmonicLinearElasticity equations.
Definition at line 78 of file Tpml_time_harmonic_linear_elasticity_elements.h.
TPMLTimeHarmonicLinearElasticityElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::TPMLTimeHarmonicLinearElasticityElement (const TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 83 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 143 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_strain(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 132 of file Tpml_time_harmonic_linear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 135 of file Tpml_time_harmonic_linear_elasticity_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 121 of file Tpml_time_harmonic_linear_elasticity_elements.h.
operator=()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::operator= (const TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 89 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function:
Reimplemented from oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >.
Definition at line 95 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function:
Reimplemented from oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >.
Definition at line 101 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function:
Reimplemented from oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >.
Definition at line 108 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function:
Reimplemented from oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >.
Definition at line 114 of file Tpml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::output().
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
Node* oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 125 of file Tpml_time_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following file:
Tpml_time_harmonic_linear_elasticity_elements.h