oomph::AlgebraicElementBase Class Reference
#include <algebraic_elements.h>
Public Member Functions
AlgebraicElementBase ()
Empty constructor.
AlgebraicElementBase (const AlgebraicElementBase &)
Broken copy constructor.
void operator= (const AlgebraicElementBase &)
Broken assignment operator.
void setup_algebraic_node_update (Node *&node_pt, const Vector< double > &s_father, FiniteElement *father_el_pt) const
Set up node update info for (newly created) algebraic node: I.e. work out its node update information by interpolation from the father element. Pass pointer to father element and the newly created node's local coordinate in the father element.
Detailed Description
Base class for algebraic elements.
Definition at line 520 of file algebraic_elements.h.
Constructor & Destructor Documentation
AlgebraicElementBase() [1/2]
oomph::AlgebraicElementBase::AlgebraicElementBase () [inline]
Empty constructor.
Definition at line 526 of file algebraic_elements.h.
AlgebraicElementBase() [2/2]
oomph::AlgebraicElementBase::AlgebraicElementBase (const AlgebraicElementBase &) [inline]
Broken copy constructor.
Definition at line 529 of file algebraic_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
void oomph::AlgebraicElementBase::operator= (const AlgebraicElementBase &) [inline]
Broken assignment operator.
Definition at line 535 of file algebraic_elements.h.
References oomph::BrokenCopy::broken_assign().
setup_algebraic_node_update()
void oomph::AlgebraicElementBase::setup_algebraic_node_update (Node *& node_pt, const Vector< double > & s_father, FiniteElement * father_el_pt) const
Set up node update info for (newly created) algebraic node: I.e. work out its node update information by interpolation from the father element. Pass pointer to father element and the newly created node's local coordinate in the father element.
Set up node update info for (newly created) algebraic node: Work out its node update information by interpolation from its father element, based on pointer to father element and its local coordinate in the father element. We're creating the node update info for update functions that are shared by all nodes in the father element. Now loop over the ids and check if they appear in all nodes
Definition at line 54 of file algebraic_elements.cc.
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::Dummy_geom_object_pt, oomph::AlgebraicNode::Dummy_mesh, oomph::AlgebraicNode::Dummy_mesh_pt, oomph::AlgebraicNode::Dummy_node_update_fct_id, oomph::AlgebraicNode::Dummy_ref_value, i, oomph::AlgebraicNode::Max_allowed_difference_between_node_update_fcts, oomph::AlgebraicNode::mesh_pt(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::AlgebraicNode::node_update(), oomph::AlgebraicNode::nref_value(), oomph::FiniteElement::shape(), and oomph::AlgebraicMesh::update_node_update().
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), and oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine().
The documentation for this class was generated from the following files:
algebraic_elements.h
algebraic_elements.cc