oomph::QLinearWaveElement< DIM, NNODE_1D > Class Template Reference
#include <linear_wave_elements.h>
Public Member Functions
QLinearWaveElement ()
Constructor: Call constructors for QElement and LinearWave equations.
QLinearWaveElement (const QLinearWaveElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const QLinearWaveElement< DIM, NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
Output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_lin_wave (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_lin_wave (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Private Member Functions
template<>
const unsigned Initial_Nvalue [4]
2D LinearWave elements
template<>
const unsigned Initial_Nvalue [3]
template<>
const unsigned Initial_Nvalue [2]
template<>
const unsigned Initial_Nvalue [16]
template<>
const unsigned Initial_Nvalue [9]
template<>
const unsigned Initial_Nvalue [4]
template<>
const unsigned Initial_Nvalue [8]
template<>
const unsigned Initial_Nvalue [27]
template<>
const unsigned Initial_Nvalue [64]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QLinearWaveElement< DIM, NNODE_1D >
QLinearWaveElement elements are linear/quadrilateral/brick-shaped LinearWave elements with isoparametric interpolation for the function.
Empty, just establishes the template parameters
Definition at line 405 of file linear_wave_elements.h.
Constructor & Destructor Documentation
QLinearWaveElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QLinearWaveElement< DIM, NNODE_1D >::QLinearWaveElement () [inline]
Constructor: Call constructors for QElement and LinearWave equations.
Definition at line 420 of file linear_wave_elements.h.
QLinearWaveElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QLinearWaveElement< DIM, NNODE_1D >::QLinearWaveElement (const QLinearWaveElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 424 of file linear_wave_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_lin_wave()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QLinearWaveElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_lin_wave (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::LinearWaveEquations< DIM >.
Definition at line 545 of file linear_wave_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QLinearWaveElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_lin_wave().
dshape_and_dtest_eulerian_lin_wave()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QLinearWaveElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_lin_wave (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::LinearWaveEquations< DIM >.
Definition at line 513 of file linear_wave_elements.h.
References oomph::QLinearWaveElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_lin_wave(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct().
Initial_Nvalue() [1/9]
template<>
const unsigned oomph::QLinearWaveElement< 1, 4 >::Initial_Nvalue () [private]
2D LinearWave elements
Definition at line 47 of file linear_wave_elements.cc.
Initial_Nvalue() [2/9]
template<>
const unsigned oomph::QLinearWaveElement< 1, 3 >::Initial_Nvalue () [private]
Definition at line 49 of file linear_wave_elements.cc.
Initial_Nvalue() [3/9]
template<>
const unsigned oomph::QLinearWaveElement< 1, 2 >::Initial_Nvalue () [private]
Definition at line 51 of file linear_wave_elements.cc.
Initial_Nvalue() [4/9]
template<>
const unsigned oomph::QLinearWaveElement< 2, 4 >::Initial_Nvalue () [private]
Definition at line 55 of file linear_wave_elements.cc.
Initial_Nvalue() [5/9]
template<>
const unsigned oomph::QLinearWaveElement< 2, 3 >::Initial_Nvalue () [private]
Definition at line 59 of file linear_wave_elements.cc.
Initial_Nvalue() [6/9]
template<>
const unsigned oomph::QLinearWaveElement< 2, 2 >::Initial_Nvalue () [private]
Definition at line 62 of file linear_wave_elements.cc.
Initial_Nvalue() [7/9]
template<>
const unsigned oomph::QLinearWaveElement< 3, 2 >::Initial_Nvalue () [private]
Definition at line 66 of file linear_wave_elements.cc.
Initial_Nvalue() [8/9]
template<>
const unsigned oomph::QLinearWaveElement< 3, 3 >::Initial_Nvalue () [private]
Definition at line 69 of file linear_wave_elements.cc.
Initial_Nvalue() [9/9]
template<>
const unsigned oomph::QLinearWaveElement< 3, 4 >::Initial_Nvalue () [private]
Definition at line 74 of file linear_wave_elements.cc.
References oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave().
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::operator= (const QLinearWaveElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 431 of file linear_wave_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 443 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 448 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 453 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 458 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 464 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 474 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_at_knot_lin_wave(), oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_lin_wave(), oomph::QLinearWaveElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_lin_wave(), oomph::LinearWaveEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QLinearWaveElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 438 of file linear_wave_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QLinearWaveElement< DIM, NNODE_1D >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 413 of file linear_wave_elements.h.
The documentation for this class was generated from the following file:
linear_wave_elements.h