oomph::QSphericalTaylorHoodElement Class Reference
#include <spherical_navier_stokes_elements.h>
Public Member Functions
QSphericalTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
int p_nodal_index_spherical_nst () const
Set the value at which the pressure is stored in the nodes In this case the third index because there are three velocity components.
double p_spherical_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_spherical_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to SphericalNavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to SphericalNavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to SphericalNavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to SphericalNavierStokesEquations output.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `Dof type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
double dshape_and_dtest_eulerian_spherical_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_spherical_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
void pshape_spherical_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_spherical_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
Static Protected Attributes
static const unsigned Pconv [] ={0,2,6,8}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 980 of file spherical_navier_stokes_elements.h.
Constructor & Destructor Documentation
QSphericalTaylorHoodElement()
oomph::QSphericalTaylorHoodElement::QSphericalTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 1025 of file spherical_navier_stokes_elements.h.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_spherical_nst()
double oomph::QSphericalTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_spherical_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1145 of file spherical_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and pshape_spherical_nst().
Referenced by dshape_and_dtest_eulerian_spherical_nst().
dshape_and_dtest_eulerian_spherical_nst()
double oomph::QSphericalTaylorHoodElement::dshape_and_dtest_eulerian_spherical_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
2D : Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1118 of file spherical_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_at_knot_spherical_nst(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by ndof_types().
fix_pressure()
void oomph::QSphericalTaylorHoodElement::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1046 of file spherical_navier_stokes_elements.h.
References oomph::FSIFluidElement::identify_load_data(), oomph::FSIFluidElement::identify_pressure_data(), oomph::FiniteElement::node_pt(), oomph::SphericalNavierStokesEquations::p_nodal_index_spherical_nst(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::QSphericalTaylorHoodElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `Dof type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 2540 of file spherical_navier_stokes_elements.cc.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
identify_load_data()
void oomph::QSphericalTaylorHoodElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2483 of file spherical_navier_stokes_elements.cc.
References i, oomph::FSIFluidElement::identify_pressure_data(), identify_pressure_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::SphericalNavierStokesEquations::u_index_spherical_nst().
Referenced by oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns().
identify_pressure_data()
void oomph::QSphericalTaylorHoodElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2515 of file spherical_navier_stokes_elements.cc.
References oomph::FiniteElement::node_pt(), oomph::SphericalNavierStokesEquations::npres_spherical_nst(), and oomph::SphericalNavierStokesEquations::p_nodal_index_spherical_nst().
Referenced by identify_load_data().
ndof_types()
unsigned oomph::QSphericalTaylorHoodElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1092 of file spherical_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_spherical_nst(), and oomph::GeneralisedElement::get_dof_numbers_for_unknowns().
npres_spherical_nst()
unsigned oomph::QSphericalTaylorHoodElement::npres_spherical_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1043 of file spherical_navier_stokes_elements.h.
output() [1/4]
void oomph::QSphericalTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 1075 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [2/4]
void oomph::QSphericalTaylorHoodElement::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 1079 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [3/4]
void oomph::QSphericalTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 1083 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [4/4]
void oomph::QSphericalTaylorHoodElement::output (FILE * file_pt, const unsigned & nplot) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 1086 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
p_local_eqn()
int oomph::QSphericalTaylorHoodElement::p_local_eqn (const unsigned & n) const [inline], [protected], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1019 of file spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), and oomph::SphericalNavierStokesEquations::p_nodal_index_spherical_nst().
p_nodal_index_spherical_nst()
int oomph::QSphericalTaylorHoodElement::p_nodal_index_spherical_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes In this case the third index because there are three velocity components.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 1035 of file spherical_navier_stokes_elements.h.
p_spherical_nst()
double oomph::QSphericalTaylorHoodElement::p_spherical_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1039 of file spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value(), and oomph::SphericalNavierStokesEquations::p_nodal_index_spherical_nst().
pshape_spherical_nst() [1/2]
void oomph::QSphericalTaylorHoodElement::pshape_spherical_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1167 of file spherical_navier_stokes_elements.h.
References i, and oomph::OneDimLagrange::shape< 2 >().
Referenced by dshape_and_dtest_eulerian_at_knot_spherical_nst().
pshape_spherical_nst() [2/2]
void oomph::QSphericalTaylorHoodElement::pshape_spherical_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 1192 of file spherical_navier_stokes_elements.h.
References i, and oomph::SphericalNavierStokesEquations::pshape_spherical_nst().
required_nvalue()
virtual unsigned oomph::QSphericalTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableQSphericalTaylorHoodElement.
Definition at line 1030 of file spherical_navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::QSphericalTaylorHoodElement::Initial_Nvalue [static], [private]
Initial value:
=
{4,3,4,3,3,3,4,3,4}
Static array of ints to hold number of variables at node.
Definition at line 986 of file spherical_navier_stokes_elements.h.
Referenced by oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns().
Pconv
const unsigned oomph::QSphericalTaylorHoodElement::Pconv ={0,2,6,8} [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 992 of file spherical_navier_stokes_elements.h.
Referenced by oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns().
The documentation for this class was generated from the following files:
spherical_navier_stokes_elements.h
spherical_navier_stokes_elements.cc