oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT > Class Template Reference
#include <refineable_pml_helmholtz_elements.h>
Public Member Functions
RefineablePMLHelmholtzEquations ()
Constructor, simply call other constructors.
RefineablePMLHelmholtzEquations (const RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT > &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Complex flux from PMLHelmholtz equations, strung together.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM, class PML_ELEMENT>
class oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >
Refineable version of PMLHelmholtz equations
Definition at line 62 of file refineable_pml_helmholtz_elements.h.
Constructor & Destructor Documentation
RefineablePMLHelmholtzEquations() [1/2]
template<unsigned DIM, class PML_ELEMENT>
oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::RefineablePMLHelmholtzEquations () [inline]
Constructor, simply call other constructors.
Definition at line 70 of file refineable_pml_helmholtz_elements.h.
RefineablePMLHelmholtzEquations() [2/2]
template<unsigned DIM, class PML_ELEMENT>
oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::RefineablePMLHelmholtzEquations (const RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file refineable_pml_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_helmholtz()
template<unsigned DIM, class PML_ELEMENT >
void oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::fill_in_generic_residual_contribution_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented from oomph::PMLHelmholtzEquations< DIM, PML_ELEMENT >.
Definition at line 48 of file refineable_pml_helmholtz_elements.cc.
References i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::further_build().
further_build()
template<unsigned DIM, class PML_ELEMENT>
void oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 171 of file refineable_pml_helmholtz_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLHelmholtzEquationsBase< DIM >::source_fct_pt(), and oomph::PMLHelmholtzEquationsBase< DIM >::Source_fct_pt.
get_interpolated_values() [1/2]
template<unsigned DIM, class PML_ELEMENT>
void oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 114 of file refineable_pml_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz().
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_interpolated_values().
get_interpolated_values() [2/2]
template<unsigned DIM, class PML_ELEMENT>
void oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 148 of file refineable_pml_helmholtz_elements.h.
References oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_interpolated_values(), and oomph::Global_string_for_annotation::string().
get_Z2_flux()
template<unsigned DIM, class PML_ELEMENT>
void oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Complex flux from PMLHelmholtz equations, strung together.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 95 of file refineable_pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::get_flux(), and i.
num_Z2_flux_terms()
template<unsigned DIM, class PML_ELEMENT>
unsigned oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 91 of file refineable_pml_helmholtz_elements.h.
The documentation for this class was generated from the following files:
refineable_pml_helmholtz_elements.h
refineable_pml_helmholtz_elements.cc