oomph::BiharmonicFluxElement< DIM > Class Template Reference
Biharmonic Flux Element.
#include <biharmonic_flux_elements.h>
Public Types
typedef void(* FluxFctPt) (const double &s, double &flux)
Public Member Functions
BiharmonicFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index, const unsigned &b)
constructor
BiharmonicFluxElement ()
Broken empty constructor.
BiharmonicFluxElement (const BiharmonicFluxElement &dummy)
Broken copy constructor.
void operator= (const BiharmonicFluxElement &)
Broken assignment operator.
FluxFctPt & flux0_fct_pt ()
Access function for the flux0 function pointer.
FluxFctPt & flux1_fct_pt ()
Access function for the flux1 function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix (note - no contributions are made to the jacobian)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- does nothing.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- does nothing.
void output (FILE *file_pt)
C-style output function -- does nothing.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- does nothing.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
compute_error -- does nothing
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
template<>
BiharmonicFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index, const unsigned &b)
Private Member Functions
void get_flux0 (const double &s, double &flux)
Function to return the prescribed flux at a given macro element coordinate position.
void get_flux1 (const double &s, double &flux)
Function to return the prescribed flux at a given macro element coordinate position.
double J_eulerian (const Vector< double > &s) const
Calculate the Jacobian of the mapping between local and global coordinates at the position s for face elements.
void fill_in_generic_residual_contribution_biharmonic_flux (Vector< double > &residuals)
Add the element's contribution to its residual vector. Flux elements only make contribution to the residual vector.
template<>
double J_eulerian (const Vector< double > &s) const
Calculate the Jacobian of the mapping between local and global coordinates at the position s for face elements for two dimensional problems The jacobian of the 1D face element is computed which is dt/ds_t.
template<>
void fill_in_generic_residual_contribution_biharmonic_flux (Vector< double > &residual)
Compute the elemental contribution to the residual vector for 2D problem type 0 biharmonic flux elements.
Private Attributes
FluxFctPt Flux0_fct_pt
Function pointer to the prescribed flux.
FluxFctPt Flux1_fct_pt
Function pointer to the prescribed flux.
unsigned Nface_nodal_dof
the number of nodal degrees of freedom for the face element basis functions
unsigned Boundary
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::BiharmonicFluxElement< DIM >
Biharmonic Flux Element.
Definition at line 93 of file biharmonic_flux_elements.h.
Member Typedef Documentation
FluxFctPt
template<unsigned DIM>
typedef void(* oomph::BiharmonicFluxElement< DIM >::FluxFctPt) (const double &s, double &flux)
definition of flux function pointer, flux must be parametised in terms of the macro element coordinate position (s) along the problem edge
Definition at line 102 of file biharmonic_flux_elements.h.
Constructor & Destructor Documentation
BiharmonicFluxElement() [1/4]
template<unsigned DIM>
oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index, const unsigned & b)
constructor
BiharmonicFluxElement() [2/4]
template<unsigned DIM>
oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement () [inline]
Broken empty constructor.
Definition at line 111 of file biharmonic_flux_elements.h.
BiharmonicFluxElement() [3/4]
template<unsigned DIM>
oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement (const BiharmonicFluxElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 121 of file biharmonic_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
BiharmonicFluxElement() [4/4]
template<>
oomph::BiharmonicFluxElement< 2 >::BiharmonicFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index, const unsigned & b)
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element. And the macro element position of the flux element along the edge of the problem
Definition at line 51 of file biharmonic_flux_elements.cc.
References oomph::BiharmonicFluxElement< DIM >::Boundary, oomph::FiniteElement::build_face_element(), oomph::BiharmonicFluxElement< DIM >::Flux0_fct_pt, oomph::BiharmonicFluxElement< DIM >::Flux1_fct_pt, and oomph::BiharmonicFluxElement< DIM >::Nface_nodal_dof.
Member Function Documentation
compute_error()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [inline], [virtual]
compute_error -- does nothing
Reimplemented from oomph::FiniteElement.
Definition at line 184 of file biharmonic_flux_elements.h.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix (note - no contributions are made to the jacobian)
Reimplemented from oomph::GeneralisedElement.
Definition at line 149 of file biharmonic_flux_elements.h.
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 140 of file biharmonic_flux_elements.h.
fill_in_generic_residual_contribution_biharmonic_flux() [1/2]
template<>
void oomph::BiharmonicFluxElement< 2 >::fill_in_generic_residual_contribution_biharmonic_flux (Vector< double > & residual) [private]
Compute the elemental contribution to the residual vector for 2D problem type 0 biharmonic flux elements.
Definition at line 132 of file biharmonic_flux_elements.cc.
References oomph::BiharmonicFluxElement< DIM >::Boundary, oomph::FaceElement::bulk_position_type(), oomph::FiniteElement::dshape_local(), oomph::FaceElement::face_index(), oomph::Node::get_coordinates_on_boundary(), oomph::BiharmonicFluxElement< DIM >::get_flux0(), oomph::BiharmonicFluxElement< DIM >::get_flux1(), oomph::FiniteElement::integral_pt(), oomph::BiharmonicFluxElement< DIM >::J_eulerian(), oomph::Integral::knot(), oomph::BiharmonicFluxElement< DIM >::Nface_nodal_dof, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::Node::x_gen().
fill_in_generic_residual_contribution_biharmonic_flux() [2/2]
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux (Vector< double > & residuals) [private]
Add the element's contribution to its residual vector. Flux elements only make contribution to the residual vector.
Referenced by oomph::BiharmonicFluxElement< DIM >::J_eulerian().
flux0_fct_pt()
template<unsigned DIM>
FluxFctPt& oomph::BiharmonicFluxElement< DIM >::flux0_fct_pt () [inline]
Access function for the flux0 function pointer.
Definition at line 134 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition().
flux1_fct_pt()
template<unsigned DIM>
FluxFctPt& oomph::BiharmonicFluxElement< DIM >::flux1_fct_pt () [inline]
Access function for the flux1 function pointer.
Definition at line 137 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition().
get_flux0()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::get_flux0 (const double & s, double & flux) [inline], [private]
Function to return the prescribed flux at a given macro element coordinate position.
Definition at line 197 of file biharmonic_flux_elements.h.
References s.
Referenced by oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux().
get_flux1()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::get_flux1 (const double & s, double & flux) [inline], [private]
Function to return the prescribed flux at a given macro element coordinate position.
Definition at line 213 of file biharmonic_flux_elements.h.
References s.
Referenced by oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux().
J_eulerian() [1/2]
template<>
double oomph::BiharmonicFluxElement< 2 >::J_eulerian (const Vector< double > & s) const [private], [virtual]
Calculate the Jacobian of the mapping between local and global coordinates at the position s for face elements for two dimensional problems The jacobian of the 1D face element is computed which is dt/ds_t.
Reimplemented from oomph::FaceElement.
Definition at line 81 of file biharmonic_flux_elements.cc.
References oomph::FaceElement::bulk_position_type(), oomph::FiniteElement::dshape_local(), oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux(), oomph::BiharmonicFluxElement< DIM >::Nface_nodal_dof, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Node::x_gen().
J_eulerian() [2/2]
template<unsigned DIM>
double oomph::BiharmonicFluxElement< DIM >::J_eulerian (const Vector< double > & s) const [private], [virtual]
Calculate the Jacobian of the mapping between local and global coordinates at the position s for face elements.
Reimplemented from oomph::FiniteElement.
Referenced by oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux().
operator=()
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::operator= (const BiharmonicFluxElement< DIM > &) [inline]
Broken assignment operator.
Definition at line 128 of file biharmonic_flux_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 168 of file biharmonic_flux_elements.h.
output() [2/4]
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 172 of file biharmonic_flux_elements.h.
output() [3/4]
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 176 of file biharmonic_flux_elements.h.
output() [4/4]
template<unsigned DIM>
void oomph::BiharmonicFluxElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 180 of file biharmonic_flux_elements.h.
output_fct()
template<unsigned DIM>
virtual void oomph::BiharmonicFluxElement< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output an exact solution over the element.
Reimplemented from oomph::FiniteElement.
Definition at line 189 of file biharmonic_flux_elements.h.
zeta_nodal()
template<unsigned DIM>
double oomph::BiharmonicFluxElement< DIM >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 162 of file biharmonic_flux_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Boundary
template<unsigned DIM>
unsigned oomph::BiharmonicFluxElement< DIM >::Boundary [private]
Definition at line 247 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), and oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux().
Flux0_fct_pt
template<unsigned DIM>
FluxFctPt oomph::BiharmonicFluxElement< DIM >::Flux0_fct_pt [private]
Function pointer to the prescribed flux.
Definition at line 237 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement().
Flux1_fct_pt
template<unsigned DIM>
FluxFctPt oomph::BiharmonicFluxElement< DIM >::Flux1_fct_pt [private]
Function pointer to the prescribed flux.
Definition at line 240 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement().
Nface_nodal_dof
template<unsigned DIM>
unsigned oomph::BiharmonicFluxElement< DIM >::Nface_nodal_dof [private]
the number of nodal degrees of freedom for the face element basis functions
Definition at line 244 of file biharmonic_flux_elements.h.
Referenced by oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux(), and oomph::BiharmonicFluxElement< DIM >::J_eulerian().
The documentation for this class was generated from the following file:
biharmonic_flux_elements.h