oomph::ContinuationStorageScheme Class Reference
GeneralisedTimestepper used to store the arclength derivatives and pervious solutions required in continuation problems. The data is stored as auxilliary data in the (fake) TimeStepper so that spatial adaptivity will be handled automatically through our standard mechanisms. The adopted storage scheme is that the continuation derivatives will be stored at the first auxilliary value and the previous value will be the second auixilliary value.
#include <generalised_timesteppers.h>
Public Member Functions
ContinuationStorageScheme ()
ContinuationStorageScheme (const ContinuationStorageScheme &)
Broken copy constructor.
void modify_storage (GeneralisedTimeStepper *const &time_stepper_pt)
Modify the scheme based on the underlying timestepper.
void operator= (const ContinuationStorageScheme &)
Broken assignment operator.
unsigned order () const
void undo_make_steady ()
This is a steady scheme, so you can't do this.
void assign_initial_values_impulsive (Data *const &data_pt)
Broken initialisation the time-history for the Data values corresponding to an impulsive start.
void assign_initial_positions_impulsive (Node *const &node_pt)
Broken initialisation of the positions for the node corresponding to an impulsive start.
void shift_time_values (Data *const &data_pt)
Broken shifting of time values.
void shift_time_positions (Node *const &node_pt)
Broken shifting of time positions.
void set_weights ()
Set the weights (Do nothing)
unsigned nprev_values () const
Number of previous values available.
unsigned ndt () const
Number of timestep increments that need to be stored by the scheme.
void set_consistent_pinned_values (Data *const &data_pt)
Set consistent values of the derivatives and current value when the data is pinned. This must be done by the `timestepper` because only it knows the local storage scheme.
void set_consistent_pinned_positions (Node *const &node_pt)
Set consistent values of the derivatives and current value when the Nodes position is pinned. This must be done by the `timestepper` because only it knows the local storage scheme.
unsigned dof_derivative_offset ()
unsigned dof_current_offset ()
Private Attributes
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Additional Inherited Members
Detailed Description
GeneralisedTimestepper used to store the arclength derivatives and pervious solutions required in continuation problems. The data is stored as auxilliary data in the (fake) TimeStepper so that spatial adaptivity will be handled automatically through our standard mechanisms. The adopted storage scheme is that the continuation derivatives will be stored at the first auxilliary value and the previous value will be the second auixilliary value.
Definition at line 110 of file generalised_timesteppers.h.
Constructor & Destructor Documentation
ContinuationStorageScheme() [1/2]
oomph::ContinuationStorageScheme::ContinuationStorageScheme () [inline]
Constructor for the case when we allow adaptive continuation It can evaulate up to second derivatives, but doesn't do anything the time-derivatives evaluate to zero.
Definition at line 123 of file generalised_timesteppers.h.
References oomph::TimeStepper::Is_steady, and oomph::TimeStepper::Type.
ContinuationStorageScheme() [2/2]
oomph::ContinuationStorageScheme::ContinuationStorageScheme (const ContinuationStorageScheme &) [inline]
Broken copy constructor.
Definition at line 132 of file generalised_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
assign_initial_positions_impulsive()
void oomph::ContinuationStorageScheme::assign_initial_positions_impulsive (Node *const & node_pt) [inline], [virtual]
Broken initialisation of the positions for the node corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 186 of file generalised_timesteppers.h.
assign_initial_values_impulsive()
void oomph::ContinuationStorageScheme::assign_initial_values_impulsive (Data *const & data_pt) [inline], [virtual]
Broken initialisation the time-history for the Data values corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 176 of file generalised_timesteppers.h.
dof_current_offset()
unsigned oomph::ContinuationStorageScheme::dof_current_offset () [inline]
Definition at line 325 of file generalised_timesteppers.h.
dof_derivative_offset()
unsigned oomph::ContinuationStorageScheme::dof_derivative_offset () [inline]
Definition at line 322 of file generalised_timesteppers.h.
modify_storage()
void oomph::ContinuationStorageScheme::modify_storage (GeneralisedTimeStepper *const & time_stepper_pt) [inline]
Modify the scheme based on the underlying timestepper.
Definition at line 138 of file generalised_timesteppers.h.
References oomph::GeneralisedTimeStepper::Ndof_storage_entries, oomph::GeneralisedTimeStepper::ndof_storage_entries(), oomph::TimeStepper::ntstorage(), oomph::DenseMatrix< T >::resize(), and oomph::TimeStepper::Weight.
ndt()
unsigned oomph::ContinuationStorageScheme::ndt () const [inline], [virtual]
Number of timestep increments that need to be stored by the scheme.
Implements oomph::TimeStepper.
Definition at line 219 of file generalised_timesteppers.h.
nprev_values()
unsigned oomph::ContinuationStorageScheme::nprev_values () const [inline], [virtual]
Number of previous values available.
Implements oomph::TimeStepper.
Definition at line 216 of file generalised_timesteppers.h.
operator=()
void oomph::ContinuationStorageScheme::operator= (const ContinuationStorageScheme &) [inline]
Broken assignment operator.
Definition at line 162 of file generalised_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
order()
unsigned oomph::ContinuationStorageScheme::order () const [inline], [virtual]
Return the actual order of the scheme. It's a steady scheme so it's zero, but that doesn't really make sense.
Reimplemented from oomph::TimeStepper.
Definition at line 169 of file generalised_timesteppers.h.
set_consistent_pinned_positions()
void oomph::ContinuationStorageScheme::set_consistent_pinned_positions (Node *const & node_pt) [inline]
Set consistent values of the derivatives and current value when the Nodes position is pinned. This must be done by the `timestepper` because only it knows the local storage scheme.
Definition at line 266 of file generalised_timesteppers.h.
References i, oomph::GeneralisedTimeStepper::Ndof_storage_entries, oomph::Node::position_time_stepper_pt(), and t.
Referenced by oomph::Mesh::set_consistent_pinned_values_for_continuation().
set_consistent_pinned_values()
void oomph::ContinuationStorageScheme::set_consistent_pinned_values (Data *const & data_pt) [inline]
Set consistent values of the derivatives and current value when the data is pinned. This must be done by the `timestepper` because only it knows the local storage scheme.
Definition at line 224 of file generalised_timesteppers.h.
References i, oomph::Data::is_a_copy(), oomph::Data::is_pinned(), oomph::GeneralisedTimeStepper::Ndof_storage_entries, oomph::Data::nvalue(), oomph::Data::set_value(), t, oomph::Data::time_stepper_pt(), and oomph::Data::value().
Referenced by oomph::SpineMesh::set_consistent_pinned_spine_values_for_continuation(), oomph::Mesh::set_consistent_pinned_values_for_continuation(), and oomph::Problem::set_consistent_pinned_values_for_continuation().
set_weights()
void oomph::ContinuationStorageScheme::set_weights () [inline], [virtual]
Set the weights (Do nothing)
Implements oomph::TimeStepper.
Definition at line 213 of file generalised_timesteppers.h.
shift_time_positions()
void oomph::ContinuationStorageScheme::shift_time_positions (Node *const & node_pt) [inline], [virtual]
Broken shifting of time positions.
Implements oomph::TimeStepper.
Definition at line 204 of file generalised_timesteppers.h.
shift_time_values()
void oomph::ContinuationStorageScheme::shift_time_values (Data *const & data_pt) [inline], [virtual]
Broken shifting of time values.
Implements oomph::TimeStepper.
Definition at line 195 of file generalised_timesteppers.h.
undo_make_steady()
void oomph::ContinuationStorageScheme::undo_make_steady () [inline], [virtual]
This is a steady scheme, so you can't do this.
Reimplemented from oomph::TimeStepper.
Definition at line 172 of file generalised_timesteppers.h.
References oomph::TimeStepper::Is_steady.
Member Data Documentation
Dof_current_offset
unsigned oomph::ContinuationStorageScheme::Dof_current_offset [private]
Definition at line 116 of file generalised_timesteppers.h.
Dof_derivative_offset
unsigned oomph::ContinuationStorageScheme::Dof_derivative_offset [private]
Definition at line 113 of file generalised_timesteppers.h.
The documentation for this class was generated from the following file:
generalised_timesteppers.h