RefineableBin Class Reference
#include <sample_point_container.h>
Public Member Functions
RefineableBin (RefineableBinArray *bin_array_pt, const unsigned &bin_index_in_bin_array)
Constructor. Pass pointer to bin array that contains this bin and the index of the newly created bin in that RefineableBinArray.
RefineableBin (const RefineableBin &data)
Broken copy constructor.
void operator= (const RefineableBin &)
Broken assignment operator.
~RefineableBin ()
Destructor.
unsigned total_number_of_sample_points_computed_recursively () const
Compute total number of sample points recursively.
void add_sample_point (SamplePoint *new_sample_point_pt, const Vector< double > &zeta_coordinates)
Add a new sample point to RefineableBin.
void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s)
Find sub-GeomObject (finite element) and the local coordinate s within it that contains point with global coordinate zeta. sub_geom_object_pt=0 if point can't be found.
void output (std::ofstream &outfile, const bool &don_t_recurse=false)
Output bin; x,[y,[z]],n_sample_points.
void output_bins (std::ofstream &outfile)
Output bin vertices (allowing display of bins as zones).
void output_bin_vertices (std::ofstream &outfile)
Output bin vertices (allowing display of bins as zones).
unsigned nsample_points_in_bin ()
Number of sample points stored in bin.
Protected Member Functions
void make_sub_bin_array (const Vector< std::pair< double, double > > &min_and_max_coordinates)
Method for building a new subbin_array (called when the Bin size is greater than the Max_number_of_sample_point_per_bin (and the Bin is recursive). Pass in the extremal coordinates of the bin which is being subdivided. Redistributes all existing sample points to newly made sub-bin-array and empties its own storage. Pass Max./min. coordinates of new bin array for efficiency.
void get_bin_boundaries (Vector< std::pair< double, double > > &min_and_max_coordinates)
Boundaries of bin in each coordinate direction. *.first = min; *.second = max.
Protected Attributes
Vector< SamplePoint * > * Sample_point_pt
Container of SamplePoints. Pointer to vector because it's shorter than an empty vector! (Not all RefineableBins have sample points -- the ones that are subdivided don't!)
RefineableBinArray * Sub_bin_array_pt
Pointer to a possible sub-BinArray. Null by default.
RefineableBinArray * Bin_array_pt
Pointer to the bin array which `owns` this RefineableBin.
unsigned Bin_index_in_bin_array
Index of bin in its bin array.
Detailed Description
RefineableBin class. Contains sample points and is embedded in a RefineableBinArray. May itself be represented by a RefineableBinArray to make it recursive.
Definition at line 113 of file sample_point_container.h.
Constructor & Destructor Documentation
RefineableBin() [1/2]
RefineableBin::RefineableBin (RefineableBinArray * bin_array_pt, const unsigned & bin_index_in_bin_array) [inline]
Constructor. Pass pointer to bin array that contains this bin and the index of the newly created bin in that RefineableBinArray.
Definition at line 120 of file sample_point_container.h.
RefineableBin() [2/2]
RefineableBin::RefineableBin (const RefineableBin & data) [inline]
Broken copy constructor.
Definition at line 130 of file sample_point_container.h.
References oomph::BrokenCopy::broken_copy().
 RefineableBin()
RefineableBin::~RefineableBin ()
Destructor.
Definition at line 48 of file sample_point_container.cc.
References i.
Member Function Documentation
add_sample_point()
void RefineableBin::add_sample_point (SamplePoint * new_sample_point_pt, const Vector< double > & zeta_coordinates)
Add a new sample point to RefineableBin.
Add a SamplePoint* to a RefineableBin object.
Definition at line 404 of file sample_point_container.cc.
get_bin_boundaries()
void RefineableBin::get_bin_boundaries (Vector< std::pair< double, double > > & min_and_max_coordinates) [protected]
Boundaries of bin in each coordinate direction. *.first = min; *.second = max.
Boundaries of bin in each coordinate direction. *.first = min; *.second = max.
Definition at line 611 of file sample_point_container.cc.
References SamplePointContainer::Always_fail_elemental_locate_zeta, SamplePointContainer::Enable_timing_of_setup, SamplePointContainer::Percentage_offset, SamplePointContainer::Use_equally_spaced_interior_sample_points, and SamplePointContainer::Visited_sample_points_file.
locate_zeta()
void RefineableBin::locate_zeta (const Vector< double > & zeta, GeomObject *& sub_geom_object_pt, Vector< double > & s)
Find sub-GeomObject (finite element) and the local coordinate s within it that contains point with global coordinate zeta. sub_geom_object_pt=0 if point can't be found.
Find sub-GeomObject (finite element) and the local coordinate s within it that contains point with global coordinate zeta. sub_geom_object_pt=0 if point can't be found.
Definition at line 449 of file sample_point_container.cc.
References SamplePointContainer::Always_fail_elemental_locate_zeta, i, s, SamplePointContainer::Use_equally_spaced_interior_sample_points, and SamplePointContainer::Visited_sample_points_file.
make_sub_bin_array()
void RefineableBin::make_sub_bin_array (const Vector< std::pair< double, double > > & min_and_max_coordinates) [protected]
Method for building a new subbin_array (called when the Bin size is greater than the Max_number_of_sample_point_per_bin (and the Bin is recursive). Pass in the extremal coordinates of the bin which is being subdivided. Redistributes all existing sample points to newly made sub-bin-array and empties its own storage. Pass Max./min. coordinates of new bin array for efficiency.
Function called for making a sub bin array in a given RefineableBin. Pass the vector of min and max coordinates of the NEW bin array.
Definition at line 97 of file sample_point_container.cc.
nsample_points_in_bin()
unsigned RefineableBin::nsample_points_in_bin () [inline]
Number of sample points stored in bin.
Definition at line 168 of file sample_point_container.h.
operator=()
void RefineableBin::operator= (const RefineableBin &) [inline]
Broken assignment operator.
Definition at line 136 of file sample_point_container.h.
References oomph::BrokenCopy::broken_assign(), oomph::output(), and s.
output()
void RefineableBin::output (std::ofstream & outfile, const bool & don_t_recurse = false)
Output bin; x,[y,[z]],n_sample_points.
Definition at line 187 of file sample_point_container.cc.
References oomph::oomph_info.
output_bin_vertices()
void RefineableBin::output_bin_vertices (std::ofstream & outfile)
Output bin vertices (allowing display of bins as zones).
Output bin; x,[y,[z]].
Definition at line 299 of file sample_point_container.cc.
References oomph::oomph_info.
output_bins()
void RefineableBin::output_bins (std::ofstream & outfile)
Output bin vertices (allowing display of bins as zones).
total_number_of_sample_points_computed_recursively()
unsigned RefineableBin::total_number_of_sample_points_computed_recursively () const
Compute total number of sample points recursively.
Definition at line 71 of file sample_point_container.cc.
Member Data Documentation
Bin_array_pt
RefineableBinArray* RefineableBin::Bin_array_pt [protected]
Pointer to the bin array which `owns` this RefineableBin.
Definition at line 191 of file sample_point_container.h.
Bin_index_in_bin_array
unsigned RefineableBin::Bin_index_in_bin_array [protected]
Index of bin in its bin array.
Definition at line 194 of file sample_point_container.h.
Sample_point_pt
Vector<SamplePoint*>* RefineableBin::Sample_point_pt [protected]
Container of SamplePoints. Pointer to vector because it's shorter than an empty vector! (Not all RefineableBins have sample points -- the ones that are subdivided don't!)
Definition at line 185 of file sample_point_container.h.
Sub_bin_array_pt
RefineableBinArray* RefineableBin::Sub_bin_array_pt [protected]
Pointer to a possible sub-BinArray. Null by default.
Definition at line 188 of file sample_point_container.h.
The documentation for this class was generated from the following files:
sample_point_container.h
sample_point_container.cc