oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT > Class Template Reference
Foeppl von Karman upgraded to become projectable.
#include <displacement_based_foeppl_von_karman_elements.h>
Public Member Functions
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just two.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of field fld of node j.
Additional Inherited Members
Detailed Description
template<class FVK_ELEMENT>
class oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >
Foeppl von Karman upgraded to become projectable.
Definition at line 768 of file displacement_based_foeppl_von_karman_elements.h.
Member Function Documentation
data_values_of_field()
template<class FVK_ELEMENT >
Vector<std::pair<Data*,unsigned> > oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 778 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class FVK_ELEMENT >
double oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 876 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::nnode(), oomph::DisplacementBasedFoepplvonKarmanEquations::nodal_index_fvk(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class FVK_ELEMENT >
double oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 846 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::dim(), oomph::DisplacementBasedFoepplvonKarmanEquations::dshape_and_dtest_eulerian_fvk(), and oomph::FiniteElement::nnode().
local_equation()
template<class FVK_ELEMENT >
int oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of field fld of node j.
Implements oomph::ProjectableElementBase.
Definition at line 939 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::nodal_index_fvk(), and oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class FVK_ELEMENT >
unsigned oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just two.
Implements oomph::ProjectableElementBase.
Definition at line 811 of file displacement_based_foeppl_von_karman_elements.h.
nhistory_values_for_coordinate_projection()
template<class FVK_ELEMENT >
unsigned oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 839 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class FVK_ELEMENT >
unsigned oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 818 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class FVK_ELEMENT >
unsigned oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 919 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
displacement_based_foeppl_von_karman_elements.h