oomph::LinearSolver Class Reference
#include <linear_solver.h>
Public Member Functions
LinearSolver ()
Empty constructor, initialise the member data.
LinearSolver (const LinearSolver &dummy)
Broken copy constructor.
void operator= (const LinearSolver &)
Broken assignment operator.
virtual ~LinearSolver ()
Empty virtual destructor.
void enable_doc_time ()
Enable documentation of solve times.
void disable_doc_time ()
Disable documentation of solve times.
bool is_doc_time_enabled () const
Is documentation of solve times enabled?
bool is_resolve_enabled () const
Boolean flag indicating if resolves are enabled.
virtual void enable_resolve ()
Enable resolve (i.e. store matrix and/or LU decomposition, say) Virtual so it can be overloaded to perform additional tasks.
virtual void disable_resolve ()
Disable resolve (i.e. store matrix and/or LU decomposition, say) This function simply resets an internal flag. It's virtual so it can be overloaded to perform additional tasks such as cleaning up memory that is only required for the resolve.
virtual void solve (Problem *const &problem_pt, DoubleVector &result)=0
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void resolve (const DoubleVector &rhs, DoubleVector &result)
Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
virtual void clean_up_memory ()
Empty virtual function that can be overloaded in specific linear solvers to clean up any memory that may have been allocated (e.g. when preparing for a re-solve).
virtual double jacobian_setup_time () const
returns the time taken to assemble the Jacobian matrix and residual vector (needs to be overloaded for each solver)
virtual double linear_solver_solution_time () const
return the time taken to solve the linear system (needs to be overloaded for each linear solver)
virtual void enable_computation_of_gradient ()
function to enable the computation of the gradient required for the globally convergent Newton method
void disable_computation_of_gradient ()
function to disable the computation of the gradient required for the globally convergent Newton method
void reset_gradient ()
function to reset the size of the gradient before each Newton solve
void get_gradient (DoubleVector &gradient)
function to access the gradient, provided it has been computed
Protected Attributes
bool Enable_resolve
Boolean that indicates whether the matrix (or its factors, in the case of direct solver) should be stored so that the resolve function can be used.
bool Doc_time
Boolean flag that indicates whether the time taken.
bool Compute_gradient
flag that indicates whether the gradient required for the globally convergent Newton method should be computed or not
bool Gradient_has_been_computed
flag that indicates whether the gradient was computed or not
DoubleVector Gradient_for_glob_conv_newton_solve
DoubleVector storing the gradient for the globally convergent Newton method.
Additional Inherited Members
Detailed Description
Base class for all linear solvers. This merely defines standard interfaces for linear solvers, so that different solvers can be used in a clean and transparent manner. Note that LinearSolvers are primarily used to solve the linear systems arising in oomph-lib's Newton iteration. Their primary solve function therefore takes a pointer to the associated problem, construct its Jacobian matrix and residual vector, and return the solution of the linear system formed by the Jacobian and the residual vector. We also provide broken virtual interfaces to a linear-algebra-type solve function in which the matrix and the rhs can be specified, but this are not guaranteed to implemented for all linear solvers (e.g. for frontal solvers).
Definition at line 73 of file linear_solver.h.
Constructor & Destructor Documentation
LinearSolver() [1/2]
oomph::LinearSolver::LinearSolver () [inline]
Empty constructor, initialise the member data.
Definition at line 100 of file linear_solver.h.
LinearSolver() [2/2]
oomph::LinearSolver::LinearSolver (const LinearSolver & dummy) [inline]
Broken copy constructor.
Definition at line 104 of file linear_solver.h.
References oomph::BrokenCopy::broken_copy().
 LinearSolver()
virtual oomph::LinearSolver::~LinearSolver () [inline], [virtual]
Empty virtual destructor.
Definition at line 116 of file linear_solver.h.
Member Function Documentation
clean_up_memory()
virtual void oomph::LinearSolver::clean_up_memory () [inline], [virtual]
Empty virtual function that can be overloaded in specific linear solvers to clean up any memory that may have been allocated (e.g. when preparing for a re-solve).
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::MGPreconditioner< DIM >, oomph::GS< MATRIX >, oomph::HypreSolver, oomph::SuperLUSolver, oomph::BiCGStab< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::CG< MATRIX >, oomph::DenseLU, oomph::ComplexDampedJacobi< MATRIX >, oomph::MumpsSolver, oomph::HSL_MA42, and oomph::MGSolver< DIM >.
Definition at line 183 of file linear_solver.h.
Referenced by oomph::CRDoubleMatrix::clear(), oomph::CG< MATRIX >::disable_resolve(), oomph::BiCGStab< MATRIX >::disable_resolve(), oomph::SuperLUSolver::disable_resolve(), oomph::GS< MATRIX >::disable_resolve(), oomph::GS< CRDoubleMatrix >::disable_resolve(), oomph::ComplexGMRES< MATRIX >::disable_resolve(), oomph::GMRES< MATRIX >::disable_resolve(), oomph::HelmholtzGMRESMG< MATRIX >::disable_resolve(), oomph::DenseLU::linear_solver_solution_time(), oomph::SuperLUSolver::linear_solver_solution_time(), oomph::SuperLUSolver::set_solver_type(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::SuperLUSolver::use_distributed_solve_in_superlu_dist(), oomph::SuperLUSolver::use_global_solve_in_superlu_dist(), oomph::BiCGStab< MATRIX >::~BiCGStab(), oomph::CG< MATRIX >::~CG(), oomph::ComplexDampedJacobi< MATRIX >::~ComplexDampedJacobi(), oomph::ComplexGMRES< MATRIX >::~ComplexGMRES(), oomph::DampedJacobi< MATRIX >::~DampedJacobi(), oomph::DenseLU::~DenseLU(), oomph::GMRES< MATRIX >::~GMRES(), oomph::GS< MATRIX >::~GS(), oomph::GS< CRDoubleMatrix >::~GS(), oomph::HelmholtzFGMRESMG< MATRIX >::~HelmholtzFGMRESMG(), oomph::HelmholtzGMRESMG< MATRIX >::~HelmholtzGMRESMG(), and oomph::SuperLUSolver::~SuperLUSolver().
disable_computation_of_gradient()
void oomph::LinearSolver::disable_computation_of_gradient () [inline]
function to disable the computation of the gradient required for the globally convergent Newton method
Definition at line 220 of file linear_solver.h.
disable_doc_time()
void oomph::LinearSolver::disable_doc_time () [inline]
Disable documentation of solve times.
Definition at line 122 of file linear_solver.h.
Referenced by oomph::ProblemBasedShiftInvertOperator::ProblemBasedShiftInvertOperator(), oomph::ARPACK::solve_eigenproblem(), and oomph::SuperLUPreconditioner::SuperLUPreconditioner().
disable_resolve()
virtual void oomph::LinearSolver::disable_resolve () [inline], [virtual]
Disable resolve (i.e. store matrix and/or LU decomposition, say) This function simply resets an internal flag. It's virtual so it can be overloaded to perform additional tasks such as cleaning up memory that is only required for the resolve.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::HypreSolver, oomph::SuperLUSolver, oomph::TrilinosAztecOOSolver, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::HSL_MA42, and oomph::MumpsSolver.
Definition at line 138 of file linear_solver.h.
References solve().
Referenced by oomph::Problem::calculate_continuation_derivatives(), oomph::MumpsSolver::disable_resolve(), oomph::HSL_MA42::disable_resolve(), oomph::CG< MATRIX >::disable_resolve(), oomph::BiCGStab< MATRIX >::disable_resolve(), oomph::SuperLUSolver::disable_resolve(), oomph::GS< MATRIX >::disable_resolve(), oomph::GS< CRDoubleMatrix >::disable_resolve(), oomph::ComplexGMRES< MATRIX >::disable_resolve(), oomph::GMRES< MATRIX >::disable_resolve(), oomph::HelmholtzGMRESMG< MATRIX >::disable_resolve(), oomph::FoldHandler::FoldHandler(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve_continuation(), and oomph::ARPACK::solve_eigenproblem().
enable_computation_of_gradient()
virtual void oomph::LinearSolver::enable_computation_of_gradient () [inline], [virtual]
function to enable the computation of the gradient required for the globally convergent Newton method
Reimplemented in oomph::SuperLUSolver.
Definition at line 209 of file linear_solver.h.
Referenced by oomph::Problem::newton_solve().
enable_doc_time()
void oomph::LinearSolver::enable_doc_time () [inline]
Enable documentation of solve times.
Definition at line 119 of file linear_solver.h.
enable_resolve()
virtual void oomph::LinearSolver::enable_resolve () [inline], [virtual]
Enable resolve (i.e. store matrix and/or LU decomposition, say) Virtual so it can be overloaded to perform additional tasks.
Definition at line 132 of file linear_solver.h.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), and oomph::ARPACK::solve_eigenproblem().
get_gradient()
void oomph::LinearSolver::get_gradient (DoubleVector & gradient) [inline]
function to access the gradient, provided it has been computed
Definition at line 233 of file linear_solver.h.
References Gradient_for_glob_conv_newton_solve.
Referenced by oomph::Problem::newton_solve().
is_doc_time_enabled()
bool oomph::LinearSolver::is_doc_time_enabled () const [inline]
Is documentation of solve times enabled?
Definition at line 125 of file linear_solver.h.
References Doc_time.
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
is_resolve_enabled()
bool oomph::LinearSolver::is_resolve_enabled () const [inline]
Boolean flag indicating if resolves are enabled.
Definition at line 128 of file linear_solver.h.
References Enable_resolve.
Referenced by oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::HopfHandler::HopfHandler(), and oomph::Problem::newton_solve_continuation().
jacobian_setup_time()
virtual double oomph::LinearSolver::jacobian_setup_time () const [inline], [virtual]
returns the time taken to assemble the Jacobian matrix and residual vector (needs to be overloaded for each solver)
Reimplemented in oomph::SuperLUSolver, oomph::DenseLU, and oomph::IterativeLinearSolver.
Definition at line 187 of file linear_solver.h.
linear_solver_solution_time()
virtual double oomph::LinearSolver::linear_solver_solution_time () const [inline], [virtual]
return the time taken to solve the linear system (needs to be overloaded for each linear solver)
Reimplemented in oomph::SuperLUSolver, oomph::DenseLU, and oomph::IterativeLinearSolver.
Definition at line 198 of file linear_solver.h.
operator=()
void oomph::LinearSolver::operator= (const LinearSolver &) [inline]
Broken assignment operator.
Definition at line 110 of file linear_solver.h.
References oomph::BrokenCopy::broken_assign().
reset_gradient()
void oomph::LinearSolver::reset_gradient () [inline]
function to reset the size of the gradient before each Newton solve
Definition at line 227 of file linear_solver.h.
References oomph::DoubleVector::clear().
Referenced by oomph::Problem::newton_solve().
resolve()
virtual void oomph::LinearSolver::resolve (const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::BlockHopfLinearSolver, oomph::GS< CRDoubleMatrix >, oomph::AugmentedBlockPitchForkLinearSolver, oomph::HypreSolver, oomph::GS< MATRIX >, oomph::BlockPitchForkLinearSolver, oomph::SuperLUSolver, oomph::BiCGStab< MATRIX >, oomph::AugmentedBlockFoldLinearSolver, oomph::TrilinosAztecOOSolver, oomph::CG< MATRIX >, oomph::HSL_MA42, and oomph::MumpsSolver.
Definition at line 172 of file linear_solver.h.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), oomph::SuperLUSolver::disable_resolve(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), and oomph::ARPACK::solve_eigenproblem().
solve() [1/3]
virtual void oomph::LinearSolver::solve (Problem *const & problem_pt, DoubleVector & result) [pure virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implemented in oomph::HelmholtzFGMRESMG< MATRIX >, oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::BlockHopfLinearSolver, oomph::ComplexGMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::AugmentedBlockPitchForkLinearSolver, oomph::HypreSolver, oomph::GS< MATRIX >, oomph::BlockPitchForkLinearSolver, oomph::SuperLUSolver, oomph::MGSolver< DIM >, oomph::ComplexDampedJacobi< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::AugmentedBlockFoldLinearSolver, oomph::FD_LU, oomph::CG< MATRIX >, oomph::DenseLU, oomph::HSL_MA42, and oomph::MumpsSolver.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), disable_resolve(), oomph::CG< MATRIX >::disable_resolve(), oomph::BiCGStab< MATRIX >::disable_resolve(), oomph::SuperLUSolver::disable_resolve(), oomph::GMRES< MATRIX >::disable_resolve(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), oomph::FD_LU::operator=(), oomph::GS< MATRIX >::resolve(), oomph::GS< CRDoubleMatrix >::resolve(), oomph::DampedJacobi< MATRIX >::resolve(), oomph::GMRES< MATRIX >::resolve(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::GS< CRDoubleMatrix >::smoother_setup(), oomph::GS< MATRIX >::smoother_solve(), oomph::DampedJacobi< MATRIX >::smoother_solve(), oomph::HSL_MA42::solve(), oomph::DoubleMatrixBase::solve(), oomph::FD_LU::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::ComplexGMRES< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::ARPACK::solve_eigenproblem(), and oomph::DenseLU::~DenseLU().
solve() [2/3]
virtual void oomph::LinearSolver::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::BlockHopfLinearSolver, oomph::GS< CRDoubleMatrix >, oomph::HypreSolver, oomph::AugmentedBlockPitchForkLinearSolver, oomph::GS< MATRIX >, oomph::BlockPitchForkLinearSolver, oomph::SuperLUSolver, oomph::BiCGStab< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::AugmentedBlockFoldLinearSolver, oomph::FD_LU, oomph::CG< MATRIX >, oomph::DenseLU, oomph::HSL_MA42, and oomph::MumpsSolver.
Definition at line 147 of file linear_solver.h.
solve() [3/3]
virtual void oomph::LinearSolver::solve (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::GMRES< MATRIX >, oomph::BlockHopfLinearSolver, oomph::ComplexGMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::AugmentedBlockPitchForkLinearSolver, oomph::GS< MATRIX >, oomph::BlockPitchForkLinearSolver, oomph::BiCGStab< MATRIX >, oomph::AugmentedBlockFoldLinearSolver, oomph::FD_LU, oomph::DenseLU, and oomph::HSL_MA42.
Definition at line 159 of file linear_solver.h.
Member Data Documentation
Compute_gradient
bool oomph::LinearSolver::Compute_gradient [protected]
flag that indicates whether the gradient required for the globally convergent Newton method should be computed or not
Definition at line 88 of file linear_solver.h.
Referenced by oomph::SuperLUSolver::enable_computation_of_gradient(), and oomph::SuperLUSolver::solve().
Doc_time
bool oomph::LinearSolver::Doc_time [protected]
Boolean flag that indicates whether the time taken.
Definition at line 84 of file linear_solver.h.
Referenced by oomph::MumpsSolver::backsub(), oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), oomph::DenseLU::DenseLU(), oomph::MumpsSolver::factorise(), is_doc_time_enabled(), oomph::MumpsSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::SuperLUSolver::resolve(), oomph::MumpsSolver::solve(), oomph::DenseLU::solve(), oomph::FD_LU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::SuperLUSolver::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::TrilinosAztecOOSolver::solve_using_AztecOO(), and oomph::TrilinosAztecOOSolver::solver_setup().
Enable_resolve
bool oomph::LinearSolver::Enable_resolve [protected]
Boolean that indicates whether the matrix (or its factors, in the case of direct solver) should be stored so that the resolve function can be used.
Definition at line 80 of file linear_solver.h.
Referenced by is_resolve_enabled(), oomph::MumpsSolver::solve(), oomph::HSL_MA42::solve(), oomph::DenseLU::solve(), oomph::CG< MATRIX >::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::SuperLUSolver::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), and oomph::HSL_MA42::solve_for_one_dof().
Gradient_for_glob_conv_newton_solve
DoubleVector oomph::LinearSolver::Gradient_for_glob_conv_newton_solve [protected]
DoubleVector storing the gradient for the globally convergent Newton method.
Definition at line 95 of file linear_solver.h.
Referenced by get_gradient(), and oomph::SuperLUSolver::solve().
Gradient_has_been_computed
bool oomph::LinearSolver::Gradient_has_been_computed [protected]
flag that indicates whether the gradient was computed or not
Definition at line 91 of file linear_solver.h.
Referenced by oomph::SuperLUSolver::solve().
The documentation for this class was generated from the following file:
linear_solver.h