oomph::FpPressureAdvDiffRobinBCElementBase Class Reference
#include <navier_stokes_elements.h>
Public Member Functions
FpPressureAdvDiffRobinBCElementBase ()
Constructor.
virtual ~FpPressureAdvDiffRobinBCElementBase ()
Empty virtual destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)=0
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Additional Inherited Members
Detailed Description
Helper class for elements that impose Robin boundary conditions on pressure advection diffusion problem required by Fp preconditioner (class used to get around some templating issues)
Definition at line 55 of file navier_stokes_elements.h.
Constructor & Destructor Documentation
FpPressureAdvDiffRobinBCElementBase()
oomph::FpPressureAdvDiffRobinBCElementBase::FpPressureAdvDiffRobinBCElementBase () [inline]
Constructor.
Definition at line 60 of file navier_stokes_elements.h.
 FpPressureAdvDiffRobinBCElementBase()
virtual oomph::FpPressureAdvDiffRobinBCElementBase::~FpPressureAdvDiffRobinBCElementBase () [inline], [virtual]
Empty virtual destructor.
Definition at line 63 of file navier_stokes_elements.h.
References fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc().
Member Function Documentation
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc()
virtual void oomph::FpPressureAdvDiffRobinBCElementBase::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [pure virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Implemented in oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >, and oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >.
Referenced by oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::~FpPressureAdvDiffRobinBCElement(), and ~FpPressureAdvDiffRobinBCElementBase().
The documentation for this class was generated from the following file:
navier_stokes_elements.h