oomph::TrilinosIFPACKPreconditioner Class Reference
An interface to the Trilinos IFPACK class- provides a function to construct an IFPACK object, and functions to modify some of the IFPACK paramaters.
#include <trilinos_preconditioners.h>
Public Member Functions
TrilinosIFPACKPreconditioner ()
Constructor.
virtual ~TrilinosIFPACKPreconditioner ()
Destructor -- empty, cleanup is done in base class.
TrilinosIFPACKPreconditioner (const TrilinosIFPACKPreconditioner &)
Broken copy constructor.
void set_preconditioner_ILU ()
Broken assignment operator.
void set_preconditioner_ILUT ()
Function to set Preconditioner_type to `ILUT`.
int & ilu_fill_level ()
Access function for ILU_fill_level.
double & ilut_fill_level ()
Access function for ILUT_fill_level.
double & absolute_threshold ()
Access function for the absolute threshold.
double & relative_threshold ()
Access function for the relative threshold.
Protected Member Functions
void setup_trilinos_preconditioner (Epetra_CrsMatrix *epetra_matrix_pt)
Function to set up an IFPACK preconditioner. It is assumed Trilinos_matrix_pt points to a suitable matrix.
Protected Attributes
string Preconditioner_type
Type of ILU preconditioner.
int ILU_fill_level
Level of fill for `ILU`.
double ILUT_fill_level
Level of fill for `ILUT`.
int Overlap
Value of overlap level - used in parallel ILU.
double Absolute_threshold
Value of absolute threshold, used to peturb diagonal.
double Relative_threshold
Value of relative threshold, used to pertub diagonal.
Additional Inherited Members
Detailed Description
An interface to the Trilinos IFPACK class- provides a function to construct an IFPACK object, and functions to modify some of the IFPACK paramaters.
Definition at line 288 of file trilinos_preconditioners.h.
Constructor & Destructor Documentation
TrilinosIFPACKPreconditioner() [1/2]
oomph::TrilinosIFPACKPreconditioner::TrilinosIFPACKPreconditioner () [inline]
Constructor.
Definition at line 293 of file trilinos_preconditioners.h.
 TrilinosIFPACKPreconditioner()
virtual oomph::TrilinosIFPACKPreconditioner::~TrilinosIFPACKPreconditioner () [inline], [virtual]
Destructor -- empty, cleanup is done in base class.
Definition at line 305 of file trilinos_preconditioners.h.
TrilinosIFPACKPreconditioner() [2/2]
oomph::TrilinosIFPACKPreconditioner::TrilinosIFPACKPreconditioner (const TrilinosIFPACKPreconditioner &) [inline]
Broken copy constructor.
Definition at line 308 of file trilinos_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
absolute_threshold()
double& oomph::TrilinosIFPACKPreconditioner::absolute_threshold () [inline]
Access function for the absolute threshold.
Definition at line 339 of file trilinos_preconditioners.h.
ilu_fill_level()
int& oomph::TrilinosIFPACKPreconditioner::ilu_fill_level () [inline]
Access function for ILU_fill_level.
Definition at line 333 of file trilinos_preconditioners.h.
ilut_fill_level()
double& oomph::TrilinosIFPACKPreconditioner::ilut_fill_level () [inline]
Access function for ILUT_fill_level.
Definition at line 336 of file trilinos_preconditioners.h.
relative_threshold()
double& oomph::TrilinosIFPACKPreconditioner::relative_threshold () [inline]
Access function for the relative threshold.
Definition at line 342 of file trilinos_preconditioners.h.
References oomph::TrilinosPreconditionerBase::setup_trilinos_preconditioner().
set_preconditioner_ILU()
void oomph::TrilinosIFPACKPreconditioner::set_preconditioner_ILU () [inline]
Broken assignment operator.
Function to set Preconditioner_type to `ILU`
Definition at line 321 of file trilinos_preconditioners.h.
set_preconditioner_ILUT()
void oomph::TrilinosIFPACKPreconditioner::set_preconditioner_ILUT () [inline]
Function to set Preconditioner_type to `ILUT`.
Definition at line 327 of file trilinos_preconditioners.h.
setup_trilinos_preconditioner()
void oomph::TrilinosIFPACKPreconditioner::setup_trilinos_preconditioner (Epetra_CrsMatrix * epetra_matrix_pt) [protected], [virtual]
Function to set up an IFPACK preconditioner. It is assumed Trilinos_matrix_pt points to a suitable matrix.
Implements oomph::TrilinosPreconditionerBase.
Definition at line 256 of file trilinos_preconditioners.cc.
References oomph::TrilinosPreconditionerBase::Epetra_preconditioner_pt.
Referenced by oomph::TrilinosMLPreconditioner::setup_trilinos_preconditioner().
Member Data Documentation
Absolute_threshold
double oomph::TrilinosIFPACKPreconditioner::Absolute_threshold [protected]
Value of absolute threshold, used to peturb diagonal.
Definition at line 363 of file trilinos_preconditioners.h.
ILU_fill_level
int oomph::TrilinosIFPACKPreconditioner::ILU_fill_level [protected]
Level of fill for `ILU`.
Definition at line 354 of file trilinos_preconditioners.h.
ILUT_fill_level
double oomph::TrilinosIFPACKPreconditioner::ILUT_fill_level [protected]
Level of fill for `ILUT`.
Definition at line 357 of file trilinos_preconditioners.h.
Overlap
int oomph::TrilinosIFPACKPreconditioner::Overlap [protected]
Value of overlap level - used in parallel ILU.
Definition at line 360 of file trilinos_preconditioners.h.
Preconditioner_type
string oomph::TrilinosIFPACKPreconditioner::Preconditioner_type [protected]
Type of ILU preconditioner.
Definition at line 351 of file trilinos_preconditioners.h.
Relative_threshold
double oomph::TrilinosIFPACKPreconditioner::Relative_threshold [protected]
Value of relative threshold, used to pertub diagonal.
Definition at line 366 of file trilinos_preconditioners.h.
The documentation for this class was generated from the following files:
trilinos_preconditioners.h
trilinos_preconditioners.cc