oomph::AxisymAdvectionDiffusionEquations Class Reference
A class for all elements that solve the Advection Diffusion equations in a cylindrical polar coordinate system using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
#include <axisym_advection_diffusion_elements.h>
Public Types
typedef void(* AxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
typedef void(* AxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Public Member Functions
AxisymAdvectionDiffusionEquations ()
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
AxisymAdvectionDiffusionEquations (const AxisymAdvectionDiffusionEquations &dummy)
Broken copy constructor.
virtual unsigned u_index_axi_adv_diff () const
Broken assignment operator.
double du_dt_axi_adv_diff (const unsigned &n) const
du/dt at local node n.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: r,z,u at nplot^2 plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,u_exact at nplot^2 plot points.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
AxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
const double & d () const
Peclet number multiplied by Strouhal number.
double *& d_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_axi_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux:
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
double interpolated_u_axi_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_axi_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
double * D_pt
Pointer to global Diffusion parameter.
AxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
AxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
bool ALE_is_disabled
Boolean flag to indicate whether AlE formulation is disable.
Static Private Attributes
static double Default_peclet_number = 0.0
Static default value for the Peclet number.
static double Default_diffusion_parameter = 1.0
Static default value for the Peclet number.
Additional Inherited Members
Detailed Description
A class for all elements that solve the Advection Diffusion equations in a cylindrical polar coordinate system using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 61 of file axisym_advection_diffusion_elements.h.
Member Typedef Documentation
AxisymAdvectionDiffusionSourceFctPt
typedef void(* oomph::AxisymAdvectionDiffusionEquations::AxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 69 of file axisym_advection_diffusion_elements.h.
AxisymAdvectionDiffusionWindFctPt
typedef void(* oomph::AxisymAdvectionDiffusionEquations::AxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Definition at line 74 of file axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
AxisymAdvectionDiffusionEquations() [1/2]
oomph::AxisymAdvectionDiffusionEquations::AxisymAdvectionDiffusionEquations () [inline]
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
Definition at line 80 of file axisym_advection_diffusion_elements.h.
References D_pt, Default_diffusion_parameter, Default_peclet_number, Pe_pt, and PeSt_pt.
AxisymAdvectionDiffusionEquations() [2/2]
oomph::AxisymAdvectionDiffusionEquations::AxisymAdvectionDiffusionEquations (const AxisymAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 90 of file axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error()
void oomph::AxisymAdvectionDiffusionEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 428 of file axisym_advection_diffusion_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output().
d()
const double& oomph::AxisymAdvectionDiffusionEquations::d () const [inline]
Peclet number multiplied by Strouhal number.
Definition at line 323 of file axisym_advection_diffusion_elements.h.
References D_pt.
Referenced by fill_in_generic_residual_contribution_axi_adv_diff().
d_pt()
double* & oomph::AxisymAdvectionDiffusionEquations::d_pt () [inline]
Pointer to Peclet number multipled by Strouha number.
Definition at line 326 of file axisym_advection_diffusion_elements.h.
References D_pt.
dinterpolated_u_axi_adv_diff_ddata()
virtual void oomph::AxisymAdvectionDiffusionEquations::dinterpolated_u_axi_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
Definition at line 464 of file axisym_advection_diffusion_elements.h.
References dshape_and_dtest_eulerian_at_knot_axi_adv_diff(), dshape_and_dtest_eulerian_axi_adv_diff(), oomph::Data::eqn_number(), fill_in_generic_residual_contribution_axi_adv_diff(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, self_test(), oomph::FiniteElement::shape(), and u_index_axi_adv_diff().
disable_ALE()
void oomph::AxisymAdvectionDiffusionEquations::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 147 of file axisym_advection_diffusion_elements.h.
References ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_axi_adv_diff()
virtual double oomph::AxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_axi_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), fill_in_generic_residual_contribution_axi_adv_diff(), and oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_axi_adv_diff()
virtual double oomph::AxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_axi_adv_diff_ddata(), and oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
du_dt_axi_adv_diff()
double oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff (const unsigned & n) const [inline]
du/dt at local node n.
Uses suitably interpolated value for hanging nodes.
Definition at line 121 of file axisym_advection_diffusion_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axi_adv_diff(), and oomph::TimeStepper::weight().
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), and fill_in_generic_residual_contribution_axi_adv_diff().
enable_ALE()
void oomph::AxisymAdvectionDiffusionEquations::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 157 of file axisym_advection_diffusion_elements.h.
References ALE_is_disabled.
fill_in_contribution_to_jacobian()
void oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 420 of file axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_adv_diff().
fill_in_contribution_to_residuals()
void oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 406 of file axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_adv_diff().
fill_in_generic_residual_contribution_axi_adv_diff()
void oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableAxisymAdvectionDiffusionEquations.
Definition at line 54 of file axisym_advection_diffusion_elements.cc.
References ALE_is_disabled, d(), dshape_and_dtest_eulerian_at_knot_axi_adv_diff(), du_dt_axi_adv_diff(), get_source_axi_adv_diff(), get_wind_axi_adv_diff(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), pe(), pe_st(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, oomph::Data::time_stepper_pt(), u_index_axi_adv_diff(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by dinterpolated_u_axi_adv_diff_ddata(), fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_flux()
void oomph::AxisymAdvectionDiffusionEquations::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux:
Definition at line 376 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_adv_diff().
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::get_Z2_flux().
get_source_axi_adv_diff()
virtual void oomph::AxisymAdvectionDiffusionEquations::get_source_axi_adv_diff (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 332 of file axisym_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), and fill_in_generic_residual_contribution_axi_adv_diff().
get_wind_axi_adv_diff()
virtual void oomph::AxisymAdvectionDiffusionEquations::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 353 of file axisym_advection_diffusion_elements.h.
References i, and Wind_fct_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), fill_in_generic_residual_contribution_axi_adv_diff(), output(), and scalar_value_paraview().
interpolated_u_axi_adv_diff()
double oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 432 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_axi_adv_diff().
Referenced by compute_error(), output(), and scalar_value_paraview().
nscalar_paraview()
unsigned oomph::AxisymAdvectionDiffusionEquations::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 165 of file axisym_advection_diffusion_elements.h.
output() [1/4]
void oomph::AxisymAdvectionDiffusionEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 254 of file axisym_advection_diffusion_elements.h.
Referenced by output(), and oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output().
output() [2/4]
void oomph::AxisymAdvectionDiffusionEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: r,z,u at nplot^2 plot points.
Output function:
r,z,u,w_r,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 279 of file axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), get_wind_axi_adv_diff(), i, interpolated_u_axi_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::AxisymAdvectionDiffusionEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 266 of file axisym_advection_diffusion_elements.h.
References compute_error(), output(), and output_fct().
output() [4/4]
void oomph::AxisymAdvectionDiffusionEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 334 of file axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_axi_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct()
void oomph::AxisymAdvectionDiffusionEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_exact at nplot^2 plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 374 of file axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output(), and oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
pe()
const double& oomph::AxisymAdvectionDiffusionEquations::pe () const [inline]
Peclet number.
Definition at line 311 of file axisym_advection_diffusion_elements.h.
References Pe_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), and fill_in_generic_residual_contribution_axi_adv_diff().
pe_pt()
double* & oomph::AxisymAdvectionDiffusionEquations::pe_pt () [inline]
Pointer to Peclet number.
Definition at line 314 of file axisym_advection_diffusion_elements.h.
References Pe_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build().
pe_st()
const double& oomph::AxisymAdvectionDiffusionEquations::pe_st () const [inline]
Peclet number multiplied by Strouhal number.
Definition at line 317 of file axisym_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), and fill_in_generic_residual_contribution_axi_adv_diff().
pe_st_pt()
double* & oomph::AxisymAdvectionDiffusionEquations::pe_st_pt () [inline]
Pointer to Peclet number multipled by Strouha number.
Definition at line 320 of file axisym_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build().
scalar_name_paraview()
std::string oomph::AxisymAdvectionDiffusionEquations::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 225 of file axisym_advection_diffusion_elements.h.
References oomph::StringConversion::to_string().
scalar_value_paraview()
void oomph::AxisymAdvectionDiffusionEquations::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 172 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::get_s_plot(), get_wind_axi_adv_diff(), i, interpolated_u_axi_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test()
unsigned oomph::AxisymAdvectionDiffusionEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 247 of file axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by dinterpolated_u_axi_adv_diff_ddata().
source_fct_pt() [1/2]
AxisymAdvectionDiffusionSourceFctPt& oomph::AxisymAdvectionDiffusionEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 290 of file axisym_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build().
source_fct_pt() [2/2]
AxisymAdvectionDiffusionSourceFctPt oomph::AxisymAdvectionDiffusionEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 295 of file axisym_advection_diffusion_elements.h.
References Source_fct_pt.
u_index_axi_adv_diff()
virtual unsigned oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the spherical advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 113 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::AxisymAdvectionDiffusionFluxElement< ELEMENT >::AxisymAdvectionDiffusionFluxElement(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), dinterpolated_u_axi_adv_diff_ddata(), du_dt_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), fill_in_generic_residual_contribution_axi_adv_diff(), get_flux(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), and interpolated_u_axi_adv_diff().
wind_fct_pt() [1/2]
AxisymAdvectionDiffusionWindFctPt& oomph::AxisymAdvectionDiffusionEquations::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 300 of file axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build().
wind_fct_pt() [2/2]
AxisymAdvectionDiffusionWindFctPt oomph::AxisymAdvectionDiffusionEquations::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 305 of file axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
Member Data Documentation
ALE_is_disabled
bool oomph::AxisymAdvectionDiffusionEquations::ALE_is_disabled [protected]
Boolean flag to indicate whether AlE formulation is disable.
Definition at line 566 of file axisym_advection_diffusion_elements.h.
Referenced by disable_ALE(), enable_ALE(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), and fill_in_generic_residual_contribution_axi_adv_diff().
D_pt
double* oomph::AxisymAdvectionDiffusionEquations::D_pt [protected]
Pointer to global Diffusion parameter.
Definition at line 557 of file axisym_advection_diffusion_elements.h.
Referenced by AxisymAdvectionDiffusionEquations(), d(), and d_pt().
Default_diffusion_parameter
double oomph::AxisymAdvectionDiffusionEquations::Default_diffusion_parameter = 1.0 [static], [private]
Static default value for the Peclet number.
Default Diffusion coefficient.
Definition at line 574 of file axisym_advection_diffusion_elements.h.
Referenced by AxisymAdvectionDiffusionEquations().
Default_peclet_number
double oomph::AxisymAdvectionDiffusionEquations::Default_peclet_number = 0.0 [static], [private]
Static default value for the Peclet number.
Default value for Peclet number.
Definition at line 571 of file axisym_advection_diffusion_elements.h.
Referenced by AxisymAdvectionDiffusionEquations().
Pe_pt
double* oomph::AxisymAdvectionDiffusionEquations::Pe_pt [protected]
Pointer to global Peclet number.
Definition at line 551 of file axisym_advection_diffusion_elements.h.
Referenced by AxisymAdvectionDiffusionEquations(), oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), pe(), and pe_pt().
PeSt_pt
double* oomph::AxisymAdvectionDiffusionEquations::PeSt_pt [protected]
Pointer to global Peclet number multiplied by Strouhal number.
Definition at line 554 of file axisym_advection_diffusion_elements.h.
Referenced by AxisymAdvectionDiffusionEquations(), oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), pe_st(), and pe_st_pt().
Source_fct_pt
AxisymAdvectionDiffusionSourceFctPt oomph::AxisymAdvectionDiffusionEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 560 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), get_source_axi_adv_diff(), and source_fct_pt().
Wind_fct_pt
AxisymAdvectionDiffusionWindFctPt oomph::AxisymAdvectionDiffusionEquations::Wind_fct_pt [protected]
Pointer to wind function:
Definition at line 563 of file axisym_advection_diffusion_elements.h.
Referenced by oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), get_wind_axi_adv_diff(), and wind_fct_pt().
The documentation for this class was generated from the following files:
axisym_advection_diffusion_elements.h
axisym_advection_diffusion_elements.cc