oomph::SpineNode Class Reference
#include <spines.h>
Public Member Functions
SpineNode (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Steady Constructor, initialise pointers to zero.
SpineNode (TimeStepper *const &time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Unsteady Constructor, initialise pointers to zero.
Spine *& spine_pt ()
Access function to spine.
double & fraction ()
Set reference to fraction along spine.
unsigned & node_update_fct_id ()
Access function to ID of node update function (within specific mesh)
SpineMesh *& spine_mesh_pt ()
Access function to Pointer to SpineMesh that this node is a part of and which implements the node update function(s)
double & h ()
Access function to spine height.
void node_update (const bool &update_all_time_levels_for_new_node=false)
Update function, call the update function in the Node's SpineMesh.
unsigned ngeom_data () const
Return the number of geometric data, zero if no spine.
unsigned ngeom_object () const
Return the number of geometric objects, zero if no spine.
Data ** all_geom_data_pt ()
Return the vector of all geometric data.
GeomObject ** all_geom_object_pt ()
Return the vector of all geometric objects.
Private Attributes
Spine * Spine_pt
Private internal data pointer to a spine.
double Fraction
Private double that represents the fixed fraction along the spine.
SpineMesh * Spine_mesh_pt
Pointer to SpineMesh that this node is a part of. (The mesh implements the node update function(s))
unsigned Node_update_fct_id
Additional Inherited Members
Detailed Description
Class for nodes that live on spines. The assumption is that each Node lies at a fixed fraction on a single spine (although more complex behaviour could be included by adding more variables to the spine). In general, more complex node updating should be handled by the classes implemented for algebraic node updates.
Definition at line 309 of file spines.h.
Constructor & Destructor Documentation
SpineNode() [1/2]
oomph::SpineNode::SpineNode (const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Steady Constructor, initialise pointers to zero.
Definition at line 334 of file spines.h.
SpineNode() [2/2]
oomph::SpineNode::SpineNode (TimeStepper *const & time_stepper_pt, const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Unsteady Constructor, initialise pointers to zero.
Definition at line 340 of file spines.h.
Member Function Documentation
all_geom_data_pt()
Data** oomph::SpineNode::all_geom_data_pt () [inline], [virtual]
Return the vector of all geometric data.
Reimplemented from oomph::Node.
Definition at line 382 of file spines.h.
References oomph::Spine::geom_data_pt().
all_geom_object_pt()
GeomObject** oomph::SpineNode::all_geom_object_pt () [inline], [virtual]
Return the vector of all geometric objects.
Reimplemented from oomph::Node.
Definition at line 386 of file spines.h.
References oomph::Spine::geom_object_pt().
fraction()
double& oomph::SpineNode::fraction () [inline]
Set reference to fraction along spine.
Definition at line 350 of file spines.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
h()
double& oomph::SpineNode::h () [inline]
Access function to spine height.
Definition at line 363 of file spines.h.
References oomph::Spine::height().
Referenced by oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update(), oomph::SingleLayerSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
ngeom_data()
unsigned oomph::SpineNode::ngeom_data () const [inline], [virtual]
Return the number of geometric data, zero if no spine.
Reimplemented from oomph::Node.
Definition at line 370 of file spines.h.
References oomph::Spine::ngeom_data().
ngeom_object()
unsigned oomph::SpineNode::ngeom_object () const [inline], [virtual]
Return the number of geometric objects, zero if no spine.
Reimplemented from oomph::Node.
Definition at line 376 of file spines.h.
References oomph::Spine::ngeom_object().
node_update()
void oomph::SpineNode::node_update (const bool & update_all_time_levels_for_new_node = false) [virtual]
Update function, call the update function in the Node's SpineMesh.
Overload thet node update function, call the update function in the Node's SpineMesh
Reimplemented from oomph::Node.
Definition at line 50 of file spines.cc.
References oomph::Node::Aux_node_update_fct_pt, Spine_mesh_pt, and oomph::SpineMesh::spine_node_update().
Referenced by oomph::SpineMesh::node_update().
node_update_fct_id()
unsigned& oomph::SpineNode::node_update_fct_id () [inline]
Access function to ID of node update function (within specific mesh)
Definition at line 353 of file spines.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update(), and oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update().
spine_mesh_pt()
SpineMesh*& oomph::SpineNode::spine_mesh_pt () [inline]
Access function to Pointer to SpineMesh that this node is a part of and which implements the node update function(s)
Definition at line 357 of file spines.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh().
spine_pt()
Spine* & oomph::SpineNode::spine_pt () [inline]
Access function to spine.
Definition at line 347 of file spines.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::SpineMesh::dump(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_spine_value(), oomph::SpineMesh::read(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), oomph::ChannelSpineMesh< ELEMENT >::spine_node_update(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
Member Data Documentation
Fraction
double oomph::SpineNode::Fraction [private]
Private double that represents the fixed fraction along the spine.
Definition at line 319 of file spines.h.
Node_update_fct_id
unsigned oomph::SpineNode::Node_update_fct_id [private]
ID of node update function (within specific mesh -- useful if there are multiple node update functions, e.g. in two-layer problems.
Definition at line 327 of file spines.h.
Spine_mesh_pt
SpineMesh* oomph::SpineNode::Spine_mesh_pt [private]
Pointer to SpineMesh that this node is a part of. (The mesh implements the node update function(s))
Definition at line 323 of file spines.h.
Referenced by node_update().
Spine_pt
Spine* oomph::SpineNode::Spine_pt [private]
Private internal data pointer to a spine.
Definition at line 316 of file spines.h.
Referenced by oomph::SpineMesh::assign_global_spine_eqn_numbers(), oomph::SpineMesh::describe_spine_dofs(), oomph::SpineMesh::does_pointer_correspond_to_spine_data(), oomph::SpineMesh::set_consistent_pinned_spine_values_for_continuation(), oomph::SpineMesh::set_spine_time_stepper(), and oomph::SpineMesh::~SpineMesh().
The documentation for this class was generated from the following files:
spines.h
spines.cc