oomph::RefineableNavierStokesEquations< DIM > Class Template Reference
#include <refineable_navier_stokes_elements.h>
Public Member Functions
RefineableNavierStokesEquations ()
Constructor.
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement *> &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement *> &element_pt)
Unpin all pressure dofs in elements listed in vector.
Protected Member Functions
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableNavierStokesEquations< DIM >
Refineable version of the Navier--Stokes equations
Definition at line 340 of file refineable_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableNavierStokesEquations()
template<unsigned DIM>
oomph::RefineableNavierStokesEquations< DIM >::RefineableNavierStokesEquations () [inline]
Constructor.
Definition at line 357 of file refineable_navier_stokes_elements.h.
Member Function Documentation
dinterpolated_u_nst_ddata()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::NavierStokesEquations< DIM >.
Definition at line 500 of file refineable_navier_stokes_elements.h.
References oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), oomph::FiniteElement::get_dresidual_dnodal_coordinates(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::FiniteElement::shape().
fill_in_generic_pressure_advection_diffusion_contribution_nst()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::NavierStokesEquations< DIM >.
Definition at line 306 of file refineable_navier_stokes_elements.cc.
References e, oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal().
fill_in_generic_residual_contribution_nst()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::NavierStokesEquations< DIM >.
Definition at line 590 of file refineable_navier_stokes_elements.cc.
References oomph::ALE_is_disabled, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst().
further_build()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::further_build () [inline], [virtual]
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, and oomph::RefineableQCrouzeixRaviartElement< DIM >.
Definition at line 463 of file refineable_navier_stokes_elements.h.
References oomph::NavierStokesEquations< DIM >::ALE_is_disabled, oomph::ALE_is_disabled, oomph::NavierStokesEquations< DIM >::body_force_fct_pt(), oomph::NavierStokesEquations< DIM >::density_ratio_pt(), oomph::NavierStokesEquations< DIM >::g_pt(), oomph::NavierStokesEquations< DIM >::re_invfr_pt(), oomph::NavierStokesEquations< DIM >::re_pt(), oomph::NavierStokesEquations< DIM >::re_st_pt(), oomph::Source_fct_pt, oomph::NavierStokesEquations< DIM >::source_fct_pt(), and oomph::NavierStokesEquations< DIM >::viscosity_ratio_pt().
Referenced by oomph::RefineableQCrouzeixRaviartElement< DIM >::further_build(), and oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build().
get_dresidual_dnodal_coordinates()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [protected], [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::RefineableElement.
Definition at line 1123 of file refineable_navier_stokes_elements.cc.
References oomph::ALE_is_disabled, oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::Node::has_auxiliary_node_update_fct_pt(), i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::Node::perform_auxiliary_node_update_fct(), s, oomph::Data::value_pt(), and oomph::Node::x().
get_pressure_and_velocity_mass_matrix_diagonal()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Reimplemented from oomph::NavierStokesEquations< DIM >.
Definition at line 51 of file refineable_navier_stokes_elements.cc.
References oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableNavierStokesEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 421 of file refineable_navier_stokes_elements.h.
References i.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableNavierStokesEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 413 of file refineable_navier_stokes_elements.h.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_compound_flux_indices(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
pin_elemental_redundant_nodal_pressure_dofs()
template<unsigned DIM>
virtual void oomph::RefineableNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >.
Definition at line 352 of file refineable_navier_stokes_elements.h.
pin_redundant_nodal_pressures()
template<unsigned DIM>
static void oomph::RefineableNavierStokesEquations< DIM >::pin_redundant_nodal_pressures (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 373 of file refineable_navier_stokes_elements.h.
References e.
pressure_node_pt()
template<unsigned DIM>
virtual Node* oomph::RefineableNavierStokesEquations< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >.
Definition at line 401 of file refineable_navier_stokes_elements.h.
unpin_all_pressure_dofs()
template<unsigned DIM>
static void oomph::RefineableNavierStokesEquations< DIM >::unpin_all_pressure_dofs (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 387 of file refineable_navier_stokes_elements.h.
References e.
unpin_elemental_pressure_dofs()
template<unsigned DIM>
virtual void oomph::RefineableNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, and oomph::RefineableQTaylorHoodElement< DIM >.
The documentation for this class was generated from the following files:
refineable_navier_stokes_elements.h
refineable_navier_stokes_elements.cc