oomph::AxisymFoepplvonKarmanElement< NNODE_1D > Class Template Reference
#include <axisym_displ_based_fvk_elements.h>
Public Member Functions
AxisymFoepplvonKarmanElement ()
Constructor: Call constructors for QElement and AxisymFoepplvonKarmanEquations.
AxisymFoepplvonKarmanElement (const AxisymFoepplvonKarmanElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const AxisymFoepplvonKarmanElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: r,w,sigma_r_r,sigma_phi_phi.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
void output (FILE *file_pt)
C-style output function: r,w.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,w at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,w_exact at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,w_exact at n_plot plot points (Calls the steady version)
AxisymFoepplvonKarmanElement ()
Constructor: Call constructors for QElement and AxisymFoepplvonKarmanEquations.
AxisymFoepplvonKarmanElement (const AxisymFoepplvonKarmanElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const AxisymFoepplvonKarmanElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: r,w,sigma_r_r,sigma_phi_phi.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
void output (FILE *file_pt)
C-style output function: r,w.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,w at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,w_exact at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,w_exact at n_plot plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
double dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 3
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::AxisymFoepplvonKarmanElement< NNODE_1D >
Axisym FoepplvonKarmanElement elements are 1D Foeppl von Karman elements with isoparametric interpolation for the function.
Definition at line 402 of file axisym_displ_based_fvk_elements.h.
Constructor & Destructor Documentation
AxisymFoepplvonKarmanElement() [1/4]
template<unsigned NNODE_1D>
oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::AxisymFoepplvonKarmanElement () [inline]
Constructor: Call constructors for QElement and AxisymFoepplvonKarmanEquations.
Definition at line 416 of file axisym_displ_based_fvk_elements.h.
AxisymFoepplvonKarmanElement() [2/4]
template<unsigned NNODE_1D>
oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::AxisymFoepplvonKarmanElement (const AxisymFoepplvonKarmanElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 422 of file axisym_displ_based_fvk_elements.h.
References oomph::BrokenCopy::broken_copy().
AxisymFoepplvonKarmanElement() [3/4]
template<unsigned NNODE_1D>
oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::AxisymFoepplvonKarmanElement () [inline]
Constructor: Call constructors for QElement and AxisymFoepplvonKarmanEquations.
Definition at line 395 of file axisym_fvk_elements.h.
AxisymFoepplvonKarmanElement() [4/4]
template<unsigned NNODE_1D>
oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::AxisymFoepplvonKarmanElement (const AxisymFoepplvonKarmanElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 401 of file axisym_fvk_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_axisym_fvk() [1/2]
template<unsigned NNODE_1D>
double oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Implements oomph::AxisymFoepplvonKarmanEquations.
dshape_and_dtest_eulerian_at_knot_axisym_fvk() [2/2]
template<unsigned NNODE_1D>
double oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AxisymFoepplvonKarmanEquations.
Definition at line 536 of file axisym_displ_based_fvk_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_axisym_fvk(), and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_axisym_fvk() [1/2]
template<unsigned NNODE_1D>
double oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Implements oomph::AxisymFoepplvonKarmanEquations.
dshape_and_dtest_eulerian_axisym_fvk() [2/2]
template<unsigned NNODE_1D>
double oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AxisymFoepplvonKarmanEquations.
Definition at line 508 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axisym_fvk(), and oomph::FiniteElement::dshape_eulerian().
Referenced by oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct().
operator=() [1/2]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::operator= (const AxisymFoepplvonKarmanElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 407 of file axisym_fvk_elements.h.
References oomph::BrokenCopy::broken_assign().
operator=() [2/2]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::operator= (const AxisymFoepplvonKarmanElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 428 of file axisym_displ_based_fvk_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,w,sigma_r_r,sigma_phi_phi.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 420 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [2/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.
Definition at line 425 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [3/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,w.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 430 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [4/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,w at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 435 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [5/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,w,sigma_r_r,sigma_phi_phi.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 441 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [6/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.
Definition at line 446 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [7/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,w.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 451 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output() [8/8]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,w at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 456 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output().
output_fct() [1/4]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,w_exact at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 440 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output_fct().
output_fct() [2/4]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. r,w_exact at n_plot plot points (Calls the steady version)
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 447 of file axisym_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_axisym_fvk(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axisym_fvk(), oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_axisym_fvk(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_axisym_fvk(), oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::dshape_eulerian_at_knot(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), and s.
output_fct() [3/4]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,w_exact at n_plot plot points.
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 461 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::output_fct().
output_fct() [4/4]
template<unsigned NNODE_1D>
void oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. r,w_exact at n_plot plot points (Calls the steady version)
Reimplemented from oomph::AxisymFoepplvonKarmanEquations.
Definition at line 469 of file axisym_displ_based_fvk_elements.h.
References oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_axisym_fvk(), oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_axisym_fvk(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_axisym_fvk(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), and s.
required_nvalue() [1/2]
template<unsigned NNODE_1D>
unsigned oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 414 of file axisym_fvk_elements.h.
required_nvalue() [2/2]
template<unsigned NNODE_1D>
unsigned oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 435 of file axisym_displ_based_fvk_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
static const unsigned oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue = 3 [static], [private]
Static int that holds the number of variables at nodes: always the same.
Set the data for the number of Variables at each node: 6.
Set the data for the number of Variables at each node - 3.
Definition at line 410 of file axisym_displ_based_fvk_elements.h.
The documentation for this class was generated from the following files:
axisym_displ_based_fvk_elements.h
axisym_fvk_elements.h
axisym_displ_based_fvk_elements.cc
axisym_fvk_elements.cc