oomph::ILUZeroPreconditioner< CCDoubleMatrix > Class Template Reference
ILU(0) Preconditioner for matrices of CCDoubleMatrix Format.
#include <general_purpose_preconditioners.h>
Public Member Functions
ILUZeroPreconditioner ()
Constructor (empty)
~ILUZeroPreconditioner ()
Destructor (empty)
ILUZeroPreconditioner (const ILUZeroPreconditioner &)
Broken copy constructor.
void operator= (const ILUZeroPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void setup ()
Setup the preconditioner (store diagonal) from the fully assembled matrix. Problem pointer is ignored.
Private Attributes
Vector< unsigned > U_column_start
Column start for upper triangular matrix.
Vector< CompressedMatrixCoefficient > U_row_entry
Row entry for the upper triangular matrix (each element of the vector contains the row index and coefficient)
Vector< unsigned > L_column_start
Column start for lower triangular matrix.
Vector< CompressedMatrixCoefficient > L_row_entry
Row entry for the lower triangular matrix (each element of the vector contains the row index and coefficient)
Additional Inherited Members
Detailed Description
template<>
class oomph::ILUZeroPreconditioner< CCDoubleMatrix >
ILU(0) Preconditioner for matrices of CCDoubleMatrix Format.
Definition at line 285 of file general_purpose_preconditioners.h.
Constructor & Destructor Documentation
ILUZeroPreconditioner() [1/2]
oomph::ILUZeroPreconditioner< CCDoubleMatrix >::ILUZeroPreconditioner () [inline]
Constructor (empty)
Definition at line 291 of file general_purpose_preconditioners.h.
 ILUZeroPreconditioner()
oomph::ILUZeroPreconditioner< CCDoubleMatrix >::~ILUZeroPreconditioner () [inline]
Destructor (empty)
Definition at line 294 of file general_purpose_preconditioners.h.
ILUZeroPreconditioner() [2/2]
oomph::ILUZeroPreconditioner< CCDoubleMatrix >::ILUZeroPreconditioner (const ILUZeroPreconditioner< CCDoubleMatrix > &) [inline]
Broken copy constructor.
Definition at line 298 of file general_purpose_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
void oomph::ILUZeroPreconditioner< CCDoubleMatrix >::operator= (const ILUZeroPreconditioner< CCDoubleMatrix > &) [inline]
Broken assignment operator.
Definition at line 304 of file general_purpose_preconditioners.h.
References oomph::BrokenCopy::broken_assign(), oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), and oomph::MatrixBasedDiagPreconditioner::setup().
preconditioner_solve()
void oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Apply ILU(0) preconditioner for CCDoubleMatrix: Solve Ly=r then Uz=y and return z.
Implements oomph::Preconditioner.
Definition at line 620 of file general_purpose_preconditioners.cc.
References oomph::DoubleVector::built(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, and oomph::DistributableLinearAlgebraObject::nrow().
setup()
void oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup () [virtual]
Setup the preconditioner (store diagonal) from the fully assembled matrix. Problem pointer is ignored.
setup ILU(0) preconditioner for Matrices of CCDoubleMatrix type
Implements oomph::Preconditioner.
Definition at line 327 of file general_purpose_preconditioners.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::CCMatrix< T >::column_start(), oomph::Preconditioner::comm_pt(), i, oomph::Preconditioner::matrix_pt(), oomph::CCDoubleMatrix::nrow(), oomph::CCMatrix< T >::row_index(), and oomph::SparseMatrix< T, MATRIX_TYPE >::value().
Member Data Documentation
L_column_start
Vector<unsigned> oomph::ILUZeroPreconditioner< CCDoubleMatrix >::L_column_start [private]
Column start for lower triangular matrix.
Definition at line 327 of file general_purpose_preconditioners.h.
L_row_entry
Vector<CompressedMatrixCoefficient> oomph::ILUZeroPreconditioner< CCDoubleMatrix >::L_row_entry [private]
Row entry for the lower triangular matrix (each element of the vector contains the row index and coefficient)
Definition at line 331 of file general_purpose_preconditioners.h.
U_column_start
Vector<unsigned> oomph::ILUZeroPreconditioner< CCDoubleMatrix >::U_column_start [private]
Column start for upper triangular matrix.
Definition at line 320 of file general_purpose_preconditioners.h.
U_row_entry
Vector<CompressedMatrixCoefficient> oomph::ILUZeroPreconditioner< CCDoubleMatrix >::U_row_entry [private]
Row entry for the upper triangular matrix (each element of the vector contains the row index and coefficient)
Definition at line 324 of file general_purpose_preconditioners.h.
The documentation for this class was generated from the following files:
general_purpose_preconditioners.h
general_purpose_preconditioners.cc