oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D > Class Template Reference
#include <scalar_advection_elements.h>
Public Member Functions
unsigned required_nflux ()
Set the number of flux components.
void calculate_element_averages (double *&average_value)
Calculate the averages in the element.
DGSpectralScalarAdvectionElement ()
~DGSpectralScalarAdvectionElement ()
void build_all_faces ()
void fill_in_generic_residual_contribution_flux_transport (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
void get_inverse_mass_matrix_times_residuals (Vector< double > &minv_res)
Private Attributes
Vector< double > Inverse_mass_diagonal
Friends
class DGScalarAdvectionFaceElement< DGSpectralScalarAdvectionElement< 1, NNODE_1D > >
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >
Definition at line 458 of file scalar_advection_elements.h.
Constructor & Destructor Documentation
DGSpectralScalarAdvectionElement()
template<unsigned NNODE_1D>
oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::DGSpectralScalarAdvectionElement () [inline]
Definition at line 476 of file scalar_advection_elements.h.
 DGSpectralScalarAdvectionElement()
template<unsigned NNODE_1D>
oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::~DGSpectralScalarAdvectionElement () [inline]
Definition at line 480 of file scalar_advection_elements.h.
Member Function Documentation
build_all_faces()
template<unsigned NNODE_1D>
void oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::build_all_faces () [inline], [virtual]
Implements oomph::DGElement.
Definition at line 482 of file scalar_advection_elements.h.
calculate_element_averages()
template<unsigned NNODE_1D>
void oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::calculate_element_averages (double *& average_values) [inline], [virtual]
Calculate the averages in the element.
Reimplemented from oomph::DGElement.
Definition at line 472 of file scalar_advection_elements.h.
References oomph::FluxTransportEquations< DIM >::calculate_element_averages().
fill_in_generic_residual_contribution_flux_transport()
template<unsigned NNODE_1D>
void oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [inline], [virtual]
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 501 of file scalar_advection_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
get_inverse_mass_matrix_times_residuals()
template<unsigned NNODE_1D>
void oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::get_inverse_mass_matrix_times_residuals (Vector< double > & minv_res) [inline], [virtual]
Function that returns the current value of the residuals multiplied by the inverse mass matrix (virtual so that it can be overloaded specific elements in which time and memory saving tricks can be applied)
Reimplemented from oomph::DGElement.
Definition at line 520 of file scalar_advection_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_mass_matrix(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_residuals(), oomph::GeneralisedElement::ndof(), and oomph::GeneralisedElement::nexternal_data().
required_nflux()
template<unsigned NNODE_1D>
unsigned oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::required_nflux () [inline], [virtual]
Set the number of flux components.
Reimplemented from oomph::DGElement.
Definition at line 469 of file scalar_advection_elements.h.
Friends And Related Function Documentation
DGScalarAdvectionFaceElement< DGSpectralScalarAdvectionElement< 1, NNODE_1D > >
template<unsigned NNODE_1D>
friend class DGScalarAdvectionFaceElement< DGSpectralScalarAdvectionElement< 1, NNODE_1D > > [friend]
Definition at line 462 of file scalar_advection_elements.h.
Member Data Documentation
Inverse_mass_diagonal
template<unsigned NNODE_1D>
Vector<double> oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::Inverse_mass_diagonal [private]
Definition at line 464 of file scalar_advection_elements.h.
The documentation for this class was generated from the following file:
scalar_advection_elements.h