oomph::TFoepplvonKarmanElement< NNODE_1D > Class Template Reference
#include <Tfoeppl_von_karman_elements.h>
Public Member Functions
TFoepplvonKarmanElement ()
Constructor: Call constructors for TElement and Foeppl von Karman equations.
TFoepplvonKarmanElement (const TFoepplvonKarmanElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const TFoepplvonKarmanElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 8)
void output (std::ostream &outfile)
Output function: x,y,w.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,w at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: x,y,w.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,w at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,w_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,w_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from FvK equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 8
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::TFoepplvonKarmanElement< NNODE_1D >
TFoepplvonKarmanElement<NNODE_1D> elements are isoparametric triangular 2-dimensional Foeppl von Karman elements with NNODE_1D nodal points along each element edge. Inherits from TElement and FoepplvonKarmanEquations
Definition at line 67 of file Tfoeppl_von_karman_elements.h.
Constructor & Destructor Documentation
TFoepplvonKarmanElement() [1/2]
template<unsigned NNODE_1D>
oomph::TFoepplvonKarmanElement< NNODE_1D >::TFoepplvonKarmanElement () [inline]
Constructor: Call constructors for TElement and Foeppl von Karman equations.
Definition at line 76 of file Tfoeppl_von_karman_elements.h.
TFoepplvonKarmanElement() [2/2]
template<unsigned NNODE_1D>
oomph::TFoepplvonKarmanElement< NNODE_1D >::TFoepplvonKarmanElement (const TFoepplvonKarmanElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 81 of file Tfoeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_fvk()
template<unsigned NNODE_1D>
double oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FoepplvonKarmanEquations.
Definition at line 239 of file Tfoeppl_von_karman_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk(), and oomph::TFoepplvonKarmanElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_fvk()
template<unsigned NNODE_1D>
double oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FoepplvonKarmanEquations.
Definition at line 204 of file Tfoeppl_von_karman_elements.h.
References oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::TFoepplvonKarmanElement< NNODE_1D >::output_fct().
get_Z2_flux()
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from FvK equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 172 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::get_gradient_of_deflection().
nrecovery_order()
template<unsigned NNODE_1D>
unsigned oomph::TFoepplvonKarmanElement< NNODE_1D >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 166 of file Tfoeppl_von_karman_elements.h.
num_Z2_flux_terms()
template<unsigned NNODE_1D>
unsigned oomph::TFoepplvonKarmanElement< NNODE_1D >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 169 of file Tfoeppl_von_karman_elements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::TFoepplvonKarmanElement< NNODE_1D >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 176 of file Tfoeppl_von_karman_elements.h.
operator=()
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::operator= (const TFoepplvonKarmanElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 87 of file Tfoeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,w.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 99 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,w at n_plot^2 plot points.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 106 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,w.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 114 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,w at n_plot^2 plot points.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 122 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,w_exact.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 130 of file Tfoeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::TFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,w_exact (calls the steady version)
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 139 of file Tfoeppl_von_karman_elements.h.
References oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk(), oomph::TFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk(), oomph::FoepplvonKarmanEquations::output_fct(), and s.
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::TFoepplvonKarmanElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 8)
Reimplemented from oomph::FiniteElement.
Definition at line 94 of file Tfoeppl_von_karman_elements.h.
References oomph::TFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue.
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::TFoepplvonKarmanElement< NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 180 of file Tfoeppl_von_karman_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::TFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue = 8 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
Definition at line 186 of file Tfoeppl_von_karman_elements.h.
Referenced by oomph::TFoepplvonKarmanElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
Tfoeppl_von_karman_elements.h
Tfoeppl_von_karman_elements.cc