oomph::RungeKutta< ORDER > Class Template Reference
#include <explicit_timesteppers.h>
Public Member Functions
RungeKutta ()
Constructor, set the type.
RungeKutta (const RungeKutta &)
Broken copy constructor.
void operator= (const RungeKutta &)
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance time in the object.
template<>
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Explicit specialisation for fourth-order RK scheme.
template<>
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Explicit specialisation for second-order RK scheme.
Additional Inherited Members
Detailed Description
template<unsigned ORDER>
class oomph::RungeKutta< ORDER >
=========================================================== Standard Runge Kutta Timestepping
Definition at line 210 of file explicit_timesteppers.h.
Constructor & Destructor Documentation
RungeKutta() [1/2]
template<unsigned ORDER>
oomph::RungeKutta< ORDER >::RungeKutta () [inline]
Constructor, set the type.
Definition at line 215 of file explicit_timesteppers.h.
RungeKutta() [2/2]
template<unsigned ORDER>
oomph::RungeKutta< ORDER >::RungeKutta (const RungeKutta< ORDER > &) [inline]
Broken copy constructor.
Definition at line 221 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<unsigned ORDER>
void oomph::RungeKutta< ORDER >::operator= (const RungeKutta< ORDER > &) [inline]
Broken assignment operator.
Definition at line 227 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
timestep() [1/3]
template<>
void oomph::RungeKutta< 4 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Explicit specialisation for fourth-order RK scheme.
Implements oomph::ExplicitTimeStepper.
Definition at line 221 of file explicit_timesteppers.cc.
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), oomph::ExplicitTimeSteppableObject::set_dofs(), and oomph::ExplicitTimeSteppableObject::time().
timestep() [2/3]
template<unsigned ORDER>
void oomph::RungeKutta< ORDER >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Function that is used to advance time in the object.
Implements oomph::ExplicitTimeStepper.
Definition at line 207 of file explicit_timesteppers.cc.
timestep() [3/3]
template<>
void oomph::RungeKutta< 2 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Explicit specialisation for second-order RK scheme.
Implements oomph::ExplicitTimeStepper.
Definition at line 297 of file explicit_timesteppers.cc.
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), oomph::ExplicitTimeSteppableObject::set_dofs(), and oomph::ExplicitTimeSteppableObject::time().
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc