oomph::PolarNavierStokesTractionElement< ELEMENT > Class Template Reference
#include <polar_fluid_traction_elements.h>
Public Member Functions
const double & alpha () const
Alpha.
double *& alpha_pt ()
Pointer to Alpha.
void set_external_pressure_data (Data *pext_data_pt)
Function for setting up external pressure.
const int boundary () const
Boundary.
void set_boundary (int bound)
Function to set boundary.
const double get_eta () const
Eta.
void set_eta (double eta)
Function to set Eta.
PolarNavierStokesTractionElement (FiniteElement *const &element_pt, const int &face_index)
~PolarNavierStokesTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Compute the element's residual Vector and the jacobian matrix Plus the mass matrix especially for eigenvalue problems.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
double u (const unsigned &l, const unsigned &i)
local velocities
double x (const unsigned &l, const unsigned &i)
local position
Public Attributes
void(*&)(const double &t, const Vector< double > &x, Vector< double > &result) traction_fct_pt ()
Protected Member Functions
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (double time, const Vector< double > &x, Vector< double > &result)
Function to calculate the traction applied to the fluid.
void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Protected Attributes
double * Alpha_pt
Pointer to the angle alpha.
Data * Pext_data_pt
Pointer to the Data item that stores the external pressure.
unsigned External_data_number_of_Pext
The Data that contains the traded pressure is stored as external Data for the element. Which external Data item is it?
int Boundary
double Eta
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to an imposed traction function.
unsigned Dim
The highest dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PolarNavierStokesTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometery<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 57 of file polar_fluid_traction_elements.h.
Constructor & Destructor Documentation
PolarNavierStokesTractionElement()
template<class ELEMENT >
oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit
Definition at line 175 of file polar_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::PolarNavierStokesTractionElement< ELEMENT >::Traction_fct_pt.
 PolarNavierStokesTractionElement()
template<class ELEMENT >
oomph::PolarNavierStokesTractionElement< ELEMENT >::~PolarNavierStokesTractionElement () [inline]
Destructor should not delete anything.
Definition at line 222 of file polar_fluid_traction_elements.h.
Member Function Documentation
alpha()
template<class ELEMENT >
const double& oomph::PolarNavierStokesTractionElement< ELEMENT >::alpha () const [inline]
Alpha.
Definition at line 144 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::Alpha_pt.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
alpha_pt()
template<class ELEMENT >
double* & oomph::PolarNavierStokesTractionElement< ELEMENT >::alpha_pt () [inline]
Pointer to Alpha.
Definition at line 147 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::Alpha_pt.
boundary()
template<class ELEMENT >
const int oomph::PolarNavierStokesTractionElement< ELEMENT >::boundary () const [inline]
Boundary.
Definition at line 162 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::Boundary.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 239 of file polar_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix Plus the mass matrix especially for eigenvalue problems.
Reimplemented from oomph::GeneralisedElement.
Definition at line 248 of file polar_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 230 of file polar_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
fill_in_generic_residual_contribution()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Function that returns the residuals for the imposed traction Navier_Stokes equations The additional residual for the mass flux (ie. the extra equation for pext) This is an integral equation along the whole boundary It lies outside the loop over shape functions above
Definition at line 287 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::alpha(), oomph::PolarNavierStokesTractionElement< ELEMENT >::boundary(), oomph::PolarNavierStokesTractionElement< ELEMENT >::Dim, oomph::GeneralisedElement::external_local_eqn(), oomph::PolarNavierStokesTractionElement< ELEMENT >::get_eta(), oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::PolarNavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::PolarNavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::Data::value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction(), and oomph::PolarNavierStokesTractionElement< ELEMENT >::x().
get_eta()
template<class ELEMENT >
const double oomph::PolarNavierStokesTractionElement< ELEMENT >::get_eta () const [inline]
Eta.
Definition at line 168 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::Eta.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
get_traction()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction (double time, const Vector< double > & x, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 99 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::Dim, oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), i, oomph::PolarNavierStokesTractionElement< ELEMENT >::Traction_fct_pt, and oomph::PolarNavierStokesTractionElement< ELEMENT >::x().
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
output() [1/2]
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 257 of file polar_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 260 of file polar_fluid_traction_elements.h.
References oomph::FiniteElement::output().
set_boundary()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::set_boundary (int bound) [inline]
Function to set boundary.
Definition at line 165 of file polar_fluid_traction_elements.h.
set_eta()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::set_eta (double eta) [inline]
Function to set Eta.
Definition at line 171 of file polar_fluid_traction_elements.h.
set_external_pressure_data()
template<class ELEMENT >
void oomph::PolarNavierStokesTractionElement< ELEMENT >::set_external_pressure_data (Data * pext_data_pt) [inline]
Function for setting up external pressure.
Definition at line 150 of file polar_fluid_traction_elements.h.
References oomph::GeneralisedElement::add_external_data().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::PolarNavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 83 of file polar_fluid_traction_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
u()
template<class ELEMENT >
double oomph::PolarNavierStokesTractionElement< ELEMENT >::u (const unsigned & l, const unsigned & i) [inline]
local velocities
Definition at line 264 of file polar_fluid_traction_elements.h.
References oomph::FiniteElement::nodal_value().
u_local_eqn()
template<class ELEMENT >
virtual int oomph::PolarNavierStokesTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 78 of file polar_fluid_traction_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution().
x()
template<class ELEMENT >
double oomph::PolarNavierStokesTractionElement< ELEMENT >::x (const unsigned & l, const unsigned & i) [inline]
local position
Definition at line 268 of file polar_fluid_traction_elements.h.
References oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), and oomph::FiniteElement::nodal_position().
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction().
Member Data Documentation
Alpha_pt
template<class ELEMENT >
double* oomph::PolarNavierStokesTractionElement< ELEMENT >::Alpha_pt [protected]
Pointer to the angle alpha.
Definition at line 123 of file polar_fluid_traction_elements.h.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::alpha(), and oomph::PolarNavierStokesTractionElement< ELEMENT >::alpha_pt().
Boundary
template<class ELEMENT >
int oomph::PolarNavierStokesTractionElement< ELEMENT >::Boundary [protected]
Definition at line 136 of file polar_fluid_traction_elements.h.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::boundary().
Dim
template<class ELEMENT >
unsigned oomph::PolarNavierStokesTractionElement< ELEMENT >::Dim [private]
The highest dimension of the problem.
Definition at line 68 of file polar_fluid_traction_elements.h.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), and oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction().
Eta
template<class ELEMENT >
double oomph::PolarNavierStokesTractionElement< ELEMENT >::Eta [protected]
Definition at line 139 of file polar_fluid_traction_elements.h.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::get_eta().
External_data_number_of_Pext
template<class ELEMENT >
unsigned oomph::PolarNavierStokesTractionElement< ELEMENT >::External_data_number_of_Pext [protected]
The Data that contains the traded pressure is stored as external Data for the element. Which external Data item is it?
Definition at line 130 of file polar_fluid_traction_elements.h.
Pext_data_pt
template<class ELEMENT >
Data* oomph::PolarNavierStokesTractionElement< ELEMENT >::Pext_data_pt [protected]
Pointer to the Data item that stores the external pressure.
Definition at line 126 of file polar_fluid_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::PolarNavierStokesTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 64 of file polar_fluid_traction_elements.h.
Referenced by oomph::PolarNavierStokesTractionElement< ELEMENT >::get_traction(), and oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double& t, const Vector<double>& x, Vector<double>& result) oomph::PolarNavierStokesTractionElement< ELEMENT >::traction_fct_pt() [inline]
Definition at line 225 of file polar_fluid_traction_elements.h.
The documentation for this class was generated from the following file:
polar_fluid_traction_elements.h