oomph::THelmholtzElement< DIM, NNODE_1D > Class Template Reference
#include <Thelmholtz_elements.h>
Public Member Functions
THelmholtzElement ()
Constructor: Call constructors for TElement and Helmholtz equations.
THelmholtzElement (const THelmholtzElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 2
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::THelmholtzElement< DIM, NNODE_1D >
THelmholtzElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional Helmholtz elements with NNODE_1D nodal points along each element edge. Inherits from TElement and HelmholtzEquations
Definition at line 65 of file Thelmholtz_elements.h.
Constructor & Destructor Documentation
THelmholtzElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::THelmholtzElement< DIM, NNODE_1D >::THelmholtzElement () [inline]
Constructor: Call constructors for TElement and Helmholtz equations.
Definition at line 74 of file Thelmholtz_elements.h.
THelmholtzElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::THelmholtzElement< DIM, NNODE_1D >::THelmholtzElement (const THelmholtzElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 79 of file Thelmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::HelmholtzEquations< DIM >.
Definition at line 252 of file Thelmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz(), and oomph::THelmholtzElement< DIM, NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::HelmholtzEquations< DIM >.
Definition at line 217 of file Thelmholtz_elements.h.
References oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::THelmholtzElement< DIM, NNODE_1D >::output_fct().
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 176 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::get_flux(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::THelmholtzElement< DIM, NNODE_1D >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 169 of file Thelmholtz_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::THelmholtzElement< DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 172 of file Thelmholtz_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::THelmholtzElement< DIM, NNODE_1D >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 189 of file Thelmholtz_elements.h.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 101 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 108 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 116 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 124 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 132 of file Thelmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::THelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 141 of file Thelmholtz_elements.h.
References oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::THelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz(), oomph::HelmholtzEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::THelmholtzElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
Reimplemented from oomph::FiniteElement.
Definition at line 96 of file Thelmholtz_elements.h.
References oomph::THelmholtzElement< DIM, NNODE_1D >::Initial_Nvalue.
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node* oomph::THelmholtzElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 193 of file Thelmholtz_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::THelmholtzElement< DIM, NNODE_1D >::Initial_Nvalue = 2 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
(real and imag part) in every case
Definition at line 199 of file Thelmholtz_elements.h.
Referenced by oomph::THelmholtzElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
Thelmholtz_elements.h
Thelmholtz_elements.cc