oomph::PRefineableQPoissonElement< DIM > Class Template Reference
p-refineable version of 2D QPoissonElement elements
#include <refineable_poisson_elements.h>
Public Member Functions
PRefineableQPoissonElement ()
Constructor, simply call the other constructors.
~PRefineableQPoissonElement ()
Destructor (to avoid memory leaks)
PRefineableQPoissonElement (const PRefineableQPoissonElement< DIM > &dummy)
Broken copy constructor.
void operator= (const PRefineableQPoissonElement< DIM > &)
Broken assignment operator.
void further_build ()
Further build: Copy source function pointer from father element.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation:
void compute_energy_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double &error, double &norm)
Get error against and norm of exact solution.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PRefineableQPoissonElement< DIM >
p-refineable version of 2D QPoissonElement elements
Definition at line 249 of file refineable_poisson_elements.h.
Constructor & Destructor Documentation
PRefineableQPoissonElement() [1/2]
template<unsigned DIM>
oomph::PRefineableQPoissonElement< DIM >::PRefineableQPoissonElement () [inline]
Constructor, simply call the other constructors.
Definition at line 256 of file refineable_poisson_elements.h.
References oomph::FiniteElement::set_integration_scheme().
 PRefineableQPoissonElement()
template<unsigned DIM>
oomph::PRefineableQPoissonElement< DIM >::~PRefineableQPoissonElement () [inline]
Destructor (to avoid memory leaks)
Definition at line 268 of file refineable_poisson_elements.h.
References oomph::FiniteElement::integral_pt().
PRefineableQPoissonElement() [2/2]
template<unsigned DIM>
oomph::PRefineableQPoissonElement< DIM >::PRefineableQPoissonElement (const PRefineableQPoissonElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 275 of file refineable_poisson_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_energy_error()
template<unsigned DIM>
void oomph::PRefineableQPoissonElement< DIM >::compute_energy_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double & error, double & norm)
Get error against and norm of exact solution.
Definition at line 534 of file refineable_poisson_elements.cc.
References oomph::PoissonEquations< DIM >::get_flux(), i, s, and oomph::QuadTreeNames::W.
further_build()
template<unsigned DIM>
void oomph::PRefineableQPoissonElement< DIM >::further_build () [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineablePoissonEquations< DIM >.
Definition at line 618 of file refineable_poisson_elements.cc.
References oomph::RefineablePoissonEquations< DIM >::further_build().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::PRefineableQPoissonElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 289 of file refineable_poisson_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::PRefineableQPoissonElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation:
Same order as shape functions. - Constant recovery order, since recovery order of the first element is used for the whole mesh.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 308 of file refineable_poisson_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::PRefineableQPoissonElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 292 of file refineable_poisson_elements.h.
References oomph::FiniteElement::nvertex_node().
operator=()
template<unsigned DIM>
void oomph::PRefineableQPoissonElement< DIM >::operator= (const PRefineableQPoissonElement< DIM > &) [inline]
Broken assignment operator.
Definition at line 281 of file refineable_poisson_elements.h.
References oomph::BrokenCopy::broken_assign(), and oomph::RefineablePoissonEquations< DIM >::further_build().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::PRefineableQPoissonElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 296 of file refineable_poisson_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following files:
refineable_poisson_elements.h
refineable_poisson_elements.cc