oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT > Class Template Reference
Class that makes the finite element specified as template argument projectable -- on the assumption that all fields are interpolated by isoparametric Lagrange interpolation between the nodes.
#include <face_mesh_project.h>
Public Member Functions
GenericLagrangeInterpolatedProjectableElement ()
Constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Nodal value of boundary coordinate.
void set_boundary_id (const unsigned &boundary_id)
Boundary id.
unsigned boundary_id () const
Boundary id.
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field (includes current value!). Extract from first node but assume it's the same for all.
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!). Extract from first node but assume it's the same for all.
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld. Assumed to be the local nodal equation.
Private Attributes
unsigned Boundary_id
Boundary id.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >
Class that makes the finite element specified as template argument projectable -- on the assumption that all fields are interpolated by isoparametric Lagrange interpolation between the nodes.
Definition at line 50 of file face_mesh_project.h.
Constructor & Destructor Documentation
GenericLagrangeInterpolatedProjectableElement()
template<class ELEMENT >
oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::GenericLagrangeInterpolatedProjectableElement () [inline]
Constructor.
Definition at line 57 of file face_mesh_project.h.
References oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::Boundary_id.
Member Function Documentation
boundary_id()
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::boundary_id () const [inline]
Boundary id.
Definition at line 97 of file face_mesh_project.h.
References oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::Boundary_id.
Referenced by oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::set_boundary_id().
data_values_of_field()
template<class ELEMENT >
Vector<std::pair<Data*,unsigned> > oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 117 of file face_mesh_project.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class ELEMENT >
double oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 171 of file face_mesh_project.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class ELEMENT >
double oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 159 of file face_mesh_project.h.
References oomph::FiniteElement::J_eulerian(), and oomph::FiniteElement::shape().
local_equation()
template<class ELEMENT >
int oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld. Assumed to be the local nodal equation.
Implements oomph::ProjectableElementBase.
Definition at line 202 of file face_mesh_project.h.
References oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected.
Implements oomph::ProjectableElementBase.
Definition at line 135 of file face_mesh_project.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
nhistory_values_for_coordinate_projection()
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!). Extract from first node but assume it's the same for all.
Implements oomph::ProjectableElementBase.
Definition at line 151 of file face_mesh_project.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field (includes current value!). Extract from first node but assume it's the same for all.
Implements oomph::ProjectableElementBase.
Definition at line 143 of file face_mesh_project.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 194 of file face_mesh_project.h.
References oomph::FiniteElement::nnode().
set_boundary_id()
template<class ELEMENT >
void oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::set_boundary_id (const unsigned & boundary_id) [inline]
Boundary id.
Definition at line 91 of file face_mesh_project.h.
References oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::boundary_id(), and oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::Boundary_id.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection().
zeta_nodal()
template<class ELEMENT >
double oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Nodal value of boundary coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 63 of file face_mesh_project.h.
References oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::Boundary_id, oomph::FiniteElement::dim(), oomph::Node::get_coordinates_on_boundary(), i, and oomph::FiniteElement::node_pt().
Member Data Documentation
Boundary_id
template<class ELEMENT >
unsigned oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::Boundary_id [private]
Boundary id.
Definition at line 212 of file face_mesh_project.h.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::boundary_id(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::GenericLagrangeInterpolatedProjectableElement(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::set_boundary_id(), and oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::zeta_nodal().
The documentation for this class was generated from the following file:
face_mesh_project.h