oomph::PMLElementBase< DIM > Class Template Reference
Base class for elements with pml capabilities.
#include <pml_elements.h>
Public Member Functions
PMLElementBase ()
Constructor.
virtual ~PMLElementBase ()
Virtual destructor.
virtual void disable_pml ()
Disable pml.
virtual void enable_pml ()
Enable pml.
virtual void pml_transformation_jacobian (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseComplexMatrix &jacobian)=0
virtual void pml_transformation_jacobian (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseComplexMatrix &jacobian_matrix, Vector< std::complex< double > > &transformed_x)=0
virtual void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)=0
Pure virtual function in which we have to specify the values to be pinned (and set to zero) on the outer edge of the pml layer. This is usually all of the nodal values (values 0 and 1 (real and imag part) for Helmholtz; values 0,1,2 and 3 (real and imag part of x- and y-displacement for 2D time-harmonic linear elasticity; etc.). Vector must be resized internally!
virtual double wavenumber () const
template<>
void compute_laplace_matrix_and_det (const DenseComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_jacobian_inverse_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &J_inv, std::complex< double > &J_det)
template<>
void compute_laplace_matrix_and_det (const DenseComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_jacobian_inverse_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &J_inv, std::complex< double > &J_det)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_laplace_matrix_and_det (const DenseComplexMatrix &J, DenseComplexMatrix &laplace_matrix, std::complex< double > &detJ)
template<>
void compute_jacobian_inverse_and_det (const DiagonalComplexMatrix &J, DiagonalComplexMatrix &J_inv, std::complex< double > &J_det)
Static Public Member Functions
static void compute_laplace_matrix_and_det (const DenseComplexMatrix &jacobian, DenseComplexMatrix &laplace_matrix, std::complex< double > &jacobian_det)
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
static void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &jacobian, DiagonalComplexMatrix &laplace_matrix, std::complex< double > &jacobian_det)
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for diagonal matrix jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
static void compute_laplace_matrix_and_det (const DiagonalComplexMatrix &jacobian, DenseComplexMatrix &laplace_matrix, std::complex< double > &jacobian_det)
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for diagonal matrix jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
static void compute_jacobian_inverse_and_det (const DiagonalComplexMatrix &jacobian, DiagonalComplexMatrix &jacobian_inverse, std::complex< double > &jacobian_det)
Computes the inverse J^-1 and determinant |J| of a Jacobian J.
Protected Attributes
bool Pml_is_enabled
Boolean indicating if element is used in pml mode.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PMLElementBase< DIM >
Base class for elements with pml capabilities.
Definition at line 65 of file pml_elements.h.
Constructor & Destructor Documentation
PMLElementBase()
template<unsigned DIM>
oomph::PMLElementBase< DIM >::PMLElementBase () [inline]
Constructor.
Definition at line 71 of file pml_elements.h.
 PMLElementBase()
template<unsigned DIM>
virtual oomph::PMLElementBase< DIM >::~PMLElementBase () [inline], [virtual]
Virtual destructor.
Definition at line 74 of file pml_elements.h.
Member Function Documentation
compute_jacobian_inverse_and_det() [1/4]
template<>
void oomph::PMLElementBase< 1 >::compute_jacobian_inverse_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & J_inv, std::complex< double > & J_det)
Definition at line 94 of file pml_elements.cc.
compute_jacobian_inverse_and_det() [2/4]
template<unsigned DIM>
static void oomph::PMLElementBase< DIM >::compute_jacobian_inverse_and_det (const DiagonalComplexMatrix & jacobian, DiagonalComplexMatrix & jacobian_inverse, std::complex< double > & jacobian_det) [static]
Computes the inverse J^-1 and determinant |J| of a Jacobian J.
Referenced by oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det().
compute_jacobian_inverse_and_det() [3/4]
template<>
void oomph::PMLElementBase< 2 >::compute_jacobian_inverse_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & J_inv, std::complex< double > & J_det)
Definition at line 172 of file pml_elements.cc.
compute_jacobian_inverse_and_det() [4/4]
template<>
void oomph::PMLElementBase< 3 >::compute_jacobian_inverse_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & J_inv, std::complex< double > & J_det)
Definition at line 245 of file pml_elements.cc.
compute_laplace_matrix_and_det() [1/12]
template<>
void oomph::PMLElementBase< 1 >::compute_laplace_matrix_and_det (const DenseComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 39 of file pml_elements.cc.
compute_laplace_matrix_and_det() [2/12]
template<>
void oomph::PMLElementBase< 1 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 62 of file pml_elements.cc.
compute_laplace_matrix_and_det() [3/12]
template<>
void oomph::PMLElementBase< 1 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 78 of file pml_elements.cc.
compute_laplace_matrix_and_det() [4/12]
template<>
void oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det (const DenseComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 110 of file pml_elements.cc.
compute_laplace_matrix_and_det() [5/12]
template<unsigned DIM>
static void oomph::PMLElementBase< DIM >::compute_laplace_matrix_and_det (const DenseComplexMatrix & jacobian, DenseComplexMatrix & laplace_matrix, std::complex< double > & jacobian_det) [static]
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
Referenced by oomph::PMLElementBase< 2 >::compute_jacobian_inverse_and_det(), and oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det().
compute_laplace_matrix_and_det() [6/12]
template<unsigned DIM>
static void oomph::PMLElementBase< DIM >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & jacobian, DiagonalComplexMatrix & laplace_matrix, std::complex< double > & jacobian_det) [static]
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for diagonal matrix jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
compute_laplace_matrix_and_det() [7/12]
template<>
void oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 138 of file pml_elements.cc.
compute_laplace_matrix_and_det() [8/12]
template<unsigned DIM>
static void oomph::PMLElementBase< DIM >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & jacobian, DenseComplexMatrix & laplace_matrix, std::complex< double > & jacobian_det) [static]
Computes laplace matrix (JJ^T)^-1|J| and determinant |J| for diagonal matrix jacobian J. Laplace matrix is so named because it appears as the factor when the Laplace operator is transformed.
compute_laplace_matrix_and_det() [9/12]
template<>
void oomph::PMLElementBase< 2 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 155 of file pml_elements.cc.
compute_laplace_matrix_and_det() [10/12]
template<>
void oomph::PMLElementBase< 3 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DiagonalComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 190 of file pml_elements.cc.
compute_laplace_matrix_and_det() [11/12]
template<>
void oomph::PMLElementBase< 3 >::compute_laplace_matrix_and_det (const DiagonalComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 208 of file pml_elements.cc.
compute_laplace_matrix_and_det() [12/12]
template<>
void oomph::PMLElementBase< 3 >::compute_laplace_matrix_and_det (const DenseComplexMatrix & J, DenseComplexMatrix & laplace_matrix, std::complex< double > & detJ)
Definition at line 226 of file pml_elements.cc.
disable_pml()
template<unsigned DIM>
virtual void oomph::PMLElementBase< DIM >::disable_pml () [inline], [virtual]
Disable pml.
Reimplemented in oomph::AxisAlignedPMLElement< DIM >.
Definition at line 77 of file pml_elements.h.
Referenced by oomph::AxisAlignedPMLElement< DIM >::disable_pml().
enable_pml()
template<unsigned DIM>
virtual void oomph::PMLElementBase< DIM >::enable_pml () [inline], [virtual]
Enable pml.
Definition at line 83 of file pml_elements.h.
Referenced by oomph::AxisAlignedPMLElement< DIM >::enable_pml(), oomph::AnnularFromCartesianPMLElement::enable_pml(), oomph::AnnularFromLocalCoordinatePMLElement::enable_pml(), oomph::Conformal2DPMLElement::enable_pml(), oomph::TangentiallyVaryingConformal2DPMLElement::enable_pml(), and oomph::TangentiallyDiscontinuousConformal2DPMLElement::enable_pml().
pml_transformation_jacobian() [1/2]
template<unsigned DIM>
virtual void oomph::PMLElementBase< DIM >::pml_transformation_jacobian (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseComplexMatrix & jacobian) [pure virtual]
Implemented in oomph::TangentiallyDiscontinuousConformal2DPMLElement, oomph::TangentiallyVaryingConformal2DPMLElement, oomph::Conformal2DPMLElement, oomph::AnnularPMLElementBase, and oomph::AxisAlignedPMLElement< DIM >.
pml_transformation_jacobian() [2/2]
template<unsigned DIM>
virtual void oomph::PMLElementBase< DIM >::pml_transformation_jacobian (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseComplexMatrix & jacobian_matrix, Vector< std::complex< double > > & transformed_x) [pure virtual]
Implemented in oomph::TangentiallyDiscontinuousConformal2DPMLElement, oomph::TangentiallyVaryingConformal2DPMLElement, oomph::Conformal2DPMLElement, oomph::AnnularPMLElementBase, and oomph::AxisAlignedPMLElement< DIM >.
values_to_be_pinned_on_outer_pml_boundary()
template<unsigned DIM>
virtual void oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [pure virtual]
Pure virtual function in which we have to specify the values to be pinned (and set to zero) on the outer edge of the pml layer. This is usually all of the nodal values (values 0 and 1 (real and imag part) for Helmholtz; values 0,1,2 and 3 (real and imag part of x- and y-displacement for 2D time-harmonic linear elasticity; etc.). Vector must be resized internally!
Referenced by oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_pml_mesh(), and oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh().
wavenumber()
template<unsigned DIM>
virtual double oomph::PMLElementBase< DIM >::wavenumber () const [inline], [virtual]
Definition at line 113 of file pml_elements.h.
Member Data Documentation
Pml_is_enabled
template<unsigned DIM>
bool oomph::PMLElementBase< DIM >::Pml_is_enabled [protected]
Boolean indicating if element is used in pml mode.
Definition at line 153 of file pml_elements.h.
The documentation for this class was generated from the following file:
pml_elements.h