oomph::LineFluidInterfaceBoundingElement Class Reference
Specialisation of the interface boundary constraint to a line.
#include <interface_elements.h>
Public Member Functions
LineFluidInterfaceBoundingElement ()
Constructor.
Protected Member Functions
void fill_in_generic_residual_contribution_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Overload the helper function to calculate the residuals and (if flag==true) the Jacobian -- this function only deals with the part of the Jacobian that can be handled generically. Specific additional contributions may be provided in add_additional_residual_contributions_interface_boundary()
Additional Inherited Members
Detailed Description
Specialisation of the interface boundary constraint to a line.
Definition at line 289 of file interface_elements.h.
Constructor & Destructor Documentation
LineFluidInterfaceBoundingElement()
oomph::LineFluidInterfaceBoundingElement::LineFluidInterfaceBoundingElement () [inline]
Constructor.
Definition at line 307 of file interface_elements.h.
Member Function Documentation
fill_in_generic_residual_contribution_interface_boundary()
void oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Overload the helper function to calculate the residuals and (if flag==true) the Jacobian -- this function only deals with the part of the Jacobian that can be handled generically. Specific additional contributions may be provided in add_additional_residual_contributions_interface_boundary()
Add contribution to element's residual vector and Jacobian.
Implements oomph::FluidInterfaceBoundingElement.
Definition at line 238 of file interface_elements.cc.
References oomph::FluidInterfaceBoundingElement::add_additional_residual_contributions_interface_boundary(), oomph::FaceElement::bulk_element_pt(), oomph::FluidInterfaceBoundingElement::ca(), oomph::FluidInterfaceBoundingElement::contact_angle(), oomph::FluidInterfaceBoundingElement::Contact_angle_flag, oomph::FluidInterfaceElement::Default_Physical_Constant_Value, oomph::FiniteElement::dim(), oomph::VectorHelpers::dot(), oomph::FiniteElement::dshape_local(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FluidInterfaceElement::interpolated_u(), oomph::FluidInterfaceBoundingElement::kinematic_local_eqn(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::FluidInterfaceBoundingElement::U_index_interface_boundary, oomph::QuadTreeNames::W, oomph::FluidInterfaceBoundingElement::wall_unit_normal(), and oomph::Integral::weight().
Referenced by oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary().
The documentation for this class was generated from the following files:
interface_elements.h
interface_elements.cc