oomph::HelmholtzFGMRESMG< MATRIX > Class Template Reference
The FGMRES method, i.e. the flexible variant of the GMRES method which allows for nonconstant preconditioners [see Saad Y, `Iterative methods for sparse linear systems`, p.287]. Note, FGMRES can only cater to right preconditioning; if the user tries to switch to left preconditioning they will be notified of this.
#include <complex_smoother.h>
Public Member Functions
HelmholtzFGMRESMG ()
Constructor (empty)
virtual ~HelmholtzFGMRESMG ()
Destructor (cleanup storage)
HelmholtzFGMRESMG (const HelmholtzFGMRESMG &)
Broken copy constructor.
void operator= (const HelmholtzFGMRESMG &)
Broken assignment operator.
void set_preconditioner_LHS ()
Overloaded function to let the user know that left preconditioning is not possible with FGMRES, only right preconditioning.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Private Member Functions
void solve_helper (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
General interface to solve function.
void update (const unsigned &k, const Vector< Vector< std::complex< double > > > &hessenberg, const Vector< std::complex< double > > &s, const Vector< Vector< DoubleVector > > &z_m, Vector< DoubleVector > &x)
Helper function to update the result vector.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::HelmholtzFGMRESMG< MATRIX >
The FGMRES method, i.e. the flexible variant of the GMRES method which allows for nonconstant preconditioners [see Saad Y, `Iterative methods for sparse linear systems`, p.287]. Note, FGMRES can only cater to right preconditioning; if the user tries to switch to left preconditioning they will be notified of this.
Definition at line 3285 of file complex_smoother.h.
Constructor & Destructor Documentation
HelmholtzFGMRESMG() [1/2]
template<typename MATRIX >
oomph::HelmholtzFGMRESMG< MATRIX >::HelmholtzFGMRESMG () [inline]
Constructor (empty)
Definition at line 3291 of file complex_smoother.h.
 HelmholtzFGMRESMG()
template<typename MATRIX >
virtual oomph::HelmholtzFGMRESMG< MATRIX >::~HelmholtzFGMRESMG () [inline], [virtual]
Destructor (cleanup storage)
Definition at line 3298 of file complex_smoother.h.
References oomph::LinearSolver::clean_up_memory().
HelmholtzFGMRESMG() [2/2]
template<typename MATRIX >
oomph::HelmholtzFGMRESMG< MATRIX >::HelmholtzFGMRESMG (const HelmholtzFGMRESMG< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 3305 of file complex_smoother.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<typename MATRIX >
void oomph::HelmholtzFGMRESMG< MATRIX >::operator= (const HelmholtzFGMRESMG< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 3311 of file complex_smoother.h.
References oomph::BrokenCopy::broken_assign().
set_preconditioner_LHS()
template<typename MATRIX >
void oomph::HelmholtzFGMRESMG< MATRIX >::set_preconditioner_LHS () [inline]
Overloaded function to let the user know that left preconditioning is not possible with FGMRES, only right preconditioning.
Definition at line 3318 of file complex_smoother.h.
solve()
template<typename MATRIX >
void oomph::HelmholtzFGMRESMG< MATRIX >::solve (Problem *const & problem_pt, DoubleVector & result) [inline], [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Reimplemented from oomph::HelmholtzGMRESMG< MATRIX >.
Definition at line 3337 of file complex_smoother.h.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DoubleVector::built(), oomph::LinearSolver::clean_up_memory(), oomph::MPI_Helpers::communicator_pt(), oomph::Problem::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::Problem::get_jacobian(), i, oomph::IterativeLinearSolver::Jacobian_setup_time, oomph::Problem::mesh_pt(), oomph::Problem::ndof(), oomph::oomph_info, oomph::DoubleVector::redistribute(), and oomph::TimingHelpers::timer().
solve_helper()
template<typename MATRIX >
void oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [private]
General interface to solve function.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. based on the algorithm presented in Templates for the Solution of Linear Systems: Building Blocks for Iterative Methods, Barrett, Berry et al, SIAM, 2006 and the implementation in the IML++ library : http://math.nist.gov/iml++/
Definition at line 3603 of file complex_smoother.h.
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::HelmholtzSmoother::complex_matrix_multiplication(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, i, oomph::DoubleVector::initialise(), oomph::IterativeLinearSolver::Max_iter, oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, oomph::IterativeLinearSolver::preconditioner_pt(), oomph::IterativeLinearSolver::Preconditioner_setup_time, oomph::Preconditioner::preconditioner_solve(), s, oomph::Preconditioner::setup(), oomph::IterativeLinearSolver::Setup_preconditioner_before_solve, oomph::IterativeLinearSolver::Solution_time, oomph::Global_string_for_annotation::string(), oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), and oomph::IterativeLinearSolver::Tolerance.
Referenced by oomph::HelmholtzFGMRESMG< MATRIX >::update().
update()
template<typename MATRIX >
void oomph::HelmholtzFGMRESMG< MATRIX >::update (const unsigned & k, const Vector< Vector< std::complex< double > > > & hessenberg, const Vector< std::complex< double > > & s, const Vector< Vector< DoubleVector > > & z_m, Vector< DoubleVector > & x) [inline], [private]
Helper function to update the result vector.
Definition at line 3499 of file complex_smoother.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), i, s, and oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper().
The documentation for this class was generated from the following file:
complex_smoother.h