oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT > Class Template Reference
#include <fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h>
Public Member Functions
FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
const double & q () const
Return the ratio of the stress scales used to non-dimensionalise the fluid and elasticity equations. E.g. $ Q = (\omega a)^2 \rho/E $, i.e. the ratio between the inertial fluid stress and the solid's elastic modulus E.
double *& q_pt ()
Return a pointer the ratio of stress scales used to non-dimensionalise the fluid and solid equations.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: Plot traction etc at Gauss points nplot is ignored.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
void fill_in_contribution_to_residuals_helmholtz_traction (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
double * Q_pt
Pointer to the ratio, $ Q $ , of the stress used to non-dimensionalise the fluid stresses to the stress used to non-dimensionalise the solid stresses.
Vector< std::complex< unsigned > > U_index_fourier_decomposed_time_harmonic_linear_elasticity_helmholtz_traction
Index at which the i-th displacement component is stored.
Static Protected Attributes
static double Default_Q_Value =1.0
Static default value for the ratio of stress scales used in the fluid and solid equations (default is 1.0)
Additional Inherited Members
Detailed Description
template<class ELASTICITY_BULK_ELEMENT, class HELMHOLTZ_BULK_ELEMENT>
class oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >
A class for elements that allow the imposition of an applied traction in the equations of time-harmonic linear elasticity from a Helmholtz potential (interpreted as a displacement potential for the fluid in a quasi-steady, linearised FSI problem.) The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 54 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Constructor & Destructor Documentation
FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 86 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::has_hanging_nodes(), i, oomph::FiniteElement::nodal_dimension(), oomph::ElementWithExternalElement::set_ninteraction(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::U_index_fourier_decomposed_time_harmonic_linear_elasticity_helmholtz_traction.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 150 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), and oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd().
fill_in_contribution_to_residuals()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 142 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction().
fill_in_contribution_to_residuals_helmholtz_traction()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals.
Definition at line 269 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FiniteElement::dshape_local_at_knot(), oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::U_index_fourier_decomposed_time_harmonic_linear_elasticity_helmholtz_traction, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output().
output() [1/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Dummy
Reimplemented from oomph::FiniteElement.
Definition at line 173 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output().
output() [2/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: Plot traction etc at Gauss points nplot is ignored.
Reimplemented from oomph::FiniteElement.
Definition at line 182 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_zeta(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q().
output() [3/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 239 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::output().
output() [4/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
void oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 243 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Default_Q_Value, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), and oomph::output().
q()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
const double& oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q () const [inline]
Return the ratio of the stress scales used to non-dimensionalise the fluid and elasticity equations. E.g. $ Q = (\omega a)^2 \rho/E $, i.e. the ratio between the inertial fluid stress and the solid's elastic modulus E.
Definition at line 165 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt.
Referenced by oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output().
q_pt()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
double* & oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q_pt () [inline]
Return a pointer the ratio of stress scales used to non-dimensionalise the fluid and solid equations.
Definition at line 169 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt.
Member Data Documentation
Default_Q_Value
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
double oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Default_Q_Value =1.0 [static], [protected]
Static default value for the ratio of stress scales used in the fluid and solid equations (default is 1.0)
Static default value for the ratio of stress scales used in the fluid and solid equations (default is 1.0)
Definition at line 69 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output().
Q_pt
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
double* oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt [protected]
Pointer to the ratio, $ Q $ , of the stress used to non-dimensionalise the fluid stresses to the stress used to non-dimensionalise the solid stresses.
Definition at line 65 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q_pt().
U_index_fourier_decomposed_time_harmonic_linear_elasticity_helmholtz_traction
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT >
Vector<std::complex<unsigned> > oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::U_index_fourier_decomposed_time_harmonic_linear_elasticity_helmholtz_traction [protected]
Index at which the i-th displacement component is stored.
Definition at line 73 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), and oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement().
The documentation for this class was generated from the following file:
fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h