oomph::DoubleMatrixBase Class Reference
Abstract base class for matrices of doubles -- adds abstract interfaces for solving, LU decomposition and multiplication by vectors.
#include <matrices.h>
Public Member Functions
DoubleMatrixBase ()
(Empty) constructor.
DoubleMatrixBase (const DoubleMatrixBase &matrix)
Broken copy constructor.
void operator= (const DoubleMatrixBase &)
Broken assignment operator.
virtual unsigned long nrow () const =0
Return the number of rows of the matrix.
virtual unsigned long ncol () const =0
Return the number of columns of the matrix.
virtual ~DoubleMatrixBase ()
virtual (empty) destructor
virtual double operator() (const unsigned long &i, const unsigned long &j) const =0
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
void solve (DoubleVector &rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written.
void solve (const DoubleVector &rhs, DoubleVector &soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten.
void solve (Vector< double > &rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written.
void solve (const Vector< double > &rhs, Vector< double > &soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten.
virtual void residual (const DoubleVector &x, const DoubleVector &b, DoubleVector &residual_)
Find the residual, i.e. r=b-Ax the residual.
virtual double max_residual (const DoubleVector &x, const DoubleVector &rhs)
Find the maximum residual r=b-Ax -- generic version, can be overloaded for specific derived classes where the max. can be determined `on the fly`.
virtual void multiply (const DoubleVector &x, DoubleVector &soln) const =0
Multiply the matrix by the vector x: soln=Ax.
virtual void multiply_transpose (const DoubleVector &x, DoubleVector &soln) const =0
Multiply the transposed matrix by the vector x: soln=A^T x.
Protected Attributes
LinearSolver * Linear_solver_pt
LinearSolver * Default_linear_solver_pt
Detailed Description
Abstract base class for matrices of doubles -- adds abstract interfaces for solving, LU decomposition and multiplication by vectors.
Definition at line 275 of file matrices.h.
Constructor & Destructor Documentation
DoubleMatrixBase() [1/2]
oomph::DoubleMatrixBase::DoubleMatrixBase () [inline]
(Empty) constructor.
Definition at line 288 of file matrices.h.
DoubleMatrixBase() [2/2]
oomph::DoubleMatrixBase::DoubleMatrixBase (const DoubleMatrixBase & matrix) [inline]
Broken copy constructor.
Definition at line 291 of file matrices.h.
References oomph::BrokenCopy::broken_copy().
 DoubleMatrixBase()
virtual oomph::DoubleMatrixBase::~DoubleMatrixBase () [inline], [virtual]
virtual (empty) destructor
Definition at line 309 of file matrices.h.
References i, and oomph::Matrix< T, MATRIX_TYPE >::operator()().
Member Function Documentation
linear_solver_pt() [1/2]
LinearSolver* & oomph::DoubleMatrixBase::linear_solver_pt () [inline]
Return a pointer to the linear solver object.
Definition at line 319 of file matrices.h.
linear_solver_pt() [2/2]
LinearSolver* const& oomph::DoubleMatrixBase::linear_solver_pt () const [inline]
Return a pointer to the linear solver object (const version)
Definition at line 322 of file matrices.h.
max_residual()
virtual double oomph::DoubleMatrixBase::max_residual (const DoubleVector & x, const DoubleVector & rhs) [inline], [virtual]
Find the maximum residual r=b-Ax -- generic version, can be overloaded for specific derived classes where the max. can be determined `on the fly`.
Definition at line 364 of file matrices.h.
References oomph::DoubleVector::max(), and oomph::TrilinosEpetraHelpers::multiply().
multiply()
virtual void oomph::DoubleMatrixBase::multiply (const DoubleVector & x, DoubleVector & soln) const [pure virtual]
Multiply the matrix by the vector x: soln=Ax.
Implemented in oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, oomph::CRDoubleMatrix, and oomph::SumOfMatrices.
Referenced by oomph::SumOfMatrices::multiply(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), and oomph::GMRES< MATRIX >::solve_helper().
multiply_transpose()
virtual void oomph::DoubleMatrixBase::multiply_transpose (const DoubleVector & x, DoubleVector & soln) const [pure virtual]
Multiply the transposed matrix by the vector x: soln=A^T x.
Implemented in oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, oomph::CRDoubleMatrix, and oomph::SumOfMatrices.
ncol()
virtual unsigned long oomph::DoubleMatrixBase::ncol () const [pure virtual]
Return the number of columns of the matrix.
Implemented in oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, oomph::CRDoubleMatrix, and oomph::SumOfMatrices.
Referenced by oomph::SumOfMatrices::add_matrix(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::SumOfMatrices::ncol(), oomph::TrilinosPreconditionerBase::setup(), oomph::MumpsSolver::solve(), oomph::DenseLU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::SuperLUSolver::solve(), oomph::HypreSolver::solve(), oomph::CG< MATRIX >::solve_helper(), and oomph::BiCGStab< MATRIX >::solve_helper().
nrow()
virtual unsigned long oomph::DoubleMatrixBase::nrow () const [pure virtual]
Return the number of rows of the matrix.
Implemented in oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, oomph::CRDoubleMatrix, and oomph::SumOfMatrices.
Referenced by oomph::SumOfMatrices::add_matrix(), oomph::MumpsSolver::factorise(), oomph::DenseLU::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::SumOfMatrices::nrow(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::setup(), oomph::IdentityPreconditioner::setup(), oomph::MumpsSolver::solve(), oomph::DenseLU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::SuperLUSolver::solve(), oomph::HypreSolver::solve(), oomph::CG< MATRIX >::solve_helper(), and oomph::BiCGStab< MATRIX >::solve_helper().
operator()()
virtual double oomph::DoubleMatrixBase::operator() (const unsigned long & i, const unsigned long & j) const [pure virtual]
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
Implemented in oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, oomph::CRDoubleMatrix, and oomph::SumOfMatrices.
operator=()
void oomph::DoubleMatrixBase::operator= (const DoubleMatrixBase &) [inline]
Broken assignment operator.
Definition at line 297 of file matrices.h.
References oomph::BrokenCopy::broken_assign(), oomph::Matrix< T, MATRIX_TYPE >::ncol(), and oomph::Matrix< T, MATRIX_TYPE >::nrow().
residual()
virtual void oomph::DoubleMatrixBase::residual (const DoubleVector & x, const DoubleVector & b, DoubleVector & residual_) [inline], [virtual]
Find the residual, i.e. r=b-Ax the residual.
Definition at line 343 of file matrices.h.
References i, oomph::TrilinosEpetraHelpers::multiply(), oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleVector::values_pt().
Referenced by oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::DampedJacobi< MATRIX >::solve_helper().
solve() [1/4]
void oomph::DoubleMatrixBase::solve (DoubleVector & rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written.
Complete LU solve (overwrites RHS with solution). This is the generic version which should not need to be over-written.
Definition at line 55 of file matrices.cc.
References Linear_solver_pt, and oomph::LinearSolver::solve().
Referenced by oomph::Newmark< NSTEPS >::assign_initial_data_values(), oomph::Newmark< NSTEPS >::assign_initial_data_values_stage2(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), oomph::PVDEquationsBase< DIM >::get_principal_stress(), and oomph::FiniteElement::locate_zeta().
solve() [2/4]
void oomph::DoubleMatrixBase::solve (const DoubleVector & rhs, DoubleVector & soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten.
Complete LU solve (Nothing gets overwritten!). This generic version should never need to be overwritten
Definition at line 79 of file matrices.cc.
References Linear_solver_pt, and oomph::LinearSolver::solve().
solve() [3/4]
void oomph::DoubleMatrixBase::solve (Vector< double > & rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written.
Complete LU solve (overwrites RHS with solution). This is the generic version which should not need to be over-written.
Definition at line 98 of file matrices.cc.
References Linear_solver_pt, and oomph::LinearSolver::solve().
solve() [4/4]
void oomph::DoubleMatrixBase::solve (const Vector< double > & rhs, Vector< double > & soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten.
Complete LU solve (Nothing gets overwritten!). This generic version should never need to be overwritten
Definition at line 122 of file matrices.cc.
References Linear_solver_pt, and oomph::LinearSolver::solve().
Member Data Documentation
Default_linear_solver_pt
LinearSolver* oomph::DoubleMatrixBase::Default_linear_solver_pt [protected]
Definition at line 283 of file matrices.h.
Referenced by oomph::CRDoubleMatrix::build(), oomph::CCDoubleMatrix::CCDoubleMatrix(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::DenseDoubleMatrix::DenseDoubleMatrix(), oomph::CRDoubleMatrix::lubksub(), oomph::DenseDoubleMatrix::lubksub(), oomph::CCDoubleMatrix::lubksub(), oomph::CRDoubleMatrix::ludecompose(), oomph::DenseDoubleMatrix::ludecompose(), oomph::CCDoubleMatrix::ludecompose(), oomph::CCDoubleMatrix::~CCDoubleMatrix(), oomph::CRDoubleMatrix::~CRDoubleMatrix(), and oomph::DenseDoubleMatrix::~DenseDoubleMatrix().
Linear_solver_pt
LinearSolver* oomph::DoubleMatrixBase::Linear_solver_pt [protected]
Definition at line 280 of file matrices.h.
Referenced by oomph::CCDoubleMatrix::CCDoubleMatrix(), oomph::CRDoubleMatrix::clear(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::DenseDoubleMatrix::DenseDoubleMatrix(), and solve().
The documentation for this class was generated from the following files:
matrices.h
matrices.cc