oomph::RefineableHelmholtzEquations< DIM > Class Template Reference
#include <refineable_helmholtz_elements.h>
Public Member Functions
RefineableHelmholtzEquations ()
Constructor, simply call other constructors.
RefineableHelmholtzEquations (const RefineableHelmholtzEquations< DIM > &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from Helmholtz equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableHelmholtzEquations< DIM >
Refineable version of Helmholtz equations
Definition at line 63 of file refineable_helmholtz_elements.h.
Constructor & Destructor Documentation
RefineableHelmholtzEquations() [1/2]
template<unsigned DIM>
oomph::RefineableHelmholtzEquations< DIM >::RefineableHelmholtzEquations () [inline]
Constructor, simply call other constructors.
Definition at line 70 of file refineable_helmholtz_elements.h.
RefineableHelmholtzEquations() [2/2]
template<unsigned DIM>
oomph::RefineableHelmholtzEquations< DIM >::RefineableHelmholtzEquations (const RefineableHelmholtzEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 74 of file refineable_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_helmholtz()
template<unsigned DIM>
void oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 46 of file refineable_helmholtz_elements.cc.
References i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableHelmholtzEquations< DIM >::further_build().
further_build()
template<unsigned DIM>
void oomph::RefineableHelmholtzEquations< DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 161 of file refineable_helmholtz_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::HelmholtzEquations< DIM >::k_squared_pt(), oomph::HelmholtzEquations< DIM >::K_squared_pt, oomph::HelmholtzEquations< DIM >::source_fct_pt(), and oomph::HelmholtzEquations< DIM >::Source_fct_pt.
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 110 of file refineable_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::HelmholtzEquations< DIM >::u_index_helmholtz().
Referenced by oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 138 of file refineable_helmholtz_elements.h.
References oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), and oomph::Global_string_for_annotation::string().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableHelmholtzEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from Helmholtz equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 93 of file refineable_helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::get_flux(), and i.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableHelmholtzEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 90 of file refineable_helmholtz_elements.h.
The documentation for this class was generated from the following files:
refineable_helmholtz_elements.h
refineable_helmholtz_elements.cc