QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
QGeneralisedAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
#include <gen_axisym_advection_diffusion_elements.h>
Public Member Functions
QGeneralisedAxisymAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Detailed Description
template<unsigned NNODE_1D>
class QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >
QGeneralisedAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 607 of file gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QGeneralisedAxisymAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 623 of file gen_axisym_advection_diffusion_elements.h.
QGeneralisedAxisymAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 628 of file gen_axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff()
template<unsigned NNODE_1D>
double QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 759 of file gen_axisym_advection_diffusion_elements.h.
Referenced by QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_cons_axisym_adv_diff().
dshape_and_dtest_eulerian_cons_axisym_adv_diff()
template<unsigned NNODE_1D>
double QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 725 of file gen_axisym_advection_diffusion_elements.h.
References QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff(), and i.
Referenced by QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
output() [1/4]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile) [inline]
Output function: r,z,u.
Definition at line 647 of file gen_axisym_advection_diffusion_elements.h.
References oomph::output().
output() [2/4]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Output function: r,z,u at n_plot^2 plot points.
Definition at line 652 of file gen_axisym_advection_diffusion_elements.h.
References oomph::output().
output() [3/4]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt) [inline]
C-style output function: r,z,u.
Definition at line 658 of file gen_axisym_advection_diffusion_elements.h.
References oomph::output().
output() [4/4]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline]
C-style output function: r,z,u at n_plot^2 plot points.
Definition at line 665 of file gen_axisym_advection_diffusion_elements.h.
References oomph::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Definition at line 672 of file gen_axisym_advection_diffusion_elements.h.
References oomph::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Definition at line 682 of file gen_axisym_advection_diffusion_elements.h.
References oomph::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff(), oomph::dshape_and_dtest_eulerian_cons_axisym_adv_diff(), QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_cons_axisym_adv_diff(), oomph::output_fct(), and s.
required_nvalue()
template<unsigned NNODE_1D>
unsigned QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Definition at line 642 of file gen_axisym_advection_diffusion_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 616 of file gen_axisym_advection_diffusion_elements.h.
The documentation for this class was generated from the following file:
gen_axisym_advection_diffusion_elements.h