oomph::PMLHelmholtzEquationsBase< DIM > Class Template Reference
#include <pml_helmholtz_elements.h>
Public Types
typedef void(* PMLHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
PMLHelmholtzEquationsBase ()
Constructor.
PMLHelmholtzEquationsBase (const PMLHelmholtzEquationsBase &dummy)
Broken copy constructor.
virtual std::complex< unsigned > u_index_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to k_squared.
double k_squared () const
Get the square of wavenumber.
const double & alpha () const
Alpha, wavenumber complex shift.
double *& alpha_pt ()
Pointer to Alpha, wavenumber complex shift.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_total_real (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double &phi, const unsigned &nplot)
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
void compute_norm (double &norm)
Compute norm of fe solution.
PMLHelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PMLHelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
void get_flux (const Vector< double > &s, Vector< std::complex< double > > &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
std::complex< double > interpolated_u_pml_helmholtz (const Vector< double > &s) const
Return FE representation of function value u_helmholtz(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Attributes
double * Alpha_pt
Pointer to wavenumber complex shift.
PMLHelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to wave number (must be set!)
Static Protected Attributes
static double Default_Physical_Constant_Value = 0.0
Static default value for the physical constants (initialised to zero)
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PMLHelmholtzEquationsBase< DIM >
A class for all isoparametric elements that solve the Helmholtz equations with PMLs, but without any of the PML capability or depedence on a PML element template parameter
Definition at line 64 of file pml_helmholtz_elements.h.
Member Typedef Documentation
PMLHelmholtzSourceFctPt
template<unsigned DIM>
typedef void(* oomph::PMLHelmholtzEquationsBase< DIM >::PMLHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 71 of file pml_helmholtz_elements.h.
Constructor & Destructor Documentation
PMLHelmholtzEquationsBase() [1/2]
template<unsigned DIM>
oomph::PMLHelmholtzEquationsBase< DIM >::PMLHelmholtzEquationsBase () [inline]
Constructor.
Definition at line 75 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Alpha_pt, and oomph::PMLHelmholtzEquationsBase< DIM >::Default_Physical_Constant_Value.
PMLHelmholtzEquationsBase() [2/2]
template<unsigned DIM>
oomph::PMLHelmholtzEquationsBase< DIM >::PMLHelmholtzEquationsBase (const PMLHelmholtzEquationsBase< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 85 of file pml_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha()
template<unsigned DIM>
const double& oomph::PMLHelmholtzEquationsBase< DIM >::alpha () const [inline]
Alpha, wavenumber complex shift.
Definition at line 124 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Alpha_pt.
alpha_pt()
template<unsigned DIM>
double* & oomph::PMLHelmholtzEquationsBase< DIM >::alpha_pt () [inline]
Pointer to Alpha, wavenumber complex shift.
Definition at line 127 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Alpha_pt.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures().
compute_error() [1/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 731 of file pml_helmholtz_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output_fct().
compute_error() [2/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 383 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::compute_norm().
compute_norm()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 814 of file pml_helmholtz_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::compute_error().
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM>
virtual double oomph::PMLHelmholtzEquationsBase< DIM >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::get_dof_numbers_for_unknowns(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_fct().
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM>
virtual double oomph::PMLHelmholtzEquationsBase< DIM >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_fct().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Reimplemented from oomph::GeneralisedElement.
Definition at line 525 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::PMLHelmholtzEquationsBase< DIM >::dshape_and_dtest_eulerian_helmholtz(), oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), s, and oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz().
get_flux()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::get_flux (const Vector< double > & s, Vector< std::complex< double > > & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 438 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz().
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_Z2_flux(), and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::get_Z2_flux().
get_source_helmholtz()
template<unsigned DIM>
virtual void oomph::PMLHelmholtzEquationsBase< DIM >::get_source_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 408 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Source_fct_pt.
interpolated_u_pml_helmholtz()
template<unsigned DIM>
std::complex<double> oomph::PMLHelmholtzEquationsBase< DIM >::interpolated_u_pml_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u_helmholtz(s) at local coordinate s.
Definition at line 477 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::PMLHelmholtzEquationsBase< DIM >::self_test(), oomph::FiniteElement::shape(), and oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz().
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::scalar_value_paraview().
k_squared()
template<unsigned DIM>
double oomph::PMLHelmholtzEquationsBase< DIM >::k_squared () const [inline]
Get the square of wavenumber.
Definition at line 109 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::K_squared_pt.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), and oomph::PMLHelmholtzEquations< DIM, PML_ELEMENT >::wavenumber().
k_squared_pt()
template<unsigned DIM>
double*& oomph::PMLHelmholtzEquationsBase< DIM >::k_squared_pt () [inline]
Get pointer to k_squared.
Definition at line 106 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::K_squared_pt.
ndof_types()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquationsBase< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
Reimplemented from oomph::GeneralisedElement.
Definition at line 514 of file pml_helmholtz_elements.h.
nscalar_paraview()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquationsBase< DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 132 of file pml_helmholtz_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 287 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::output_imag(), oomph::PMLHelmholtzEquationsBase< DIM >::output_real(), and oomph::PMLHelmholtzEquationsBase< DIM >::output_total_real().
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
Output function:
x,y,u_re,u_imag or x,y,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 335 of file pml_helmholtz_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 325 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::output(), and oomph::PMLHelmholtzEquationsBase< DIM >::output_fct().
output() [4/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 520 of file pml_helmholtz_elements.cc.
References i, oomph::PMLHelmholtzEquationsBase< DIM >::output_fct(), and s.
output_fct() [1/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_re_exact,u_im_exact or x,y,z,u_re_exact,u_im_exact at n_plot^DIM plot points
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 567 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output().
output_fct() [2/2]
template<unsigned DIM>
virtual void oomph::PMLHelmholtzEquationsBase< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >, oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >.
Definition at line 342 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::compute_error(), oomph::PMLHelmholtzEquationsBase< DIM >::output_imag_fct(), and oomph::PMLHelmholtzEquationsBase< DIM >::output_real_fct().
output_imag()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_imag (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 482 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_imag().
output_imag_fct()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_imag_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent fct
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 676 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output_fct(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_imag_fct().
output_real()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 381 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_real().
output_real_fct()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 621 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output_fct(), and oomph::QPMLHelmholtzElement< 2, NNODE_1D, PML_ELEMENT >::output_real_fct().
output_total_real()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::output_total_real (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
Output function for real part of full time-dependent solution constructed by adding the scattered field
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 424 of file pml_helmholtz_elements.cc.
References i, and s.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::output().
scalar_name_paraview()
template<unsigned DIM>
std::string oomph::PMLHelmholtzEquationsBase< DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 254 of file pml_helmholtz_elements.h.
scalar_value_fct_paraview()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 190 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_paraview()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 139 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::PMLHelmholtzEquationsBase< DIM >::interpolated_u_pml_helmholtz(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquationsBase< DIM >::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 303 of file pml_helmholtz_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::interpolated_u_pml_helmholtz().
source_fct_pt() [1/2]
template<unsigned DIM>
PMLHelmholtzSourceFctPt& oomph::PMLHelmholtzEquationsBase< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 398 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Source_fct_pt.
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
PMLHelmholtzSourceFctPt oomph::PMLHelmholtzEquationsBase< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 401 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::Source_fct_pt.
u_index_helmholtz()
template<unsigned DIM>
virtual std::complex<unsigned> oomph::PMLHelmholtzEquationsBase< DIM >::u_index_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored.
Definition at line 102 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::PMLHelmholtzEquationsBase< DIM >::get_flux(), oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::get_interpolated_values(), oomph::PMLHelmholtzEquationsBase< DIM >::interpolated_u_pml_helmholtz(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::local_equation(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), and oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement().
values_to_be_pinned_on_outer_pml_boundary()
template<unsigned DIM>
void oomph::PMLHelmholtzEquationsBase< DIM >::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Definition at line 427 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM, PML_ELEMENT >::values_to_be_pinned_on_outer_pml_boundary().
Member Data Documentation
Alpha_pt
template<unsigned DIM>
double* oomph::PMLHelmholtzEquationsBase< DIM >::Alpha_pt [protected]
Pointer to wavenumber complex shift.
Definition at line 594 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::alpha(), oomph::PMLHelmholtzEquationsBase< DIM >::alpha_pt(), and oomph::PMLHelmholtzEquationsBase< DIM >::PMLHelmholtzEquationsBase().
Default_Physical_Constant_Value
template<unsigned DIM>
double oomph::PMLHelmholtzEquationsBase< DIM >::Default_Physical_Constant_Value = 0.0 [static], [protected]
Static default value for the physical constants (initialised to zero)
PML Helmholtz equations static data, so that by default we can point to a 0.
Definition at line 603 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::PMLHelmholtzEquationsBase().
K_squared_pt
template<unsigned DIM>
double* oomph::PMLHelmholtzEquationsBase< DIM >::K_squared_pt [protected]
Pointer to wave number (must be set!)
Definition at line 600 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquationsBase< DIM >::k_squared(), and oomph::PMLHelmholtzEquationsBase< DIM >::k_squared_pt().
Source_fct_pt
template<unsigned DIM>
PMLHelmholtzSourceFctPt oomph::PMLHelmholtzEquationsBase< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 597 of file pml_helmholtz_elements.h.
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::further_build(), oomph::PMLHelmholtzEquationsBase< DIM >::get_source_helmholtz(), and oomph::PMLHelmholtzEquationsBase< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
pml_helmholtz_elements.h
pml_helmholtz_elements.cc