oomph::GeompackQuadScaffoldMesh Class Reference
Mesh that is based on input files generated by the quadrilateral mesh generator Geompack.
#include <geompack_scaffold_mesh.h>
Public Member Functions
GeompackQuadScaffoldMesh ()
Empty constructor.
GeompackQuadScaffoldMesh (const std::string &mesh_file_name, const std::string &curve_file_name)
Constructor: Pass the filename of the mesh files.
GeompackQuadScaffoldMesh (const GeompackQuadScaffoldMesh &)
Broken copy constructor.
void operator= (const GeompackQuadScaffoldMesh &)
Broken assignment operator.
~GeompackQuadScaffoldMesh ()
Empty destructor.
Additional Inherited Members
Detailed Description
Mesh that is based on input files generated by the quadrilateral mesh generator Geompack.
Definition at line 43 of file geompack_scaffold_mesh.h.
Constructor & Destructor Documentation
GeompackQuadScaffoldMesh() [1/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh () [inline]
Empty constructor.
Definition at line 49 of file geompack_scaffold_mesh.h.
References oomph::Global_string_for_annotation::string().
GeompackQuadScaffoldMesh() [2/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh (const std::string & mesh_file_name, const std::string & curve_file_name)
Constructor: Pass the filename of the mesh files.
Definition at line 38 of file geompack_scaffold_mesh.cc.
References oomph::Mesh::add_boundary_node(), oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, oomph::Mesh::Node_pt, oomph::FiniteElement::node_pt(), oomph::oomph_info, and oomph::Mesh::set_nboundary().
GeompackQuadScaffoldMesh() [3/3]
oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh (const GeompackQuadScaffoldMesh &) [inline]
Broken copy constructor.
Definition at line 56 of file geompack_scaffold_mesh.h.
References oomph::BrokenCopy::broken_copy().
 GeompackQuadScaffoldMesh()
oomph::GeompackQuadScaffoldMesh::~GeompackQuadScaffoldMesh () [inline]
Empty destructor.
Definition at line 69 of file geompack_scaffold_mesh.h.
Member Function Documentation
operator=()
void oomph::GeompackQuadScaffoldMesh::operator= (const GeompackQuadScaffoldMesh &) [inline]
Broken assignment operator.
Definition at line 63 of file geompack_scaffold_mesh.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
geompack_scaffold_mesh.h
geompack_scaffold_mesh.cc