oomph::LinearisedAxisymmetricQCrouzeixRaviartElement Class Reference
#include <linearised_axisym_navier_stokes_elements.h>
Public Member Functions
LinearisedAxisymmetricQCrouzeixRaviartElement ()
Constructor: there are three internal values for each of the two pressure components.
virtual unsigned required_nvalue (const unsigned &n) const
Return number of values (pinned or dofs) required at local node n.
double p_linearised_axi_nst (const unsigned &i_internal, const unsigned &i) const
Return the pressure value i at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes)
unsigned npres_linearised_axi_nst () const
Return number of pressure values corresponding to a single pressure component.
void fix_pressure (const unsigned &p_dof, const double &pvalue)
Fix both components of the internal pressure degrees of freedom p_dof to pvalue.
int p_local_eqn (const unsigned &n, const unsigned &i)
Overload the access function for the i-th component of the pressure's local equation numbers.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
The number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Protected Member Functions
double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates at the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinate s.
Protected Attributes
Vector< unsigned > P_linearised_axi_nst_internal_index
Internal indices that indicate at which internal data the pressure values are stored. We note that there are two pressure values, corresponding to the functions P^C(r,z,t) and P^S(r,z,t) which multiply the cosine and sine terms respectively.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
Crouzeix-Raviart elements are Navier-Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation
Definition at line 476 of file linearised_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
LinearisedAxisymmetricQCrouzeixRaviartElement()
oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::LinearisedAxisymmetricQCrouzeixRaviartElement () [inline]
Constructor: there are three internal values for each of the two pressure components.
Definition at line 522 of file linearised_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data(), i, and oomph::FiniteElement::required_nvalue().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates at the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. global (Eulerian) coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 633 of file linearised_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and pshape_linearised_axi_nst().
Referenced by dshape_and_dtest_eulerian_linearised_axi_nst().
dshape_and_dtest_eulerian_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. global (Eulerian) coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 606 of file linearised_axisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by ndof_types().
fix_pressure()
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::fix_pressure (const unsigned & p_dof, const double & pvalue) [inline]
Fix both components of the internal pressure degrees of freedom p_dof to pvalue.
Definition at line 555 of file linearised_axisym_navier_stokes_elements.h.
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
ndof_types()
unsigned oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::ndof_types () const [inline], [virtual]
The number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 592 of file linearised_axisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_linearised_axi_nst().
npres_linearised_axi_nst()
unsigned oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::npres_linearised_axi_nst () const [inline], [virtual]
Return number of pressure values corresponding to a single pressure component.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 551 of file linearised_axisym_navier_stokes_elements.h.
output() [1/4]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 575 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 579 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 583 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 587 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
p_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::p_linearised_axi_nst (const unsigned & i_internal, const unsigned & i) const [inline], [virtual]
Return the pressure value i at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes)
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 542 of file linearised_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_local_eqn()
int oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::p_local_eqn (const unsigned & n, const unsigned & i) [inline], [virtual]
Overload the access function for the i-th component of the pressure's local equation numbers.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 569 of file linearised_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn().
pshape_linearised_axi_nst() [1/2]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Compute the pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 659 of file linearised_axisym_navier_stokes_elements.h.
Referenced by dshape_and_dtest_eulerian_at_knot_linearised_axi_nst().
pshape_linearised_axi_nst() [2/2]
void oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Compute the pressure shape and test functions at local coordinate s.
Define the pressure shape and test functions.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 670 of file linearised_axisym_navier_stokes_elements.h.
References i, and oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst().
required_nvalue()
unsigned oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::required_nvalue (const unsigned & n) const [virtual]
Return number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 1818 of file linearised_axisym_navier_stokes_elements.cc.
Referenced by oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
Member Data Documentation
Initial_Nvalue
const unsigned oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::Initial_Nvalue[] [static], [private]
Static array of ints to hold required number of variables at nodes.
Definition at line 483 of file linearised_axisym_navier_stokes_elements.h.
P_linearised_axi_nst_internal_index
Vector<unsigned> oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::P_linearised_axi_nst_internal_index [protected]
Internal indices that indicate at which internal data the pressure values are stored. We note that there are two pressure values, corresponding to the functions P^C(r,z,t) and P^S(r,z,t) which multiply the cosine and sine terms respectively.
Definition at line 491 of file linearised_axisym_navier_stokes_elements.h.
The documentation for this class was generated from the following files:
linearised_axisym_navier_stokes_elements.h
linearised_axisym_navier_stokes_elements.cc