oomph::RefineablePVDEquations< DIM > Class Template Reference
Class for Refineable PVD equations.
#include <refineable_solid_elements.h>
Public Member Functions
RefineablePVDEquations ()
Constructor.
void fill_in_generic_contribution_to_residuals_pvd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Call the residuals including hanging node cases.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
No values are interpolated in this element (pure solid)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
No values are interpolated in this element (pure solid)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 0 (pure solid problem)
virtual Node * solid_pressure_node_pt (const unsigned &l)
void further_build ()
Further build function, pass the pointers down to the sons.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineablePVDEquations< DIM >
Class for Refineable PVD equations.
Definition at line 49 of file refineable_solid_elements.h.
Constructor & Destructor Documentation
RefineablePVDEquations()
template<unsigned DIM>
oomph::RefineablePVDEquations< DIM >::RefineablePVDEquations () [inline]
Constructor.
Definition at line 56 of file refineable_solid_elements.h.
References oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd().
Member Function Documentation
fill_in_generic_contribution_to_residuals_pvd()
template<unsigned DIM>
void oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [virtual]
Call the residuals including hanging node cases.
Residuals for Refineable QPVDElements.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 44 of file refineable_solid_elements.cc.
References oomph::Helper_namespace_for_mesh_smoothing::Constitutive_law_pt, oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::DShape::offset(), oomph::RankFourTensor< T >::offset(), oomph::RankFiveTensor< T >::offset(), oomph::DShape::raw_direct_access(), oomph::RankFourTensor< T >::raw_direct_access(), oomph::RankFiveTensor< T >::raw_direct_access(), oomph::ConstitutiveLaw::requires_incompressibility_constraint(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineablePVDEquations< DIM >::RefineablePVDEquations().
further_build()
template<unsigned DIM>
void oomph::RefineablePVDEquations< DIM >::further_build () [inline], [virtual]
Further build function, pass the pointers down to the sons.
Reimplemented from oomph::RefineableSolidElement.
Definition at line 136 of file refineable_solid_elements.h.
References oomph::PVDEquationsBase< DIM >::body_force_fct_pt(), oomph::PVDEquationsBase< DIM >::Body_force_fct_pt, oomph::PVDEquationsBase< DIM >::constitutive_law_pt(), oomph::PVDEquationsBase< DIM >::Constitutive_law_pt, oomph::PVDEquationsBase< DIM >::Evaluate_jacobian_by_fd, oomph::RefineableElement::father_element_pt(), oomph::RefineableSolidElement::further_build(), oomph::PVDEquationsBase< DIM >::is_inertia_enabled(), oomph::PVDEquationsBase< DIM >::is_jacobian_evaluated_by_fd(), oomph::PVDEquationsBase< DIM >::isotropic_growth_fct_pt(), oomph::PVDEquationsBase< DIM >::Isotropic_growth_fct_pt, oomph::PVDEquationsBase< DIM >::lambda_sq_pt(), oomph::PVDEquationsBase< DIM >::Lambda_sq_pt, and oomph::PVDEquationsBase< DIM >::Unsteady.
Referenced by oomph::RefineableQPVDElementWithPressure< DIM >::further_setup_hanging_nodes().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineablePVDEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
No values are interpolated in this element (pure solid)
Implements oomph::RefineableElement.
Definition at line 70 of file refineable_solid_elements.h.
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineablePVDEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
No values are interpolated in this element (pure solid)
Reimplemented from oomph::RefineableElement.
Definition at line 74 of file refineable_solid_elements.h.
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineablePVDEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 86 of file refineable_solid_elements.h.
References oomph::PVDEquationsBase< DIM >::get_strain(), and i.
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineablePVDEquations< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 0 (pure solid problem)
Implements oomph::RefineableElement.
Definition at line 128 of file refineable_solid_elements.h.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineablePVDEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 78 of file refineable_solid_elements.h.
solid_pressure_node_pt()
template<unsigned DIM>
virtual Node* oomph::RefineablePVDEquations< DIM >::solid_pressure_node_pt (const unsigned & l) [inline], [virtual]
Definition at line 133 of file refineable_solid_elements.h.
Referenced by oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_node_pt(), and oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures().
The documentation for this class was generated from the following files:
refineable_solid_elements.h
refineable_solid_elements.cc