oomph::SteadyAxisymAdvectionDiffusionEquations Class Reference
A class for all elements that solve the Steady Axisymmetric Advection Diffusion equations using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
#include <steady_axisym_advection_diffusion_elements.h>
Public Types
typedef void(* SteadyAxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
typedef void(* SteadyAxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Public Member Functions
SteadyAxisymAdvectionDiffusionEquations ()
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
SteadyAxisymAdvectionDiffusionEquations (const SteadyAxisymAdvectionDiffusionEquations &dummy)
Broken copy constructor.
virtual unsigned u_index_axisym_adv_diff () const
Broken assignment operator.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: r,z,u at nplot^2 plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,u_exact at nplot^2 plot points.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
SteadyAxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SteadyAxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
SteadyAxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
SteadyAxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
virtual void get_source_axisym_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_wind_axisym_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: $ \mbox{flux}[i] = \nabla u = \mbox{d}u / \mbox{d}x_i $.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
double interpolated_u_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Pe_pt
Pointer to global Peclet number.
SteadyAxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
SteadyAxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
Static Private Attributes
static double Default_peclet_number = 0.0
Static default value for the Peclet number.
Additional Inherited Members
Detailed Description
A class for all elements that solve the Steady Axisymmetric Advection Diffusion equations using isoparametric elements.
 Pe \mathbf{w}\cdot(\mathbf{x}) \nabla u = \nabla \cdot \left( \nabla u \right) + f(\mathbf{x}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 59 of file steady_axisym_advection_diffusion_elements.h.
Member Typedef Documentation
SteadyAxisymAdvectionDiffusionSourceFctPt
typedef void(* oomph::SteadyAxisymAdvectionDiffusionEquations::SteadyAxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 66 of file steady_axisym_advection_diffusion_elements.h.
SteadyAxisymAdvectionDiffusionWindFctPt
typedef void(* oomph::SteadyAxisymAdvectionDiffusionEquations::SteadyAxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Definition at line 72 of file steady_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
SteadyAxisymAdvectionDiffusionEquations() [1/2]
oomph::SteadyAxisymAdvectionDiffusionEquations::SteadyAxisymAdvectionDiffusionEquations () [inline]
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
Definition at line 78 of file steady_axisym_advection_diffusion_elements.h.
References Default_peclet_number, and Pe_pt.
SteadyAxisymAdvectionDiffusionEquations() [2/2]
oomph::SteadyAxisymAdvectionDiffusionEquations::SteadyAxisymAdvectionDiffusionEquations (const SteadyAxisymAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 85 of file steady_axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error()
void oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 371 of file steady_axisym_advection_diffusion_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output().
dinterpolated_u_adv_diff_ddata()
virtual void oomph::SteadyAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Return derivative of u at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. This is virtual so that it can be overloaded in the refineable version.
Definition at line 326 of file steady_axisym_advection_diffusion_elements.h.
References dshape_and_dtest_eulerian_adv_diff(), dshape_and_dtest_eulerian_at_knot_adv_diff(), oomph::Data::eqn_number(), fill_in_generic_residual_contribution_adv_diff(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, self_test(), oomph::FiniteElement::shape(), and u_index_axisym_adv_diff().
dshape_and_dtest_eulerian_adv_diff()
virtual double oomph::SteadyAxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_adv_diff_ddata(), and oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_at_knot_adv_diff()
virtual double oomph::SteadyAxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Referenced by dinterpolated_u_adv_diff_ddata(), fill_in_generic_residual_contribution_adv_diff(), and oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
fill_in_contribution_to_jacobian()
void oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 282 of file steady_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_adv_diff().
fill_in_contribution_to_residuals()
void oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 269 of file steady_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_adv_diff().
fill_in_generic_residual_contribution_adv_diff()
void oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Definition at line 52 of file steady_axisym_advection_diffusion_elements.cc.
References dshape_and_dtest_eulerian_at_knot_adv_diff(), get_source_axisym_adv_diff(), get_wind_axisym_adv_diff(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), pe(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, u_index_axisym_adv_diff(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by dinterpolated_u_adv_diff_ddata(), fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_flux()
void oomph::SteadyAxisymAdvectionDiffusionEquations::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: $ \mbox{flux}[i] = \nabla u = \mbox{d}u / \mbox{d}x_i $.
Definition at line 235 of file steady_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axisym_adv_diff().
get_source_axisym_adv_diff()
virtual void oomph::SteadyAxisymAdvectionDiffusionEquations::get_source_axisym_adv_diff (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 193 of file steady_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by fill_in_generic_residual_contribution_adv_diff().
get_wind_axisym_adv_diff()
virtual void oomph::SteadyAxisymAdvectionDiffusionEquations::get_wind_axisym_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 214 of file steady_axisym_advection_diffusion_elements.h.
References i, and Wind_fct_pt.
Referenced by fill_in_generic_residual_contribution_adv_diff(), and output().
interpolated_u_adv_diff()
double oomph::SteadyAxisymAdvectionDiffusionEquations::interpolated_u_adv_diff (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 294 of file steady_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_axisym_adv_diff().
Referenced by compute_error(), and output().
output() [1/4]
void oomph::SteadyAxisymAdvectionDiffusionEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 113 of file steady_axisym_advection_diffusion_elements.h.
Referenced by output(), and oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >::output().
output() [2/4]
void oomph::SteadyAxisymAdvectionDiffusionEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: r,z,u at nplot^2 plot points.
Output function:
r,z,u,w_r,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 226 of file steady_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), get_wind_axisym_adv_diff(), i, interpolated_u_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::SteadyAxisymAdvectionDiffusionEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 125 of file steady_axisym_advection_diffusion_elements.h.
References compute_error(), output(), and output_fct().
output() [4/4]
void oomph::SteadyAxisymAdvectionDiffusionEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 279 of file steady_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct()
void oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_exact at nplot^2 plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 318 of file steady_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output(), and oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
pe()
const double& oomph::SteadyAxisymAdvectionDiffusionEquations::pe () const [inline]
Peclet number.
Definition at line 178 of file steady_axisym_advection_diffusion_elements.h.
References Pe_pt.
Referenced by fill_in_generic_residual_contribution_adv_diff().
pe_pt()
double* & oomph::SteadyAxisymAdvectionDiffusionEquations::pe_pt () [inline]
Pointer to Peclet number.
Definition at line 184 of file steady_axisym_advection_diffusion_elements.h.
References Pe_pt.
self_test()
unsigned oomph::SteadyAxisymAdvectionDiffusionEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 194 of file steady_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by dinterpolated_u_adv_diff_ddata().
source_fct_pt() [1/2]
SteadyAxisymAdvectionDiffusionSourceFctPt& oomph::SteadyAxisymAdvectionDiffusionEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 149 of file steady_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
source_fct_pt() [2/2]
SteadyAxisymAdvectionDiffusionSourceFctPt oomph::SteadyAxisymAdvectionDiffusionEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 156 of file steady_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
u_index_axisym_adv_diff()
virtual unsigned oomph::SteadyAxisymAdvectionDiffusionEquations::u_index_axisym_adv_diff () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the steady axisymmetric advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 107 of file steady_axisym_advection_diffusion_elements.h.
Referenced by dinterpolated_u_adv_diff_ddata(), fill_in_generic_residual_contribution_adv_diff(), get_flux(), interpolated_u_adv_diff(), and oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement().
wind_fct_pt() [1/2]
SteadyAxisymAdvectionDiffusionWindFctPt& oomph::SteadyAxisymAdvectionDiffusionEquations::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 163 of file steady_axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
wind_fct_pt() [2/2]
SteadyAxisymAdvectionDiffusionWindFctPt oomph::SteadyAxisymAdvectionDiffusionEquations::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 170 of file steady_axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
Member Data Documentation
Default_peclet_number
double oomph::SteadyAxisymAdvectionDiffusionEquations::Default_peclet_number = 0.0 [static], [private]
Static default value for the Peclet number.
2D Steady Axisymmetric Advection Diffusion elements
Default value for Peclet number
Definition at line 422 of file steady_axisym_advection_diffusion_elements.h.
Referenced by SteadyAxisymAdvectionDiffusionEquations().
Pe_pt
double* oomph::SteadyAxisymAdvectionDiffusionEquations::Pe_pt [protected]
Pointer to global Peclet number.
Definition at line 411 of file steady_axisym_advection_diffusion_elements.h.
Referenced by pe(), pe_pt(), and SteadyAxisymAdvectionDiffusionEquations().
Source_fct_pt
SteadyAxisymAdvectionDiffusionSourceFctPt oomph::SteadyAxisymAdvectionDiffusionEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 414 of file steady_axisym_advection_diffusion_elements.h.
Referenced by get_source_axisym_adv_diff(), and source_fct_pt().
Wind_fct_pt
SteadyAxisymAdvectionDiffusionWindFctPt oomph::SteadyAxisymAdvectionDiffusionEquations::Wind_fct_pt [protected]
Pointer to wind function:
Definition at line 417 of file steady_axisym_advection_diffusion_elements.h.
Referenced by get_wind_axisym_adv_diff(), and wind_fct_pt().
The documentation for this class was generated from the following files:
steady_axisym_advection_diffusion_elements.h
steady_axisym_advection_diffusion_elements.cc