oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT > Class Template Reference
#include <refineable_navier_stokes_elements.h>
Public Member Functions
RefineableFpPressureAdvDiffRobinBCElement (FiniteElement *const &element_pt, const int &face_index)
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometery<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 64 of file refineable_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableFpPressureAdvDiffRobinBCElement()
template<class ELEMENT >
oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::RefineableFpPressureAdvDiffRobinBCElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit
Definition at line 72 of file refineable_navier_stokes_elements.h.
References oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc().
Member Function Documentation
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc()
template<class ELEMENT >
void oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Get residuals and Jacobian of Robin boundary conditions in pressure advection diffusion problem in Fp preconditoner. Refineable version. Get outer unit normal
Reimplemented from oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >.
Definition at line 104 of file refineable_navier_stokes_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::RefineableFpPressureAdvDiffRobinBCElement().
The documentation for this class was generated from the following file:
refineable_navier_stokes_elements.h