oomph::MGProblem Class Reference
MGProblem class; subclass of Problem.
#include <geometric_multigrid.h>
Public Member Functions
MGProblem ()
Constructor. Initialise pointers to coarser and finer levels.
virtual ~MGProblem ()
Destructor (empty)
virtual MGProblem * make_new_problem ()=0
This function needs to be implemented in the derived problem: Returns a pointer to a new object of the same type as the derived problem.
virtual TreeBasedRefineableMeshBase * mg_bulk_mesh_pt ()=0
Function to get a pointer to the mesh we will be working with. If there are flux elements present in the mesh this will be overloaded to return a pointer to the bulk mesh otherwise it can be overloaded to point to the global mesh but it must be of type RefineableMeshBase.
Additional Inherited Members
Detailed Description
MGProblem class; subclass of Problem.
Definition at line 32 of file geometric_multigrid.h.
Constructor & Destructor Documentation
MGProblem()
oomph::MGProblem::MGProblem () [inline]
Constructor. Initialise pointers to coarser and finer levels.
Definition at line 38 of file geometric_multigrid.h.
 MGProblem()
virtual oomph::MGProblem::~MGProblem () [inline], [virtual]
Destructor (empty)
Definition at line 42 of file geometric_multigrid.h.
References make_new_problem(), and mg_bulk_mesh_pt().
Member Function Documentation
make_new_problem()
virtual MGProblem* oomph::MGProblem::make_new_problem () [pure virtual]
This function needs to be implemented in the derived problem: Returns a pointer to a new object of the same type as the derived problem.
Referenced by oomph::MGSolver< DIM >::setup_mg_hierarchy(), and ~MGProblem().
mg_bulk_mesh_pt()
virtual TreeBasedRefineableMeshBase* oomph::MGProblem::mg_bulk_mesh_pt () [pure virtual]
Function to get a pointer to the mesh we will be working with. If there are flux elements present in the mesh this will be overloaded to return a pointer to the bulk mesh otherwise it can be overloaded to point to the global mesh but it must be of type RefineableMeshBase.
Referenced by oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_mg_hierarchy(), and ~MGProblem().
The documentation for this class was generated from the following file:
geometric_multigrid.h