oomph::ChannelSpineMesh< ELEMENT > Class Template Reference
#include <channel_spine_mesh.template.h>
Public Member Functions
ChannelSpineMesh (const unsigned &nx0, const unsigned &nx1, const unsigned &nx2, const unsigned &ny, const double &lx0, const double &lx1, const double &lx2, const double &h, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region and pointer to timestepper (defaults to Steady timestepper)
ChannelSpineMesh (const unsigned &nx0, const unsigned &nx1, const unsigned &nx2, const unsigned &ny, const double &lx0, const double &lx1, const double &lx2, const double &h, GeomObject *wall_pt, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region, a boolean flag to indicate whether or not the mesh is periodic and pointer to timestepper (defaults to Steady timestepper)
FiniteElement *& left_element_pt (const unsigned long &i)
Access functions for pointers to the $ i $ -th element in the left region.
FiniteElement *& centre_element_pt (const unsigned long &i)
Access functions for pointers to the $ i $ -th element in the centre region.
FiniteElement *& right_element_pt (const unsigned long &i)
Access functions for pointers to the $ i $ -th element in the right region.
unsigned long nleft () const
Number of elements in left region.
unsigned long ncentre () const
Number of elements in centre region.
unsigned long nright () const
Number of elements in right region.
unsigned long nbulk () const
Number of elements in bulk.
void element_reorder ()
Reorder the elements so we loop over them vertically first (advantageous in `wide` domains if a frontal solver is used).
virtual void spine_node_update (SpineNode *spine_node_pt)
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines.
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Return the value of the x-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a `psudeo` two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default is to return nodes that are equally spaced in the x coodinate.
Spine *& left_spine_pt (const unsigned long &i)
Access function for spines in left region.
Spine *& centre_spine_pt (const unsigned long &i)
Access function for spines in centre region.
Spine *& right_spine_pt (const unsigned long &i)
Access function for spines in right region.
unsigned nleft_spine ()
Access function for the number of spines in the left region.
unsigned ncentre_spine ()
Access function for the number of spines in the centre region.
unsigned nright_spine ()
Access function for the number of spines in the right region.
GeomObject * wall_pt ()
Access function to the GeomObject for upper wall.
GeomObject * straight_wall_pt ()
Access function to the GeomObject for the straight upper wall.
Protected Member Functions
virtual void build_channel_spine_mesh (TimeStepper *time_stepper_pt)
Helper function to actually build the channel-spine mesh (called from various constructors)
Protected Attributes
Vector< FiniteElement * > Left_element_pt
Vector of pointers to element in the left region.
Vector< FiniteElement * > Centre_element_pt
Vector of pointers to element in the centre region.
Vector< FiniteElement * > Right_element_pt
Vector of pointers to element in the right region.
unsigned Nx0
Number of elements in the left region.
unsigned Nx1
Number of elements in the centre region.
unsigned Nx2
Number of elements in the right region.
double Lx0
Length of left region.
double Lx1
Length of centre region.
double Lx2
Length of right region.
unsigned Nleft_spine
Number of spines in left region.
unsigned Ncentre_spine
Number of spines in centre region.
unsigned Nright_spine
Number of spines in right region.
GeomObject * Wall_pt
GeomObject for upper wall.
GeomObject * Straight_wall_pt
GeomObject for the straight upper wall.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ChannelSpineMesh< ELEMENT >
Spine mesh class derived from standard 2D mesh. The mesh contains a StraightLine GeomObject which defines the height of the left and right regions (0,2) and another GeomObject is passed to the constructor to define the height in the central region.
Definition at line 47 of file channel_spine_mesh.template.h.
Constructor & Destructor Documentation
ChannelSpineMesh() [1/2]
template<class ELEMENT >
oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh (const unsigned & nx0, const unsigned & nx1, const unsigned & nx2, const unsigned & ny, const double & lx0, const double & lx1, const double & lx2, const double & h, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region and pointer to timestepper (defaults to Steady timestepper)
Constructor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction, axial length and height of layer, and pointer to timestepper (defaults to Static timestepper).
The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and a surface layer of corresponding Spine interface elements of type INTERFACE_ELEMENT, e.g. SpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
Definition at line 55 of file channel_spine_mesh.template.cc.
References oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
ChannelSpineMesh() [2/2]
template<class ELEMENT >
oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh (const unsigned & nx0, const unsigned & nx1, const unsigned & nx2, const unsigned & ny, const double & lx0, const double & lx1, const double & lx2, const double & h, GeomObject * wall_pt, const bool & periodic_in_x, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction in regions 0,1 and 2, number of elements in y-direction, length in x direction in regions 0,1 and 2, height mesh, pointer to the GeomObject defining the heightof the central region, a boolean flag to indicate whether or not the mesh is periodic and pointer to timestepper (defaults to Steady timestepper)
Constuctor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction, axial length and height of layer, a boolean flag to make the mesh periodic in the x-direction, and pointer to timestepper (defaults to Static timestepper).
The mesh contains a layer of elements (of type ELEMENT) and a surface layer of corresponding Spine interface elements (of type SpineLineFluidInterfaceElement<ELEMENT>).
Definition at line 103 of file channel_spine_mesh.template.cc.
References oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
Member Function Documentation
build_channel_spine_mesh()
template<class ELEMENT >
void oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh (TimeStepper * time_stepper_pt) [protected], [virtual]
Helper function to actually build the channel-spine mesh (called from various constructors)
Helper function that actually builds the channel-spine mesh based on the parameters set in the various constructors
Definition at line 147 of file channel_spine_mesh.template.cc.
References oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt, e, oomph::SpineMesh::element_node_pt(), oomph::Mesh::finite_element_pt(), oomph::SpineNode::fraction(), oomph::Spine::height(), i, oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt, oomph::GeomObject::locate_zeta(), oomph::ChannelSpineMesh< ELEMENT >::Lx0, oomph::ChannelSpineMesh< ELEMENT >::Lx1, oomph::ChannelSpineMesh< ELEMENT >::Lx2, oomph::ChannelSpineMesh< ELEMENT >::ncentre(), oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine, oomph::Mesh::nelement(), oomph::ChannelSpineMesh< ELEMENT >::nleft(), oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, oomph::SpineNode::node_update_fct_id(), oomph::ChannelSpineMesh< ELEMENT >::nright(), oomph::ChannelSpineMesh< ELEMENT >::Nright_spine, oomph::SpineMesh::nspine(), oomph::RectangularQuadMesh< ELEMENT >::Nx, oomph::ChannelSpineMesh< ELEMENT >::Nx0, oomph::ChannelSpineMesh< ELEMENT >::Nx1, oomph::ChannelSpineMesh< ELEMENT >::Nx2, oomph::RectangularQuadMesh< ELEMENT >::Ny, oomph::Data::pin(), oomph::GeomObject::position(), oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt, oomph::Spine::set_geom_object_pt(), oomph::Spine::set_geom_parameter(), oomph::Spine::spine_height_pt(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), oomph::SpineMesh::Spine_pt, oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt, oomph::ChannelSpineMesh< ELEMENT >::Wall_pt, and oomph::RectangularQuadMesh< ELEMENT >::Xperiodic.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh().
centre_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::ChannelSpineMesh< ELEMENT >::centre_element_pt (const unsigned long & i) [inline]
Access functions for pointers to the $ i $ -th element in the centre region.
Definition at line 93 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt, and i.
centre_spine_pt()
template<class ELEMENT >
Spine*& oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt (const unsigned long & i) [inline]
Access function for spines in centre region.
Definition at line 201 of file channel_spine_mesh.template.h.
References i, oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, and oomph::SpineMesh::Spine_pt.
element_reorder()
template<class ELEMENT >
void oomph::ChannelSpineMesh< ELEMENT >::element_reorder () [virtual]
Reorder the elements so we loop over them vertically first (advantageous in `wide` domains if a frontal solver is used).
Reorder the elements, so we loop over them vertically first (advantageous in `wide` domains if a frontal solver is used).
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
Definition at line 680 of file channel_spine_mesh.template.cc.
References e, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, oomph::Mesh::nelement(), oomph::RectangularQuadMesh< ELEMENT >::Nx, and oomph::RectangularQuadMesh< ELEMENT >::Ny.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::nbulk().
left_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::ChannelSpineMesh< ELEMENT >::left_element_pt (const unsigned long & i) [inline]
Access functions for pointers to the $ i $ -th element in the left region.
Definition at line 88 of file channel_spine_mesh.template.h.
References i, and oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt.
left_spine_pt()
template<class ELEMENT >
Spine*& oomph::ChannelSpineMesh< ELEMENT >::left_spine_pt (const unsigned long & i) [inline]
Access function for spines in left region.
Definition at line 187 of file channel_spine_mesh.template.h.
References i, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, and oomph::SpineMesh::Spine_pt.
nbulk()
template<class ELEMENT >
unsigned long oomph::ChannelSpineMesh< ELEMENT >::nbulk () const [inline]
Number of elements in bulk.
Definition at line 111 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt, oomph::ChannelSpineMesh< ELEMENT >::element_reorder(), oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt, and oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
ncentre()
template<class ELEMENT >
unsigned long oomph::ChannelSpineMesh< ELEMENT >::ncentre () const [inline]
Number of elements in centre region.
Definition at line 105 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh().
ncentre_spine()
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::ncentre_spine () [inline]
Access function for the number of spines in the centre region.
Definition at line 234 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine.
nleft()
template<class ELEMENT >
unsigned long oomph::ChannelSpineMesh< ELEMENT >::nleft () const [inline]
Number of elements in left region.
Definition at line 102 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh().
nleft_spine()
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::nleft_spine () [inline]
Access function for the number of spines in the left region.
Definition at line 231 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine.
nright()
template<class ELEMENT >
unsigned long oomph::ChannelSpineMesh< ELEMENT >::nright () const [inline]
Number of elements in right region.
Definition at line 108 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh().
nright_spine()
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::nright_spine () [inline]
Access function for the number of spines in the right region.
Definition at line 237 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Nright_spine.
right_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::ChannelSpineMesh< ELEMENT >::right_element_pt (const unsigned long & i) [inline]
Access functions for pointers to the $ i $ -th element in the right region.
Definition at line 98 of file channel_spine_mesh.template.h.
References i, and oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt.
right_spine_pt()
template<class ELEMENT >
Spine*& oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt (const unsigned long & i) [inline]
Access function for spines in right region.
Definition at line 216 of file channel_spine_mesh.template.h.
References i, oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine, oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine, oomph::ChannelSpineMesh< ELEMENT >::Nright_spine, and oomph::SpineMesh::Spine_pt.
spine_node_update()
template<class ELEMENT >
virtual void oomph::ChannelSpineMesh< ELEMENT >::spine_node_update (SpineNode * spine_node_pt) [inline], [virtual]
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines.
Implements oomph::SpineMesh.
Definition at line 125 of file channel_spine_mesh.template.h.
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::GeomObject::position(), oomph::SpineNode::spine_pt(), oomph::QuadTreeNames::W, oomph::Node::x(), and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
straight_wall_pt()
template<class ELEMENT >
GeomObject* oomph::ChannelSpineMesh< ELEMENT >::straight_wall_pt () [inline]
Access function to the GeomObject for the straight upper wall.
Definition at line 243 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt.
wall_pt()
template<class ELEMENT >
GeomObject* oomph::ChannelSpineMesh< ELEMENT >::wall_pt () [inline]
Access function to the GeomObject for upper wall.
Definition at line 240 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Wall_pt.
x_spacing_function()
template<class ELEMENT >
virtual double oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) [inline], [virtual]
Return the value of the x-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a `psudeo` two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default is to return nodes that are equally spaced in the x coodinate.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
Definition at line 148 of file channel_spine_mesh.template.h.
References oomph::ChannelSpineMesh< ELEMENT >::Lx0, oomph::ChannelSpineMesh< ELEMENT >::Lx1, oomph::ChannelSpineMesh< ELEMENT >::Lx2, oomph::RectangularQuadMesh< ELEMENT >::Np, oomph::ChannelSpineMesh< ELEMENT >::Nx0, oomph::ChannelSpineMesh< ELEMENT >::Nx1, oomph::ChannelSpineMesh< ELEMENT >::Nx2, and oomph::RectangularQuadMesh< ELEMENT >::Xmin.
Member Data Documentation
Centre_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::ChannelSpineMesh< ELEMENT >::Centre_element_pt [protected]
Vector of pointers to element in the centre region.
Definition at line 251 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::centre_element_pt(), oomph::ChannelSpineMesh< ELEMENT >::nbulk(), and oomph::ChannelSpineMesh< ELEMENT >::ncentre().
Left_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::ChannelSpineMesh< ELEMENT >::Left_element_pt [protected]
Vector of pointers to element in the left region.
Definition at line 248 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::left_element_pt(), oomph::ChannelSpineMesh< ELEMENT >::nbulk(), and oomph::ChannelSpineMesh< ELEMENT >::nleft().
Lx0
template<class ELEMENT >
double oomph::ChannelSpineMesh< ELEMENT >::Lx0 [protected]
Length of left region.
Definition at line 270 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Lx1
template<class ELEMENT >
double oomph::ChannelSpineMesh< ELEMENT >::Lx1 [protected]
Length of centre region.
Definition at line 273 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Lx2
template<class ELEMENT >
double oomph::ChannelSpineMesh< ELEMENT >::Lx2 [protected]
Length of right region.
Definition at line 276 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Ncentre_spine
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Ncentre_spine [protected]
Number of spines in centre region.
Definition at line 282 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::ncentre_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nleft_spine
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Nleft_spine [protected]
Number of spines in left region.
Definition at line 279 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::left_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::nleft_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nright_spine
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Nright_spine [protected]
Number of spines in right region.
Definition at line 285 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::nright_spine(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
Nx0
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx0 [protected]
Number of elements in the left region.
Definition at line 261 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Nx1
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx1 [protected]
Number of elements in the centre region.
Definition at line 264 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Nx2
template<class ELEMENT >
unsigned oomph::ChannelSpineMesh< ELEMENT >::Nx2 [protected]
Number of elements in the right region.
Definition at line 267 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::x_spacing_function().
Right_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::ChannelSpineMesh< ELEMENT >::Right_element_pt [protected]
Vector of pointers to element in the right region.
Definition at line 254 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::nbulk(), oomph::ChannelSpineMesh< ELEMENT >::nright(), and oomph::ChannelSpineMesh< ELEMENT >::right_element_pt().
Straight_wall_pt
template<class ELEMENT >
GeomObject* oomph::ChannelSpineMesh< ELEMENT >::Straight_wall_pt [protected]
GeomObject for the straight upper wall.
Definition at line 291 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::ChannelSpineMesh< ELEMENT >::ChannelSpineMesh(), and oomph::ChannelSpineMesh< ELEMENT >::straight_wall_pt().
Wall_pt
template<class ELEMENT >
GeomObject* oomph::ChannelSpineMesh< ELEMENT >::Wall_pt [protected]
GeomObject for upper wall.
Definition at line 288 of file channel_spine_mesh.template.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::wall_pt().
The documentation for this class was generated from the following files:
channel_spine_mesh.template.h
channel_spine_mesh.template.cc