oomph::MeshChecker Namespace Reference
Functions
template<class GEOM_ELEMENT_BASE , class ELEMENT >
void assert_geometric_element (const unsigned &dim, const unsigned &nnode_1d=0)
Helper function to assert that finite element of type ELEMENT can be cast to base class of type GEOM_ELEMENT_BASE -- useful to avoid confusion if a mesh that was written for a specific element type (e.g. a QElement) is used with another one (e.g. a TElement. First argument specifies the required spatial dimension of the element (i.e. the number of local coordinates). The optional second argument specifies the required nnode_1d (i.e. the number of nodes along a 1D element edge). Can be omitted if the mesh can handle any number in which case this test is skipped.
Detailed Description
Namespace with helper function to check element type in mesh constructors (say).
Function Documentation
assert_geometric_element()
template<class GEOM_ELEMENT_BASE , class ELEMENT >
void oomph::MeshChecker::assert_geometric_element (const unsigned & dim, const unsigned & nnode_1d = 0)
Helper function to assert that finite element of type ELEMENT can be cast to base class of type GEOM_ELEMENT_BASE -- useful to avoid confusion if a mesh that was written for a specific element type (e.g. a QElement) is used with another one (e.g. a TElement. First argument specifies the required spatial dimension of the element (i.e. the number of local coordinates). The optional second argument specifies the required nnode_1d (i.e. the number of nodes along a 1D element edge). Can be omitted if the mesh can handle any number in which case this test is skipped.
Definition at line 2497 of file mesh.h.
References oomph::Global_string_for_annotation::string(), oomph::ParaviewHelper::write_pvd_footer(), oomph::ParaviewHelper::write_pvd_header(), and oomph::ParaviewHelper::write_pvd_information().