oomph::TerminateHelper Namespace Reference
Functions
void setup ()
Setup terminate helper.
void suppress_exception_error_messages ()
Flush string stream of error messages (call when error has been caught)
void spawn_errors_from_uncaught_errors ()
Function to spawn messages from uncaught errors.
Variables
std::ostream * Error_message_stream_pt =&std::cerr
Stream to output error messages.
std::stringstream * Exception_stringstream_pt =0
String stream that records the error message.
Detailed Description
Helper namespace for set_terminate function -- used to spawn
messages from uncaught errors
Helper namespace for set_terminate function -- used to spawn
messages from uncaught errors (their destructor may not be called)
Function Documentation
setup()
void oomph::TerminateHelper::setup ()
Setup terminate helper.
Definition at line 71 of file oomph_definitions.cc.
References Exception_stringstream_pt, and spawn_errors_from_uncaught_errors().
Referenced by oomph::NavierStokesSchurComplementPreconditioner::disable_accept_non_NavierStokesElementWithDiagonalMassMatrices_elements(), oomph::HyprePreconditioner::disable_delete_matrix(), oomph::NavierStokesExactPreconditioner< MATRIX >::NavierStokesExactPreconditioner(), oomph::BiharmonicPreconditioner::operator=(), oomph::LagrangeEnforcedFlowPreconditioner::operator=(), oomph::ExactSubBiharmonicPreconditioner::operator=(), oomph::InexactSubBiharmonicPreconditioner::operator=(), oomph::BlockDiagonalPreconditioner< MATRIX >::operator=(), oomph::BlockTriangularPreconditioner< MATRIX >::operator=(), oomph::ExactBlockPreconditioner< MATRIX >::operator=(), oomph::Problem::Problem(), oomph::PseudoElasticPreconditioner::PseudoElasticPreconditioner(), oomph::PseudoElasticPreconditionerOld::PseudoElasticPreconditionerOld(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::PseudoElasticPreconditionerSubsidiaryPreconditionerOld(), oomph::InexactSubBiharmonicPreconditioner::setup(), and oomph::WomersleyImpedanceTubeBase< WOMERSLEY_ELEMENT, DIM >::setup().
spawn_errors_from_uncaught_errors()
void oomph::TerminateHelper::spawn_errors_from_uncaught_errors ()
Function to spawn messages from uncaught errors.
Definition at line 87 of file oomph_definitions.cc.
Referenced by setup().
suppress_exception_error_messages()
void oomph::TerminateHelper::suppress_exception_error_messages ()
Flush string stream of error messages (call when error has been caught)
Suppress error messages (e.g. because error has been caught)
Definition at line 80 of file oomph_definitions.cc.
References Exception_stringstream_pt.
Referenced by oomph::OomphLibException::disable_error_message().
Variable Documentation
Error_message_stream_pt
std::ostream * oomph::TerminateHelper::Error_message_stream_pt =&std::cerr
Stream to output error messages.
Definition at line 93 of file oomph_definitions.cc.
Exception_stringstream_pt
std::stringstream * oomph::TerminateHelper::Exception_stringstream_pt =0
String stream that records the error message.
Definition at line 96 of file oomph_definitions.cc.
Referenced by setup(), suppress_exception_error_messages(), and oomph::OomphLibException::~OomphLibException().