oomph::Hankel_functions_for_helmholtz_problem Namespace Reference
Functions
void Hankel_first (const unsigned &n, const double &x, Vector< std::complex< double > > &h, Vector< std::complex< double > > &hp)
void CHankel_first (const unsigned &n, const std::complex< double > &x, Vector< std::complex< double > > &h, Vector< std::complex< double > > &hp)
Detailed Description
Namespace to provide Hankel function of the first kind and various orders -- needed for Helmholtz computations.
Function Documentation
CHankel_first()
void oomph::Hankel_functions_for_helmholtz_problem::CHankel_first (const unsigned & n, const std::complex< double > & x, Vector< std::complex< double > > & h, Vector< std::complex< double > > & hp)
Compute Hankel function of the first kind of orders 0...n and its derivates at coordinate x. The function returns the vector then its derivative (complex version). This functionality is only required in the computation of the solution for the complex- shifted Laplacian preconditioner.
Definition at line 103 of file helmholtz_bc_elements.h.
References oomph::MathematicalConstants::I(), and i.
Hankel_first()
void oomph::Hankel_functions_for_helmholtz_problem::Hankel_first (const unsigned & n, const double & x, Vector< std::complex< double > > & h, Vector< std::complex< double > > & hp)
Compute Hankel function of the first kind of orders 0...n and its derivates at coordinate x. The function returns the vector then its derivative.
Definition at line 67 of file helmholtz_bc_elements.h.
References oomph::MathematicalConstants::I(), and i.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma().