oomph::TypeNames Namespace Reference
Functions
template<class T >
std::string get_type_name (T &obj)
Get the type name of an object. Only for use in debugging, do not write real code using this function as it is implementation dependant!
template<class T >
std::string get_type_name (T *obj)
Get the type name of an object from a pointer to the object (we usually want the type of the object itself not the pointer because the type of the pointer may be a base class). Only for use in debugging, do not write real code using this function as it is implementation dependant!
Function Documentation
get_type_name() [1/2]
template<class T >
std::string oomph::TypeNames::get_type_name (T & obj)
Get the type name of an object. Only for use in debugging, do not write real code using this function as it is implementation dependant!
Definition at line 184 of file oomph_utilities.h.
References oomph::Global_string_for_annotation::string(), and oomph::StringConversion::to_string().
get_type_name() [2/2]
template<class T >
std::string oomph::TypeNames::get_type_name (T * obj)
Get the type name of an object from a pointer to the object (we usually want the type of the object itself not the pointer because the type of the pointer may be a base class). Only for use in debugging, do not write real code using this function as it is implementation dependant!
Definition at line 207 of file oomph_utilities.h.
References oomph::CumulativeTimings::cumulative_time(), oomph::CumulativeTimings::halt(), i, oomph::CumulativeTimings::reset(), oomph::CumulativeTimings::set_ntimers(), oomph::CumulativeTimings::start(), oomph::CumulativeTimings::Start_time, and oomph::CumulativeTimings::Timing.