oomph::ProjectableElementBase Class Reference
Template-free Base class for projectable elements.
#include <projection.h>
Public Member Functions
ProjectableElementBase ()
virtual ~ProjectableElementBase ()
Virtual destructor.
virtual Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)=0
Pure virtual function in which the element writer must specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. E.g. in Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the DIM-th field) are the DIM-th values at the vertex nodes etc.
virtual unsigned nfields_for_projection ()=0
Number of fields of the problem, so e.g. for 2D Navier Stokes this would be 3 (for the two velocities and one pressure)
virtual unsigned nhistory_values_for_projection (const unsigned &fld)=0
Number of history values to be stored for fld-th field (includes current value!)
virtual unsigned nhistory_values_for_coordinate_projection ()=0
Number of history values to be stored when projecting the history values of the nodal coordinates (includes current value!)
virtual unsigned nvalue_of_field (const unsigned &fld)=0
Return number of values (pinned or not) associated with field fld within the element. This must correspond to the number of shape functions returned in jacobian_and_shape_of_field(...).
virtual int local_equation (const unsigned &fld, const unsigned &ivalue)=0
Return local equation numbers associated with value ivalue of field fld within the element.
virtual double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)=0
Return Jacobian of mapping and the shape functions associated with field fld. The number of shape functions must match the number of values specified in nvalue_of_field(...). For Lagrange-type interpolations the shape functinos are simply the `normal` nodal shape functions; if the element contains internal Data that is not associated with shape functions, simply set the corresonding shape function to 1.
virtual double get_field (const unsigned &time, const unsigned &fld, const Vector< double > &s)=0
Return the fld-th field at local coordinates s at time-level time (time=0: current value; time>0: history values)
Protected Types
enum Projection_Type { Coordinate,
Lagrangian,
Value
 }
Enumerated collection to specify which projection problem is to be solved.
Protected Attributes
unsigned Projected_field
Field that is currently being projected.
unsigned Time_level_for_projection
Time level we are projecting (0=current values; >0: history values)
unsigned Projected_coordinate
When projecting the history values of the nodal coordinates, this is the coordinate we're projecting.
unsigned Projected_lagrangian
When projecting the Lagrangain coordinates indicate which coordiante is to be projected.
Projection_Type Projection_type
Variable to indicate if we're projecting the history values of the nodal coordinates (Coordinate) the values themselves (Value), or the Lagrangian coordinates in Solid Mechanics problems (Lagrangian)
bool Do_projection
Bool to know if we do projection or not. If false (the default) we solve the element's `real` equations rather than the projection equations.
unsigned Backup_ninteraction
Store number of `external` interactions that were assigned to the element before doing the projection.
bool Backup_external_geometric_data
Remember if the element includes external geometric data when used in non-projection mode (this is temporarily disabled during the projection)
bool Backup_external_interaction_data
Remember if the element includes external data when used in non-projection mode (this is temporarily disabled during the projection)
Detailed Description
Template-free Base class for projectable elements.
Definition at line 59 of file projection.h.
Member Enumeration Documentation
Projection_Type
enum oomph::ProjectableElementBase::Projection_Type [protected]
Enumerated collection to specify which projection problem is to be solved.
Enumerator
Coordinate
Lagrangian
Value
Definition at line 66 of file projection.h.
Constructor & Destructor Documentation
ProjectableElementBase()
oomph::ProjectableElementBase::ProjectableElementBase () [inline]
Constructor: Initialise data so that we don't project but solve the `normal` equations associated with the element.
Definition at line 114 of file projection.h.
 ProjectableElementBase()
virtual oomph::ProjectableElementBase::~ProjectableElementBase () [inline], [virtual]
Virtual destructor.
Definition at line 120 of file projection.h.
References data_values_of_field(), get_field(), jacobian_and_shape_of_field(), local_equation(), nfields_for_projection(), nhistory_values_for_coordinate_projection(), nhistory_values_for_projection(), and nvalue_of_field().
Member Function Documentation
data_values_of_field()
virtual Vector<std::pair<Data*,unsigned> > oomph::ProjectableElementBase::data_values_of_field (const unsigned & fld) [pure virtual]
Pure virtual function in which the element writer must specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. E.g. in Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the DIM-th field) are the DIM-th values at the vertex nodes etc.
Referenced by ~ProjectableElementBase().
get_field()
virtual double oomph::ProjectableElementBase::get_field (const unsigned & time, const unsigned & fld, const Vector< double > & s) [pure virtual]
Return the fld-th field at local coordinates s at time-level time (time=0: current value; time>0: history values)
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and ~ProjectableElementBase().
jacobian_and_shape_of_field()
virtual double oomph::ProjectableElementBase::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [pure virtual]
Return Jacobian of mapping and the shape functions associated with field fld. The number of shape functions must match the number of values specified in nvalue_of_field(...). For Lagrange-type interpolations the shape functinos are simply the `normal` nodal shape functions; if the element contains internal Data that is not associated with shape functions, simply set the corresonding shape function to 1.
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and ~ProjectableElementBase().
local_equation()
virtual int oomph::ProjectableElementBase::local_equation (const unsigned & fld, const unsigned & ivalue) [pure virtual]
Return local equation numbers associated with value ivalue of field fld within the element.
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and ~ProjectableElementBase().
nfields_for_projection()
virtual unsigned oomph::ProjectableElementBase::nfields_for_projection () [pure virtual]
Number of fields of the problem, so e.g. for 2D Navier Stokes this would be 3 (for the two velocities and one pressure)
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), and ~ProjectableElementBase().
nhistory_values_for_coordinate_projection()
virtual unsigned oomph::ProjectableElementBase::nhistory_values_for_coordinate_projection () [pure virtual]
Number of history values to be stored when projecting the history values of the nodal coordinates (includes current value!)
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), and ~ProjectableElementBase().
nhistory_values_for_projection()
virtual unsigned oomph::ProjectableElementBase::nhistory_values_for_projection (const unsigned & fld) [pure virtual]
Number of history values to be stored for fld-th field (includes current value!)
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), and ~ProjectableElementBase().
nvalue_of_field()
virtual unsigned oomph::ProjectableElementBase::nvalue_of_field (const unsigned & fld) [pure virtual]
Return number of values (pinned or not) associated with field fld within the element. This must correspond to the number of shape functions returned in jacobian_and_shape_of_field(...).
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and ~ProjectableElementBase().
Member Data Documentation
Backup_external_geometric_data
bool oomph::ProjectableElementBase::Backup_external_geometric_data [protected]
Remember if the element includes external geometric data when used in non-projection mode (this is temporarily disabled during the projection)
Definition at line 100 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::disable_projection(), and oomph::ProjectableElement< ELEMENT >::enable_projection().
Backup_external_interaction_data
bool oomph::ProjectableElementBase::Backup_external_interaction_data [protected]
Remember if the element includes external data when used in non-projection mode (this is temporarily disabled during the projection)
Definition at line 106 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::disable_projection(), and oomph::ProjectableElement< ELEMENT >::enable_projection().
Backup_ninteraction
unsigned oomph::ProjectableElementBase::Backup_ninteraction [protected]
Store number of `external` interactions that were assigned to the element before doing the projection.
Definition at line 95 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::disable_projection(), and oomph::ProjectableElement< ELEMENT >::enable_projection().
Do_projection
bool oomph::ProjectableElementBase::Do_projection [protected]
Bool to know if we do projection or not. If false (the default) we solve the element's `real` equations rather than the projection equations.
Definition at line 90 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::disable_projection(), oomph::ProjectableElement< ELEMENT >::enable_projection(), oomph::ProjectableElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ProjectableElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::ProjectableElement< ELEMENT >::zeta_nodal().
Projected_coordinate
unsigned oomph::ProjectableElementBase::Projected_coordinate [protected]
When projecting the history values of the nodal coordinates, this is the coordinate we're projecting.
Definition at line 76 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::projected_coordinate(), and oomph::ProjectableElement< ELEMENT >::residual_for_projection().
Projected_field
unsigned oomph::ProjectableElementBase::Projected_field [protected]
Field that is currently being projected.
Definition at line 69 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::projected_field(), and oomph::ProjectableElement< ELEMENT >::residual_for_projection().
Projected_lagrangian
unsigned oomph::ProjectableElementBase::Projected_lagrangian [protected]
When projecting the Lagrangain coordinates indicate which coordiante is to be projected.
Definition at line 80 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::projected_lagrangian_coordinate(), and oomph::ProjectableElement< ELEMENT >::residual_for_projection().
Projection_type
Projection_Type oomph::ProjectableElementBase::Projection_type [protected]
Variable to indicate if we're projecting the history values of the nodal coordinates (Coordinate) the values themselves (Value), or the Lagrangian coordinates in Solid Mechanics problems (Lagrangian)
Definition at line 85 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::set_project_coordinates(), oomph::ProjectableElement< ELEMENT >::set_project_lagrangian(), and oomph::ProjectableElement< ELEMENT >::set_project_values().
Time_level_for_projection
unsigned oomph::ProjectableElementBase::Time_level_for_projection [protected]
Time level we are projecting (0=current values; >0: history values)
Definition at line 72 of file projection.h.
Referenced by oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and oomph::ProjectableElement< ELEMENT >::time_level_for_projection().
The documentation for this class was generated from the following file:
projection.h