ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER > Class Template Reference
1D ComplexHarmonic problem in unit interval.
Public Member Functions
ComplexHarmonicProblem (const unsigned &n_element)
Constructor: Pass number of elements and pointer to source function.
~ComplexHarmonicProblem ()
Destructor. Clean up the mesh and solver.
void solve (const unsigned &label)
Solve the problem.
void doc_solution (const unsigned &label)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Detailed Description
template<class ELEMENT, class EIGEN_SOLVER>
class ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >
1D ComplexHarmonic problem in unit interval.
Definition at line 353 of file complex_harmonic.cc.
Constructor & Destructor Documentation
ComplexHarmonicProblem()
template<class ELEMENT , class EIGEN_SOLVER >
ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::ComplexHarmonicProblem (const unsigned & n_element)
Constructor: Pass number of elements and pointer to source function.
Constructor for 1D ComplexHarmonic problem in unit interval. Discretise the 1D domain with n_element elements of type ELEMENT. Specify function pointer to source function.
Definition at line 381 of file complex_harmonic.cc.
 ComplexHarmonicProblem()
template<class ELEMENT, class EIGEN_SOLVER>
ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::~ComplexHarmonicProblem () [inline]
Destructor. Clean up the mesh and solver.
Definition at line 361 of file complex_harmonic.cc.
Member Function Documentation
doc_solution()
template<class ELEMENT , class EIGEN_SOLVER >
void ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::doc_solution (const unsigned & label)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Doc the solution in tecplot format. Label files with label.
Definition at line 420 of file complex_harmonic.cc.
References ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve().
solve()
template<class ELEMENT , class EIGEN_SOLVER >
void ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::solve (const unsigned & label)
Solve the problem.
Solve the eigenproblem.
Definition at line 444 of file complex_harmonic.cc.
Referenced by ComplexHarmonicProblem< ELEMENT, EIGEN_SOLVER >::doc_solution(), and main().
The documentation for this class was generated from the following file:
complex_harmonic.cc