DiskOscillationProblem< ELEMENT > Class Template Reference
Problem class to simulate small-amplitude oscillations of a circular disk.
Public Member Functions
DiskOscillationProblem ()
Constructor.
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
ElasticRefineableQuarterCircleSectorMesh< ELEMENT > * mesh_pt ()
Access function for the solid mesh.
void run (const unsigned &nstep)
Run the problem: Pass number of timesteps to be performed.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
ofstream Trace_file
Trace file.
Vector< Node * > Trace_node_pt
Vector of pointers to nodes whose position we're tracing.
AxisymOscillatingDisk * IC_geom_object_pt
Geometric object that specifies the initial conditions.
Detailed Description
template<class ELEMENT>
class DiskOscillationProblem< ELEMENT >
Problem class to simulate small-amplitude oscillations of a circular disk.
Definition at line 418 of file disk_oscillation.cc.
Constructor & Destructor Documentation
DiskOscillationProblem()
template<class ELEMENT >
DiskOscillationProblem< ELEMENT >::DiskOscillationProblem ()
Constructor.
Definition at line 466 of file disk_oscillation.cc.
References Global_Physical_Variables::Constitutive_law_pt, and Global_Physical_Variables::Lambda_sq.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void DiskOscillationProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 427 of file disk_oscillation.cc.
actions_before_newton_solve()
template<class ELEMENT>
void DiskOscillationProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 430 of file disk_oscillation.cc.
doc_solution()
template<class ELEMENT >
void DiskOscillationProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 558 of file disk_oscillation.cc.
mesh_pt()
template<class ELEMENT>
ElasticRefineableQuarterCircleSectorMesh<ELEMENT>* DiskOscillationProblem< ELEMENT >::mesh_pt () [inline]
Access function for the solid mesh.
Definition at line 433 of file disk_oscillation.cc.
run()
template<class ELEMENT >
void DiskOscillationProblem< ELEMENT >::run (const unsigned & nstep)
Run the problem: Pass number of timesteps to be performed.
Definition at line 757 of file disk_oscillation.cc.
References AxisymOscillatingDisk::AxisymOscillatingDisk(), Global_Physical_Variables::multiplier(), and Global_Physical_Variables::Nu.
Referenced by main().
Member Data Documentation
IC_geom_object_pt
template<class ELEMENT>
AxisymOscillatingDisk* DiskOscillationProblem< ELEMENT >::IC_geom_object_pt [private]
Geometric object that specifies the initial conditions.
Definition at line 454 of file disk_oscillation.cc.
Trace_file
template<class ELEMENT>
ofstream DiskOscillationProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 448 of file disk_oscillation.cc.
Trace_node_pt
template<class ELEMENT>
Vector<Node*> DiskOscillationProblem< ELEMENT >::Trace_node_pt [private]
Vector of pointers to nodes whose position we're tracing.
Definition at line 451 of file disk_oscillation.cc.
The documentation for this class was generated from the following file:
disk_oscillation.cc