oomph::DGSpectralEulerElement< 2, NNODE_1D > Class Template Reference
Specialisation for 2D DG Elements.
#include <euler_elements.h>
Public Member Functions
unsigned required_nflux ()
Overload the required number of fluxes for the DGElement.
void calculate_element_averages (double *&average_value)
Calculate the averages in the element.
DGSpectralEulerElement ()
~DGSpectralEulerElement ()
Integral * face_integration_pt () const
void build_all_faces ()
void fill_in_generic_residual_contribution_flux_transport (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Static Private Attributes
static Gauss< 1, NNODE_1D > Default_face_integration_scheme
Friends
class DGEulerFaceElement< DGSpectralEulerElement< 2, NNODE_1D > >
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::DGSpectralEulerElement< 2, NNODE_1D >
Specialisation for 2D DG Elements.
Definition at line 871 of file euler_elements.h.
Constructor & Destructor Documentation
DGSpectralEulerElement()
template<unsigned NNODE_1D>
oomph::DGSpectralEulerElement< 2, NNODE_1D >::DGSpectralEulerElement () [inline]
Definition at line 889 of file euler_elements.h.
References oomph::FiniteElement::set_integration_scheme().
 DGSpectralEulerElement()
template<unsigned NNODE_1D>
oomph::DGSpectralEulerElement< 2, NNODE_1D >::~DGSpectralEulerElement () [inline]
Definition at line 898 of file euler_elements.h.
Member Function Documentation
build_all_faces()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 2, NNODE_1D >::build_all_faces () [inline], [virtual]
Implements oomph::DGElement.
Definition at line 903 of file euler_elements.h.
calculate_element_averages()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 2, NNODE_1D >::calculate_element_averages (double *& average_values) [inline], [virtual]
Calculate the averages in the element.
Reimplemented from oomph::DGElement.
Definition at line 885 of file euler_elements.h.
References oomph::FluxTransportEquations< DIM >::calculate_element_averages().
face_integration_pt()
template<unsigned NNODE_1D>
Integral* oomph::DGSpectralEulerElement< 2, NNODE_1D >::face_integration_pt () const [inline]
Definition at line 900 of file euler_elements.h.
fill_in_generic_residual_contribution_flux_transport()
template<unsigned NNODE_1D>
void oomph::DGSpectralEulerElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [inline], [virtual]
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 927 of file euler_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
required_nflux()
template<unsigned NNODE_1D>
unsigned oomph::DGSpectralEulerElement< 2, NNODE_1D >::required_nflux () [inline], [virtual]
Overload the required number of fluxes for the DGElement.
Reimplemented from oomph::DGElement.
Definition at line 882 of file euler_elements.h.
References oomph::EulerEquations< DIM >::nflux().
Friends And Related Function Documentation
DGEulerFaceElement< DGSpectralEulerElement< 2, NNODE_1D > >
template<unsigned NNODE_1D>
friend class DGEulerFaceElement< DGSpectralEulerElement< 2, NNODE_1D > > [friend]
Definition at line 875 of file euler_elements.h.
Member Data Documentation
Default_face_integration_scheme
template<unsigned NNODE_1D>
Gauss< 1, NNODE_1D > oomph::DGSpectralEulerElement< 2, NNODE_1D >::Default_face_integration_scheme [static], [private]
Definition at line 877 of file euler_elements.h.
The documentation for this class was generated from the following files:
euler_elements.h
euler_elements.cc