oomph::TBubbleEnrichedElement< DIM, 3 > Class Template Reference
#include <Telements.h>
Public Member Functions
TBubbleEnrichedElement ()
Constructor.
TBubbleEnrichedElement (const TBubbleEnrichedElement &)
Broken copy constructor.
~TBubbleEnrichedElement ()
Broken assignment operator.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement.
Static Private Attributes
static TBubbleEnrichedGauss< DIM, 3 > Default_enriched_integration_scheme
static const unsigned Central_node_on_face [DIM+1]
Detailed Description
template<unsigned DIM>
class oomph::TBubbleEnrichedElement< DIM, 3 >
Enriched TElement class specialised to two spatial dimensions and three nodes per side (quadratic element) Ordering of nodes as in Zienkiwizc sketches: vertex nodes 0 - 1 - 2 anticlockwise. Midside nodes filled in progressing along the consecutive edges. Central node(s) come(s) last. The idea is that we inherit from the existing TElement<2,3>, add the single extra node at the centroid and overload the shape functions to be those corresponding to the enriched element.
Definition at line 3539 of file Telements.h.
Constructor & Destructor Documentation
TBubbleEnrichedElement() [1/2]
template<unsigned DIM>
oomph::TBubbleEnrichedElement< DIM, 3 >::TBubbleEnrichedElement () [inline]
Constructor.
Definition at line 3553 of file Telements.h.
TBubbleEnrichedElement() [2/2]
template<unsigned DIM>
oomph::TBubbleEnrichedElement< DIM, 3 >::TBubbleEnrichedElement (const TBubbleEnrichedElement< DIM, 3 > &) [inline]
Broken copy constructor.
Definition at line 3565 of file Telements.h.
References oomph::BrokenCopy::broken_copy().
 TBubbleEnrichedElement()
template<unsigned DIM>
oomph::TBubbleEnrichedElement< DIM, 3 >::~TBubbleEnrichedElement () [inline]
Broken assignment operator.
Destructor
Definition at line 3577 of file Telements.h.
Member Function Documentation
build_face_element()
template<unsigned DIM>
void oomph::TBubbleEnrichedElement< DIM, 3 >::build_face_element (const int & face_index, FaceElement * face_element_pt)
Build the lower-dimensional FaceElement.
d2shape_local()
template<unsigned DIM>
void oomph::TBubbleEnrichedElement< DIM, 3 >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
Definition at line 3595 of file Telements.h.
dshape_local()
template<unsigned DIM>
void oomph::TBubbleEnrichedElement< DIM, 3 >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Definition at line 3585 of file Telements.h.
Referenced by oomph::TCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::TTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst().
local_coordinate_of_node()
template<unsigned DIM>
void oomph::TBubbleEnrichedElement< DIM, 3 >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline]
Return local coordinates of node j.
Definition at line 3600 of file Telements.h.
shape()
template<unsigned DIM>
void oomph::TBubbleEnrichedElement< DIM, 3 >::shape (const Vector< double > & s, Shape & psi) const [inline]
Calculate the geometric shape functions at local coordinate s.
Definition at line 3580 of file Telements.h.
References oomph::OneDimLagrange::shape().
Member Data Documentation
Central_node_on_face
template<unsigned DIM>
const unsigned oomph::TBubbleEnrichedElement< DIM, 3 >::Central_node_on_face[DIM+1] [static], [private]
Definition at line 3548 of file Telements.h.
Default_enriched_integration_scheme
template<unsigned DIM>
TBubbleEnrichedGauss< DIM, 3 > oomph::TBubbleEnrichedElement< DIM, 3 >::Default_enriched_integration_scheme [static], [private]
Definition at line 3545 of file Telements.h.
The documentation for this class was generated from the following files:
Telements.h
Telements.cc