oomph::LinearWaveFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied flux on the boundaries of LinearWave elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <linear_wave_flux_elements.h>
Public Types
typedef void(* LinearWavePrescribedFluxFctPt) (const double &time, const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Public Member Functions
LinearWaveFluxElement (FiniteElement *bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
LinearWaveFluxElement ()
Broken empty constructor.
LinearWaveFluxElement (const LinearWaveFluxElement &dummy)
Broken copy constructor.
void operator= (const LinearWaveFluxElement &)
Broken assignment operator.
LinearWavePrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const double &time, const Vector< double > &x, double &flux)
Private Member Functions
void fill_in_generic_residual_contribution_lin_wave_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute the element residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
LinearWavePrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
unsigned Dim
The spatial dimension of the problem.
unsigned U_index_lin_wave
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::LinearWaveFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied flux on the boundaries of LinearWave elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 56 of file linear_wave_flux_elements.h.
Member Typedef Documentation
LinearWavePrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::LinearWaveFluxElement< ELEMENT >::LinearWavePrescribedFluxFctPt) (const double &time, const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Definition at line 65 of file linear_wave_flux_elements.h.
Constructor & Destructor Documentation
LinearWaveFluxElement() [1/3]
template<class ELEMENT >
oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement (FiniteElement * bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Definition at line 220 of file linear_wave_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::LinearWaveFluxElement< ELEMENT >::Dim, oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux(), oomph::LinearWaveFluxElement< ELEMENT >::Flux_fct_pt, oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), oomph::LinearWaveEquations< DIM >::u_index_lin_wave(), and oomph::LinearWaveFluxElement< ELEMENT >::U_index_lin_wave.
LinearWaveFluxElement() [2/3]
template<class ELEMENT >
oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement () [inline]
Broken empty constructor.
Definition at line 74 of file linear_wave_flux_elements.h.
LinearWaveFluxElement() [3/3]
template<class ELEMENT >
oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement (const LinearWaveFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 83 of file linear_wave_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 110 of file linear_wave_flux_elements.h.
References oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the element residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 100 of file linear_wave_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux().
fill_in_generic_residual_contribution_lin_wave_flux()
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Compute the element residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 382 of file linear_wave_flux_elements.h.
References oomph::LinearWaveFluxElement< ELEMENT >::Dim, oomph::LinearWaveFluxElement< ELEMENT >::get_flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), s, oomph::LinearWaveFluxElement< ELEMENT >::shape_and_test(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::LinearWaveFluxElement< ELEMENT >::U_index_lin_wave, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::LinearWaveFluxElement< ELEMENT >::get_flux(), and oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement().
flux_fct_pt()
template<class ELEMENT >
LinearWavePrescribedFluxFctPt& oomph::LinearWaveFluxElement< ELEMENT >::flux_fct_pt () [inline]
Access function for the prescribed-flux function pointer.
Definition at line 96 of file linear_wave_flux_elements.h.
References oomph::LinearWaveFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::get_flux (const double & time, const Vector< double > & x, double & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position and at a gien time
Definition at line 171 of file linear_wave_flux_elements.h.
References oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux(), and oomph::LinearWaveFluxElement< ELEMENT >::Flux_fct_pt.
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux().
operator=()
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::operator= (const LinearWaveFluxElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 89 of file linear_wave_flux_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 128 of file linear_wave_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 132 of file linear_wave_flux_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 138 of file linear_wave_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::LinearWaveFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 142 of file linear_wave_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::LinearWaveFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 151 of file linear_wave_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux().
zeta_nodal()
template<class ELEMENT >
double oomph::LinearWaveFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Specify the value of nodal zeta from the face geometry
Reimplemented from oomph::FaceElement.
Definition at line 122 of file linear_wave_flux_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::LinearWaveFluxElement< ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 201 of file linear_wave_flux_elements.h.
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux(), and oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement().
Flux_fct_pt
template<class ELEMENT >
LinearWavePrescribedFluxFctPt oomph::LinearWaveFluxElement< ELEMENT >::Flux_fct_pt [private]
Function pointer to the (global) prescribed-flux function.
Definition at line 198 of file linear_wave_flux_elements.h.
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::flux_fct_pt(), oomph::LinearWaveFluxElement< ELEMENT >::get_flux(), and oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement().
U_index_lin_wave
template<class ELEMENT >
unsigned oomph::LinearWaveFluxElement< ELEMENT >::U_index_lin_wave [private]
The index at which the unknown is stored at the nodes.
Definition at line 204 of file linear_wave_flux_elements.h.
Referenced by oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux(), and oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement().
The documentation for this class was generated from the following file:
linear_wave_flux_elements.h