oomph::RefineableQSpectralElement< 3 > Class Template Reference
#include <refineable_brick_spectral_element.h>
Public Member Functions
RefineableQSpectralElement ()
Constructor.
RefineableQSpectralElement (const RefineableQSpectralElement< 3 > &dummy)
Broken copy constructor.
virtual ~RefineableQSpectralElement ()
Broken assignment operator.
void rebuild_from_sons (Mesh *&mesh_pt)
The only thing to add is rebuild from sons.
virtual bool nodes_built ()
Overload the nodes built function.
Additional Inherited Members
Detailed Description
template<>
class oomph::RefineableQSpectralElement< 3 >
Refineable version of QuadElements that add functionality for spectral Elements.
Definition at line 51 of file refineable_brick_spectral_element.h.
Constructor & Destructor Documentation
RefineableQSpectralElement() [1/2]
oomph::RefineableQSpectralElement< 3 >::RefineableQSpectralElement () [inline]
Constructor.
Definition at line 57 of file refineable_brick_spectral_element.h.
References oomph::LeakCheckNames::_build.
RefineableQSpectralElement() [2/2]
oomph::RefineableQSpectralElement< 3 >::RefineableQSpectralElement (const RefineableQSpectralElement< 3 > & dummy) [inline]
Broken copy constructor.
Definition at line 66 of file refineable_brick_spectral_element.h.
References oomph::BrokenCopy::broken_copy().
 RefineableQSpectralElement()
virtual oomph::RefineableQSpectralElement< 3 >::~RefineableQSpectralElement () [inline], [virtual]
Broken assignment operator.
Destructor
Definition at line 82 of file refineable_brick_spectral_element.h.
References oomph::LeakCheckNames::_build.
Member Function Documentation
nodes_built()
virtual bool oomph::RefineableQSpectralElement< 3 >::nodes_built () [inline], [virtual]
Overload the nodes built function.
Reimplemented from oomph::RefineableElement.
Definition at line 539 of file refineable_brick_spectral_element.h.
rebuild_from_sons()
void oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
The only thing to add is rebuild from sons.
Implements oomph::RefineableElement.
Definition at line 90 of file refineable_brick_spectral_element.h.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::OcTreeNames::B, oomph::Mesh::boundary_coordinate_exists(), oomph::OcTreeNames::D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, oomph::RefineableQElement< 3 >::get_bcs(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::RefineableElement::get_interpolated_values(), oomph::RefineableSolidQElement< 3 >::get_solid_bcs(), oomph::FiniteElement::get_x(), i, oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), oomph::BinaryTreeNames::L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::Node::ndim(), oomph::TimeStepper::ntstorage(), oomph::Tree::OMEGA, oomph::SolidNode::pin_position(), oomph::BinaryTreeNames::R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, s, oomph::Global_string_for_annotation::string(), t, oomph::OcTreeNames::U, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
The documentation for this class was generated from the following file:
refineable_brick_spectral_element.h