oomph::RefineableTriangleMesh< ELEMENT > Class Template Reference
Unstructured refineable Triangle Mesh.
#include <triangle_mesh.template.h>
Public Types
typedef void(* MeshUpdateFctPt) (Mesh *mesh_pt)
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
typedef void(* InternalHolePointUpdateFctPt) (const unsigned &ihole, TriangleMeshPolygon *poly_pt)
Function pointer to a function that can generate a point within the ihole-th hole, so that this can be overloaded by the user if they have a better way of doing it than our clunky default. The function should update the components of the Vector poly_pt->internal_point()
Public Member Functions
RefineableTriangleMesh (TriangleMeshParameters &triangle_mesh_parameters, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Build mesh, based on the specifications on TriangleMeshParameters.
RefineableTriangleMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Build mesh, based on the polyfiles.
virtual ~RefineableTriangleMesh ()
Empty Destructor.
void enable_timings_tranfering_target_areas ()
Enables info. and timings for tranferring of target areas.
void disable_timings_tranfering_target_areas ()
Disables info. and timings for tranferring of target areas.
void enable_projection ()
Enables the solution projection step during adaptation.
void disable_projection ()
Disables the solution projection step during adaptation.
void enable_timings_projection ()
Enables info. and timings for projection.
void disable_timings_projection ()
Disables info. and timings for projection.
unsigned & nbin_x_for_area_transfer ()
Read/write access to number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned & nbin_y_for_area_transfer ()
Read/write access to number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned max_sample_points_for_limited_locate_zeta_during_target_area_transfer ()
Read/write access to number of sample points from which we try to locate zeta by Newton method when transferring target areas using cgal-based sample point container. If Newton method doesn't converge from any of these we use the nearest sample point.
double & max_element_size ()
Max element size allowed during adaptation.
double & min_element_size ()
Min element size allowed during adaptation.
double & min_permitted_angle ()
Min angle before remesh gets triggered.
bool use_iterative_solver_for_projection ()
void enable_iterative_solver_for_projection ()
void disable_iterative_solver_for_projection ()
void enable_print_timings_adaptation (const unsigned &print_level=1)
Enables printing of timings for adaptation.
void disable_print_timings_adaptation ()
Disables printing of timings for adaptation.
void set_print_level_timings_adaptation (const unsigned &print_level)
Sets the printing level of timings for adaptation.
void enable_print_timings_load_balance (const unsigned &print_level=1)
Enables printing of timings for load balance.
void disable_print_timings_load_balance ()
Disables printing of timings for load balance.
void set_print_level_timings_load_balance (const unsigned &print_level)
Sets the printing level of timings for load balance.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
unsigned unrefine_uniformly ()
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void adapt (const Vector< double > &elem_error)
Adapt mesh, based on elemental error provided.
MeshUpdateFctPt & mesh_update_fct_pt ()
Access to function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
InternalHolePointUpdateFctPt & internal_hole_point_update_fct_pt ()
Access to function pointer to can be used to generate the internal point for the ihole-th hole.
unsigned nsorted_shared_boundary_node (unsigned &b)
void flush_sorted_shared_boundary_node ()
Node * sorted_shared_boundary_node_pt (unsigned &b, unsigned &i)
Vector< Node * > sorted_shared_boundary_node_pt (unsigned &b)
void create_polylines_from_polyfiles (const std::string &node_file_name, const std::string &poly_file_name)
Helper function to create polylines and fill associate data.
void fill_boundary_elements_and_nodes_for_internal_boundaries ()
void fill_boundary_elements_and_nodes_for_internal_boundaries (std::ofstream &outfile)
void reestablish_distribution_info_for_restart (OomphCommunicator *comm_pt, std::istream &restart_file)
void update_polyline_representation_from_restart ()
Method used to update the polylines representation after restart.
void load_balance (const Vector< unsigned > &input_target_domain_for_local_non_halo_element)
Performs the load balancing for unstructured meshes, the load balancing strategy is based on mesh migration.
void get_shared_boundary_elements_and_face_indexes (const Vector< FiniteElement *> &first_element_pt, const Vector< FiniteElement *> &second_element_pt, Vector< FiniteElement *> &first_shared_boundary_element_pt, Vector< unsigned > &first_shared_boundary_element_face_index, Vector< FiniteElement *> &second_shared_boundary_element_pt, Vector< unsigned > &second_shared_boundary_element_face_index)
Use the first and second group of elements to find the intersection between them to get the shared boundary elements from the first and second group.
void create_new_shared_boundaries (std::set< FiniteElement *> &element_in_processor_pt, Vector< Vector< FiniteElement *> > &new_shared_boundary_element_pt, Vector< Vector< unsigned > > &new_shared_boundary_element_face_index)
Creates the new shared boundaries, this method is also in charge of computing the shared boundaries ids of each processor and send that info. to all the processors.
void compute_shared_node_degree_helper (Vector< Vector< FiniteElement *> > &unsorted_face_ele_pt, std::map< Node *, unsigned > &global_node_degree)
Computes the degree of the nodes on the shared boundaries, the degree of the node is computed from the global graph created by the shared boundaries of all processors.
void create_adjacency_matrix_new_shared_edges_helper (Vector< Vector< FiniteElement *> > &unsorted_face_ele_pt, Vector< Vector< Node *> > &tmp_sorted_shared_node_pt, std::map< Node *, Vector< Vector< unsigned > > > &node_alias, Vector< Vector< Vector< unsigned > > > &adjacency_matrix)
Sort the nodes on the new shared boundaries (after load balancing), computes the alias of the nodes and creates the adjacency matrix that represent the graph created by the shared edges between each pair of processors.
void get_shared_boundary_segment_nodes_helper (const unsigned &shd_bnd_id, Vector< Vector< Node *> > &tmp_segment_nodes)
Get the nodes on the shared boundary (b), these are stored in the segment they belong.
void get_boundary_segment_nodes_helper (const unsigned &b, Vector< Vector< Node *> > &tmp_segment_nodes)
Get the nodes on the boundary (b), these are stored in the segment they belong (also used by the load balance method to re-set the number of segments per boundary after load balance has taken place)
void enable_boundary_unrefinement_constrained_by_target_areas ()
Enable/disable unrefinement/refinement methods for original boundaries.
void disable_boundary_unrefinement_constrained_by_target_areas ()
void enable_boundary_refinement_constrained_by_target_areas ()
void disable_boundary_refinement_constrained_by_target_areas ()
void enable_shared_boundary_unrefinement_constrained_by_target_areas ()
Enable/disable unrefinement/refinement methods for shared boundaries.
void disable_shared_boundary_unrefinement_constrained_by_target_areas ()
void enable_shared_boundary_refinement_constrained_by_target_areas ()
void disable_shared_boundary_refinement_constrained_by_target_areas ()
Protected Member Functions
RefineableTriangleMesh (const Vector< double > &target_area, TriangulateIO &triangulate_io, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &allow_automatic_creation_of_vertices_on_boundaries=true, OomphCommunicator *comm_pt=0)
Build mesh from specified triangulation and associated target areas for elements in it NOTE: This is used ONLY during adaptation and should not be used as a method of constructing a TriangleMesh object in demo drivers!
const bool boundary_connections (const unsigned &b, const unsigned &c, std::set< Vector< double > > &vertices)
Verifies if the given boundary receives a connection, and if that is the case then returns the list of vertices that receive the connections.
const void synchronize_shared_boundary_connections ()
Synchronise the vertices that are marked for non deletion.
void add_vertices_for_non_deletion ()
Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_chunk_connections_pt structure.
void add_non_delete_vertices_from_boundary_helper (Vector< Vector< Node *> > src_bound_segment_node_pt, Vector< Vector< Node *> > dst_bound_segment_node_pt, const unsigned &dst_bnd_id, const unsigned &dst_bnd_chunk)
Adds the vertices from the sources boundary that are repeated in the destination boundary to the list of non delete-able vertices in the destination boundary.
void create_temporary_boundary_connections (Vector< TriangleMeshPolygon *> &tmp_outer_polygons_pt, Vector< TriangleMeshOpenCurve *> &tmp_open_curves_pt)
After unrefinement and refinement has taken place compute the new vertices numbers of the temporary representation of the.
void restore_boundary_connections (Vector< TriangleMeshPolyLine *> &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> &resume_final_connection_polyline_pt)
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended and resumed after the adaptation processor.
void restore_polyline_connections_helper (TriangleMeshPolyLine *polyline_pt, Vector< TriangleMeshPolyLine *> &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> &resume_final_connection_polyline_pt)
Restore the connections of the specific polyline The vertices numbering on the destination boundaries may have change because of (un)refinement in the destination boundaries. Also deals with connection that do not longer exist because the destination boundary does no longer exist because of the distribution process.
void resume_boundary_connections (Vector< TriangleMeshPolyLine *> &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> &resume_final_connection_polyline_pt)
Resume the boundary connections that may have been suspended because the destination boundary is no part of the domain. The connections are no permanently suspended because if load balance takes place the destination boundary may be part of the new domain representation therefore the connection would exist.
bool get_connected_vertex_number_on_dst_boundary (Vector< double > &vertex_coordinates, const unsigned &dst_b_id, unsigned &vertex_number)
Computes the associated vertex number on the destination boundary.
bool unrefine_boundary (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, double &unrefinement_tolerance, const bool &check_only=false)
Helper function that performs the unrefinement process.
bool refine_boundary (Mesh *face_mesh_pt, Vector< Vector< double > > &vector_bnd_vertices, double &refinement_tolerance, const bool &check_only=false)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
bool apply_max_length_constraint (Mesh *face_mesh_pt, Vector< Vector< double > > &vector_bnd_vertices, double &max_length_constraint)
bool unrefine_boundary_constrained_by_target_area (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, double &unrefinement_tolerance, Vector< double > &area_constraint)
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
bool refine_boundary_constrained_by_target_area (MeshAsGeomObject *mesh_geom_obj_pt, Vector< Vector< double > > &vector_bnd_vertices, double &refinement_tolerance, Vector< double > &area_constraint)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
bool unrefine_shared_boundary_constrained_by_target_area (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, Vector< double > &area_constraint)
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. NOTE: This is the version that applies unrefinement to shared boundaries.
bool refine_shared_boundary_constrained_by_target_area (Vector< Vector< double > > &vector_bnd_vertices, Vector< double > &area_constraint)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. NOTE: This is the version that applies refinement to shared boundaries.
void initialise_boundary_refinement_data ()
Set all the flags to true (the default values)
void sort_nodes_on_shared_boundaries ()
Sort the nodes on shared boundaries so that the processors that share a boundary agree with the order of the nodes on the boundary.
void reset_shared_boundary_elements_and_nodes (const bool flush_elements=true, const bool update_elements=true, const bool flush_nodes=true, const bool update_nodes=true)
Re-establish the shared boundary elements after the adaptation process (the updating of shared nodes is optional and performed by default)
void reset_halo_haloed_scheme ()
In charge of. re-establish the halo(ed) scheme on all processors. Sends info. to create halo elements and nodes on the processors that need it. It uses and all to all communication strategy therefore must be called on all processors.
void compute_global_node_names_and_shared_nodes (Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Compute the names of the nodes on shared boundaries in this (my_rank) processor with other processors. Also compute the names of nodes on shared boundaries of other processors with other processors (useful when there is an element that requires to be sent to this (my_rank) processor because there is a shared node between this (my_rank) and other processors BUT there is not a shared boundary between this and the other processor.
void send_boundary_node_info_of_shared_nodes (Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Get the original boundaries to which is associated each shared node, and send the info. to the related processors. We need to do this so that at the reset of halo(ed) info. stage, the info. be already updated.
void reset_halo_haloed_scheme_helper (Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Node *> > &iproc_currently_created_nodes_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
In charge of creating additional halo(ed) elements on those processors that have no shared boundaries in common but have shared nodes.
unsigned try_to_add_element_pt_load_balance (Vector< FiniteElement *> &new_elements_on_domain, FiniteElement *&ele_pt)
Check if necessary to add the element to the new domain or if it has been previously added.
void get_required_elemental_information_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement *> > &f_haloed_ele_pt, FiniteElement *ele_pt)
Helper function to get the required elemental information from the element to be sent. This info. involves the association of the element to a boundary or region, and if its part of the halo(ed) elements within a processor.
unsigned try_to_add_node_pt_load_balance (Vector< Node *> &new_nodes_on_domain, Node *&node_pt)
Check if necessary to add the node to the new domain or if it has been already added.
void add_node_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement *> > &f_halo_ele_pt, Vector< Node *> &new_nodes_on_domain, Node *nod_pt)
Helper function to add haloed node.
void get_required_nodal_information_load_balance_helper (Vector< Vector< FiniteElement *> > &f_halo_ele_pt, unsigned &iproc, Node *nod_pt)
Helper function to get the required nodal information from an haloed node so that a fully-functional node (and therefore element) can be created on the receiving process (this is the specific version for the load balance strategy, the difference with the original method is that it checks if the node is on a shared boundary no associated with the current processor --my_rank--, or in a haloed element from other processors.
void create_element_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement *> > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > &received_old_haloed_element_pt, Vector< FiniteElement *> &new_elements_on_domain, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info.
void add_element_load_balance_helper (const unsigned &iproc, Vector< Vector< std::map< unsigned, FiniteElement *> > > &received_old_haloed_element_pt, FiniteElement *ele_pt)
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info This function is in charge of verify if the element is associated to a boundary and associate to it if that is the case.
void add_received_node_load_balance_helper (Node *&new_nod_pt, Vector< Vector< FiniteElement *> > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > &received_old_haloed_element_pt, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function to add a new node from load balance.
void construct_new_node_load_balance_helper (Node *&new_nod_pt, Vector< Vector< FiniteElement *> > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > &received_old_haloed_element_pt, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function which constructs a new node (on an element) with the information sent from the load balance process.
unsigned try_to_add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Check if necessary to add the element as haloed or if it has been previously added to the haloed scheme.
unsigned try_to_add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Check if necessary to add the node as haloed or if it has been previously added to the haloed scheme.
void get_required_elemental_information_helper (unsigned &iproc, FiniteElement *ele_pt)
Helper function to get the required elemental information from an haloed element. This info. involves the association of the element to a boundary or region.
void get_required_nodal_information_helper (unsigned &iproc, Node *nod_pt)
Helper function to get the required nodal information from a haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
void add_haloed_node_helper (unsigned &iproc, Node *nod_pt)
Helper function to add haloed node.
void send_and_receive_elements_nodes_info (int &send_proc, int &recv_proc)
Helper function to send back halo and haloed information.
void create_halo_element (unsigned &iproc, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info.
void add_halo_element_helper (unsigned &iproc, FiniteElement *ele_pt)
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info This function is in charge of verify if the element is associated to a boundary.
void add_halo_node_helper (Node *&new_nod_pt, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function to add halo node.
void construct_new_halo_node_helper (Node *&new_nod_pt, Vector< Node *> &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function which constructs a new halo node (on an element) with the information sent from the haloed process.
void update_other_proc_shd_bnd_node_helper (Node *&new_nod_pt, Vector< Vector< Vector< std::map< unsigned, Node *> > > > &other_proc_shd_bnd_node_pt, Vector< unsigned > &other_processor_1, Vector< unsigned > &other_processor_2, Vector< unsigned > &other_shared_boundaries, Vector< unsigned > &other_indexes, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node *> &global_shared_node_pt)
Helper function that assigns/updates the references to the node so that it can be found with any other reference. The return value indicates whether or not a node was found on the same reference.
bool update_polygon_using_face_mesh (TriangleMeshPolygon *polygon_pt, const bool &check_only=false)
Helper function that updates the input polygon's PSLG by using the end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon. Optional boolean is used to run it as test only (if true is specified as input) in which case polygon isn't actually modified. Returned boolean indicates if polygon was (or would have been -- if called with check_only=false) changed.
bool update_open_curve_using_face_mesh (TriangleMeshOpenCurve *open_polyline_pt, const bool &check_only=false)
Helper function that updates the input open curve by using end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the polylines. Optional boolean is used to run it as test only (if true is specified as input) in which case the polylines are not actually modified. Returned boolean indicates if polylines were (or would have been -- if called with check_only=false) changed.
virtual bool surface_remesh_for_inner_hole_boundaries (Vector< Vector< double > > &internal_point_coord, const bool &check_only=false)
Generate a new PSLG representation of the inner hole boundaries. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
void snap_nodes_onto_boundary (RefineableTriangleMesh< ELEMENT > *&new_mesh_pt, const unsigned &b)
Snap the boundary nodes onto any curvilinear boundaries.
void create_unsorted_face_mesh_representation (const unsigned &boundary_id, Mesh *face_mesh_pt)
Helper function Creates an unsorted face mesh representation from the specified boundary id. It means that the elements are not sorted along the boundary.
void create_sorted_face_mesh_representation (const unsigned &boundary_id, Mesh *face_mesh_pt, std::map< FiniteElement *, bool > &is_inverted, bool &inverted_face_mesh)
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary It also returns a map that indicated the inverted elements.
void get_face_mesh_representation (TriangleMeshPolygon *polygon_pt, Vector< Mesh *> &face_mesh_pt)
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an appxroximately even sub-division of the polygon.
void get_face_mesh_representation (TriangleMeshOpenCurve *open_polyline_pt, Vector< Mesh *> &face_mesh_pt)
Helper function to construct face mesh representation of open curves.
void update_polygon_after_restart (TriangleMeshPolygon *&polygon_pt)
Updates the polylines representation after restart.
void update_open_curve_after_restart (TriangleMeshOpenCurve *&open_curve_pt)
Updates the open curve representation after restart.
bool update_polygon_using_elements_area (TriangleMeshPolygon *&polygon_pt, const Vector< double > &target_area)
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
bool update_open_curve_using_elements_area (TriangleMeshOpenCurve *&open_curve_pt, const Vector< double > &target_area)
Updates the open curve but using the elements area instead of the default refinement and unrefinement methods.
bool update_shared_curve_using_elements_area (Vector< TriangleMeshPolyLine *> &vector_polyline_pt, const Vector< double > &target_areas)
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
void update_shared_curve_after_restart (Vector< TriangleMeshPolyLine *> &vector_polyline_pt)
Updates the shared polylines representation after restart.
void initialise_adaptation_data ()
Helper function to initialise data associated with adaptation.
void refine_triangulateio (TriangulateIO &triangulate_io, const Vector< double > &target_area, TriangulateIO &triangle_refine)
Build a new TriangulateIO object from previous TriangulateIO based on target area for each element.
double compute_area_target (const Vector< double > &elem_error, Vector< double > &target_area)
Compute target area based on the element's error and the error target; return minimum angle (in degrees)
Protected Attributes
std::map< unsigned, std::set< Vector< double > > > Boundary_connections_pt
A map that stores the vertices that receive connections, they are identified by the boundary number that receive the connection This is necessary for not erasing them on the adaptation process, specifically for the un-refinement process.
bool Do_boundary_unrefinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
bool Do_boundary_refinement_constrained_by_target_areas
Flag that enables or disables boundary refinement (true by default)
bool Do_shared_boundary_unrefinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
bool Do_shared_boundary_refinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
std::map< unsigned, Vector< Node * > > Sorted_shared_boundary_node_pt
Stores the nodes in the boundaries in the same order in all the processors Sorted_shared_boundary_node_pt[bnd_id][i-th node] = Node* It is a map since the boundary id may not start at zero.
Vector< double > Flat_packed_doubles
Vector of flat-packed doubles to be communicated with other processors.
unsigned Counter_for_flat_packed_doubles
Counter used when processing vector of flat-packed doubles.
Vector< unsigned > Flat_packed_unsigneds
Vector of flat-packed unsigneds to be communicated with other processors.
unsigned Counter_for_flat_packed_unsigneds
Counter used when processing vector of flat-packed unsigneds.
Vector< std::string > Flat_packed_unsigneds_string
Temporary vector of strings to enable full annotation of RefineableTriangleMesh comms.
unsigned Nbin_x_for_area_transfer
Number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned Nbin_y_for_area_transfer
Number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned Max_sample_points_for_limited_locate_zeta_during_target_area_transfer
Default value for max. number of sample points used for locate_zeta when transferring target areas using cgal-based sample point container.
double Max_element_size
Max permitted element size.
double Min_element_size
Min permitted element size.
double Min_permitted_angle
Min angle before remesh gets triggered.
bool Disable_projection
Enable/disable solution projection during adaptation.
bool Use_iterative_solver_for_projection
bool Print_timings_transfering_target_areas
Enable/disable printing timings for transfering target areas.
bool Print_timings_projection
Enable/disable printing timings for projection.
unsigned Print_timings_level_adaptation
The printing level for adaptation.
unsigned Print_timings_level_load_balance
The printing level for load balance.
MeshUpdateFctPt Mesh_update_fct_pt
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
InternalHolePointUpdateFctPt Internal_hole_point_update_fct_pt
Function pointer to function that can be set to update the position of the central point in internal holes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableTriangleMesh< ELEMENT >
Unstructured refineable Triangle Mesh.
Definition at line 2132 of file triangle_mesh.template.h.
Member Typedef Documentation
InternalHolePointUpdateFctPt
template<class ELEMENT>
typedef void(* oomph::RefineableTriangleMesh< ELEMENT >::InternalHolePointUpdateFctPt) (const unsigned &ihole, TriangleMeshPolygon *poly_pt)
Function pointer to a function that can generate a point within the ihole-th hole, so that this can be overloaded by the user if they have a better way of doing it than our clunky default. The function should update the components of the Vector poly_pt->internal_point()
Definition at line 2150 of file triangle_mesh.template.h.
MeshUpdateFctPt
template<class ELEMENT>
typedef void(* oomph::RefineableTriangleMesh< ELEMENT >::MeshUpdateFctPt) (Mesh *mesh_pt)
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 2142 of file triangle_mesh.template.h.
Constructor & Destructor Documentation
RefineableTriangleMesh() [1/3]
template<class ELEMENT>
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (TriangleMeshParameters & triangle_mesh_parameters, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Build mesh, based on the specifications on TriangleMeshParameters.
Definition at line 2157 of file triangle_mesh.template.h.
RefineableTriangleMesh() [2/3]
template<class ELEMENT>
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & poly_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & allow_automatic_creation_of_vertices_on_boundaries = true) [inline]
Build mesh, based on the polyfiles.
Definition at line 2173 of file triangle_mesh.template.h.
RefineableTriangleMesh() [3/3]
template<class ELEMENT>
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (const Vector< double > & target_area, TriangulateIO & triangulate_io, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & allow_automatic_creation_of_vertices_on_boundaries = true, OomphCommunicator * comm_pt = 0) [inline], [protected]
Build mesh from specified triangulation and associated target areas for elements in it NOTE: This is used ONLY during adaptation and should not be used as a method of constructing a TriangleMesh object in demo drivers!
Definition at line 2204 of file triangle_mesh.template.h.
References oomph::TriangleMeshParameters::Allow_automatic_creation_of_vertices_on_boundaries, oomph::TriangleHelper::clear_triangulateio(), oomph::TriangleHelper::initialise_triangulateio(), oomph::TriangleMeshParameters::set_communicator_pt(), oomph::triangulate(), and oomph::TriangleMeshParameters::Use_attributes.
 RefineableTriangleMesh()
template<class ELEMENT>
virtual oomph::RefineableTriangleMesh< ELEMENT >::~RefineableTriangleMesh () [inline], [virtual]
Empty Destructor.
Definition at line 2295 of file triangle_mesh.template.h.
Member Function Documentation
adapt()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::adapt (const Vector< double > & elem_error) [virtual]
Adapt mesh, based on elemental error provided.
Adapt problem based on specified elemental error estimates This function implement serial and parallel mesh adaptation, the sections for parallel mesh adaptation are clearly identified by checking whether the mesh is distributed or not
Implements oomph::RefineableMeshBase.
Definition at line 29348 of file triangle_mesh.template.cc.
References oomph::Problem::add_time_stepper_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt(), oomph::Mesh::boundary_node_pt(), oomph::TriangleHelper::clear_triangulateio(), oomph::TriangleHelper::deep_copy_of_triangulateio_representation(), oomph::BinArrayParameters::dimensions_of_bin_array(), oomph::TriangleMeshParameters::disable_automatic_creation_of_vertices_on_boundaries(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::disable_use_iterative_solver_for_projection(), oomph::Multi_domain_functions::Doc_full_stats, oomph::Multi_domain_functions::Doc_stats, oomph::Multi_domain_functions::Doc_timings, e, oomph::TriangleMeshParameters::element_area(), oomph::Mesh::element_pt(), oomph::Problem::enable_problem_distributed(), oomph::TriangleMeshParameters::enable_use_attributes(), oomph::SamplePointContainerParameters::enable_use_eulerian_coordinates_during_setup(), oomph::TriangleMeshParameters::extra_holes_coordinates(), oomph::Mesh::face_index_at_boundary(), oomph::UnstructuredTwoDMeshGeometryBase::face_index_at_boundary_in_region(), NonRefineableBinArray::fill_bin_by_diffusion(), oomph::Mesh::finite_element_pt(), oomph::Mesh::flush_element_and_node_storage(), NonRefineableBinArray::get_all_bins_content(), NonRefineableBinArray::get_bin(), NonRefineableBinArray::get_fill_stats(), i, oomph::TriangleMeshParameters::internal_closed_curve_pt(), oomph::TriangleMeshParameters::internal_open_curves_pt(), oomph::GeneralisedElement::is_halo(), oomph::RefineableTriangleMesh< ELEMENT >::max_element_size(), oomph::Problem::mesh_pt(), oomph::RefineableTriangleMesh< ELEMENT >::min_element_size(), oomph::RefineableTriangleMesh< ELEMENT >::min_permitted_angle(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::UnstructuredTwoDMeshGeometryBase::nboundary_element_in_region(), oomph::Mesh::nboundary_node(), oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::UnstructuredTwoDMeshGeometryBase::nregion(), oomph::UnstructuredTwoDMeshGeometryBase::nregion_element(), oomph::oomph_info, oomph::TriangleMesh< ELEMENT >::oomph_vertex_nodes_id(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::UnstructuredTwoDMeshGeometryBase::region_attribute(), oomph::UnstructuredTwoDMeshGeometryBase::region_element_pt(), oomph::TriangleMeshParameters::regions_coordinates(), oomph::Node::remove_from_boundary(), s, oomph::TriangleMeshParameters::set_communicator_pt(), oomph::TriangleMesh< ELEMENT >::set_mesh_level_time_stepper(), oomph::Mesh::set_nodal_and_elemental_time_stepper(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundary_overlaps_internal_boundary(), oomph::FiniteElement::size(), oomph::TimingHelpers::timer(), oomph::TriangleMeshBase::triangulateio_representation(), and oomph::Node::x().
add_element_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_element_load_balance_helper (const unsigned & iproc, Vector< Vector< std::map< unsigned, FiniteElement *> > > & received_old_haloed_element_pt, FiniteElement * ele_pt) [protected]
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info This function is in charge of verify if the element is associated to a boundary and associate to it if that is the case.
Definition at line 27316 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_received_node_load_balance_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_element_load_balance_helper().
add_halo_element_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_halo_element_helper (unsigned & iproc, FiniteElement * ele_pt) [protected]
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info This function is in charge of verify if the element is associated to a boundary.
Definition at line 18963 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_halo_node_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_halo_element().
add_halo_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_halo_node_helper (Node *& new_nod_pt, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function to add halo node.
Definition at line 19132 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::FiniteElement::node_pt(), and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_halo_element_helper().
add_haloed_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_haloed_node_helper (unsigned & iproc, Node * nod_pt) [protected]
Helper function to add haloed node.
Helper to add external haloed node that is not a master.
Definition at line 18700 of file triangle_mesh.template.cc.
References oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::Missing_masters_functions::get_required_nodal_information_helper(), and oomph::RefineableTriangleMesh< ELEMENT >::send_and_receive_elements_nodes_info().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper().
add_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_node_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement *> > & f_halo_ele_pt, Vector< Node *> & new_nodes_on_domain, Node * nod_pt) [protected]
Helper function to add haloed node.
Helper function to add nodes on a new domain as a result of load balance.
Definition at line 26475 of file triangle_mesh.template.cc.
References oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, and oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_load_balance_helper().
add_non_delete_vertices_from_boundary_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_non_delete_vertices_from_boundary_helper (Vector< Vector< Node *> > src_bound_segment_node_pt, Vector< Vector< Node *> > dst_bound_segment_node_pt, const unsigned & dst_bnd_id, const unsigned & dst_bnd_chunk) [protected]
Adds the vertices from the sources boundary that are repeated in the destination boundary to the list of non delete-able vertices in the destination boundary.
Definition at line 32325 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::synchronize_shared_boundary_connections(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_vertices_for_non_deletion().
add_received_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_received_node_load_balance_helper (Node *& new_nod_pt, Vector< Vector< FiniteElement *> > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > & received_old_haloed_element_pt, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function to add a new node from load balance.
Definition at line 27581 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::FiniteElement::node_pt(), and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_element_load_balance_helper().
add_vertices_for_non_deletion()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_vertices_for_non_deletion () [protected]
Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_chunk_connections_pt structure.
\ short Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_connections_pt structure
Definition at line 31602 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_non_delete_vertices_from_boundary_helper(), oomph::TriangleMeshPolyLine::boundary_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshPolygon::polyline_pt(), and oomph::TriangleMeshOpenCurve::polyline_pt().
apply_max_length_constraint()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::apply_max_length_constraint (Mesh * face_mesh_pt, Vector< Vector< double > > & vector_bnd_vertices, double & max_length_constraint) [protected]
Get the size of the vector that now includes all added nodes
Definition at line 35283 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::create_unsorted_face_mesh_representation(), i, oomph::MeshAsGeomObject::position(), and s.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary().
boundary_connections()
template<class ELEMENT>
const bool oomph::RefineableTriangleMesh< ELEMENT >::boundary_connections (const unsigned & b, const unsigned & c, std::set< Vector< double > > & vertices) [inline], [protected]
Verifies if the given boundary receives a connection, and if that is the case then returns the list of vertices that receive the connections.
Definition at line 2768 of file triangle_mesh.template.h.
compute_area_target()
template<class ELEMENT>
double oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target (const Vector< double > & elem_error, Vector< double > & target_area) [inline], [protected]
Compute target area based on the element's error and the error target; return minimum angle (in degrees)
Definition at line 3544 of file triangle_mesh.template.h.
References e, oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::MathematicalConstants::Pi, oomph::TriangleMeshParameters::Regions_areas, oomph::FiniteElement::size(), and oomph::Node::x().
compute_global_node_names_and_shared_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes (Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Compute the names of the nodes on shared boundaries in this (my_rank) processor with other processors. Also compute the names of nodes on shared boundaries of other processors with other processors (useful when there is an element that requires to be sent to this (my_rank) processor because there is a shared node between this (my_rank) and other processors BUT there is not a shared boundary between this and the other processor.
Definition at line 15898 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::RefineableTriangleMesh< ELEMENT >::send_boundary_node_info_of_shared_nodes(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme().
compute_shared_node_degree_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::compute_shared_node_degree_helper (Vector< Vector< FiniteElement *> > & unsorted_face_ele_pt, std::map< Node *, unsigned > & global_node_degree)
Computes the degree of the nodes on the shared boundaries, the degree of the node is computed from the global graph created by the shared boundaries of all processors.
Definition at line 24593 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::create_adjacency_matrix_new_shared_edges_helper(), and i.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries().
construct_new_halo_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper (Node *& new_nod_pt, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function which constructs a new halo node (on an element) with the information sent from the haloed process.
The first entry of All_alg_nodal_info contains the default node update id e.g. for the quarter circle there are `Upper_left_box`, `Lower right box` etc...
again we need the size of this vector as it varies between meshes; we also need some indication as to which geometric object should be used...
For the received update_id, ref_value, geom_object call add_node_update_info
Now call update_node_update
Definition at line 19187 of file triangle_mesh.template.cc.
References oomph::AlgebraicNode::add_node_update_info(), oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), oomph::Multi_domain_functions::Counter_for_flat_packed_doubles, oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::MacroElementNodeUpdateMesh::geom_object_vector_pt(), i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element_pt(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::oomph_info, oomph::SolidNode::read_values_from_vector(), oomph::Node::resize(), oomph::Node::set_coordinates_on_boundary(), oomph::MacroElementNodeUpdateNode::set_node_update_info(), oomph::Data::set_value(), t, oomph::AlgebraicMesh::update_node_update(), oomph::RefineableTriangleMesh< ELEMENT >::update_other_proc_shd_bnd_node_helper(), oomph::SolidNode::variable_position_pt(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_halo_node_helper().
construct_new_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper (Node *& new_nod_pt, Vector< Vector< FiniteElement *> > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > & received_old_haloed_element_pt, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function which constructs a new node (on an element) with the information sent from the load balance process.
The first entry of All_alg_nodal_info contains the default node update id e.g. for the quarter circle there are `Upper_left_box`, `Lower right box` etc...
again we need the size of this vector as it varies between meshes; we also need some indication as to which geometric object should be used...
For the received update_id, ref_value, geom_object call add_node_update_info
Now call update_node_update
Definition at line 27652 of file triangle_mesh.template.cc.
References oomph::AlgebraicNode::add_node_update_info(), oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), oomph::Multi_domain_functions::Counter_for_flat_packed_doubles, oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::MacroElementNodeUpdateMesh::geom_object_vector_pt(), i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element_pt(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::oomph_info, oomph::SolidNode::read_values_from_vector(), oomph::Node::resize(), oomph::Node::set_coordinates_on_boundary(), oomph::MacroElementNodeUpdateNode::set_node_update_info(), oomph::Data::set_value(), t, oomph::AlgebraicMesh::update_node_update(), oomph::SolidNode::variable_position_pt(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_received_node_load_balance_helper().
create_adjacency_matrix_new_shared_edges_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_adjacency_matrix_new_shared_edges_helper (Vector< Vector< FiniteElement *> > & unsorted_face_ele_pt, Vector< Vector< Node *> > & tmp_sorted_shared_node_pt, std::map< Node *, Vector< Vector< unsigned > > > & node_alias, Vector< Vector< Vector< unsigned > > > & adjacency_matrix)
Sort the nodes on the new shared boundaries (after load balancing), computes the alias of the nodes and creates the adjacency matrix that represent the graph created by the shared edges between each pair of processors.
Definition at line 25591 of file triangle_mesh.template.cc.
References e, oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_segment_nodes_helper(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::compute_shared_node_degree_helper().
create_element_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_element_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement *> > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement *> > > & received_old_haloed_element_pt, Vector< FiniteElement *> & new_elements_on_domain, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info.
Definition at line 27231 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_element_load_balance_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::FiniteElement::nnode(), and oomph::oomph_info.
create_halo_element()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_halo_element (unsigned & iproc, Vector< Node *> & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info.
Creates (halo) element on the loop process based on the information received from each processor
Definition at line 18871 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_halo_element_helper(), oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::FiniteElement::nnode(), and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::send_and_receive_elements_nodes_info().
create_new_shared_boundaries()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries (std::set< FiniteElement *> & element_in_processor_pt, Vector< Vector< FiniteElement *> > & new_shared_boundary_element_pt, Vector< Vector< unsigned > > & new_shared_boundary_element_face_index)
Creates the new shared boundaries, this method is also in charge of computing the shared boundaries ids of each processor and send that info. to all the processors.
Definition at line 22466 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::compute_shared_node_degree_helper(), e, oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::TriangleMeshCurveSection::set_final_vertex_connected(), oomph::TriangleMeshCurveSection::set_initial_vertex_connected(), oomph::TimingHelpers::timer(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_elements_and_face_indexes().
create_polylines_from_polyfiles()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_polylines_from_polyfiles (const std::string & node_file_name, const std::string & poly_file_name)
Helper function to create polylines and fill associate data.
Create the polylines and fill associate data structures, used when creating from a mesh from polyfiles
Definition at line 36397 of file triangle_mesh.template.cc.
References i, oomph::TriangleMeshPolyLine::nvertex(), oomph::Global_string_for_annotation::string(), oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_elements_area(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries().
create_sorted_face_mesh_representation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_sorted_face_mesh_representation (const unsigned & boundary_id, Mesh * face_mesh_pt, std::map< FiniteElement *, bool > & is_inverted, bool & inverted_face_mesh) [protected]
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary It also returns a map that indicated the inverted elements.
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary.
Definition at line 35438 of file triangle_mesh.template.cc.
References oomph::Mesh::add_element_pt(), e, oomph::Mesh::finite_element_pt(), oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshPolyLine::vertex_coordinate(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_unsorted_face_mesh_representation().
create_temporary_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_temporary_boundary_connections (Vector< TriangleMeshPolygon *> & tmp_outer_polygons_pt, Vector< TriangleMeshOpenCurve *> & tmp_open_curves_pt) [protected]
After unrefinement and refinement has taken place compute the new vertices numbers of the temporary representation of the.
Definition at line 32761 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolyLine::boundary_id(), i, oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshPolygon::polyline_pt(), and oomph::TriangleMeshOpenCurve::polyline_pt().
create_unsorted_face_mesh_representation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_unsorted_face_mesh_representation (const unsigned & boundary_id, Mesh * face_mesh_pt) [protected]
Helper function Creates an unsorted face mesh representation from the specified boundary id. It means that the elements are not sorted along the boundary.
Definition at line 35401 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::create_sorted_face_mesh_representation(), e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::apply_max_length_constraint().
disable_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2739 of file triangle_mesh.template.h.
disable_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_boundary_unrefinement_constrained_by_target_areas () [inline]
Definition at line 2733 of file triangle_mesh.template.h.
disable_iterative_solver_for_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_iterative_solver_for_projection () [inline]
Enables the use of an iterative solver for the projection problem
Definition at line 2363 of file triangle_mesh.template.h.
disable_print_timings_adaptation()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_print_timings_adaptation () [inline]
Disables printing of timings for adaptation.
Definition at line 2371 of file triangle_mesh.template.h.
disable_print_timings_load_balance()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_print_timings_load_balance () [inline]
Disables printing of timings for load balance.
Definition at line 2394 of file triangle_mesh.template.h.
disable_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_projection () [inline]
Disables the solution projection step during adaptation.
Definition at line 2312 of file triangle_mesh.template.h.
disable_shared_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_shared_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2753 of file triangle_mesh.template.h.
disable_shared_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_shared_boundary_unrefinement_constrained_by_target_areas () [inline]
Definition at line 2747 of file triangle_mesh.template.h.
disable_timings_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_timings_projection () [inline]
Disables info. and timings for projection.
Definition at line 2320 of file triangle_mesh.template.h.
disable_timings_tranfering_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::disable_timings_tranfering_target_areas () [inline]
Disables info. and timings for tranferring of target areas.
Definition at line 2304 of file triangle_mesh.template.h.
doc_adaptivity_targets()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::doc_adaptivity_targets (std::ostream & outfile) [inline], [virtual]
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
Definition at line 2413 of file triangle_mesh.template.h.
enable_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2736 of file triangle_mesh.template.h.
enable_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_boundary_unrefinement_constrained_by_target_areas () [inline]
Enable/disable unrefinement/refinement methods for original boundaries.
Definition at line 2730 of file triangle_mesh.template.h.
enable_iterative_solver_for_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_iterative_solver_for_projection () [inline]
Enables the use of an iterative solver for the projection problem
Definition at line 2358 of file triangle_mesh.template.h.
enable_print_timings_adaptation()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_print_timings_adaptation (const unsigned & print_level = 1) [inline]
Enables printing of timings for adaptation.
Definition at line 2367 of file triangle_mesh.template.h.
enable_print_timings_load_balance()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_print_timings_load_balance (const unsigned & print_level = 1) [inline]
Enables printing of timings for load balance.
Definition at line 2390 of file triangle_mesh.template.h.
enable_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_projection () [inline]
Enables the solution projection step during adaptation.
Definition at line 2308 of file triangle_mesh.template.h.
enable_shared_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_shared_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2750 of file triangle_mesh.template.h.
enable_shared_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_shared_boundary_unrefinement_constrained_by_target_areas () [inline]
Enable/disable unrefinement/refinement methods for shared boundaries.
Definition at line 2744 of file triangle_mesh.template.h.
enable_timings_projection()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_timings_projection () [inline]
Enables info. and timings for projection.
Definition at line 2316 of file triangle_mesh.template.h.
enable_timings_tranfering_target_areas()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::enable_timings_tranfering_target_areas () [inline]
Enables info. and timings for tranferring of target areas.
Definition at line 2299 of file triangle_mesh.template.h.
fill_boundary_elements_and_nodes_for_internal_boundaries() [1/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries ()
Definition at line 43096 of file triangle_mesh.template.cc.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_after_restart().
fill_boundary_elements_and_nodes_for_internal_boundaries() [2/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries (std::ofstream & outfile)
Definition at line 43109 of file triangle_mesh.template.cc.
References i.
flush_sorted_shared_boundary_node()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::flush_sorted_shared_boundary_node () [inline]
Definition at line 2504 of file triangle_mesh.template.h.
get_boundary_segment_nodes_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_boundary_segment_nodes_helper (const unsigned & b, Vector< Vector< Node *> > & tmp_segment_nodes)
Get the nodes on the boundary (b), these are stored in the segment they belong (also used by the load balance method to re-set the number of segments per boundary after load balance has taken place)
Definition at line 28824 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_connected_vertex_number_on_dst_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::get_connected_vertex_number_on_dst_boundary (Vector< double > & vertex_coordinates, const unsigned & dst_b_id, unsigned & vertex_number) [protected]
Computes the associated vertex number on the destination boundary.
Gets the associated vertex number according to the vertex coordinates on the destination boundary.
Definition at line 33824 of file triangle_mesh.template.cc.
References i, oomph::TriangleMeshPolyLine::nvertex(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_face_mesh(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::resume_boundary_connections().
get_face_mesh_representation() [1/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation (TriangleMeshPolygon * polygon_pt, Vector< Mesh *> & face_mesh_pt) [protected]
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an appxroximately even sub-division of the polygon.
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an approximately even sub-division of the polygon
Definition at line 35635 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolyLine::boundary_id(), e, i, oomph::TriangleMeshPolygon::is_redistribution_of_segments_between_polylines_enabled(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshPolygon::polyline_pt(), s, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_sorted_face_mesh_representation().
get_face_mesh_representation() [2/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation (TriangleMeshOpenCurve * open_polyline_pt, Vector< Mesh *> & face_mesh_pt) [protected]
Helper function to construct face mesh representation of open curves.
Helper function to construct face mesh representation of all polylines.
Definition at line 36175 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::TriangleMeshCurve::ncurve_section(), and oomph::RefineableTriangleMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries().
get_required_elemental_information_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_helper (unsigned & iproc, FiniteElement * ele_pt) [protected]
Helper function to get the required elemental information from an haloed element. This info. involves the association of the element to a boundary or region.
Definition at line 17800 of file triangle_mesh.template.cc.
References e, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper(), and i.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme_helper().
get_required_elemental_information_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement *> > & f_haloed_ele_pt, FiniteElement * ele_pt) [protected]
Helper function to get the required elemental information from the element to be sent. This info. involves the association of the element to a boundary or region, and if its part of the halo(ed) elements within a processor.
Helper function to get the required elemental information from the element that will be sent to iproc processor. This info. involves the association of the element to a boundary or region.
Definition at line 26104 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_node_load_balance_helper(), e, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, and i.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_segment_nodes_helper().
get_required_nodal_information_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper (unsigned & iproc, Node * nod_pt) [protected]
Helper function to get the required nodal information from a haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
Helper function to get the required nodal information from an haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process
Definition at line 18121 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::add_haloed_node_helper(), oomph::SolidNode::add_values_to_vector(), oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::AlgebraicMesh::geom_object_list_pt(), oomph::AlgebraicNode::geom_object_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::Node::is_on_boundary(), oomph::Node::ndim(), oomph::AlgebraicNode::ngeom_object(), oomph::AlgebraicMesh::ngeom_object_list_pt(), oomph::AlgebraicNode::node_update_fct_id(), oomph::AlgebraicNode::nref_value(), oomph::Data::nvalue(), oomph::AlgebraicNode::ref_value(), t, oomph::Node::value(), oomph::SolidNode::variable_position_pt(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_helper().
get_required_nodal_information_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper (Vector< Vector< FiniteElement *> > & f_halo_ele_pt, unsigned & iproc, Node * nod_pt) [protected]
Helper function to get the required nodal information from an haloed node so that a fully-functional node (and therefore element) can be created on the receiving process (this is the specific version for the load balance strategy, the difference with the original method is that it checks if the node is on a shared boundary no associated with the current processor --my_rank--, or in a haloed element from other processors.
Helper function to get the required nodal information from an haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process
Definition at line 26534 of file triangle_mesh.template.cc.
References oomph::SolidNode::add_values_to_vector(), oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::AlgebraicMesh::geom_object_list_pt(), oomph::AlgebraicNode::geom_object_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::Node::is_on_boundary(), oomph::Node::ndim(), oomph::AlgebraicNode::ngeom_object(), oomph::AlgebraicMesh::ngeom_object_list_pt(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::AlgebraicNode::node_update_fct_id(), oomph::AlgebraicNode::nref_value(), oomph::Data::nvalue(), oomph::AlgebraicNode::ref_value(), t, oomph::Node::value(), oomph::SolidNode::variable_position_pt(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_node_load_balance_helper().
get_shared_boundary_elements_and_face_indexes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_elements_and_face_indexes (const Vector< FiniteElement *> & first_element_pt, const Vector< FiniteElement *> & second_element_pt, Vector< FiniteElement *> & first_shared_boundary_element_pt, Vector< unsigned > & first_shared_boundary_element_face_index, Vector< FiniteElement *> & second_shared_boundary_element_pt, Vector< unsigned > & second_shared_boundary_element_face_index)
Use the first and second group of elements to find the intersection between them to get the shared boundary elements from the first and second group.
Use the first and second group of elements to find the intersection between them to get the shared boundary elements from the first and second group
Definition at line 22311 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries(), oomph::GeneralisedElement::is_halo(), and oomph::FiniteElement::node_pt().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::load_balance().
get_shared_boundary_segment_nodes_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_segment_nodes_helper (const unsigned & shd_bnd_id, Vector< Vector< Node *> > & tmp_segment_nodes)
Get the nodes on the shared boundary (b), these are stored in the segment they belong.
Definition at line 25777 of file triangle_mesh.template.cc.
References e, oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_load_balance_helper(), oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_adjacency_matrix_new_shared_edges_helper().
initialise_adaptation_data()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::initialise_adaptation_data () [inline], [protected]
Helper function to initialise data associated with adaptation.
Definition at line 3480 of file triangle_mesh.template.h.
initialise_boundary_refinement_data()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::initialise_boundary_refinement_data () [inline], [protected]
Set all the flags to true (the default values)
Definition at line 2934 of file triangle_mesh.template.h.
internal_hole_point_update_fct_pt()
template<class ELEMENT>
InternalHolePointUpdateFctPt& oomph::RefineableTriangleMesh< ELEMENT >::internal_hole_point_update_fct_pt () [inline]
Access to function pointer to can be used to generate the internal point for the ihole-th hole.
Definition at line 2479 of file triangle_mesh.template.h.
load_balance()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::load_balance (const Vector< unsigned > & input_target_domain_for_local_non_halo_element) [virtual]
Performs the load balancing for unstructured meshes, the load balancing strategy is based on mesh migration.
Reimplemented from oomph::TriangleMesh< ELEMENT >.
Definition at line 20245 of file triangle_mesh.template.cc.
References oomph::Multi_domain_functions::Counter_for_flat_packed_doubles, oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, e, oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_elements_and_face_indexes(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::Node::set_non_obsolete(), and oomph::TimingHelpers::timer().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_other_proc_shd_bnd_node_helper().
max_element_size()
template<class ELEMENT>
double& oomph::RefineableTriangleMesh< ELEMENT >::max_element_size () [inline]
Max element size allowed during adaptation.
Definition at line 2343 of file triangle_mesh.template.h.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
max_sample_points_for_limited_locate_zeta_during_target_area_transfer()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::max_sample_points_for_limited_locate_zeta_during_target_area_transfer () [inline]
Read/write access to number of sample points from which we try to locate zeta by Newton method when transferring target areas using cgal-based sample point container. If Newton method doesn't converge from any of these we use the nearest sample point.
Definition at line 2337 of file triangle_mesh.template.h.
mesh_update_fct_pt()
template<class ELEMENT>
MeshUpdateFctPt& oomph::RefineableTriangleMesh< ELEMENT >::mesh_update_fct_pt () [inline]
Access to function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 2471 of file triangle_mesh.template.h.
min_element_size()
template<class ELEMENT>
double& oomph::RefineableTriangleMesh< ELEMENT >::min_element_size () [inline]
Min element size allowed during adaptation.
Definition at line 2346 of file triangle_mesh.template.h.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
min_permitted_angle()
template<class ELEMENT>
double& oomph::RefineableTriangleMesh< ELEMENT >::min_permitted_angle () [inline]
Min angle before remesh gets triggered.
Definition at line 2349 of file triangle_mesh.template.h.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
nbin_x_for_area_transfer()
template<class ELEMENT>
unsigned& oomph::RefineableTriangleMesh< ELEMENT >::nbin_x_for_area_transfer () [inline]
Read/write access to number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 2326 of file triangle_mesh.template.h.
nbin_y_for_area_transfer()
template<class ELEMENT>
unsigned& oomph::RefineableTriangleMesh< ELEMENT >::nbin_y_for_area_transfer () [inline]
Read/write access to number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 2331 of file triangle_mesh.template.h.
nsorted_shared_boundary_node()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::nsorted_shared_boundary_node (unsigned & b) [inline]
Definition at line 2488 of file triangle_mesh.template.h.
reestablish_distribution_info_for_restart()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::reestablish_distribution_info_for_restart (OomphCommunicator * comm_pt, std::istream & restart_file) [inline], [virtual]
Used to re-establish any additional info. related with the distribution after a re-starting for triangle meshes
Reimplemented from oomph::TriangleMesh< ELEMENT >.
Definition at line 2561 of file triangle_mesh.template.h.
References oomph::TriangleMeshParameters::is_mesh_distributed().
refine_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary (Mesh * face_mesh_pt, Vector< Vector< double > > & vector_bnd_vertices, double & refinement_tolerance, const bool & check_only = false) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
Get the size of the vector that now includes all added nodes
Definition at line 35133 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::apply_max_length_constraint(), i, and oomph::MeshAsGeomObject::position().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary().
refine_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary_constrained_by_target_area (MeshAsGeomObject * mesh_geom_obj_pt, Vector< Vector< double > > & vector_bnd_vertices, double & refinement_tolerance, Vector< double > & area_constraint) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area.
Definition at line 40523 of file triangle_mesh.template.cc.
References i, oomph::MeshAsGeomObject::position(), s, and oomph::RefineableTriangleMesh< ELEMENT >::unrefine_shared_boundary_constrained_by_target_area().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area().
refine_shared_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_shared_boundary_constrained_by_target_area (Vector< Vector< double > > & vector_bnd_vertices, Vector< double > & area_constraint) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. NOTE: This is the version that applies refinement to shared boundaries.
Definition at line 40877 of file triangle_mesh.template.cc.
References i, s, and oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_after_restart().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::unrefine_shared_boundary_constrained_by_target_area().
refine_triangulateio()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::refine_triangulateio (TriangulateIO & triangulate_io, const Vector< double > & target_area, TriangulateIO & triangle_refine) [protected]
Build a new TriangulateIO object from previous TriangulateIO based on target area for each element.
Build a new TriangulateIO object based on target areas specified.
Definition at line 14886 of file triangle_mesh.template.cc.
References oomph::TriangulateIO::holelist, oomph::TriangleHelper::initialise_triangulateio(), oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::TriangulateIO::trianglearealist, oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
refine_uniformly()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::refine_uniformly (DocInfo & doc_info) [inline], [virtual]
Refine mesh uniformly and doc process.
Implements oomph::RefineableMeshBase.
Definition at line 2429 of file triangle_mesh.template.h.
reset_halo_haloed_scheme()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme () [protected]
In charge of. re-establish the halo(ed) scheme on all processors. Sends info. to create halo elements and nodes on the processors that need it. It uses and all to all communication strategy therefore must be called on all processors.
Definition at line 15327 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes(), oomph::Multi_domain_functions::Counter_for_flat_packed_doubles, oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, oomph::DocInfo::disable_doc(), oomph::Global_timings::Doc_comprehensive_timings, e, oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, and oomph::TimingHelpers::timer().
reset_halo_haloed_scheme_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme_helper (Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Node *> > & iproc_currently_created_nodes_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
In charge of creating additional halo(ed) elements on those processors that have no shared boundaries in common but have shared nodes.
Definition at line 17463 of file triangle_mesh.template.cc.
References oomph::Multi_domain_functions::Counter_for_flat_packed_doubles, oomph::Multi_domain_functions::Counter_for_flat_packed_unsigneds, e, oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_helper(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::oomph_info.
reset_shared_boundary_elements_and_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_shared_boundary_elements_and_nodes (const bool flush_elements = true, const bool update_elements = true, const bool flush_nodes = true, const bool update_nodes = true) [protected]
Re-establish the shared boundary elements after the adaptation process (the updating of shared nodes is optional and performed by default)
Definition at line 15241 of file triangle_mesh.template.cc.
References e.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::sort_nodes_on_shared_boundaries().
restore_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::restore_boundary_connections (Vector< TriangleMeshPolyLine *> & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> & resume_final_connection_polyline_pt) [protected]
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended and resumed after the adaptation processor.
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended. It is not permanently deleted because if load balance takes place it may be possible that the boundary to connect be part of the new domain representation, so the connection would exist)
Definition at line 32888 of file triangle_mesh.template.cc.
References i, oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshPolygon::polyline_pt(), oomph::TriangleMeshOpenCurve::polyline_pt(), and oomph::RefineableTriangleMesh< ELEMENT >::restore_polyline_connections_helper().
restore_polyline_connections_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::restore_polyline_connections_helper (TriangleMeshPolyLine * polyline_pt, Vector< TriangleMeshPolyLine *> & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> & resume_final_connection_polyline_pt) [protected]
Restore the connections of the specific polyline The vertices numbering on the destination boundaries may have change because of (un)refinement in the destination boundaries. Also deals with connection that do not longer exist because the destination boundary does no longer exist because of the distribution process.
Definition at line 33012 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolyLine::boundary_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), oomph::TriangleMeshPolyLine::nvertex(), oomph::TriangleMeshCurveSection::suspend_final_vertex_connected(), oomph::TriangleMeshCurveSection::suspend_initial_vertex_connected(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::restore_boundary_connections().
resume_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::resume_boundary_connections (Vector< TriangleMeshPolyLine *> & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine *> & resume_final_connection_polyline_pt) [protected]
Resume the boundary connections that may have been suspended because the destination boundary is no part of the domain. The connections are no permanently suspended because if load balance takes place the destination boundary may be part of the new domain representation therefore the connection would exist.
Definition at line 33778 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::get_connected_vertex_number_on_dst_boundary(), oomph::TriangleMeshCurveSection::resume_final_vertex_connected(), and oomph::TriangleMeshCurveSection::resume_initial_vertex_connected().
send_and_receive_elements_nodes_info()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::send_and_receive_elements_nodes_info (int & send_proc, int & recv_proc) [protected]
Helper function to send back halo and haloed information.
Send the information of the elements that will be created on the other processor
Definition at line 18753 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::create_halo_element(), oomph::Multi_domain_functions::Flat_packed_doubles, oomph::Multi_domain_functions::Flat_packed_unsigneds, oomph::Missing_masters_functions::Flat_packed_unsigneds_string, i, and oomph::oomph_info.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_haloed_node_helper().
send_boundary_node_info_of_shared_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::send_boundary_node_info_of_shared_nodes (Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Get the original boundaries to which is associated each shared node, and send the info. to the related processors. We need to do this so that at the reset of halo(ed) info. stage, the info. be already updated.
Definition at line 16898 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::Node::is_on_boundary(), oomph::Node::set_coordinates_on_boundary(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes().
set_print_level_timings_adaptation()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::set_print_level_timings_adaptation (const unsigned & print_level) [inline]
Sets the printing level of timings for adaptation.
Definition at line 2375 of file triangle_mesh.template.h.
set_print_level_timings_load_balance()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::set_print_level_timings_load_balance (const unsigned & print_level) [inline]
Sets the printing level of timings for load balance.
Definition at line 2398 of file triangle_mesh.template.h.
snap_nodes_onto_boundary()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary (RefineableTriangleMesh< ELEMENT > *& new_mesh_pt, const unsigned & b) [protected]
Snap the boundary nodes onto any curvilinear boundaries.
Move the boundary nodes onto the boundary defined by the old mesh. Correct!? Because assigned again below
Repositioning of mid-side nodes
Definition at line 43322 of file triangle_mesh.template.cc.
References oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt(), e, oomph::Mesh::flush_node_storage(), oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::Node::is_on_boundary(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment(), oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment_node(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::MeshAsGeomObject::position(), s, oomph::FiniteElement::size(), and oomph::Node::x().
sort_nodes_on_shared_boundaries()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::sort_nodes_on_shared_boundaries () [protected]
Sort the nodes on shared boundaries so that the processors that share a boundary agree with the order of the nodes on the boundary.
Definition at line 15131 of file triangle_mesh.template.cc.
References oomph::Bottom_left_sorter, i, oomph::RefineableTriangleMesh< ELEMENT >::reset_shared_boundary_elements_and_nodes(), oomph::classcomp::Tol, and oomph::Node::x().
sorted_shared_boundary_node_pt() [1/2]
template<class ELEMENT>
Node* oomph::RefineableTriangleMesh< ELEMENT >::sorted_shared_boundary_node_pt (unsigned & b, unsigned & i) [inline]
Definition at line 2507 of file triangle_mesh.template.h.
sorted_shared_boundary_node_pt() [2/2]
template<class ELEMENT>
Vector<Node*> oomph::RefineableTriangleMesh< ELEMENT >::sorted_shared_boundary_node_pt (unsigned & b) [inline]
Definition at line 2524 of file triangle_mesh.template.h.
References oomph::Global_string_for_annotation::string().
surface_remesh_for_inner_hole_boundaries()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries (Vector< Vector< double > > & internal_point_coord, const bool & check_only = false) [protected], [virtual]
Generate a new PSLG representation of the inner hole boundaries. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
Update the PSLG that define the inner boundaries of the mesh. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
Definition at line 36208 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolygon::can_update_reference_configuration(), oomph::RefineableTriangleMesh< ELEMENT >::create_polylines_from_polyfiles(), i, oomph::TriangleMeshClosedCurve::internal_point(), oomph::TriangleMeshClosedCurve::is_internal_point_fixed(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshPolyLine::nvertex(), oomph::TriangleMeshPolygon::polyline_pt(), oomph::TriangleMeshPolygon::reset_reference_configuration(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation().
synchronize_shared_boundary_connections()
template<class ELEMENT >
const void oomph::RefineableTriangleMesh< ELEMENT >::synchronize_shared_boundary_connections () [protected]
Synchronise the vertices that are marked for non deletion.
Definition at line 32412 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolyLine::boundary_chunk(), and i.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::add_non_delete_vertices_from_boundary_helper().
try_to_add_element_pt_load_balance()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_element_pt_load_balance (Vector< FiniteElement *> & new_elements_on_domain, FiniteElement *& ele_pt) [inline], [protected]
Check if necessary to add the element to the new domain or if it has been previously added.
Definition at line 3020 of file triangle_mesh.template.h.
References e.
try_to_add_haloed_node_pt()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_haloed_node_pt (const unsigned & p, Node *& nod_pt) [inline], [protected], [virtual]
Check if necessary to add the node as haloed or if it has been previously added to the haloed scheme.
Reimplemented from oomph::Mesh.
Definition at line 3265 of file triangle_mesh.template.h.
References oomph::Missing_masters_functions::get_required_nodal_information_helper().
try_to_add_node_pt_load_balance()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_node_pt_load_balance (Vector< Node *> & new_nodes_on_domain, Node *& node_pt) [inline], [protected]
Check if necessary to add the node to the new domain or if it has been already added.
Definition at line 3070 of file triangle_mesh.template.h.
try_to_add_root_haloed_element_pt()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_root_haloed_element_pt (const unsigned & p, GeneralisedElement *& el_pt) [inline], [protected], [virtual]
Check if necessary to add the element as haloed or if it has been previously added to the haloed scheme.
Reimplemented from oomph::Mesh.
Definition at line 3227 of file triangle_mesh.template.h.
unrefine_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, double & unrefinement_tolerance, const bool & check_only = false) [protected]
Helper function that performs the unrefinement process.
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed. Get the size of the vector that now includes all remaining nodes
Copy back
Definition at line 34848 of file triangle_mesh.template.cc.
References e, i, oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh().
unrefine_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, double & unrefinement_tolerance, Vector< double > & area_constraint) [protected]
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area.
Definition at line 40268 of file triangle_mesh.template.cc.
References e, i, oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary_constrained_by_target_area(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_using_elements_area().
unrefine_shared_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_shared_boundary_constrained_by_target_area (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, Vector< double > & area_constraint) [protected]
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. NOTE: This is the version that applies unrefinement to shared boundaries.
Definition at line 40667 of file triangle_mesh.template.cc.
References i, oomph::RefineableTriangleMesh< ELEMENT >::refine_shared_boundary_constrained_by_target_area(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary_constrained_by_target_area().
unrefine_uniformly()
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::unrefine_uniformly () [inline], [virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
Definition at line 2455 of file triangle_mesh.template.h.
update_open_curve_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart (TriangleMeshOpenCurve *& open_curve_pt) [protected]
Updates the open curve representation after restart.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split bn the distribution process. Internal boundaries may be completely or partially overlapped by shared boundaries
Definition at line 41735 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::TriangleMeshCurve::ncurve_section(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshCurveSection::nvertex(), oomph::TriangleMeshOpenCurve::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::unrefinement_tolerance(), oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_after_restart(), oomph::TriangleMeshPolyLine::vertex_coordinate(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_after_restart().
update_open_curve_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area (TriangleMeshOpenCurve *& open_curve_pt, const Vector< double > & target_area) [protected]
Updates the open curve but using the elements area instead of the default refinement and unrefinement methods.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process. Internal boundaries may be completely or partially overlapped by shared boundaries
Definition at line 38367 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_chunk(), oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::TriangleMeshCurve::ncurve_section(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshCurveSection::nvertex(), oomph::TriangleMeshOpenCurve::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::unrefinement_tolerance(), oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_using_elements_area(), oomph::TriangleMeshPolyLine::vertex_coordinate(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_elements_area().
update_open_curve_using_face_mesh()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh (TriangleMeshOpenCurve * open_polyline_pt, const bool & check_only = false) [protected]
Helper function that updates the input open curve by using end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the polylines. Optional boolean is used to run it as test only (if true is specified as input) in which case the polylines are not actually modified. Returned boolean indicates if polylines were (or would have been -- if called with check_only=false) changed.
Refinement
Definition at line 34366 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_chunk(), oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), e, oomph::Node::get_coordinates_on_boundary(), i, oomph::TriangleMeshCurveSection::maximum_length(), oomph::TriangleMeshCurve::ncurve_section(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshOpenCurve::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary(), oomph::TriangleMeshCurveSection::unrefinement_tolerance(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_face_mesh().
update_other_proc_shd_bnd_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_other_proc_shd_bnd_node_helper (Node *& new_nod_pt, Vector< Vector< Vector< std::map< unsigned, Node *> > > > & other_proc_shd_bnd_node_pt, Vector< unsigned > & other_processor_1, Vector< unsigned > & other_processor_2, Vector< unsigned > & other_shared_boundaries, Vector< unsigned > & other_indexes, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node *> & global_shared_node_pt) [protected]
Helper function that assigns/updates the references to the node so that it can be found with any other reference. The return value indicates whether or not a node was found on the same reference.
Definition at line 20086 of file triangle_mesh.template.cc.
References oomph::RefineableTriangleMesh< ELEMENT >::load_balance().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper().
update_polygon_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_after_restart (TriangleMeshPolygon *& polygon_pt) [protected]
Updates the polylines representation after restart.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process
Definition at line 40981 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshCurveSection::nvertex(), oomph::TriangleMeshPolygon::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::unrefinement_tolerance(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::refine_shared_boundary_constrained_by_target_area().
update_polygon_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_elements_area (TriangleMeshPolygon *& polygon_pt, const Vector< double > & target_area) [protected]
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
Updates the polygon but using the elements area instead of the default refinement and unrefinement methods. Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process
Definition at line 37425 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_chunk(), oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshCurveSection::nvertex(), oomph::TriangleMeshPolygon::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::unrefinement_tolerance(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::create_polylines_from_polyfiles().
update_polygon_using_face_mesh()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_face_mesh (TriangleMeshPolygon * polygon_pt, const bool & check_only = false) [protected]
Helper function that updates the input polygon's PSLG by using the end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon. Optional boolean is used to run it as test only (if true is specified as input) in which case polygon isn't actually modified. Returned boolean indicates if polygon was (or would have been -- if called with check_only=false) changed.
Definition at line 33880 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::boundary_chunk(), oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), e, oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TriangleMeshPolygon::npolyline(), oomph::TriangleMeshCurveSection::nvertex(), oomph::TriangleMeshPolygon::polyline_pt(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshPolyLine::reverse(), oomph::TriangleMeshCurveSection::set_maximum_length(), oomph::TriangleMeshCurveSection::set_refinement_tolerance(), oomph::TriangleMeshCurveSection::set_unrefinement_tolerance(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::unrefinement_tolerance(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh(), and oomph::Node::x().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::get_connected_vertex_number_on_dst_boundary().
update_polyline_representation_from_restart()
template<class ELEMENT>
void oomph::RefineableTriangleMesh< ELEMENT >::update_polyline_representation_from_restart () [inline], [virtual]
Method used to update the polylines representation after restart.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 2613 of file triangle_mesh.template.h.
References oomph::TriangleMeshParameters::communicator_pt(), i, oomph::TriangleMeshParameters::is_mesh_distributed(), and oomph::TriangleMeshParameters::Outer_boundary_pt.
update_shared_curve_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_after_restart (Vector< TriangleMeshPolyLine *> & vector_polyline_pt) [protected]
Updates the shared polylines representation after restart.
Definition at line 42680 of file triangle_mesh.template.cc.
References e, oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries(), i, oomph::GeneralisedElement::is_halo(), and oomph::FiniteElement::node_pt().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart().
update_shared_curve_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_using_elements_area (Vector< TriangleMeshPolyLine *> & vector_polyline_pt, const Vector< double > & target_areas) [protected]
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
Definition at line 39611 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, and oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area().
use_iterative_solver_for_projection()
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::use_iterative_solver_for_projection () [inline]
Definition at line 2353 of file triangle_mesh.template.h.
Member Data Documentation
Boundary_connections_pt
template<class ELEMENT>
std::map<unsigned, std::set<Vector<double> > > oomph::RefineableTriangleMesh< ELEMENT >::Boundary_connections_pt [protected]
A map that stores the vertices that receive connections, they are identified by the boundary number that receive the connection This is necessary for not erasing them on the adaptation process, specifically for the un-refinement process.
Definition at line 2763 of file triangle_mesh.template.h.
Counter_for_flat_packed_doubles
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Counter_for_flat_packed_doubles [protected]
Counter used when processing vector of flat-packed doubles.
Definition at line 3201 of file triangle_mesh.template.h.
Counter_for_flat_packed_unsigneds
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Counter_for_flat_packed_unsigneds [protected]
Counter used when processing vector of flat-packed unsigneds.
Definition at line 3209 of file triangle_mesh.template.h.
Disable_projection
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Disable_projection [protected]
Enable/disable solution projection during adaptation.
Definition at line 3697 of file triangle_mesh.template.h.
Do_boundary_refinement_constrained_by_target_areas
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_boundary_refinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary refinement (true by default)
Definition at line 2925 of file triangle_mesh.template.h.
Do_boundary_unrefinement_constrained_by_target_areas
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_boundary_unrefinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 2922 of file triangle_mesh.template.h.
Do_shared_boundary_refinement_constrained_by_target_areas
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_shared_boundary_refinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 2931 of file triangle_mesh.template.h.
Do_shared_boundary_unrefinement_constrained_by_target_areas
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_shared_boundary_unrefinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 2928 of file triangle_mesh.template.h.
Flat_packed_doubles
template<class ELEMENT>
Vector<double> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_doubles [protected]
Vector of flat-packed doubles to be communicated with other processors.
Definition at line 3197 of file triangle_mesh.template.h.
Flat_packed_unsigneds
template<class ELEMENT>
Vector<unsigned> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_unsigneds [protected]
Vector of flat-packed unsigneds to be communicated with other processors.
Definition at line 3205 of file triangle_mesh.template.h.
Flat_packed_unsigneds_string
template<class ELEMENT>
Vector<std::string> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_unsigneds_string [protected]
Temporary vector of strings to enable full annotation of RefineableTriangleMesh comms.
Definition at line 3214 of file triangle_mesh.template.h.
Internal_hole_point_update_fct_pt
template<class ELEMENT>
InternalHolePointUpdateFctPt oomph::RefineableTriangleMesh< ELEMENT >::Internal_hole_point_update_fct_pt [protected]
Function pointer to function that can be set to update the position of the central point in internal holes.
Definition at line 3724 of file triangle_mesh.template.h.
Max_element_size
template<class ELEMENT>
double oomph::RefineableTriangleMesh< ELEMENT >::Max_element_size [protected]
Max permitted element size.
Definition at line 3688 of file triangle_mesh.template.h.
Max_sample_points_for_limited_locate_zeta_during_target_area_transfer
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Max_sample_points_for_limited_locate_zeta_during_target_area_transfer [protected]
Default value for max. number of sample points used for locate_zeta when transferring target areas using cgal-based sample point container.
Definition at line 3685 of file triangle_mesh.template.h.
Mesh_update_fct_pt
template<class ELEMENT>
MeshUpdateFctPt oomph::RefineableTriangleMesh< ELEMENT >::Mesh_update_fct_pt [protected]
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 3719 of file triangle_mesh.template.h.
Min_element_size
template<class ELEMENT>
double oomph::RefineableTriangleMesh< ELEMENT >::Min_element_size [protected]
Min permitted element size.
Definition at line 3691 of file triangle_mesh.template.h.
Min_permitted_angle
template<class ELEMENT>
double oomph::RefineableTriangleMesh< ELEMENT >::Min_permitted_angle [protected]
Min angle before remesh gets triggered.
Definition at line 3694 of file triangle_mesh.template.h.
Nbin_x_for_area_transfer
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Nbin_x_for_area_transfer [protected]
Number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 3676 of file triangle_mesh.template.h.
Nbin_y_for_area_transfer
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Nbin_y_for_area_transfer [protected]
Number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 3681 of file triangle_mesh.template.h.
Print_timings_level_adaptation
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_level_adaptation [protected]
The printing level for adaptation.
Definition at line 3710 of file triangle_mesh.template.h.
Print_timings_level_load_balance
template<class ELEMENT>
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_level_load_balance [protected]
The printing level for load balance.
Definition at line 3713 of file triangle_mesh.template.h.
Print_timings_projection
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_projection [protected]
Enable/disable printing timings for projection.
Definition at line 3707 of file triangle_mesh.template.h.
Print_timings_transfering_target_areas
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_transfering_target_areas [protected]
Enable/disable printing timings for transfering target areas.
Definition at line 3704 of file triangle_mesh.template.h.
Sorted_shared_boundary_node_pt
template<class ELEMENT>
std::map<unsigned, Vector<Node*> > oomph::RefineableTriangleMesh< ELEMENT >::Sorted_shared_boundary_node_pt [protected]
Stores the nodes in the boundaries in the same order in all the processors Sorted_shared_boundary_node_pt[bnd_id][i-th node] = Node* It is a map since the boundary id may not start at zero.
Definition at line 2949 of file triangle_mesh.template.h.
Use_iterative_solver_for_projection
template<class ELEMENT>
bool oomph::RefineableTriangleMesh< ELEMENT >::Use_iterative_solver_for_projection [protected]
Flag to indicate whether to use or not an iterative solver (CG with diagonal preconditioned) for the projection problem
Definition at line 3701 of file triangle_mesh.template.h.
The documentation for this class was generated from the following files:
triangle_mesh.template.h
triangle_mesh.template.cc