oomph::QElement< 1, NNODE_1D > Class Template Reference
General QElement class specialised to one spatial dimension.
#include <Qelements.h>
Public Member Functions
QElement ()
Constructor.
QElement (const QElement &)
Broken copy constructor.
void shape (const Vector< double > &s, Shape &psi) const
Broken assignment operator.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = $ d^2 \psi_j / d s^2 $.
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one-dimensional element, so use the 1D version.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Get the node at the specified local coordinate.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nplot_points_paraview (const unsigned &nplot) const
Return the number of actual plot points for paraview plot with parameter nplot.
unsigned nsub_elements_paraview (const unsigned &nplot) const
Return the number of local sub-elements for paraview plot with parameter nplot.
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf Use type `VTK_LINE` (== 3) for 2D quad elements.
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction)
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
Get a pointer to the function mapping face coordinates to bulk coordinates.
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Static Private Attributes
static Gauss< 1, NNODE_1D > Default_integration_scheme
Default integration rule: Gaussian integration of same 'order' as the element.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QElement< 1, NNODE_1D >
General QElement class specialised to one spatial dimension.
Definition at line 511 of file Qelements.h.
Constructor & Destructor Documentation
QElement() [1/2]
template<unsigned NNODE_1D>
oomph::QElement< 1, NNODE_1D >::QElement () [inline]
Constructor.
Definition at line 524 of file Qelements.h.
References oomph::FiniteElement::set_dimension(), oomph::FiniteElement::set_integration_scheme(), and oomph::FiniteElement::set_n_node().
QElement() [2/2]
template<unsigned NNODE_1D>
oomph::QElement< 1, NNODE_1D >::QElement (const QElement< 1, NNODE_1D > &) [inline]
Broken copy constructor.
Definition at line 535 of file Qelements.h.
References oomph::BrokenCopy::broken_copy(), oomph::FiniteElement::d2shape_local(), oomph::FiniteElement::dshape_local(), s, and oomph::FiniteElement::shape().
Member Function Documentation
bulk_coordinate_derivatives_fct_pt()
template<unsigned NNODE_1D>
BulkCoordinateDerivativesFctPt oomph::QElement< 1, NNODE_1D >::bulk_coordinate_derivatives_fct_pt (const int & face_index) const [inline], [virtual]
Get a pointer to the derivative of the mapping from face to bulk coordinates.
Reimplemented from oomph::FiniteElement.
Definition at line 804 of file Qelements.h.
References oomph::QElement1BulkCoordinateDerivatives::faces0(), and oomph::Global_string_for_annotation::string().
d2shape_local()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [virtual]
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = $ d^2 \psi_j / d s^2 $.
Second derivatives of shape functions for specific QElement<1,..>: d2psids(i,0) = $ d^2 \psi_j / d s^2 $
Reimplemented from oomph::FiniteElement.
Definition at line 144 of file Qelements.cc.
dshape_local()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [virtual]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Derivatives of shape functions for specific QElement<1,..>
Reimplemented from oomph::FiniteElement.
Definition at line 121 of file Qelements.cc.
face_outer_unit_normal_sign()
template<unsigned NNODE_1D>
int oomph::QElement< 1, NNODE_1D >::face_outer_unit_normal_sign (const int & face_index) const [inline], [virtual]
Get the sign of the outer unit normal on the face given by face_index.
Reimplemented from oomph::FiniteElement.
Definition at line 774 of file Qelements.h.
References oomph::FiniteElement::face_to_bulk_coordinate_fct_pt(), and oomph::Global_string_for_annotation::string().
face_to_bulk_coordinate_fct_pt()
template<unsigned NNODE_1D>
CoordinateMappingFctPt oomph::QElement< 1, NNODE_1D >::face_to_bulk_coordinate_fct_pt (const int & face_index) const [inline], [virtual]
Get a pointer to the function mapping face coordinates to bulk coordinates.
Reimplemented from oomph::FiniteElement.
Definition at line 789 of file Qelements.h.
References oomph::FiniteElement::bulk_coordinate_derivatives_fct_pt(), oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), and oomph::Global_string_for_annotation::string().
get_bulk_node_number()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::get_bulk_node_number (const int & face_index, const unsigned & i) const [inline], [virtual]
Get the number of the ith node on face face_index in the bulk node vector.
Reimplemented from oomph::FiniteElement.
Definition at line 758 of file Qelements.h.
References oomph::FiniteElement::face_node_number_error_check(), oomph::FiniteElement::nnode_1d(), and oomph::Global_string_for_annotation::string().
get_node_at_local_coordinate()
template<unsigned NNODE_1D>
Node * oomph::QElement< 1, NNODE_1D >::get_node_at_local_coordinate (const Vector< double > & s) const [virtual]
Get the node at the specified local coordinate.
Return the node at the specified local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 54 of file Qelements.cc.
References oomph::FiniteElement::Node_location_tolerance.
get_s_plot()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const [inline], [virtual]
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
Definition at line 714 of file Qelements.h.
invert_jacobian_mapping()
template<unsigned NNODE_1D>
double oomph::QElement< 1, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one-dimensional element, so use the 1D version.
Reimplemented from oomph::FiniteElement.
Definition at line 563 of file Qelements.h.
local_coordinate_of_node()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline], [virtual]
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
Definition at line 603 of file Qelements.h.
References oomph::FiniteElement::s_max(), and oomph::FiniteElement::s_min().
local_fraction_of_node()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::local_fraction_of_node (const unsigned & j, Vector< double > & s_fraction) [inline], [virtual]
Get the local fraction of node j in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 612 of file Qelements.h.
local_one_d_fraction_of_node()
template<unsigned NNODE_1D>
double oomph::QElement< 1, NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) [inline], [virtual]
This function returns the local fraction of all nodes at the n-th position in a one dimensional expansion along the i-th local coordinate
Reimplemented from oomph::FiniteElement.
Definition at line 622 of file Qelements.h.
References oomph::FiniteElement::get_node_at_local_coordinate().
nnode_1d()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::nnode_1d () const [inline], [virtual]
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 633 of file Qelements.h.
nplot_points()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 748 of file Qelements.h.
References i.
nplot_points_paraview()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::nplot_points_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of actual plot points for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 637 of file Qelements.h.
nsub_elements_paraview()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::nsub_elements_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of local sub-elements for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 644 of file Qelements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::QElement< 1, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::LineElementBase.
Definition at line 574 of file Qelements.h.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::output (std::ostream & outfile) [virtual]
Output.
The output function for general 1D QElements.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQElement< 1, NNODE_1D >.
Definition at line 169 of file Qelements.cc.
References oomph::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output at n_plot points.
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQElement< 1, NNODE_1D >.
Definition at line 178 of file Qelements.cc.
References i, and s.
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::output (FILE * file_pt) [virtual]
C-style output.
C style output function for general 1D QElements.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQElement< 1, NNODE_1D >.
Definition at line 210 of file Qelements.cc.
References oomph::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C_style output at n_plot points.
C style output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQElement< 1, NNODE_1D >.
Definition at line 219 of file Qelements.cc.
References i, and s.
s_max()
template<unsigned NNODE_1D>
double oomph::QElement< 1, NNODE_1D >::s_max () const [inline], [virtual]
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 571 of file Qelements.h.
s_min()
template<unsigned NNODE_1D>
double oomph::QElement< 1, NNODE_1D >::s_min () const [inline], [virtual]
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 568 of file Qelements.h.
shape()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const [virtual]
Broken assignment operator.
Shape function for specific QElement<1,..>
Calculate the geometric shape functions at local coordinate s
Implements oomph::FiniteElement.
Definition at line 104 of file Qelements.cc.
References i.
tecplot_zone_string()
template<unsigned NNODE_1D>
std::string oomph::QElement< 1, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 739 of file Qelements.h.
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::QElement< 1, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::LineElementBase.
Definition at line 578 of file Qelements.h.
References oomph::FiniteElement::nnode_1d(), and oomph::FiniteElement::node_pt().
write_paraview_offsets()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const [inline], [virtual]
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 686 of file Qelements.h.
References i, oomph::FiniteElement::nsub_elements_paraview(), and oomph::FiniteElement::output().
write_paraview_output_offset_information()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const [inline], [virtual]
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 652 of file Qelements.h.
References i, oomph::FiniteElement::nplot_points_paraview(), and oomph::FiniteElement::nsub_elements_paraview().
write_paraview_type()
template<unsigned NNODE_1D>
void oomph::QElement< 1, NNODE_1D >::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const [inline], [virtual]
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf Use type `VTK_LINE` (== 3) for 2D quad elements.
Reimplemented from oomph::FiniteElement.
Definition at line 673 of file Qelements.h.
References i, and oomph::FiniteElement::nsub_elements_paraview().
Member Data Documentation
Default_integration_scheme
template<unsigned NNODE_1D>
Gauss< 1, NNODE_1D > oomph::QElement< 1, NNODE_1D >::Default_integration_scheme [static], [private]
Default integration rule: Gaussian integration of same 'order' as the element.
Assign the static Default_integration_scheme.
Definition at line 519 of file Qelements.h.
The documentation for this class was generated from the following files:
Qelements.h
Qelements.cc