oomph::HelmholtzMGProblem Class Reference
HelmholtzMGProblem class; subclass of Problem.
#include <helmholtz_geometric_multigrid.h>
Public Member Functions
HelmholtzMGProblem ()
Constructor. Initialise pointers to coarser and finer levels.
virtual ~HelmholtzMGProblem ()
Destructor (empty)
virtual HelmholtzMGProblem * make_new_problem ()=0
This function needs to be implemented in the derived problem: Returns a pointer to a new object of the same type as the derived problem.
virtual TreeBasedRefineableMeshBase * mg_bulk_mesh_pt ()=0
Function to get a pointer to the mesh we will be working with. If there are flux elements present in the mesh this will be overloaded to return a pointer to the bulk mesh otherwise it can be overloaded to point to the global mesh but it must be of type RefineableMeshBase.
Additional Inherited Members
Detailed Description
HelmholtzMGProblem class; subclass of Problem.
Definition at line 25 of file helmholtz_geometric_multigrid.h.
Constructor & Destructor Documentation
HelmholtzMGProblem()
oomph::HelmholtzMGProblem::HelmholtzMGProblem () [inline]
Constructor. Initialise pointers to coarser and finer levels.
Definition at line 31 of file helmholtz_geometric_multigrid.h.
 HelmholtzMGProblem()
virtual oomph::HelmholtzMGProblem::~HelmholtzMGProblem () [inline], [virtual]
Destructor (empty)
Definition at line 35 of file helmholtz_geometric_multigrid.h.
References make_new_problem(), and mg_bulk_mesh_pt().
Member Function Documentation
make_new_problem()
virtual HelmholtzMGProblem* oomph::HelmholtzMGProblem::make_new_problem () [pure virtual]
This function needs to be implemented in the derived problem: Returns a pointer to a new object of the same type as the derived problem.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy(), and ~HelmholtzMGProblem().
mg_bulk_mesh_pt()
virtual TreeBasedRefineableMeshBase* oomph::HelmholtzMGProblem::mg_bulk_mesh_pt () [pure virtual]
Function to get a pointer to the mesh we will be working with. If there are flux elements present in the mesh this will be overloaded to return a pointer to the bulk mesh otherwise it can be overloaded to point to the global mesh but it must be of type RefineableMeshBase.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy(), and ~HelmholtzMGProblem().
The documentation for this class was generated from the following file:
helmholtz_geometric_multigrid.h