oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > Class Template Reference
Refineable version of QGeneralisedAdvectionDiffusionElement. Inherit from the standard QGeneralisedAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
#include <refineable_gen_advection_diffusion_elements.h>
Public Member Functions
RefineableQGeneralisedAdvectionDiffusionElement ()
Empty Constructor:
RefineableQGeneralisedAdvectionDiffusionElement (const RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &)
Broken assignment operator.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >
Refineable version of QGeneralisedAdvectionDiffusionElement. Inherit from the standard QGeneralisedAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
Definition at line 202 of file refineable_gen_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableQGeneralisedAdvectionDiffusionElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQGeneralisedAdvectionDiffusionElement () [inline]
Empty Constructor:
Definition at line 210 of file refineable_gen_advection_diffusion_elements.h.
RefineableQGeneralisedAdvectionDiffusionElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQGeneralisedAdvectionDiffusionElement (const RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 219 of file refineable_gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 256 of file refineable_gen_advection_diffusion_elements.h.
ncont_interpolated_values()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 235 of file refineable_gen_advection_diffusion_elements.h.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 252 of file refineable_gen_advection_diffusion_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 238 of file refineable_gen_advection_diffusion_elements.h.
References oomph::FiniteElement::nvertex_node().
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::operator= (const RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 228 of file refineable_gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
rebuild_from_sons()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 248 of file refineable_gen_advection_diffusion_elements.h.
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node* oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 243 of file refineable_gen_advection_diffusion_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_gen_advection_diffusion_elements.h