oomph::QAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
QAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Axisymmetric Advection Diffusion elements with isoparametric interpolation for the function.
#include <axisym_advection_diffusion_elements.h>
Public Member Functions
QAxisymAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QAxisymAdvectionDiffusionElement (const QAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Protected Member Functions
double dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >
QAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Axisymmetric Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 592 of file axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QAxisymAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::QAxisymAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 607 of file axisym_advection_diffusion_elements.h.
QAxisymAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::QAxisymAdvectionDiffusionElement (const QAxisymAdvectionDiffusionElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 612 of file axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_axi_adv_diff()
template<unsigned NNODE_1D>
double oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AxisymAdvectionDiffusionEquations.
Definition at line 737 of file axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_axi_adv_diff().
dshape_and_dtest_eulerian_axi_adv_diff()
template<unsigned NNODE_1D>
double oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AxisymAdvectionDiffusionEquations.
Definition at line 702 of file axisym_advection_diffusion_elements.h.
References oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_axi_adv_diff(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 633 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 640 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 648 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 655 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::output().
output_fct()
template<unsigned NNODE_1D>
void oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 662 of file axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_axi_adv_diff(), oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), and s.
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 626 of file axisym_advection_diffusion_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 600 of file axisym_advection_diffusion_elements.h.
The documentation for this class was generated from the following files:
axisym_advection_diffusion_elements.h
axisym_advection_diffusion_elements.cc