oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT > Class Template Reference
PVDElementWithContinuousPressure upgraded to become projectable.
#include <solid_elements.h>
Public Member Functions
ProjectablePVDElementWithContinuousPressure ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying PVD elements the pressures (the first field) are the first values at the vertex nodes etc.
unsigned nfields_for_projection ()
Number of fields to be projected: 1, corresponding to the pressure only.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Includes the current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Includes the current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class PVD_ELEMENT>
class oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >
PVDElementWithContinuousPressure upgraded to become projectable.
Definition at line 2375 of file solid_elements.h.
Constructor & Destructor Documentation
ProjectablePVDElementWithContinuousPressure()
template<class PVD_ELEMENT >
oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::ProjectablePVDElementWithContinuousPressure () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2383 of file solid_elements.h.
Member Function Documentation
data_values_of_field()
template<class PVD_ELEMENT >
Vector<std::pair<Data*,unsigned> > oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying PVD elements the pressures (the first field) are the first values at the vertex nodes etc.
Implements oomph::ProjectableElementBase.
Definition at line 2391 of file solid_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::PVDEquationsBase< DIM >::npres_solid().
get_field()
template<class PVD_ELEMENT >
double oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 2442 of file solid_elements.h.
jacobian_and_shape_of_field()
template<class PVD_ELEMENT >
double oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 2430 of file solid_elements.h.
References oomph::FiniteElement::J_eulerian().
local_equation()
template<class PVD_ELEMENT >
int oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2459 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::solid_p_local_eqn().
nfields_for_projection()
template<class PVD_ELEMENT >
unsigned oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: 1, corresponding to the pressure only.
Implements oomph::ProjectableElementBase.
Definition at line 2411 of file solid_elements.h.
nhistory_values_for_coordinate_projection()
template<class PVD_ELEMENT >
unsigned oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Includes the current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2423 of file solid_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class PVD_ELEMENT >
unsigned oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Includes the current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2415 of file solid_elements.h.
nvalue_of_field()
template<class PVD_ELEMENT >
unsigned oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2452 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::npres_solid().
The documentation for this class was generated from the following file:
solid_elements.h