oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM > Class Template Reference
#include <generalised_newtonian_Tnavier_stokes_elements.h>
Public Member Functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
void unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
GeneralisedNewtonianTCrouzeixRaviartElement ()
Constructor, there are DIM+1 internal values (for the pressure)
GeneralisedNewtonianTCrouzeixRaviartElement (const GeneralisedNewtonianTCrouzeixRaviartElement< DIM > &dummy)
Broken copy constructor.
virtual unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
double p_nst (const unsigned &i) const
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
double p_nst (const unsigned &t, const unsigned &i) const
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs of pointers to data objects and unsignedegers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as unenriched shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions.
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions.
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Protected Attributes
unsigned P_nst_internal_index
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >
TCrouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions enriched by a single cubic bubble function, but a discontinuous linear pressure interpolation
Definition at line 65 of file generalised_newtonian_Tnavier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianTCrouzeixRaviartElement() [1/2]
template<unsigned DIM>
oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::GeneralisedNewtonianTCrouzeixRaviartElement () [inline]
Constructor, there are DIM+1 internal values (for the pressure)
Definition at line 135 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data().
GeneralisedNewtonianTCrouzeixRaviartElement() [2/2]
template<unsigned DIM>
oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::GeneralisedNewtonianTCrouzeixRaviartElement (const GeneralisedNewtonianTCrouzeixRaviartElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 145 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
dpshape_and_dptest_eulerian_nst() [2/3]
template<>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 488 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::TBubbleEnrichedElement< DIM, 3 >::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), and oomph::FiniteElement::transform_derivatives().
dpshape_and_dptest_eulerian_nst() [3/3]
template<>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 542 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::TBubbleEnrichedElement< DIM, 3 >::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), and oomph::FiniteElement::transform_derivatives().
dshape_and_dtest_eulerian_at_knot_nst() [1/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 351 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst().
dshape_and_dtest_eulerian_at_knot_nst() [2/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 377 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 329 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::FiniteElement::dshape_eulerian().
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::ndof_types().
fix_pressure()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 183 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_pressure_data(), oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
full_output() [1/2]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 292 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
full_output() [2/2]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile, const unsigned & nplot) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Definition at line 298 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the DOF that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 658 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::npres_nst(), oomph::Data::nvalue(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::p_local_eqn().
Referenced by oomph::FaceGeometry< FaceGeometry< GeneralisedNewtonianTCrouzeixRaviartElement< 3 > > >::FaceGeometry(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::ndof_types().
get_Z2_flux()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 246 of file generalised_newtonian_Tnavier_stokes_elements.h.
References i, and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::strain_rate().
identify_load_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [virtual]
Add to the set paired_load_data pairs of pointers to data objects and unsignedegers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 72 of file generalised_newtonian_Tnavier_stokes_elements.cc.
References i, and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_pressure_data().
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::fix_pressure(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::fix_pressure(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::unpin_all_internal_pressure_dofs().
identify_pressure_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressue_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 106 of file generalised_newtonian_Tnavier_stokes_elements.cc.
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::fix_pressure(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::fix_pressure(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_load_data().
ndof_types()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element.
are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 303 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns().
npres_nst()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 180 of file generalised_newtonian_Tnavier_stokes_elements.h.
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns(), and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::p_nodal_index_nst().
nrecovery_order()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as unenriched shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 227 of file generalised_newtonian_Tnavier_stokes_elements.h.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 238 of file generalised_newtonian_Tnavier_stokes_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 230 of file generalised_newtonian_Tnavier_stokes_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 209 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 213 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 217 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 221 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::p_local_eqn (const unsigned & n) const [inline], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase.
Definition at line 129 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn().
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns().
p_nst() [1/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::p_nst (const unsigned & i) const [inline], [virtual]
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 170 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_nst() [2/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::p_nst (const unsigned & t, const unsigned & i) const [inline], [virtual]
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 176 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
pshape_nst() [1/6]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::pshape_nst(), and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::required_nvalue().
pshape_nst() [2/6]
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
pshape_nst() [3/6]
template<>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 420 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [4/6]
template<>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 434 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [5/6]
template<>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 452 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [6/6]
template<>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 469 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::pshape_nst().
required_nvalue()
template<unsigned DIM>
virtual unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Number of values (pinned or dofs) required at local node n.
Reimplemented from oomph::FiniteElement.
Definition at line 163 of file generalised_newtonian_Tnavier_stokes_elements.h.
Referenced by oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns().
unpin_all_internal_pressure_dofs()
template<unsigned DIM>
void oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::unpin_all_internal_pressure_dofs ()
Unpin all internal pressure dofs.
Definition at line 49 of file generalised_newtonian_Tnavier_stokes_elements.cc.
References oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_load_data().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 234 of file generalised_newtonian_Tnavier_stokes_elements.h.
References oomph::FiniteElement::node_pt().
Member Data Documentation
P_nst_internal_index
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::P_nst_internal_index [protected]
Internal index that indicates at which internal datum the pressure is stored
Definition at line 75 of file generalised_newtonian_Tnavier_stokes_elements.h.
The documentation for this class was generated from the following files:
generalised_newtonian_Tnavier_stokes_elements.h
generalised_newtonian_Tnavier_stokes_elements.cc