oomph::NavierStokesElementWithDiagonalMassMatrices Class Reference
#include <elements.h>
Public Member Functions
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)
Broken assignment operator.
virtual void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)=0
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Detailed Description
Pure virtual base class for elements that can be used with Navier-Stokes Schur complement preconditioner and provide the diagonal of their velocity and pressure mass matrices -- needs to be defined here (in generic) because this applies to a variety of Navier-Stokes elements (cartesian, cylindrical polar, ...) that can be preconditioned effectively by the Navier Stokes (!) preconditioners in the (cartesian) Navier-Stokes directory.
Definition at line 5007 of file elements.h.
Constructor & Destructor Documentation
NavierStokesElementWithDiagonalMassMatrices() [1/2]
oomph::NavierStokesElementWithDiagonalMassMatrices::NavierStokesElementWithDiagonalMassMatrices () [inline]
Empty constructor.
Definition at line 5013 of file elements.h.
 NavierStokesElementWithDiagonalMassMatrices()
virtual oomph::NavierStokesElementWithDiagonalMassMatrices::~NavierStokesElementWithDiagonalMassMatrices () [inline], [virtual]
Virtual destructor.
Definition at line 5016 of file elements.h.
NavierStokesElementWithDiagonalMassMatrices() [2/2]
oomph::NavierStokesElementWithDiagonalMassMatrices::NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &) [inline]
Broken copy constructor.
Definition at line 5019 of file elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_pressure_and_velocity_mass_matrix_diagonal()
virtual void oomph::NavierStokesElementWithDiagonalMassMatrices::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [pure virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Implemented in oomph::NavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::AxisymmetricNavierStokesEquations, oomph::SphericalNavierStokesEquations, oomph::RefineableNavierStokesEquations< DIM >, oomph::TemplateFreeNavierStokesEquationsBase, oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >, and oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal().
operator=()
void oomph::NavierStokesElementWithDiagonalMassMatrices::operator= (const NavierStokesElementWithDiagonalMassMatrices &) [inline]
Broken assignment operator.
Definition at line 5027 of file elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
elements.h