oomph::DummyMesh Class Reference
Dummy mesh that can be created and deleted in SolidICProblem.
#include <elastic_problems.h>
Public Member Functions
DummyMesh ()
Additional Inherited Members
Detailed Description
Dummy mesh that can be created and deleted in SolidICProblem.
Definition at line 58 of file elastic_problems.h.
Constructor & Destructor Documentation
DummyMesh()
oomph::DummyMesh::DummyMesh () [inline]
Definition at line 64 of file elastic_problems.h.
Referenced by oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), and oomph::SolidICProblem::SolidICProblem().
The documentation for this class was generated from the following file:
elastic_problems.h