oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied flux on the boundaries of Fourier decomposed Helmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <fourier_decomposed_helmholtz_flux_elements.h>
Public Types
typedef void(* FourierDecomposedHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex.
Public Member Functions
FourierDecomposedHelmholtzFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
FourierDecomposedHelmholtzFluxElement ()
Broken empty constructor.
FourierDecomposedHelmholtzFluxElement (const FourierDecomposedHelmholtzFluxElement &dummy)
Broken copy constructor.
FourierDecomposedHelmholtzPrescribedFluxFctPt & flux_fct_pt ()
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
virtual std::complex< unsigned > u_index_fourier_decomposed_helmholtz () const
Return the index at which the unknown value is stored. (Real/imag part gives real index of real/imag part).
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const Vector< double > &x, std::complex< double > &flux)
virtual void fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Protected Attributes
std::complex< unsigned > U_index_fourier_decomposed_helmholtz
The index at which the real and imag part of the unknown is stored at the nodes.
FourierDecomposedHelmholtzPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied flux on the boundaries of Fourier decomposed Helmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 58 of file fourier_decomposed_helmholtz_flux_elements.h.
Member Typedef Documentation
FourierDecomposedHelmholtzPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex.
Definition at line 69 of file fourier_decomposed_helmholtz_flux_elements.h.
Constructor & Destructor Documentation
FourierDecomposedHelmholtzFluxElement() [1/3]
template<class ELEMENT >
oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 255 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt, oomph::Global_string_for_annotation::string(), and oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_fourier_decomposed_helmholtz.
FourierDecomposedHelmholtzFluxElement() [2/3]
template<class ELEMENT >
oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement () [inline]
Broken empty constructor.
Definition at line 77 of file fourier_decomposed_helmholtz_flux_elements.h.
FourierDecomposedHelmholtzFluxElement() [3/3]
template<class ELEMENT >
oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement (const FourierDecomposedHelmholtzFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 86 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 120 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 109 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux().
fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 299 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), s, oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_fourier_decomposed_helmholtz, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement().
flux_fct_pt()
template<class ELEMENT >
FourierDecomposedHelmholtzPrescribedFluxFctPt& oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::flux_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-flux function pointer
Definition at line 104 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux (const Vector< double > & x, std::complex< double > & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position
Definition at line 206 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt.
Referenced by oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux().
output() [1/4]
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 130 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 134 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 140 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 145 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 165 of file fourier_decomposed_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 186 of file fourier_decomposed_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
u_index_fourier_decomposed_helmholtz()
template<class ELEMENT >
virtual std::complex<unsigned> oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::u_index_fourier_decomposed_helmholtz () const [inline], [virtual]
Return the index at which the unknown value is stored. (Real/imag part gives real index of real/imag part).
Definition at line 152 of file fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_fourier_decomposed_helmholtz.
Member Data Documentation
Flux_fct_pt
template<class ELEMENT >
FourierDecomposedHelmholtzPrescribedFluxFctPt oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::Flux_fct_pt [protected]
Function pointer to the (global) prescribed-flux function.
Definition at line 236 of file fourier_decomposed_helmholtz_flux_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::flux_fct_pt(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), and oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::get_flux().
U_index_fourier_decomposed_helmholtz
template<class ELEMENT >
std::complex<unsigned> oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::U_index_fourier_decomposed_helmholtz [protected]
The index at which the real and imag part of the unknown is stored at the nodes.
Definition at line 223 of file fourier_decomposed_helmholtz_flux_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), and oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::u_index_fourier_decomposed_helmholtz().
The documentation for this class was generated from the following file:
fourier_decomposed_helmholtz_flux_elements.h