oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT > Class Template Reference
#include <mesh_smooth.h>
Public Member Functions
void operator() (SolidMesh *orig_mesh_pt, std::set< Node *> pinned_nodes)
Constructor: Specify SolidMesh whose nodal positions are to be adjusted, and set of nodes in that mesh whose position are to remain fixed.
~LinearElasticitySmoothMesh ()
Destructor (empty)
Additional Inherited Members
Detailed Description
template<class LINEAR_ELASTICITY_ELEMENT>
class oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >
Auxiliary Problem to smooth a SolidMesh by adjusting the internal nodal positions by solving a LINEAR solid mechanics problem for the nodal displacements between the specified displacements of certain pinned nodes (usually located on boundaries). The template parameter specifies the linear elasticity element that must have the same shape (geometric element type) as the elements contained in the mesh that's to be smoothed. So, e.g. for the ten-noded three-dimensional tetrahedral TTaylorHoodElement<3>, it would be a TLinearElasticityElement<3,3>, etc. Important assumptions:
It is important that the Lagrangian coordinates of all nodes still indicate their original position, i.e. their position before (some of) them were moved to their new position.
It is assumed that in its original state, the mesh does not contain any inverted elements.
Definition at line 542 of file mesh_smooth.h.
Constructor & Destructor Documentation
 LinearElasticitySmoothMesh()
template<class LINEAR_ELASTICITY_ELEMENT >
oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::~LinearElasticitySmoothMesh () [inline]
Destructor (empty)
Definition at line 651 of file mesh_smooth.h.
Member Function Documentation
operator()()
template<class LINEAR_ELASTICITY_ELEMENT >
void oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator() (SolidMesh * orig_mesh_pt, std::set< Node *> pinned_nodes) [inline]
Constructor: Specify SolidMesh whose nodal positions are to be adjusted, and set of nodes in that mesh whose position are to remain fixed.
Definition at line 550 of file mesh_smooth.h.
References e, oomph::Mesh::finite_element_pt(), i, oomph::Helper_namespace_for_mesh_smoothing::Isotropic_elasticity_tensor(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::SolidMesh::node_pt(), oomph::oomph_info, oomph::SolidMesh::set_lagrangian_nodal_coordinates(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
The documentation for this class was generated from the following file:
mesh_smooth.h