oomph::GeneralisedNewtonianQTaylorHoodElement< DIM > Class Template Reference
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianQTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
template<>
const unsigned Pconv [4]
template<>
const unsigned Pconv [8]
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
template<>
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
template<>
const unsigned Initial_Nvalue [9]
template<>
const unsigned Initial_Nvalue [27]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 1770 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianQTaylorHoodElement()
template<unsigned DIM>
oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::GeneralisedNewtonianQTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 1827 of file generalised_newtonian_navier_stokes_elements.h.
Member Function Documentation
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst().
dpshape_and_dptest_eulerian_nst() [2/3]
template<>
double oomph::GeneralisedNewtonianQTaylorHoodElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1988 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::local_to_eulerian_mapping(), oomph::OneDimLagrange::shape< 2 >(), and oomph::FiniteElement::transform_derivatives().
dpshape_and_dptest_eulerian_nst() [3/3]
template<>
double oomph::GeneralisedNewtonianQTaylorHoodElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2180 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::local_to_eulerian_mapping(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst(), oomph::OneDimLagrange::shape< 2 >(), and oomph::FiniteElement::transform_derivatives().
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1965 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), and oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_nst().
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
template<>
double oomph::GeneralisedNewtonianQTaylorHoodElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2057 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<>
double oomph::GeneralisedNewtonianQTaylorHoodElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2105 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst().
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1940 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::FiniteElement::dshape_eulerian().
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::ndof_types().
fix_pressure()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1865 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_nodal_index_nst(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 2873 of file generalised_newtonian_navier_stokes_elements.cc.
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_pressure_data().
identify_load_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >.
Definition at line 2812 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_pressure_data().
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::Pconv().
identify_pressure_data()
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Implements oomph::FSIFluidElement.
Definition at line 2846 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns().
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data().
Initial_Nvalue() [1/2]
template<>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< 2 >::Initial_Nvalue () [private]
Definition at line 2784 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
template<>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< 3 >::Initial_Nvalue () [private]
Definition at line 2794 of file generalised_newtonian_navier_stokes_elements.cc.
ndof_types()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::ndof_types () const [inline], [virtual]
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1914 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_nst(), and oomph::GeneralisedElement::get_dof_numbers_for_unknowns().
npres_nst()
template<unsigned DIM>
unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1861 of file generalised_newtonian_navier_stokes_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1896 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1900 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1904 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1908 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_local_eqn (const unsigned & n) const [inline], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase.
Definition at line 1847 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), and oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_nodal_index_nst().
p_nodal_index_nst()
template<unsigned DIM>
virtual int oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1844 of file generalised_newtonian_navier_stokes_elements.h.
p_nst() [1/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1852 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value(), and oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_nodal_index_nst().
p_nst() [2/2]
template<unsigned DIM>
double oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1857 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value(), and oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_nodal_index_nst().
Pconv() [1/2]
template<>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< 2 >::Pconv () [protected]
Definition at line 2788 of file generalised_newtonian_navier_stokes_elements.cc.
Pconv() [2/2]
template<>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< 3 >::Pconv () [protected]
Definition at line 2799 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data().
pshape_nst() [1/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst().
pshape_nst() [2/4]
template<unsigned DIM>
void oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2281 of file generalised_newtonian_navier_stokes_elements.h.
pshape_nst() [3/4]
template<>
void oomph::GeneralisedNewtonianQTaylorHoodElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2149 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst(), i, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [4/4]
template<>
void oomph::GeneralisedNewtonianQTaylorHoodElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2247 of file generalised_newtonian_navier_stokes_elements.h.
References i, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst(), and oomph::OneDimLagrange::shape< 2 >().
required_nvalue()
template<unsigned DIM>
virtual unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >.
Definition at line 1832 of file generalised_newtonian_navier_stokes_elements.h.
References s.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 1776 of file generalised_newtonian_navier_stokes_elements.h.
Pconv
template<unsigned DIM>
const unsigned oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::Pconv[] [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 1782 of file generalised_newtonian_navier_stokes_elements.h.
The documentation for this class was generated from the following files:
generalised_newtonian_navier_stokes_elements.h
generalised_newtonian_navier_stokes_elements.cc