oomph::RefineableQSpectralElement< 2 > Class Template Reference
#include <refineable_quad_spectral_element.h>
Public Member Functions
RefineableQSpectralElement ()
Constructor.
RefineableQSpectralElement (const RefineableQSpectralElement< 2 > &dummy)
Broken copy constructor.
virtual ~RefineableQSpectralElement ()
Broken assignment operator.
void rebuild_from_sons (Mesh *&mesh_pt)
The only thing to add is rebuild from sons.
virtual bool nodes_built ()
Overload the nodes built function.
Additional Inherited Members
Detailed Description
template<>
class oomph::RefineableQSpectralElement< 2 >
Refineable version of QuadElements that add functionality for spectral Elements.
Definition at line 51 of file refineable_quad_spectral_element.h.
Constructor & Destructor Documentation
RefineableQSpectralElement() [1/2]
oomph::RefineableQSpectralElement< 2 >::RefineableQSpectralElement () [inline]
Constructor.
Definition at line 57 of file refineable_quad_spectral_element.h.
References oomph::LeakCheckNames::_build.
RefineableQSpectralElement() [2/2]
oomph::RefineableQSpectralElement< 2 >::RefineableQSpectralElement (const RefineableQSpectralElement< 2 > & dummy) [inline]
Broken copy constructor.
Definition at line 66 of file refineable_quad_spectral_element.h.
References oomph::BrokenCopy::broken_copy().
 RefineableQSpectralElement()
virtual oomph::RefineableQSpectralElement< 2 >::~RefineableQSpectralElement () [inline], [virtual]
Broken assignment operator.
Destructor
Definition at line 82 of file refineable_quad_spectral_element.h.
References oomph::LeakCheckNames::_build.
Member Function Documentation
nodes_built()
virtual bool oomph::RefineableQSpectralElement< 2 >::nodes_built () [inline], [virtual]
Overload the nodes built function.
Reimplemented from oomph::RefineableElement.
Definition at line 422 of file refineable_quad_spectral_element.h.
rebuild_from_sons()
void oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
The only thing to add is rebuild from sons.
Implements oomph::RefineableElement.
Definition at line 90 of file refineable_quad_spectral_element.h.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::Mesh::boundary_coordinate_exists(), oomph::QuadTreeNames::E, oomph::RefineableQElement< 2 >::get_bcs(), oomph::RefineableQElement< 2 >::get_boundaries(), oomph::RefineableElement::get_interpolated_values(), oomph::RefineableSolidQElement< 2 >::get_solid_bcs(), oomph::FiniteElement::get_x(), i, oomph::RefineableQElement< 2 >::interpolated_zeta_on_edge(), oomph::QuadTreeNames::N, oomph::Node::ndim(), oomph::QuadTreeNames::NE, oomph::TimeStepper::ntstorage(), oomph::QuadTreeNames::NW, oomph::Tree::OMEGA, oomph::SolidNode::pin_position(), oomph::QuadTreeNames::S, s, oomph::QuadTreeNames::SE, oomph::Global_string_for_annotation::string(), oomph::QuadTreeNames::SW, t, and oomph::QuadTreeNames::W.
The documentation for this class was generated from the following file:
refineable_quad_spectral_element.h