oomph::IdentityPreconditioner Class Reference
The Identity Preconditioner.
#include <preconditioner.h>
Public Member Functions
IdentityPreconditioner ()
IdentityPreconditioner (const IdentityPreconditioner &)
Broken copy constructor.
void operator= (const IdentityPreconditioner &)
Broken assignment operator.
virtual ~IdentityPreconditioner ()
Destructor (empty)
virtual void setup ()
setup method - just sets the distribution
virtual void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply the preconditioner. This method should apply the preconditioner operator to the vector r and return the vector z.
Additional Inherited Members
Detailed Description
The Identity Preconditioner.
Definition at line 215 of file preconditioner.h.
Constructor & Destructor Documentation
IdentityPreconditioner() [1/2]
oomph::IdentityPreconditioner::IdentityPreconditioner () [inline]
Definition at line 221 of file preconditioner.h.
IdentityPreconditioner() [2/2]
oomph::IdentityPreconditioner::IdentityPreconditioner (const IdentityPreconditioner &) [inline]
Broken copy constructor.
Definition at line 224 of file preconditioner.h.
References oomph::BrokenCopy::broken_copy().
 IdentityPreconditioner()
virtual oomph::IdentityPreconditioner::~IdentityPreconditioner () [inline], [virtual]
Destructor (empty)
Definition at line 236 of file preconditioner.h.
Member Function Documentation
operator=()
void oomph::IdentityPreconditioner::operator= (const IdentityPreconditioner &) [inline]
Broken assignment operator.
Definition at line 230 of file preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
virtual void oomph::IdentityPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Apply the preconditioner. This method should apply the preconditioner operator to the vector r and return the vector z.
Implements oomph::Preconditioner.
Definition at line 264 of file preconditioner.h.
References oomph::DoubleVector::built(), and oomph::DistributableLinearAlgebraObject::distribution_pt().
setup()
virtual void oomph::IdentityPreconditioner::setup () [inline], [virtual]
setup method - just sets the distribution
Implements oomph::Preconditioner.
Definition at line 239 of file preconditioner.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::Preconditioner::comm_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::Preconditioner::matrix_pt(), and oomph::DoubleMatrixBase::nrow().
The documentation for this class was generated from the following file:
preconditioner.h