oomph::YoungLaplaceEquations Class Reference
#include <young_laplace_elements.h>
Public Types
typedef void(* SpineBaseFctPt) (const Vector< double > &x, Vector< double > &spine_base, Vector< Vector< double > > &dspine_base)
Function pointer to `spine base` function.
typedef void(* SpineFctPt) (const Vector< double > &x, Vector< double > &spine, Vector< Vector< double > > &dspine)
Function pointer to `spine` function.
Public Member Functions
YoungLaplaceEquations ()
YoungLaplaceEquations (const YoungLaplaceEquations &dummy)
Broken copy constructor.
void operator= (const YoungLaplaceEquations &)
Broken assignment operator.
virtual double u (const unsigned &n) const
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln at n_plot^2 plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln at n_plot^2 plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
Data * kappa_pt ()
Access function: Pointer Data object that stores kappa (const version -- kappa must be set with set_kappa() which also ensures that the Data object is added to the element's external Data.
bool use_spines () const
Use spines or not? (Based on availability of function pointers to to spine and spine base vector fields)
SpineBaseFctPt & spine_base_fct_pt ()
Access function to function pointer that specifies spine base vector field.
SpineFctPt & spine_fct_pt ()
Access function to function pointer that specifies spine vector field.
void set_kappa (Data *kappa_pt)
Set curvature data (and add it to the element's external Data)
double get_kappa () const
Get curvature.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i: Mainly used for error estimation.
virtual void get_spine_base (const Vector< double > &x, Vector< double > &spine_base, Vector< Vector< double > > &dspine_base) const
Get spine base vector field: Defaults to standard cartesian representation if no spine base fct pointers have been set. dspine_B[i][j] = d spine_B[j] / dx_i.
void get_spine (const Vector< double > &x, Vector< double > &spine, Vector< Vector< double > > &dspine) const
Get spine vector field: Defaults to standard cartesian representation if no spine base fct pointers have been set. dspine[i][j] = d spine[j] / dx_i.
void position (const Vector< double > &s, Vector< double > &r) const
Get position vector to meniscus at local coordinate s.
void exact_position (const Vector< double > &s, Vector< double > &r, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Get exact position vector to meniscus at local coordinate s.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
double interpolated_u (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Static Public Member Functions
static void allocate_vector_of_vectors (unsigned n_rows, unsigned n_cols, Vector< Vector< double > > &v)
Helper fct: Allocate storage for a vector of vectors of doubles to v(n_rows,n_cols) and initialise each component to 0.0.
static void scalar_times_vector (const double &lambda, const Vector< double > &v, Vector< double > &lambda_times_v)
Multiply a vector by a scalar.
static double two_norm (const Vector< double > &v)
2-norm of a vector
static double scalar_product (const Vector< double > &v1, const Vector< double > &v2)
Scalar product between two vectors.
static void cross_product (const Vector< double > &v1, const Vector< double > &v2, Vector< double > &v_cross)
Cross-product: v_cross= v1 x v2.
static void vector_sum (const Vector< double > &v1, const Vector< double > &v2, Vector< double > &vs)
Vectorial sum of two vectors.
Protected Member Functions
virtual int u_local_eqn (const unsigned &n)
Get the local equation number of the (one and only) unknown stored at local node n (returns -1 if value is pinned). Can be overloaded in derived multiphysics elements.
Protected Attributes
unsigned Kappa_index
Index of Kappa_pt in the element's storage of external Data.
SpineBaseFctPt Spine_base_fct_pt
Pointer to spine base function:
SpineFctPt Spine_fct_pt
Pointer to spine function:
Private Attributes
Data * Kappa_pt
Pointer to Data item that stores kappa as its first value -- private to ensure that it must be set with set_kappa(...) which adds the Data to the element's internal Data!
Additional Inherited Members
Detailed Description
A class for all isoparametric elements that solve the YoungLaplace equations.
 div (\frac{1}{W} \nabla u) = \kappa 
 with
 W^2=1+\|\nabla u\|^2 
 These equations can either be solved in the above (cartesian) form, or in a parametric representation using the method of spines. See the theory write-up in the documentation for details. This class contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 69 of file young_laplace_elements.h.
Member Typedef Documentation
SpineBaseFctPt
typedef void(* oomph::YoungLaplaceEquations::SpineBaseFctPt) (const Vector< double > &x, Vector< double > &spine_base, Vector< Vector< double > > &dspine_base)
Function pointer to `spine base` function.
Definition at line 76 of file young_laplace_elements.h.
SpineFctPt
typedef void(* oomph::YoungLaplaceEquations::SpineFctPt) (const Vector< double > &x, Vector< double > &spine, Vector< Vector< double > > &dspine)
Function pointer to `spine` function.
Definition at line 81 of file young_laplace_elements.h.
Constructor & Destructor Documentation
YoungLaplaceEquations() [1/2]
oomph::YoungLaplaceEquations::YoungLaplaceEquations () [inline]
Constructor: Initialise pointers to NULL, so by default prescribed kappa evaluates to zero, and no spines are used.
Definition at line 87 of file young_laplace_elements.h.
YoungLaplaceEquations() [2/2]
oomph::YoungLaplaceEquations::YoungLaplaceEquations (const YoungLaplaceEquations & dummy) [inline]
Broken copy constructor.
Definition at line 92 of file young_laplace_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
allocate_vector_of_vectors()
static void oomph::YoungLaplaceEquations::allocate_vector_of_vectors (unsigned n_rows, unsigned n_cols, Vector< Vector< double > > & v) [inline], [static]
Helper fct: Allocate storage for a vector of vectors of doubles to v(n_rows,n_cols) and initialise each component to 0.0.
Definition at line 343 of file young_laplace_elements.h.
References i.
Referenced by exact_position(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), output(), and position().
compute_error() [1/2]
void oomph::YoungLaplaceEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points. Calculate the cartesian coordinates of point on meniscus
Calculate the exact position
Reimplemented from oomph::FiniteElement.
Definition at line 567 of file young_laplace_elements.cc.
References exact_position(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), position(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output_fct().
compute_error() [2/2]
void oomph::YoungLaplaceEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 144 of file young_laplace_elements.h.
cross_product()
static void oomph::YoungLaplaceEquations::cross_product (const Vector< double > & v1, const Vector< double > & v2, Vector< double > & v_cross) [inline], [static]
Cross-product: v_cross= v1 x v2.
Definition at line 400 of file young_laplace_elements.h.
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
exact_position()
void oomph::YoungLaplaceEquations::exact_position (const Vector< double > & s, Vector< double > & r, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Get exact position vector to meniscus at local coordinate s.
Get exact position vector to meniscus. Get spines values
Global Eulerian cooordinates
Definition at line 53 of file young_laplace_elements.cc.
References allocate_vector_of_vectors(), get_spine(), get_spine_base(), oomph::FiniteElement::interpolated_x(), and use_spines().
Referenced by compute_error(), get_spine(), and output_fct().
fill_in_contribution_to_residuals()
void oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Add the element's contribution to its residual vector.
Compute element residual vector. Pure version without hanging nodes.
`Simple` case
Spine case
Get the unnormalized normal
Reimplemented from oomph::GeneralisedElement.
Definition at line 144 of file young_laplace_elements.cc.
References allocate_vector_of_vectors(), cross_product(), oomph::FiniteElement::dshape_eulerian_at_knot(), get_kappa(), get_spine(), get_spine_base(), oomph::FiniteElement::integral_pt(), interpolated_u(), oomph::FiniteElement::interpolated_zeta(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), scalar_product(), scalar_times_vector(), two_norm(), u(), u_local_eqn(), use_spines(), vector_sum(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by get_spine().
get_flux()
void oomph::YoungLaplaceEquations::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i] = du/dx_i: Mainly used for error estimation.
Definition at line 212 of file young_laplace_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), and u().
Referenced by oomph::RefineableYoungLaplaceEquations::get_Z2_flux().
get_kappa()
double oomph::YoungLaplaceEquations::get_kappa () const [inline]
Get curvature.
No kappa has been set: return zero (the default)
Definition at line 196 of file young_laplace_elements.h.
References Kappa_pt, and oomph::Data::value().
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
get_spine()
void oomph::YoungLaplaceEquations::get_spine (const Vector< double > & x, Vector< double > & spine, Vector< Vector< double > > & dspine) const [inline]
Get spine vector field: Defaults to standard cartesian representation if no spine base fct pointers have been set. dspine[i][j] = d spine[j] / dx_i.
Definition at line 273 of file young_laplace_elements.h.
References exact_position(), fill_in_contribution_to_residuals(), i, position(), s, and Spine_fct_pt.
Referenced by exact_position(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), output(), and position().
get_spine_base()
virtual void oomph::YoungLaplaceEquations::get_spine_base (const Vector< double > & x, Vector< double > & spine_base, Vector< Vector< double > > & dspine_base) const [inline], [virtual]
Get spine base vector field: Defaults to standard cartesian representation if no spine base fct pointers have been set. dspine_B[i][j] = d spine_B[j] / dx_i.
Definition at line 245 of file young_laplace_elements.h.
References i, and Spine_base_fct_pt.
Referenced by exact_position(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), output(), and position().
interpolated_u()
double oomph::YoungLaplaceEquations::interpolated_u (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 313 of file young_laplace_elements.h.
References oomph::FiniteElement::nnode(), self_test(), oomph::FiniteElement::shape(), and u().
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), output(), and position().
kappa_pt()
Data* oomph::YoungLaplaceEquations::kappa_pt () [inline]
Access function: Pointer Data object that stores kappa (const version -- kappa must be set with set_kappa() which also ensures that the Data object is added to the element's external Data.
Definition at line 157 of file young_laplace_elements.h.
References Kappa_pt.
Referenced by oomph::RefineableYoungLaplaceEquations::further_build(), and set_kappa().
operator=()
void oomph::YoungLaplaceEquations::operator= (const YoungLaplaceEquations &) [inline]
Broken assignment operator.
Definition at line 98 of file young_laplace_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/2]
void oomph::YoungLaplaceEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >.
Definition at line 109 of file young_laplace_elements.h.
References output_fct().
Referenced by oomph::QYoungLaplaceElement< NNODE_1D >::output().
output() [2/2]
void oomph::YoungLaplaceEquations::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output FE representation of soln at n_plot^2 plot points.
Output solution at nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >.
Definition at line 408 of file young_laplace_elements.cc.
References allocate_vector_of_vectors(), oomph::FiniteElement::get_s_plot(), get_spine(), get_spine_base(), i, interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), position(), s, oomph::FiniteElement::tecplot_zone_string(), use_spines(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::YoungLaplaceEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln at n_plot^2 plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points. Calculate the cartesian coordinates of point on meniscus
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >.
Definition at line 511 of file young_laplace_elements.cc.
References exact_position(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output(), and oomph::QYoungLaplaceElement< NNODE_1D >::output_fct().
output_fct() [2/2]
virtual void oomph::YoungLaplaceEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln at n_plot^2 plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QYoungLaplaceElement< NNODE_1D >.
Definition at line 128 of file young_laplace_elements.h.
References compute_error().
position()
void oomph::YoungLaplaceEquations::position (const Vector< double > & s, Vector< double > & r) const [virtual]
Get position vector to meniscus at local coordinate s.
Get position vector to meniscus. Get spines values
Global Eulerian cooordinates
Reimplemented from oomph::FiniteElement.
Definition at line 98 of file young_laplace_elements.cc.
References allocate_vector_of_vectors(), get_spine(), get_spine_base(), interpolated_u(), oomph::FiniteElement::interpolated_x(), u(), and use_spines().
Referenced by compute_error(), get_spine(), and output().
scalar_product()
static double oomph::YoungLaplaceEquations::scalar_product (const Vector< double > & v1, const Vector< double > & v2) [inline], [static]
Scalar product between two vectors.
Definition at line 387 of file young_laplace_elements.h.
References i.
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
scalar_times_vector()
static void oomph::YoungLaplaceEquations::scalar_times_vector (const double & lambda, const Vector< double > & v, Vector< double > & lambda_times_v) [inline], [static]
Multiply a vector by a scalar.
Definition at line 360 of file young_laplace_elements.h.
References i.
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
self_test()
unsigned oomph::YoungLaplaceEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 380 of file young_laplace_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by interpolated_u().
set_kappa()
void oomph::YoungLaplaceEquations::set_kappa (Data * kappa_pt) [inline]
Set curvature data (and add it to the element's external Data)
Definition at line 176 of file young_laplace_elements.h.
References oomph::GeneralisedElement::add_external_data(), Kappa_index, kappa_pt(), Kappa_pt, and oomph::Data::nvalue().
Referenced by oomph::RefineableYoungLaplaceEquations::further_build().
spine_base_fct_pt()
SpineBaseFctPt& oomph::YoungLaplaceEquations::spine_base_fct_pt () [inline]
Access function to function pointer that specifies spine base vector field.
Definition at line 168 of file young_laplace_elements.h.
References Spine_base_fct_pt.
Referenced by oomph::RefineableYoungLaplaceEquations::further_build().
spine_fct_pt()
SpineFctPt& oomph::YoungLaplaceEquations::spine_fct_pt () [inline]
Access function to function pointer that specifies spine vector field.
Definition at line 173 of file young_laplace_elements.h.
References Spine_fct_pt.
Referenced by oomph::RefineableYoungLaplaceEquations::further_build().
two_norm()
static double oomph::YoungLaplaceEquations::two_norm (const Vector< double > & v) [inline], [static]
2-norm of a vector
Definition at line 374 of file young_laplace_elements.h.
References i.
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
u()
virtual double oomph::YoungLaplaceEquations::u (const unsigned & n) const [inline], [virtual]
Access function: Nodal function value at local node n Uses suitably interpolated value for hanging nodes.
Definition at line 105 of file young_laplace_elements.h.
References oomph::FiniteElement::nodal_value().
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), get_flux(), oomph::RefineableYoungLaplaceEquations::get_interpolated_values(), interpolated_u(), and position().
u_local_eqn()
virtual int oomph::YoungLaplaceEquations::u_local_eqn (const unsigned & n) [inline], [protected], [virtual]
Get the local equation number of the (one and only) unknown stored at local node n (returns -1 if value is pinned). Can be overloaded in derived multiphysics elements.
Definition at line 436 of file young_laplace_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
use_spines()
bool oomph::YoungLaplaceEquations::use_spines () const [inline]
Use spines or not? (Based on availability of function pointers to to spine and spine base vector fields)
Definition at line 161 of file young_laplace_elements.h.
References Spine_fct_pt.
Referenced by exact_position(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), fill_in_contribution_to_residuals(), output(), and position().
vector_sum()
static void oomph::YoungLaplaceEquations::vector_sum (const Vector< double > & v1, const Vector< double > & v2, Vector< double > & vs) [inline], [static]
Vectorial sum of two vectors.
Definition at line 420 of file young_laplace_elements.h.
References i.
Referenced by oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), and fill_in_contribution_to_residuals().
Member Data Documentation
Kappa_index
unsigned oomph::YoungLaplaceEquations::Kappa_index [protected]
Index of Kappa_pt in the element's storage of external Data.
Definition at line 440 of file young_laplace_elements.h.
Referenced by set_kappa().
Kappa_pt
Data* oomph::YoungLaplaceEquations::Kappa_pt [private]
Pointer to Data item that stores kappa as its first value -- private to ensure that it must be set with set_kappa(...) which adds the Data to the element's internal Data!
Definition at line 454 of file young_laplace_elements.h.
Referenced by get_kappa(), kappa_pt(), and set_kappa().
Spine_base_fct_pt
SpineBaseFctPt oomph::YoungLaplaceEquations::Spine_base_fct_pt [protected]
Pointer to spine base function:
Definition at line 443 of file young_laplace_elements.h.
Referenced by oomph::RefineableYoungLaplaceEquations::further_build(), get_spine_base(), and spine_base_fct_pt().
Spine_fct_pt
SpineFctPt oomph::YoungLaplaceEquations::Spine_fct_pt [protected]
Pointer to spine function:
Definition at line 446 of file young_laplace_elements.h.
Referenced by oomph::RefineableYoungLaplaceEquations::further_build(), get_spine(), spine_fct_pt(), and use_spines().
The documentation for this class was generated from the following files:
young_laplace_elements.h
young_laplace_elements.cc