oomph::TreeForest Class Reference
#include <tree.h>
Public Member Functions
TreeForest (Vector< TreeRoot *> &trees_pt)
Constructor for Tree forest: Pass Vector of (pointers to) constituents trees.
TreeForest ()
Default constructor (empty and broken)
TreeForest (const TreeForest &dummy)
Broken copy constructor.
void operator= (const TreeForest &)
Broken assignment operator.
virtual ~TreeForest ()
Destructor: Delete the constituent trees (and thus the objects associated with its non-leaf nodes!)
void stick_leaves_into_vector (Vector< Tree * > &forest_nodes)
Traverse forst and stick pointers to leaf `nodes` into Vector.
void stick_all_tree_nodes_into_vector (Vector< Tree * > &all_forest_nodes)
Traverse forest and stick pointers to all `nodes` into Vector.
virtual void check_all_neighbours (DocInfo &doc_info)=0
Document/check the neighbours of all the nodes in the forest. This must be overloaded for different types of forest.
virtual void open_hanging_node_files (DocInfo &doc_info, Vector< std::ofstream *> &output_stream)=0
Open output files that will store any hanging nodes in the forest. Return a vector of the output streams. This is included in the tree structure, so that we can use generic routines for mesh adaptation in two and three dimensions. The need for pointers to the output streams is because one cannot copy a stream!
void close_hanging_node_files (DocInfo &doc_info, Vector< std::ofstream *> &output_stream)
Close output files that will store any hanging nodes in the forest and delete any associated storage. This can be performed genercially in this base class.
unsigned ntree ()
Number of trees in forest.
TreeRoot * tree_pt (const unsigned &i) const
Return pointer to i-th tree in forest.
void flush_trees ()
Flush trees from forest.
Protected Attributes
Vector< TreeRoot * > Trees_pt
Vector containing the pointers to the trees.
Detailed Description
A TreeForest consists of a collection of TreeRoots. Each member tree can have neighbours in various enumerated directions (e.g. S/W/N/E for a QuadTreeForest) and the orientation of their compasses can differ, allowing for complex, unstructured meshes.
Definition at line 385 of file tree.h.
Constructor & Destructor Documentation
TreeForest() [1/3]
oomph::TreeForest::TreeForest (Vector< TreeRoot *> & trees_pt)
Constructor for Tree forest: Pass Vector of (pointers to) constituents trees.
Constructor for TreeForest:
Pass:
trees_pt[], the Vector of pointers to the constituent trees (TreeRoot objects)
Note that the pointers to the neighbour's of each tree must have been allocated before the constructor is called, otherwise the relative rotation scheme will not be constructed correctly.
Definition at line 356 of file tree.cc.
TreeForest() [2/3]
oomph::TreeForest::TreeForest () [inline]
Default constructor (empty and broken)
Definition at line 394 of file tree.h.
TreeForest() [3/3]
oomph::TreeForest::TreeForest (const TreeForest & dummy) [inline]
Broken copy constructor.
Definition at line 403 of file tree.h.
References oomph::BrokenCopy::broken_copy().
 TreeForest()
oomph::TreeForest::~TreeForest () [virtual]
Destructor: Delete the constituent trees (and thus the objects associated with its non-leaf nodes!)
Kill tree forest: Delete the constituent trees.
Definition at line 362 of file tree.cc.
References i, and Trees_pt.
Member Function Documentation
check_all_neighbours()
virtual void oomph::TreeForest::check_all_neighbours (DocInfo & doc_info) [pure virtual]
Document/check the neighbours of all the nodes in the forest. This must be overloaded for different types of forest.
Implemented in oomph::OcTreeForest, oomph::QuadTreeForest, and oomph::BinaryTreeForest.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
close_hanging_node_files()
void oomph::TreeForest::close_hanging_node_files (DocInfo & doc_info, Vector< std::ofstream *> & output_stream)
Close output files that will store any hanging nodes in the forest and delete any associated storage. This can be performed genercially in this base class.
Close the hanging node output files and delete storage allocated at the pointers. This can be done generically at the base level
Definition at line 433 of file tree.cc.
References oomph::DocInfo::is_doc_enabled().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
flush_trees()
void oomph::TreeForest::flush_trees () [inline]
Flush trees from forest.
Definition at line 452 of file tree.h.
Referenced by oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
ntree()
unsigned oomph::TreeForest::ntree () [inline]
Number of trees in forest.
Definition at line 446 of file tree.h.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::QuadTreeForest::construct_north_equivalents(), oomph::OcTreeForest::construct_up_right_equivalents(), oomph::BinaryTreeForest::find_neighbours(), oomph::QuadTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), stick_all_tree_nodes_into_vector(), and stick_leaves_into_vector().
open_hanging_node_files()
virtual void oomph::TreeForest::open_hanging_node_files (DocInfo & doc_info, Vector< std::ofstream *> & output_stream) [pure virtual]
Open output files that will store any hanging nodes in the forest. Return a vector of the output streams. This is included in the tree structure, so that we can use generic routines for mesh adaptation in two and three dimensions. The need for pointers to the output streams is because one cannot copy a stream!
Implemented in oomph::OcTreeForest, oomph::QuadTreeForest, and oomph::BinaryTreeForest.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
operator=()
void oomph::TreeForest::operator= (const TreeForest &) [inline]
Broken assignment operator.
Definition at line 409 of file tree.h.
References oomph::BrokenCopy::broken_assign(), oomph::Tree::stick_all_tree_nodes_into_vector(), and oomph::Tree::stick_leaves_into_vector().
stick_all_tree_nodes_into_vector()
void oomph::TreeForest::stick_all_tree_nodes_into_vector (Vector< Tree * > & all_forest_nodes)
Traverse forest and stick pointers to all `nodes` into Vector.
Traverse TreeForest: Preorder traverse and stick pointers to all nodes into Vector
Definition at line 405 of file tree.cc.
References i, oomph::Tree::nsons(), ntree(), oomph::Tree::son_pt(), and tree_pt().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::BinaryTreeForest::check_all_neighbours(), oomph::QuadTreeForest::check_all_neighbours(), oomph::OcTreeForest::check_all_neighbours(), oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level(), oomph::TreeBasedRefineableMeshBase::get_refinement_pattern(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::BinaryTreeForest::self_test(), oomph::QuadTreeForest::self_test(), oomph::OcTreeForest::self_test(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
stick_leaves_into_vector()
void oomph::TreeForest::stick_leaves_into_vector (Vector< Tree * > & forest_nodes)
Traverse forst and stick pointers to leaf `nodes` into Vector.
Traverse TreeForest: Preorder traverse and stick pointers to leaf nodes (only) into Vector
Definition at line 377 of file tree.cc.
References i, oomph::Tree::nsons(), ntree(), oomph::Tree::son_pt(), oomph::Tree::stick_leaves_into_vector(), and tree_pt().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
tree_pt()
TreeRoot* oomph::TreeForest::tree_pt (const unsigned & i) const [inline]
Return pointer to i-th tree in forest.
Definition at line 449 of file tree.h.
References i.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), stick_all_tree_nodes_into_vector(), and stick_leaves_into_vector().
Member Data Documentation
Trees_pt
Vector<TreeRoot*> oomph::TreeForest::Trees_pt [protected]
Vector containing the pointers to the trees.
Definition at line 461 of file tree.h.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents(), oomph::BinaryTreeForest::find_neighbours(), oomph::QuadTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), and ~TreeForest().
The documentation for this class was generated from the following files:
tree.h
tree.cc