oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D > Class Template Reference
QSUPGAdvectionDiffusionElement<DIM,NNODE_1D> elements are SUPG-stabilised Advection Diffusion elements with NNODE_1D nodal points in each coordinate direction. Inherits from QAdvectionDiffusionElement and overwrites their test functions.
#include <supg_advection_diffusion_elements.h>
Public Member Functions
QSUPGAdvectionDiffusionElement ()
Constructor: Call constructors for underlying QAdvectionDiffusion element. Initialise stabilisation parameter to zero.
double get_Tau_SUPG ()
Get stabilisation parameter for the element.
void switch_off_stabilisation ()
Set stabilisation parameter for the element to zero.
void compute_stabilisation_parameter ()
Compute stabilisation parameter for the element.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,u,w_x,w_y,tau_supg or x,y,z,u,w_x,w_y,w_z,tau_supg nplot points in each coordinate direction.
void output (std::ostream &outfile)
Output at default number of plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
Protected Member Functions
double dshape_and_dtest_eulerian_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Protected Attributes
double Tau_SUPG
SUPG stabilisation parameter.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >
QSUPGAdvectionDiffusionElement<DIM,NNODE_1D> elements are SUPG-stabilised Advection Diffusion elements with NNODE_1D nodal points in each coordinate direction. Inherits from QAdvectionDiffusionElement and overwrites their test functions.
Definition at line 47 of file supg_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QSUPGAdvectionDiffusionElement()
template<unsigned DIM, unsigned NNODE_1D>
oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::QSUPGAdvectionDiffusionElement () [inline]
Constructor: Call constructors for underlying QAdvectionDiffusion element. Initialise stabilisation parameter to zero.
Definition at line 57 of file supg_advection_diffusion_elements.h.
References oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG.
Member Function Documentation
compute_stabilisation_parameter()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter () [inline]
Compute stabilisation parameter for the element.
Definition at line 77 of file supg_advection_diffusion_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::get_wind_adv_diff(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::AdvectionDiffusionEquations< DIM >::pe(), s, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG, and oomph::FiniteElement::vertex_node_pt().
dshape_and_dtest_eulerian_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
QSUPGAdvectionDiffusionElement<DIM,NNODE_1D> elements are SUPG-stabilised Advection Diffusion elements with NNODE_1D nodal points in each coordinate direction. Inherits from QAdvectionDiffusionElement and overwrites their test functions.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
SUPG stabilisation: Petrov-Galerkin, i.e. test functions $ \ne $ shape functions
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 54 of file supg_advection_diffusion_elements.cc.
References oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff(), and i.
Referenced by oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output().
dshape_and_dtest_eulerian_at_knot_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
SUPG stabilisation: Petrov-Galerkin, i.e. test functions $ \ne $ shape functions
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 113 of file supg_advection_diffusion_elements.cc.
References oomph::Multi_domain_functions::Dim, i, and s.
Referenced by oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff(), and oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output().
get_Tau_SUPG()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::get_Tau_SUPG () [inline]
Get stabilisation parameter for the element.
Definition at line 63 of file supg_advection_diffusion_elements.h.
References oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,u,w_x,w_y,tau_supg or x,y,z,u,w_x,w_y,w_z,tau_supg nplot points in each coordinate direction.
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 176 of file supg_advection_diffusion_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::AdvectionDiffusionEquations< DIM >::get_wind_adv_diff(), i, oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output at default number of plot points.
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 223 of file supg_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 227 of file supg_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
Reimplemented from oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 231 of file supg_advection_diffusion_elements.h.
References oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff(), oomph::FiniteElement::output(), and s.
switch_off_stabilisation()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::switch_off_stabilisation () [inline]
Set stabilisation parameter for the element to zero.
Definition at line 70 of file supg_advection_diffusion_elements.h.
References oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG.
Member Data Documentation
Tau_SUPG
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::Tau_SUPG [protected]
SUPG stabilisation parameter.
Definition at line 251 of file supg_advection_diffusion_elements.h.
Referenced by oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::get_Tau_SUPG(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::QSUPGAdvectionDiffusionElement(), and oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::switch_off_stabilisation().
The documentation for this class was generated from the following files:
supg_advection_diffusion_elements.h
supg_advection_diffusion_elements.cc