oomph::DummyErrorEstimator Class Reference
#include <error_estimator.h>
Public Member Functions
DummyErrorEstimator (Mesh *mesh_pt, const Vector< unsigned > &elements_to_refine, const unsigned &central_node_number, const bool &use_lagrangian_coordinates=false)
Constructor. Provide mesh and number of the elements that define the regions within which elements are to be refined subsequently. Also specify the node number of a central node within elements -- it's used to determine if an element is in the region where refinement is supposed to take place. Optional boolean flag (defaulting to false) indicates that refinement decision is based on Lagrangian coordinates -- only applicable to solid meshes.
DummyErrorEstimator (Mesh *mesh_pt, const Vector< double > &lower_left, const Vector< double > &upper_right, const unsigned &central_node_number, const bool &use_lagrangian_coordinates=false)
Constructor. Provide vectors to `lower left` and `upper right` vertices of refinement region Also specify the node number of a central node within elements -- it's used to determine if an element is in the region where refinement is supposed to take place. Optional boolean flag (defaulting to false) indicates that refinement decision is based on Lagrangian coordinates -- only applicable to solid meshes.
DummyErrorEstimator (const DummyErrorEstimator &)
Broken copy constructor.
void operator= (const DummyErrorEstimator &)
Broken assignment operator.
virtual ~DummyErrorEstimator ()
Empty virtual destructor.
virtual void get_element_errors (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Compute the elemental error measures for a given mesh and store them in a vector. Doc errors etc.
Private Attributes
bool Use_lagrangian_coordinates
Use Lagrangian coordinates to decide which element is to be refined.
unsigned Central_node_number
Number of local node that is used to identify if an element is located in the refinement region.
Vector< Vector< double > > Region_upp_bound
Upper bounds for the coordinates of the refinement regions.
Vector< Vector< double > > Region_low_bound
Lower bounds for the coordinates of the refinement regions.
Detailed Description
Dummy error estimator, allows manual specification of refinement pattern by forcing refinement in regions defined by elements in a reference mesh.
Definition at line 471 of file error_estimator.h.
Constructor & Destructor Documentation
DummyErrorEstimator() [1/3]
oomph::DummyErrorEstimator::DummyErrorEstimator (Mesh * mesh_pt, const Vector< unsigned > & elements_to_refine, const unsigned & central_node_number, const bool & use_lagrangian_coordinates = false) [inline]
Constructor. Provide mesh and number of the elements that define the regions within which elements are to be refined subsequently. Also specify the node number of a central node within elements -- it's used to determine if an element is in the region where refinement is supposed to take place. Optional boolean flag (defaulting to false) indicates that refinement decision is based on Lagrangian coordinates -- only applicable to solid meshes.
Definition at line 484 of file error_estimator.h.
References e, oomph::Mesh::finite_element_pt(), i, oomph::Mesh::is_mesh_distributed(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Node::x(), and oomph::SolidNode::xi().
DummyErrorEstimator() [2/3]
oomph::DummyErrorEstimator::DummyErrorEstimator (Mesh * mesh_pt, const Vector< double > & lower_left, const Vector< double > & upper_right, const unsigned & central_node_number, const bool & use_lagrangian_coordinates = false) [inline]
Constructor. Provide vectors to `lower left` and `upper right` vertices of refinement region Also specify the node number of a central node within elements -- it's used to determine if an element is in the region where refinement is supposed to take place. Optional boolean flag (defaulting to false) indicates that refinement decision is based on Lagrangian coordinates -- only applicable to solid meshes.
Definition at line 569 of file error_estimator.h.
References oomph::Mesh::nelement().
DummyErrorEstimator() [3/3]
oomph::DummyErrorEstimator::DummyErrorEstimator (const DummyErrorEstimator &) [inline]
Broken copy constructor.
Definition at line 602 of file error_estimator.h.
References oomph::BrokenCopy::broken_copy().
 DummyErrorEstimator()
virtual oomph::DummyErrorEstimator::~DummyErrorEstimator () [inline], [virtual]
Empty virtual destructor.
Definition at line 616 of file error_estimator.h.
Member Function Documentation
get_element_errors()
virtual void oomph::DummyErrorEstimator::get_element_errors (Mesh *& mesh_pt, Vector< double > & elemental_error, DocInfo & doc_info) [inline], [virtual]
Compute the elemental error measures for a given mesh and store them in a vector. Doc errors etc.
Implements oomph::ErrorEstimator.
Definition at line 621 of file error_estimator.h.
References e, oomph::Mesh::finite_element_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Mesh::nelement(), oomph::FiniteElement::node_pt(), oomph::Node::x(), and oomph::SolidNode::xi().
operator=()
void oomph::DummyErrorEstimator::operator= (const DummyErrorEstimator &) [inline]
Broken assignment operator.
Definition at line 609 of file error_estimator.h.
References oomph::BrokenCopy::broken_assign().
Member Data Documentation
Central_node_number
unsigned oomph::DummyErrorEstimator::Central_node_number [private]
Number of local node that is used to identify if an element is located in the refinement region.
Definition at line 689 of file error_estimator.h.
Region_low_bound
Vector<Vector<double> > oomph::DummyErrorEstimator::Region_low_bound [private]
Lower bounds for the coordinates of the refinement regions.
Definition at line 695 of file error_estimator.h.
Region_upp_bound
Vector<Vector<double> > oomph::DummyErrorEstimator::Region_upp_bound [private]
Upper bounds for the coordinates of the refinement regions.
Definition at line 692 of file error_estimator.h.
Use_lagrangian_coordinates
bool oomph::DummyErrorEstimator::Use_lagrangian_coordinates [private]
Use Lagrangian coordinates to decide which element is to be refined.
Definition at line 685 of file error_estimator.h.
The documentation for this class was generated from the following file:
error_estimator.h