oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT > Class Template Reference
Crouzeix Raviart upgraded to become projectable.
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
ProjectableGeneralisedNewtonianCrouzeixRaviartElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Crouzeix Raviart elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures are stored internally.
unsigned nfields_for_projection ()
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values. (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class CROUZEIX_RAVIART_ELEMENT>
class oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >
Crouzeix Raviart upgraded to become projectable.
Definition at line 2576 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
ProjectableGeneralisedNewtonianCrouzeixRaviartElement()
template<class CROUZEIX_RAVIART_ELEMENT >
oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::ProjectableGeneralisedNewtonianCrouzeixRaviartElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2584 of file generalised_newtonian_navier_stokes_elements.h.
Member Function Documentation
data_values_of_field()
template<class CROUZEIX_RAVIART_ELEMENT >
Vector<std::pair<Data*,unsigned> > oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Crouzeix Raviart elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures are stored internally.
Implements oomph::ProjectableElementBase.
Definition at line 2592 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::GeneralisedElement::internal_data_pt(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class CROUZEIX_RAVIART_ELEMENT >
double oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 2695 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim().
jacobian_and_shape_of_field()
template<class CROUZEIX_RAVIART_ELEMENT >
double oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 2659 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), and oomph::FiniteElement::nnode().
local_equation()
template<class CROUZEIX_RAVIART_ELEMENT >
int oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2729 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nodal_local_eqn(), and oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_local_eqn().
nfields_for_projection()
template<class CROUZEIX_RAVIART_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
Implements oomph::ProjectableElementBase.
Definition at line 2628 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim().
nhistory_values_for_coordinate_projection()
template<class CROUZEIX_RAVIART_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2652 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class CROUZEIX_RAVIART_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2637 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class CROUZEIX_RAVIART_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2715 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), and oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
generalised_newtonian_navier_stokes_elements.h