oomph::SpineMesh Class Reference
#include <spines.h>
Public Member Functions
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
Return the n-th local SpineNode in element e. This is required to cast the nodes in a spine mesh to be SpineNodes and therefore allow access to the extra SpineNode data.
unsigned long assign_global_spine_eqn_numbers (Vector< double *> &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Spine. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Overload the mesh_level timestepper function to set the timestepper data for the spines.
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the time stepper forthe spine data that is stored in the mesh.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set any pinned spine `history` values to be consistent for continuation problems.
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses data stored in the spines.
void node_update (const bool &update_all_solid_nodes=false)
Update function to update all nodes of mesh [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
virtual void spine_node_update (SpineNode *spine_node_pt)=0
Update function for given spine node -- this must be implemented by all specific SpineMeshes.
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is read from the restart file.
Protected Attributes
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Additional Inherited Members
Detailed Description
General SpineMesh class.
Derived from Mesh with virtual so that spine meshes can be derived from general meshes, without multiple copies of Mesh objects.
Definition at line 565 of file spines.h.
Constructor & Destructor Documentation
 SpineMesh()
oomph::SpineMesh::~SpineMesh () [virtual]
Destructor to clean up the memory allocated to the spines.
Definition at line 75 of file spines.cc.
References i, and oomph::SpineNode::Spine_pt.
Member Function Documentation
add_spine_pt()
void oomph::SpineMesh::add_spine_pt (Spine *const & spine_pt) [inline]
Add a spine to the mesh.
Definition at line 587 of file spines.h.
assign_global_spine_eqn_numbers()
unsigned long oomph::SpineMesh::assign_global_spine_eqn_numbers (Vector< double *> & Dof_pt)
Assign spines to Spine_pt vector of element.
Assign (global) equation numbers to spines, nodes and elements.
Assign equation numbers for spines
Definition at line 135 of file spines.cc.
References oomph::Data::assign_eqn_numbers(), i, oomph::Spine::spine_height_pt(), and oomph::SpineNode::Spine_pt.
Referenced by node_update().
describe_spine_dofs()
void oomph::SpineMesh::describe_spine_dofs (std::ostream & out, const std::string & current_string) const
Function to describe the dofs of the Spine. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Definition at line 163 of file spines.cc.
References oomph::Data::describe_dofs(), i, oomph::Spine::spine_height_pt(), oomph::SpineNode::Spine_pt, and oomph::Global_string_for_annotation::string().
does_pointer_correspond_to_spine_data()
bool oomph::SpineMesh::does_pointer_correspond_to_spine_data (double *const & parameter_pt)
Check whether the pointer parameter_pt addresses data stored in the spines.
Return true if the pointer addresses data stored within the spines, false if not.
Definition at line 216 of file spines.cc.
References oomph::Data::does_pointer_correspond_to_value(), i, and oomph::SpineNode::Spine_pt.
dump()
void oomph::SpineMesh::dump (std::ofstream & dump_file) const
Overload the dump function so that the spine data is dumped.
Overload the dump function so that the spine data is also dumped.
Definition at line 235 of file spines.cc.
References oomph::Data::dump(), oomph::Mesh::dump(), s, oomph::Spine::spine_height_pt(), and oomph::SpineNode::spine_pt().
element_node_pt()
SpineNode* oomph::SpineMesh::element_node_pt (const unsigned long & e, const unsigned & n) [inline]
Return the n-th local SpineNode in element e. This is required to cast the nodes in a spine mesh to be SpineNodes and therefore allow access to the extra SpineNode data.
Definition at line 614 of file spines.h.
References e, oomph::FiniteElement::node_pt(), and oomph::Global_string_for_annotation::string().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines().
node_pt()
SpineNode* oomph::SpineMesh::node_pt (const unsigned long & n) [inline]
Return a pointer to the n-th global SpineNode.
Definition at line 592 of file spines.h.
node_update()
void oomph::SpineMesh::node_update (const bool & update_all_solid_nodes = false) [virtual]
Update function to update all nodes of mesh [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Update function to update all nodes of mesh. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes (which defaults to false) is set to true.]
Reimplemented from oomph::Mesh.
Definition at line 92 of file spines.cc.
References assign_global_spine_eqn_numbers(), oomph::SpineNode::node_update(), and oomph::Global_string_for_annotation::string().
nspine()
unsigned long oomph::SpineMesh::nspine () const [inline]
Return the number of spines in the mesh.
Definition at line 584 of file spines.h.
Referenced by oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::pin_all_spines().
read()
void oomph::SpineMesh::read (std::ifstream & restart_file) [virtual]
Overload the read function so that the spine data is read from the restart file.
Overload the read function so that the spine data is also read.
Reimplemented from oomph::Mesh.
Definition at line 259 of file spines.cc.
References oomph::Data::read(), oomph::Mesh::read(), s, oomph::Spine::spine_height_pt(), oomph::SpineNode::spine_pt(), and oomph::Global_string_for_annotation::string().
set_consistent_pinned_spine_values_for_continuation()
void oomph::SpineMesh::set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const & continuation_stepper_pt)
Set any pinned spine `history` values to be consistent for continuation problems.
Set the data associated with pinned spine values to be consistent for continuation when using the continuation storage scheme
Definition at line 198 of file spines.cc.
References i, oomph::ContinuationStorageScheme::set_consistent_pinned_values(), and oomph::SpineNode::Spine_pt.
set_mesh_level_time_stepper()
void oomph::SpineMesh::set_mesh_level_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data) [inline], [virtual]
Overload the mesh_level timestepper function to set the timestepper data for the spines.
Reimplemented from oomph::Mesh.
Definition at line 666 of file spines.h.
set_spine_time_stepper()
void oomph::SpineMesh::set_spine_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data)
Set the time stepper forthe spine data that is stored in the mesh.
Assign time stepper to spines data.
Definition at line 180 of file spines.cc.
References i, oomph::Data::set_time_stepper(), oomph::Spine::spine_height_pt(), and oomph::SpineNode::Spine_pt.
spine_node_update()
virtual void oomph::SpineMesh::spine_node_update (SpineNode * spine_node_pt) [pure virtual]
Update function for given spine node -- this must be implemented by all specific SpineMeshes.
Implemented in oomph::TwoLayerSpineMesh< ELEMENT >, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >, oomph::ChannelSpineMesh< ELEMENT >, oomph::SingleLayerSpineMesh< ELEMENT >, oomph::SingleLayerCubicSpineMesh< ELEMENT >, and oomph::HorizontalSingleLayerSpineMesh< ELEMENT >.
Referenced by oomph::SpineNode::node_update().
spine_pt() [1/2]
Spine*& oomph::SpineMesh::spine_pt (const unsigned long & i) [inline]
Return the i-th spine in the mesh.
Definition at line 578 of file spines.h.
References i.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::pin_all_spines().
spine_pt() [2/2]
const Spine* oomph::SpineMesh::spine_pt (const unsigned long & i) const [inline]
Return the i-th spine in the mesh (const version)
Definition at line 581 of file spines.h.
References i.
Member Data Documentation
Spine_pt
Vector<Spine*> oomph::SpineMesh::Spine_pt [protected]
A Spine mesh contains a Vector of pointers to spines.
Definition at line 570 of file spines.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::HorizontalSingleLayerSpineMesh< ELEMENT >::build_horizontal_single_layer_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::ChannelSpineMesh< ELEMENT >::centre_spine_pt(), oomph::ChannelSpineMesh< ELEMENT >::left_spine_pt(), and oomph::ChannelSpineMesh< ELEMENT >::right_spine_pt().
The documentation for this class was generated from the following files:
spines.h
spines.cc