oomph::AxisymFoepplvonKarmanEquations Class Reference
#include <axisym_displ_based_fvk_elements.h>
Public Types
typedef void(* AxisymFoepplvonKarmanPressureFctPt) (const double &r, double &f)
Function pointer to pressure function fct(r,f(r)) -- r is a Vector!
typedef void(* AxisymFoepplvonKarmanPressureFctPt) (const double &r, double &f)
Function pointer to pressure function fct(r,f(r)) -- r is a Vector!
Public Member Functions
AxisymFoepplvonKarmanEquations ()
Constructor (must initialise the Pressure_fct_pt). Also set physical parameters to their default values.
AxisymFoepplvonKarmanEquations (const AxisymFoepplvonKarmanEquations &dummy)
Broken copy constructor.
void operator= (const AxisymFoepplvonKarmanEquations &)
Broken assignment operator.
const double & nu () const
Poisson's ratio.
double *& nu_pt ()
Pointer to Poisson's ratio.
const double & eta () const
FvK parameter.
double *& eta_pt ()
Pointer to FvK parameter.
virtual unsigned nodal_index_fvk (const unsigned &i=0) const
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: transverse displacement w 1: laplacian w 2: radial displacement u In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,w at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,w_exact at n_plot plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,w_exact at n_plot plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
AxisymFoepplvonKarmanPressureFctPt & pressure_fct_pt ()
Access function: Pointer to pressure function.
AxisymFoepplvonKarmanPressureFctPt pressure_fct_pt () const
Access function: Pointer to pressure function. Const version.
virtual void get_pressure_fvk (const unsigned &ipt, const double &r, double &pressure) const
Get pressure term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
void get_gradient_of_deflection (const Vector< double > &s, Vector< double > &gradient) const
Get gradient of deflection: gradient[i] = dw/dr_i */.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals with this element's contribution.
double interpolated_w_fvk (const Vector< double > &s) const
Return FE representation of transverse displacement.
double interpolated_u_fvk (const Vector< double > &s) const
Return FE representation of radial displacement.
bool interpolated_stress (const Vector< double > &s, double &sigma_r_r, double &sigma_phi_phi) const
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
unsigned self_test ()
Self-test: Return 0 for OK.
void use_linear_bending_model ()
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
AxisymFoepplvonKarmanEquations ()
Constructor (must initialise the Pressure_fct_pt and Airy_forcing_fct_pt to null). Also set physical parameters to their default values.
AxisymFoepplvonKarmanEquations (const AxisymFoepplvonKarmanEquations &dummy)
Broken copy constructor.
void operator= (const AxisymFoepplvonKarmanEquations &)
Broken assignment operator.
const double & eta () const
FvK parameter.
double *& eta_pt ()
Pointer to FvK parameter.
virtual unsigned nodal_index_fvk (const unsigned &i=0) const
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: w 1: laplacian w 2: phi 3: laplacian phi 4-5: smooth first derivatives In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,w at n_plot plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,w_exact at n_plot plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,w_exact at n_plot plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
AxisymFoepplvonKarmanPressureFctPt & pressure_fct_pt ()
Access function: Pointer to pressure function.
AxisymFoepplvonKarmanPressureFctPt pressure_fct_pt () const
Access function: Pointer to pressure function. Const version.
AxisymFoepplvonKarmanPressureFctPt & airy_forcing_fct_pt ()
Access function: Pointer to Airy forcing function.
AxisymFoepplvonKarmanPressureFctPt airy_forcing_fct_pt () const
Access function: Pointer to Airy forcing function. Const version.
virtual void get_pressure_fvk (const unsigned &ipt, const double &r, double &pressure) const
Get pressure term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
virtual void get_airy_forcing_fvk (const unsigned &ipt, const double &r, double &airy_forcing) const
Get Airy forcing term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
void get_gradient_of_deflection (const Vector< double > &s, Vector< double > &gradient) const
Get gradient of deflection: gradient[i] = dw/dr_i */.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals with this element's contribution.
double interpolated_w_fvk (const Vector< double > &s) const
Return FE representation of vertical displacement, w_fvk(s) at local coordinate s.
bool interpolated_stress (const Vector< double > &s, double &sigma_r_r, double &sigma_phi_phi)
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
unsigned self_test ()
Self-test: Return 0 for OK.
void use_linear_bending_model ()
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidr, Shape &test, DShape &dtestdr) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Attributes
double * Eta_pt
Pointer to FvK parameter.
AxisymFoepplvonKarmanPressureFctPt Pressure_fct_pt
Pointer to pressure function:
double * Nu_pt
Pointer to Poisson's ratio.
bool Linear_bending_model
Flag which stores whether we are using a linear, pure bending model instead of the full non-linear Foeppl-von Karman.
AxisymFoepplvonKarmanPressureFctPt Airy_forcing_fct_pt
Pointer to Airy forcing function.
Static Private Attributes
static double Default_Physical_Constant_Value = 0.0
Default value for physical constants.
Additional Inherited Members
Detailed Description
A class for all isoparametric elements that solve the axisYm Foeppl von Karman equations in a displacement based formulation.
This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
A class for all isoparametric elements that solve the axisum Foeppl von Karman equations.
This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 55 of file axisym_displ_based_fvk_elements.h.
Member Typedef Documentation
AxisymFoepplvonKarmanPressureFctPt [1/2]
typedef void(* oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanPressureFctPt) (const double &r, double &f)
Function pointer to pressure function fct(r,f(r)) -- r is a Vector!
Definition at line 62 of file axisym_fvk_elements.h.
AxisymFoepplvonKarmanPressureFctPt [2/2]
typedef void(* oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanPressureFctPt) (const double &r, double &f)
Function pointer to pressure function fct(r,f(r)) -- r is a Vector!
Definition at line 62 of file axisym_displ_based_fvk_elements.h.
Constructor & Destructor Documentation
AxisymFoepplvonKarmanEquations() [1/4]
oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanEquations () [inline]
Constructor (must initialise the Pressure_fct_pt). Also set physical parameters to their default values.
Definition at line 67 of file axisym_displ_based_fvk_elements.h.
AxisymFoepplvonKarmanEquations() [2/4]
oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanEquations (const AxisymFoepplvonKarmanEquations & dummy) [inline]
Broken copy constructor.
Definition at line 71 of file axisym_displ_based_fvk_elements.h.
References oomph::BrokenCopy::broken_copy().
AxisymFoepplvonKarmanEquations() [3/4]
oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanEquations () [inline]
Constructor (must initialise the Pressure_fct_pt and Airy_forcing_fct_pt to null). Also set physical parameters to their default values.
Definition at line 67 of file axisym_fvk_elements.h.
References Default_Physical_Constant_Value, Eta_pt, and Linear_bending_model.
AxisymFoepplvonKarmanEquations() [4/4]
oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanEquations (const AxisymFoepplvonKarmanEquations & dummy) [inline]
Broken copy constructor.
Definition at line 76 of file axisym_fvk_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
airy_forcing_fct_pt() [1/2]
AxisymFoepplvonKarmanPressureFctPt& oomph::AxisymFoepplvonKarmanEquations::airy_forcing_fct_pt () [inline]
Access function: Pointer to Airy forcing function.
Definition at line 175 of file axisym_fvk_elements.h.
References Airy_forcing_fct_pt.
airy_forcing_fct_pt() [2/2]
AxisymFoepplvonKarmanPressureFctPt oomph::AxisymFoepplvonKarmanEquations::airy_forcing_fct_pt () const [inline]
Access function: Pointer to Airy forcing function. Const version.
Definition at line 179 of file axisym_fvk_elements.h.
References Airy_forcing_fct_pt.
compute_error() [1/4]
void oomph::AxisymFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Reimplemented from oomph::FiniteElement.
compute_error() [2/4]
void oomph::AxisymFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 155 of file axisym_fvk_elements.h.
compute_error() [3/4]
void oomph::AxisymFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 438 of file axisym_displ_based_fvk_elements.cc.
References oomph::FiniteElement::integral_pt(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by interpolated_stress(), and output_fct().
compute_error() [4/4]
void oomph::AxisymFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 169 of file axisym_displ_based_fvk_elements.h.
dshape_and_dtest_eulerian_at_knot_axisym_fvk() [1/2]
virtual double oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
dshape_and_dtest_eulerian_at_knot_axisym_fvk() [2/2]
virtual double oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_axisym_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Referenced by fill_in_contribution_to_residuals(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct(), and use_linear_bending_model().
dshape_and_dtest_eulerian_axisym_fvk() [1/2]
virtual double oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
dshape_and_dtest_eulerian_axisym_fvk() [2/2]
virtual double oomph::AxisymFoepplvonKarmanEquations::dshape_and_dtest_eulerian_axisym_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidr, Shape & test, DShape & dtestdr) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Referenced by oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct(), and use_linear_bending_model().
eta() [1/2]
const double& oomph::AxisymFoepplvonKarmanEquations::eta () const [inline]
FvK parameter.
Definition at line 88 of file axisym_fvk_elements.h.
References Eta_pt.
eta() [2/2]
const double& oomph::AxisymFoepplvonKarmanEquations::eta () const [inline]
FvK parameter.
Definition at line 104 of file axisym_displ_based_fvk_elements.h.
References Eta_pt.
Referenced by fill_in_contribution_to_residuals().
eta_pt() [1/2]
double* & oomph::AxisymFoepplvonKarmanEquations::eta_pt () [inline]
Pointer to FvK parameter.
Definition at line 91 of file axisym_fvk_elements.h.
References Eta_pt.
eta_pt() [2/2]
double* & oomph::AxisymFoepplvonKarmanEquations::eta_pt () [inline]
Pointer to FvK parameter.
Definition at line 107 of file axisym_displ_based_fvk_elements.h.
References Eta_pt.
fill_in_contribution_to_residuals() [1/2]
void oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Fill in the residuals with this element's contribution.
Compute contribution to element residual Vector
Pure version without hanging nodes
Reimplemented from oomph::GeneralisedElement.
Definition at line 52 of file axisym_displ_based_fvk_elements.cc.
References dshape_and_dtest_eulerian_at_knot_axisym_fvk(), eta(), get_pressure_fvk(), oomph::FiniteElement::integral_pt(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), nu(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by get_gradient_of_deflection().
fill_in_contribution_to_residuals() [2/2]
void oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Fill in the residuals with this element's contribution.
Reimplemented from oomph::GeneralisedElement.
get_airy_forcing_fvk()
virtual void oomph::AxisymFoepplvonKarmanEquations::get_airy_forcing_fvk (const unsigned & ipt, const double & r, double & airy_forcing) const [inline], [virtual]
Get Airy forcing term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
Definition at line 206 of file axisym_fvk_elements.h.
References Airy_forcing_fct_pt.
get_gradient_of_deflection() [1/2]
void oomph::AxisymFoepplvonKarmanEquations::get_gradient_of_deflection (const Vector< double > & s, Vector< double > & gradient) const [inline]
Get gradient of deflection: gradient[i] = dw/dr_i */.
Definition at line 209 of file axisym_displ_based_fvk_elements.h.
References oomph::FiniteElement::dshape_eulerian(), fill_in_contribution_to_residuals(), oomph::FiniteElement::nnode(), nodal_index_fvk(), and oomph::FiniteElement::nodal_value().
get_gradient_of_deflection() [2/2]
void oomph::AxisymFoepplvonKarmanEquations::get_gradient_of_deflection (const Vector< double > & s, Vector< double > & gradient) const [inline]
Get gradient of deflection: gradient[i] = dw/dr_i */.
Definition at line 223 of file axisym_fvk_elements.h.
References oomph::FiniteElement::dshape_eulerian(), fill_in_contribution_to_residuals(), oomph::FiniteElement::nnode(), nodal_index_fvk(), and oomph::FiniteElement::nodal_value().
get_pressure_fvk() [1/2]
virtual void oomph::AxisymFoepplvonKarmanEquations::get_pressure_fvk (const unsigned & ipt, const double & r, double & pressure) const [inline], [virtual]
Get pressure term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.
Definition at line 186 of file axisym_fvk_elements.h.
References Pressure_fct_pt.
get_pressure_fvk() [2/2]
virtual void oomph::AxisymFoepplvonKarmanEquations::get_pressure_fvk (const unsigned & ipt, const double & r, double & pressure) const [inline], [virtual]
Get pressure term at (Eulerian) position r. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.
Definition at line 192 of file axisym_displ_based_fvk_elements.h.
References Pressure_fct_pt.
Referenced by fill_in_contribution_to_residuals(), and oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::get_pressure_fvk().
interpolated_stress() [1/2]
bool oomph::AxisymFoepplvonKarmanEquations::interpolated_stress (const Vector< double > & s, double & sigma_r_r, double & sigma_phi_phi)
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
Definition at line 287 of file axisym_fvk_elements.cc.
References compute_error(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::get_s_plot(), oomph::FiniteElement::integral_pt(), interpolated_stress(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), oomph::Integral::nweight(), output(), output_fct(), oomph::FiniteElement::raw_nodal_position(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::FiniteElement::write_tecplot_zone_footer().
interpolated_stress() [2/2]
bool oomph::AxisymFoepplvonKarmanEquations::interpolated_stress (const Vector< double > & s, double & sigma_r_r, double & sigma_phi_phi) const
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
Compute in-plane stresses. Return boolean to indicate success (false if attempt to evaluate stresses at zero radius)
Definition at line 238 of file axisym_displ_based_fvk_elements.cc.
References oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::interpolated_x(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), nu(), oomph::FiniteElement::raw_nodal_position(), and oomph::FiniteElement::raw_nodal_value().
Referenced by interpolated_stress(), interpolated_u_fvk(), interpolated_w_fvk(), output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output(), and self_test().
interpolated_u_fvk()
double oomph::AxisymFoepplvonKarmanEquations::interpolated_u_fvk (const Vector< double > & s) const [inline]
Return FE representation of radial displacement.
Definition at line 273 of file axisym_displ_based_fvk_elements.h.
References interpolated_stress(), oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), s, self_test(), and oomph::FiniteElement::shape().
Referenced by output().
interpolated_w_fvk() [1/2]
double oomph::AxisymFoepplvonKarmanEquations::interpolated_w_fvk (const Vector< double > & s) const [inline]
Return FE representation of transverse displacement.
Definition at line 245 of file axisym_displ_based_fvk_elements.h.
References oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
Referenced by compute_error(), interpolated_stress(), output(), and oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output().
interpolated_w_fvk() [2/2]
double oomph::AxisymFoepplvonKarmanEquations::interpolated_w_fvk (const Vector< double > & s) const [inline]
Return FE representation of vertical displacement, w_fvk(s) at local coordinate s.
Definition at line 259 of file axisym_fvk_elements.h.
References interpolated_stress(), oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), s, self_test(), and oomph::FiniteElement::shape().
nodal_index_fvk() [1/2]
virtual unsigned oomph::AxisymFoepplvonKarmanEquations::nodal_index_fvk (const unsigned & i = 0) const [inline], [virtual]
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: w 1: laplacian w 2: phi 3: laplacian phi 4-5: smooth first derivatives In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 104 of file axisym_fvk_elements.h.
References i.
nodal_index_fvk() [2/2]
virtual unsigned oomph::AxisymFoepplvonKarmanEquations::nodal_index_fvk (const unsigned & i = 0) const [inline], [virtual]
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: transverse displacement w 1: laplacian w 2: radial displacement u In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 118 of file axisym_displ_based_fvk_elements.h.
References i.
Referenced by oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), fill_in_contribution_to_residuals(), get_gradient_of_deflection(), interpolated_stress(), interpolated_u_fvk(), interpolated_w_fvk(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::position(), and use_linear_bending_model().
nu()
const double& oomph::AxisymFoepplvonKarmanEquations::nu () const [inline]
Poisson's ratio.
Definition at line 83 of file axisym_displ_based_fvk_elements.h.
References Nu_pt.
Referenced by fill_in_contribution_to_residuals(), and interpolated_stress().
nu_pt()
double* & oomph::AxisymFoepplvonKarmanEquations::nu_pt () [inline]
Pointer to Poisson's ratio.
Definition at line 101 of file axisym_displ_based_fvk_elements.h.
References Nu_pt.
operator=() [1/2]
void oomph::AxisymFoepplvonKarmanEquations::operator= (const AxisymFoepplvonKarmanEquations &) [inline]
Broken assignment operator.
Definition at line 77 of file axisym_displ_based_fvk_elements.h.
References oomph::BrokenCopy::broken_assign().
operator=() [2/2]
void oomph::AxisymFoepplvonKarmanEquations::operator= (const AxisymFoepplvonKarmanEquations &) [inline]
Broken assignment operator.
Definition at line 82 of file axisym_fvk_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/8]
void oomph::AxisymFoepplvonKarmanEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 108 of file axisym_fvk_elements.h.
References output().
output() [2/8]
void oomph::AxisymFoepplvonKarmanEquations::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output FE representation of soln: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
output() [3/8]
void oomph::AxisymFoepplvonKarmanEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 119 of file axisym_fvk_elements.h.
References output(), and output_fct().
output() [4/8]
void oomph::AxisymFoepplvonKarmanEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 122 of file axisym_displ_based_fvk_elements.h.
Referenced by interpolated_stress(), output(), and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output().
output() [5/8]
void oomph::AxisymFoepplvonKarmanEquations::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C-style output FE representation of soln: r,w at n_plot plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
output() [6/8]
void oomph::AxisymFoepplvonKarmanEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: r,w,sigma_r_r,sigma_phi_phi at n_plot plot points.
Output function: r, w, sigma_r_r, sigma_phi_phi nplot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 317 of file axisym_displ_based_fvk_elements.cc.
References oomph::FiniteElement::get_s_plot(), interpolated_stress(), interpolated_u_fvk(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), and s.
output() [7/8]
void oomph::AxisymFoepplvonKarmanEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 133 of file axisym_displ_based_fvk_elements.h.
References output(), and output_fct().
output() [8/8]
void oomph::AxisymFoepplvonKarmanEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,w at n_plot plot points.
C-style output function: r,w nplot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 355 of file axisym_displ_based_fvk_elements.cc.
References oomph::FiniteElement::get_s_plot(), interpolated_u_fvk(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), output_fct(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/4]
void oomph::AxisymFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,w_exact at n_plot plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
output_fct() [2/4]
virtual void oomph::AxisymFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: r,w_exact at n_plot plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 136 of file axisym_fvk_elements.h.
References compute_error().
output_fct() [3/4]
void oomph::AxisymFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,w_exact at n_plot plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
r,w_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 390 of file axisym_displ_based_fvk_elements.cc.
References compute_error(), oomph::FiniteElement::get_s_plot(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by interpolated_stress(), output(), and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::output_fct().
output_fct() [4/4]
virtual void oomph::AxisymFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: r,w_exact at n_plot plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, and oomph::AxisymFoepplvonKarmanElement< NNODE_1D >.
Definition at line 150 of file axisym_displ_based_fvk_elements.h.
References compute_error().
pressure_fct_pt() [1/4]
AxisymFoepplvonKarmanPressureFctPt& oomph::AxisymFoepplvonKarmanEquations::pressure_fct_pt () [inline]
Access function: Pointer to pressure function.
Definition at line 167 of file axisym_fvk_elements.h.
References Pressure_fct_pt.
pressure_fct_pt() [2/4]
AxisymFoepplvonKarmanPressureFctPt oomph::AxisymFoepplvonKarmanEquations::pressure_fct_pt () const [inline]
Access function: Pointer to pressure function. Const version.
Definition at line 171 of file axisym_fvk_elements.h.
References Pressure_fct_pt.
pressure_fct_pt() [3/4]
AxisymFoepplvonKarmanPressureFctPt& oomph::AxisymFoepplvonKarmanEquations::pressure_fct_pt () [inline]
Access function: Pointer to pressure function.
Definition at line 181 of file axisym_displ_based_fvk_elements.h.
References Pressure_fct_pt.
pressure_fct_pt() [4/4]
AxisymFoepplvonKarmanPressureFctPt oomph::AxisymFoepplvonKarmanEquations::pressure_fct_pt () const [inline]
Access function: Pointer to pressure function. Const version.
Definition at line 185 of file axisym_displ_based_fvk_elements.h.
References Pressure_fct_pt.
self_test() [1/2]
unsigned oomph::AxisymFoepplvonKarmanEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
self_test() [2/2]
unsigned oomph::AxisymFoepplvonKarmanEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 209 of file axisym_displ_based_fvk_elements.cc.
References interpolated_stress(), and oomph::FiniteElement::self_test().
Referenced by interpolated_u_fvk(), and interpolated_w_fvk().
use_linear_bending_model() [1/2]
void oomph::AxisymFoepplvonKarmanEquations::use_linear_bending_model () [inline]
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
Definition at line 297 of file axisym_fvk_elements.h.
References dshape_and_dtest_eulerian_at_knot_axisym_fvk(), dshape_and_dtest_eulerian_axisym_fvk(), Eta_pt, Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::node_pt(), oomph::Data::pin(), and Pressure_fct_pt.
use_linear_bending_model() [2/2]
void oomph::AxisymFoepplvonKarmanEquations::use_linear_bending_model () [inline]
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
Definition at line 316 of file axisym_displ_based_fvk_elements.h.
References dshape_and_dtest_eulerian_at_knot_axisym_fvk(), dshape_and_dtest_eulerian_axisym_fvk(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::node_pt(), and oomph::Data::pin().
Member Data Documentation
Airy_forcing_fct_pt
AxisymFoepplvonKarmanPressureFctPt oomph::AxisymFoepplvonKarmanEquations::Airy_forcing_fct_pt [protected]
Pointer to Airy forcing function.
Definition at line 357 of file axisym_fvk_elements.h.
Referenced by airy_forcing_fct_pt(), and get_airy_forcing_fvk().
Default_Physical_Constant_Value
static double oomph::AxisymFoepplvonKarmanEquations::Default_Physical_Constant_Value = 0.0 [static], [private]
Default value for physical constants.
Default value physical constants.
Definition at line 385 of file axisym_displ_based_fvk_elements.h.
Referenced by AxisymFoepplvonKarmanEquations().
Eta_pt
double * oomph::AxisymFoepplvonKarmanEquations::Eta_pt [protected]
Pointer to FvK parameter.
Definition at line 370 of file axisym_displ_based_fvk_elements.h.
Referenced by AxisymFoepplvonKarmanEquations(), eta(), eta_pt(), and use_linear_bending_model().
Linear_bending_model
bool oomph::AxisymFoepplvonKarmanEquations::Linear_bending_model [protected]
Flag which stores whether we are using a linear, pure bending model instead of the full non-linear Foeppl-von Karman.
Definition at line 380 of file axisym_displ_based_fvk_elements.h.
Referenced by AxisymFoepplvonKarmanEquations(), fill_in_contribution_to_residuals(), interpolated_stress(), and use_linear_bending_model().
Nu_pt
double* oomph::AxisymFoepplvonKarmanEquations::Nu_pt [protected]
Pointer to Poisson's ratio.
Definition at line 376 of file axisym_displ_based_fvk_elements.h.
Referenced by nu(), and nu_pt().
Pressure_fct_pt
AxisymFoepplvonKarmanPressureFctPt oomph::AxisymFoepplvonKarmanEquations::Pressure_fct_pt [protected]
Pointer to pressure function:
Definition at line 373 of file axisym_displ_based_fvk_elements.h.
Referenced by get_pressure_fvk(), pressure_fct_pt(), and use_linear_bending_model().
The documentation for this class was generated from the following files:
axisym_displ_based_fvk_elements.h
axisym_fvk_elements.h
axisym_displ_based_fvk_elements.cc
axisym_fvk_elements.cc