oomph::MGPreconditioner< DIM > Class Template Reference
An interface to allow scalar MG to be used as a Preconditioner.
#include <geometric_multigrid.h>
Public Member Functions
MGPreconditioner (MGProblem *mg_problem_pt)
Constructor.
~MGPreconditioner ()
Destructor (empty)
MGPreconditioner (const MGPreconditioner &)
Broken copy constructor.
void operator= (const MGPreconditioner &)
Broken assignment operator.
void setup ()
Function to set up a preconditioner for the linear system.
virtual void preconditioner_solve (const DoubleVector &rhs, DoubleVector &z)
Function applies MG to the vector r for a full solve.
void clean_up_memory ()
Clean up memory.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::MGPreconditioner< DIM >
An interface to allow scalar MG to be used as a Preconditioner.
Definition at line 711 of file geometric_multigrid.h.
Constructor & Destructor Documentation
MGPreconditioner() [1/2]
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::MGPreconditioner (MGProblem * mg_problem_pt) [inline]
Constructor.
Definition at line 716 of file geometric_multigrid.h.
 MGPreconditioner()
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::~MGPreconditioner () [inline]
Destructor (empty)
Definition at line 723 of file geometric_multigrid.h.
MGPreconditioner() [2/2]
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::MGPreconditioner (const MGPreconditioner< DIM > &) [inline]
Broken copy constructor.
Definition at line 726 of file geometric_multigrid.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::clean_up_memory () [inline], [virtual]
Clean up memory.
Reimplemented from oomph::MGSolver< DIM >.
Definition at line 800 of file geometric_multigrid.h.
operator=()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::operator= (const MGPreconditioner< DIM > &) [inline]
Broken assignment operator.
Definition at line 732 of file geometric_multigrid.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<unsigned DIM>
virtual void oomph::MGPreconditioner< DIM >::preconditioner_solve (const DoubleVector & rhs, DoubleVector & z) [inline], [virtual]
Function applies MG to the vector r for a full solve.
Implements oomph::Preconditioner.
Definition at line 765 of file geometric_multigrid.h.
References oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, and oomph::OomphInfo::stream_pt().
setup()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::setup () [inline], [virtual]
Function to set up a preconditioner for the linear system.
Implements oomph::Preconditioner.
Definition at line 738 of file geometric_multigrid.h.
References oomph::MPI_Helpers::communicator_pt(), oomph::oomph_info, and oomph::OomphInfo::stream_pt().
The documentation for this class was generated from the following file:
geometric_multigrid.h