oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT > Class Template Reference
#include <Tpml_helmholtz_elements.h>
Public Member Functions
TPMLHelmholtzElement ()
Constructor: Call constructors for TElement and PMLHelmholtz equations.
TPMLHelmholtzElement (const TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 2
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
class oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >
TPMLHelmholtzElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional PMLHelmholtz elements with NNODE_1D nodal points along each element edge. Inherits from TElement and PMLHelmholtzEquations
Definition at line 66 of file Tpml_helmholtz_elements.h.
Constructor & Destructor Documentation
TPMLHelmholtzElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::TPMLHelmholtzElement () [inline]
Constructor: Call constructors for TElement and PMLHelmholtz equations.
Definition at line 75 of file Tpml_helmholtz_elements.h.
TPMLHelmholtzElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::TPMLHelmholtzElement (const TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 82 of file Tpml_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT >
double oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLHelmholtzEquationsBase< DIM >.
Definition at line 262 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_helmholtz(), and oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output_fct().
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT >
double oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLHelmholtzEquationsBase< DIM >.
Definition at line 227 of file Tpml_helmholtz_elements.h.
References oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output_fct().
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 182 of file Tpml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquationsBase< DIM >::get_flux(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 175 of file Tpml_helmholtz_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 178 of file Tpml_helmholtz_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 195 of file Tpml_helmholtz_elements.h.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::FiniteElement.
Definition at line 104 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 111 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::FiniteElement.
Definition at line 119 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 127 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact.
Reimplemented from oomph::FiniteElement.
Definition at line 135 of file Tpml_helmholtz_elements.h.
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Reimplemented from oomph::FiniteElement.
Definition at line 144 of file Tpml_helmholtz_elements.h.
References oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_helmholtz(), oomph::FiniteElement::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
Reimplemented from oomph::FiniteElement.
Definition at line 99 of file Tpml_helmholtz_elements.h.
References oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::Initial_Nvalue.
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
Node* oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 199 of file Tpml_helmholtz_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D, class PML_ELEMENT>
const unsigned oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::Initial_Nvalue = 2 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
! Cleanup - this was not here before!
Definition at line 205 of file Tpml_helmholtz_elements.h.
Referenced by oomph::TPMLHelmholtzElement< DIM, NNODE_1D, PML_ELEMENT >::required_nvalue().
The documentation for this class was generated from the following file:
Tpml_helmholtz_elements.h