oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <steady_axisym_advection_diffusion_elements.h>
Public Types
typedef void(* SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
typedef void(* SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Public Member Functions
SteadyAxisymAdvectionDiffusionFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
SteadyAxisymAdvectionDiffusionFluxElement ()
Broken empty constructor.
SteadyAxisymAdvectionDiffusionFluxElement (const SteadyAxisymAdvectionDiffusionFluxElement &dummy)
Broken copy constructor.
SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt & beta_fct_pt ()
Broken assignment operator.
SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt & alpha_fct_pt ()
Access function for the prescribed-alpha function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &nplot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_beta (const Vector< double > &x, double &beta)
Function to calculate the prescribed beta at a given spatial position.
void get_alpha (const Vector< double > &x, double &alpha)
Function to calculate the prescribed alpha at a given spatial position.
Private Member Functions
void fill_in_generic_residual_contribution_adv_diff_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt Beta_fct_pt
Function pointer to the (global) prescribed-beta function.
SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt Alpha_fct_pt
Function pointer to the (global) prescribed-alpha function.
unsigned U_index_adv_diff
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 634 of file steady_axisym_advection_diffusion_elements.h.
Member Typedef Documentation
SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt
template<class ELEMENT >
typedef void(* oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Definition at line 649 of file steady_axisym_advection_diffusion_elements.h.
SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt
template<class ELEMENT >
typedef void(* oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
Definition at line 644 of file steady_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
SteadyAxisymAdvectionDiffusionFluxElement() [1/3]
template<class ELEMENT >
oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Definition at line 856 of file steady_axisym_advection_diffusion_elements.h.
References oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt, oomph::FiniteElement::build_face_element(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), oomph::FiniteElement::has_hanging_nodes(), oomph::Global_string_for_annotation::string(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, and oomph::SteadyAxisymAdvectionDiffusionEquations::u_index_axisym_adv_diff().
SteadyAxisymAdvectionDiffusionFluxElement() [2/3]
template<class ELEMENT >
oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement () [inline]
Broken empty constructor.
Definition at line 660 of file steady_axisym_advection_diffusion_elements.h.
SteadyAxisymAdvectionDiffusionFluxElement() [3/3]
template<class ELEMENT >
oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement (const SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 669 of file steady_axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha_fct_pt()
template<class ELEMENT >
SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt& oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::alpha_fct_pt () [inline]
Access function for the prescribed-alpha function pointer.
Definition at line 687 of file steady_axisym_advection_diffusion_elements.h.
beta_fct_pt()
template<class ELEMENT >
SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt& oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::beta_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-beta function pointer
Definition at line 681 of file steady_axisym_advection_diffusion_elements.h.
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 706 of file steady_axisym_advection_diffusion_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 694 of file steady_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_residual_contribution_adv_diff_flux()
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix for the Robin boundary condition:
 \Delta u \cdot \mathbf{n} + \alpha (\mathbf{x}) = \beta (\mathbf{x}) 
.
Definition at line 940 of file steady_axisym_advection_diffusion_elements.h.
References oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::get_alpha(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::get_beta(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), s, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement().
get_alpha()
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::get_alpha (const Vector< double > & x, double & alpha) [inline], [protected]
Function to calculate the prescribed alpha at a given spatial position.
Definition at line 808 of file steady_axisym_advection_diffusion_elements.h.
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux().
get_beta()
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::get_beta (const Vector< double > & x, double & beta) [inline], [protected]
Function to calculate the prescribed beta at a given spatial position.
Definition at line 792 of file steady_axisym_advection_diffusion_elements.h.
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux().
output() [1/2]
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 728 of file steady_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 735 of file steady_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 746 of file steady_axisym_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 770 of file steady_axisym_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
zeta_nodal()
template<class ELEMENT >
double oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Specify the value of nodal zeta from the face geometry
Reimplemented from oomph::FaceElement.
Definition at line 721 of file steady_axisym_advection_diffusion_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Alpha_fct_pt
template<class ELEMENT >
SteadyAxisymAdvectionDiffusionPrescribedAlphaFctPt oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::Alpha_fct_pt [private]
Function pointer to the (global) prescribed-alpha function.
Definition at line 836 of file steady_axisym_advection_diffusion_elements.h.
Beta_fct_pt
template<class ELEMENT >
SteadyAxisymAdvectionDiffusionPrescribedBetaFctPt oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt [private]
Function pointer to the (global) prescribed-beta function.
Definition at line 833 of file steady_axisym_advection_diffusion_elements.h.
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement().
U_index_adv_diff
template<class ELEMENT >
unsigned oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff [private]
The index at which the unknown is stored at the nodes.
Definition at line 839 of file steady_axisym_advection_diffusion_elements.h.
Referenced by oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), and oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement().
The documentation for this class was generated from the following file:
steady_axisym_advection_diffusion_elements.h