oomph::MatrixBasedLumpedPreconditioner< MATRIX > Class Template Reference
Matrix-based lumped preconditioner.
#include <general_purpose_preconditioners.h>
Public Member Functions
MatrixBasedLumpedPreconditioner ()
Constructor.
~MatrixBasedLumpedPreconditioner ()
Destructor.
MatrixBasedLumpedPreconditioner (const MatrixBasedDiagPreconditioner &)
Broken copy constructor.
void operator= (const MatrixBasedLumpedPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to z, i.e. z=D^-1.
void setup ()
Setup the preconditioner (store diagonal) from the fully assembled matrix. Problem pointer is ignored.
bool positive_matrix () const
Access function to the Positive_matrix which indicates whether lumped matrix was positive.
double * inverse_lumped_vector_pt ()
Access function to the inverse of the lumped vector assembled in the preconditioner setup routine.
unsigned & nrow ()
Access function to number of rows for this preconditioner.
void clean_up_memory ()
clean up memory - just delete the inverse lumped vector
template<>
void setup ()
Setup the lumped preconditioner. Specialisation for CCDoubleMatrix.
template<>
void setup ()
Setup the lumped preconditioner. Specialisation for CRDoubleMatrix.
Private Attributes
double * Inv_lumped_diag_pt
Vector of inverse diagonal entries.
bool Positive_matrix
unsigned Nrow
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::MatrixBasedLumpedPreconditioner< MATRIX >
Matrix-based lumped preconditioner.
Definition at line 95 of file general_purpose_preconditioners.h.
Constructor & Destructor Documentation
MatrixBasedLumpedPreconditioner() [1/2]
template<typename MATRIX>
oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner () [inline]
Constructor.
Definition at line 100 of file general_purpose_preconditioners.h.
 MatrixBasedLumpedPreconditioner()
template<typename MATRIX>
oomph::MatrixBasedLumpedPreconditioner< MATRIX >::~MatrixBasedLumpedPreconditioner () [inline]
Destructor.
Definition at line 110 of file general_purpose_preconditioners.h.
MatrixBasedLumpedPreconditioner() [2/2]
template<typename MATRIX>
oomph::MatrixBasedLumpedPreconditioner< MATRIX >::MatrixBasedLumpedPreconditioner (const MatrixBasedDiagPreconditioner &) [inline]
Broken copy constructor.
Definition at line 116 of file general_purpose_preconditioners.h.
Member Function Documentation
clean_up_memory()
template<typename MATRIX>
void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::clean_up_memory () [inline], [virtual]
clean up memory - just delete the inverse lumped vector
Reimplemented from oomph::Preconditioner.
Definition at line 178 of file general_purpose_preconditioners.h.
inverse_lumped_vector_pt()
template<typename MATRIX>
double* oomph::MatrixBasedLumpedPreconditioner< MATRIX >::inverse_lumped_vector_pt () [inline]
Access function to the inverse of the lumped vector assembled in the preconditioner setup routine.
paranoid check that vector has been created
Definition at line 158 of file general_purpose_preconditioners.h.
nrow()
template<typename MATRIX>
unsigned& oomph::MatrixBasedLumpedPreconditioner< MATRIX >::nrow () [inline]
Access function to number of rows for this preconditioner.
Definition at line 175 of file general_purpose_preconditioners.h.
operator=()
template<typename MATRIX>
void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::operator= (const MatrixBasedLumpedPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 122 of file general_purpose_preconditioners.h.
positive_matrix()
template<typename MATRIX>
bool oomph::MatrixBasedLumpedPreconditioner< MATRIX >::positive_matrix () const [inline]
Access function to the Positive_matrix which indicates whether lumped matrix was positive.
paranoid check that preconditioner has been setup
Definition at line 140 of file general_purpose_preconditioners.h.
preconditioner_solve()
template<typename MATRIX >
void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to z, i.e. z=D^-1.
Apply preconditioner: Multiply r by the inverse of the lumped matrix.
Implements oomph::Preconditioner.
Definition at line 279 of file general_purpose_preconditioners.cc.
setup() [1/3]
template<typename MATRIX>
void oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup () [virtual]
Setup the preconditioner (store diagonal) from the fully assembled matrix. Problem pointer is ignored.
Implements oomph::Preconditioner.
Referenced by oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::setup(), and oomph::InexactSubBiharmonicPreconditioner::setup().
setup() [2/3]
template<>
void oomph::MatrixBasedLumpedPreconditioner< CCDoubleMatrix >::setup () [virtual]
Setup the lumped preconditioner. Specialisation for CCDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 176 of file general_purpose_preconditioners.cc.
setup() [3/3]
template<>
void oomph::MatrixBasedLumpedPreconditioner< CRDoubleMatrix >::setup () [virtual]
Setup the lumped preconditioner. Specialisation for CRDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 228 of file general_purpose_preconditioners.cc.
Member Data Documentation
Inv_lumped_diag_pt
template<typename MATRIX>
double* oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Inv_lumped_diag_pt [private]
Vector of inverse diagonal entries.
Definition at line 187 of file general_purpose_preconditioners.h.
Nrow
template<typename MATRIX>
unsigned oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Nrow [private]
Definition at line 193 of file general_purpose_preconditioners.h.
Positive_matrix
template<typename MATRIX>
bool oomph::MatrixBasedLumpedPreconditioner< MATRIX >::Positive_matrix [private]
Definition at line 190 of file general_purpose_preconditioners.h.
The documentation for this class was generated from the following files:
general_purpose_preconditioners.h
general_purpose_preconditioners.cc