oomph::GMRES< MATRIX > Class Template Reference
The GMRES method.
#include <iterative_linear_solver.h>
Public Member Functions
GMRES ()
Constructor.
virtual ~GMRES ()
Destructor (cleanup storage)
GMRES (const GMRES &)
Broken copy constructor.
void operator= (const GMRES &)
Broken assignment operator.
void disable_resolve ()
Overload disable resolve so that it cleans up memory too.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
void resolve (const DoubleVector &rhs, DoubleVector &result)
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
unsigned iterations () const
Number of iterations taken.
bool iteration_restart () const
access function indicating whether restarted GMRES is used
void enable_iteration_restart (const unsigned &restart)
switches on iteration restarting and takes as an argument the number of iterations after which the construction of the orthogonalisation basis vectors should be restarted
void disable_iteration_restart ()
switches off iteration restart
void set_preconditioner_LHS ()
Set left preconditioning (the default)
void set_preconditioner_RHS ()
Enable right preconditioning.
Private Member Functions
void solve_helper (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
General interface to solve function.
void clean_up_memory ()
Cleanup data that's stored for resolve (if any has been stored)
void update (const unsigned &k, const Vector< Vector< double > > &H, const Vector< double > &s, const Vector< DoubleVector > &v, DoubleVector &x)
Helper function to update the result vector using the result, x=x_0+V_m*y.
void generate_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and () (i.e. sn) such that:
 \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix} = \begin{bmatrix} r \newline 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(dx,2)+pow(dy,2)} $. The values of a and b are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{pow(dx,2)+pow(dy,2)}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{pow(dx,2)+pow(dy,2)}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.192.
void apply_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \newline dy \end{bmatrix} \leftarrow \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix}. 
.
Private Attributes
unsigned Iterations
Number of iterations taken.
unsigned Restart
The number of iterations before the iteration proceedure is restarted if iteration restart is used.
bool Iteration_restart
boolean indicating if iteration restarting is used
MATRIX * Matrix_pt
Pointer to matrix.
bool Resolving
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
bool Matrix_can_be_deleted
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
bool Preconditioner_LHS
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::GMRES< MATRIX >
The GMRES method.
Definition at line 1246 of file iterative_linear_solver.h.
Constructor & Destructor Documentation
GMRES() [1/2]
template<typename MATRIX >
oomph::GMRES< MATRIX >::GMRES () [inline]
Constructor.
Definition at line 1252 of file iterative_linear_solver.h.
 GMRES()
template<typename MATRIX >
virtual oomph::GMRES< MATRIX >::~GMRES () [inline], [virtual]
Destructor (cleanup storage)
Definition at line 1262 of file iterative_linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
GMRES() [2/2]
template<typename MATRIX >
oomph::GMRES< MATRIX >::GMRES (const GMRES< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 1268 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
apply_plane_rotation()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::apply_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \newline dy \end{bmatrix} \leftarrow \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix}. 
.
Definition at line 1533 of file iterative_linear_solver.h.
clean_up_memory()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::clean_up_memory () [inline], [private], [virtual]
Cleanup data that's stored for resolve (if any has been stored)
Reimplemented from oomph::LinearSolver.
Definition at line 1371 of file iterative_linear_solver.h.
disable_iteration_restart()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::disable_iteration_restart () [inline]
switches off iteration restart
Definition at line 1352 of file iterative_linear_solver.h.
disable_resolve()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::disable_resolve () [inline], [virtual]
Overload disable resolve so that it cleans up memory too.
Reimplemented from oomph::LinearSolver.
Definition at line 1280 of file iterative_linear_solver.h.
References oomph::LinearSolver::clean_up_memory(), oomph::LinearSolver::disable_resolve(), and oomph::LinearSolver::solve().
enable_iteration_restart()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::enable_iteration_restart (const unsigned & restart) [inline]
switches on iteration restarting and takes as an argument the number of iterations after which the construction of the orthogonalisation basis vectors should be restarted
Definition at line 1345 of file iterative_linear_solver.h.
generate_plane_rotation()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::generate_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and () (i.e. sn) such that:
 \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix} = \begin{bmatrix} r \newline 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(dx,2)+pow(dy,2)} $. The values of a and b are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{pow(dx,2)+pow(dy,2)}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{pow(dx,2)+pow(dy,2)}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.192.
Definition at line 1475 of file iterative_linear_solver.h.
iteration_restart()
template<typename MATRIX >
bool oomph::GMRES< MATRIX >::iteration_restart () const [inline]
access function indicating whether restarted GMRES is used
Definition at line 1337 of file iterative_linear_solver.h.
iterations()
template<typename MATRIX >
unsigned oomph::GMRES< MATRIX >::iterations () const [inline], [virtual]
Number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 1331 of file iterative_linear_solver.h.
operator=()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::operator= (const GMRES< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 1274 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_assign().
resolve()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::resolve (const DoubleVector & rhs, DoubleVector & result) [virtual]
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
Reimplemented from oomph::LinearSolver.
Definition at line 2162 of file iterative_linear_solver.cc.
References oomph::LinearSolver::solve().
set_preconditioner_LHS()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::set_preconditioner_LHS () [inline]
Set left preconditioning (the default)
Definition at line 1358 of file iterative_linear_solver.h.
set_preconditioner_RHS()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::set_preconditioner_RHS () [inline]
Enable right preconditioning.
Definition at line 1361 of file iterative_linear_solver.h.
solve() [1/3]
template<typename MATRIX >
void oomph::GMRES< MATRIX >::solve (Problem *const & problem_pt, DoubleVector & result) [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Definition at line 2191 of file iterative_linear_solver.cc.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DoubleVector::built(), oomph::LinearSolver::clean_up_memory(), oomph::Problem::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::Problem::get_jacobian(), oomph::IterativeLinearSolver::Jacobian_setup_time, oomph::Problem::ndof(), oomph::oomph_info, oomph::DoubleVector::redistribute(), and oomph::TimingHelpers::timer().
solve() [2/3]
template<typename MATRIX >
void oomph::GMRES< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented from oomph::LinearSolver.
Definition at line 1293 of file iterative_linear_solver.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), and oomph::LinearSolver::Enable_resolve.
solve() [3/3]
template<typename MATRIX >
void oomph::GMRES< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
Reimplemented from oomph::LinearSolver.
Definition at line 1319 of file iterative_linear_solver.h.
References oomph::LinearSolver::resolve(), and oomph::LinearSolver::solve().
solve_helper()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::solve_helper (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [private]
General interface to solve function.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. based on the algorithm presented in Templates for the Solution of Linear Systems: Building Blocks for Iterative Methods, Barrett, Berry et al, SIAM, 2006 and the implementation in the IML++ library : http://math.nist.gov/iml++/
Definition at line 2272 of file iterative_linear_solver.cc.
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, i, oomph::DoubleVector::initialise(), oomph::IterativeLinearSolver::Max_iter, oomph::DoubleMatrixBase::multiply(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, oomph::IterativeLinearSolver::preconditioner_pt(), oomph::IterativeLinearSolver::Preconditioner_setup_time, oomph::Preconditioner::preconditioner_solve(), s, oomph::Preconditioner::setup(), oomph::IterativeLinearSolver::Setup_preconditioner_before_solve, oomph::IterativeLinearSolver::Solution_time, oomph::Global_string_for_annotation::string(), oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), oomph::IterativeLinearSolver::Tolerance, and oomph::DoubleVector::values_pt().
update()
template<typename MATRIX >
void oomph::GMRES< MATRIX >::update (const unsigned & k, const Vector< Vector< double > > & H, const Vector< double > & s, const Vector< DoubleVector > & v, DoubleVector & x) [inline], [private]
Helper function to update the result vector using the result, x=x_0+V_m*y.
Definition at line 1381 of file iterative_linear_solver.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), i, oomph::DistributableLinearAlgebraObject::nrow(), oomph::IterativeLinearSolver::preconditioner_pt(), oomph::Preconditioner::preconditioner_solve(), and oomph::DoubleVector::values_pt().
Member Data Documentation
Iteration_restart
template<typename MATRIX >
bool oomph::GMRES< MATRIX >::Iteration_restart [private]
boolean indicating if iteration restarting is used
Definition at line 1553 of file iterative_linear_solver.h.
Iterations
template<typename MATRIX >
unsigned oomph::GMRES< MATRIX >::Iterations [private]
Number of iterations taken.
Definition at line 1546 of file iterative_linear_solver.h.
Matrix_can_be_deleted
template<typename MATRIX >
bool oomph::GMRES< MATRIX >::Matrix_can_be_deleted [private]
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
Definition at line 1564 of file iterative_linear_solver.h.
Matrix_pt
template<typename MATRIX >
MATRIX* oomph::GMRES< MATRIX >::Matrix_pt [private]
Pointer to matrix.
Definition at line 1556 of file iterative_linear_solver.h.
Preconditioner_LHS
template<typename MATRIX >
bool oomph::GMRES< MATRIX >::Preconditioner_LHS [private]
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Definition at line 1568 of file iterative_linear_solver.h.
Resolving
template<typename MATRIX >
bool oomph::GMRES< MATRIX >::Resolving [private]
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
Definition at line 1560 of file iterative_linear_solver.h.
Restart
template<typename MATRIX >
unsigned oomph::GMRES< MATRIX >::Restart [private]
The number of iterations before the iteration proceedure is restarted if iteration restart is used.
Definition at line 1550 of file iterative_linear_solver.h.
The documentation for this class was generated from the following files:
iterative_linear_solver.h
iterative_linear_solver.cc