oomph::TPoissonElement< DIM, NNODE_1D > Class Template Reference
#include <Tpoisson_elements.h>
Public Member Functions
TPoissonElement ()
Constructor: Call constructors for TElement and Poisson equations.
TPoissonElement (const TPoissonElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const TPoissonElement< DIM, NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TPoissonElement< DIM, NNODE_1D >
TPoissonElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional Poisson elements with NNODE_1D nodal points along each element edge. Inherits from TElement and PoissonEquations
Definition at line 65 of file Tpoisson_elements.h.
Constructor & Destructor Documentation
TPoissonElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TPoissonElement< DIM, NNODE_1D >::TPoissonElement () [inline]
Constructor: Call constructors for TElement and Poisson equations.
Definition at line 74 of file Tpoisson_elements.h.
TPoissonElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TPoissonElement< DIM, NNODE_1D >::TPoissonElement (const TPoissonElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 79 of file Tpoisson_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_poisson() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 250 of file Tpoisson_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson(), and oomph::TPoissonElement< DIM, NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_at_knot_poisson() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 282 of file Tpoisson_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
dshape_and_dtest_eulerian_poisson()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PoissonEquations< DIM >.
Definition at line 215 of file Tpoisson_elements.h.
References oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::TPoissonElement< DIM, NNODE_1D >::output_fct().
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 183 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::get_flux().
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPoissonElement< DIM, NNODE_1D >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 177 of file Tpoisson_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPoissonElement< DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 180 of file Tpoisson_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPoissonElement< DIM, NNODE_1D >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 187 of file Tpoisson_elements.h.
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::operator= (const TPoissonElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 85 of file Tpoisson_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 97 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 104 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 112 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 120 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact.
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 128 of file Tpoisson_elements.h.
References oomph::PoissonEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Reimplemented from oomph::PoissonEquations< DIM >.
Definition at line 137 of file Tpoisson_elements.h.
References oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson(), oomph::TPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson(), oomph::PoissonEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPoissonElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
Reimplemented from oomph::FiniteElement.
Definition at line 92 of file Tpoisson_elements.h.
References oomph::TPoissonElement< DIM, NNODE_1D >::Initial_Nvalue.
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node* oomph::TPoissonElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 191 of file Tpoisson_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::TPoissonElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
Definition at line 197 of file Tpoisson_elements.h.
Referenced by oomph::TPoissonElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
Tpoisson_elements.h
Tpoisson_elements.cc