oomph::Euler Class Reference
#include <explicit_timesteppers.h>
Public Member Functions
Euler ()
Constructor, set the type.
Euler (const Euler &)
Broken copy constructor.
void operator= (const Euler &)
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Overload function that is used to advance time in the object reference by object_pt by an amount dt.
Additional Inherited Members
Detailed Description
=========================================================== Simple first-order Euler Timestepping
Definition at line 181 of file explicit_timesteppers.h.
Constructor & Destructor Documentation
Euler() [1/2]
oomph::Euler::Euler () [inline]
Constructor, set the type.
Definition at line 186 of file explicit_timesteppers.h.
Euler() [2/2]
oomph::Euler::Euler (const Euler &) [inline]
Broken copy constructor.
Definition at line 189 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
void oomph::Euler::operator= (const Euler &) [inline]
Broken assignment operator.
Definition at line 195 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
timestep()
void oomph::Euler::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Overload function that is used to advance time in the object reference by object_pt by an amount dt.
Euler timestepping x^{t+1} = x^{t} + dt M^{-1} L(x^{t})
Implements oomph::ExplicitTimeStepper.
Definition at line 180 of file explicit_timesteppers.cc.
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), and oomph::ExplicitTimeSteppableObject::time().
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc