oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM > Class Template Reference
Class for Refineable TimeHarmonicLinearElasticity equations.
#include <refineable_time_harmonic_linear_elasticity_elements.h>
Public Member Functions
RefineableTimeHarmonicLinearElasticityEquations ()
Constructor.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the current interpolated values (displacements). Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines) ,the values Vector sets its own size in here.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 2*DIM.
void further_build ()
Further build function, pass the pointers down to the sons.
Private Member Functions
void fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Overloaded helper function to take hanging nodes into account.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >
Class for Refineable TimeHarmonicLinearElasticity equations.
Definition at line 49 of file refineable_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
RefineableTimeHarmonicLinearElasticityEquations()
template<unsigned DIM>
oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::RefineableTimeHarmonicLinearElasticityEquations () [inline]
Constructor.
Definition at line 57 of file refineable_time_harmonic_linear_elasticity_elements.h.
Member Function Documentation
fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity()
template<unsigned DIM>
void oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Overloaded helper function to take hanging nodes into account.
Residuals for Refineable QTimeHarmonicLinearElasticityElements.
Reimplemented from oomph::TimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 44 of file refineable_time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
further_build()
template<unsigned DIM>
void oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build () [inline], [virtual]
Further build function, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Definition at line 164 of file refineable_time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt, oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, oomph::RefineableElement::father_element_pt(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt.
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 68 of file refineable_time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity().
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the current interpolated values (displacements). Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines) ,the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 99 of file refineable_time_harmonic_linear_elasticity_elements.h.
References oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 114 of file refineable_time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain(), and i.
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 2*DIM.
Implements oomph::RefineableElement.
Definition at line 161 of file refineable_time_harmonic_linear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 106 of file refineable_time_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
refineable_time_harmonic_linear_elasticity_elements.h
refineable_time_harmonic_linear_elasticity_elements.cc