oomph::ErrorEstimator Class Reference
Base class for spatial error estimators.
#include <error_estimator.h>
Public Member Functions
ErrorEstimator ()
Default empty constructor.
ErrorEstimator (const ErrorEstimator &)
Broken copy constructor.
void operator= (const ErrorEstimator &)
Broken assignment operator.
virtual ~ErrorEstimator ()
Empty virtual destructor.
void get_element_errors (Mesh *&mesh_pt, Vector< double > &elemental_error)
Compute the elemental error-measures for a given mesh and store them in a vector.
virtual void get_element_errors (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)=0
Compute the elemental error measures for a given mesh and store them in a vector. Doc errors etc.
Detailed Description
Base class for spatial error estimators.
Definition at line 43 of file error_estimator.h.
Constructor & Destructor Documentation
ErrorEstimator() [1/2]
oomph::ErrorEstimator::ErrorEstimator () [inline]
Default empty constructor.
Definition at line 49 of file error_estimator.h.
ErrorEstimator() [2/2]
oomph::ErrorEstimator::ErrorEstimator (const ErrorEstimator &) [inline]
Broken copy constructor.
Definition at line 52 of file error_estimator.h.
References oomph::BrokenCopy::broken_copy().
 ErrorEstimator()
virtual oomph::ErrorEstimator::~ErrorEstimator () [inline], [virtual]
Empty virtual destructor.
Definition at line 64 of file error_estimator.h.
Member Function Documentation
get_element_errors() [1/2]
void oomph::ErrorEstimator::get_element_errors (Mesh *& mesh_pt, Vector< double > & elemental_error) [inline]
Compute the elemental error-measures for a given mesh and store them in a vector.
Definition at line 68 of file error_estimator.h.
References oomph::DocInfo::disable_doc().
Referenced by oomph::Problem::adapt(), oomph::Problem::doc_errors(), oomph::Problem::get_all_error_estimates(), oomph::Z2ErrorEstimator::get_element_errors(), and oomph::Problem::p_adapt().
get_element_errors() [2/2]
virtual void oomph::ErrorEstimator::get_element_errors (Mesh *& mesh_pt, Vector< double > & elemental_error, DocInfo & doc_info) [pure virtual]
Compute the elemental error measures for a given mesh and store them in a vector. Doc errors etc.
Implemented in oomph::DummyErrorEstimator, and oomph::Z2ErrorEstimator.
operator=()
void oomph::ErrorEstimator::operator= (const ErrorEstimator &) [inline]
Broken assignment operator.
Definition at line 58 of file error_estimator.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
error_estimator.h