oomph::GeneralisedAdvectionDiffusionEquations< DIM > Class Template Reference
A class for all elements that solve the Advection Diffusion equations in conservative form using isoparametric elements.
 \frac{\partial}{\partial x_{i}}\left( Pe w_{i}(x_{k}) u - D_{ij}(x_{k})\frac{\partial u}{\partial x_{j}}\right) = f(x_{j}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
#include <gen_advection_diffusion_elements.h>
Public Types
typedef void(* GeneralisedAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
typedef void(* GeneralisedAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
typedef void(* GeneralisedAdvectionDiffusionDiffFctPt) (const Vector< double > &x, DenseMatrix< double > &D)
Funciton pointer to a diffusivity function.
Public Member Functions
GeneralisedAdvectionDiffusionEquations ()
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
GeneralisedAdvectionDiffusionEquations (const GeneralisedAdvectionDiffusionEquations &dummy)
Broken copy constructor.
void operator= (const GeneralisedAdvectionDiffusionEquations &)
Broken assignment operator.
virtual unsigned u_index_cons_adv_diff () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double du_dt_cons_adv_diff (const unsigned &n) const
du/dt at local node n.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at nplot^DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
double integrate_u ()
Integrate the concentration over the element.
GeneralisedAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
GeneralisedAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
GeneralisedAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
GeneralisedAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
GeneralisedAdvectionDiffusionWindFctPt & conserved_wind_fct_pt ()
Access function: Pointer to additional (conservative) wind function.
GeneralisedAdvectionDiffusionWindFctPt conserved_wind_fct_pt () const
Access function: Pointer to additoinal (conservative) wind function. Const version.
GeneralisedAdvectionDiffusionDiffFctPt & diff_fct_pt ()
Access function: Pointer to diffusion function.
GeneralisedAdvectionDiffusionDiffFctPt diff_fct_pt () const
Access function: Pointer to diffusion function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_cons_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_wind_cons_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
virtual void get_conserved_wind_cons_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get additional (conservative) wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
virtual void get_diff_cons_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &D) const
Get diffusivity tensor at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
void get_total_flux (const Vector< double > &s, Vector< double > &total_flux) const
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_cons_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_cons_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_cons_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_cons_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
GeneralisedAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
GeneralisedAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
GeneralisedAdvectionDiffusionWindFctPt Conserved_wind_fct_pt
Pointer to additional (conservative) wind function:
GeneralisedAdvectionDiffusionDiffFctPt Diff_fct_pt
Pointer to diffusivity funciton.
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to false if you're sure that the mesh is stationary.
Static Private Attributes
static double Default_peclet_number =0.0
Static default value for the Peclet number.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::GeneralisedAdvectionDiffusionEquations< DIM >
A class for all elements that solve the Advection Diffusion equations in conservative form using isoparametric elements.
 \frac{\partial}{\partial x_{i}}\left( Pe w_{i}(x_{k}) u - D_{ij}(x_{k})\frac{\partial u}{\partial x_{j}}\right) = f(x_{j}) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 60 of file gen_advection_diffusion_elements.h.
Member Typedef Documentation
GeneralisedAdvectionDiffusionDiffFctPt
template<unsigned DIM>
typedef void(* oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionDiffFctPt) (const Vector< double > &x, DenseMatrix< double > &D)
Funciton pointer to a diffusivity function.
Definition at line 78 of file gen_advection_diffusion_elements.h.
GeneralisedAdvectionDiffusionSourceFctPt
template<unsigned DIM>
typedef void(* oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 68 of file gen_advection_diffusion_elements.h.
GeneralisedAdvectionDiffusionWindFctPt
template<unsigned DIM>
typedef void(* oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) -- x is a Vector!
Definition at line 73 of file gen_advection_diffusion_elements.h.
Constructor & Destructor Documentation
GeneralisedAdvectionDiffusionEquations() [1/2]
template<unsigned DIM>
oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations () [inline]
Constructor: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default.
Definition at line 82 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Default_peclet_number, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Pe_pt, and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::PeSt_pt.
GeneralisedAdvectionDiffusionEquations() [2/2]
template<unsigned DIM>
oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations (const GeneralisedAdvectionDiffusionEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 92 of file gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 463 of file gen_advection_diffusion_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct().
compute_error() [2/2]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 207 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::integrate_u().
conserved_wind_fct_pt() [1/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::conserved_wind_fct_pt () [inline]
Access function: Pointer to additional (conservative) wind function.
Definition at line 242 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Conserved_wind_fct_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
conserved_wind_fct_pt() [2/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::conserved_wind_fct_pt () const [inline]
Access function: Pointer to additoinal (conservative) wind function. Const version.
Definition at line 249 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Conserved_wind_fct_pt.
diff_fct_pt() [1/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionDiffFctPt& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::diff_fct_pt () [inline]
Access function: Pointer to diffusion function.
Definition at line 253 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Diff_fct_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
diff_fct_pt() [2/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionDiffFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::diff_fct_pt () const [inline]
Access function: Pointer to diffusion function. Const version.
Definition at line 257 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Diff_fct_pt.
disable_ALE()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 141 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_cons_adv_diff()
template<unsigned DIM>
virtual double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_at_knot_cons_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), and oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_cons_adv_diff()
template<unsigned DIM>
virtual double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_cons_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), and oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct().
du_dt_cons_adv_diff()
template<unsigned DIM>
double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff (const unsigned & n) const [inline]
du/dt at local node n.
Uses suitably interpolated value for hanging nodes.
Definition at line 115 of file gen_advection_diffusion_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff(), and oomph::TimeStepper::weight().
enable_ALE()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 151 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::ALE_is_disabled.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 473 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
Definition at line 484 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 461 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff().
fill_in_generic_residual_contribution_cons_adv_diff()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 53 of file gen_advection_diffusion_elements.cc.
References oomph::ALE_is_disabled, oomph::OcTreeNames::D, i, oomph::pe(), oomph::pe_st(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff().
get_conserved_wind_cons_adv_diff()
template<unsigned DIM>
virtual void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_conserved_wind_cons_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get additional (conservative) wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 318 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Conserved_wind_fct_pt, and i.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux().
get_diff_cons_adv_diff()
template<unsigned DIM>
virtual void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_diff_cons_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & D) const [inline], [virtual]
Get diffusivity tensor at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 343 of file gen_advection_diffusion_elements.h.
References oomph::OcTreeNames::D, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Diff_fct_pt, and i.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux().
get_flux()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
Definition at line 368 of file gen_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff().
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_Z2_flux().
get_source_cons_adv_diff()
template<unsigned DIM>
virtual void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_source_cons_adv_diff (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 276 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Source_fct_pt.
get_total_flux()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux (const Vector< double > & s, Vector< double > & total_flux) const [inline]
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
Definition at line 398 of file gen_advection_diffusion_elements.h.
References oomph::OcTreeNames::D, oomph::FiniteElement::dshape_eulerian(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_conserved_wind_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_diff_cons_adv_diff(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff().
get_wind_cons_adv_diff()
template<unsigned DIM>
virtual void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_wind_cons_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 294 of file gen_advection_diffusion_elements.h.
References i, and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Wind_fct_pt.
integrate_u()
template<unsigned DIM>
double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::integrate_u ()
Integrate the concentration over the element.
Calculate the integrated value of the unknown over the element.
Definition at line 540 of file gen_advection_diffusion_elements.cc.
References s.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::compute_error().
interpolated_u_cons_adv_diff()
template<unsigned DIM>
double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 495 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_at_knot_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::self_test(), oomph::FiniteElement::shape(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff().
operator=()
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::operator= (const GeneralisedAdvectionDiffusionEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 99 of file gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 158 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output(), and oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output().
output() [2/4]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at nplot^DIM plot points.
Output function:
x,y,u,w_x,w_y or x,y,z,u,w_x,w_y,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 292 of file gen_advection_diffusion_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 170 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct().
output() [4/4]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 367 of file gen_advection_diffusion_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 408 of file gen_advection_diffusion_elements.cc.
References i, and s.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output(), and oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct().
output_fct() [2/2]
template<unsigned DIM>
virtual void oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >.
Definition at line 189 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::compute_error().
pe()
template<unsigned DIM>
const double& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe () const [inline]
Peclet number.
Definition at line 261 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Pe_pt.
pe_pt()
template<unsigned DIM>
double* & oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_pt () [inline]
Pointer to Peclet number.
Definition at line 264 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Pe_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
pe_st()
template<unsigned DIM>
const double& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_st () const [inline]
Peclet number multiplied by Strouhal number.
Definition at line 267 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::PeSt_pt.
pe_st_pt()
template<unsigned DIM>
double* & oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_st_pt () [inline]
Pointer to Peclet number multipled by Strouha number.
Definition at line 270 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::PeSt_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
self_test()
template<unsigned DIM>
unsigned oomph::GeneralisedAdvectionDiffusionEquations< DIM >::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 259 of file gen_advection_diffusion_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff().
source_fct_pt() [1/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionSourceFctPt& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 223 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionSourceFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 228 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Source_fct_pt.
u_index_cons_adv_diff()
template<unsigned DIM>
virtual unsigned oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 111 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff().
wind_fct_pt() [1/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt& oomph::GeneralisedAdvectionDiffusionEquations< DIM >::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 233 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Wind_fct_pt.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
wind_fct_pt() [2/2]
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 237 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Wind_fct_pt.
Member Data Documentation
ALE_is_disabled
template<unsigned DIM>
bool oomph::GeneralisedAdvectionDiffusionEquations< DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to false if you're sure that the mesh is stationary.
Definition at line 573 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::disable_ALE(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::enable_ALE(), and oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
Conserved_wind_fct_pt
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Conserved_wind_fct_pt [protected]
Pointer to additional (conservative) wind function:
Definition at line 565 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::conserved_wind_fct_pt(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_conserved_wind_cons_adv_diff().
Default_peclet_number
template<unsigned DIM>
double oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Default_peclet_number =0.0 [static], [private]
Static default value for the Peclet number.
2D GeneralisedAdvection Diffusion elements
Default value for Peclet number
Definition at line 578 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations().
Diff_fct_pt
template<unsigned DIM>
GeneralisedAdvectionDiffusionDiffFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Diff_fct_pt [protected]
Pointer to diffusivity funciton.
Definition at line 568 of file gen_advection_diffusion_elements.h.
Referenced by oomph::GeneralisedAdvectionDiffusionEquations< DIM >::diff_fct_pt(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_diff_cons_adv_diff().
Pe_pt
template<unsigned DIM>
double* oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Pe_pt [protected]
Pointer to global Peclet number.
Definition at line 553 of file gen_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_pt().
PeSt_pt
template<unsigned DIM>
double* oomph::GeneralisedAdvectionDiffusionEquations< DIM >::PeSt_pt [protected]
Pointer to global Peclet number multiplied by Strouhal number.
Definition at line 556 of file gen_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_st(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_st_pt().
Source_fct_pt
template<unsigned DIM>
GeneralisedAdvectionDiffusionSourceFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 559 of file gen_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_source_cons_adv_diff(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::source_fct_pt().
Wind_fct_pt
template<unsigned DIM>
GeneralisedAdvectionDiffusionWindFctPt oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Wind_fct_pt [protected]
Pointer to wind function:
Definition at line 562 of file gen_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_wind_cons_adv_diff(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::wind_fct_pt().
The documentation for this class was generated from the following files:
gen_advection_diffusion_elements.h
gen_advection_diffusion_elements.cc