oomph::UniaxialPMLMapping Class Reference
#include <pml_mapping_functions.h>
Public Member Functions
UniaxialPMLMapping ()
Default constructor (empty)
virtual std::complex< double > dtransformed_nu_dnu (const double &nu, const double &delta, const double &wavenumber_squared, const double &alpha_shift=0.0)=0
Pure virtual to return Pml mapping gamma, where gamma is the $d\tilde x / d x$ as function of $\nu$ where $\nu = x - h$ where h is the vector from the origin to the start of the Pml.
virtual std::complex< double > transformed_nu (const double &nu, const double &delta, const double &wavenumber_squared, const double &alpha_shift=0.0)=0
Detailed Description
Class to hold the mapping function (gamma) for the Pml which defines how the coordinates are transformed in the Pml. This class holds the one dimensional or uniaxial case which is the most common
Definition at line 49 of file pml_mapping_functions.h.
Constructor & Destructor Documentation
UniaxialPMLMapping()
oomph::UniaxialPMLMapping::UniaxialPMLMapping () [inline]
Default constructor (empty)
Definition at line 55 of file pml_mapping_functions.h.
References dtransformed_nu_dnu(), and transformed_nu().
Member Function Documentation
dtransformed_nu_dnu()
virtual std::complex<double> oomph::UniaxialPMLMapping::dtransformed_nu_dnu (const double & nu, const double & delta, const double & wavenumber_squared, const double & alpha_shift = 0.0) [pure virtual]
Pure virtual to return Pml mapping gamma, where gamma is the $d\tilde x / d x$ as function of $\nu$ where $\nu = x - h$ where h is the vector from the origin to the start of the Pml.
Implemented in oomph::ScaleFreeBermudezPMLMapping, oomph::C1BermudezPMLMapping, and oomph::BermudezPMLMapping.
Referenced by UniaxialPMLMapping().
transformed_nu()
virtual std::complex<double> oomph::UniaxialPMLMapping::transformed_nu (const double & nu, const double & delta, const double & wavenumber_squared, const double & alpha_shift = 0.0) [pure virtual]
Implemented in oomph::ScaleFreeBermudezPMLMapping, oomph::C1BermudezPMLMapping, and oomph::BermudezPMLMapping.
Referenced by UniaxialPMLMapping().
The documentation for this class was generated from the following file:
pml_mapping_functions.h