oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT > Class Template Reference
#include <pml_time_harmonic_linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates FCT(x,b) -- x and b are Vectors!
Public Member Functions
PMLTimeHarmonicLinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
void operator= (const PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT > &)
Broken assignment operator.
virtual std::complex< unsigned > u_index_time_harmonic_linear_elasticity (const unsigned i) const
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
void interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, Vector< std::complex< double > > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
std::complex< double > interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] at local coordinate s.
PMLTimeHarmonicIsotropicElasticityTensor *& elasticity_tensor_pt ()
Return the pointer to the elasticity_tensor.
std::complex< double > E (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Access function to the entries in the elasticity tensor.
double nu () const
Access function to nu in the elasticity tensor.
const double & omega_sq () const
Access function for square of non-dim frequency.
double *& omega_sq_pt ()
Access function for square of non-dim frequency.
double wavenumber () const
Wavenumber for the PML.
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
virtual void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double > > &sigma) const =0
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
void get_strain (const Vector< double > &s, DenseMatrix< std::complex< double > > &strain) const
Return the strain tensor.
void body_force (const Vector< double > &x, Vector< std::complex< double > > &b) const
Evaluate body force at Eulerian coordinate x (returns zero vector if no body force function pointer has been set)
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Static Public Attributes
static C1BermudezPMLMapping Default_pml_mapping
Protected Attributes
PMLTimeHarmonicIsotropicElasticityTensor * Elasticity_tensor_pt
Pointer to the elasticity tensor.
double * Omega_sq_pt
Square of nondim frequency.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Static Protected Attributes
static double Default_omega_sq_value
Static default value for square of frequency.
Additional Inherited Members
Detailed Description
template<unsigned DIM, class PML_ELEMENT>
class oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >
A base class for elements that solve the equations of time-harmonic linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by PMLTimeHarmonicLinearElasticityEquations and PMLTimeHarmonicLinearElasticityEquationsWithPressure (Note: The latter don't exist yet but will be written as soon as somebody needs them...)
Definition at line 83 of file pml_time_harmonic_linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM, class PML_ELEMENT >
typedef void(* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates FCT(x,b) -- x and b are Vectors!
Definition at line 188 of file pml_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
PMLTimeHarmonicLinearElasticityEquationsBase()
template<unsigned DIM, class PML_ELEMENT >
oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::PMLTimeHarmonicLinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
Definition at line 91 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Default_pml_mapping.
Member Function Documentation
body_force()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force (const Vector< double > & x, Vector< std::complex< double > > & b) const [inline]
Evaluate body force at Eulerian coordinate x (returns zero vector if no body force function pointer has been set)
Definition at line 239 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Body_force_fct_pt, oomph::FiniteElement::dim(), and i.
body_force_fct_pt() [1/2]
template<unsigned DIM, class PML_ELEMENT >
BodyForceFctPt& oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 221 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Body_force_fct_pt.
body_force_fct_pt() [2/2]
template<unsigned DIM, class PML_ELEMENT >
BodyForceFctPt oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 224 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Body_force_fct_pt, oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_strain(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_stress(), and s.
E()
template<unsigned DIM, class PML_ELEMENT >
std::complex<double> oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::E (const unsigned & i, const unsigned & j, const unsigned & k, const unsigned & l) const [inline]
Access function to the entries in the elasticity tensor.
Definition at line 196 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Elasticity_tensor_pt, and i.
elasticity_tensor_pt()
template<unsigned DIM, class PML_ELEMENT >
PMLTimeHarmonicIsotropicElasticityTensor* & oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::elasticity_tensor_pt () [inline]
Return the pointer to the elasticity_tensor.
Definition at line 192 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Elasticity_tensor_pt.
get_dof_numbers_for_unknowns()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 287 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
get_strain()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_strain (const Vector< double > & s, DenseMatrix< std::complex< double > > & strain) const
Return the strain tensor.
Compute the strain tensor at local coordinate s. Now fill in the entries of the strain tensor
Definition at line 53 of file pml_time_harmonic_linear_elasticity_elements.cc.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::get_stress(), and i.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force_fct_pt(), and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D, PML_ELEMENT >::get_Z2_flux().
get_stress()
template<unsigned DIM, class PML_ELEMENT >
virtual void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double > > & sigma) const [pure virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
Implemented in oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force_fct_pt(), and oomph::PMLTimeHarmonicLinearElasticityEquations< DIM, PML_ELEMENT >::fill_in_contribution_to_jacobian().
interpolated_u_time_harmonic_linear_elasticity() [1/2]
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, Vector< std::complex< double > > & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 115 of file pml_time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::u_index_time_harmonic_linear_elasticity().
interpolated_u_time_harmonic_linear_elasticity() [2/2]
template<unsigned DIM, class PML_ELEMENT >
std::complex<double> oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] at local coordinate s.
Definition at line 151 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::u_index_time_harmonic_linear_elasticity().
ndof_types()
template<unsigned DIM, class PML_ELEMENT >
unsigned oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 276 of file pml_time_harmonic_linear_elasticity_elements.h.
nu()
template<unsigned DIM, class PML_ELEMENT >
double oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::nu () const [inline]
Access function to nu in the elasticity tensor.
Definition at line 203 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Elasticity_tensor_pt, and oomph::PMLTimeHarmonicIsotropicElasticityTensor::nu().
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::wavenumber().
omega_sq()
template<unsigned DIM, class PML_ELEMENT >
const double& oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::omega_sq () const [inline]
Access function for square of non-dim frequency.
Definition at line 209 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Omega_sq_pt.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::wavenumber().
omega_sq_pt()
template<unsigned DIM, class PML_ELEMENT >
double* & oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::omega_sq_pt () [inline]
Access function for square of non-dim frequency.
Definition at line 212 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Omega_sq_pt.
operator=()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::operator= (const PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 100 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::BrokenCopy::broken_assign().
u_index_time_harmonic_linear_elasticity()
template<unsigned DIM, class PML_ELEMENT >
virtual std::complex<unsigned> oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::u_index_time_harmonic_linear_elasticity (const unsigned i) const [inline], [virtual]
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
Definition at line 109 of file pml_time_harmonic_linear_elasticity_elements.h.
References i.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::interpolated_u_time_harmonic_linear_elasticity().
values_to_be_pinned_on_outer_pml_boundary()
template<unsigned DIM, class PML_ELEMENT >
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Definition at line 263 of file pml_time_harmonic_linear_elasticity_elements.h.
wavenumber()
template<unsigned DIM, class PML_ELEMENT >
double oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::wavenumber () const [inline]
Wavenumber for the PML.
Definition at line 215 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::nu(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::omega_sq().
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM, class PML_ELEMENT >
BodyForceFctPt oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 339 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::body_force_fct_pt().
Default_omega_sq_value
template<unsigned DIM, class PML_ELEMENT >
double oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Default_omega_sq_value [static], [protected]
Static default value for square of frequency.
Definition at line 342 of file pml_time_harmonic_linear_elasticity_elements.h.
Default_pml_mapping
template<unsigned DIM, class PML_ELEMENT >
C1BermudezPMLMapping oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Default_pml_mapping [static]
Static so that the class doesn't need to instantiate a new default everytime it uses it
Definition at line 328 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::PMLTimeHarmonicLinearElasticityEquationsBase().
Elasticity_tensor_pt
template<unsigned DIM, class PML_ELEMENT >
PMLTimeHarmonicIsotropicElasticityTensor* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Elasticity_tensor_pt [protected]
Pointer to the elasticity tensor.
Definition at line 333 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::E(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::elasticity_tensor_pt(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::nu().
Omega_sq_pt
template<unsigned DIM, class PML_ELEMENT >
double* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::Omega_sq_pt [protected]
Square of nondim frequency.
Definition at line 336 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::omega_sq(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM, PML_ELEMENT >::omega_sq_pt().
The documentation for this class was generated from the following files:
pml_time_harmonic_linear_elasticity_elements.h
pml_time_harmonic_linear_elasticity_elements.cc