oomph::QSphericalCrouzeixRaviartElement Class Reference
#include <spherical_navier_stokes_elements.h>
Public Member Functions
QSphericalCrouzeixRaviartElement ()
Constructor, there are 3 internal values (for the pressure)
unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
double p_spherical_nst (const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_spherical_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to SphericalNavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to SphericalNavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to SphericalNavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to SphericalNavierStokesEquations output.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (three comp) and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
double dshape_and_dtest_eulerian_spherical_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_spherical_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
void pshape_spherical_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_spherical_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
Protected Attributes
unsigned P_spherical_nst_internal_index
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
Crouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation. They can be used within oomph-lib's block preconditioning framework.
Definition at line 726 of file spherical_navier_stokes_elements.h.
Constructor & Destructor Documentation
QSphericalCrouzeixRaviartElement()
oomph::QSphericalCrouzeixRaviartElement::QSphericalCrouzeixRaviartElement () [inline]
Constructor, there are 3 internal values (for the pressure)
Definition at line 772 of file spherical_navier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_spherical_nst()
double oomph::QSphericalCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_spherical_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 902 of file spherical_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, and pshape_spherical_nst().
Referenced by dshape_and_dtest_eulerian_spherical_nst().
dshape_and_dtest_eulerian_spherical_nst()
double oomph::QSphericalCrouzeixRaviartElement::dshape_and_dtest_eulerian_spherical_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 877 of file spherical_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_at_knot_spherical_nst(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by ndof_types().
fix_pressure()
void oomph::QSphericalCrouzeixRaviartElement::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 794 of file spherical_navier_stokes_elements.h.
References oomph::FSIFluidElement::identify_load_data(), oomph::FSIFluidElement::identify_pressure_data(), oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
full_output() [1/2]
void oomph::QSphericalCrouzeixRaviartElement::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 841 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::full_output().
full_output() [2/2]
void oomph::QSphericalCrouzeixRaviartElement::full_output (std::ostream & outfile, const unsigned & nplot) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Definition at line 847 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::full_output().
get_dof_numbers_for_unknowns()
void oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 2394 of file spherical_navier_stokes_elements.cc.
References oomph::GeneralisedElement::eqn_number(), oomph::QSphericalTaylorHoodElement::identify_load_data(), oomph::QSphericalTaylorHoodElement::Initial_Nvalue, oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::SphericalNavierStokesEquations::npres_spherical_nst(), oomph::Data::nvalue(), oomph::SphericalNavierStokesEquations::p_local_eqn(), and oomph::QSphericalTaylorHoodElement::Pconv.
identify_load_data()
void oomph::QSphericalCrouzeixRaviartElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2339 of file spherical_navier_stokes_elements.cc.
References i, oomph::FSIFluidElement::identify_pressure_data(), identify_pressure_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::SphericalNavierStokesEquations::u_index_spherical_nst().
Referenced by oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst().
identify_pressure_data()
void oomph::QSphericalCrouzeixRaviartElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_pressure_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for pressures values that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2371 of file spherical_navier_stokes_elements.cc.
References oomph::GeneralisedElement::internal_data_pt(), oomph::GeneralisedElement::ninternal_data(), and oomph::Data::nvalue().
Referenced by identify_load_data().
ndof_types()
unsigned oomph::QSphericalCrouzeixRaviartElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (three comp) and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 853 of file spherical_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_spherical_nst(), and oomph::GeneralisedElement::get_dof_numbers_for_unknowns().
npres_spherical_nst()
unsigned oomph::QSphericalCrouzeixRaviartElement::npres_spherical_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 791 of file spherical_navier_stokes_elements.h.
output() [1/4]
void oomph::QSphericalCrouzeixRaviartElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 821 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [2/4]
void oomph::QSphericalCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 825 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [3/4]
void oomph::QSphericalCrouzeixRaviartElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 830 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
output() [4/4]
void oomph::QSphericalCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & nplot) [inline], [virtual]
Redirect output to SphericalNavierStokesEquations output.
Reimplemented from oomph::SphericalNavierStokesEquations.
Definition at line 834 of file spherical_navier_stokes_elements.h.
References oomph::SphericalNavierStokesEquations::output().
p_local_eqn()
int oomph::QSphericalCrouzeixRaviartElement::p_local_eqn (const unsigned & n) const [inline], [protected], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 766 of file spherical_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn().
p_spherical_nst()
double oomph::QSphericalCrouzeixRaviartElement::p_spherical_nst (const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::SphericalNavierStokesEquations.
Definition at line 787 of file spherical_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
pshape_spherical_nst() [1/2]
void oomph::QSphericalCrouzeixRaviartElement::pshape_spherical_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 926 of file spherical_navier_stokes_elements.h.
Referenced by dshape_and_dtest_eulerian_at_knot_spherical_nst().
pshape_spherical_nst() [2/2]
void oomph::QSphericalCrouzeixRaviartElement::pshape_spherical_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Pressure shape and test functions at local coordinte s.
Define the pressure shape and test functions.
Implements oomph::SphericalNavierStokesEquations.
Definition at line 935 of file spherical_navier_stokes_elements.h.
References i, and oomph::SphericalNavierStokesEquations::pshape_spherical_nst().
required_nvalue()
unsigned oomph::QSphericalCrouzeixRaviartElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at local node n.
Reimplemented from oomph::FiniteElement.
Definition at line 781 of file spherical_navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::QSphericalCrouzeixRaviartElement::Initial_Nvalue[] [static], [private]
Static array of ints to hold required number of variables at nodes.
Definition at line 732 of file spherical_navier_stokes_elements.h.
P_spherical_nst_internal_index
unsigned oomph::QSphericalCrouzeixRaviartElement::P_spherical_nst_internal_index [protected]
Internal index that indicates at which internal data the pressure is stored
Definition at line 738 of file spherical_navier_stokes_elements.h.
The documentation for this class was generated from the following files:
spherical_navier_stokes_elements.h
spherical_navier_stokes_elements.cc