oomph::SuperLUSolver Class Reference
. SuperLU Project Solver class. This is a combined wrapper for both SuperLU and SuperLU Dist. See http://crd.lbl.gov/~xiaoye/SuperLU/ Default Behaviour: If this solver is distributed over more than one processor then SuperLU Dist is used. Member data naming convention: member data associated with the SuperLU Dist solver begins Dist_... and member data associated with the serial SuperLU solver begins Serial_... .
#include <linear_solver.h>
Public Types
enum Type { Default,
Serial,
Distributed
 }
enum type to specify the solver behaviour. Default - will employ superlu dist if more than 1 processor. Serial - will always try use superlu (serial). Distributed - will always try to use superlu dist.
Public Member Functions
SuperLUSolver ()
Constructor. Set the defaults.
SuperLUSolver (const SuperLUSolver &dummy)
Broken copy constructor.
void operator= (const SuperLUSolver &)
Broken assignment operator.
~SuperLUSolver ()
Destructor, clean up the stored matrices.
void enable_computation_of_gradient ()
function to enable the computation of the gradient
void disable_resolve ()
Overload disable resolve so that it cleans up memory too.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results Vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual Vector.
void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. The function returns the global result Vector. Note: if Delete_matrix_data is true the function matrix_pt->clean_up_memory() will be used to wipe the matrix data.
void resolve (const DoubleVector &rhs, DoubleVector &result)
Resolve the system defined by the last assembled jacobian and the specified rhs vector if resolve has been enabled. Note: returns the global result Vector.
void enable_doc_stats ()
Enable documentation of solver statistics.
void disable_doc_stats ()
Disable documentation of solver statistics.
double jacobian_setup_time () const
returns the time taken to assemble the jacobian matrix and residual vector
virtual double linear_solver_solution_time () const
return the time taken to solve the linear system (needs to be overloaded for each linear solver)
void factorise (DoubleMatrixBase *const &matrix_pt)
Do the factorisation stage Note: if Delete_matrix_data is true the function matrix_pt->clean_up_memory() will be used to wipe the matrix data.
void backsub (const DoubleVector &rhs, DoubleVector &result)
Do the backsubstitution for SuperLU solver Note: returns the global result Vector.
void clean_up_memory ()
Clean up the memory allocated by the solver.
void set_solver_type (const Type &t)
Specify the solve type. Either default, serial or distributed. See enum SuperLU_solver_type for more details.
void use_compressed_row_for_superlu_serial ()
Use the compressed row format in superlu serial.
void use_compressed_column_for_superlu_serial ()
Use the compressed column format in superlu serial.
void enable_delete_matrix_data_in_superlu_dist ()
Set Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be deleted the flag can be set to true to reduce the amount of memory required, and the matrix data will be wiped using its clean_up_memory() function. Default value is false.
void disable_delete_matrix_data_in_superlu_dist ()
Unset Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be.
void enable_row_and_col_permutations_in_superlu_dist ()
Set flag so that SuperLU_DIST is allowed to permute matrix rows and columns during factorisation. This is the default for SuperLU_DIST, and can lead to significantly faster solves.
void disable_row_and_col_permutations_in_superlu_dist ()
Set flag so that SuperLU_DIST is not allowed to permute matrix rows and columns during factorisation.
void use_global_solve_in_superlu_dist ()
Calling this method will ensure that when the problem based solve interface is used, a global (serial) jacobian will be assembled. Note: calling this function will delete any distributed solve data.
void use_distributed_solve_in_superlu_dist ()
Calling this method will ensure that when the problem based solve interface is used, a distributed jacobian will be assembled. Note: calling this function will delete any global solve data.
Static Public Attributes
static bool Suppress_incorrect_rhs_distribution_warning_in_resolve =false
Static flag that determines whether the warning about incorrect distribution of RHSs will be printed or not.
Private Member Functions
void factorise_serial (DoubleMatrixBase *const &matrix_pt)
factorise method for SuperLU (serial)
void backsub_serial (const DoubleVector &rhs, DoubleVector &result)
backsub method for SuperLU (serial)
void factorise_distributed (DoubleMatrixBase *const &matrix_pt)
factorise method for SuperLU Dist
void backsub_distributed (const DoubleVector &rhs, DoubleVector &result)
backsub method for SuperLU Dist
Private Attributes
double Jacobian_setup_time
Jacobian setup time.
double Solution_time
Solution time.
bool Suppress_solve
Suppress solve?
bool Doc_stats
Set to true to output statistics (false by default).
Type Solver_type
the solver type. see SuperLU_solver_type for details.
bool Using_dist
boolean flag indicating whether superlu dist is being used
void * Serial_f_factors
Storage for the LU factors as required by SuperLU.
int Serial_info
Info flag for the SuperLU solver.
unsigned long Serial_n_dof
The number of unknowns in the linear system.
int Serial_sign_of_determinant_of_matrix
Sign of the determinant of the matrix.
bool Serial_compressed_row_flag
Use compressed row version?
bool Dist_use_global_solver
Flag that determines whether the MPIProblem based solve function uses the global or distributed version of SuperLU_DIST (default value is false).
bool Dist_global_solve_data_allocated
Flag is true if solve data has been generated for a global matrix.
bool Dist_distributed_solve_data_allocated
Flag is true if solve data has been generated for distributed matrix.
void * Dist_solver_data_pt
Storage for the LU factors and other data required by SuperLU.
int Dist_nprow
Number of rows for the process grid.
int Dist_npcol
Number of columns for the process grid.
int Dist_info
Info flag for the SuperLU solver.
bool Dist_allow_row_and_col_permutations
If true then SuperLU_DIST is allowed to permute matrix rows and columns during factorisation. This is the default for SuperLU_DIST, and can lead to significantly faster solves, but has been known to fail, hence the default value is 0.
bool Dist_delete_matrix_data
Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be deleted the flag can be set to true to reduce the amount of memory required, and the matrix data will be wiped using its clean_up_memory() function. Default value is false.
double * Dist_value_pt
Pointer for storage of the matrix values required by SuperLU_DIST.
int * Dist_index_pt
Pointer for storage of matrix rows or column indices required by SuperLU_DIST.
int * Dist_start_pt
Pointers for storage of matrix column or row starts.
Additional Inherited Members
Detailed Description
. SuperLU Project Solver class. This is a combined wrapper for both SuperLU and SuperLU Dist. See http://crd.lbl.gov/~xiaoye/SuperLU/ Default Behaviour: If this solver is distributed over more than one processor then SuperLU Dist is used. Member data naming convention: member data associated with the SuperLU Dist solver begins Dist_... and member data associated with the serial SuperLU solver begins Serial_... .
Definition at line 424 of file linear_solver.h.
Member Enumeration Documentation
Type
enum oomph::SuperLUSolver::Type
enum type to specify the solver behaviour. Default - will employ superlu dist if more than 1 processor. Serial - will always try use superlu (serial). Distributed - will always try to use superlu dist.
Enumerator
Default
Serial
Distributed
Definition at line 433 of file linear_solver.h.
Constructor & Destructor Documentation
SuperLUSolver() [1/2]
oomph::SuperLUSolver::SuperLUSolver () [inline]
Constructor. Set the defaults.
Definition at line 436 of file linear_solver.h.
References oomph::Missing_masters_functions::Doc_stats.
SuperLUSolver() [2/2]
oomph::SuperLUSolver::SuperLUSolver (const SuperLUSolver & dummy) [inline]
Broken copy constructor.
Definition at line 465 of file linear_solver.h.
References oomph::BrokenCopy::broken_copy().
 SuperLUSolver()
oomph::SuperLUSolver::~SuperLUSolver () [inline]
Destructor, clean up the stored matrices.
Definition at line 477 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
Member Function Documentation
backsub()
void oomph::SuperLUSolver::backsub (const DoubleVector & rhs, DoubleVector & result)
Do the backsubstitution for SuperLU solver Note: returns the global result Vector.
Do the backsubstitution for SuperLUSolver. Note - this method performs no paranoid checks - these are all performed in solve(...) and resolve(...)
Definition at line 1539 of file linear_solver.cc.
References Suppress_incorrect_rhs_distribution_warning_in_resolve.
backsub_distributed()
void oomph::SuperLUSolver::backsub_distributed (const DoubleVector & rhs, DoubleVector & result) [private]
backsub method for SuperLU Dist
Do the backsubstitution for SuperLU solver. Note - this method performs no paranoid checks - these are all performed in solve(...) and resolve(...)
Definition at line 1567 of file linear_solver.cc.
References oomph::LinearAlgebraDistribution::built(), oomph::LinearAlgebraDistribution::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_built(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LeakCheckNames::doc(), oomph::Missing_masters_functions::Doc_stats, oomph::LinearAlgebraDistribution::nrow(), oomph::superlu_dist_distributed_matrix(), oomph::superlu_dist_global_matrix(), and oomph::DoubleVector::values_pt().
backsub_serial()
void oomph::SuperLUSolver::backsub_serial (const DoubleVector & rhs, DoubleVector & result) [private]
backsub method for SuperLU (serial)
Do the backsubstitution for SuperLU.
Definition at line 1688 of file linear_solver.cc.
References oomph::DoubleVector::built(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LeakCheckNames::doc(), oomph::Missing_masters_functions::Doc_stats, i, oomph::DistributableLinearAlgebraObject::nrow(), and oomph::superlu().
clean_up_memory()
void oomph::SuperLUSolver::clean_up_memory () [virtual]
Clean up the memory allocated by the solver.
Clean up the memory.
Reimplemented from oomph::LinearSolver.
Definition at line 1774 of file linear_solver.cc.
References oomph::DistributableLinearAlgebraObject::clear_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LeakCheckNames::doc(), oomph::Missing_masters_functions::Doc_stats, i, oomph::LinearAlgebraDistribution::nrow(), oomph::superlu(), oomph::superlu_dist_distributed_matrix(), and oomph::superlu_dist_global_matrix().
Referenced by oomph::SuperLUPreconditioner::clean_up_memory().
disable_delete_matrix_data_in_superlu_dist()
void oomph::SuperLUSolver::disable_delete_matrix_data_in_superlu_dist () [inline]
Unset Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be.
Definition at line 597 of file linear_solver.h.
disable_doc_stats()
void oomph::SuperLUSolver::disable_doc_stats () [inline]
Disable documentation of solver statistics.
Definition at line 532 of file linear_solver.h.
References oomph::Missing_masters_functions::Doc_stats.
Referenced by oomph::SuperLUPreconditioner::SuperLUPreconditioner().
disable_resolve()
void oomph::SuperLUSolver::disable_resolve () [inline], [virtual]
Overload disable resolve so that it cleans up memory too.
Reimplemented from oomph::LinearSolver.
Definition at line 492 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory(), oomph::LinearSolver::disable_resolve(), oomph::LinearSolver::resolve(), and oomph::LinearSolver::solve().
disable_row_and_col_permutations_in_superlu_dist()
void oomph::SuperLUSolver::disable_row_and_col_permutations_in_superlu_dist () [inline]
Set flag so that SuperLU_DIST is not allowed to permute matrix rows and columns during factorisation.
Definition at line 608 of file linear_solver.h.
enable_computation_of_gradient()
void oomph::SuperLUSolver::enable_computation_of_gradient () [inline], [virtual]
function to enable the computation of the gradient
Reimplemented from oomph::LinearSolver.
Definition at line 483 of file linear_solver.h.
References oomph::LinearSolver::Compute_gradient.
enable_delete_matrix_data_in_superlu_dist()
void oomph::SuperLUSolver::enable_delete_matrix_data_in_superlu_dist () [inline]
Set Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be deleted the flag can be set to true to reduce the amount of memory required, and the matrix data will be wiped using its clean_up_memory() function. Default value is false.
Definition at line 591 of file linear_solver.h.
enable_doc_stats()
void oomph::SuperLUSolver::enable_doc_stats () [inline]
Enable documentation of solver statistics.
Definition at line 529 of file linear_solver.h.
References oomph::Missing_masters_functions::Doc_stats.
enable_row_and_col_permutations_in_superlu_dist()
void oomph::SuperLUSolver::enable_row_and_col_permutations_in_superlu_dist () [inline]
Set flag so that SuperLU_DIST is allowed to permute matrix rows and columns during factorisation. This is the default for SuperLU_DIST, and can lead to significantly faster solves.
Definition at line 603 of file linear_solver.h.
factorise()
void oomph::SuperLUSolver::factorise (DoubleMatrixBase *const & matrix_pt)
Do the factorisation stage Note: if Delete_matrix_data is true the function matrix_pt->clean_up_memory() will be used to wipe the matrix data.
LU decompose the matrix addressed by matrix_pt by using the SuperLU solver. The resulting matrix factors are stored internally.
Definition at line 1104 of file linear_solver.cc.
References oomph::DenseLU::clean_up_memory(), oomph::LinearAlgebraDistribution::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), and oomph::MPI_Helpers::mpi_has_been_initialised().
Referenced by oomph::SuperLUPreconditioner::setup().
factorise_distributed()
void oomph::SuperLUSolver::factorise_distributed (DoubleMatrixBase *const & matrix_pt) [private]
factorise method for SuperLU Dist
LU decompose the matrix addressed by matrix_pt using the SuperLU_DIST solver. The resulting matrix factors are stored internally.
Definition at line 1151 of file linear_solver.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::CRDoubleMatrix::built(), oomph::DenseLU::clean_up_memory(), oomph::CCMatrix< T >::clean_up_memory(), oomph::CRDoubleMatrix::clear(), oomph::CRDoubleMatrix::column_index(), oomph::CCMatrix< T >::column_start(), oomph::LinearAlgebraDistribution::communicator_pt(), oomph::MPI_Helpers::communicator_pt(), oomph::DistributableLinearAlgebraObject::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LeakCheckNames::doc(), oomph::Missing_masters_functions::Doc_stats, oomph::DistributableLinearAlgebraObject::first_row(), i, oomph::DoubleMatrixBase::ncol(), oomph::SparseMatrix< T, MATRIX_TYPE >::nnz(), oomph::CRDoubleMatrix::nnz(), oomph::LinearAlgebraDistribution::nrow(), oomph::DoubleMatrixBase::nrow(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::CRDoubleMatrix::nrow(), oomph::CCDoubleMatrix::nrow(), oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::CCMatrix< T >::row_index(), oomph::CRDoubleMatrix::row_start(), oomph::superlu_cr_to_cc(), oomph::superlu_dist_distributed_matrix(), oomph::superlu_dist_global_matrix(), oomph::SparseMatrix< T, MATRIX_TYPE >::value(), and oomph::CRDoubleMatrix::value().
factorise_serial()
void oomph::SuperLUSolver::factorise_serial (DoubleMatrixBase *const & matrix_pt) [private]
factorise method for SuperLU (serial)
LU decompose the matrix addressed by matrix_pt by using the SuperLU solver. The resulting matrix factors are stored internally.
Definition at line 1413 of file linear_solver.cc.
References oomph::DenseLU::clean_up_memory(), oomph::CRDoubleMatrix::column_index(), oomph::CCMatrix< T >::column_start(), oomph::DistributableLinearAlgebraObject::distributed(), oomph::LeakCheckNames::doc(), oomph::Missing_masters_functions::Doc_stats, i, oomph::DoubleMatrixBase::ncol(), oomph::SparseMatrix< T, MATRIX_TYPE >::nnz(), oomph::CRDoubleMatrix::nnz(), oomph::DoubleMatrixBase::nrow(), oomph::CCMatrix< T >::row_index(), oomph::CRDoubleMatrix::row_start(), oomph::CumulativeTimings::start(), oomph::superlu(), oomph::SparseMatrix< T, MATRIX_TYPE >::value(), and oomph::CRDoubleMatrix::value().
jacobian_setup_time()
double oomph::SuperLUSolver::jacobian_setup_time () const [inline], [virtual]
returns the time taken to assemble the jacobian matrix and residual vector
Reimplemented from oomph::LinearSolver.
Definition at line 536 of file linear_solver.h.
linear_solver_solution_time()
virtual double oomph::SuperLUSolver::linear_solver_solution_time () const [inline], [virtual]
return the time taken to solve the linear system (needs to be overloaded for each linear solver)
Reimplemented from oomph::LinearSolver.
Definition at line 543 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
operator=()
void oomph::SuperLUSolver::operator= (const SuperLUSolver &) [inline]
Broken assignment operator.
Definition at line 471 of file linear_solver.h.
References oomph::BrokenCopy::broken_assign().
resolve()
void oomph::SuperLUSolver::resolve (const DoubleVector & rhs, DoubleVector & result) [virtual]
Resolve the system defined by the last assembled jacobian and the specified rhs vector if resolve has been enabled. Note: returns the global result Vector.
Resolve the system for a given RHS.
Reimplemented from oomph::LinearSolver.
Definition at line 1080 of file linear_solver.cc.
References oomph::DenseLU::backsub(), oomph::LinearSolver::Doc_time, oomph::oomph_info, oomph::DenseLU::Solution_time, and oomph::TimingHelpers::timer().
Referenced by oomph::SuperLUPreconditioner::preconditioner_solve().
set_solver_type()
void oomph::SuperLUSolver::set_solver_type (const Type & t) [inline]
Specify the solve type. Either default, serial or distributed. See enum SuperLU_solver_type for more details.
Definition at line 563 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory(), and t.
solve() [1/2]
void oomph::SuperLUSolver::solve (Problem *const & problem_pt, DoubleVector & result) [virtual]
Solver: Takes pointer to problem and returns the results Vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual Vector.
Solver: Takes pointer to problem and returns the results Vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual Vector.
Implements oomph::LinearSolver.
Definition at line 678 of file linear_solver.cc.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DoubleVector::built(), oomph::DenseLU::clean_up_memory(), oomph::Problem::communicator_pt(), oomph::LinearSolver::Compute_gradient, oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LinearSolver::Doc_time, oomph::Problem::get_jacobian(), oomph::LinearSolver::Gradient_for_glob_conv_newton_solve, oomph::LinearSolver::Gradient_has_been_computed, oomph::DenseLU::Jacobian_setup_time, oomph::CRDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::Problem::ndof(), oomph::oomph_info, oomph::DoubleVector::redistribute(), oomph::Problem::sign_of_jacobian(), oomph::DenseLU::solve(), and oomph::TimingHelpers::timer().
solve() [2/2]
void oomph::SuperLUSolver::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & result) [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. The function returns the global result Vector. Note: if Delete_matrix_data is true the function matrix_pt->clean_up_memory() will be used to wipe the matrix data.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. Problem pointer defaults to NULL and can be omitted. The function returns the global result Vector. Note: if Delete_matrix_data is true the function matrix_pt->clean_up_memory() will be used to wipe the matrix data.
Reimplemented from oomph::LinearSolver.
Definition at line 933 of file linear_solver.cc.
References oomph::DenseLU::backsub(), oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DoubleVector::built(), oomph::DenseLU::clean_up_memory(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::DenseLU::factorise(), oomph::DoubleMatrixBase::ncol(), oomph::DoubleMatrixBase::nrow(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::DenseLU::Solution_time, and oomph::TimingHelpers::timer().
use_compressed_column_for_superlu_serial()
void oomph::SuperLUSolver::use_compressed_column_for_superlu_serial () [inline]
Use the compressed column format in superlu serial.
Definition at line 577 of file linear_solver.h.
use_compressed_row_for_superlu_serial()
void oomph::SuperLUSolver::use_compressed_row_for_superlu_serial () [inline]
Use the compressed row format in superlu serial.
Definition at line 573 of file linear_solver.h.
use_distributed_solve_in_superlu_dist()
void oomph::SuperLUSolver::use_distributed_solve_in_superlu_dist () [inline]
Calling this method will ensure that when the problem based solve interface is used, a distributed jacobian will be assembled. Note: calling this function will delete any global solve data.
Definition at line 628 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
use_global_solve_in_superlu_dist()
void oomph::SuperLUSolver::use_global_solve_in_superlu_dist () [inline]
Calling this method will ensure that when the problem based solve interface is used, a global (serial) jacobian will be assembled. Note: calling this function will delete any distributed solve data.
Definition at line 615 of file linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
Member Data Documentation
Dist_allow_row_and_col_permutations
bool oomph::SuperLUSolver::Dist_allow_row_and_col_permutations [private]
If true then SuperLU_DIST is allowed to permute matrix rows and columns during factorisation. This is the default for SuperLU_DIST, and can lead to significantly faster solves, but has been known to fail, hence the default value is 0.
Definition at line 733 of file linear_solver.h.
Dist_delete_matrix_data
bool oomph::SuperLUSolver::Dist_delete_matrix_data [private]
Delete_matrix_data flag. SuperLU_dist needs its own copy of the input matrix, therefore a copy must be made if any matrix used with this solver is to be preserved. If the input matrix can be deleted the flag can be set to true to reduce the amount of memory required, and the matrix data will be wiped using its clean_up_memory() function. Default value is false.
Definition at line 741 of file linear_solver.h.
Dist_distributed_solve_data_allocated
bool oomph::SuperLUSolver::Dist_distributed_solve_data_allocated [private]
Flag is true if solve data has been generated for distributed matrix.
Definition at line 715 of file linear_solver.h.
Dist_global_solve_data_allocated
bool oomph::SuperLUSolver::Dist_global_solve_data_allocated [private]
Flag is true if solve data has been generated for a global matrix.
Definition at line 712 of file linear_solver.h.
Dist_index_pt
int* oomph::SuperLUSolver::Dist_index_pt [private]
Pointer for storage of matrix rows or column indices required by SuperLU_DIST.
Definition at line 748 of file linear_solver.h.
Dist_info
int oomph::SuperLUSolver::Dist_info [private]
Info flag for the SuperLU solver.
Definition at line 727 of file linear_solver.h.
Dist_npcol
int oomph::SuperLUSolver::Dist_npcol [private]
Number of columns for the process grid.
Definition at line 724 of file linear_solver.h.
Dist_nprow
int oomph::SuperLUSolver::Dist_nprow [private]
Number of rows for the process grid.
Definition at line 721 of file linear_solver.h.
Dist_solver_data_pt
void* oomph::SuperLUSolver::Dist_solver_data_pt [private]
Storage for the LU factors and other data required by SuperLU.
Definition at line 718 of file linear_solver.h.
Dist_start_pt
int* oomph::SuperLUSolver::Dist_start_pt [private]
Pointers for storage of matrix column or row starts.
Definition at line 752 of file linear_solver.h.
Dist_use_global_solver
bool oomph::SuperLUSolver::Dist_use_global_solver [private]
Flag that determines whether the MPIProblem based solve function uses the global or distributed version of SuperLU_DIST (default value is false).
Definition at line 709 of file linear_solver.h.
Dist_value_pt
double* oomph::SuperLUSolver::Dist_value_pt [private]
Pointer for storage of the matrix values required by SuperLU_DIST.
Definition at line 744 of file linear_solver.h.
Doc_stats
bool oomph::SuperLUSolver::Doc_stats [private]
Set to true to output statistics (false by default).
Definition at line 670 of file linear_solver.h.
Jacobian_setup_time
double oomph::SuperLUSolver::Jacobian_setup_time [private]
Jacobian setup time.
Definition at line 661 of file linear_solver.h.
Serial_compressed_row_flag
bool oomph::SuperLUSolver::Serial_compressed_row_flag [private]
Use compressed row version?
Definition at line 694 of file linear_solver.h.
Serial_f_factors
void* oomph::SuperLUSolver::Serial_f_factors [private]
Storage for the LU factors as required by SuperLU.
Definition at line 682 of file linear_solver.h.
Serial_info
int oomph::SuperLUSolver::Serial_info [private]
Info flag for the SuperLU solver.
Definition at line 685 of file linear_solver.h.
Serial_n_dof
unsigned long oomph::SuperLUSolver::Serial_n_dof [private]
The number of unknowns in the linear system.
Definition at line 688 of file linear_solver.h.
Serial_sign_of_determinant_of_matrix
int oomph::SuperLUSolver::Serial_sign_of_determinant_of_matrix [private]
Sign of the determinant of the matrix.
Definition at line 691 of file linear_solver.h.
Solution_time
double oomph::SuperLUSolver::Solution_time [private]
Solution time.
Definition at line 664 of file linear_solver.h.
Solver_type
Type oomph::SuperLUSolver::Solver_type [private]
the solver type. see SuperLU_solver_type for details.
Definition at line 673 of file linear_solver.h.
Suppress_incorrect_rhs_distribution_warning_in_resolve
bool oomph::SuperLUSolver::Suppress_incorrect_rhs_distribution_warning_in_resolve =false [static]
Static flag that determines whether the warning about incorrect distribution of RHSs will be printed or not.
Static warning to suppress warnings about incorrect distribution of RHS vector. Default is false
Definition at line 703 of file linear_solver.h.
Referenced by backsub().
Suppress_solve
bool oomph::SuperLUSolver::Suppress_solve [private]
Suppress solve?
Definition at line 667 of file linear_solver.h.
Using_dist
bool oomph::SuperLUSolver::Using_dist [private]
boolean flag indicating whether superlu dist is being used
Definition at line 676 of file linear_solver.h.
The documentation for this class was generated from the following files:
linear_solver.h
linear_solver.cc