oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <spherical_advection_diffusion_elements.h>
Public Types
typedef void(* SphericalAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
typedef void(* SphericalAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Public Member Functions
SphericalAdvectionDiffusionFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
SphericalAdvectionDiffusionFluxElement ()
Broken empty constructor.
SphericalAdvectionDiffusionFluxElement (const SphericalAdvectionDiffusionFluxElement &dummy)
Broken copy constructor.
void operator= (const SphericalAdvectionDiffusionFluxElement &)
Broken assignment operator.
SphericalAdvectionDiffusionPrescribedBetaFctPt & beta_fct_pt ()
Access function for the prescribed-beta function pointer.
SphericalAdvectionDiffusionPrescribedAlphaFctPt & alpha_fct_pt ()
Access function for the prescribed-alpha function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &nplot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_beta (const Vector< double > &x, double &beta)
Function to calculate the prescribed beta at a given spatial position.
void get_alpha (const Vector< double > &x, double &alpha)
Function to calculate the prescribed alpha at a given spatial position.
Private Member Functions
void fill_in_generic_residual_contribution_spherical_adv_diff_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
SphericalAdvectionDiffusionPrescribedBetaFctPt Beta_fct_pt
Function pointer to the (global) prescribed-beta function.
SphericalAdvectionDiffusionPrescribedAlphaFctPt Alpha_fct_pt
Function pointer to the (global) prescribed-alpha function.
unsigned U_index_adv_diff
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied Robin boundary condition on the boundaries of Steady Axisymmnetric Advection Diffusion Flux elements.
 -\Delta u \cdot \mathbf{n} + \alpha(r,z) u = \beta(r,z) 
 The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 683 of file spherical_advection_diffusion_elements.h.
Member Typedef Documentation
SphericalAdvectionDiffusionPrescribedAlphaFctPt
template<class ELEMENT >
typedef void(* oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionPrescribedAlphaFctPt) (const Vector< double > &x, double &alpha)
Function pointer to the prescribed-alpha function fct(x,alpha(x)) -- x is a Vector!
Definition at line 699 of file spherical_advection_diffusion_elements.h.
SphericalAdvectionDiffusionPrescribedBetaFctPt
template<class ELEMENT >
typedef void(* oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionPrescribedBetaFctPt) (const Vector< double > &x, double &beta)
Function pointer to the prescribed-beta function fct(x,beta(x)) -- x is a Vector!
Definition at line 693 of file spherical_advection_diffusion_elements.h.
Constructor & Destructor Documentation
SphericalAdvectionDiffusionFluxElement() [1/3]
template<class ELEMENT >
oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Definition at line 906 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt, oomph::FiniteElement::build_face_element(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), oomph::FiniteElement::has_hanging_nodes(), oomph::Global_string_for_annotation::string(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, and oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff().
SphericalAdvectionDiffusionFluxElement() [2/3]
template<class ELEMENT >
oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement () [inline]
Broken empty constructor.
Definition at line 711 of file spherical_advection_diffusion_elements.h.
SphericalAdvectionDiffusionFluxElement() [3/3]
template<class ELEMENT >
oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement (const SphericalAdvectionDiffusionFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 720 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha_fct_pt()
template<class ELEMENT >
SphericalAdvectionDiffusionPrescribedAlphaFctPt& oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::alpha_fct_pt () [inline]
Access function for the prescribed-alpha function pointer.
Definition at line 739 of file spherical_advection_diffusion_elements.h.
beta_fct_pt()
template<class ELEMENT >
SphericalAdvectionDiffusionPrescribedBetaFctPt& oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::beta_fct_pt () [inline]
Access function for the prescribed-beta function pointer.
Definition at line 733 of file spherical_advection_diffusion_elements.h.
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 758 of file spherical_advection_diffusion_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 746 of file spherical_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_residual_contribution_spherical_adv_diff_flux()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix for the Robin boundary condition:
 \Delta u \cdot \mathbf{n} + \alpha (\mathbf{x}) = \beta (\mathbf{x}) 
.
Definition at line 990 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::get_alpha(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::get_beta(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), s, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement().
get_alpha()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::get_alpha (const Vector< double > & x, double & alpha) [inline], [protected]
Function to calculate the prescribed alpha at a given spatial position.
Definition at line 858 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux().
get_beta()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::get_beta (const Vector< double > & x, double & beta) [inline], [protected]
Function to calculate the prescribed beta at a given spatial position.
Definition at line 842 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux().
operator=()
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::operator= (const SphericalAdvectionDiffusionFluxElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 727 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/2]
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 778 of file spherical_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 785 of file spherical_advection_diffusion_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 796 of file spherical_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 820 of file spherical_advection_diffusion_elements.h.
References i, oomph::FiniteElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
zeta_nodal()
template<class ELEMENT >
double oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Specify the value of nodal zeta from the face geometry
Reimplemented from oomph::FaceElement.
Definition at line 772 of file spherical_advection_diffusion_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Alpha_fct_pt
template<class ELEMENT >
SphericalAdvectionDiffusionPrescribedAlphaFctPt oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::Alpha_fct_pt [private]
Function pointer to the (global) prescribed-alpha function.
Definition at line 886 of file spherical_advection_diffusion_elements.h.
Beta_fct_pt
template<class ELEMENT >
SphericalAdvectionDiffusionPrescribedBetaFctPt oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::Beta_fct_pt [private]
Function pointer to the (global) prescribed-beta function.
Definition at line 883 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement().
U_index_adv_diff
template<class ELEMENT >
unsigned oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff [private]
The index at which the unknown is stored at the nodes.
Definition at line 889 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), and oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement().
The documentation for this class was generated from the following file:
spherical_advection_diffusion_elements.h