oomph::BrickFromTetMesh< ELEMENT > Class Template Reference
#include <brick_from_tet_mesh.template.h>
Public Member Functions
BrickFromTetMesh (const std::string xda_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass xda file name.
BrickFromTetMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor: Pass the files required for the tetgen mesh.
BrickFromTetMesh (const std::string xda_file_name, XdaTetMesh< TElement< 3, 3 > > *&xda_tet_mesh_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass xda file name. This returns a pointer to the internally built XdaTetMesh for external use. Note that YOU are responsible for deleting this mesh.
Vector< unsigned > oomph_lib_boundary_ids (const unsigned &xda_boundary_id)
Access functions to the Vector of oomph-lib boundary ids that make up boundary b in the original xda enumeration.
Private Member Functions
void build_mesh (XdaTetMesh< TElement< 3, 3 > > *tet_mesh_pt, TimeStepper *time_stepper_pt)
Build fct: Pass pointer to existing tet mesh.
void build_mesh (TetgenMesh< TElement< 3, 3 > > *tet_mesh_pt, TimeStepper *time_stepper_pt)
Build fct: Pass pointer to existing tet mesh.
Private Attributes
Vector< Vector< unsigned > > Boundary_id
Vector of vectors containing the boundary IDs of the overall boundary specified in the xda file.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::BrickFromTetMesh< ELEMENT >
Brick mesh built by brickifying an existing tet mesh -- each tet gets split into four bricks. Can only be built with quadratic (27 node) elements.
Definition at line 66 of file brick_from_tet_mesh.template.h.
Constructor & Destructor Documentation
BrickFromTetMesh() [1/3]
template<class ELEMENT >
oomph::BrickFromTetMesh< ELEMENT >::BrickFromTetMesh (const std::string xda_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass xda file name.
Definition at line 72 of file brick_from_tet_mesh.template.h.
References oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
BrickFromTetMesh() [2/3]
template<class ELEMENT >
oomph::BrickFromTetMesh< ELEMENT >::BrickFromTetMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor: Pass the files required for the tetgen mesh.
Definition at line 91 of file brick_from_tet_mesh.template.h.
References oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
BrickFromTetMesh() [3/3]
template<class ELEMENT >
oomph::BrickFromTetMesh< ELEMENT >::BrickFromTetMesh (const std::string xda_file_name, XdaTetMesh< TElement< 3, 3 > > *& xda_tet_mesh_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass xda file name. This returns a pointer to the internally built XdaTetMesh for external use. Note that YOU are responsible for deleting this mesh.
Definition at line 122 of file brick_from_tet_mesh.template.h.
References oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
Member Function Documentation
build_mesh() [1/2]
template<class ELEMENT >
void oomph::BrickFromTetMesh< ELEMENT >::build_mesh (XdaTetMesh< TElement< 3, 3 > > * tet_mesh_pt, TimeStepper * time_stepper_pt) [private]
Build fct: Pass pointer to existing tet mesh.
Build fct: Pass pointer to existing tet mesh and timestepper Specialisation for XdaTetMesh<TElement<3,3> >
Definition at line 45 of file brick_from_tet_mesh.template.cc.
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e, oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), oomph::QElement2FaceToBulkCoordinates::face2(), oomph::BrickFromTetMeshHelper::Face_position_tolerance, oomph::TFace::get_boundaries_pt(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::TFace::is_boundary_face(), oomph::Node::is_on_boundary(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), s, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::Node::set_coordinates_on_boundary(), oomph::Data::set_value(), and oomph::Node::x().
Referenced by oomph::BrickFromTetMesh< ELEMENT >::BrickFromTetMesh(), and oomph::BrickFromTetMesh< ELEMENT >::oomph_lib_boundary_ids().
build_mesh() [2/2]
template<class ELEMENT >
void oomph::BrickFromTetMesh< ELEMENT >::build_mesh (TetgenMesh< TElement< 3, 3 > > * tet_mesh_pt, TimeStepper * time_stepper_pt) [private]
Build fct: Pass pointer to existing tet mesh.
Build fct: Pass pointer to existing tet mesh and timestepper Specialisation for TetgenMesh<TElement<3,3> >
Definition at line 4944 of file brick_from_tet_mesh.template.cc.
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e, oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), oomph::QElement2FaceToBulkCoordinates::face2(), oomph::BrickFromTetMeshHelper::Face_position_tolerance, oomph::TFace::get_boundaries_pt(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::TFace::is_boundary_face(), oomph::Node::is_on_boundary(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), s, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::Node::set_coordinates_on_boundary(), oomph::Data::set_value(), and oomph::Node::x().
oomph_lib_boundary_ids()
template<class ELEMENT >
Vector<unsigned> oomph::BrickFromTetMesh< ELEMENT >::oomph_lib_boundary_ids (const unsigned & xda_boundary_id) [inline]
Access functions to the Vector of oomph-lib boundary ids that make up boundary b in the original xda enumeration.
Definition at line 142 of file brick_from_tet_mesh.template.h.
References oomph::BrickFromTetMesh< ELEMENT >::Boundary_id, and oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
Member Data Documentation
Boundary_id
template<class ELEMENT >
Vector<Vector<unsigned> > oomph::BrickFromTetMesh< ELEMENT >::Boundary_id [private]
Vector of vectors containing the boundary IDs of the overall boundary specified in the xda file.
Definition at line 160 of file brick_from_tet_mesh.template.h.
Referenced by oomph::BrickFromTetMesh< ELEMENT >::oomph_lib_boundary_ids().
The documentation for this class was generated from the following files:
brick_from_tet_mesh.template.h
brick_from_tet_mesh.template.cc