oomph::YoungLaplaceContactAngleElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an contact angle bcs for Young Laplace elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class. Jacobian is evaluated by finite differencing.
#include <young_laplace_contact_angle_elements.h>
Public Member Functions
YoungLaplaceContactAngleElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
YoungLaplaceContactAngleElement ()
Broken empty constructor.
YoungLaplaceContactAngleElement (const YoungLaplaceContactAngleElement &dummy)
Broken copy constructor.
void operator= (const YoungLaplaceContactAngleElement &)
Broken assignment operator.
double * prescribed_cos_gamma_pt () const
Access function for the pointer to the prescribed contact angle (const version)
double *& prescribed_cos_gamma_pt ()
Access function for the pointer to the prescribed contact angle.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
int u_local_eqn (const unsigned &n)
Get the local equation number of the (one and only) unknown stored at local node n (returns -1 if value is pinned). Can be overloaded in derived multiphysics elements.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
double actual_cos_contact_angle (const Vector< double > &s)
Compute cosinus of actual contact angle.
void contact_line_vectors (const Vector< double > &s, Vector< double > &tangent, Vector< double > &normal)
Get unit tangent and normal vectors to contact line.
void contact_line_vectors (const Vector< double > &s, Vector< double > &tangent, Vector< double > &normal, double &norm_of_drds)
Get unit tangent and normal vectors to contact line. Final argument gives the norm of dR/ds where R is the vector to the contact line and s the local coordinate in the element.
void contact_line_vectors (const Vector< double > &s, Vector< double > &tangent, Vector< double > &normal, Vector< double > &spine, double &norm_of_drds)
Get tangent and normal vectors to contact line and spine vector (wall normal can then be obtained by cross-product). Final argument gives the norm of dR/ds where R is the vector to the contact line and s the local coordinate in the element.
Protected Member Functions
double & u (const unsigned int &n)
Define an access function to the first data value stored at each node. In a more general `Equation` element, such abstraction is essential, because different Elements will store the same variables in different locations.
double prescribed_cos_gamma ()
Function to calculate the cos of the prescribed contact angle.
Private Attributes
double * Prescribed_cos_gamma_pt
Pointer to prescribed cos gamma.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::YoungLaplaceContactAngleElement< ELEMENT >
A class for elements that allow the imposition of an contact angle bcs for Young Laplace elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class. Jacobian is evaluated by finite differencing.
Definition at line 56 of file young_laplace_contact_angle_elements.h.
Constructor & Destructor Documentation
YoungLaplaceContactAngleElement() [1/3]
template<class ELEMENT >
oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
Definition at line 44 of file young_laplace_contact_angle_elements.cc.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::Prescribed_cos_gamma_pt.
YoungLaplaceContactAngleElement() [2/3]
template<class ELEMENT >
oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement () [inline]
Broken empty constructor.
Definition at line 68 of file young_laplace_contact_angle_elements.h.
YoungLaplaceContactAngleElement() [3/3]
template<class ELEMENT >
oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement (const YoungLaplaceContactAngleElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 77 of file young_laplace_contact_angle_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
actual_cos_contact_angle()
template<class ELEMENT >
double oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle (const Vector< double > & s)
Compute cosinus of actual contact angle.
Get the actual contact angle.
Definition at line 168 of file young_laplace_contact_angle_elements.cc.
References oomph::FaceElement::bulk_element_pt(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), i, oomph::FaceElement::local_coordinate_in_bulk(), and oomph::FaceElement::outer_unit_normal().
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::output().
contact_line_vectors() [1/3]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors (const Vector< double > & s, Vector< double > & tangent, Vector< double > & normal) [inline]
Get unit tangent and normal vectors to contact line.
Definition at line 149 of file young_laplace_contact_angle_elements.h.
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals().
contact_line_vectors() [2/3]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors (const Vector< double > & s, Vector< double > & tangent, Vector< double > & normal, double & norm_of_drds) [inline]
Get unit tangent and normal vectors to contact line. Final argument gives the norm of dR/ds where R is the vector to the contact line and s the local coordinate in the element.
Definition at line 162 of file young_laplace_contact_angle_elements.h.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors().
contact_line_vectors() [3/3]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors (const Vector< double > & s, Vector< double > & tangent, Vector< double > & normal, Vector< double > & spine, double & norm_of_drds)
Get tangent and normal vectors to contact line and spine vector (wall normal can then be obtained by cross-product). Final argument gives the norm of dR/ds where R is the vector to the contact line and s the local coordinate in the element.
Get unit tangent and normal to contact line and the spine itself (this allows the wall normal to be worked out by a cross product). Final argument gives the norm of dR/ds where R is the vector to the contact line and s the local coordinate in the element.
Definition at line 283 of file young_laplace_contact_angle_elements.cc.
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::get_ds_bulk_ds_face(), i, oomph::FiniteElement::interpolated_zeta(), oomph::FaceElement::local_coordinate_in_bulk(), and oomph::FaceElement::normal_sign().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Add the element's contribution to its residual vector.
Compute the element's contribution to the residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 81 of file young_laplace_contact_angle_elements.cc.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma(), s, oomph::FiniteElement::shape_at_knot(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::u_local_eqn(), and oomph::Integral::weight().
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma_pt(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement().
operator=()
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::operator= (const YoungLaplaceContactAngleElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 83 of file young_laplace_contact_angle_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 128 of file young_laplace_contact_angle_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 132 of file young_laplace_contact_angle_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 137 of file young_laplace_contact_angle_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::YoungLaplaceContactAngleElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 142 of file young_laplace_contact_angle_elements.h.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle(), oomph::FiniteElement::output(), and s.
prescribed_cos_gamma()
template<class ELEMENT >
double oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma () [inline], [protected]
Function to calculate the cos of the prescribed contact angle.
Definition at line 192 of file young_laplace_contact_angle_elements.h.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::Prescribed_cos_gamma_pt.
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals().
prescribed_cos_gamma_pt() [1/2]
template<class ELEMENT >
double* oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma_pt () const [inline]
Access function for the pointer to the prescribed contact angle (const version)
Definition at line 91 of file young_laplace_contact_angle_elements.h.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::Prescribed_cos_gamma_pt.
prescribed_cos_gamma_pt() [2/2]
template<class ELEMENT >
double*& oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma_pt () [inline]
Access function for the pointer to the prescribed contact angle.
Definition at line 98 of file young_laplace_contact_angle_elements.h.
References oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::Prescribed_cos_gamma_pt.
u()
template<class ELEMENT >
double& oomph::YoungLaplaceContactAngleElement< ELEMENT >::u (const unsigned int & n) [inline], [protected]
Define an access function to the first data value stored at each node. In a more general `Equation` element, such abstraction is essential, because different Elements will store the same variables in different locations.
Definition at line 189 of file young_laplace_contact_angle_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::value_pt().
u_local_eqn()
template<class ELEMENT >
int oomph::YoungLaplaceContactAngleElement< ELEMENT >::u_local_eqn (const unsigned & n) [inline]
Get the local equation number of the (one and only) unknown stored at local node n (returns -1 if value is pinned). Can be overloaded in derived multiphysics elements.
Definition at line 110 of file young_laplace_contact_angle_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals().
zeta_nodal()
template<class ELEMENT >
double oomph::YoungLaplaceContactAngleElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Specify the value of nodal zeta from the face geometry
Reimplemented from oomph::FaceElement.
Definition at line 122 of file young_laplace_contact_angle_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Prescribed_cos_gamma_pt
template<class ELEMENT >
double* oomph::YoungLaplaceContactAngleElement< ELEMENT >::Prescribed_cos_gamma_pt [private]
Pointer to prescribed cos gamma.
Definition at line 210 of file young_laplace_contact_angle_elements.h.
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::prescribed_cos_gamma_pt(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement().
The documentation for this class was generated from the following files:
young_laplace_contact_angle_elements.h
young_laplace_contact_angle_elements.cc