oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement Class Reference
#include <generalised_newtonian_Taxisym_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianAxisymmetricTTaylorHoodElement ()
Constructor, no internal data points.
GeneralisedNewtonianAxisymmetricTTaylorHoodElement (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement &dummy)
Broken copy constructor.
void operator= (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement &)
Broken assignment operator.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Test whether the pressure dof p_dof hanging or not?
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
unsigned p_index_axi_nst ()
Which nodal value represents the pressure?
int p_local_eqn (const unsigned &n) const
Pointer to n_p-th pressure node.
double p_axi_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
int p_nodal_index_axi_nst () const
Set the value at which the pressure is stored in the nodes.
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocities and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Protected Member Functions
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual double dpshape_and_dptest_eulerian_axi_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
void unpin_all_nodal_pressure_dofs ()
Unpin all pressure dofs.
void pin_all_nodal_pressure_dofs ()
Pin all nodal pressure dofs.
void unpin_proper_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
Static Protected Attributes
static const unsigned Pconv [] ={0,1,2}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue [] ={4,4,4,3,3,3}
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continous linear pressure interpolation
Definition at line 556 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianAxisymmetricTTaylorHoodElement() [1/2]
oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::GeneralisedNewtonianAxisymmetricTTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 626 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
GeneralisedNewtonianAxisymmetricTTaylorHoodElement() [2/2]
oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::GeneralisedNewtonianAxisymmetricTTaylorHoodElement (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement & dummy) [inline]
Broken copy constructor.
Definition at line 631 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dpshape_and_dptest_eulerian_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Definition at line 927 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_local(), oomph::FiniteElement::local_to_eulerian_mapping(), pshape_axi_nst(), and oomph::FiniteElement::transform_derivatives().
Referenced by dshape_and_dtest_eulerian_at_knot_axi_nst().
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
double oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 880 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by dshape_and_dtest_eulerian_axi_nst().
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
double oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 902 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References dpshape_and_dptest_eulerian_axi_nst(), and oomph::FiniteElement::dshape_eulerian_at_knot().
dshape_and_dtest_eulerian_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 858 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_at_knot_axi_nst(), and oomph::FiniteElement::dshape_eulerian().
Referenced by get_dof_numbers_for_unknowns().
fix_pressure()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::fix_pressure (const unsigned & p_dof, const double & p_value) [inline]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Definition at line 685 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data(), oomph::FiniteElement::node_pt(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Reimplemented from oomph::GeneralisedElement.
Definition at line 806 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::required_nvalue().
get_Z2_flux()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 752 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References i, and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate().
identify_load_data()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 201 of file generalised_newtonian_Taxisym_navier_stokes_elements.cc.
References i, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data(), identify_pressure_data(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by unpin_proper_nodal_pressure_dofs().
identify_pressure_data()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Add to the set paired_load_data pairs containing
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 229 of file generalised_newtonian_Taxisym_navier_stokes_elements.cc.
References oomph::FiniteElement::node_pt(), and oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::npres_axi_nst().
Referenced by identify_load_data().
ndof_types()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocities and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 795 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
npres_axi_nst()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::npres_axi_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 682 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
nrecovery_order()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 732 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
num_Z2_flux_terms()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 744 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 735 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
operator=()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::operator= (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement &) [inline]
Broken assignment operator.
Definition at line 639 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 713 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 717 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 722 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 726 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output().
p_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_axi_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 675 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value().
p_index_axi_nst()
unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_index_axi_nst () [inline]
Which nodal value represents the pressure?
Definition at line 663 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
p_local_eqn()
int oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_local_eqn (const unsigned & n) const [inline], [virtual]
Pointer to n_p-th pressure node.
Return the local equation numbers for the pressure values.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 670 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
p_nodal_index_axi_nst()
int oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_nodal_index_axi_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 679 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
pin_all_nodal_pressure_dofs()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs () [protected]
Pin all nodal pressure dofs.
Pin all nodal pressure dofs, incl the mid-face/side ones where they have been allocated (e.g. in the refineable version of this element).
Definition at line 161 of file generalised_newtonian_Taxisym_navier_stokes_elements.cc.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::pin(), and unpin_proper_nodal_pressure_dofs().
Referenced by unpin_all_nodal_pressure_dofs().
pshape_axi_nst() [1/2]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pshape_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Test whether the pressure dof p_dof hanging or not?
Pressure shape functions.
Pressure shape functions at local coordinate s
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 978 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
Referenced by dpshape_and_dptest_eulerian_axi_nst().
pshape_axi_nst() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 990 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::pshape_axi_nst().
required_nvalue()
virtual unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Definition at line 647 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::pshape_axi_nst(), and s.
unpin_all_nodal_pressure_dofs()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::unpin_all_nodal_pressure_dofs () [protected]
Unpin all pressure dofs.
Unpin all pressure dofs, incl the mid-face/side ones where they have been allocated (e.g. in the refineable version of this element).
Definition at line 141 of file generalised_newtonian_Taxisym_navier_stokes_elements.cc.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), pin_all_nodal_pressure_dofs(), and oomph::Data::unpin().
Referenced by oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data().
unpin_proper_nodal_pressure_dofs()
void oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::unpin_proper_nodal_pressure_dofs () [protected]
Unpin the proper nodal pressure dofs.
Unpin the proper nodal pressure dofs which are not hanging.
Definition at line 178 of file generalised_newtonian_Taxisym_navier_stokes_elements.cc.
References identify_load_data(), oomph::Node::is_hanging(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::npres_axi_nst(), and oomph::Data::unpin().
Referenced by pin_all_nodal_pressure_dofs().
vertex_node_pt()
Node* oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 739 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt().
Member Data Documentation
Initial_Nvalue
const unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::Initial_Nvalue ={4,4,4,3,3,3} [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 565 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
Referenced by oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data().
Pconv
const unsigned oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::Pconv ={0,1,2} [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 571 of file generalised_newtonian_Taxisym_navier_stokes_elements.h.
Referenced by oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_pressure_data().
The documentation for this class was generated from the following files:
generalised_newtonian_Taxisym_navier_stokes_elements.h
generalised_newtonian_Taxisym_navier_stokes_elements.cc