oomph::LowStorageRungeKutta< ORDER > Class Template Reference
#include <explicit_timesteppers.h>
Public Member Functions
LowStorageRungeKutta ()
Constructor, set the type.
LowStorageRungeKutta (const LowStorageRungeKutta &)
Broken copy constructor.
void operator= (const LowStorageRungeKutta &)
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance the solution by time dt.
template<>
LowStorageRungeKutta ()
template<>
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Pure virtual function that is used to advance time in the object.
Private Attributes
Vector< double > A
Vector< double > B
Vector< double > C
Additional Inherited Members
Detailed Description
template<unsigned ORDER>
class oomph::LowStorageRungeKutta< ORDER >
=========================================================== Runge Kutta Timestepping that uses low storage
Definition at line 243 of file explicit_timesteppers.h.
Constructor & Destructor Documentation
LowStorageRungeKutta() [1/3]
template<unsigned ORDER>
oomph::LowStorageRungeKutta< ORDER >::LowStorageRungeKutta ()
Constructor, set the type.
Definition at line 345 of file explicit_timesteppers.cc.
LowStorageRungeKutta() [2/3]
template<unsigned ORDER>
oomph::LowStorageRungeKutta< ORDER >::LowStorageRungeKutta (const LowStorageRungeKutta< ORDER > &) [inline]
Broken copy constructor.
Definition at line 254 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
LowStorageRungeKutta() [3/3]
template<>
oomph::LowStorageRungeKutta< 4 >::LowStorageRungeKutta ()
Definition at line 369 of file explicit_timesteppers.cc.
References oomph::OcTreeNames::B.
Member Function Documentation
operator=()
template<unsigned ORDER>
void oomph::LowStorageRungeKutta< ORDER >::operator= (const LowStorageRungeKutta< ORDER > &) [inline]
Broken assignment operator.
Definition at line 260 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
timestep() [1/2]
template<unsigned ORDER>
void oomph::LowStorageRungeKutta< ORDER >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Function that is used to advance the solution by time dt.
Broken default timestep for LowStorageRungeKutta.
Implements oomph::ExplicitTimeStepper.
Definition at line 354 of file explicit_timesteppers.cc.
timestep() [2/2]
template<>
void oomph::LowStorageRungeKutta< 4 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [virtual]
Pure virtual function that is used to advance time in the object.
Implements oomph::ExplicitTimeStepper.
Definition at line 399 of file explicit_timesteppers.cc.
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::OcTreeNames::B, oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), i, oomph::DistributableLinearAlgebraObject::nrow(), and oomph::ExplicitTimeSteppableObject::time().
Member Data Documentation
A
template<unsigned ORDER>
Vector<double> oomph::LowStorageRungeKutta< ORDER >::A [private]
Definition at line 246 of file explicit_timesteppers.h.
B
template<unsigned ORDER>
Vector<double> oomph::LowStorageRungeKutta< ORDER >::B [private]
Definition at line 246 of file explicit_timesteppers.h.
C
template<unsigned ORDER>
Vector<double> oomph::LowStorageRungeKutta< ORDER >::C [private]
Definition at line 246 of file explicit_timesteppers.h.
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc