oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > Class Template Reference
QGeneralisedAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
#include <gen_advection_diffusion_elements.h>
Public Member Functions
QGeneralisedAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QGeneralisedAdvectionDiffusionElement (const QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_cons_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_cons_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >
QGeneralisedAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 596 of file gen_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QGeneralisedAdvectionDiffusionElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::QGeneralisedAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 612 of file gen_advection_diffusion_elements.h.
QGeneralisedAdvectionDiffusionElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::QGeneralisedAdvectionDiffusionElement (const QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 617 of file gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_cons_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 747 of file gen_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_cons_adv_diff().
dshape_and_dtest_eulerian_cons_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_cons_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 713 of file gen_advection_diffusion_elements.h.
References oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_adv_diff(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct().
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::operator= (const QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 624 of file gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 636 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 641 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 647 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 654 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 661 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 670 of file gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_at_knot_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::dshape_and_dtest_eulerian_cons_adv_diff(), oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 631 of file gen_advection_diffusion_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 605 of file gen_advection_diffusion_elements.h.
The documentation for this class was generated from the following files:
gen_advection_diffusion_elements.h
gen_advection_diffusion_elements.cc