oomph::RefineableLinearisedNavierStokesEquations Class Reference
Refineable version of the linearised axisymmetric Navier--Stokes equations.
#include <refineable_linearised_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build: pass the pointers down to the sons.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement *> &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement *> &element_pt)
Unpin all pressure dofs in elements listed in Vector.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Private Member Functions
void fill_in_generic_residual_contribution_linearised_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
Refineable version of the linearised axisymmetric Navier--Stokes equations.
Definition at line 52 of file refineable_linearised_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableLinearisedNavierStokesEquations()
oomph::RefineableLinearisedNavierStokesEquations::RefineableLinearisedNavierStokesEquations () [inline]
Empty Constructor.
Definition at line 73 of file refineable_linearised_navier_stokes_elements.h.
Member Function Documentation
fill_in_generic_residual_contribution_linearised_nst()
void oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [private], [virtual]
Add element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Compute the residuals for the refineable linearised axisymmetric Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 45 of file refineable_linearised_navier_stokes_elements.cc.
References oomph::LinearisedNavierStokesEquations::density_ratio(), oomph::LinearisedNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_nst(), oomph::LinearisedNavierStokesEquations::eigenvalue_local_eqn(), oomph::LinearisedNavierStokesEquations::Gamma, oomph::LinearisedNavierStokesEquations::get_base_flow_dudx(), oomph::LinearisedNavierStokesEquations::get_base_flow_u(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::LinearisedNavierStokesEquations::lambda(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::LinearisedNavierStokesEquations::npres_linearised_nst(), oomph::Integral::nweight(), oomph::LinearisedNavierStokesEquations::omega(), oomph::LinearisedNavierStokesEquations::p_index_linearised_nst(), oomph::LinearisedNavierStokesEquations::p_linearised_nst(), oomph::LinearisedNavierStokesEquations::p_local_eqn(), pressure_node_pt(), oomph::LinearisedNavierStokesEquations::pshape_linearised_nst(), oomph::LinearisedNavierStokesEquations::re(), oomph::LinearisedNavierStokesEquations::re_st(), s, oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), oomph::LinearisedNavierStokesEquations::u_index_linearised_nst(), oomph::LinearisedNavierStokesEquations::viscosity_ratio(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by unpin_all_pressure_dofs().
further_build()
void oomph::RefineableLinearisedNavierStokesEquations::further_build () [inline], [virtual]
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableLinearisedQCrouzeixRaviartElement.
Definition at line 150 of file refineable_linearised_navier_stokes_elements.h.
References oomph::LinearisedNavierStokesEquations::ALE_is_disabled, oomph::LinearisedNavierStokesEquations::Density_Ratio_pt, oomph::LinearisedNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::LinearisedNavierStokesEquations::normalisation_element_pt(), oomph::LinearisedNavierStokesEquations::Re_pt, oomph::LinearisedNavierStokesEquations::re_pt(), oomph::LinearisedNavierStokesEquations::re_st_pt(), oomph::LinearisedNavierStokesEquations::ReSt_pt, oomph::LinearisedNavierStokesEquations::set_eigenfunction_normalisation_element(), oomph::LinearisedNavierStokesEquations::Viscosity_Ratio_pt, and oomph::LinearisedNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build().
get_Z2_flux()
void oomph::RefineableLinearisedNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 87 of file refineable_linearised_navier_stokes_elements.h.
References i, and oomph::LinearisedNavierStokesEquations::strain_rate().
num_Z2_flux_terms()
unsigned oomph::RefineableLinearisedNavierStokesEquations::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 79 of file refineable_linearised_navier_stokes_elements.h.
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineableLinearisedNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableLinearisedQTaylorHoodElement.
Definition at line 68 of file refineable_linearised_navier_stokes_elements.h.
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineableLinearisedNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableLinearisedNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 191 of file refineable_linearised_navier_stokes_elements.h.
References e, and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt()
virtual Node* oomph::RefineableLinearisedNavierStokesEquations::pressure_node_pt (const unsigned & n_p) [inline], [protected], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableLinearisedQTaylorHoodElement.
Definition at line 61 of file refineable_linearised_navier_stokes_elements.h.
References unpin_elemental_pressure_dofs().
Referenced by fill_in_generic_residual_contribution_linearised_nst().
unpin_all_pressure_dofs()
static void oomph::RefineableLinearisedNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement *> & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in Vector.
Definition at line 205 of file refineable_linearised_navier_stokes_elements.h.
References e, fill_in_generic_residual_contribution_linearised_nst(), and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineableLinearisedNavierStokesEquations::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableLinearisedQTaylorHoodElement, and oomph::RefineableLinearisedQCrouzeixRaviartElement.
Referenced by pressure_node_pt(), and unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_linearised_navier_stokes_elements.h
refineable_linearised_navier_stokes_elements.cc