oomph::RefineableAxisymAdvectionDiffusionEquations Class Reference
A version of the Advection Diffusion in axisym coordinates equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_axisym_advection_diffusion_elements.h>
Public Member Functions
RefineableAxisymAdvectionDiffusionEquations ()
Empty Constructor.
RefineableAxisymAdvectionDiffusionEquations (const RefineableAxisymAdvectionDiffusionEquations &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: Copy source function pointer from father element.
void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Protected Member Functions
void fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
A version of the Advection Diffusion in axisym coordinates equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 59 of file refineable_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableAxisymAdvectionDiffusionEquations() [1/2]
oomph::RefineableAxisymAdvectionDiffusionEquations::RefineableAxisymAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 67 of file refineable_axisym_advection_diffusion_elements.h.
RefineableAxisymAdvectionDiffusionEquations() [2/2]
oomph::RefineableAxisymAdvectionDiffusionEquations::RefineableAxisymAdvectionDiffusionEquations (const RefineableAxisymAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file refineable_axisym_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dinterpolated_u_adv_diff_ddata()
void oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Definition at line 210 of file refineable_axisym_advection_diffusion_elements.h.
References oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), fill_in_generic_residual_contribution_axi_adv_diff(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff().
fill_in_generic_residual_contribution_axi_adv_diff()
void oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
Definition at line 43 of file refineable_axisym_advection_diffusion_elements.cc.
References oomph::AxisymAdvectionDiffusionEquations::ALE_is_disabled, oomph::FiniteElement::dnodal_position_dt(), oomph::AxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::get_source_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::get_wind_axi_adv_diff(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::AxisymAdvectionDiffusionEquations::pe(), oomph::AxisymAdvectionDiffusionEquations::pe_st(), s, oomph::Data::time_stepper_pt(), oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by dinterpolated_u_adv_diff_ddata().
further_build()
void oomph::RefineableAxisymAdvectionDiffusionEquations::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 188 of file refineable_axisym_advection_diffusion_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::AxisymAdvectionDiffusionEquations::pe_pt(), oomph::AxisymAdvectionDiffusionEquations::Pe_pt, oomph::AxisymAdvectionDiffusionEquations::pe_st_pt(), oomph::AxisymAdvectionDiffusionEquations::PeSt_pt, oomph::AxisymAdvectionDiffusionEquations::source_fct_pt(), oomph::AxisymAdvectionDiffusionEquations::Source_fct_pt, oomph::AxisymAdvectionDiffusionEquations::wind_fct_pt(), and oomph::AxisymAdvectionDiffusionEquations::Wind_fct_pt.
geometric_jacobian()
double oomph::RefineableAxisymAdvectionDiffusionEquations::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
Definition at line 184 of file refineable_axisym_advection_diffusion_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 104 of file refineable_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff().
Referenced by get_interpolated_values().
get_interpolated_values() [2/2]
void oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 135 of file refineable_axisym_advection_diffusion_elements.h.
References get_interpolated_values(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), oomph::Global_string_for_annotation::string(), and oomph::AxisymAdvectionDiffusionEquations::u_index_axi_adv_diff().
get_Z2_flux()
void oomph::RefineableAxisymAdvectionDiffusionEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 96 of file refineable_axisym_advection_diffusion_elements.h.
References oomph::AxisymAdvectionDiffusionEquations::get_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableAxisymAdvectionDiffusionEquations::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 92 of file refineable_axisym_advection_diffusion_elements.h.
The documentation for this class was generated from the following files:
refineable_axisym_advection_diffusion_elements.h
refineable_axisym_advection_diffusion_elements.cc