oomph::DisplacementBasedFoepplvonKarmanEquations Class Reference
#include <displacement_based_foeppl_von_karman_elements.h>
Public Types
typedef void(* FoepplvonKarmanPressureFctPt) (const Vector< double > &x, double &f)
Function pointer to pressure function fct(x,f(x)) -- x is a Vector!
typedef void(* FoepplvonKarmanTractionFctPt) (const Vector< double > &x, Vector< double > &f)
Function pointer to traction function fct(x,f(x)) -- x is a Vector!
Public Member Functions
DisplacementBasedFoepplvonKarmanEquations ()
Constructor (must initialise the Pressure_fct_pt and the Traction_fct_pt. Also set physical parameters to their default values.
DisplacementBasedFoepplvonKarmanEquations (const DisplacementBasedFoepplvonKarmanEquations &dummy)
Broken copy constructor.
void operator= (const DisplacementBasedFoepplvonKarmanEquations &)
Broken assignment operator.
const double & nu () const
Poisson's ratio.
double *& nu_pt ()
Pointer to Poisson's ratio.
const double & eta () const
Eta.
double *& eta_pt ()
Pointer to eta.
virtual unsigned nodal_index_fvk (const unsigned &i=0) const
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: w 1: laplacian w 2: u_x 3: u_y In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,w at n_plot^DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,w at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,w_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,w_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
FoepplvonKarmanPressureFctPt & pressure_fct_pt ()
Access function: Pointer to pressure function.
FoepplvonKarmanPressureFctPt pressure_fct_pt () const
Access function: Pointer to pressure function. Const version.
FoepplvonKarmanTractionFctPt & traction_fct_pt ()
Access function: Pointer to in-plane traction function.
FoepplvonKarmanTractionFctPt traction_fct_pt () const
Access function: Pointer to in-plane traction function. Const version.
virtual void get_pressure_fvk (const unsigned &ipt, const Vector< double > &x, double &pressure) const
Get pressure term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
virtual void get_traction_fvk (Vector< double > &x, Vector< double > &traction) const
Get in-plane traction term at (Eulerian) position x.
void get_gradient_of_deflection (const Vector< double > &s, Vector< double > &gradient) const
Get gradient of deflection: gradient[i] = dw/dx_i.
void get_gradient_of_field (const Vector< double > &s, Vector< double > &gradient, const unsigned &index) const
Get gradient of field: gradient[i] = d[.]/dx_i,.
void get_sigma (DenseMatrix< double > &sigma, const Vector< double > &interpolated_dwdx, const Vector< double > &interpolated_duxdx, const Vector< double > &interpolated_duydx)
void get_stress_and_strain_for_output (const Vector< double > &s, DenseMatrix< double > &sigma, DenseMatrix< double > &strain)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
hierher dummy
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals with this element's contribution.
double interpolated_w_fvk (const Vector< double > &s, unsigned index=0) const
Return FE representation of function value w_fvk(s) at local coordinate s (by default - if index > 0, returns FE representation of valued stored at index^th nodal index.
unsigned self_test ()
Self-test: Return 0 for OK.
void use_linear_bending_model ()
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Attributes
double * Nu_pt
Pointer to global Poisson's ratio.
double * Eta_pt
Pointer to global eta.
FoepplvonKarmanPressureFctPt Pressure_fct_pt
Pointer to pressure function:
FoepplvonKarmanTractionFctPt Traction_fct_pt
Pointer to traction function:
Private Attributes
bool Linear_bending_model
Flag which stores whether we are using a linear, pure bending model instead of the full non-linear Foeppl-von Karman.
Static Private Attributes
static double Default_Nu_Value = 0.5
Default value for Poisson's ratio.
static double Default_Physical_Constant_Value
Default value for physical constants.
Additional Inherited Members
Detailed Description
A class for all isoparametric elements that solve the Foeppl von Karman equations.
 \nabla^4 w - \eta \frac{\partial}{\partial x_{\beta}} \left( \sigma^{\alpha \beta} \frac{\partial w}{\partial x_{\alpha}} \right) = p(x,y) 
 and
 \frac{\sigma^{\alpha \beta}}{\partial x_{\beta}} = \tau_\alpha 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 67 of file displacement_based_foeppl_von_karman_elements.h.
Member Typedef Documentation
FoepplvonKarmanPressureFctPt
typedef void(* oomph::DisplacementBasedFoepplvonKarmanEquations::FoepplvonKarmanPressureFctPt) (const Vector< double > &x, double &f)
Function pointer to pressure function fct(x,f(x)) -- x is a Vector!
Definition at line 74 of file displacement_based_foeppl_von_karman_elements.h.
FoepplvonKarmanTractionFctPt
typedef void(* oomph::DisplacementBasedFoepplvonKarmanEquations::FoepplvonKarmanTractionFctPt) (const Vector< double > &x, Vector< double > &f)
Function pointer to traction function fct(x,f(x)) -- x is a Vector!
Definition at line 79 of file displacement_based_foeppl_von_karman_elements.h.
Constructor & Destructor Documentation
DisplacementBasedFoepplvonKarmanEquations() [1/2]
oomph::DisplacementBasedFoepplvonKarmanEquations::DisplacementBasedFoepplvonKarmanEquations () [inline]
Constructor (must initialise the Pressure_fct_pt and the Traction_fct_pt. Also set physical parameters to their default values.
Definition at line 85 of file displacement_based_foeppl_von_karman_elements.h.
References Default_Nu_Value, Default_Physical_Constant_Value, Eta_pt, Linear_bending_model, and Nu_pt.
DisplacementBasedFoepplvonKarmanEquations() [2/2]
oomph::DisplacementBasedFoepplvonKarmanEquations::DisplacementBasedFoepplvonKarmanEquations (const DisplacementBasedFoepplvonKarmanEquations & dummy) [inline]
Broken copy constructor.
Definition at line 99 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error() [1/2]
void oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 242 of file displacement_based_foeppl_von_karman_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by output_fct().
compute_error() [2/2]
void oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 183 of file displacement_based_foeppl_von_karman_elements.h.
dshape_and_dtest_eulerian_at_knot_fvk()
virtual double oomph::DisplacementBasedFoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Referenced by fill_in_contribution_to_residuals(), and use_linear_bending_model().
dshape_and_dtest_eulerian_fvk()
virtual double oomph::DisplacementBasedFoepplvonKarmanEquations::dshape_and_dtest_eulerian_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Referenced by oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field(), and use_linear_bending_model().
eta()
const double& oomph::DisplacementBasedFoepplvonKarmanEquations::eta () const [inline]
Eta.
Definition at line 117 of file displacement_based_foeppl_von_karman_elements.h.
References Eta_pt.
Referenced by fill_in_contribution_to_residuals().
eta_pt()
double* & oomph::DisplacementBasedFoepplvonKarmanEquations::eta_pt () [inline]
Pointer to eta.
Definition at line 120 of file displacement_based_foeppl_von_karman_elements.h.
References Eta_pt.
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
hierher dummy
Reimplemented from oomph::GeneralisedElement.
Definition at line 439 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::fill_in_contribution_to_jacobian(), i, oomph::GeneralisedElement::ndof(), and oomph::DenseMatrix< T >::nrow().
fill_in_contribution_to_residuals()
void oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the residuals with this element's contribution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 462 of file displacement_based_foeppl_von_karman_elements.h.
References dshape_and_dtest_eulerian_at_knot_fvk(), eta(), get_pressure_fvk(), get_sigma(), get_traction_fvk(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_gradient_of_deflection()
void oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_deflection (const Vector< double > & s, Vector< double > & gradient) const [inline]
Get gradient of deflection: gradient[i] = dw/dx_i.
Definition at line 243 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), nodal_index_fvk(), and oomph::FiniteElement::nodal_value().
Referenced by oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_Z2_flux().
get_gradient_of_field()
void oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_field (const Vector< double > & s, Vector< double > & gradient, const unsigned & index) const [inline]
Get gradient of field: gradient[i] = d[.]/dx_i,.
Definition at line 287 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), nodal_index_fvk(), and oomph::FiniteElement::nodal_value().
get_pressure_fvk()
virtual void oomph::DisplacementBasedFoepplvonKarmanEquations::get_pressure_fvk (const unsigned & ipt, const Vector< double > & x, double & pressure) const [inline], [virtual]
Get pressure term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
Definition at line 212 of file displacement_based_foeppl_von_karman_elements.h.
References Pressure_fct_pt.
Referenced by fill_in_contribution_to_residuals().
get_sigma()
void oomph::DisplacementBasedFoepplvonKarmanEquations::get_sigma (DenseMatrix< double > & sigma, const Vector< double > & interpolated_dwdx, const Vector< double > & interpolated_duxdx, const Vector< double > & interpolated_duydx) [inline]
Get the in-plane stress (sigma) as a fct of the pre=computed displcement derivatives
Definition at line 328 of file displacement_based_foeppl_von_karman_elements.h.
References nu().
Referenced by fill_in_contribution_to_residuals(), and get_stress_and_strain_for_output().
get_stress_and_strain_for_output()
void oomph::DisplacementBasedFoepplvonKarmanEquations::get_stress_and_strain_for_output (const Vector< double > & s, DenseMatrix< double > & sigma, DenseMatrix< double > & strain) [inline]
Definition at line 359 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::dshape_eulerian(), get_sigma(), oomph::FiniteElement::nnode(), nodal_index_fvk(), and oomph::FiniteElement::nodal_value().
Referenced by output().
get_traction_fvk()
virtual void oomph::DisplacementBasedFoepplvonKarmanEquations::get_traction_fvk (Vector< double > & x, Vector< double > & traction) const [inline], [virtual]
Get in-plane traction term at (Eulerian) position x.
Definition at line 226 of file displacement_based_foeppl_von_karman_elements.h.
References Traction_fct_pt.
Referenced by fill_in_contribution_to_residuals().
interpolated_w_fvk()
double oomph::DisplacementBasedFoepplvonKarmanEquations::interpolated_w_fvk (const Vector< double > & s, unsigned index = 0) const [inline]
Return FE representation of function value w_fvk(s) at local coordinate s (by default - if index > 0, returns FE representation of valued stored at index^th nodal index.
Definition at line 654 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), self_test(), and oomph::FiniteElement::shape().
Referenced by compute_error(), and output().
nodal_index_fvk()
virtual unsigned oomph::DisplacementBasedFoepplvonKarmanEquations::nodal_index_fvk (const unsigned & i = 0) const [inline], [virtual]
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: w 1: laplacian w 2: u_x 3: u_y In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 132 of file displacement_based_foeppl_von_karman_elements.h.
References i.
Referenced by fill_in_contribution_to_residuals(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), get_gradient_of_deflection(), get_gradient_of_field(), get_stress_and_strain_for_output(), interpolated_w_fvk(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::local_equation(), and use_linear_bending_model().
nu()
const double& oomph::DisplacementBasedFoepplvonKarmanEquations::nu () const [inline]
Poisson's ratio.
Definition at line 111 of file displacement_based_foeppl_von_karman_elements.h.
References Nu_pt.
Referenced by get_sigma().
nu_pt()
double* & oomph::DisplacementBasedFoepplvonKarmanEquations::nu_pt () [inline]
Pointer to Poisson's ratio.
Definition at line 114 of file displacement_based_foeppl_von_karman_elements.h.
References Nu_pt.
operator=()
void oomph::DisplacementBasedFoepplvonKarmanEquations::operator= (const DisplacementBasedFoepplvonKarmanEquations &) [inline]
Broken assignment operator.
Definition at line 105 of file displacement_based_foeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
void oomph::DisplacementBasedFoepplvonKarmanEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 135 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by output(), and oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output().
output() [2/4]
void oomph::DisplacementBasedFoepplvonKarmanEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,w at n_plot^DIM plot points.
Output function:
x,y,w
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 82 of file displacement_based_foeppl_von_karman_elements.cc.
References oomph::FiniteElement::get_s_plot(), get_stress_and_strain_for_output(), i, interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::DisplacementBasedFoepplvonKarmanEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 146 of file displacement_based_foeppl_von_karman_elements.h.
References output(), and output_fct().
output() [4/4]
void oomph::DisplacementBasedFoepplvonKarmanEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,w at n_plot^DIM plot points.
C-style output function:
x,y,w
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 150 of file displacement_based_foeppl_von_karman_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,w_exact at n_plot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,w_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 187 of file displacement_based_foeppl_von_karman_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output(), and oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output_fct().
output_fct() [2/2]
virtual void oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: x,y,w_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >.
Definition at line 163 of file displacement_based_foeppl_von_karman_elements.h.
References compute_error().
pressure_fct_pt() [1/2]
FoepplvonKarmanPressureFctPt& oomph::DisplacementBasedFoepplvonKarmanEquations::pressure_fct_pt () [inline]
Access function: Pointer to pressure function.
Definition at line 195 of file displacement_based_foeppl_von_karman_elements.h.
References Pressure_fct_pt.
pressure_fct_pt() [2/2]
FoepplvonKarmanPressureFctPt oomph::DisplacementBasedFoepplvonKarmanEquations::pressure_fct_pt () const [inline]
Access function: Pointer to pressure function. Const version.
Definition at line 198 of file displacement_based_foeppl_von_karman_elements.h.
References Pressure_fct_pt.
self_test()
unsigned oomph::DisplacementBasedFoepplvonKarmanEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 52 of file displacement_based_foeppl_von_karman_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by interpolated_w_fvk().
traction_fct_pt() [1/2]
FoepplvonKarmanTractionFctPt& oomph::DisplacementBasedFoepplvonKarmanEquations::traction_fct_pt () [inline]
Access function: Pointer to in-plane traction function.
Definition at line 202 of file displacement_based_foeppl_von_karman_elements.h.
References Traction_fct_pt.
traction_fct_pt() [2/2]
FoepplvonKarmanTractionFctPt oomph::DisplacementBasedFoepplvonKarmanEquations::traction_fct_pt () const [inline]
Access function: Pointer to in-plane traction function. Const version.
Definition at line 205 of file displacement_based_foeppl_von_karman_elements.h.
References Traction_fct_pt.
use_linear_bending_model()
void oomph::DisplacementBasedFoepplvonKarmanEquations::use_linear_bending_model () [inline]
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case.
Definition at line 686 of file displacement_based_foeppl_von_karman_elements.h.
References dshape_and_dtest_eulerian_at_knot_fvk(), dshape_and_dtest_eulerian_fvk(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::node_pt(), oomph::Data::pin(), and s.
Member Data Documentation
Default_Nu_Value
double oomph::DisplacementBasedFoepplvonKarmanEquations::Default_Nu_Value = 0.5 [static], [private]
Default value for Poisson's ratio.
Definition at line 752 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by DisplacementBasedFoepplvonKarmanEquations().
Default_Physical_Constant_Value
double oomph::DisplacementBasedFoepplvonKarmanEquations::Default_Physical_Constant_Value [static], [private]
Default value for physical constants.
Definition at line 755 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by DisplacementBasedFoepplvonKarmanEquations().
Eta_pt
double* oomph::DisplacementBasedFoepplvonKarmanEquations::Eta_pt [protected]
Pointer to global eta.
Definition at line 741 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by DisplacementBasedFoepplvonKarmanEquations(), eta(), and eta_pt().
Linear_bending_model
bool oomph::DisplacementBasedFoepplvonKarmanEquations::Linear_bending_model [private]
Flag which stores whether we are using a linear, pure bending model instead of the full non-linear Foeppl-von Karman.
Definition at line 759 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by DisplacementBasedFoepplvonKarmanEquations(), fill_in_contribution_to_residuals(), and use_linear_bending_model().
Nu_pt
double* oomph::DisplacementBasedFoepplvonKarmanEquations::Nu_pt [protected]
Pointer to global Poisson's ratio.
Definition at line 738 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by DisplacementBasedFoepplvonKarmanEquations(), nu(), and nu_pt().
Pressure_fct_pt
FoepplvonKarmanPressureFctPt oomph::DisplacementBasedFoepplvonKarmanEquations::Pressure_fct_pt [protected]
Pointer to pressure function:
Definition at line 744 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by get_pressure_fvk(), and pressure_fct_pt().
Traction_fct_pt
FoepplvonKarmanTractionFctPt oomph::DisplacementBasedFoepplvonKarmanEquations::Traction_fct_pt [protected]
Pointer to traction function:
Definition at line 747 of file displacement_based_foeppl_von_karman_elements.h.
Referenced by get_traction_fvk(), and traction_fct_pt().
The documentation for this class was generated from the following files:
displacement_based_foeppl_von_karman_elements.h
displacement_based_foeppl_von_karman_elements.cc