oomph::HangInfo Class Reference
Class that contains data for hanging nodes.
#include <nodes.h>
Public Member Functions
HangInfo ()
Default constructor, initialise vectors to have size zero.
HangInfo (const unsigned &n_master)
Alternative constructor when the number of master nodes is known.
~HangInfo ()
Delete the storage.
HangInfo (const HangInfo &)
Broken copy constructor.
void operator= (const HangInfo &)
Broken assignment operator.
unsigned nmaster () const
Return the number of master nodes.
Node *const & master_node_pt (const unsigned &i) const
Return a pointer to the i-th master node.
double const & master_weight (const unsigned &i) const
Return weight for dofs on i-th master node.
void set_master_node_pt (const unsigned &i, Node *const &master_node_pt, const double &weight)
Set the pointer to the i-th master node and its weight.
void add_master_node_pt (Node *const &master_node_pt, const double &weight)
Add (pointer to) master node and corresponding weight to the internally stored (pointers to) master nodes and weights.
Private Member Functions
void range_check (const unsigned &i) const
Check that the argument is within the range of stored data values.
Private Attributes
Node ** Master_nodes_pt
C-style array of pointers to nodes that this hanging node depends on.
double * Master_weights
C-style array of weights for the dofs on the master nodes.
unsigned Nmaster
Number of master nodes required by this hanging node.
Detailed Description
Class that contains data for hanging nodes.
To ensure inter-element continuity, the values and nodal positions of hanging nodes must be linear combinations of the values and positions on certain adjacent `master` nodes. For every hanging node $ J $ ,
 {\bf U}_J = \sum_{K} {\bf U}_{K} \omega_{JK} 
 and
 {\bf X}_J = \sum_{K} {\bf X}_{K} \omega_{JK} 
, where $ {\bf U}_I $ and $ {\bf U}_I $ are Vectors containing the nodal values and positions of node $ I $ respectively; the sum is taken over the hanging node's master nodes $ K $ and $ \omega_{JK} $ are suitable weights. This class provides storage and access functions for the pointers to the master nodes and their associated weights.
Definition at line 684 of file nodes.h.
Constructor & Destructor Documentation
HangInfo() [1/3]
oomph::HangInfo::HangInfo () [inline]
Default constructor, initialise vectors to have size zero.
Definition at line 689 of file nodes.h.
References oomph::LeakCheckNames::HangInfo_build.
HangInfo() [2/3]
oomph::HangInfo::HangInfo (const unsigned & n_master) [inline]
Alternative constructor when the number of master nodes is known.
Definition at line 697 of file nodes.h.
References oomph::LeakCheckNames::HangInfo_build.
 HangInfo()
oomph::HangInfo::~HangInfo () [inline]
Delete the storage.
Definition at line 707 of file nodes.h.
References oomph::LeakCheckNames::HangInfo_build.
HangInfo() [3/3]
oomph::HangInfo::HangInfo (const HangInfo &) [inline]
Broken copy constructor.
Definition at line 721 of file nodes.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
add_master_node_pt()
void oomph::HangInfo::add_master_node_pt (Node *const & master_node_pt_, const double & weight)
Add (pointer to) master node and corresponding weight to the internally stored (pointers to) master nodes and weights.
Add (pointer to) master node and corresponding weight to the internally stored (pointers to) master nodes and weights.
Definition at line 1432 of file nodes.cc.
References i.
master_node_pt()
Node* const& oomph::HangInfo::master_node_pt (const unsigned & i) const [inline]
Return a pointer to the i-th master node.
Definition at line 736 of file nodes.h.
References i, and oomph::Data::range_check().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::Mesh::check_halo_schemes(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively(), oomph::Mesh::delete_all_external_storage(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::RefineableSolidElement::geom_data_pt(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::RefineableSolidElement::identify_geometric_data(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::identify_geometric_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), oomph::RefineablePolarCrouzeixRaviartElement::insert_load_data(), oomph::SolidNode::lagrangian_position(), oomph::SolidNode::lagrangian_position_gen(), oomph::RefineableSolidElement::ngeom_data(), oomph::Mesh::node_update(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::MGSolver< DIM >::plot(), oomph::Node::position(), oomph::Node::position_gen(), oomph::Missing_masters_functions::recursively_add_masters_of_external_haloed_node(), oomph::Multi_domain_functions::recursively_add_masters_of_external_haloed_node(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::Problem::remove_duplicate_data(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices(), oomph::MGSolver< DIM >::setup_interpolation_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes(), and oomph::Node::value().
master_weight()
double const& oomph::HangInfo::master_weight (const unsigned & i) const [inline]
Return weight for dofs on i-th master node.
Definition at line 753 of file nodes.h.
References i, and oomph::Data::range_check().
Referenced by oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SolidNode::lagrangian_position(), oomph::SolidNode::lagrangian_position_gen(), oomph::Mesh::node_update(), oomph::AlgebraicMesh::node_update(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::MGSolver< DIM >::plot(), oomph::Node::position(), oomph::Node::position_gen(), oomph::Missing_masters_functions::recursively_add_masters_of_external_haloed_node(), oomph::Multi_domain_functions::recursively_add_masters_of_external_haloed_node(), oomph::RefineableSolidTractionElement< ELEMENT >::refineable_fill_in_contribution_to_residuals_solid_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::Problem::remove_duplicate_data(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices(), oomph::MGSolver< DIM >::setup_interpolation_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes(), and oomph::Node::value().
nmaster()
unsigned oomph::HangInfo::nmaster () const [inline]
Return the number of master nodes.
Definition at line 733 of file nodes.h.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::additional_synchronise_hanging_nodes(), oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::Mesh::check_halo_schemes(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively(), oomph::Mesh::delete_all_external_storage(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM, PML_ELEMENT >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::RefineableSolidElement::geom_data_pt(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_mass_matrix_diagonal(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::RefineableSolidElement::identify_geometric_data(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::identify_geometric_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), oomph::RefineablePolarCrouzeixRaviartElement::insert_load_data(), oomph::SolidNode::lagrangian_position(), oomph::SolidNode::lagrangian_position_gen(), oomph::RefineableSolidElement::ngeom_data(), oomph::MacroElementNodeUpdateNode::node_update(), oomph::Mesh::node_update(), oomph::AlgebraicMesh::node_update(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::MGSolver< DIM >::plot(), oomph::Node::position(), oomph::Node::position_gen(), oomph::Missing_masters_functions::recursively_add_masters_of_external_haloed_node(), oomph::Multi_domain_functions::recursively_add_masters_of_external_haloed_node(), oomph::RefineableSolidTractionElement< ELEMENT >::refineable_fill_in_contribution_to_residuals_solid_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::Problem::remove_duplicate_data(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices(), oomph::MGSolver< DIM >::setup_interpolation_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes(), and oomph::Node::value().
operator=()
void oomph::HangInfo::operator= (const HangInfo &) [inline]
Broken assignment operator.
Definition at line 727 of file nodes.h.
References oomph::BrokenCopy::broken_assign().
range_check()
void oomph::HangInfo::range_check (const unsigned & i) const [private]
Check that the argument is within the range of stored data values.
Check that the argument is within the range of stored master nodes
Definition at line 1397 of file nodes.cc.
set_master_node_pt()
void oomph::HangInfo::set_master_node_pt (const unsigned & i, Node *const & master_node_pt, const double & weight)
Set the pointer to the i-th master node and its weight.
Definition at line 1417 of file nodes.cc.
References i, and oomph::Data::range_check().
Referenced by oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::RefineableQElement< 2 >::quad_hang_helper(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper(), oomph::Missing_masters_functions::recursively_add_masters_of_external_halo_node_to_storage(), oomph::Multi_domain_functions::recursively_add_masters_of_external_halo_node_to_storage(), and oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes().
Member Data Documentation
Master_nodes_pt
Node* * oomph::HangInfo::Master_nodes_pt [private]
C-style array of pointers to nodes that this hanging node depends on.
Definition at line 784 of file nodes.h.
Master_weights
double* oomph::HangInfo::Master_weights [private]
C-style array of weights for the dofs on the master nodes.
Definition at line 787 of file nodes.h.
Nmaster
unsigned oomph::HangInfo::Nmaster [private]
Number of master nodes required by this hanging node.
Definition at line 790 of file nodes.h.
The documentation for this class was generated from the following files:
nodes.h
nodes.cc