oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > Class Template Reference
#include <Tpml_fourier_decomposed_helmholtz_elements.h>
Public Member Functions
TPMLFourierDecomposedHelmholtzElement ()
Constructor: Call constructors for TElement and PMLFourierDecomposedHelmholtz equations.
TPMLFourierDecomposedHelmholtzElement (const TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: r,z,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 2
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D, class PML_ELEMENT>
class oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >
TPMLFourierDecomposedHelmholtzElement<NNODE_1D> elements are isoparametric triangular PMLFourierDecomposedHelmholtz elements with NNODE_1D nodal points along each element edge. Inherits from TElement and PMLFourierDecomposedHelmholtzEquations
Definition at line 67 of file Tpml_fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
TPMLFourierDecomposedHelmholtzElement() [1/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::TPMLFourierDecomposedHelmholtzElement () [inline]
Constructor: Call constructors for TElement and PMLFourierDecomposedHelmholtz equations.
Definition at line 77 of file Tpml_fourier_decomposed_helmholtz_elements.h.
TPMLFourierDecomposedHelmholtzElement() [2/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::TPMLFourierDecomposedHelmholtzElement (const TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 83 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D, class PML_ELEMENT >
double oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLFourierDecomposedHelmholtzEquationsBase.
Definition at line 264 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz(), and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct().
dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D, class PML_ELEMENT >
double oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLFourierDecomposedHelmholtzEquationsBase.
Definition at line 229 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct().
get_Z2_flux()
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux from UnsteadyHeat equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 187 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::PMLFourierDecomposedHelmholtzEquationsBase::get_flux(), and i.
nrecovery_order()
template<unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 180 of file Tpml_fourier_decomposed_helmholtz_elements.h.
num_Z2_flux_terms()
template<unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 183 of file Tpml_fourier_decomposed_helmholtz_elements.h.
nvertex_node()
template<unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 200 of file Tpml_fourier_decomposed_helmholtz_elements.h.
output() [1/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::TElement< 2, NNODE_1D >.
Definition at line 106 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u n_plot^2 plot points.
Reimplemented from oomph::TElement< 2, NNODE_1D >.
Definition at line 113 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u or x,y,z,u.
Reimplemented from oomph::TElement< 2, NNODE_1D >.
Definition at line 121 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::TElement< 2, NNODE_1D >.
Definition at line 129 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output_fct() [1/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact.
Reimplemented from oomph::FiniteElement.
Definition at line 137 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Reimplemented from oomph::FiniteElement.
Definition at line 147 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz(), oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::output_fct(), and s.
required_nvalue()
template<unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 2)
Reimplemented from oomph::FiniteElement.
Definition at line 101 of file Tpml_fourier_decomposed_helmholtz_elements.h.
References oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::Initial_Nvalue.
vertex_node_pt()
template<unsigned NNODE_1D, class PML_ELEMENT>
Node* oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 204 of file Tpml_fourier_decomposed_helmholtz_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D, class PML_ELEMENT>
const unsigned oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::Initial_Nvalue = 2 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
(real and imag part) in every case
Definition at line 210 of file Tpml_fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::required_nvalue().
The documentation for this class was generated from the following files:
Tpml_fourier_decomposed_helmholtz_elements.h
Tpml_fourier_decomposed_helmholtz_elements.cc