oomph::TangentiallyDiscontinuousConformal2DPMLElement Class Reference
#include <pml_elements.h>
Classes
struct TwoDimRip
Information about a rip in two dimensions.
Public Member Functions
TangentiallyDiscontinuousConformal2DPMLElement ()
Constructor.
TangentiallyDiscontinuousConformal2DPMLElement (const unsigned nu_s_index, const double nu_at_s_min, const double nu_at_s_max)
Constructor.
virtual void enable_pml (TangentiallyDiscontinuousConformalPMLMapping *pml_mapping_pt)
Enable pml. Set the pointer to a PML mapping function.
virtual void pml_transformation_jacobian (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseComplexMatrix &jacobian)
virtual void pml_transformation_jacobian (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseComplexMatrix &jacobian_matrix, Vector< std::complex< double > > &transformed_x)
void find_rips ()
Look for rips in the transformation and store in rips vector.
double distance_from_element_edge (const Vector< double > &x_inner, const Vector< double > &x_outer, const Vector< double > &p, const Vector< double > &r)
Compute distance from rip to PML element edge.
void compute_transformed_normal_derivative (const DenseComplexMatrix &J, const Vector< double > &n, Vector< std::complex< double > > &result)
Compute n'J^{-1}, which when applied to the untransformed grad operator gives us the transformed normal derivative.
virtual void fill_in_contribution_to_jacobian_no_rips (Vector< double > &residuals, DenseMatrix< double > &jacobian, bool flag)=0
virtual void fill_in_contribution_to_jacobian_with_rips (Vector< double > &residuals, DenseMatrix< double > &jacobian, bool flag)=0
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Static Public Attributes
static bool Find_rips_mode
static Vector< TwoDimRip > rips
Protected Attributes
bool Force_rip_integration
bool Disable_rip_integration
TangentiallyDiscontinuousConformalPMLMapping * Tangentially_discontinuous_pml_mapping_pt
Additional Inherited Members
Detailed Description
Definition at line 727 of file pml_elements.h.
Constructor & Destructor Documentation
TangentiallyDiscontinuousConformal2DPMLElement() [1/2]
oomph::TangentiallyDiscontinuousConformal2DPMLElement::TangentiallyDiscontinuousConformal2DPMLElement () [inline]
Constructor.
Definition at line 733 of file pml_elements.h.
TangentiallyDiscontinuousConformal2DPMLElement() [2/2]
oomph::TangentiallyDiscontinuousConformal2DPMLElement::TangentiallyDiscontinuousConformal2DPMLElement (const unsigned nu_s_index, const double nu_at_s_min, const double nu_at_s_max) [inline]
Constructor.
Definition at line 738 of file pml_elements.h.
Member Function Documentation
compute_transformed_normal_derivative()
void oomph::TangentiallyDiscontinuousConformal2DPMLElement::compute_transformed_normal_derivative (const DenseComplexMatrix & J, const Vector< double > & n, Vector< std::complex< double > > & result)
Compute n'J^{-1}, which when applied to the untransformed grad operator gives us the transformed normal derivative.
Definition at line 265 of file pml_elements.cc.
References oomph::QuadTreeNames::N, oomph::DenseComplexMatrix::ncol(), and oomph::DenseComplexMatrix::nrow().
distance_from_element_edge()
double oomph::TangentiallyDiscontinuousConformal2DPMLElement::distance_from_element_edge (const Vector< double > & x_inner, const Vector< double > & x_outer, const Vector< double > & p, const Vector< double > & r)
Compute distance from rip to PML element edge.
enable_pml()
virtual void oomph::TangentiallyDiscontinuousConformal2DPMLElement::enable_pml (TangentiallyDiscontinuousConformalPMLMapping * pml_mapping_pt) [inline], [virtual]
Enable pml. Set the pointer to a PML mapping function.
Definition at line 747 of file pml_elements.h.
References oomph::PMLElementBase< DIM >::enable_pml(), and s.
fill_in_contribution_to_jacobian()
void oomph::TangentiallyDiscontinuousConformal2DPMLElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 855 of file pml_elements.h.
fill_in_contribution_to_jacobian_no_rips()
virtual void oomph::TangentiallyDiscontinuousConformal2DPMLElement::fill_in_contribution_to_jacobian_no_rips (Vector< double > & residuals, DenseMatrix< double > & jacobian, bool flag) [pure virtual]
fill_in_contribution_to_jacobian_with_rips()
virtual void oomph::TangentiallyDiscontinuousConformal2DPMLElement::fill_in_contribution_to_jacobian_with_rips (Vector< double > & residuals, DenseMatrix< double > & jacobian, bool flag) [pure virtual]
fill_in_contribution_to_residuals()
void oomph::TangentiallyDiscontinuousConformal2DPMLElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 828 of file pml_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
find_rips()
void oomph::TangentiallyDiscontinuousConformal2DPMLElement::find_rips ()
Look for rips in the transformation and store in rips vector.
pml_transformation_jacobian() [1/2]
virtual void oomph::TangentiallyDiscontinuousConformal2DPMLElement::pml_transformation_jacobian (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseComplexMatrix & jacobian) [virtual]
Reimplemented from oomph::TangentiallyVaryingConformal2DPMLElement.
pml_transformation_jacobian() [2/2]
virtual void oomph::TangentiallyDiscontinuousConformal2DPMLElement::pml_transformation_jacobian (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseComplexMatrix & jacobian_matrix, Vector< std::complex< double > > & transformed_x) [virtual]
Reimplemented from oomph::TangentiallyVaryingConformal2DPMLElement.
Member Data Documentation
Disable_rip_integration
bool oomph::TangentiallyDiscontinuousConformal2DPMLElement::Disable_rip_integration [protected]
Definition at line 883 of file pml_elements.h.
Find_rips_mode
bool oomph::TangentiallyDiscontinuousConformal2DPMLElement::Find_rips_mode [static]
Definition at line 769 of file pml_elements.h.
Force_rip_integration
bool oomph::TangentiallyDiscontinuousConformal2DPMLElement::Force_rip_integration [protected]
Definition at line 880 of file pml_elements.h.
rips
Vector<TwoDimRip> oomph::TangentiallyDiscontinuousConformal2DPMLElement::rips [static]
Definition at line 800 of file pml_elements.h.
Tangentially_discontinuous_pml_mapping_pt
TangentiallyDiscontinuousConformalPMLMapping* oomph::TangentiallyDiscontinuousConformal2DPMLElement::Tangentially_discontinuous_pml_mapping_pt [protected]
Definition at line 885 of file pml_elements.h.
The documentation for this class was generated from the following files:
pml_elements.h
pml_elements.cc