oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM > Class Template Reference
Refineable version of Crouzeix Raviart elements. Generic class definitions.
#include <generalised_newtonian_refineable_navier_stokes_elements.h>
Public Member Functions
RefineableGeneralisedNewtonianQCrouzeixRaviartElement ()
Constructor.
RefineableGeneralisedNewtonianQCrouzeixRaviartElement (const RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM > &dummy)
Broken copy constructor.
unsigned ncont_interpolated_values () const
Broken assignment operator.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
void further_build ()
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
template<>
void rebuild_from_sons (Mesh *&mesh_pt)
2D Rebuild from sons: Reconstruct pressure from the (merged) sons
template<>
void rebuild_from_sons (Mesh *&mesh_pt)
3D Rebuild from sons: Reconstruct pressure from the (merged) sons
template<>
void further_build ()
template<>
void further_build ()
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all internal pressure dofs.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >
Refineable version of Crouzeix Raviart elements. Generic class definitions.
Definition at line 780 of file generalised_newtonian_refineable_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableGeneralisedNewtonianQCrouzeixRaviartElement() [1/2]
template<unsigned DIM>
oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::RefineableGeneralisedNewtonianQCrouzeixRaviartElement () [inline]
Constructor.
Definition at line 799 of file generalised_newtonian_refineable_navier_stokes_elements.h.
RefineableGeneralisedNewtonianQCrouzeixRaviartElement() [2/2]
template<unsigned DIM>
oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::RefineableGeneralisedNewtonianQCrouzeixRaviartElement (const RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 808 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
further_build() [1/3]
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build () [inline], [virtual]
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements. This must be specialised for each dimension.
Reimplemented from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), and oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons().
further_build() [2/3]
template<>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< 2 >::further_build () [inline], [virtual]
2D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1480 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::QuadTreeNames::SW, and oomph::Data::value().
further_build() [3/3]
template<>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< 3 >::further_build () [inline], [virtual]
3D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1554 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::OcTree::Direction_to_vector, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::Data::set_value().
further_setup_hanging_nodes()
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 899 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 851 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References i, and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
Definition at line 869 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_index_nst().
identify_load_data()
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 917 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::Node::hanging_pt(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::npres_nst(), and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_index_nst().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Broken assignment operator.
Number of continuously interpolated values: DIM (velocities)
Implements oomph::RefineableElement.
Definition at line 827 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::RefineableElement::rebuild_from_sons().
nrecovery_order()
template<unsigned DIM>
unsigned oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 835 of file generalised_newtonian_refineable_navier_stokes_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 838 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons() [1/3]
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
Implements oomph::RefineableElement.
Referenced by oomph::FaceGeometry< FaceGeometry< RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM > > >::FaceGeometry(), and oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons().
rebuild_from_sons() [2/3]
template<>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< 2 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
2D Rebuild from sons: Reconstruct pressure from the (merged) sons
Implements oomph::RefineableElement.
Definition at line 1244 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::QuadTreeNames::SW, and oomph::Data::value().
rebuild_from_sons() [3/3]
template<>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< 3 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
3D Rebuild from sons: Reconstruct pressure from the (merged) sons
Implements oomph::RefineableElement.
Definition at line 1331 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::GeneralisedElement::internal_data_pt(), oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, and oomph::Data::value().
unpin_elemental_pressure_dofs()
template<unsigned DIM>
void oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all internal pressure dofs.
Implements oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 788 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::npres_nst(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 842 of file generalised_newtonian_refineable_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
generalised_newtonian_refineable_navier_stokes_elements.h