oomph::MatrixBasedDiagPreconditioner Class Reference
Matrix-based diagonal preconditioner.
#include <general_purpose_preconditioners.h>
Public Member Functions
MatrixBasedDiagPreconditioner ()
Constructor (empty)
~MatrixBasedDiagPreconditioner ()
Destructor (empty)
MatrixBasedDiagPreconditioner (const MatrixBasedDiagPreconditioner &)
Broken copy constructor.
void operator= (const MatrixBasedDiagPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to z, i.e. z=D^-1.
void setup ()
Setup the preconditioner (store diagonal) from the fully assembled matrix.
Private Attributes
Vector< double > Inv_diag
Vector of inverse diagonal entries.
Additional Inherited Members
Detailed Description
Matrix-based diagonal preconditioner.
Definition at line 56 of file general_purpose_preconditioners.h.
Constructor & Destructor Documentation
MatrixBasedDiagPreconditioner() [1/2]
oomph::MatrixBasedDiagPreconditioner::MatrixBasedDiagPreconditioner () [inline]
Constructor (empty)
Definition at line 61 of file general_purpose_preconditioners.h.
 MatrixBasedDiagPreconditioner()
oomph::MatrixBasedDiagPreconditioner::~MatrixBasedDiagPreconditioner () [inline]
Destructor (empty)
Definition at line 64 of file general_purpose_preconditioners.h.
MatrixBasedDiagPreconditioner() [2/2]
oomph::MatrixBasedDiagPreconditioner::MatrixBasedDiagPreconditioner (const MatrixBasedDiagPreconditioner &) [inline]
Broken copy constructor.
Definition at line 67 of file general_purpose_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
void oomph::MatrixBasedDiagPreconditioner::operator= (const MatrixBasedDiagPreconditioner &) [inline]
Broken assignment operator.
Definition at line 73 of file general_purpose_preconditioners.h.
References oomph::BrokenCopy::broken_assign(), preconditioner_solve(), and setup().
preconditioner_solve()
void oomph::MatrixBasedDiagPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to z, i.e. z=D^-1.
Apply preconditioner: Multiply r by the inverse of the diagonal.
Implements oomph::Preconditioner.
Definition at line 124 of file general_purpose_preconditioners.cc.
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, Inv_diag, oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup(), and oomph::DoubleVector::values_pt().
Referenced by operator=(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::operator=(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::operator=(), and oomph::ILUZeroPreconditioner< CRDoubleMatrix >::~ILUZeroPreconditioner().
setup()
void oomph::MatrixBasedDiagPreconditioner::setup () [virtual]
Setup the preconditioner (store diagonal) from the fully assembled matrix.
Setup diagonal preconditioner: Store the inverse of the diagonal entries from the fully assembled matrix.
Implements oomph::Preconditioner.
Definition at line 49 of file general_purpose_preconditioners.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::Preconditioner::comm_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::DistributableLinearAlgebraObject::first_row(), i, Inv_diag, oomph::Preconditioner::matrix_pt(), oomph::DoubleMatrixBase::nrow(), and oomph::DistributableLinearAlgebraObject::nrow_local().
Referenced by operator=(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::operator=(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::operator=(), oomph::BiharmonicPreconditioner::setup(), and oomph::ILUZeroPreconditioner< CRDoubleMatrix >::~ILUZeroPreconditioner().
Member Data Documentation
Inv_diag
Vector<double> oomph::MatrixBasedDiagPreconditioner::Inv_diag [private]
Vector of inverse diagonal entries.
Definition at line 88 of file general_purpose_preconditioners.h.
Referenced by preconditioner_solve(), and setup().
The documentation for this class was generated from the following files:
general_purpose_preconditioners.h
general_purpose_preconditioners.cc