oomph::LinearWaveEquations< DIM > Class Template Reference
#include <linear_wave_elements.h>
Public Types
typedef void(* LinearWaveSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
LinearWaveEquations ()
Constructor (must initialise the Source_fct_pt to null)
LinearWaveEquations (const LinearWaveEquations &dummy)
Broken copy constructor.
void operator= (const LinearWaveEquations &)
Broken assignment operator.
virtual unsigned u_index_lin_wave () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the linear wave equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double du_dt_lin_wave (const unsigned &n) const
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double d2u_dt2_lin_wave (const unsigned &n) const
d^2u/dt^2 at local node n. Uses suitably interpolated value for hanging nodes.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
Output with default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error against and norm of exact solution.
LinearWaveSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
LinearWaveSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
void get_source_lin_wave (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multiphysics elements.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_lin_wave (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
double interpolated_du_dt_lin_wave (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
double interpolated_d2u_dt2_lin_wave (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_lin_wave (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_lin_wave (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_lin_wave (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
LinearWaveSourceFctPt Source_fct_pt
Pointer to source function:
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::LinearWaveEquations< DIM >
A class for all isoparametric elements that solve the LinearWave equations.
 \frac{\partial^2 u}{\partial x_i^2}= \frac{\partial^2 u}{\partial t^2}+f(t,x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 60 of file linear_wave_elements.h.
Member Typedef Documentation
LinearWaveSourceFctPt
template<unsigned DIM>
typedef void(* oomph::LinearWaveEquations< DIM >::LinearWaveSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 67 of file linear_wave_elements.h.
Constructor & Destructor Documentation
LinearWaveEquations() [1/2]
template<unsigned DIM>
oomph::LinearWaveEquations< DIM >::LinearWaveEquations () [inline]
Constructor (must initialise the Source_fct_pt to null)
Definition at line 72 of file linear_wave_elements.h.
LinearWaveEquations() [2/2]
template<unsigned DIM>
oomph::LinearWaveEquations< DIM >::LinearWaveEquations (const LinearWaveEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file linear_wave_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 447 of file linear_wave_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::LinearWaveEquations< DIM >::output().
compute_error() [2/2]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution at time t.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 530 of file linear_wave_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
d2u_dt2_lin_wave()
template<unsigned DIM>
double oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave (const unsigned & n) const [inline]
d^2u/dt^2 at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 124 of file linear_wave_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::LinearWaveEquations< DIM >::u_index_lin_wave(), and oomph::TimeStepper::weight().
Referenced by oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave().
dshape_and_dtest_eulerian_at_knot_lin_wave()
template<unsigned DIM>
virtual double oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_at_knot_lin_wave (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Referenced by oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave(), and oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_lin_wave()
template<unsigned DIM>
virtual double oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_lin_wave (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Referenced by oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave(), and oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct().
du_dt_lin_wave()
template<unsigned DIM>
double oomph::LinearWaveEquations< DIM >::du_dt_lin_wave (const unsigned & n) const [inline]
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 97 of file linear_wave_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::LinearWaveEquations< DIM >::u_index_lin_wave(), and oomph::TimeStepper::weight().
Referenced by oomph::LinearWaveEquations< DIM >::interpolated_du_dt_lin_wave().
fill_in_contribution_to_jacobian()
template<unsigned DIM>
virtual void oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 263 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 253 of file linear_wave_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave().
fill_in_generic_residual_contribution_lin_wave()
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableLinearWaveEquations< DIM >.
Definition at line 95 of file linear_wave_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_residuals(), oomph::QLinearWaveElement< DIM, NNODE_1D >::Initial_Nvalue(), and oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave().
get_flux()
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i] = du/dx_i.
Definition at line 222 of file linear_wave_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::LinearWaveEquations< DIM >::u_index_lin_wave().
Referenced by oomph::RefineableLinearWaveEquations< DIM >::get_Z2_flux().
get_source_lin_wave()
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::get_source_lin_wave (const double & t, const unsigned & ipt, const Vector< double > & x, double & source) const [inline]
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multiphysics elements.
Definition at line 206 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::Source_fct_pt, and t.
interpolated_d2u_dt2_lin_wave()
template<unsigned DIM>
double oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 324 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_at_knot_lin_wave(), oomph::LinearWaveEquations< DIM >::dshape_and_dtest_eulerian_lin_wave(), oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::FiniteElement::nnode(), s, oomph::LinearWaveEquations< DIM >::self_test(), and oomph::FiniteElement::shape().
interpolated_du_dt_lin_wave()
template<unsigned DIM>
double oomph::LinearWaveEquations< DIM >::interpolated_du_dt_lin_wave (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 300 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
interpolated_u_lin_wave()
template<unsigned DIM>
double oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 272 of file linear_wave_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::LinearWaveEquations< DIM >::u_index_lin_wave().
operator=()
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::operator= (const LinearWaveEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 81 of file linear_wave_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 150 of file linear_wave_elements.h.
Referenced by oomph::LinearWaveEquations< DIM >::output(), and oomph::QLinearWaveElement< DIM, NNODE_1D >::output().
output() [2/4]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 259 of file linear_wave_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 162 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::compute_error(), oomph::LinearWaveEquations< DIM >::output(), and oomph::LinearWaveEquations< DIM >::output_fct().
output() [4/4]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 296 of file linear_wave_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 337 of file linear_wave_elements.cc.
References i, and s.
Referenced by oomph::LinearWaveEquations< DIM >::output(), and oomph::QLinearWaveElement< DIM, NNODE_1D >::output_fct().
output_fct() [2/2]
template<unsigned DIM>
void oomph::LinearWaveEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
Output exact solution at time t
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearWaveElement< DIM, NNODE_1D >.
Definition at line 390 of file linear_wave_elements.cc.
References i, and s.
self_test()
template<unsigned DIM>
unsigned oomph::LinearWaveEquations< DIM >::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 226 of file linear_wave_elements.cc.
References oomph::FiniteElement::self_test().
Referenced by oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave().
source_fct_pt() [1/2]
template<unsigned DIM>
LinearWaveSourceFctPt& oomph::LinearWaveEquations< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 198 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineableLinearWaveEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
LinearWaveSourceFctPt oomph::LinearWaveEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 201 of file linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::Source_fct_pt.
u_index_lin_wave()
template<unsigned DIM>
virtual unsigned oomph::LinearWaveEquations< DIM >::u_index_lin_wave () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the linear wave equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 93 of file linear_wave_elements.h.
Referenced by oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::LinearWaveEquations< DIM >::get_flux(), oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values(), oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave(), and oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement().
Member Data Documentation
Source_fct_pt
template<unsigned DIM>
LinearWaveSourceFctPt oomph::LinearWaveEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 381 of file linear_wave_elements.h.
Referenced by oomph::RefineableLinearWaveEquations< DIM >::further_build(), oomph::LinearWaveEquations< DIM >::get_source_lin_wave(), and oomph::LinearWaveEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
linear_wave_elements.h
linear_wave_elements.cc