oomph::HijackedElementBase Class Reference
#include <hijacked_elements.h>
Public Member Functions
HijackedElementBase ()
Constructor, initialise the pointer to the equation numbers for the storage to zero.
virtual ~HijackedElementBase ()
Destructor, destroy the storage for the equation numbers.
void unhijack_all_data ()
Reset the hijacked data pt, so that none of the equations in the element are hijacked.
const double & residual_multiplier () const
Return the value of the residual multiplier.
double *& residual_multiplier_pt ()
Return the pointer to the residual multiplier.
Protected Member Functions
void hijack_global_eqn (long *const &global_eqn_pt)
Mark the global equation, addressed by global_eqn_pt, as hijacked by this element.
void unhijack_global_eqn (long *const &global_eqn_pt)
The global equation, addressed by global_eqn_pt, is no longer hijacked by this element.
Protected Attributes
std::set< long * > * Hijacked_global_eqn_number_pt
Vector< int > * Hijacked_local_eqn_number_pt
Pointer to a vector of integers containing the local equation numbers of any hijacked variables in the element.
double * Residual_multiplier_pt
Pointer to a double that multiplies the contribution to the residuals from the original element. This is usually used as a homotopy parameter to permit a smooth transition between different types of boundary conditions, rather than switching them on or off abruptly.
Static Protected Attributes
static double Default_residual_multiplier =0.0
Static default value for the double that multiplies the original residuals.
Detailed Description
HijackedElement base class that provides storage and access funcitons for pointers to the global equation numbers that are hijacked by the HijackedElement. A default residuals multiplier is also provided.
Definition at line 49 of file hijacked_elements.h.
Constructor & Destructor Documentation
HijackedElementBase()
oomph::HijackedElementBase::HijackedElementBase () [inline]
Constructor, initialise the pointer to the equation numbers for the storage to zero.
Definition at line 55 of file hijacked_elements.h.
References Default_residual_multiplier, Residual_multiplier_pt, and ~HijackedElementBase().
 HijackedElementBase()
oomph::HijackedElementBase::~HijackedElementBase () [virtual]
Destructor, destroy the storage for the equation numbers.
Destructor that cleans up any memory allocated by the class.
Definition at line 46 of file hijacked_elements.cc.
References Hijacked_global_eqn_number_pt, and Hijacked_local_eqn_number_pt.
Referenced by HijackedElementBase().
Member Function Documentation
hijack_global_eqn()
void oomph::HijackedElementBase::hijack_global_eqn (long *const & global_eqn_pt) [protected]
Mark the global equation, addressed by global_eqn_pt, as hijacked by this element.
Mark the global equation, addressed by global_eqn_pt, as hijacked by this element.
Definition at line 63 of file hijacked_elements.cc.
References Hijacked_global_eqn_number_pt.
Referenced by oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_external_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_internal_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_position_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_spine_value(), and oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_value().
residual_multiplier()
const double& oomph::HijackedElementBase::residual_multiplier () const [inline]
Return the value of the residual multiplier.
Definition at line 73 of file hijacked_elements.h.
References Residual_multiplier_pt.
Referenced by oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_jacobian(), and oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_residuals().
residual_multiplier_pt()
double* & oomph::HijackedElementBase::residual_multiplier_pt () [inline]
Return the pointer to the residual multiplier.
Definition at line 77 of file hijacked_elements.h.
References Residual_multiplier_pt.
unhijack_all_data()
void oomph::HijackedElementBase::unhijack_all_data () [inline]
Reset the hijacked data pt, so that none of the equations in the element are hijacked.
Definition at line 70 of file hijacked_elements.h.
References Hijacked_global_eqn_number_pt.
unhijack_global_eqn()
void oomph::HijackedElementBase::unhijack_global_eqn (long *const & global_eqn_pt) [protected]
The global equation, addressed by global_eqn_pt, is no longer hijacked by this element.
The global equation, addressed by global_eqn_pt, is no longer hijacked by this element.
Definition at line 80 of file hijacked_elements.cc.
References Hijacked_global_eqn_number_pt.
Member Data Documentation
Default_residual_multiplier
double oomph::HijackedElementBase::Default_residual_multiplier =0.0 [static], [protected]
Static default value for the double that multiplies the original residuals.
Static default value of the multiplier for the original residuals The contribution to the total residuals is the product of the multiplier and the original value of the residuals
Definition at line 100 of file hijacked_elements.h.
Referenced by HijackedElementBase().
Hijacked_global_eqn_number_pt
std::set<long*>* oomph::HijackedElementBase::Hijacked_global_eqn_number_pt [protected]
Pointer to a Set of pointers to the equation numbers that will be hijacked by this element. Note that these MUST be pointers because hijacking information is set BEFORE global equation numbers have been assigned.
Definition at line 85 of file hijacked_elements.h.
Referenced by oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::assign_local_eqn_numbers(), hijack_global_eqn(), unhijack_all_data(), unhijack_global_eqn(), and ~HijackedElementBase().
Hijacked_local_eqn_number_pt
Vector<int>* oomph::HijackedElementBase::Hijacked_local_eqn_number_pt [protected]
Pointer to a vector of integers containing the local equation numbers of any hijacked variables in the element.
Definition at line 90 of file hijacked_elements.h.
Referenced by oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::assign_local_eqn_numbers(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_jacobian(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_residuals(), and ~HijackedElementBase().
Residual_multiplier_pt
double* oomph::HijackedElementBase::Residual_multiplier_pt [protected]
Pointer to a double that multiplies the contribution to the residuals from the original element. This is usually used as a homotopy parameter to permit a smooth transition between different types of boundary conditions, rather than switching them on or off abruptly.
Definition at line 97 of file hijacked_elements.h.
Referenced by HijackedElementBase(), residual_multiplier(), and residual_multiplier_pt().
The documentation for this class was generated from the following files:
hijacked_elements.h
hijacked_elements.cc