oomph::PressureBasedSolidExactPreconditioner< MATRIX > Class Template Reference
The exact solid preconditioner. This extracts 2x2 blocks (corresponding to the displacement/position and pressure unknowns) and uses these to build a single preconditioner matrix for testing purposes. Iterative solvers should converge in a single step if this is used. If it doesn't something is wrong in the setup of the block matrices.
#include <solid_preconditioners.h>
Public Member Functions
PressureBasedSolidExactPreconditioner ()
Constructor - do nothing.
~PressureBasedSolidExactPreconditioner ()
Destructor - do nothing.
PressureBasedSolidExactPreconditioner (const PressureBasedSolidExactPreconditioner &)
Broken copy constructor.
void setup ()
Broken assignment operator.
void preconditioner_solve (const Vector< double > &r, Vector< double > &z)
Apply preconditioner to r.
Protected Attributes
MATRIX P_matrix
Preconditioner matrix.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::PressureBasedSolidExactPreconditioner< MATRIX >
The exact solid preconditioner. This extracts 2x2 blocks (corresponding to the displacement/position and pressure unknowns) and uses these to build a single preconditioner matrix for testing purposes. Iterative solvers should converge in a single step if this is used. If it doesn't something is wrong in the setup of the block matrices.
Definition at line 421 of file solid_preconditioners.h.
Constructor & Destructor Documentation
PressureBasedSolidExactPreconditioner() [1/2]
template<typename MATRIX >
oomph::PressureBasedSolidExactPreconditioner< MATRIX >::PressureBasedSolidExactPreconditioner () [inline]
Constructor - do nothing.
Definition at line 427 of file solid_preconditioners.h.
 PressureBasedSolidExactPreconditioner()
template<typename MATRIX >
oomph::PressureBasedSolidExactPreconditioner< MATRIX >::~PressureBasedSolidExactPreconditioner () [inline]
Destructor - do nothing.
Definition at line 431 of file solid_preconditioners.h.
PressureBasedSolidExactPreconditioner() [2/2]
template<typename MATRIX >
oomph::PressureBasedSolidExactPreconditioner< MATRIX >::PressureBasedSolidExactPreconditioner (const PressureBasedSolidExactPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 435 of file solid_preconditioners.h.
References oomph::BrokenCopy::broken_copy(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), and oomph::PressureBasedSolidLSCPreconditioner::setup().
Member Function Documentation
preconditioner_solve()
template<typename MATRIX >
void oomph::PressureBasedSolidExactPreconditioner< MATRIX >::preconditioner_solve (const Vector< double > & r, Vector< double > & z)
Apply preconditioner to r.
setup()
template<typename MATRIX >
void oomph::PressureBasedSolidExactPreconditioner< MATRIX >::setup () [virtual]
Broken assignment operator.
Setup the preconditioner
Implements oomph::Preconditioner.
Member Data Documentation
P_matrix
template<typename MATRIX >
MATRIX oomph::PressureBasedSolidExactPreconditioner< MATRIX >::P_matrix [protected]
Preconditioner matrix.
Definition at line 458 of file solid_preconditioners.h.
The documentation for this class was generated from the following file:
solid_preconditioners.h