oomph::RefineableLinearElasticityEquations< DIM > Class Template Reference
Class for Refineable LinearElasticity equations.
#include <refineable_linear_elasticity_elements.h>
Public Member Functions
RefineableLinearElasticityEquations ()
Constructor.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the current interpolated values (displacements). Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines),the values Vector sets its own size in here.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: DIM.
void further_build ()
Further build function, pass the pointers down to the sons.
Private Member Functions
void fill_in_generic_contribution_to_residuals_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Overloaded helper function to take hanging nodes into account.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableLinearElasticityEquations< DIM >
Class for Refineable LinearElasticity equations.
Definition at line 49 of file refineable_linear_elasticity_elements.h.
Constructor & Destructor Documentation
RefineableLinearElasticityEquations()
template<unsigned DIM>
oomph::RefineableLinearElasticityEquations< DIM >::RefineableLinearElasticityEquations () [inline]
Constructor.
Definition at line 57 of file refineable_linear_elasticity_elements.h.
Member Function Documentation
fill_in_generic_contribution_to_residuals_linear_elasticity()
template<unsigned DIM>
void oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Overloaded helper function to take hanging nodes into account.
Residuals for Refineable QLinearElasticityElements.
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 44 of file refineable_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build().
further_build()
template<unsigned DIM>
void oomph::RefineableLinearElasticityEquations< DIM >::further_build () [inline], [virtual]
Further build function, pass the pointers down to the sons.
Set the flag that switches inertia on/off
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::PRefineableQLinearElasticityElement< DIM >.
Definition at line 157 of file refineable_linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::body_force_fct_pt(), oomph::LinearElasticityEquationsBase< DIM >::Body_force_fct_pt, oomph::LinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), oomph::LinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, oomph::RefineableElement::father_element_pt(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearElasticityEquationsBase< DIM >::is_inertia_enabled(), oomph::LinearElasticityEquationsBase< DIM >::lambda_sq_pt(), oomph::LinearElasticityEquationsBase< DIM >::Lambda_sq_pt, and oomph::LinearElasticityEquationsBase< DIM >::Unsteady.
Referenced by oomph::PRefineableQLinearElasticityElement< DIM >::further_build(), and oomph::PRefineableQLinearElasticityElement< DIM >::PRefineableQLinearElasticityElement().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 67 of file refineable_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::LinearElasticityEquationsBase< DIM >::u_index_linear_elasticity().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the current interpolated values (displacements). Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines),the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 96 of file refineable_linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableLinearElasticityEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 112 of file refineable_linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::get_strain(), and i.
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineableLinearElasticityEquations< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: DIM.
Implements oomph::RefineableElement.
Reimplemented in oomph::PRefineableQLinearElasticityElement< DIM >.
Definition at line 154 of file refineable_linear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableLinearElasticityEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 104 of file refineable_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
refineable_linear_elasticity_elements.h
refineable_linear_elasticity_elements.cc