oomph::RefineableAdvectionDiffusionEquations< DIM > Class Template Reference
A version of the Advection Diffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_advection_diffusion_elements.h>
Public Member Functions
RefineableAdvectionDiffusionEquations ()
Empty Constructor.
RefineableAdvectionDiffusionEquations (const RefineableAdvectionDiffusionEquations< DIM > &dummy)
Broken copy constructor.
void operator= (const RefineableAdvectionDiffusionEquations< DIM > &)
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Protected Member Functions
void fill_in_generic_residual_contribution_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableAdvectionDiffusionEquations< DIM >
A version of the Advection Diffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 59 of file refineable_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableAdvectionDiffusionEquations() [1/2]
template<unsigned DIM>
oomph::RefineableAdvectionDiffusionEquations< DIM >::RefineableAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 67 of file refineable_advection_diffusion_elements.h.
RefineableAdvectionDiffusionEquations() [2/2]
template<unsigned DIM>
oomph::RefineableAdvectionDiffusionEquations< DIM >::RefineableAdvectionDiffusionEquations (const RefineableAdvectionDiffusionEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file refineable_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dinterpolated_u_adv_diff_ddata()
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 203 of file refineable_advection_diffusion_elements.h.
References oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::AdvectionDiffusionEquations< DIM >::u_index_adv_diff().
fill_in_generic_residual_contribution_adv_diff()
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 44 of file refineable_advection_diffusion_elements.cc.
References oomph::ALE_is_disabled, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::pe(), oomph::pe_st(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata().
further_build()
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 181 of file refineable_advection_diffusion_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::ALE_is_disabled, oomph::RefineableElement::father_element_pt(), oomph::AdvectionDiffusionEquations< DIM >::pe_pt(), oomph::AdvectionDiffusionEquations< DIM >::Pe_pt, oomph::AdvectionDiffusionEquations< DIM >::pe_st_pt(), oomph::AdvectionDiffusionEquations< DIM >::PeSt_pt, oomph::AdvectionDiffusionEquations< DIM >::source_fct_pt(), oomph::AdvectionDiffusionEquations< DIM >::Source_fct_pt, oomph::AdvectionDiffusionEquations< DIM >::wind_fct_pt(), and oomph::AdvectionDiffusionEquations< DIM >::Wind_fct_pt.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::further_build().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 100 of file refineable_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::AdvectionDiffusionEquations< DIM >::u_index_adv_diff().
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_interpolated_values().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 131 of file refineable_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::AdvectionDiffusionEquations< DIM >::u_index_adv_diff().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 92 of file refineable_advection_diffusion_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::get_flux().
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableAdvectionDiffusionEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 88 of file refineable_advection_diffusion_elements.h.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_compound_flux_indices(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
operator=()
template<unsigned DIM>
void oomph::RefineableAdvectionDiffusionEquations< DIM >::operator= (const RefineableAdvectionDiffusionEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 82 of file refineable_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
refineable_advection_diffusion_elements.h
refineable_advection_diffusion_elements.cc