oomph::TreeRoot Class Reference
#include <tree.h>
Public Member Functions
TreeRoot (RefineableElement *const &object_pt)
Constructor for the (empty) root tree.
TreeRoot (const TreeRoot &dummy)
Broken copy constructor.
void operator= (const TreeRoot &)
Broken assignment operator.
TreeRoot *& neighbour_pt (const int &direction)
Return the pointer to the neighbouring TreeRoots in specified direction. Returns NULL if there's no neighbour in this direction.
bool is_neighbour_periodic (const int &direction)
Return whether the neighbour in the particular direction is periodic.
void set_neighbour_periodic (const int &direction)
Set the neighbour in particular direction to be periodic.
void set_neighbour_nonperiodic (const int &direction)
Set the neighbour in particular direction to be nonperiodic.
unsigned nneighbour ()
Return the number of neighbours.
Protected Attributes
std::map< int, TreeRoot * > Neighbour_pt
Map of pointers to the neighbouring TreeRoots: Neighbour_pt[direction] returns the pointer to the TreeRoot's neighbour in the (enumerated) direction. Returns NULL if there's no neighbour in this direction.
std::map< int, bool > Neighbour_periodic
Map of booleans used for periodic boundaries: Neighbour_periodic_direction[directon] returns true if the neighbour in that direction is actually a periodic neighbour --- shared data values, but independent position. The default return of the map is false.
Additional Inherited Members
Detailed Description
TreeRoot is a Tree that forms the root of a (recursive) tree. The `root node` is special as it holds additional information about its neighbours and their relative rotation (inside a TreeForest).
Definition at line 303 of file tree.h.
Constructor & Destructor Documentation
TreeRoot() [1/2]
oomph::TreeRoot::TreeRoot (RefineableElement *const & object_pt) [inline]
Constructor for the (empty) root tree.
Definition at line 324 of file tree.h.
References oomph::Tree::Root_pt.
TreeRoot() [2/2]
oomph::TreeRoot::TreeRoot (const TreeRoot & dummy) [inline]
Broken copy constructor.
Definition at line 332 of file tree.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
is_neighbour_periodic()
bool oomph::TreeRoot::is_neighbour_periodic (const int & direction) [inline]
Return whether the neighbour in the particular direction is periodic.
Definition at line 350 of file tree.h.
Referenced by oomph::RefineableQElement< 2 >::check_integrity(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), oomph::BinaryTree::doc_neighbours(), and oomph::QuadTree::doc_neighbours().
neighbour_pt()
TreeRoot* & oomph::TreeRoot::neighbour_pt (const int & direction) [inline]
Return the pointer to the neighbouring TreeRoots in specified direction. Returns NULL if there's no neighbour in this direction.
Definition at line 345 of file tree.h.
Referenced by oomph::BinaryTree::gteq_edge_neighbour(), oomph::QuadTree::gteq_edge_neighbour(), and oomph::OcTree::gteq_face_neighbour().
nneighbour()
unsigned oomph::TreeRoot::nneighbour () [inline]
Return the number of neighbours.
Definition at line 362 of file tree.h.
operator=()
void oomph::TreeRoot::operator= (const TreeRoot &) [inline]
Broken assignment operator.
Definition at line 338 of file tree.h.
References oomph::BrokenCopy::broken_assign().
set_neighbour_nonperiodic()
void oomph::TreeRoot::set_neighbour_nonperiodic (const int & direction) [inline]
Set the neighbour in particular direction to be nonperiodic.
Definition at line 358 of file tree.h.
set_neighbour_periodic()
void oomph::TreeRoot::set_neighbour_periodic (const int & direction) [inline]
Set the neighbour in particular direction to be periodic.
Definition at line 354 of file tree.h.
Member Data Documentation
Neighbour_periodic
std::map<int,bool> oomph::TreeRoot::Neighbour_periodic [protected]
Map of booleans used for periodic boundaries: Neighbour_periodic_direction[directon] returns true if the neighbour in that direction is actually a periodic neighbour --- shared data values, but independent position. The default return of the map is false.
Definition at line 319 of file tree.h.
Neighbour_pt
std::map<int,TreeRoot*> oomph::TreeRoot::Neighbour_pt [protected]
Map of pointers to the neighbouring TreeRoots: Neighbour_pt[direction] returns the pointer to the TreeRoot's neighbour in the (enumerated) direction. Returns NULL if there's no neighbour in this direction.
Definition at line 311 of file tree.h.
The documentation for this class was generated from the following file:
tree.h