oomph::RefineableTetgenMesh< ELEMENT > Class Template Reference
#include <refineable_tetgen_mesh.template.h>
Public Member Functions
RefineableTetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface *> &internal_closed_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &split_corner_elements=false)
Build mesh, based on a TetMeshFacetedClosedSurface that specifies the outer boundary of the domain and any number of internal closed curves, specified by TetMeshFacetedSurfaces. Also specify target volume for uniform element size.
virtual ~RefineableTetgenMesh ()
Empty Destructor.
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
unsigned unrefine_uniformly ()
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void adapt (const Vector< double > &elem_error)
Adapt mesh, based on elemental error provided.
bool projection_is_disabled ()
Is projection of old solution onto new mesh disabled?
void disable_projection ()
Disable projection of old solution onto new mesh.
void enable_projection ()
Disable projection of old solution onto new mesh.
Protected Member Functions
void initialise_adaptation_data ()
Helper function to initialise data associated with adaptation.
Protected Attributes
bool Projection_is_disabled
Disable projection of solution onto new mesh during adaptation.
bool Corner_elements_must_be_split
Corner elements which have all of their nodes on the outer boundary are to be split into elements which have some non-boundary nodes.
Private Member Functions
RefineableTetgenMesh (const Vector< double > &target_volume, tetgenio *const &tetgen_io_pt, TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface *> &internal_surface_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Specialised constructor used during adaptation only. Element sizes are specified by vector tetgen_io is passed in from previous mesh (is then modified to build new mesh) Ditto with use_attributes, which comes from the previous mesh.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableTetgenMesh< ELEMENT >
Definition at line 54 of file refineable_tetgen_mesh.template.h.
Constructor & Destructor Documentation
RefineableTetgenMesh() [1/2]
template<class ELEMENT>
oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface *> & internal_closed_surface_pt, const double & element_volume, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & split_corner_elements = false) [inline]
Build mesh, based on a TetMeshFacetedClosedSurface that specifies the outer boundary of the domain and any number of internal closed curves, specified by TetMeshFacetedSurfaces. Also specify target volume for uniform element size.
Definition at line 64 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data().
RefineableTetgenMesh() [2/2]
template<class ELEMENT>
oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (const Vector< double > & target_volume, tetgenio *const & tetgen_io_pt, TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface *> & internal_surface_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline], [private]
Specialised constructor used during adaptation only. Element sizes are specified by vector tetgen_io is passed in from previous mesh (is then modified to build new mesh) Ditto with use_attributes, which comes from the previous mesh.
Definition at line 89 of file refineable_tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), e, oomph::TetMeshFacetedSurface::facet_pt(), i, oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data(), oomph::TetMeshBase::Internal_surface_pt, oomph::Mesh::nboundary(), oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), oomph::TetMeshBase::Outer_boundary_pt, oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::Tet_mesh_facet_pt, oomph::TetMeshBase::Tet_mesh_faceted_surface_pt, oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetMeshBase::Time_stepper_pt, and oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt.
 RefineableTetgenMesh()
template<class ELEMENT>
virtual oomph::RefineableTetgenMesh< ELEMENT >::~RefineableTetgenMesh () [inline], [virtual]
Empty Destructor.
Definition at line 235 of file refineable_tetgen_mesh.template.h.
Member Function Documentation
adapt()
template<class ELEMENT >
void oomph::RefineableTetgenMesh< ELEMENT >::adapt (const Vector< double > & elem_error) [virtual]
Adapt mesh, based on elemental error provided.
Adapt problem based on specified elemental error estimates.
Implements oomph::RefineableMeshBase.
Definition at line 52 of file refineable_tetgen_mesh.template.cc.
References oomph::TetMeshBase::boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), e, oomph::Mesh::element_pt(), oomph::SamplePointContainerParameters::enable_use_eulerian_coordinates_during_setup(), oomph::Mesh::face_index_at_boundary(), oomph::TetMeshBase::face_index_at_boundary_in_region(), oomph::Mesh::finite_element_pt(), oomph::Mesh::flush_element_and_node_storage(), i, oomph::Problem::mesh_pt(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::TetMeshBase::nboundary_element_in_region(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::TetMeshBase::nregion(), oomph::TetMeshBase::nregion_element(), oomph::oomph_info, oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::TetMeshBase::region_attribute(), oomph::TetMeshBase::region_element_pt(), s, oomph::FiniteElement::size(), oomph::TetgenMesh< ELEMENT >::tetgenio_pt(), oomph::TimingHelpers::timer(), and oomph::Node::x().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::unrefine_uniformly().
disable_projection()
template<class ELEMENT>
void oomph::RefineableTetgenMesh< ELEMENT >::disable_projection () [inline]
Disable projection of old solution onto new mesh.
Definition at line 270 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
enable_projection()
template<class ELEMENT>
void oomph::RefineableTetgenMesh< ELEMENT >::enable_projection () [inline]
Disable projection of old solution onto new mesh.
Definition at line 276 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
initialise_adaptation_data()
template<class ELEMENT>
void oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data () [inline], [protected]
Helper function to initialise data associated with adaptation.
By default we project solution onto new mesh during adaptation
Definition at line 285 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetMeshBase::Max_element_size, oomph::RefineableTetMeshBase::Max_permitted_edge_ratio, oomph::RefineableTetMeshBase::Min_element_size, and oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh().
projection_is_disabled()
template<class ELEMENT>
bool oomph::RefineableTetgenMesh< ELEMENT >::projection_is_disabled () [inline]
Is projection of old solution onto new mesh disabled?
Definition at line 264 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
refine_uniformly()
template<class ELEMENT>
void oomph::RefineableTetgenMesh< ELEMENT >::refine_uniformly (DocInfo & doc_info) [inline], [virtual]
Refine mesh uniformly and doc process.
Implements oomph::RefineableMeshBase.
Definition at line 238 of file refineable_tetgen_mesh.template.h.
unrefine_uniformly()
template<class ELEMENT>
unsigned oomph::RefineableTetgenMesh< ELEMENT >::unrefine_uniformly () [inline], [virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
Definition at line 249 of file refineable_tetgen_mesh.template.h.
References oomph::RefineableTetgenMesh< ELEMENT >::adapt().
Member Data Documentation
Corner_elements_must_be_split
template<class ELEMENT>
bool oomph::RefineableTetgenMesh< ELEMENT >::Corner_elements_must_be_split [protected]
Corner elements which have all of their nodes on the outer boundary are to be split into elements which have some non-boundary nodes.
Definition at line 302 of file refineable_tetgen_mesh.template.h.
Projection_is_disabled
template<class ELEMENT>
bool oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled [protected]
Disable projection of solution onto new mesh during adaptation.
Definition at line 297 of file refineable_tetgen_mesh.template.h.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::disable_projection(), oomph::RefineableTetgenMesh< ELEMENT >::enable_projection(), oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data(), and oomph::RefineableTetgenMesh< ELEMENT >::projection_is_disabled().
The documentation for this class was generated from the following files:
refineable_tetgen_mesh.template.h
refineable_tetgen_mesh.template.cc