oomph::QHelmholtzElement< DIM, NNODE_1D > Class Template Reference
#include <helmholtz_elements.h>
Public Member Functions
QHelmholtzElement ()
Constructor: Call constructors for QElement and Helmholtz equations.
QHelmholtzElement (const QHelmholtzElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 2
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QHelmholtzElement< DIM, NNODE_1D >
QHelmholtzElement elements are linear/quadrilateral/brick-shaped Helmholtz elements with isoparametric interpolation for the function.
Definition at line 462 of file helmholtz_elements.h.
Constructor & Destructor Documentation
QHelmholtzElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QHelmholtzElement< DIM, NNODE_1D >::QHelmholtzElement () [inline]
Constructor: Call constructors for QElement and Helmholtz equations.
Definition at line 477 of file helmholtz_elements.h.
QHelmholtzElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QHelmholtzElement< DIM, NNODE_1D >::QHelmholtzElement (const QHelmholtzElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 481 of file helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::HelmholtzEquations< DIM >.
Definition at line 622 of file helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz().
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::HelmholtzEquations< DIM >.
Definition at line 593 of file helmholtz_elements.h.
References oomph::QHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz(), and oomph::FiniteElement::dshape_eulerian().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 500 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 506 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 521 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 527 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 533 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::HelmholtzEquations< DIM >.
Definition at line 555 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::dshape_and_dtest_eulerian_at_knot_helmholtz(), oomph::HelmholtzEquations< DIM >::dshape_and_dtest_eulerian_helmholtz(), oomph::HelmholtzEquations< DIM >::output_fct(), and s.
output_real()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output_real (std::ostream & outfile, const double & phi, const unsigned & n_plot) [inline]
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 514 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output_real().
output_real_fct()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QHelmholtzElement< DIM, NNODE_1D >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 543 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output_real_fct().
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QHelmholtzElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 495 of file helmholtz_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QHelmholtzElement< DIM, NNODE_1D >::Initial_Nvalue = 2 [static], [private]
Static int that holds the number of variables at nodes: always the same.
Set the data for the number of Variables at each node, always two (real and imag part) in every case
Definition at line 470 of file helmholtz_elements.h.
The documentation for this class was generated from the following files:
helmholtz_elements.h
helmholtz_elements.cc