oomph::PRefineableQCrouzeixRaviartElement< DIM > Class Template Reference
#include <refineable_navier_stokes_elements.h>
Public Member Functions
PRefineableQCrouzeixRaviartElement ()
Constructor.
~PRefineableQCrouzeixRaviartElement ()
Destructor.
PRefineableQCrouzeixRaviartElement (const PRefineableQCrouzeixRaviartElement< DIM > &dummy)
Broken copy constructor.
double p_nst (const unsigned &i) const
Broken assignment operator.
double p_nst (const unsigned &t, const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: DIM (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation:
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
void further_build ()
template<>
void further_build ()
template<>
void further_build ()
template<>
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
template<>
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
template<>
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Define the pressure shape and test functions.
template<>
void pshape_nst (const Vector< double > &s, Shape &psi) const
template<>
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Define the pressure shape and test functions.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all internal pressure dofs.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PRefineableQCrouzeixRaviartElement< DIM >
p-refineable version of Crouzeix Raviart elements. Generic class definitions
Definition at line 1283 of file refineable_navier_stokes_elements.h.
Constructor & Destructor Documentation
PRefineableQCrouzeixRaviartElement() [1/2]
template<unsigned DIM>
oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement () [inline]
Constructor.
Definition at line 1303 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::resize(), and oomph::FiniteElement::set_integration_scheme().
 PRefineableQCrouzeixRaviartElement()
template<unsigned DIM>
oomph::PRefineableQCrouzeixRaviartElement< DIM >::~PRefineableQCrouzeixRaviartElement () [inline]
Destructor.
Definition at line 1334 of file refineable_navier_stokes_elements.h.
References oomph::FiniteElement::integral_pt().
PRefineableQCrouzeixRaviartElement() [2/2]
template<unsigned DIM>
oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement (const PRefineableQCrouzeixRaviartElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 1342 of file refineable_navier_stokes_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_nst() [1/3]
template<unsigned DIM>
double oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Referenced by oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst().
dshape_and_dtest_eulerian_at_knot_nst() [2/3]
template<>
double oomph::PRefineableQCrouzeixRaviartElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
2D Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1920 of file refineable_navier_stokes_elements.h.
References oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst(), oomph::FiniteElement::dshape_eulerian_at_knot(), i, and oomph::FiniteElement::nnode_1d().
dshape_and_dtest_eulerian_at_knot_nst() [3/3]
template<>
double oomph::PRefineableQCrouzeixRaviartElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
3D Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1977 of file refineable_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, oomph::FiniteElement::nnode_1d(), and oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst().
dshape_and_dtest_eulerian_nst() [1/3]
template<unsigned DIM>
double oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Referenced by oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::RefineableQCrouzeixRaviartElement< DIM >::further_build().
dshape_and_dtest_eulerian_nst() [2/3]
template<>
double oomph::PRefineableQCrouzeixRaviartElement< 2 >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
2D Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1892 of file refineable_navier_stokes_elements.h.
References oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode_1d().
dshape_and_dtest_eulerian_nst() [3/3]
template<>
double oomph::PRefineableQCrouzeixRaviartElement< 3 >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
3D Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1948 of file refineable_navier_stokes_elements.h.
References oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode_1d().
fix_pressure()
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1366 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
further_build() [1/3]
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build () [virtual]
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements. This must be specialised for each dimension.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
further_build() [2/3]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 2 >::further_build () [virtual]
2D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1779 of file refineable_navier_stokes_elements.cc.
References oomph::RefineableNavierStokesEquations< DIM >::further_build(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::QuadTreeNames::SE, and oomph::QuadTreeNames::SW.
further_build() [3/3]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 3 >::further_build () [virtual]
2D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1890 of file refineable_navier_stokes_elements.cc.
References oomph::OcTree::Direction_to_vector, oomph::RefineableNavierStokesEquations< DIM >::further_build(), i, and oomph::NavierStokesEquations< DIM >::interpolated_p_nst().
further_setup_hanging_nodes()
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 1490 of file refineable_navier_stokes_elements.h.
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 1442 of file refineable_navier_stokes_elements.h.
References i.
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
Definition at line 1460 of file refineable_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::PRefineableQCrouzeixRaviartElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: DIM (velocities)
Implements oomph::RefineableElement.
Definition at line 1376 of file refineable_navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned oomph::PRefineableQCrouzeixRaviartElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1363 of file refineable_navier_stokes_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::PRefineableQCrouzeixRaviartElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation:
Same order as shape functions. - Constant recovery order, since recovery order of the first element is used for the whole mesh.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1403 of file refineable_navier_stokes_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::PRefineableQCrouzeixRaviartElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1406 of file refineable_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
p_nst() [1/2]
template<unsigned DIM>
double oomph::PRefineableQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & i) const [inline], [virtual]
Broken assignment operator.
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1356 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
p_nst() [2/2]
template<unsigned DIM>
double oomph::PRefineableQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & t, const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1359 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
pshape_nst() [1/6]
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Referenced by oomph::PRefineableQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), and oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [2/6]
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
pshape_nst() [3/6]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 2004 of file refineable_navier_stokes_elements.h.
References i, and oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [4/6]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Define the pressure shape and test functions.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 2037 of file refineable_navier_stokes_elements.h.
References i, and oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [5/6]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 2059 of file refineable_navier_stokes_elements.h.
References i, and oomph::PRefineableQCrouzeixRaviartElement< DIM >::pshape_nst().
pshape_nst() [6/6]
template<>
void oomph::PRefineableQCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Define the pressure shape and test functions.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 2096 of file refineable_navier_stokes_elements.h.
References i.
rebuild_from_sons()
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
Implements oomph::RefineableElement.
Definition at line 1380 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::set_value().
required_nvalue()
template<unsigned DIM>
unsigned oomph::PRefineableQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1372 of file refineable_navier_stokes_elements.h.
unpin_elemental_pressure_dofs()
template<unsigned DIM>
void oomph::PRefineableQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all internal pressure dofs.
Implements oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1291 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::nvalue(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::PRefineableQCrouzeixRaviartElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1410 of file refineable_navier_stokes_elements.h.
References s, and oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_navier_stokes_elements.h