oomph::RefineableQPVDElementWithPressure< DIM > Class Template Reference
#include <refineable_solid_elements.h>
Public Member Functions
RefineableQPVDElementWithPressure ()
Constructor:
void rebuild_from_sons (Mesh *&mesh_pt)
Reconstruct the pressure from the sons Must be specialized for each dimension.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
No additional hanging node procedures are required for discontinuous solid pressures.
void further_build ()
Further build: Interpolate the solid pressure values Again this must be specialised for each dimension.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 0 (pure solid problem)
template<>
void rebuild_from_sons (Mesh *&mesh_pt)
2D rebuild from sons: reconstruct the solid pressure
template<>
void further_build ()
template<>
void rebuild_from_sons (Mesh *&mesh_pt)
3D rebuild from sons: reconstruct the pressure
template<>
void further_build ()
3D Further build: Interpolate the solid pressure values
Private Member Functions
void unpin_elemental_solid_pressure_dofs ()
Unpin all solid pressure dofs.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableQPVDElementWithPressure< DIM >
Class for refineable solid mechanics elements in near-incompressible/ incompressible formulation, so a pressure is included! In this case, the pressure interpolation is discontinuous, a la Crouzeix Raviart, and the displacement is always quadratic.
Definition at line 407 of file refineable_solid_elements.h.
Constructor & Destructor Documentation
RefineableQPVDElementWithPressure()
template<unsigned DIM>
oomph::RefineableQPVDElementWithPressure< DIM >::RefineableQPVDElementWithPressure () [inline]
Constructor:
Definition at line 427 of file refineable_solid_elements.h.
References oomph::RefineableElement::rebuild_from_sons().
Member Function Documentation
further_build() [1/3]
template<unsigned DIM>
void oomph::RefineableQPVDElementWithPressure< DIM >::further_build () [inline], [virtual]
Further build: Interpolate the solid pressure values Again this must be specialised for each dimension.
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
further_build() [2/3]
template<>
void oomph::RefineableQPVDElementWithPressure< 2 >::further_build () [inline], [virtual]
2D further build interpolates the internal solid pressure from the father.
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
Definition at line 557 of file refineable_solid_elements.h.
References oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::RefineableQPVDElementWithPressure< DIM >::rebuild_from_sons(), oomph::QuadTreeNames::SE, oomph::QPVDElementWithPressure< DIM >::solid_p(), and oomph::QuadTreeNames::SW.
further_build() [3/3]
template<>
void oomph::RefineableQPVDElementWithPressure< 3 >::further_build () [inline], [virtual]
3D Further build: Interpolate the solid pressure values
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
Definition at line 710 of file refineable_solid_elements.h.
References oomph::OcTree::Direction_to_vector, oomph::RefineablePVDEquationsWithPressure< DIM >::further_build(), i, oomph::PVDEquationsWithPressure< DIM >::interpolated_solid_p(), and oomph::QPVDElementWithPressure< DIM >::solid_p().
further_setup_hanging_nodes()
template<unsigned DIM>
void oomph::RefineableQPVDElementWithPressure< DIM >::further_setup_hanging_nodes () [inline], [virtual]
No additional hanging node procedures are required for discontinuous solid pressures.
Reimplemented from oomph::RefineableElement.
Definition at line 453 of file refineable_solid_elements.h.
References oomph::RefineablePVDEquations< DIM >::further_build().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineableQPVDElementWithPressure< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 0 (pure solid problem)
Reimplemented from oomph::RefineablePVDEquationsWithPressure< DIM >.
Definition at line 461 of file refineable_solid_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::RefineableQPVDElementWithPressure< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 449 of file refineable_solid_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::RefineableQPVDElementWithPressure< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 440 of file refineable_solid_elements.h.
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons() [1/3]
template<unsigned DIM>
void oomph::RefineableQPVDElementWithPressure< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Reconstruct the pressure from the sons Must be specialized for each dimension.
Implements oomph::RefineableElement.
Referenced by oomph::FaceGeometry< FaceGeometry< RefineableQPVDElementWithPressure< 2 > > >::FaceGeometry(), and oomph::RefineableQPVDElementWithPressure< DIM >::further_build().
rebuild_from_sons() [2/3]
template<>
void oomph::RefineableQPVDElementWithPressure< 2 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
2D rebuild from sons: reconstruct the solid pressure
Implements oomph::RefineableElement.
Definition at line 497 of file refineable_solid_elements.h.
References oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::QuadTreeNames::SE, and oomph::QuadTreeNames::SW.
rebuild_from_sons() [3/3]
template<>
void oomph::RefineableQPVDElementWithPressure< 3 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
3D rebuild from sons: reconstruct the pressure
Implements oomph::RefineableElement.
Definition at line 619 of file refineable_solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, and oomph::Data::value().
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM>
void oomph::RefineableQPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs () [inline], [private], [virtual]
Unpin all solid pressure dofs.
Implements oomph::PVDEquationsBase< DIM >.
Definition at line 416 of file refineable_solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::PVDEquationsBase< DIM >::npres_solid(), and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM>
Node* oomph::RefineableQPVDElementWithPressure< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 444 of file refineable_solid_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_solid_elements.h