oomph::TreeBasedRefineableMeshBase Class Reference
Base class for tree-based refineable meshes.
#include <refineable_mesh.h>
Classes
struct HangHelperStruct
Helper struct to collate data required during TreeBasedRefineableMeshBase::synchronise_hanging_nodes.
Public Member Functions
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
void p_adapt (const Vector< double > &elemental_error)
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
virtual void setup_tree_forest ()=0
Set up the tree forest associated with the Mesh (if any)
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
Access fct for max. permissible p-refinement level (relative to base mesh)
unsigned & min_p_refinement_level ()
Access fct for min. permissible p-refinement level (relative to base mesh)
virtual void adapt_mesh (DocInfo &doc_info)
Perform the actual tree-based mesh adaptation, documenting the progress in the directory specified in DocInfo object.
virtual void adapt_mesh ()
Perform the actual tree-based mesh adaptation. A simple wrapper to call the function without documentation.
void p_adapt_mesh (DocInfo &doc_info)
Perform the actual tree-based mesh p-adaptation, documenting the progress in the directory specified in DocInfo object.
void p_adapt_mesh ()
Perform the actual tree-based mesh p-adaptation. A simple wrapper to call the function without documentation.
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
Refine mesh by splitting the elements identified by their numbers.
virtual void refine_selected_elements (const Vector< RefineableElement *> &elements_to_be_refined)
Refine mesh by splitting the elements identified by their pointers.
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement *> &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine base mesh to same degree as reference mesh (relative to original unrefined mesh).
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine base mesh to same degree as reference mesh minus one level of refinement (relative to original unrefined mesh). Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one.
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh -- if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement *> &level_elements)
Extract the elements at a particular refinement level in the refinement pattern - used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
virtual void get_refinement_pattern (Vector< Vector< unsigned > > &to_be_refined)
Extract refinement pattern: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...].
void refine_base_mesh (Vector< Vector< unsigned > > &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned > > &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
Level to which the mesh was uniformly refined when it was pruned (const version)
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh.
Protected Member Functions
void synchronise_hanging_nodes (const unsigned &ncont_interpolated_values)
Synchronise the hanging nodes if the mesh is distributed.
virtual void additional_synchronise_hanging_nodes (const unsigned &ncont_interpolated_values)=0
void synchronise_nonhanging_nodes ()
virtual void split_elements_if_required ()=0
Split all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any new elements that are created will be of the correct type.
virtual void p_refine_elements_if_required ()=0
p-refine all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any temporary copies of the element that are created will be of the correct type.
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node *> &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Additional Inherited Members
Detailed Description
Base class for tree-based refineable meshes.
Definition at line 345 of file refineable_mesh.h.
Constructor & Destructor Documentation
TreeBasedRefineableMeshBase() [1/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase () [inline]
Constructor.
Definition at line 351 of file refineable_mesh.h.
References oomph::RefineableMeshBase::Doc_info_pt, oomph::RefineableMeshBase::Nrefined, and oomph::RefineableMeshBase::Nunrefined.
TreeBasedRefineableMeshBase() [2/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase & dummy) [inline]
Broken copy constructor.
Definition at line 377 of file refineable_mesh.h.
References oomph::BrokenCopy::broken_copy().
 TreeBasedRefineableMeshBase()
virtual oomph::TreeBasedRefineableMeshBase::~TreeBasedRefineableMeshBase () [inline], [virtual]
Empty Destructor:
Definition at line 389 of file refineable_mesh.h.
References oomph::RefineableMeshBase::adapt(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::p_adapt(), and oomph::RefineableMeshBase::refine_uniformly().
Member Function Documentation
adapt()
void oomph::TreeBasedRefineableMeshBase::adapt (const Vector< double > & elemental_error) [virtual]
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
Do adaptive refinement for mesh.
Pass Vector of error estimates for all elements.
Refine those whose errors exceeds the threshold
(Try to) unrefine those whose errors is less than threshold (only possible if the three brothers also want to be unrefined, of course.)
Update the nodal positions in the whole lot
Store # of refined/unrefined elements.
Doc refinement process (if required)
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 315 of file refineable_mesh.cc.
References adapt_mesh(), classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Mesh::delete_all_external_storage(), oomph::RefineableElement::deselect_for_refinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e, oomph::Mesh::element_pt(), oomph::Tree::father_pt(), get_refinement_levels(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::DocInfo::is_doc_enabled(), oomph::Tree::is_leaf(), oomph::Mesh::is_mesh_distributed(), oomph::OcTreeNames::LDB, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), max_refinement_level(), oomph::RefineableMeshBase::min_permitted_error(), min_refinement_level(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::Tree::nsons(), oomph::RefineableMeshBase::Nunrefined, oomph::Tree::object_pt(), oomph::oomph_info, oomph::RefineableElement::refinement_is_enabled(), oomph::RefineableElement::refinement_level(), oomph::Mesh::reorder_nodes(), oomph::RefineableElement::select_for_refinement(), oomph::Tree::son_pt(), oomph::Tree::son_type(), and oomph::RefineableElement::tree_pt().
Referenced by unrefine_uniformly().
adapt_mesh() [1/2]
void oomph::TreeBasedRefineableMeshBase::adapt_mesh (DocInfo & doc_info) [virtual]
Perform the actual tree-based mesh adaptation, documenting the progress in the directory specified in DocInfo object.
Adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
Refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the refinement for those who want to be refined. Note: Refinement/splitting only allocates elements but doesn't build them.
Build the new elements (i.e. give them nodes (create new ones where necessary), assign boundary conditions, and add nodes to mesh and mesh boundaries.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Unrefine selected elements (which may cause nodes to be re-built).
Add the new elements to the mesh (by completely overwriting the old Vector of elements).
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
Adjust position of hanging nodes to make sure their position is consistent with the FE-based represenetation of their larger neighbours.
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
`neighbours.dat`
`all_nodes.dat`
`new_nodes.dat`
`hang_nodes_*.dat` where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
`hangnodes_withmasters.dat`
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
`neighbours.dat`
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info -- this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
Definition at line 898 of file refineable_mesh.cc.
References oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), classify_halo_and_haloed_nodes(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, e, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), Forest_pt, oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), oomph::Tree::merge_sons_if_required(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), split_elements_if_required(), oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), t, oomph::TimingHelpers::timer(), oomph::Tree::traverse_all(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
adapt_mesh() [2/2]
virtual void oomph::TreeBasedRefineableMeshBase::adapt_mesh () [inline], [virtual]
Perform the actual tree-based mesh adaptation. A simple wrapper to call the function without documentation.
Definition at line 477 of file refineable_mesh.h.
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
Referenced by adapt(), refine_base_mesh(), refine_selected_elements(), and refine_uniformly().
additional_synchronise_hanging_nodes()
virtual void oomph::TreeBasedRefineableMeshBase::additional_synchronise_hanging_nodes (const unsigned & ncont_interpolated_values) [protected], [pure virtual]
Additional synchronisation of hanging nodes Required for reconcilliation of hanging nodes on the outer edge of the halo layer when using elements with nonuniformly spaced nodes Must be implemented in templated derived class because ELEMENT template parameter is required for the node-creation functions in the Missing_masters_functions namespace
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >, and oomph::TreeBasedRefineableMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >.
Referenced by synchronise_hanging_nodes().
classify_halo_and_haloed_nodes() [1/2]
void oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes (DocInfo & doc_info, const bool & report_stats) [inline], [virtual]
Classify all halo and haloed information in the mesh (overloaded version from Mesh base class. Calls that one first, then synchronises hanging nodes)
Reimplemented from oomph::Mesh.
Definition at line 595 of file refineable_mesh.h.
References oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Global_timings::Doc_comprehensive_timings, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), oomph::oomph_info, oomph::Mesh::resize_halo_nodes(), oomph::Mesh::Resize_halo_nodes_not_required, and oomph::TimingHelpers::timer().
Referenced by adapt(), adapt_mesh(), p_adapt(), and p_adapt_mesh().
classify_halo_and_haloed_nodes() [2/2]
void oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes (const bool & report_stats = false) [inline], [virtual]
Classify the halo and haloed nodes in the mesh.
Reimplemented from oomph::Mesh.
Definition at line 657 of file refineable_mesh.h.
References oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
complete_hanging_nodes()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes (const int & ncont_interpolated_values) [protected]
Complete the hanging node scheme recursively.
Complete the hanging node scheme recursively. After the initial markup scheme, hanging nodes can depend on other hanging nodes ---> AAAAAAAAARGH! Need to translate this into a scheme where all hanging nodes only depend on non-hanging nodes...
Definition at line 2232 of file refineable_mesh.cc.
References complete_hanging_nodes_recursively(), e, oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::oomph_info, oomph::Node::set_hanging_pt(), oomph::HangInfo::set_master_node_pt(), and synchronise_hanging_nodes().
Referenced by adapt_mesh(), complete_hanging_nodes_recursively(), and p_adapt_mesh().
complete_hanging_nodes_recursively()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively (Node *& nod_pt, Vector< Node *> & master_nodes, Vector< double > & hang_weights, const int & i) [protected]
Auxiliary routine for recursive hanging node completion.
Given a node, return a vector of pointers to master nodes and a vector of the associated weights. This is done recursively, so if a node is not hanging, the node is regarded as its own master node which has weight 1.0.
Definition at line 2174 of file refineable_mesh.cc.
References complete_hanging_nodes(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), and oomph::HangInfo::nmaster().
Referenced by complete_hanging_nodes(), and unrefine_uniformly().
doc_adaptivity_targets()
void oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets (std::ostream & outfile) [inline], [virtual]
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
Definition at line 441 of file refineable_mesh.h.
References oomph::RefineableMeshBase::Max_keep_unrefined, oomph::RefineableMeshBase::Max_permitted_error, and oomph::RefineableMeshBase::Min_permitted_error.
dump_refinement()
void oomph::TreeBasedRefineableMeshBase::dump_refinement (std::ostream & outfile) [virtual]
Dump refinement pattern to allow for rebuild.
Dump refinement pattern to allow for rebuild
Definition at line 223 of file refineable_mesh.cc.
References get_refinement_pattern(), and i.
forest_pt()
TreeForest* oomph::TreeBasedRefineableMeshBase::forest_pt () [inline]
Return pointer to the Forest represenation of the mesh.
Definition at line 437 of file refineable_mesh.h.
Referenced by get_elements_at_refinement_level(), get_refinement_pattern(), p_adapt_mesh(), and refine_as_in_reference_mesh().
get_elements_at_refinement_level()
void oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level (unsigned & refinement_level, Vector< RefineableElement *> & level_elements) [virtual]
Extract the elements at a particular refinement level in the refinement pattern - used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
Extract the elements at a particular refinement level in the refinement pattern (used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
Definition at line 118 of file refineable_mesh.cc.
References e, forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by oomph::Mesh::prune_halo_elements_and_nodes().
get_refinement_levels()
void oomph::TreeBasedRefineableMeshBase::get_refinement_levels (unsigned & min_refinement_level, unsigned & max_refinement_level) [virtual]
Get max/min refinement levels in mesh.
Get max/min refinement level.
Definition at line 801 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), and oomph::Mesh::nelement().
Referenced by adapt(), oomph::Problem::load_balance(), oomph::Mesh::prune_halo_elements_and_nodes(), refine_as_in_reference_mesh(), refine_base_mesh(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
get_refinement_pattern()
void oomph::TreeBasedRefineableMeshBase::get_refinement_pattern (Vector< Vector< unsigned > > & to_be_refined) [virtual]
Extract refinement pattern: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...].
Get refinement pattern of mesh: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...]
Definition at line 55 of file refineable_mesh.cc.
References e, forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by dump_refinement(), oomph::Mesh::prune_halo_elements_and_nodes(), refine_base_mesh_as_in_reference_mesh(), and refine_base_mesh_as_in_reference_mesh_minus_one().
max_p_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::max_p_refinement_level () [inline]
Access fct for max. permissible p-refinement level (relative to base mesh)
Definition at line 466 of file refineable_mesh.h.
Referenced by p_adapt().
max_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::max_refinement_level () [inline]
Access fct for max. permissible refinement level (relative to base mesh)
Definition at line 460 of file refineable_mesh.h.
Referenced by adapt().
min_p_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::min_p_refinement_level () [inline]
Access fct for min. permissible p-refinement level (relative to base mesh)
Definition at line 469 of file refineable_mesh.h.
Referenced by p_adapt().
min_refinement_level()
unsigned& oomph::TreeBasedRefineableMeshBase::min_refinement_level () [inline]
Access fct for min. permissible refinement level (relative to base mesh)
Definition at line 463 of file refineable_mesh.h.
Referenced by adapt().
operator=()
void oomph::TreeBasedRefineableMeshBase::operator= (const TreeBasedRefineableMeshBase &) [inline]
Broken assignment operator.
Definition at line 383 of file refineable_mesh.h.
References oomph::BrokenCopy::broken_assign().
p_adapt()
void oomph::TreeBasedRefineableMeshBase::p_adapt (const Vector< double > & elemental_error) [virtual]
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
Do adaptive p-refinement for mesh.
Pass Vector of error estimates for all elements.
p-refine those whose errors exceeds the threshold
p-unrefine those whose errors is less than threshold.
Reimplemented from oomph::RefineableMeshBase.
Definition at line 3833 of file refineable_mesh.cc.
References classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e, oomph::Mesh::element_pt(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::PRefineableElement::initial_p_order(), oomph::DocInfo::is_doc_enabled(), oomph::Mesh::is_mesh_distributed(), oomph::RefineableMeshBase::max_keep_unrefined(), max_p_refinement_level(), oomph::RefineableMeshBase::max_permitted_error(), min_p_refinement_level(), oomph::RefineableMeshBase::min_permitted_error(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::RefineableMeshBase::Nunrefined, oomph::oomph_info, p_adapt_mesh(), oomph::PRefineableElement::p_order(), oomph::PRefineableElement::p_refinement_is_enabled(), oomph::Mesh::reorder_nodes(), oomph::PRefineableElement::select_for_p_refinement(), and oomph::PRefineableElement::select_for_p_unrefinement().
p_adapt_mesh() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh (DocInfo & doc_info)
Perform the actual tree-based mesh p-adaptation, documenting the progress in the directory specified in DocInfo object.
p-adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
p-refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the p-refinement/unrefinement for those who want to be refined. Note: p-refinement builds fully- functional elements.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
`neighbours.dat`
`all_nodes.dat`
`new_nodes.dat`
`hang_nodes_*.dat` where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
`hangnodes_withmasters.dat`
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
`neighbours.dat`
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info -- this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
Definition at line 4292 of file refineable_mesh.cc.
References oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), classify_halo_and_haloed_nodes(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, e, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), forest_pt(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), p_refine_elements_if_required(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), t, oomph::TimingHelpers::timer(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
p_adapt_mesh() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh () [inline]
Perform the actual tree-based mesh p-adaptation. A simple wrapper to call the function without documentation.
Definition at line 493 of file refineable_mesh.h.
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
Referenced by p_adapt(), p_refine_selected_elements(), p_refine_uniformly(), and p_unrefine_uniformly().
p_refine_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::p_refine_elements_if_required () [protected], [pure virtual]
p-refine all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any temporary copies of the element that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >, and oomph::TreeBasedRefineableMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >.
Referenced by p_adapt_mesh().
p_refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< unsigned > & elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
Definition at line 5087 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), oomph::Mesh::is_mesh_distributed(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< PRefineableElement *> & elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
Definition at line 5129 of file refineable_mesh.cc.
References e, oomph::Mesh::is_mesh_distributed(), and p_adapt_mesh().
p_refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly (DocInfo & doc_info) [virtual]
p-refine mesh uniformly and doc process
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
Definition at line 1741 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly () [inline], [virtual]
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
Definition at line 420 of file refineable_mesh.h.
References oomph::RefineableMeshBase::p_refine_uniformly(), oomph::RefineableMeshBase::p_unrefine_uniformly(), and oomph::RefineableMeshBase::unrefine_uniformly().
p_unrefine_uniformly()
void oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly (DocInfo & doc_info)
p-unrefine mesh uniformly
p-unrefine mesh uniformly Unlike in h-refinement, we can simply p-unrefine each element in the mesh
Definition at line 5063 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_unrefinement().
read_refinement()
void oomph::TreeBasedRefineableMeshBase::read_refinement (std::ifstream & restart_file, Vector< Vector< unsigned > > & to_be_refined) [virtual]
Read refinement pattern to allow for rebuild.
Read refinement pattern to allow for rebuild
Definition at line 256 of file refineable_mesh.cc.
References i, and oomph::Global_string_for_annotation::string().
Referenced by refine().
refine()
void oomph::TreeBasedRefineableMeshBase::refine (std::ifstream & restart_file) [virtual]
Refine mesh according to refinement pattern in restart file.
Refine base mesh according to refinement pattern in restart file.
Definition at line 206 of file refineable_mesh.cc.
References read_refinement(), and refine_base_mesh().
refine_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh -- if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh -- if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
Definition at line 1902 of file refineable_mesh.cc.
References e, oomph::Tree::father_pt(), oomph::Mesh::finite_element_pt(), forest_pt(), get_refinement_levels(), i, oomph::Tree::is_leaf(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::Tree::nsons(), oomph::oomph_info, oomph::Mesh::output(), oomph::pause(), refine_selected_elements(), oomph::Tree::son_pt(), and oomph::Node::x().
refine_base_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh (Vector< Vector< unsigned > > & to_be_refined)
Refine base mesh according to specified refinement pattern.
Refine original, unrefined mesh according to specified refinement pattern (relative to original, unrefined mesh).
Definition at line 144 of file refineable_mesh.cc.
References adapt_mesh(), oomph::Mesh::Comm_pt, oomph::Mesh::element_pt(), get_refinement_levels(), i, oomph::Mesh::is_mesh_distributed(), and unrefine_uniformly().
Referenced by refine(), refine_base_mesh_as_in_reference_mesh(), refine_base_mesh_as_in_reference_mesh_minus_one(), and oomph::Problem::refine_distributed_base_mesh().
refine_base_mesh_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine base mesh to same degree as reference mesh (relative to original unrefined mesh).
Refine to same degree as the reference mesh.
Definition at line 1840 of file refineable_mesh.cc.
References get_refinement_pattern(), refine_base_mesh(), and refine_base_mesh_as_in_reference_mesh_minus_one().
refine_base_mesh_as_in_reference_mesh_minus_one()
bool oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine base mesh to same degree as reference mesh minus one level of refinement (relative to original unrefined mesh). Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one.
Refine to same degree as the reference mesh minus one. Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one. Returns a boolean variable which indicates if the reference mesh has not been refined at all.
Definition at line 1862 of file refineable_mesh.cc.
References get_refinement_pattern(), and refine_base_mesh().
Referenced by refine_base_mesh_as_in_reference_mesh().
refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< unsigned > & elements_to_be_refined) [virtual]
Refine mesh by splitting the elements identified by their numbers.
Refine mesh by splitting the elements identified by their numbers.
Definition at line 1767 of file refineable_mesh.cc.
References adapt_mesh(), e, oomph::Mesh::element_pt(), and oomph::Mesh::is_mesh_distributed().
Referenced by refine_as_in_reference_mesh().
refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< RefineableElement *> & elements_to_be_refined_pt) [virtual]
Refine mesh by splitting the elements identified by their pointers.
Refine mesh by splitting the elements identified by their pointers
Definition at line 1805 of file refineable_mesh.cc.
References adapt_mesh(), e, and oomph::Mesh::is_mesh_distributed().
refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly (DocInfo & doc_info) [virtual]
Refine mesh uniformly and doc process.
Refine mesh uniformly.
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 1722 of file refineable_mesh.cc.
References adapt_mesh(), e, oomph::Mesh::element_pt(), and oomph::Mesh::nelement().
Referenced by oomph::Problem::load_balance().
refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly () [inline], [virtual]
Refine mesh uniformly.
Reimplemented from oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 411 of file refineable_mesh.h.
References oomph::RefineableMeshBase::p_refine_uniformly(), and oomph::RefineableMeshBase::refine_uniformly().
setup_tree_forest()
virtual void oomph::TreeBasedRefineableMeshBase::setup_tree_forest () [pure virtual]
Set up the tree forest associated with the Mesh (if any)
Implemented in oomph::RefineableBrickMesh< ELEMENT >, oomph::RefineableQuadMesh< ELEMENT >, oomph::RefineableLineMesh< ELEMENT >, and oomph::RefineableLineMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >.
Referenced by oomph::Mesh::distribute(), and oomph::Mesh::prune_halo_elements_and_nodes().
split_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::split_elements_if_required () [protected], [pure virtual]
Split all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any new elements that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >, and oomph::TreeBasedRefineableMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >.
Referenced by adapt_mesh().
synchronise_hanging_nodes()
void oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes (const unsigned & ncont_interpolated_values) [protected]
Synchronise the hanging nodes if the mesh is distributed.
Deal with nodes that are hanging on one process but not another (i.e. the hanging status of the haloed and halo layers disagrees)
Definition at line 2337 of file refineable_mesh.cc.
References additional_synchronise_hanging_nodes(), oomph::Mesh::Comm_pt, oomph::Global_timings::Doc_comprehensive_timings, oomph::Mesh::halo_node_pt(), oomph::Mesh::haloed_node_pt(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Hang_pt, oomph::Node::hanging_pt(), i, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::icont, oomph::Node::is_hanging(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Master_node_index, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::Mesh::nhalo_node(), oomph::Mesh::nhaloed_node(), oomph::HangInfo::nmaster(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Node_pt, oomph::Data::non_halo_proc_ID(), oomph::oomph_info, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Sending_processor, oomph::Node::set_hanging_pt(), oomph::HangInfo::set_master_node_pt(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Shared_node_id_on_sending_processor, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Shared_node_proc, oomph::Mesh::Shared_node_pt, oomph::Mesh::shared_node_pt(), oomph::TimingHelpers::timer(), and oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Weight.
Referenced by complete_hanging_nodes().
synchronise_nonhanging_nodes()
void oomph::TreeBasedRefineableMeshBase::synchronise_nonhanging_nodes () [protected]
Synchronise the positions of non-hanging nodes that depend on non-existent neighbours (e.g. h-refinement of neighbouring elements with different p-orders where the shared edge is on the outer edge of the halo layer)
Definition at line 3563 of file refineable_mesh.cc.
References oomph::Mesh::Comm_pt, oomph::FiniteElement::dim(), oomph::Global_timings::Doc_comprehensive_timings, e, oomph::FiniteElement::get_x(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::Node::is_hanging(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::ntstorage(), oomph::oomph_info, s, t, oomph::TimingHelpers::timer(), and oomph::Node::x().
uniform_refinement_level_when_pruned() [1/2]
unsigned oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () const [inline]
Level to which the mesh was uniformly refined when it was pruned (const version)
Definition at line 578 of file refineable_mesh.h.
Referenced by oomph::Problem::load_balance(), and oomph::Mesh::prune_halo_elements_and_nodes().
uniform_refinement_level_when_pruned() [2/2]
unsigned& oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () [inline]
Level to which the mesh was uniformly refined when it was pruned.
Definition at line 585 of file refineable_mesh.h.
unrefine_uniformly()
unsigned oomph::TreeBasedRefineableMeshBase::unrefine_uniformly () [virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Unrefine mesh uniformly. Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
Definition at line 2107 of file refineable_mesh.cc.
References adapt(), complete_hanging_nodes_recursively(), e, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), oomph::RefineableMeshBase::min_permitted_error(), and oomph::Mesh::nelement().
Referenced by refine_base_mesh().
Member Data Documentation
Forest_pt
TreeForest* oomph::TreeBasedRefineableMeshBase::Forest_pt [protected]
Forest representation of the mesh.
Definition at line 727 of file refineable_mesh.h.
Referenced by adapt_mesh(), oomph::RefineableLineMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::setup_binary_tree_forest(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
Max_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_p_refinement_level [protected]
Max. permissible p-refinement level (relative to base mesh)
Definition at line 721 of file refineable_mesh.h.
Max_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_refinement_level [protected]
Max. permissible refinement level (relative to base mesh)
Definition at line 715 of file refineable_mesh.h.
Min_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_p_refinement_level [protected]
Min. permissible p-refinement level (relative to base mesh)
Definition at line 724 of file refineable_mesh.h.
Min_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_refinement_level [protected]
Min. permissible refinement level (relative to base mesh)
Definition at line 718 of file refineable_mesh.h.
Uniform_refinement_level_when_pruned
unsigned oomph::TreeBasedRefineableMeshBase::Uniform_refinement_level_when_pruned [protected]
Level to which the mesh was uniformly refined when it was pruned.
Definition at line 712 of file refineable_mesh.h.
The documentation for this class was generated from the following files:
refineable_mesh.h
refineable_mesh.cc