oomph::UnsteadyHeatFluxElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied flux on the boundaries of UnsteadyHeat elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <unsteady_heat_flux_elements.h>
Public Types
typedef void(* UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Public Member Functions
UnsteadyHeatFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
UnsteadyHeatFluxElement (const UnsteadyHeatFluxElement &dummy)
Broken copy constructor.
UnsteadyHeatPrescribedFluxFctPt & flux_fct_pt ()
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry: The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const double &time, const Vector< double > &x, double &flux)
Private Member Functions
void fill_in_generic_residual_contribution_ust_heat_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute the element residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
UnsteadyHeatPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
unsigned Dim
The spatial dimension of the problem.
unsigned U_index_ust_heat
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::UnsteadyHeatFluxElement< ELEMENT >
A class for elements that allow the imposition of an applied flux on the boundaries of UnsteadyHeat elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 59 of file unsteady_heat_flux_elements.h.
Member Typedef Documentation
UnsteadyHeatPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Definition at line 69 of file unsteady_heat_flux_elements.h.
Constructor & Destructor Documentation
UnsteadyHeatFluxElement() [1/2]
template<class ELEMENT >
oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
Definition at line 213 of file unsteady_heat_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::UnsteadyHeatFluxElement< ELEMENT >::Dim, oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux(), oomph::UnsteadyHeatFluxElement< ELEMENT >::Flux_fct_pt, oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::U_index_ust_heat.
UnsteadyHeatFluxElement() [2/2]
template<class ELEMENT >
oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement (const UnsteadyHeatFluxElement< ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 78 of file unsteady_heat_flux_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 107 of file unsteady_heat_flux_elements.h.
References oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the element residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 97 of file unsteady_heat_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux().
fill_in_generic_residual_contribution_ust_heat_flux()
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Compute the element residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 372 of file unsteady_heat_flux_elements.h.
References oomph::UnsteadyHeatFluxElement< ELEMENT >::Dim, oomph::UnsteadyHeatFluxElement< ELEMENT >::get_flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), s, oomph::UnsteadyHeatFluxElement< ELEMENT >::shape_and_test(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::UnsteadyHeatFluxElement< ELEMENT >::U_index_ust_heat, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::UnsteadyHeatFluxElement< ELEMENT >::get_flux(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
flux_fct_pt()
template<class ELEMENT >
UnsteadyHeatPrescribedFluxFctPt& oomph::UnsteadyHeatFluxElement< ELEMENT >::flux_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-flux function pointer
Definition at line 94 of file unsteady_heat_flux_elements.h.
References oomph::UnsteadyHeatFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::get_flux (const double & time, const Vector< double > & x, double & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position and at a gien time
Definition at line 166 of file unsteady_heat_flux_elements.h.
References oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::Flux_fct_pt.
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux().
output() [1/4]
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 126 of file unsteady_heat_flux_elements.h.
References oomph::output().
output() [2/4]
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 130 of file unsteady_heat_flux_elements.h.
References oomph::output().
output() [3/4]
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 135 of file unsteady_heat_flux_elements.h.
References oomph::output().
output() [4/4]
template<class ELEMENT >
void oomph::UnsteadyHeatFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 140 of file unsteady_heat_flux_elements.h.
References oomph::output().
shape_and_test()
template<class ELEMENT >
double oomph::UnsteadyHeatFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 148 of file unsteady_heat_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape().
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux().
zeta_nodal()
template<class ELEMENT >
double oomph::UnsteadyHeatFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry: The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 120 of file unsteady_heat_flux_elements.h.
References oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::UnsteadyHeatFluxElement< ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 195 of file unsteady_heat_flux_elements.h.
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
Flux_fct_pt
template<class ELEMENT >
UnsteadyHeatPrescribedFluxFctPt oomph::UnsteadyHeatFluxElement< ELEMENT >::Flux_fct_pt [private]
Function pointer to the (global) prescribed-flux function.
Definition at line 192 of file unsteady_heat_flux_elements.h.
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::flux_fct_pt(), oomph::UnsteadyHeatFluxElement< ELEMENT >::get_flux(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
U_index_ust_heat
template<class ELEMENT >
unsigned oomph::UnsteadyHeatFluxElement< ELEMENT >::U_index_ust_heat [private]
The index at which the unknown is stored at the nodes.
Definition at line 198 of file unsteady_heat_flux_elements.h.
Referenced by oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
The documentation for this class was generated from the following file:
unsteady_heat_flux_elements.h