oomph::DampedJacobi< MATRIX > Class Template Reference
#include <iterative_linear_solver.h>
Public Member Functions
DampedJacobi (const double &omega=2.0/3.0)
Empty constructor.
~DampedJacobi ()
Empty destructor.
DampedJacobi (const DampedJacobi &)
Broken copy constructor.
void operator= (const DampedJacobi &)
Broken assignment operator.
void clean_up_memory ()
Cleanup data that's stored for resolve (if any has been stored)
void smoother_setup (DoubleMatrixBase *matrix_pt)
Setup: Pass pointer to the matrix and store in cast form.
void extract_diagonal_entries (DoubleMatrixBase *matrix_pt)
Function to extract the diagonal entries from the matrix.
void smoother_solve (const DoubleVector &rhs, DoubleVector &solution)
The smoother_solve function performs fixed number of iterations on the system A*result=rhs. The number of (smoothing) iterations is the same as the max. number of iterations in the underlying IterativeLinearSolver class.
void solve (Problem *const &problem_pt, DoubleVector &result)
Use damped Jacobi iteration as an IterativeLinearSolver: This obtains the Jacobian matrix J and the residual vector r (needed for the Newton method) from the problem's get_jacobian function and returns the result of Jx=r.
void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
void resolve (const DoubleVector &rhs, DoubleVector &result)
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
unsigned iterations () const
Number of iterations taken.
Private Member Functions
void solve_helper (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
This is where the actual work is done -- different implementations for different matrix types.
Private Attributes
MATRIX * Matrix_pt
Pointer to the matrix.
Vector< double > Matrix_diagonal
Vector containing the diagonal entries of A.
bool Resolving
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
bool Matrix_can_be_deleted
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
unsigned Iterations
Number of iterations taken.
double Omega
Damping factor.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::DampedJacobi< MATRIX >
Damped Jacobi `solver` templated by matrix type. The `solver` exists in many different incarnations: It's an IterativeLinearSolver, and a Smoother, all of which use the same basic iteration.
Definition at line 1012 of file iterative_linear_solver.h.
Constructor & Destructor Documentation
DampedJacobi() [1/2]
template<typename MATRIX >
oomph::DampedJacobi< MATRIX >::DampedJacobi (const double & omega = 2.0/3.0) [inline]
Empty constructor.
Definition at line 1018 of file iterative_linear_solver.h.
 DampedJacobi()
template<typename MATRIX >
oomph::DampedJacobi< MATRIX >::~DampedJacobi () [inline]
Empty destructor.
Definition at line 1025 of file iterative_linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
DampedJacobi() [2/2]
template<typename MATRIX >
oomph::DampedJacobi< MATRIX >::DampedJacobi (const DampedJacobi< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 1032 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::clean_up_memory () [inline], [virtual]
Cleanup data that's stored for resolve (if any has been stored)
Reimplemented from oomph::LinearSolver.
Definition at line 1044 of file iterative_linear_solver.h.
extract_diagonal_entries()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::extract_diagonal_entries (DoubleMatrixBase * matrix_pt) [inline]
Function to extract the diagonal entries from the matrix.
Definition at line 1073 of file iterative_linear_solver.h.
References i.
iterations()
template<typename MATRIX >
unsigned oomph::DampedJacobi< MATRIX >::iterations () const [inline], [virtual]
Number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 1201 of file iterative_linear_solver.h.
operator=()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::operator= (const DampedJacobi< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 1038 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_assign().
resolve()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::resolve (const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
Reimplemented from oomph::LinearSolver.
Definition at line 1179 of file iterative_linear_solver.h.
References oomph::LinearSolver::solve().
smoother_setup()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::smoother_setup (DoubleMatrixBase * matrix_pt) [inline], [virtual]
Setup: Pass pointer to the matrix and store in cast form.
Implements oomph::Smoother.
Definition at line 1059 of file iterative_linear_solver.h.
smoother_solve()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::smoother_solve (const DoubleVector & rhs, DoubleVector & solution) [inline], [virtual]
The smoother_solve function performs fixed number of iterations on the system A*result=rhs. The number of (smoothing) iterations is the same as the max. number of iterations in the underlying IterativeLinearSolver class.
Implements oomph::Smoother.
Definition at line 1132 of file iterative_linear_solver.h.
References oomph::LinearSolver::solve().
solve() [1/2]
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::solve (Problem *const & problem_pt, DoubleVector & result) [virtual]
Use damped Jacobi iteration as an IterativeLinearSolver: This obtains the Jacobian matrix J and the residual vector r (needed for the Newton method) from the problem's get_jacobian function and returns the result of Jx=r.
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Definition at line 1886 of file iterative_linear_solver.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::LinearSolver::clean_up_memory(), oomph::Problem::communicator_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::Problem::get_jacobian(), oomph::IterativeLinearSolver::Jacobian_setup_time, oomph::Problem::ndof(), oomph::oomph_info, oomph::TimingHelpers::timer(), and oomph::Smoother::Use_as_smoother.
solve() [2/2]
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented from oomph::LinearSolver.
Definition at line 1149 of file iterative_linear_solver.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), and oomph::LinearSolver::Enable_resolve.
solve_helper()
template<typename MATRIX >
void oomph::DampedJacobi< MATRIX >::solve_helper (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [private]
This is where the actual work is done -- different implementations for different matrix types.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Definition at line 1951 of file iterative_linear_solver.cc.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, i, oomph::IterativeLinearSolver::Max_iter, oomph::DoubleMatrixBase::multiply(), oomph::DoubleVector::norm(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, oomph::DoubleMatrixBase::residual(), oomph::IterativeLinearSolver::Solution_time, oomph::Global_string_for_annotation::string(), oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), oomph::IterativeLinearSolver::Tolerance, and oomph::Smoother::Use_as_smoother.
Member Data Documentation
Iterations
template<typename MATRIX >
unsigned oomph::DampedJacobi< MATRIX >::Iterations [private]
Number of iterations taken.
Definition at line 1230 of file iterative_linear_solver.h.
Matrix_can_be_deleted
template<typename MATRIX >
bool oomph::DampedJacobi< MATRIX >::Matrix_can_be_deleted [private]
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
Definition at line 1227 of file iterative_linear_solver.h.
Matrix_diagonal
template<typename MATRIX >
Vector<double> oomph::DampedJacobi< MATRIX >::Matrix_diagonal [private]
Vector containing the diagonal entries of A.
Definition at line 1219 of file iterative_linear_solver.h.
Matrix_pt
template<typename MATRIX >
MATRIX* oomph::DampedJacobi< MATRIX >::Matrix_pt [private]
Pointer to the matrix.
Definition at line 1216 of file iterative_linear_solver.h.
Omega
template<typename MATRIX >
double oomph::DampedJacobi< MATRIX >::Omega [private]
Damping factor.
Definition at line 1233 of file iterative_linear_solver.h.
Resolving
template<typename MATRIX >
bool oomph::DampedJacobi< MATRIX >::Resolving [private]
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
Definition at line 1223 of file iterative_linear_solver.h.
The documentation for this class was generated from the following files:
iterative_linear_solver.h
iterative_linear_solver.cc