oomph::PolarStressIntegralElement< ELEMENT > Class Template Reference
#include <polar_stress_integral_elements.h>
Public Member Functions
const double & alpha () const
Alpha.
double *& alpha_pt ()
Pointer to Alpha.
const int boundary () const
Boundary.
void set_boundary (int bound)
Function to set boundary.
double get_shear_stress ()
Function to calculate the shear stress along boundary.
PolarStressIntegralElement (FiniteElement *const &element_pt, const int &face_index)
~PolarStressIntegralElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Compute the element's residual Vector and the jacobian matrix Plus the mass matrix especially for eigenvalue problems.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
double u (const unsigned &l, const unsigned &i)
local velocities
double x (const unsigned &l, const unsigned &i)
local position
Protected Member Functions
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
Protected Attributes
double * Alpha_pt
Pointer to the angle alpha.
int Boundary
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to an imposed traction function.
unsigned Dim
The highest dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PolarStressIntegralElement< ELEMENT >
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometery<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 56 of file polar_stress_integral_elements.h.
Constructor & Destructor Documentation
PolarStressIntegralElement()
template<class ELEMENT >
oomph::PolarStressIntegralElement< ELEMENT >::PolarStressIntegralElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit
Definition at line 124 of file polar_stress_integral_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), and oomph::FiniteElement::node_pt().
 PolarStressIntegralElement()
template<class ELEMENT >
oomph::PolarStressIntegralElement< ELEMENT >::~PolarStressIntegralElement () [inline]
Destructor should not delete anything.
Definition at line 162 of file polar_stress_integral_elements.h.
Member Function Documentation
alpha()
template<class ELEMENT >
const double& oomph::PolarStressIntegralElement< ELEMENT >::alpha () const [inline]
Alpha.
Definition at line 108 of file polar_stress_integral_elements.h.
References oomph::PolarStressIntegralElement< ELEMENT >::Alpha_pt.
alpha_pt()
template<class ELEMENT >
double* & oomph::PolarStressIntegralElement< ELEMENT >::alpha_pt () [inline]
Pointer to Alpha.
Definition at line 111 of file polar_stress_integral_elements.h.
References oomph::PolarStressIntegralElement< ELEMENT >::Alpha_pt.
boundary()
template<class ELEMENT >
const int oomph::PolarStressIntegralElement< ELEMENT >::boundary () const [inline]
Boundary.
Definition at line 114 of file polar_stress_integral_elements.h.
References oomph::PolarStressIntegralElement< ELEMENT >::Boundary.
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 171 of file polar_stress_integral_elements.h.
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix Plus the mass matrix especially for eigenvalue problems.
Reimplemented from oomph::GeneralisedElement.
Definition at line 179 of file polar_stress_integral_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 165 of file polar_stress_integral_elements.h.
get_shear_stress()
template<class ELEMENT >
double oomph::PolarStressIntegralElement< ELEMENT >::get_shear_stress ()
Function to calculate the shear stress along boundary.
Function that returns the shear stress.
Definition at line 208 of file polar_stress_integral_elements.h.
References oomph::FaceElement::Bulk_element_pt, oomph::PolarStressIntegralElement< ELEMENT >::Dim, i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::PolarStressIntegralElement< ELEMENT >::shape_and_test_at_knot(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::PolarStressIntegralElement< ELEMENT >::set_boundary(), and oomph::PolarStressIntegralElement< ELEMENT >::x().
output() [1/2]
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 187 of file polar_stress_integral_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 190 of file polar_stress_integral_elements.h.
References oomph::FiniteElement::output().
set_boundary()
template<class ELEMENT >
void oomph::PolarStressIntegralElement< ELEMENT >::set_boundary (int bound) [inline]
Function to set boundary.
Definition at line 117 of file polar_stress_integral_elements.h.
References oomph::PolarStressIntegralElement< ELEMENT >::get_shear_stress().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::PolarStressIntegralElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 82 of file polar_stress_integral_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Referenced by oomph::PolarStressIntegralElement< ELEMENT >::get_shear_stress().
u()
template<class ELEMENT >
double oomph::PolarStressIntegralElement< ELEMENT >::u (const unsigned & l, const unsigned & i) [inline]
local velocities
Definition at line 194 of file polar_stress_integral_elements.h.
References oomph::FiniteElement::nodal_value().
u_local_eqn()
template<class ELEMENT >
virtual int oomph::PolarStressIntegralElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 77 of file polar_stress_integral_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
x()
template<class ELEMENT >
double oomph::PolarStressIntegralElement< ELEMENT >::x (const unsigned & l, const unsigned & i) [inline]
local position
Definition at line 198 of file polar_stress_integral_elements.h.
References oomph::PolarStressIntegralElement< ELEMENT >::get_shear_stress(), and oomph::FiniteElement::nodal_position().
Member Data Documentation
Alpha_pt
template<class ELEMENT >
double* oomph::PolarStressIntegralElement< ELEMENT >::Alpha_pt [protected]
Pointer to the angle alpha.
Definition at line 97 of file polar_stress_integral_elements.h.
Referenced by oomph::PolarStressIntegralElement< ELEMENT >::alpha(), and oomph::PolarStressIntegralElement< ELEMENT >::alpha_pt().
Boundary
template<class ELEMENT >
int oomph::PolarStressIntegralElement< ELEMENT >::Boundary [protected]
Definition at line 103 of file polar_stress_integral_elements.h.
Referenced by oomph::PolarStressIntegralElement< ELEMENT >::boundary().
Dim
template<class ELEMENT >
unsigned oomph::PolarStressIntegralElement< ELEMENT >::Dim [private]
The highest dimension of the problem.
Definition at line 67 of file polar_stress_integral_elements.h.
Referenced by oomph::PolarStressIntegralElement< ELEMENT >::get_shear_stress().
Traction_fct_pt
template<class ELEMENT >
void(* oomph::PolarStressIntegralElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 63 of file polar_stress_integral_elements.h.
The documentation for this class was generated from the following file:
polar_stress_integral_elements.h