oomph::GS< MATRIX > Class Template Reference
The Gauss Seidel method.
#include <iterative_linear_solver.h>
Public Member Functions
GS ()
Constructor.
virtual ~GS ()
Destructor (cleanup storage)
GS (const GS &)
Broken copy constructor.
void operator= (const GS &)
Broken assignment operator.
void disable_resolve ()
Overload disable resolve so that it cleans up memory too.
void smoother_setup (DoubleMatrixBase *matrix_pt)
Set up the smoother for the matrix specified by the pointer.
void smoother_solve (const DoubleVector &rhs, DoubleVector &result)
The smoother_solve function performs fixed number of iterations on the system A*result=rhs. The number of (smoothing) iterations is the same as the max. number of iterations in the underlying IterativeLinearSolver class.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
void resolve (const DoubleVector &rhs, DoubleVector &result)
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
double preconditioner_setup_time () const
Returns the time taken to set up the preconditioner.
unsigned iterations () const
Number of iterations taken.
Private Member Functions
void solve_helper (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
General interface to solve function.
void clean_up_memory ()
Cleanup data that's stored for resolve (if any has been stored)
Private Attributes
MATRIX * Matrix_pt
System matrix pointer in the format specified by the template argument.
unsigned Iterations
Number of iterations taken.
bool Resolving
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
bool Matrix_can_be_deleted
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::GS< MATRIX >
The Gauss Seidel method.
Definition at line 598 of file iterative_linear_solver.h.
Constructor & Destructor Documentation
GS() [1/2]
template<typename MATRIX >
oomph::GS< MATRIX >::GS () [inline]
Constructor.
Definition at line 604 of file iterative_linear_solver.h.
 GS()
template<typename MATRIX >
virtual oomph::GS< MATRIX >::~GS () [inline], [virtual]
Destructor (cleanup storage)
Definition at line 609 of file iterative_linear_solver.h.
References oomph::LinearSolver::clean_up_memory().
GS() [2/2]
template<typename MATRIX >
oomph::GS< MATRIX >::GS (const GS< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 615 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
template<typename MATRIX >
void oomph::GS< MATRIX >::clean_up_memory () [inline], [private], [virtual]
Cleanup data that's stored for resolve (if any has been stored)
Reimplemented from oomph::LinearSolver.
Definition at line 751 of file iterative_linear_solver.h.
disable_resolve()
template<typename MATRIX >
void oomph::GS< MATRIX >::disable_resolve () [inline], [virtual]
Overload disable resolve so that it cleans up memory too.
Reimplemented from oomph::LinearSolver.
Definition at line 627 of file iterative_linear_solver.h.
References oomph::LinearSolver::clean_up_memory(), and oomph::LinearSolver::disable_resolve().
iterations()
template<typename MATRIX >
unsigned oomph::GS< MATRIX >::iterations () const [inline], [virtual]
Number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 738 of file iterative_linear_solver.h.
operator=()
template<typename MATRIX >
void oomph::GS< MATRIX >::operator= (const GS< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 621 of file iterative_linear_solver.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_setup_time()
template<typename MATRIX >
double oomph::GS< MATRIX >::preconditioner_setup_time () const [inline], [virtual]
Returns the time taken to set up the preconditioner.
Reimplemented from oomph::IterativeLinearSolver.
Definition at line 728 of file iterative_linear_solver.h.
resolve()
template<typename MATRIX >
void oomph::GS< MATRIX >::resolve (const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
Reimplemented from oomph::LinearSolver.
Definition at line 706 of file iterative_linear_solver.h.
References oomph::LinearSolver::solve().
smoother_setup()
template<typename MATRIX >
void oomph::GS< MATRIX >::smoother_setup (DoubleMatrixBase * matrix_pt) [inline], [virtual]
Set up the smoother for the matrix specified by the pointer.
Implements oomph::Smoother.
Definition at line 634 of file iterative_linear_solver.h.
smoother_solve()
template<typename MATRIX >
void oomph::GS< MATRIX >::smoother_solve (const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
The smoother_solve function performs fixed number of iterations on the system A*result=rhs. The number of (smoothing) iterations is the same as the max. number of iterations in the underlying IterativeLinearSolver class.
Implements oomph::Smoother.
Definition at line 651 of file iterative_linear_solver.h.
References oomph::LinearSolver::solve().
solve() [1/3]
template<typename MATRIX >
void oomph::GS< MATRIX >::solve (Problem *const & problem_pt, DoubleVector & result) [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Definition at line 1133 of file iterative_linear_solver.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::LinearSolver::clean_up_memory(), oomph::Problem::communicator_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::Problem::get_jacobian(), oomph::IterativeLinearSolver::Jacobian_setup_time, oomph::Problem::ndof(), oomph::oomph_info, oomph::TimingHelpers::timer(), and oomph::Smoother::Use_as_smoother.
solve() [2/3]
template<typename MATRIX >
void oomph::GS< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented from oomph::LinearSolver.
Definition at line 667 of file iterative_linear_solver.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), and oomph::LinearSolver::Enable_resolve.
solve() [3/3]
template<typename MATRIX >
void oomph::GS< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
Reimplemented from oomph::LinearSolver.
Definition at line 696 of file iterative_linear_solver.h.
References oomph::LinearSolver::solve().
solve_helper()
template<typename MATRIX >
void oomph::GS< MATRIX >::solve_helper (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [private]
General interface to solve function.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Definition at line 1194 of file iterative_linear_solver.cc.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, i, oomph::IterativeLinearSolver::Max_iter, oomph::DoubleVector::norm(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, oomph::DoubleMatrixBase::residual(), oomph::IterativeLinearSolver::Solution_time, oomph::Global_string_for_annotation::string(), oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), oomph::IterativeLinearSolver::Tolerance, and oomph::Smoother::Use_as_smoother.
Member Data Documentation
Iterations
template<typename MATRIX >
unsigned oomph::GS< MATRIX >::Iterations [private]
Number of iterations taken.
Definition at line 769 of file iterative_linear_solver.h.
Matrix_can_be_deleted
template<typename MATRIX >
bool oomph::GS< MATRIX >::Matrix_can_be_deleted [private]
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
Definition at line 777 of file iterative_linear_solver.h.
Matrix_pt
template<typename MATRIX >
MATRIX* oomph::GS< MATRIX >::Matrix_pt [private]
System matrix pointer in the format specified by the template argument.
Definition at line 766 of file iterative_linear_solver.h.
Resolving
template<typename MATRIX >
bool oomph::GS< MATRIX >::Resolving [private]
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
Definition at line 773 of file iterative_linear_solver.h.
The documentation for this class was generated from the following files:
iterative_linear_solver.h
iterative_linear_solver.cc