oomph::GeneralisedTimeStepper Class Reference
Generalised timestepper that can serve a variety of purposes in continuation, bifurcation detection and periodic-orbit computations. The key generalisation is that more than one of the entries is actually a degree of freedom in the problem. These are distinct from our standard (implict) Timesteppers in which the only dof is the current value (first entry in the storage scheme). These objects will typically be used to replace exisiting timesteppers for specific tasks.
#include <generalised_timesteppers.h>
Public Member Functions
unsigned ndof_storage_entries () const
Return the number of entries that correspond to dof storage.
Protected Member Functions
GeneralisedTimeStepper (const unsigned &n_tstorage, const unsigned &max_deriv, const unsigned &ndof_storage_entries=1)
GeneralisedTimeStepper ()
Broken empty constructor.
GeneralisedTimeStepper (const GeneralisedTimeStepper &)
Broken copy constructor.
void operator= (const GeneralisedTimeStepper &)
Broken assignment operator.
Protected Attributes
unsigned Ndof_storage_entries
Detailed Description
Generalised timestepper that can serve a variety of purposes in continuation, bifurcation detection and periodic-orbit computations. The key generalisation is that more than one of the entries is actually a degree of freedom in the problem. These are distinct from our standard (implict) Timesteppers in which the only dof is the current value (first entry in the storage scheme). These objects will typically be used to replace exisiting timesteppers for specific tasks.
Definition at line 55 of file generalised_timesteppers.h.
Constructor & Destructor Documentation
GeneralisedTimeStepper() [1/3]
oomph::GeneralisedTimeStepper::GeneralisedTimeStepper (const unsigned & n_tstorage, const unsigned & max_deriv, const unsigned & ndof_storage_entries = 1) [inline], [protected]
Constructor that can only be called by derived objects. Pass the information directly through to the TimeStepper object
Definition at line 68 of file generalised_timesteppers.h.
GeneralisedTimeStepper() [2/3]
oomph::GeneralisedTimeStepper::GeneralisedTimeStepper () [inline], [protected]
Broken empty constructor.
Definition at line 77 of file generalised_timesteppers.h.
GeneralisedTimeStepper() [3/3]
oomph::GeneralisedTimeStepper::GeneralisedTimeStepper (const GeneralisedTimeStepper &) [inline], [protected]
Broken copy constructor.
Definition at line 80 of file generalised_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
ndof_storage_entries()
unsigned oomph::GeneralisedTimeStepper::ndof_storage_entries () const [inline]
Return the number of entries that correspond to dof storage.
Definition at line 94 of file generalised_timesteppers.h.
References Ndof_storage_entries.
Referenced by oomph::ContinuationStorageScheme::modify_storage().
operator=()
void oomph::GeneralisedTimeStepper::operator= (const GeneralisedTimeStepper &) [inline], [protected]
Broken assignment operator.
Definition at line 86 of file generalised_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
Member Data Documentation
Ndof_storage_entries
unsigned oomph::GeneralisedTimeStepper::Ndof_storage_entries [protected]
Definition at line 61 of file generalised_timesteppers.h.
Referenced by oomph::ContinuationStorageScheme::modify_storage(), ndof_storage_entries(), oomph::ContinuationStorageScheme::set_consistent_pinned_positions(), and oomph::ContinuationStorageScheme::set_consistent_pinned_values().
The documentation for this class was generated from the following file:
generalised_timesteppers.h