oomph::QUnsteadyHeatElement< DIM, NNODE_1D > Class Template Reference
#include <unsteady_heat_elements.h>
Public Member Functions
QUnsteadyHeatElement ()
Constructor: Call constructors for QElement and UnsteadyHeat equations.
QUnsteadyHeatElement (const QUnsteadyHeatElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QUnsteadyHeatElement< DIM, NNODE_1D >
QUnsteadyHeatElement elements are linear/quadrilateral/brick-shaped UnsteadyHeat elements with isoparametric interpolation for the function.
Definition at line 472 of file unsteady_heat_elements.h.
Constructor & Destructor Documentation
QUnsteadyHeatElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::QUnsteadyHeatElement () [inline]
Constructor: Call constructors for QElement and UnsteadyHeat equations.
Definition at line 485 of file unsteady_heat_elements.h.
QUnsteadyHeatElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::QUnsteadyHeatElement (const QUnsteadyHeatElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 490 of file unsteady_heat_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_ust_heat()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::UnsteadyHeatEquations< DIM >.
Definition at line 615 of file unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat().
dshape_and_dtest_eulerian_ust_heat()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::UnsteadyHeatEquations< DIM >.
Definition at line 582 of file unsteady_heat_elements.h.
References oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_ust_heat(), oomph::FiniteElement::dshape_eulerian(), and i.
Referenced by oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output_fct().
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 508 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 514 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 520 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 526 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 532 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::UnsteadyHeatEquations< DIM >.
Definition at line 542 of file unsteady_heat_elements.h.
References oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::output_fct(), and s.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 503 of file unsteady_heat_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 479 of file unsteady_heat_elements.h.
The documentation for this class was generated from the following files:
unsteady_heat_elements.h
unsteady_heat_elements.cc