oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > Class Template Reference
#include <pml_fourier_decomposed_helmholtz_elements.h>
Public Member Functions
QPMLFourierDecomposedHelmholtzElement ()
Constructor: Call constructors for QElement and PMLFourierDecomposedHelmholtz equations.
QPMLFourierDecomposedHelmholtzElement (const QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > &dummy)
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D, class PML_ELEMENT>
class oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >
QPMLFourierDecomposedHelmholtzElement elements are linear/quadrilateral/brick-shaped PMLFourierDecomposedHelmholtz elements with isoparametric interpolation for the function.
Definition at line 520 of file pml_fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
QPMLFourierDecomposedHelmholtzElement() [1/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::QPMLFourierDecomposedHelmholtzElement () [inline]
Constructor: Call constructors for QElement and PMLFourierDecomposedHelmholtz equations.
Definition at line 536 of file pml_fourier_decomposed_helmholtz_elements.h.
QPMLFourierDecomposedHelmholtzElement() [2/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::QPMLFourierDecomposedHelmholtzElement (const QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 541 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D, class PML_ELEMENT >
double oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLFourierDecomposedHelmholtzEquationsBase.
Definition at line 689 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz().
dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D, class PML_ELEMENT >
double oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLFourierDecomposedHelmholtzEquationsBase.
Definition at line 660 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz().
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct().
output() [1/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 562 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 567 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 581 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 586 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output().
output_fct() [1/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 591 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Reimplemented from oomph::FiniteElement.
Definition at line 616 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::output_fct(), and s.
output_real()
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_real (std::ostream & outfile, const double & phi, const unsigned & n_plot) [inline]
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Definition at line 575 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_real().
output_real_fct()
template<unsigned NNODE_1D, class PML_ELEMENT>
void oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Definition at line 603 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::PMLFourierDecomposedHelmholtzEquationsBase::output_real_fct().
required_nvalue()
template<unsigned NNODE_1D, class PML_ELEMENT>
unsigned oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 558 of file pml_fourier_decomposed_helmholtz_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D, class PML_ELEMENT>
const unsigned oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D, PML_ELEMENT >::Initial_Nvalue [static], [private]
Static int that holds the number of variables at nodes: always the same.
Definition at line 529 of file pml_fourier_decomposed_helmholtz_elements.h.
The documentation for this class was generated from the following file:
pml_fourier_decomposed_helmholtz_elements.h