oomph::HelmholtzGMRESMG< MATRIX > Class Template Reference
The GMRES method for the Helmholtz solver.
#include <complex_smoother.h>
Public Member Functions
HelmholtzGMRESMG ()
Constructor.
virtual ~HelmholtzGMRESMG ()
Destructor (cleanup storage)
HelmholtzGMRESMG (const HelmholtzGMRESMG &)
Broken copy constructor.
void operator= (const HelmholtzGMRESMG &)
Broken assignment operator.
void disable_resolve ()
Overload disable resolve so that it cleans up memory too.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Implementation of the pure virtual base class function. The function has been broken because this is meant to be used as a linear solver.
void setup ()
Implementation of the pure virtual base class function. This accompanies the preconditioner_solve function and so is also broken.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
void resolve (const DoubleVector &rhs, DoubleVector &result)
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
unsigned iterations () const
Number of iterations taken.
void set_preconditioner_LHS ()
Set left preconditioning (the default)
void set_preconditioner_RHS ()
Enable right preconditioning.
Protected Member Functions
void solve_helper (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &solution)
General interface to solve function.
void clean_up_memory ()
Cleanup data that's stored for resolve (if any has been stored)
void complex_matrix_multiplication (Vector< CRDoubleMatrix *> const matrices_pt, const Vector< DoubleVector > &x, Vector< DoubleVector > &soln)
Helper function to calculate a complex matrix-vector product. Assumes the matrix has been provided as a Vector of length two; the first entry containing the real part of the system matrix and the second entry containing the imaginary part.
void update (const unsigned &k, const Vector< Vector< std::complex< double > > > &hessenberg, const Vector< std::complex< double > > &s, const Vector< Vector< DoubleVector > > &v, Vector< DoubleVector > &x)
Helper function to update the result vector.
void generate_plane_rotation (std::complex< double > &dx, std::complex< double > &dy, std::complex< double > &cs, std::complex< double > &sn)
Helper function: Generate a plane rotation. This is done by finding the value of $ \cos(\theta) $ (i.e. cs) and the value of $ \sin(\theta) $ (i.e. sn) such that:
 \begin{bmatrix} \overline{\cos\theta} & \overline{\sin\theta} \\ -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \\ dy \end{bmatrix} = \begin{bmatrix} r \\ 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(|dx|,2)+pow(|dy|,2)} $. The values of a and b are given by: The values of dx and dy are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{|dx|^2+|dy|^2}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{|dx|^2+|dy|^2}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.193. We also check to see that sn is always a real (nonnegative) number. See pp.193-194 for an explanation.
void apply_plane_rotation (std::complex< double > &dx, std::complex< double > &dy, std::complex< double > &cs, std::complex< double > &sn)
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \\ dy \end{bmatrix} \leftarrow \begin{bmatrix} \overline{\cos\theta} & \overline{\sin\theta} \\ -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \\ dy \end{bmatrix}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.193.
Protected Attributes
unsigned Iterations
Number of iterations taken.
Vector< CRDoubleMatrix * > Matrices_storage_pt
Vector of pointers to the real and imaginary part of the system matrix.
bool Resolving
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
bool Matrix_can_be_deleted
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
bool Preconditioner_LHS
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::HelmholtzGMRESMG< MATRIX >
The GMRES method for the Helmholtz solver.
Definition at line 1762 of file complex_smoother.h.
Constructor & Destructor Documentation
HelmholtzGMRESMG() [1/2]
template<typename MATRIX >
oomph::HelmholtzGMRESMG< MATRIX >::HelmholtzGMRESMG () [inline]
Constructor.
Definition at line 1768 of file complex_smoother.h.
 HelmholtzGMRESMG()
template<typename MATRIX >
virtual oomph::HelmholtzGMRESMG< MATRIX >::~HelmholtzGMRESMG () [inline], [virtual]
Destructor (cleanup storage)
Definition at line 1778 of file complex_smoother.h.
References oomph::LinearSolver::clean_up_memory().
HelmholtzGMRESMG() [2/2]
template<typename MATRIX >
oomph::HelmholtzGMRESMG< MATRIX >::HelmholtzGMRESMG (const HelmholtzGMRESMG< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 1784 of file complex_smoother.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
apply_plane_rotation()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::apply_plane_rotation (std::complex< double > & dx, std::complex< double > & dy, std::complex< double > & cs, std::complex< double > & sn) [inline], [protected]
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \\ dy \end{bmatrix} \leftarrow \begin{bmatrix} \overline{\cos\theta} & \overline{\sin\theta} \\ -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \\ dy \end{bmatrix}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.193.
Definition at line 2462 of file complex_smoother.h.
clean_up_memory()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::clean_up_memory () [inline], [protected], [virtual]
Cleanup data that's stored for resolve (if any has been stored)
Reimplemented from oomph::LinearSolver.
Definition at line 2080 of file complex_smoother.h.
complex_matrix_multiplication()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::complex_matrix_multiplication (Vector< CRDoubleMatrix *> const matrices_pt, const Vector< DoubleVector > & x, Vector< DoubleVector > & soln) [inline], [protected]
Helper function to calculate a complex matrix-vector product. Assumes the matrix has been provided as a Vector of length two; the first entry containing the real part of the system matrix and the second entry containing the imaginary part.
Definition at line 2113 of file complex_smoother.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt().
disable_resolve()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::disable_resolve () [inline], [virtual]
Overload disable resolve so that it cleans up memory too.
Reimplemented from oomph::LinearSolver.
Definition at line 1796 of file complex_smoother.h.
References oomph::LinearSolver::clean_up_memory(), and oomph::LinearSolver::disable_resolve().
generate_plane_rotation()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation (std::complex< double > & dx, std::complex< double > & dy, std::complex< double > & cs, std::complex< double > & sn) [inline], [protected]
Helper function: Generate a plane rotation. This is done by finding the value of $ \cos(\theta) $ (i.e. cs) and the value of $ \sin(\theta) $ (i.e. sn) such that:
 \begin{bmatrix} \overline{\cos\theta} & \overline{\sin\theta} \\ -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \\ dy \end{bmatrix} = \begin{bmatrix} r \\ 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(|dx|,2)+pow(|dy|,2)} $. The values of a and b are given by: The values of dx and dy are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{|dx|^2+|dy|^2}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{|dx|^2+|dy|^2}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.193. We also check to see that sn is always a real (nonnegative) number. See pp.193-194 for an explanation.
Definition at line 2370 of file complex_smoother.h.
References oomph::IterativeLinearSolver::tolerance().
iterations()
template<typename MATRIX >
unsigned oomph::HelmholtzGMRESMG< MATRIX >::iterations () const [inline], [virtual]
Number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 2061 of file complex_smoother.h.
operator=()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::operator= (const HelmholtzGMRESMG< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 1790 of file complex_smoother.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Implementation of the pure virtual base class function. The function has been broken because this is meant to be used as a linear solver.
Implements oomph::Preconditioner.
Definition at line 1805 of file complex_smoother.h.
resolve()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::resolve (const DoubleVector & rhs, DoubleVector & result) [inline], [virtual]
Re-solve the system defined by the last assembled Jacobian and the rhs vector specified here. Solution is returned in the vector result.
Reimplemented from oomph::LinearSolver.
Definition at line 2027 of file complex_smoother.h.
set_preconditioner_LHS()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::set_preconditioner_LHS () [inline]
Set left preconditioning (the default)
Definition at line 2067 of file complex_smoother.h.
set_preconditioner_RHS()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::set_preconditioner_RHS () [inline]
Enable right preconditioning.
Definition at line 2070 of file complex_smoother.h.
setup()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::setup () [inline], [virtual]
Implementation of the pure virtual base class function. This accompanies the preconditioner_solve function and so is also broken.
Implements oomph::Preconditioner.
Definition at line 1823 of file complex_smoother.h.
solve() [1/3]
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::solve (Problem *const & problem_pt, DoubleVector & result) [inline], [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Reimplemented in oomph::HelmholtzFGMRESMG< MATRIX >.
Definition at line 1841 of file complex_smoother.h.
References oomph::DoubleVector::build(), oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DoubleVector::built(), oomph::LinearSolver::clean_up_memory(), oomph::MPI_Helpers::communicator_pt(), oomph::Problem::communicator_pt(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::LinearSolver::Doc_time, oomph::LinearSolver::Enable_resolve, oomph::Problem::get_jacobian(), i, oomph::IterativeLinearSolver::Jacobian_setup_time, oomph::Problem::mesh_pt(), oomph::Problem::ndof(), oomph::oomph_info, oomph::DoubleVector::redistribute(), and oomph::TimingHelpers::timer().
solve() [2/3]
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented from oomph::LinearSolver.
Definition at line 1997 of file complex_smoother.h.
solve() [3/3]
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::solve (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) [inline], [virtual]
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system Call the broken base-class version. If you want this, please implement it.
Reimplemented from oomph::LinearSolver.
Definition at line 2019 of file complex_smoother.h.
References oomph::LinearSolver::solve().
solve_helper()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::solve_helper (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & solution) [protected]
General interface to solve function.
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system. based on the algorithm presented in Templates for the Solution of Linear Systems: Building Blocks for Iterative Methods, Barrett, Berry et al, SIAM, 2006 and the implementation in the IML++ library : http://math.nist.gov/iml++/
Definition at line 2510 of file complex_smoother.h.
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::HelmholtzSmoother::complex_matrix_multiplication(), oomph::LinearAlgebraDistribution::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, i, oomph::DoubleVector::initialise(), oomph::IterativeLinearSolver::Max_iter, oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, oomph::IterativeLinearSolver::preconditioner_pt(), oomph::IterativeLinearSolver::Preconditioner_setup_time, oomph::Preconditioner::preconditioner_solve(), s, oomph::Preconditioner::setup(), oomph::IterativeLinearSolver::Setup_preconditioner_before_solve, oomph::IterativeLinearSolver::Solution_time, oomph::Global_string_for_annotation::string(), oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), and oomph::IterativeLinearSolver::Tolerance.
update()
template<typename MATRIX >
void oomph::HelmholtzGMRESMG< MATRIX >::update (const unsigned & k, const Vector< Vector< std::complex< double > > > & hessenberg, const Vector< std::complex< double > > & s, const Vector< Vector< DoubleVector > > & v, Vector< DoubleVector > & x) [inline], [protected]
Helper function to update the result vector.
Definition at line 2211 of file complex_smoother.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), i, oomph::IterativeLinearSolver::preconditioner_pt(), oomph::Preconditioner::preconditioner_solve(), and s.
Member Data Documentation
Iterations
template<typename MATRIX >
unsigned oomph::HelmholtzGMRESMG< MATRIX >::Iterations [protected]
Number of iterations taken.
Definition at line 2478 of file complex_smoother.h.
Matrices_storage_pt
template<typename MATRIX >
Vector<CRDoubleMatrix*> oomph::HelmholtzGMRESMG< MATRIX >::Matrices_storage_pt [protected]
Vector of pointers to the real and imaginary part of the system matrix.
Definition at line 2481 of file complex_smoother.h.
Matrix_can_be_deleted
template<typename MATRIX >
bool oomph::HelmholtzGMRESMG< MATRIX >::Matrix_can_be_deleted [protected]
Boolean flag to indicate if the matrix pointed to be Matrix_pt can be deleted.
Definition at line 2489 of file complex_smoother.h.
Preconditioner_LHS
template<typename MATRIX >
bool oomph::HelmholtzGMRESMG< MATRIX >::Preconditioner_LHS [protected]
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Definition at line 2493 of file complex_smoother.h.
Resolving
template<typename MATRIX >
bool oomph::HelmholtzGMRESMG< MATRIX >::Resolving [protected]
Boolean flag to indicate if the solve is done in re-solve mode, bypassing setup of matrix and preconditioner.
Definition at line 2485 of file complex_smoother.h.
The documentation for this class was generated from the following file:
complex_smoother.h