oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM > Class Template Reference
A version of the GeneralisedAdvection Diffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_gen_advection_diffusion_elements.h>
Public Member Functions
RefineableGeneralisedAdvectionDiffusionEquations ()
Empty Constructor.
RefineableGeneralisedAdvectionDiffusionEquations (const RefineableGeneralisedAdvectionDiffusionEquations< DIM > &dummy)
Broken copy constructor.
void operator= (const RefineableGeneralisedAdvectionDiffusionEquations< DIM > &)
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Protected Member Functions
void fill_in_generic_residual_contribution_cons_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >
A version of the GeneralisedAdvection Diffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 59 of file refineable_gen_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableGeneralisedAdvectionDiffusionEquations() [1/2]
template<unsigned DIM>
oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::RefineableGeneralisedAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 67 of file refineable_gen_advection_diffusion_elements.h.
RefineableGeneralisedAdvectionDiffusionEquations() [2/2]
template<unsigned DIM>
oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::RefineableGeneralisedAdvectionDiffusionEquations (const RefineableGeneralisedAdvectionDiffusionEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 75 of file refineable_gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_cons_adv_diff()
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::GeneralisedAdvectionDiffusionEquations< DIM >.
Definition at line 44 of file refineable_gen_advection_diffusion_elements.cc.
References oomph::ALE_is_disabled, oomph::OcTreeNames::D, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::pe(), oomph::pe_st(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build().
further_build()
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 163 of file refineable_gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::ALE_is_disabled, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::conserved_wind_fct_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Conserved_wind_fct_pt, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::diff_fct_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Diff_fct_pt, oomph::RefineableElement::father_element_pt(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Pe_pt, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::pe_st_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::PeSt_pt, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::source_fct_pt(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Source_fct_pt, oomph::GeneralisedAdvectionDiffusionEquations< DIM >::wind_fct_pt(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::Wind_fct_pt.
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 102 of file refineable_gen_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 133 of file refineable_gen_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::GeneralisedAdvectionDiffusionEquations< DIM >::u_index_cons_adv_diff().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 94 of file refineable_gen_advection_diffusion_elements.h.
References oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux().
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 90 of file refineable_gen_advection_diffusion_elements.h.
operator=()
template<unsigned DIM>
void oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::operator= (const RefineableGeneralisedAdvectionDiffusionEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 83 of file refineable_gen_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
refineable_gen_advection_diffusion_elements.h
refineable_gen_advection_diffusion_elements.cc