oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D > Class Template Reference
#include <Tdisplacement_based_foeppl_von_karman_elements.h>
Public Member Functions
TDisplacementBasedFoepplvonKarmanElement ()
Constructor: Call constructors for TElement and Foeppl von Karman equations.
TDisplacementBasedFoepplvonKarmanElement (const TDisplacementBasedFoepplvonKarmanElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const TDisplacementBasedFoepplvonKarmanElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 4)
unsigned ndof_types () const
The number of dof types that degrees of freedom in this element are sub-divided into.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the dof type that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Dof_types 0,1: Laplacian; 2: Bending w 3: Displacements Ux and Uy The indexing of the dofs in the element is like below
[1]: laplacian w.
void output (std::ostream &outfile)
Output function: x,y,w.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,w at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: x,y,w.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,w at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,w_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,w_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from FvK equations.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Static Private Attributes
static const unsigned Initial_Nvalue = 4
Static unsigned that holds the (same) number of variables at every node.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >
TDisplacementBasedFoepplvonKarmanElement<NNODE_1D> elements are isoparametric triangular 2-dimensional Foeppl von Karman elements with NNODE_1D nodal points along each element edge. Inherits from TElement and DisplacementBasedFoepplvonKarmanEquations
Definition at line 72 of file Tdisplacement_based_foeppl_von_karman_elements.h.
Constructor & Destructor Documentation
TDisplacementBasedFoepplvonKarmanElement() [1/2]
template<unsigned NNODE_1D>
oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::TDisplacementBasedFoepplvonKarmanElement () [inline]
Constructor: Call constructors for TElement and Foeppl von Karman equations.
Definition at line 81 of file Tdisplacement_based_foeppl_von_karman_elements.h.
TDisplacementBasedFoepplvonKarmanElement() [2/2]
template<unsigned NNODE_1D>
oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::TDisplacementBasedFoepplvonKarmanElement (const TDisplacementBasedFoepplvonKarmanElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 87 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_fvk()
template<unsigned NNODE_1D>
double oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 380 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
Referenced by oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk(), and oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output_fct().
dshape_and_dtest_eulerian_fvk()
template<unsigned NNODE_1D>
double oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 345 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk(), oomph::FiniteElement::dshape_eulerian(), i, and oomph::FiniteElement::nnode().
Referenced by oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output_fct().
get_dof_numbers_for_unknowns()
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the dof type that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Dof_types 0,1: Laplacian; 2: Bending w 3: Displacements Ux and Uy The indexing of the dofs in the element is like below
[1]: laplacian w.
Reimplemented from oomph::GeneralisedElement.
Definition at line 131 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::node_pt().
get_Z2_flux()
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from FvK equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 313 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_deflection().
ndof_types()
template<unsigned NNODE_1D>
unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::ndof_types () const [inline], [virtual]
The number of dof types that degrees of freedom in this element are sub-divided into.
Reimplemented from oomph::GeneralisedElement.
Definition at line 105 of file Tdisplacement_based_foeppl_von_karman_elements.h.
nrecovery_order()
template<unsigned NNODE_1D>
unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 307 of file Tdisplacement_based_foeppl_von_karman_elements.h.
num_Z2_flux_terms()
template<unsigned NNODE_1D>
unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 310 of file Tdisplacement_based_foeppl_von_karman_elements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 317 of file Tdisplacement_based_foeppl_von_karman_elements.h.
operator=()
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::operator= (const TDisplacementBasedFoepplvonKarmanElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 93 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,w.
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 241 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,w at n_plot^2 plot points.
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 248 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,w.
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 256 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,w at n_plot^2 plot points.
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 264 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,w_exact.
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 272 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,w_exact (calls the steady version)
Reimplemented from oomph::DisplacementBasedFoepplvonKarmanEquations.
Definition at line 281 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), and s.
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 4)
Reimplemented from oomph::FiniteElement.
Definition at line 100 of file Tdisplacement_based_foeppl_von_karman_elements.h.
References oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue.
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 321 of file Tdisplacement_based_foeppl_von_karman_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue = 4 [static], [private]
Static unsigned that holds the (same) number of variables at every node.
Definition at line 327 of file Tdisplacement_based_foeppl_von_karman_elements.h.
Referenced by oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
Tdisplacement_based_foeppl_von_karman_elements.h
Tdisplacement_based_foeppl_von_karman_elements.cc