oomph::SuperLUPreconditioner Class Reference
An interface to allow SuperLU to be used as an (exact) Preconditioner.
#include <SuperLU_preconditioner.h>
Public Member Functions
SuperLUPreconditioner ()
Constructor.
~SuperLUPreconditioner ()
Destructor.
SuperLUPreconditioner (const SuperLUPreconditioner &)
Broken copy constructor.
void operator= (const SuperLUPreconditioner &)
Broken assignment operator.
void setup ()
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Function applies SuperLU to vector r for (exact) preconditioning, this requires a call to setup(...) first.
virtual void clean_up_memory ()
Clean up memory -- forward the call to the version in SuperLU in its LinearSolver incarnation.
Private Attributes
SuperLUSolver Solver
the SuperLU solver emplyed by this preconditioner
Additional Inherited Members
Detailed Description
An interface to allow SuperLU to be used as an (exact) Preconditioner.
Definition at line 44 of file SuperLU_preconditioner.h.
Constructor & Destructor Documentation
SuperLUPreconditioner() [1/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner () [inline]
Constructor.
Definition at line 49 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::disable_doc_stats(), oomph::LinearSolver::disable_doc_time(), and Solver.
 SuperLUPreconditioner()
oomph::SuperLUPreconditioner::~SuperLUPreconditioner () [inline]
Destructor.
Definition at line 56 of file SuperLU_preconditioner.h.
SuperLUPreconditioner() [2/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner (const SuperLUPreconditioner &) [inline]
Broken copy constructor.
Definition at line 60 of file SuperLU_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
virtual void oomph::SuperLUPreconditioner::clean_up_memory () [inline], [virtual]
Clean up memory -- forward the call to the version in SuperLU in its LinearSolver incarnation.
Reimplemented from oomph::Preconditioner.
Definition at line 114 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::clean_up_memory(), and Solver.
operator=()
void oomph::SuperLUPreconditioner::operator= (const SuperLUPreconditioner &) [inline]
Broken assignment operator.
Definition at line 67 of file SuperLU_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
void oomph::SuperLUPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Function applies SuperLU to vector r for (exact) preconditioning, this requires a call to setup(...) first.
Implements oomph::Preconditioner.
Definition at line 105 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::resolve(), and Solver.
setup()
void oomph::SuperLUPreconditioner::setup () [inline], [virtual]
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 77 of file SuperLU_preconditioner.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::SuperLUSolver::factorise(), oomph::Preconditioner::matrix_pt(), oomph::oomph_info, and Solver.
Referenced by oomph::PseudoElasticPreconditioner::setup(), oomph::ExactSubBiharmonicPreconditioner::setup(), oomph::InexactSubBiharmonicPreconditioner::setup(), oomph::PseudoElasticPreconditionerOld::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), and oomph::SimpleFSIPreconditioner< MATRIX >::setup().
Member Data Documentation
Solver
SuperLUSolver oomph::SuperLUPreconditioner::Solver [private]
the SuperLU solver emplyed by this preconditioner
Definition at line 122 of file SuperLU_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), setup(), and SuperLUPreconditioner().
The documentation for this class was generated from the following file:
SuperLU_preconditioner.h