oomph::LinearisedAxisymmetricNavierStokesEquations Class Reference
A class for elements that solve the linearised version of the unsteady Navier--Stokes equations in cylindrical polar coordinates, where we have Fourier-decomposed in the azimuthal direction so that the theta-dependance is replaced by an azimuthal mode number.
#include <linearised_axisym_navier_stokes_elements.h>
Public Member Functions
LinearisedAxisymmetricNavierStokesEquations ()
Constructor: NULL the base flow solution and the derivatives of the base flow function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_axi_nst () const =0
Return the number of pressure degrees of freedom associated with a single pressure component in the element.
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const =0
Return the i-th pressure value at local pressure `node` n_p. Uses suitably interpolated value for hanging nodes.
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order)
void output (std::ostream &outfile)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction.
void output (FILE *file_pt)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
Return the i-th component of the FE interpolated velocity u[i] at local coordinate s.
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s.
Public Attributes
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
Access function for the derivatives of the base flow w.r.t. global coordinates solution pointer.
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
virtual double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
Calculate the velocity components of the base flow solution at a given time and Eulerian position.
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position.
virtual void fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Protected Attributes
double * Viscosity_Ratio_pt
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
double * Density_Ratio_pt
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
int * Azimuthal_Mode_Number_pt
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
Pointer to derivatives of base flow solution velocity components w.r.t. global coordinates (r and z) function.
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Static Private Attributes
static int Pressure_not_stored_at_node
static double Default_Physical_Constant_Value
static int Default_Azimuthal_Mode_Number_Value
Static default value for the azimuthal mode number (zero)
static double Default_Physical_Ratio_Value
Static default value for the physical ratios (all initialised to one)
Additional Inherited Members
Detailed Description
A class for elements that solve the linearised version of the unsteady Navier--Stokes equations in cylindrical polar coordinates, where we have Fourier-decomposed in the azimuthal direction so that the theta-dependance is replaced by an azimuthal mode number.
Definition at line 53 of file linearised_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
LinearisedAxisymmetricNavierStokesEquations()
oomph::LinearisedAxisymmetricNavierStokesEquations::LinearisedAxisymmetricNavierStokesEquations () [inline]
Constructor: NULL the base flow solution and the derivatives of the base flow function.
Definition at line 196 of file linearised_axisym_navier_stokes_elements.h.
References Default_Azimuthal_Mode_Number_Value, Default_Physical_Constant_Value, and Default_Physical_Ratio_Value.
Member Function Documentation
azimuthal_mode_number()
const int& oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number () const [inline]
Azimuthal mode number k in e^ik(theta) decomposition.
Definition at line 227 of file linearised_axisym_navier_stokes_elements.h.
References Azimuthal_Mode_Number_pt.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and strain_rate().
azimuthal_mode_number_pt()
int* & oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number_pt () [inline]
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
Definition at line 239 of file linearised_axisym_navier_stokes_elements.h.
References Azimuthal_Mode_Number_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
density_ratio()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio () const [inline]
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 250 of file linearised_axisym_navier_stokes_elements.h.
References Density_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
density_ratio_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio_pt () [inline]
Pointer to the density ratio.
Definition at line 253 of file linearised_axisym_navier_stokes_elements.h.
References Density_Ratio_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
disable_ALE()
void oomph::LinearisedAxisymmetricNavierStokesEquations::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 316 of file linearised_axisym_navier_stokes_elements.h.
dshape_and_dtest_eulerian_at_knot_linearised_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
dshape_and_dtest_eulerian_linearised_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
du_dt_linearised_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst (const unsigned & n, const unsigned & i) const [inline]
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 287 of file linearised_axisym_navier_stokes_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_linearised_axi_nst(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
enable_ALE()
void oomph::LinearisedAxisymmetricNavierStokesEquations::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 322 of file linearised_axisym_navier_stokes_elements.h.
References i, and p_linearised_axi_nst().
fill_in_contribution_to_jacobian()
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
Definition at line 384 of file linearised_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
Referenced by LinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), and RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 394 of file linearised_axisym_navier_stokes_elements.h.
References fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_contribution_to_residuals()
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 372 of file linearised_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_generic_residual_contribution_linearised_axi_nst()
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the linearised axisymmetric Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
Definition at line 389 of file linearised_axisym_navier_stokes_elements.cc.
References ALE_is_disabled, azimuthal_mode_number(), density_ratio(), dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), du_dt_linearised_axi_nst(), Gamma, get_base_flow_dudx(), get_base_flow_u(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_linearised_axi_nst(), oomph::Integral::nweight(), p_linearised_axi_nst(), p_local_eqn(), pshape_linearised_axi_nst(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_st(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::required_nvalue(), s, oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), u_index_linearised_axi_nst(), viscosity_ratio(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), fill_in_contribution_to_residuals(), get_base_flow_dudx(), and strain_rate().
get_base_flow_dudx()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const [inline], [protected], [virtual]
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
Definition at line 162 of file linearised_axisym_navier_stokes_elements.h.
References Base_flow_dudx_fct_pt, fill_in_generic_residual_contribution_linearised_axi_nst(), and i.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
get_base_flow_u()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const [inline], [protected], [virtual]
Calculate the velocity components of the base flow solution at a given time and Eulerian position.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
Definition at line 141 of file linearised_axisym_navier_stokes_elements.h.
References Base_flow_u_fct_pt, and i.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
interpolated_p_linearised_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s.
Definition at line 434 of file linearised_axisym_navier_stokes_elements.h.
References npres_linearised_axi_nst(), p_linearised_axi_nst(), and pshape_linearised_axi_nst().
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), and output().
interpolated_u_linearised_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return the i-th component of the FE interpolated velocity u[i] at local coordinate s.
Definition at line 405 of file linearised_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and u_index_linearised_axi_nst().
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), and output().
npres_linearised_axi_nst()
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::npres_linearised_axi_nst () const [pure virtual]
Return the number of pressure degrees of freedom associated with a single pressure component in the element.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), interpolated_p_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs().
output() [1/4]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile) [inline], [virtual]
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Definition at line 343 of file linearised_axisym_navier_stokes_elements.h.
Referenced by output(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output(), and oomph::LinearisedAxisymmetricQTaylorHoodElement::output().
output() [2/4]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction.
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Definition at line 150 of file linearised_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_axi_nst(), interpolated_u_linearised_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt) [inline], [virtual]
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Definition at line 355 of file linearised_axisym_navier_stokes_elements.h.
References output(), output_veloc(), and t.
output() [4/4]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction.
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Definition at line 200 of file linearised_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_axi_nst(), interpolated_u_linearised_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, strain_rate(), oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_veloc()
void oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function in tecplot format: Velocities only r, z, U^C, U^S, V^C, V^S, W^C, W^S at specified previous timestep (t=0 present; t>0 previous timestep). Specified number of plot points in each coordinate direction.
Definition at line 69 of file linearised_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::shape(), oomph::FiniteElement::tecplot_zone_string(), u_index_linearised_axi_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by output().
p_index_linearised_axi_nst()
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_index_linearised_axi_nst (const unsigned & i) const [inline], [virtual]
Which nodal value represents the pressure?
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement.
Definition at line 333 of file linearised_axisym_navier_stokes_elements.h.
References Pressure_not_stored_at_node, s, and strain_rate().
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::fix_pressure(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_linearised_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs().
p_linearised_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::p_linearised_axi_nst (const unsigned & n_p, const unsigned & i) const [pure virtual]
Return the i-th pressure value at local pressure `node` n_p. Uses suitably interpolated value for hanging nodes.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by enable_ALE(), fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and interpolated_p_linearised_axi_nst().
p_local_eqn()
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n, const unsigned & i) [protected], [pure virtual]
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
pshape_linearised_axi_nst() [1/2]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi) const [protected], [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), interpolated_p_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_basis(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::pshape_linearised_axi_nst(), and oomph::LinearisedAxisymmetricQTaylorHoodElement::pshape_linearised_axi_nst().
pshape_linearised_axi_nst() [2/2]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [protected], [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
re()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re () const [inline]
Reynolds number.
Definition at line 221 of file linearised_axisym_navier_stokes_elements.h.
References Re_pt.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
re_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 233 of file linearised_axisym_navier_stokes_elements.h.
References Re_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
re_st()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 224 of file linearised_axisym_navier_stokes_elements.h.
References ReSt_pt.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
re_st_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_st_pt () [inline]
Pointer to product of Reynolds and Strouhal number (=Womersley number)
Definition at line 236 of file linearised_axisym_navier_stokes_elements.h.
References ReSt_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
strain_rate()
void oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strainrate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order)
Get strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order). We evaluate this tensor at a value of theta such that the product of theta and the azimuthal mode number (k) gives $ \pi/4 $. Therefore $ \cos(k \theta) = \sin(k \theta) = 1/\sqrt{2} $.
Definition at line 253 of file linearised_axisym_navier_stokes_elements.cc.
References azimuthal_mode_number(), oomph::FiniteElement::dshape_eulerian(), e, fill_in_generic_residual_contribution_linearised_axi_nst(), i, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::DenseMatrix< T >::nrow(), and u_index_linearised_axi_nst().
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::get_Z2_flux(), output(), and p_index_linearised_axi_nst().
u_index_linearised_axi_nst()
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 282 of file linearised_axisym_navier_stokes_elements.h.
References i.
Referenced by du_dt_linearised_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), interpolated_u_linearised_axi_nst(), output_veloc(), and strain_rate().
viscosity_ratio()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio () const [inline]
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 243 of file linearised_axisym_navier_stokes_elements.h.
References Viscosity_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
viscosity_ratio_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio_pt () [inline]
Pointer to the viscosity ratio.
Definition at line 246 of file linearised_axisym_navier_stokes_elements.h.
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
Member Data Documentation
ALE_is_disabled
bool oomph::LinearisedAxisymmetricNavierStokesEquations::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 108 of file linearised_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
Azimuthal_Mode_Number_pt
int* oomph::LinearisedAxisymmetricNavierStokesEquations::Azimuthal_Mode_Number_pt [protected]
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
Definition at line 92 of file linearised_axisym_navier_stokes_elements.h.
Referenced by azimuthal_mode_number(), azimuthal_mode_number_pt(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
Base_flow_dudx_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_dudx_fct_pt) (const double &time, const Vector< double > &x, DenseMatrix< double > &result) [protected]
Pointer to derivatives of base flow solution velocity components w.r.t. global coordinates (r and z) function.
Definition at line 101 of file linearised_axisym_navier_stokes_elements.h.
Referenced by get_base_flow_dudx().
base_flow_dudx_fct_pt
void(* &)(const double& time, const Vector<double>& x, DenseMatrix<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_dudx_fct_pt() [inline]
Access function for the derivatives of the base flow w.r.t. global coordinates solution pointer.
Definition at line 265 of file linearised_axisym_navier_stokes_elements.h.
Base_flow_u_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_u_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) [protected]
Pointer to base flow solution (velocity components) function.
Definition at line 95 of file linearised_axisym_navier_stokes_elements.h.
Referenced by get_base_flow_u().
base_flow_u_fct_pt
void(* &)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_u_fct_pt() [inline]
Access function for the base flow solution pointer.
Definition at line 256 of file linearised_axisym_navier_stokes_elements.h.
Default_Azimuthal_Mode_Number_Value
int oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Azimuthal_Mode_Number_Value [static], [private]
Static default value for the azimuthal mode number (zero)
Definition at line 67 of file linearised_axisym_navier_stokes_elements.h.
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Default_Physical_Constant_Value
double oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Physical_Constant_Value [static], [private]
Static default value for the physical constants (all initialised to zero)
Definition at line 64 of file linearised_axisym_navier_stokes_elements.h.
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Default_Physical_Ratio_Value
double oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Physical_Ratio_Value [static], [private]
Static default value for the physical ratios (all initialised to one)
Definition at line 70 of file linearised_axisym_navier_stokes_elements.h.
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Density_Ratio_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::Density_Ratio_pt [protected]
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Definition at line 83 of file linearised_axisym_navier_stokes_elements.h.
Referenced by density_ratio(), density_ratio_pt(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
Gamma
Vector< double > oomph::LinearisedAxisymmetricNavierStokesEquations::Gamma [static]
Vector to decide whether the stress-divergence form is used or not.
Linearised axisymmetric Navier--Stokes equations static data.
Definition at line 215 of file linearised_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
Pressure_not_stored_at_node
int oomph::LinearisedAxisymmetricNavierStokesEquations::Pressure_not_stored_at_node [static], [private]
Static `magic` number that indicates that the pressure is not stored at a node
Definition at line 60 of file linearised_axisym_navier_stokes_elements.h.
Referenced by p_index_linearised_axi_nst().
Re_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::Re_pt [protected]
Pointer to global Reynolds number.
Definition at line 86 of file linearised_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), re(), and re_pt().
ReSt_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::ReSt_pt [protected]
Pointer to global Reynolds number x Strouhal number (=Womersley)
Definition at line 89 of file linearised_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), re_st(), and re_st_pt().
Viscosity_Ratio_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt [protected]
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Definition at line 79 of file linearised_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), viscosity_ratio(), and viscosity_ratio_pt().
The documentation for this class was generated from the following files:
linearised_axisym_navier_stokes_elements.h
linearised_axisym_navier_stokes_elements.cc