oomph::SimpleRectangularTriMesh< ELEMENT > Class Template Reference
Simple 2D triangular mesh for TElements.
#include <simple_rectangular_tri_mesh.template.h>
Public Member Functions
SimpleRectangularTriMesh (const unsigned &n_x, const unsigned &n_y, const double &l_x, const double &l_y, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor n_x : number of elements in the x direction; n_y : number of elements in the y direction; l_x : length in the x direction l_y : length in the y direction Ordering of elements: 'lower left' to 'lower right' then 'upwards'.
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Private Attributes
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y directions.
double Lx
Length of mesh in x-direction.
double Ly
Length of mesh in y-direction.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SimpleRectangularTriMesh< ELEMENT >
Simple 2D triangular mesh for TElements.
Definition at line 53 of file simple_rectangular_tri_mesh.template.h.
Constructor & Destructor Documentation
SimpleRectangularTriMesh()
template<class ELEMENT >
oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh (const unsigned & n_x, const unsigned & n_y, const double & l_x, const double & l_y, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor n_x : number of elements in the x direction; n_y : number of elements in the y direction; l_x : length in the x direction l_y : length in the y direction Ordering of elements: 'lower left' to 'lower right' then 'upwards'.
Constructor for simple 2D triangular mesh class:
n_x : number of elements in the x direction
n_y : number of elements in the y direction
l_x : length in the x direction
l_y : length in the y direction
Ordering of elements: 'lower left' to 'lower right' then 'upwards'
Definition at line 61 of file simple_rectangular_tri_mesh.template.cc.
References oomph::Mesh::add_boundary_node(), oomph::FiniteElement::construct_node(), oomph::Mesh::convert_to_boundary_node(), oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, oomph::SimpleRectangularTriMesh< ELEMENT >::Lx, oomph::SimpleRectangularTriMesh< ELEMENT >::Ly, oomph::FiniteElement::nnode_1d(), oomph::Mesh::Node_pt, oomph::FiniteElement::node_pt(), oomph::SimpleRectangularTriMesh< ELEMENT >::Nx, oomph::SimpleRectangularTriMesh< ELEMENT >::Ny, and oomph::Mesh::set_nboundary().
Member Function Documentation
nx()
template<class ELEMENT >
const unsigned& oomph::SimpleRectangularTriMesh< ELEMENT >::nx () const [inline]
Access function for number of elements in x directions.
Definition at line 69 of file simple_rectangular_tri_mesh.template.h.
References oomph::SimpleRectangularTriMesh< ELEMENT >::Nx.
ny()
template<class ELEMENT >
const unsigned& oomph::SimpleRectangularTriMesh< ELEMENT >::ny () const [inline]
Access function for number of elements in y directions.
Definition at line 72 of file simple_rectangular_tri_mesh.template.h.
References oomph::SimpleRectangularTriMesh< ELEMENT >::Ny.
Member Data Documentation
Lx
template<class ELEMENT >
double oomph::SimpleRectangularTriMesh< ELEMENT >::Lx [private]
Length of mesh in x-direction.
Definition at line 83 of file simple_rectangular_tri_mesh.template.h.
Referenced by oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh().
Ly
template<class ELEMENT >
double oomph::SimpleRectangularTriMesh< ELEMENT >::Ly [private]
Length of mesh in y-direction.
Definition at line 86 of file simple_rectangular_tri_mesh.template.h.
Referenced by oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh().
Nx
template<class ELEMENT >
unsigned oomph::SimpleRectangularTriMesh< ELEMENT >::Nx [private]
Number of elements in x direction.
Definition at line 77 of file simple_rectangular_tri_mesh.template.h.
Referenced by oomph::SimpleRectangularTriMesh< ELEMENT >::nx(), and oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh().
Ny
template<class ELEMENT >
unsigned oomph::SimpleRectangularTriMesh< ELEMENT >::Ny [private]
Number of elements in y directions.
Definition at line 80 of file simple_rectangular_tri_mesh.template.h.
Referenced by oomph::SimpleRectangularTriMesh< ELEMENT >::ny(), and oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh().
The documentation for this class was generated from the following files:
simple_rectangular_tri_mesh.template.h
simple_rectangular_tri_mesh.template.cc