oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase Class Reference
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
virtual int p_nodal_index_nst () const =0
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
virtual int p_local_eqn (const unsigned &n) const =0
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
virtual void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)=0
Pin all non-pressure dofs and backup eqn numbers of all Data.
virtual void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)=0
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Additional Inherited Members
Detailed Description
Template-free base class for Navier-Stokes equations to avoid casting problems
Definition at line 61 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase()
oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase () [inline]
Constructor (empty)
Definition at line 69 of file generalised_newtonian_navier_stokes_elements.h.
 GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase()
virtual oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase () [inline], [virtual]
Virtual destructor (empty)
Definition at line 72 of file generalised_newtonian_navier_stokes_elements.h.
References get_pressure_and_velocity_mass_matrix_diagonal(), p_local_eqn(), p_nodal_index_nst(), and pin_all_non_pressure_dofs().
Member Function Documentation
get_pressure_and_velocity_mass_matrix_diagonal()
virtual void oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [pure virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Implements oomph::NavierStokesElementWithDiagonalMassMatrices.
Implemented in oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, and oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_load(), and ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase().
p_local_eqn()
virtual int oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_local_eqn (const unsigned & n) const [pure virtual]
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
Implemented in oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >.
Referenced by oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation(), and ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase().
p_nodal_index_nst()
virtual int oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::p_nodal_index_nst () const [pure virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Implemented in oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::fix_pressure(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_local_eqn(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), and ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase().
pin_all_non_pressure_dofs()
virtual void oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [pure virtual]
Pin all non-pressure dofs and backup eqn numbers of all Data.
Implemented in oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase().
The documentation for this class was generated from the following file:
generalised_newtonian_navier_stokes_elements.h