oomph::ExactBlockPreconditioner< MATRIX > Class Template Reference
#include <general_purpose_block_preconditioners.h>
Public Member Functions
ExactBlockPreconditioner ()
constructor
virtual ~ExactBlockPreconditioner ()
Destructor.
ExactBlockPreconditioner (const ExactBlockPreconditioner &)
Broken copy constructor.
void operator= (const ExactBlockPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void setup ()
Setup the preconditioner.
Preconditioner *& preconditioner_pt ()
Access for the preconditioner pointer used to solve the system (stored in the vector of pointers in the base class);.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::ExactBlockPreconditioner< MATRIX >
Exact block preconditioner - block preconditioner assembled from all blocks associated with the preconditioner and solved by SuperLU.
Definition at line 560 of file general_purpose_block_preconditioners.h.
Constructor & Destructor Documentation
ExactBlockPreconditioner() [1/2]
template<typename MATRIX>
oomph::ExactBlockPreconditioner< MATRIX >::ExactBlockPreconditioner () [inline]
constructor
Definition at line 567 of file general_purpose_block_preconditioners.h.
 ExactBlockPreconditioner()
template<typename MATRIX>
virtual oomph::ExactBlockPreconditioner< MATRIX >::~ExactBlockPreconditioner () [inline], [virtual]
Destructor.
Definition at line 571 of file general_purpose_block_preconditioners.h.
ExactBlockPreconditioner() [2/2]
template<typename MATRIX>
oomph::ExactBlockPreconditioner< MATRIX >::ExactBlockPreconditioner (const ExactBlockPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 574 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<typename MATRIX>
void oomph::ExactBlockPreconditioner< MATRIX >::operator= (const ExactBlockPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 580 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_assign(), and oomph::TerminateHelper::setup().
preconditioner_pt()
template<typename MATRIX>
Preconditioner*& oomph::ExactBlockPreconditioner< MATRIX >::preconditioner_pt () [inline]
Access for the preconditioner pointer used to solve the system (stored in the vector of pointers in the base class);.
Definition at line 593 of file general_purpose_block_preconditioners.h.
preconditioner_solve()
template<typename MATRIX >
void oomph::ExactBlockPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Preconditioner solve for the exact block preconditioner.
Implements oomph::Preconditioner.
Definition at line 412 of file general_purpose_block_preconditioners.cc.
Referenced by oomph::ExactBlockPreconditioner< MATRIX >::setup().
setup()
template<typename MATRIX >
void oomph::ExactBlockPreconditioner< MATRIX >::setup () [virtual]
Setup the preconditioner.
Setup for the exact block preconditioner.
Implements oomph::Preconditioner.
Definition at line 355 of file general_purpose_block_preconditioners.cc.
References oomph::ExactBlockPreconditioner< MATRIX >::preconditioner_solve().
The documentation for this class was generated from the following files:
general_purpose_block_preconditioners.h
general_purpose_block_preconditioners.cc