oomph::Biharmonic_schur_complement_Hypre_defaults Namespace Reference
Functions
void set_defaults (HyprePreconditioner *hypre_prec_pt)
set the defaults
Variables
unsigned AMG_smoother = 1
smoother type - Gauss Seidel: 1
unsigned AMG_coarsening = 1
amg coarsening strategy: classical Ruge Stueben: 1
unsigned N_cycle = 2
number of V cycles: 2
double AMG_strength = 0.25
amg strength parameter: 0.25 -- optimal for 2d
double AMG_jacobi_damping = 0.1
jacobi damping -- hierher not used 0.1
unsigned AMG_smoother_iterations =2
amg smoother iterations
Function Documentation
set_defaults()
void oomph::Biharmonic_schur_complement_Hypre_defaults::set_defaults (HyprePreconditioner * hypre_prec_pt)
set the defaults
Definition at line 72 of file biharmonic_preconditioner.cc.
References AMG_coarsening, oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_iterations(), oomph::HyprePreconditioner::amg_simple_smoother(), AMG_smoother, AMG_smoother_iterations, oomph::HyprePreconditioner::amg_smoother_iterations(), AMG_strength, oomph::HyprePreconditioner::amg_strength(), oomph::HypreInterface::BoomerAMG, oomph::HyprePreconditioner::hypre_method(), N_cycle, and oomph::oomph_info.
Referenced by oomph::InexactSubBiharmonicPreconditioner::setup().
Variable Documentation
AMG_coarsening
unsigned oomph::Biharmonic_schur_complement_Hypre_defaults::AMG_coarsening = 1
amg coarsening strategy: classical Ruge Stueben: 1
Definition at line 57 of file biharmonic_preconditioner.cc.
Referenced by set_defaults().
AMG_jacobi_damping
double oomph::Biharmonic_schur_complement_Hypre_defaults::AMG_jacobi_damping = 0.1
jacobi damping -- hierher not used 0.1
jacobi damping -- hierher not used 0.1;
Definition at line 66 of file biharmonic_preconditioner.cc.
AMG_smoother
unsigned oomph::Biharmonic_schur_complement_Hypre_defaults::AMG_smoother = 1
smoother type - Gauss Seidel: 1
Definition at line 54 of file biharmonic_preconditioner.cc.
Referenced by set_defaults().
AMG_smoother_iterations
unsigned oomph::Biharmonic_schur_complement_Hypre_defaults::AMG_smoother_iterations =2
amg smoother iterations
Amg smoother iterations: 2.
Definition at line 69 of file biharmonic_preconditioner.cc.
Referenced by oomph::HypreSolver::amg_smoother_iterations(), oomph::HyprePreconditioner::amg_smoother_iterations(), oomph::HypreInterface::hypre_solver_setup(), oomph::HypreInterface::HypreInterface(), and set_defaults().
AMG_strength
double oomph::Biharmonic_schur_complement_Hypre_defaults::AMG_strength = 0.25
amg strength parameter: 0.25 -- optimal for 2d
Definition at line 63 of file biharmonic_preconditioner.cc.
Referenced by set_defaults().
N_cycle
unsigned oomph::Biharmonic_schur_complement_Hypre_defaults::N_cycle = 2
number of V cycles: 2
Definition at line 60 of file biharmonic_preconditioner.cc.
Referenced by set_defaults().