oomph::VectorHelpers Namespace Reference
Namespace for helper functions for Vector<double>
Functions
void check_lengths_match (const Vector< double > &a, const Vector< double > &b)
Check the lengths if two Vectors are the same length.
double dot (const Vector< double > &a, const Vector< double > &b)
Probably not always best/fastest because not optimised for dimension but useful...
double magnitude (const Vector< double > &a)
Get the magnitude of a vector.
double angle (const Vector< double > &a, const Vector< double > &b)
Get the angle between two vector.
void cross (const Vector< double > &A, const Vector< double > &B, Vector< double > &C)
Cross product using `proper` output (move semantics means this is ok nowadays).
Vector< double > cross (const Vector< double > &A, const Vector< double > &B)
Cross product using `proper` output (move semantics means this is ok This calls the other cross(...) function.
Detailed Description
Namespace for helper functions for Vector<double>
Function Documentation
angle()
double oomph::VectorHelpers::angle (const Vector< double > & a, const Vector< double > & b) [inline]
Get the angle between two vector.
Definition at line 307 of file Vector.h.
References dot().
Referenced by oomph::OcTree::construct_rotation_matrix(), and oomph::FaceElement::continuous_tangent_and_outer_unit_normal().
check_lengths_match()
void oomph::VectorHelpers::check_lengths_match (const Vector< double > & a, const Vector< double > & b) [inline]
Check the lengths if two Vectors are the same length.
Definition at line 269 of file Vector.h.
Referenced by dot().
cross() [1/2]
void oomph::VectorHelpers::cross (const Vector< double > & A, const Vector< double > & B, Vector< double > & C) [inline]
Cross product using `proper` output (move semantics means this is ok nowadays).
Definition at line 317 of file Vector.h.
Referenced by oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::TriangleMesh< ELEMENT >::convex_hull(), and oomph::FaceElement::outer_unit_normal().
cross() [2/2]
Vector<double> oomph::VectorHelpers::cross (const Vector< double > & A, const Vector< double > & B) [inline]
Cross product using `proper` output (move semantics means this is ok This calls the other cross(...) function.
Definition at line 341 of file Vector.h.
References oomph::output().
dot()
double oomph::VectorHelpers::dot (const Vector< double > & a, const Vector< double > & b) [inline]
Probably not always best/fastest because not optimised for dimension but useful...
Definition at line 289 of file Vector.h.
References check_lengths_match(), and i.
Referenced by angle(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::DGEulerFaceReflectionElement< ELEMENT >::interpolated_u(), magnitude(), and oomph::DGScalarAdvectionFaceElement< ELEMENT >::numerical_flux().
magnitude()
double oomph::VectorHelpers::magnitude (const Vector< double > & a) [inline]
Get the magnitude of a vector.
Definition at line 301 of file Vector.h.
References dot().
Referenced by oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FaceElement::outer_unit_normal(), and oomph::C1CurvedElementShape< 2, NNODE_1D >::set_of_value().