superlu_dist.c File Reference
Classes
struct superlu_dist_data
Functions
void superlu_cr_to_cc (int nrow, int ncol, int nnz, double *cr_values, int *cr_index, int *cr_start, double **cc_values, int **cc_index, int **cc_start)
void superlu_dist_distributed_matrix (int opt_flag, int allow_permutations, int n, int nnz_local, int nrow_local, int first_row, double *values, int *col_index, int *row_start, double *b, int nprow, int npcol, int doc, void **data, int *info, MPI_Comm comm)
void superlu_dist_global_matrix (int opt_flag, int allow_permutations, int n_in, int nnz_in, double *values, int *row_index, int *col_start, double *b, int nprow, int npcol, int doc, void **data, int *info, MPI_Comm comm)
Function Documentation
superlu_cr_to_cc()
void superlu_cr_to_cc (int nrow, int ncol, int nnz, double * cr_values, int * cr_index, int * cr_start, double ** cc_values, int ** cc_index, int ** cc_start)
Definition at line 65 of file superlu_dist.c.
Referenced by oomph::SuperLUSolver::factorise_distributed(), and oomph::FD_LU::solve().
superlu_dist_distributed_matrix()
void superlu_dist_distributed_matrix (int opt_flag, int allow_permutations, int n, int nnz_local, int nrow_local, int first_row, double * values, int * col_index, int * row_start, double * b, int nprow, int npcol, int doc, void ** data, int * info, MPI_Comm comm)
Definition at line 106 of file superlu_dist.c.
References superlu_dist_data::A, superlu_dist_data::anorm, oomph::OcTreeNames::B, superlu_dist_data::colequ, superlu_dist_data::grid, i, if(), superlu_dist_data::LUstruct, superlu_dist_data::options, oomph::BinaryTreeNames::R, superlu_dist_data::rowequ, superlu_dist_data::ScalePermstruct, superlu_dist_data::SOLVEstruct, and t.
Referenced by oomph::SuperLUSolver::backsub_distributed(), oomph::SuperLUSolver::clean_up_memory(), oomph::SuperLUSolver::factorise_distributed(), and oomph::FD_LU::solve().
superlu_dist_global_matrix()
void superlu_dist_global_matrix (int opt_flag, int allow_permutations, int n_in, int nnz_in, double * values, int * row_index, int * col_start, double * b, int nprow, int npcol, int doc, void ** data, int * info, MPI_Comm comm)
Definition at line 1178 of file superlu_dist.c.
References superlu_dist_data::A, superlu_dist_data::AC, superlu_dist_data::anorm, oomph::OcTreeNames::B, superlu_dist_data::colequ, superlu_dist_data::grid, i, superlu_dist_data::LUstruct, superlu_dist_data::options, oomph::BinaryTreeNames::R, superlu_dist_data::rowequ, superlu_dist_data::ScalePermstruct, and t.
Referenced by oomph::SuperLUSolver::backsub_distributed(), oomph::SuperLUSolver::clean_up_memory(), oomph::SuperLUSolver::factorise_distributed(), and oomph::FD_LU::solve().