RefineableAdvectionDiffusionProblem< ELEMENT > Class Template Reference
Public Member Functions
RefineableAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source and wind functions.
~RefineableAdvectionDiffusionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the tanh solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt: Document the solution.
void doc_solution ()
Doc the solution.
RefineableRectangularQuadMesh< ELEMENT > * mesh_pt ()
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
RefineableAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source function.
~RefineableAdvectionDiffusionProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
RefineableRectangularQuadMesh< ELEMENT > * mesh_pt ()
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Private Attributes
DocInfo Doc_info
DocInfo object.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function.
Detailed Description
template<class ELEMENT>
class RefineableAdvectionDiffusionProblem< ELEMENT >
2D AdvectionDiffusion problem on rectangular domain, discretised with refineable 2D QAdvectionDiffusion elements. The specific type of element is specified via the template parameter.
Definition at line 106 of file two_d_adv_diff_adapt.cc.
Constructor & Destructor Documentation
RefineableAdvectionDiffusionProblem() [1/2]
template<class ELEMENT >
RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source and wind functions.
Constructor for AdvectionDiffusion problem: Pass pointer to source function.
Definition at line 168 of file two_d_adv_diff_adapt.cc.
References RefineableAdvectionDiffusionProblem< ELEMENT >::Doc_info, RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt(), TanhSolnForAdvectionDiffusion::Peclet, RefineableAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt, and RefineableAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt().
 RefineableAdvectionDiffusionProblem() [1/2]
template<class ELEMENT >
RefineableAdvectionDiffusionProblem< ELEMENT >::~RefineableAdvectionDiffusionProblem () [inline]
Destructor. Empty.
Definition at line 117 of file two_d_adv_diff_adapt.cc.
RefineableAdvectionDiffusionProblem() [2/2]
template<class ELEMENT >
RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source function.
 RefineableAdvectionDiffusionProblem() [2/2]
template<class ELEMENT >
RefineableAdvectionDiffusionProblem< ELEMENT >::~RefineableAdvectionDiffusionProblem () [inline]
Destructor (empty)
Definition at line 111 of file two_d_adv_diff_adapt2.cc.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 118 of file two_d_adv_diff_adapt2.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 124 of file two_d_adv_diff_adapt.cc.
actions_before_adapt()
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Document the solution.
Definition at line 127 of file two_d_adv_diff_adapt.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the tanh solution.
Update the problem specs before solve: (Re-)set boundary conditions to the values from the tanh solution.
Update the problem specs before solve: (Re-)set boundary conditions to the values from the exact solution.
Definition at line 243 of file two_d_adv_diff_adapt.cc.
References TanhSolnForAdvectionDiffusion::get_exact_u(), and RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt().
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt().
doc_solution() [1/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 258 of file two_d_adv_diff_adapt2.cc.
doc_solution() [2/2]
template<class ELEMENT >
void RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 281 of file two_d_adv_diff_adapt.cc.
References RefineableAdvectionDiffusionProblem< ELEMENT >::Doc_info, TanhSolnForAdvectionDiffusion::get_exact_u(), and RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt().
Referenced by main().
mesh_pt() [1/2]
template<class ELEMENT >
RefineableRectangularQuadMesh<ELEMENT>* RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 127 of file two_d_adv_diff_adapt2.cc.
References RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), TanhSolnForAdvectionDiffusion::Peclet, RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem(), and TanhSolnForAdvectionDiffusion::tanh_profile().
mesh_pt() [2/2]
template<class ELEMENT >
RefineableRectangularQuadMesh<ELEMENT>* RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 142 of file two_d_adv_diff_adapt.cc.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), main(), and RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem().
Member Data Documentation
Doc_info
template<class ELEMENT >
DocInfo RefineableAdvectionDiffusionProblem< ELEMENT >::Doc_info [private]
DocInfo object.
Definition at line 151 of file two_d_adv_diff_adapt.cc.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem().
Source_fct_pt
template<class ELEMENT >
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt RefineableAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 154 of file two_d_adv_diff_adapt.cc.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem().
Wind_fct_pt
template<class ELEMENT >
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt RefineableAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt [private]
Pointer to wind function.
Definition at line 157 of file two_d_adv_diff_adapt.cc.
Referenced by RefineableAdvectionDiffusionProblem< ELEMENT >::RefineableAdvectionDiffusionProblem().
The documentation for this class was generated from the following files:
two_d_adv_diff_adapt.cc
two_d_adv_diff_adapt2.cc