two_d_adv_diff_adapt.cc File Reference
Classes
class RefineableAdvectionDiffusionProblem< ELEMENT >
Namespaces
 TanhSolnForAdvectionDiffusion
Functions
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForAdvectionDiffusion::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForAdvectionDiffusion::source_function (const Vector< double > &x_vect, double &source)
Source function required to make the solution above an exact solution.
void TanhSolnForAdvectionDiffusion::wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
int main ()
Driver code for 2D AdvectionDiffusion problem.
Variables
double TanhSolnForAdvectionDiffusion::Peclet =200.0
Peclet number.
double TanhSolnForAdvectionDiffusion::Alpha
Parameter for steepness of step.
double TanhSolnForAdvectionDiffusion::TanPhi
Parameter for angle of step.
Function Documentation
main()
int main ()
Driver code for 2D AdvectionDiffusion problem.
Definition at line 326 of file two_d_adv_diff_adapt.cc.
References TanhSolnForAdvectionDiffusion::Alpha, RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForAdvectionDiffusion::TanPhi, and TanhSolnForAdvectionDiffusion::wind_function().