PlateProblem< ELEMENT > Class Template Reference
Public Member Functions
PlateProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor.
FlatPlateMesh< ELEMENT > * mesh_pt ()
Overload Access function for the mesh.
void actions_after_newton_solve ()
Actions after solve empty.
void actions_before_newton_solve ()
Actions before solve empty.
Private Attributes
GeomObject * Undeformed_midplane_pt
Pointer to GeomObject that specifies the undeformed midplane.
Node * Trace_node_pt
First trace node.
Node * Trace_node2_pt
Second trace node.
unsigned Nshell
Number of shell elements.
Detailed Description
template<class ELEMENT>
class PlateProblem< ELEMENT >
Definition at line 318 of file plate.cc.
Constructor & Destructor Documentation
PlateProblem()
template<class ELEMENT >
PlateProblem< ELEMENT >::PlateProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor.
Definition at line 361 of file plate.cc.
References FlatPlateMesh< ELEMENT >::assign_undeformed_positions(), Global_Physical_Variables::H, Global_Physical_Variables::Nu, Global_Physical_Variables::Pext_data_pt, Global_Physical_Variables::Prescribed_z, Global_Physical_Variables::press_load(), and Global_Physical_Variables::Sigma0.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void PlateProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve empty.
Definition at line 334 of file plate.cc.
actions_before_newton_solve()
template<class ELEMENT>
void PlateProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve empty.
Definition at line 337 of file plate.cc.
mesh_pt()
template<class ELEMENT>
FlatPlateMesh<ELEMENT>* PlateProblem< ELEMENT >::mesh_pt () [inline]
Overload Access function for the mesh.
Definition at line 328 of file plate.cc.
Referenced by main().
Member Data Documentation
Nshell
template<class ELEMENT>
unsigned PlateProblem< ELEMENT >::Nshell [private]
Number of shell elements.
Definition at line 351 of file plate.cc.
Trace_node2_pt
template<class ELEMENT>
Node* PlateProblem< ELEMENT >::Trace_node2_pt [private]
Second trace node.
Definition at line 348 of file plate.cc.
Trace_node_pt
template<class ELEMENT>
Node* PlateProblem< ELEMENT >::Trace_node_pt [private]
First trace node.
Definition at line 345 of file plate.cc.
Undeformed_midplane_pt
template<class ELEMENT>
GeomObject* PlateProblem< ELEMENT >::Undeformed_midplane_pt [private]
Pointer to GeomObject that specifies the undeformed midplane.
Definition at line 342 of file plate.cc.
The documentation for this class was generated from the following file:
plate.cc