SteadyTubeProblem< ELEMENT > Class Template Reference
Entry flow problem in tapered tube domain.
Public Member Functions
SteadyTubeProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target)
Constructor: Pass DocInfo object and target errors.
~SteadyTubeProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_adapt ()
After adaptation: Pin redudant pressure dofs.
void doc_solution ()
Doc the solution.
RefineableTubeMesh< ELEMENT > * mesh_pt ()
Overload generic access function by one that returns a pointer to the specific mesh.
Private Attributes
DocInfo Doc_info
Doc info object.
GeomObject * Volume_pt
Pointer to GeomObject that specifies the domain volume.
Detailed Description
template<class ELEMENT>
class SteadyTubeProblem< ELEMENT >
Entry flow problem in tapered tube domain.
Definition at line 98 of file full_tube.cc.
Constructor & Destructor Documentation
SteadyTubeProblem()
template<class ELEMENT >
SteadyTubeProblem< ELEMENT >::SteadyTubeProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
Definition at line 148 of file full_tube.cc.
References SteadyTubeProblem< ELEMENT >::mesh_pt(), Global_Physical_Variables::Re, and SteadyTubeProblem< ELEMENT >::Volume_pt.
 SteadyTubeProblem()
template<class ELEMENT>
SteadyTubeProblem< ELEMENT >::~SteadyTubeProblem () [inline]
Destructor (empty)
Definition at line 108 of file full_tube.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT>
void SteadyTubeProblem< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Pin redudant pressure dofs.
Definition at line 114 of file full_tube.cc.
actions_before_newton_solve()
template<class ELEMENT >
void SteadyTubeProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
Set the inflow boundary conditions.
Definition at line 255 of file full_tube.cc.
References SteadyTubeProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void SteadyTubeProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 282 of file full_tube.cc.
References SteadyTubeProblem< ELEMENT >::Doc_info, SteadyTubeProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
Referenced by main().
mesh_pt()
template<class ELEMENT>
RefineableTubeMesh<ELEMENT>* SteadyTubeProblem< ELEMENT >::mesh_pt () [inline]
Overload generic access function by one that returns a pointer to the specific mesh.
Definition at line 126 of file full_tube.cc.
Referenced by SteadyTubeProblem< ELEMENT >::actions_before_newton_solve(), SteadyTubeProblem< ELEMENT >::doc_solution(), and SteadyTubeProblem< ELEMENT >::SteadyTubeProblem().
Member Data Documentation
Doc_info
template<class ELEMENT>
DocInfo SteadyTubeProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 134 of file full_tube.cc.
Referenced by SteadyTubeProblem< ELEMENT >::doc_solution().
Volume_pt
template<class ELEMENT>
GeomObject* SteadyTubeProblem< ELEMENT >::Volume_pt [private]
Pointer to GeomObject that specifies the domain volume.
Definition at line 137 of file full_tube.cc.
Referenced by SteadyTubeProblem< ELEMENT >::SteadyTubeProblem().
The documentation for this class was generated from the following file:
full_tube.cc