AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Public Member Functions
AxisymmetricLinearElasticityProblem ()
Constructor: Pass number of elements in r and z directions, boundary locations and whether we are doing an impulsive start or not.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void actions_before_implicit_timestep ()
Actions before implicit timestep.
void set_initial_conditions ()
Set the initial conditions, either for an impulsive start or with history values for the time stepper.
void set_boundary_conditions ()
Set the boundary conditions.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void assign_traction_elements ()
Allocate traction elements on the bottom surface.
Private Attributes
Mesh * Bulk_mesh_pt
Pointer to the bulk mesh.
Mesh * Surface_mesh_pt
Pointer to the mesh of traction elements.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >
Class to validate time harmonic linear elasticity (Fourier decomposed)
Definition at line 231 of file cylinder.cc.
Constructor & Destructor Documentation
AxisymmetricLinearElasticityProblem()
template<class ELEMENT , class TIMESTEPPER >
AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem ()
Constructor: Pass number of elements in r and z directions, boundary locations and whether we are doing an impulsive start or not.
Problem constructor: Pass number of elements in coordinate directions and size of domain.
Definition at line 281 of file cylinder.cc.
References AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::assign_traction_elements(), Global_Parameters::body_force(), Global_Parameters::boundary_traction(), Global_Parameters::E, Global_Parameters::Nr, Global_Parameters::Nu, Global_Parameters::Nz, Global_Parameters::Omega_sq, Global_Parameters::Rmax, Global_Parameters::Rmin, Global_Parameters::Zmax, and Global_Parameters::Zmin.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 243 of file cylinder.cc.
actions_before_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () [inline]
Actions before implicit timestep.
Definition at line 246 of file cylinder.cc.
actions_before_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 240 of file cylinder.cc.
assign_traction_elements()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::assign_traction_elements () [private]
Allocate traction elements on the bottom surface.
Make traction elements along the boundary r=Rmin.
Definition at line 392 of file cylinder.cc.
References AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
doc_solution()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 668 of file cylinder.cc.
References Global_Parameters::exact_solution().
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions().
set_boundary_conditions()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set the boundary conditions.
Definition at line 578 of file cylinder.cc.
References Global_Parameters::d2_u_r_dt2(), Global_Parameters::d2_u_theta_dt2(), Global_Parameters::d2_u_z_dt2(), Global_Parameters::d_u_r_dt(), Global_Parameters::d_u_theta_dt(), Global_Parameters::d_u_z_dt(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution(), Global_Parameters::exact_solution(), Global_Parameters::u_r(), Global_Parameters::u_theta(), and Global_Parameters::u_z().
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
set_initial_conditions()
template<class ELEMENT , class TIMESTEPPER >
void AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions ()
Set the initial conditions, either for an impulsive start or with history values for the time stepper.
Set the initial conditions (history values)
Definition at line 420 of file cylinder.cc.
References Global_Parameters::d2_u_r_dt2(), Global_Parameters::d2_u_theta_dt2(), Global_Parameters::d2_u_z_dt2(), Global_Parameters::d_u_r_dt(), Global_Parameters::d_u_theta_dt(), Global_Parameters::d_u_z_dt(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), Global_Parameters::u_r(), Global_Parameters::u_theta(), and Global_Parameters::u_z().
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::assign_traction_elements(), and main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT , class TIMESTEPPER >
Mesh* AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt [private]
Pointer to the bulk mesh.
Definition at line 268 of file cylinder.cc.
Surface_mesh_pt
template<class ELEMENT , class TIMESTEPPER >
Mesh* AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt [private]
Pointer to the mesh of traction elements.
Definition at line 271 of file cylinder.cc.
The documentation for this class was generated from the following file:
cylinder.cc