EntryFlowProblem< ELEMENT > Class Template Reference
Entry flow problem in quarter tube domain.
Public Member Functions
EntryFlowProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target)
Constructor: Pass DocInfo object and target errors.
~EntryFlowProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Doc the solution after solve.
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_adapt ()
After adaptation: Pin redudant pressure dofs.
void doc_solution ()
Doc the solution.
RefineableQuarterTubeMesh< ELEMENT > * mesh_pt ()
Overload generic access function by one that returns a pointer to the specific mesh.
Private Attributes
int Alpha
Exponent for bluntness of velocity profile.
DocInfo Doc_info
Doc info object.
Detailed Description
template<class ELEMENT>
class EntryFlowProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Definition at line 57 of file three_d_entry_flow.cc.
Constructor & Destructor Documentation
EntryFlowProblem()
template<class ELEMENT >
EntryFlowProblem< ELEMENT >::EntryFlowProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
Definition at line 117 of file three_d_entry_flow.cc.
References EntryFlowProblem< ELEMENT >::Alpha, EntryFlowProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
 EntryFlowProblem()
template<class ELEMENT>
EntryFlowProblem< ELEMENT >::~EntryFlowProblem () [inline]
Destructor (empty)
Definition at line 67 of file three_d_entry_flow.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT>
void EntryFlowProblem< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Pin redudant pressure dofs.
Definition at line 83 of file three_d_entry_flow.cc.
actions_after_newton_solve()
template<class ELEMENT>
void EntryFlowProblem< ELEMENT >::actions_after_newton_solve () [inline]
Doc the solution after solve.
Definition at line 70 of file three_d_entry_flow.cc.
actions_before_newton_solve()
template<class ELEMENT >
void EntryFlowProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
Set the inflow boundary conditions.
Definition at line 247 of file three_d_entry_flow.cc.
References EntryFlowProblem< ELEMENT >::Alpha, and EntryFlowProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void EntryFlowProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 275 of file three_d_entry_flow.cc.
References EntryFlowProblem< ELEMENT >::Doc_info, and EntryFlowProblem< ELEMENT >::mesh_pt().
Referenced by main().
mesh_pt()
template<class ELEMENT>
RefineableQuarterTubeMesh<ELEMENT>* EntryFlowProblem< ELEMENT >::mesh_pt () [inline]
Overload generic access function by one that returns a pointer to the specific mesh.
Definition at line 95 of file three_d_entry_flow.cc.
Referenced by EntryFlowProblem< ELEMENT >::actions_before_newton_solve(), EntryFlowProblem< ELEMENT >::doc_solution(), and EntryFlowProblem< ELEMENT >::EntryFlowProblem().
Member Data Documentation
Alpha
template<class ELEMENT>
int EntryFlowProblem< ELEMENT >::Alpha [private]
Exponent for bluntness of velocity profile.
Definition at line 103 of file three_d_entry_flow.cc.
Referenced by EntryFlowProblem< ELEMENT >::actions_before_newton_solve(), and EntryFlowProblem< ELEMENT >::EntryFlowProblem().
Doc_info
template<class ELEMENT>
DocInfo EntryFlowProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 106 of file three_d_entry_flow.cc.
Referenced by EntryFlowProblem< ELEMENT >::doc_solution().
The documentation for this class was generated from the following file:
three_d_entry_flow.cc