TwoMeshFluxAdvectionDiffusionProblem< ELEMENT > Class Template Reference
Public Member Functions
TwoMeshFluxAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source and wind functions.
~TwoMeshFluxAdvectionDiffusionProblem ()
Destructor (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution: doc_info contains labels/output directory etc.
Private Member Functions
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed flux elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed flux elements.
void create_flux_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
Create Advection Diffusion flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
void delete_flux_elements (Mesh *const &surface_mesh_pt)
Delete Advection Diffusion flux elements and wipe the surface mesh.
Private Attributes
RefineableRectangularQuadMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Surface_mesh_pt
Pointer to the `surface` mesh.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function.
Detailed Description
template<class ELEMENT>
class TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >
2D AdvectionDiffusion problem on rectangular domain, discretised with 2D QAdvectionDiffusion elements. Flux boundary conditions are applied along boundary 1 (the boundary where x=L). The specific type of element is specified via the template parameter.
Definition at line 123 of file two_d_adv_diff_flux_bc.cc.
Constructor & Destructor Documentation
TwoMeshFluxAdvectionDiffusionProblem()
template<class ELEMENT >
TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt)
Constructor: Pass pointer to source and wind functions.
Constructor for AdvectionDiffusion problem: Pass pointer to source and wind functions.
Definition at line 188 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), TanhSolnForAdvectionDiffusion::Peclet, TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt, TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Surface_mesh_pt, and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt.
 TwoMeshFluxAdvectionDiffusionProblem()
template<class ELEMENT >
TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::~TwoMeshFluxAdvectionDiffusionProblem () [inline]
Destructor (empty)
Definition at line 134 of file two_d_adv_diff_flux_bc.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt () [private]
Actions after adapt: Rebuild the mesh of prescribed flux elements.
Definition at line 465 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), TanhSolnForAdvectionDiffusion::prescribed_flux_on_fixed_x_boundary(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Surface_mesh_pt.
actions_after_newton_solve()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_newton_solve () [inline], [private]
Update the problem specs after solve (empty)
Definition at line 148 of file two_d_adv_diff_flux_bc.cc.
actions_before_adapt()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_adapt () [private]
Actions before adapt: Wipe the mesh of prescribed flux elements.
Definition at line 452 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::delete_flux_elements(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Surface_mesh_pt.
actions_before_newton_solve()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve () [private]
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Definition at line 296 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and TanhSolnForAdvectionDiffusion::get_exact_u().
create_flux_elements()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt) [private]
Create Advection Diffusion flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Create AdvectionDiffusion Flux Elements on the b-th boundary of the Mesh object pointed to by bulk_mesh_pt and add the elements to the Mesh object pointeed to by surface_mesh_pt.
Definition at line 399 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::delete_flux_elements().
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
delete_flux_elements()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::delete_flux_elements (Mesh *const & surface_mesh_pt) [private]
Delete Advection Diffusion flux elements and wipe the surface mesh.
Delete Advection Diffusion Flux Elements and wipe the surface mesh.
Definition at line 431 of file two_d_adv_diff_flux_bc.cc.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_adapt(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements().
doc_solution()
template<class ELEMENT >
void TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution: doc_info contains labels/output directory etc.
Doc the solution. DocInfo object stores flags/labels for where the output gets written to
Definition at line 339 of file two_d_adv_diff_flux_bc.cc.
References TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Bulk_mesh_pt, TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), and TanhSolnForAdvectionDiffusion::get_exact_u().
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), and main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
RefineableRectangularQuadMesh<ELEMENT>* TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 166 of file two_d_adv_diff_flux_bc.cc.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
Source_fct_pt
template<class ELEMENT >
AdvectionDiffusionEquations<2>::AdvectionDiffusionSourceFctPt TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 172 of file two_d_adv_diff_flux_bc.cc.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
Surface_mesh_pt
template<class ELEMENT >
Mesh* TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the `surface` mesh.
Definition at line 169 of file two_d_adv_diff_flux_bc.cc.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_before_adapt(), and TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
Wind_fct_pt
template<class ELEMENT >
AdvectionDiffusionEquations<2>::AdvectionDiffusionWindFctPt TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt [private]
Pointer to wind function.
Definition at line 175 of file two_d_adv_diff_flux_bc.cc.
Referenced by TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem().
The documentation for this class was generated from the following file:
two_d_adv_diff_flux_bc.cc