oomph::TwoLayerSpineMesh< ELEMENT > Class Template Reference
#include <two_layer_spine_mesh.template.h>
Public Member Functions
TwoLayerSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers and pointer to timestepper (defaults to Steady timestepper)
TwoLayerSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, and pointer to timestepper (defaults to Steady timestepper)
TwoLayerSpineMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, const bool &periodic_in_x, const bool &build_mesh, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, a boolean flag to specify whether or not to call the `build_two_layer_mesh` function, and pointer to timestepper (defaults to Steady timestepper)
FiniteElement *& upper_layer_element_pt (const unsigned long &i)
Access functions for pointers to elements in upper layer.
FiniteElement *& lower_layer_element_pt (const unsigned long &i)
Access functions for pointers to elements in bottom layer.
unsigned long nupper () const
Number of elements in upper layer.
unsigned long nlower () const
Number of elements in top layer.
FiniteElement *& interface_upper_boundary_element_pt (const unsigned long &i)
Access functions for pointers to elements in upper layer.
FiniteElement *& interface_lower_boundary_element_pt (const unsigned long &i)
Access functions for pointers to elements in bottom layer.
unsigned long ninterface_upper () const
Number of elements in upper layer.
unsigned long ninterface_lower () const
Number of elements in top layer.
int interface_upper_face_index_at_boundary (const unsigned &e)
Index of the face of the elements next to the interface in the upper region (always -2)
int interface_lower_face_index_at_boundary (const unsigned &e)
Index of the face of the elements next to the interface in the lower region (always 2)
void spine_node_update (SpineNode *spine_node_pt)
General node update function implements pure virtual function defined in SpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node.
Protected Member Functions
double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
The spacing function for the x co-ordinates with two regions.
double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
The spacing function for the y co-ordinates with three regions in each fluid.
void spine_node_update_lower (SpineNode *spine_node_pt)
Update function for the lower part of the domain.
void spine_node_update_upper (SpineNode *spine_node_pt)
Update function for the upper part of the domain.
virtual void build_two_layer_mesh (TimeStepper *time_stepper_pt)
Helper function to actually build the two-layer spine mesh (called from various constructors)
Protected Attributes
unsigned Ny1
Number of elements in lower layer.
unsigned Ny2
Number of elements in upper layer.
double H1
Height of the lower layer.
double H2
Height of the upper layer.
Vector< FiniteElement * > Lower_layer_element_pt
Vector of pointers to element in the upper layer.
Vector< FiniteElement * > Upper_layer_element_pt
Vector of pointers to element in the lower layer.
Vector< FiniteElement * > Interface_lower_boundary_element_pt
Vector of pointers to the elements adjacent to the interface on the lower layer.
Vector< FiniteElement * > Interface_upper_boundary_element_pt
Vector of pointers to the element adjacent to the interface on the upper layer.
Detailed Description
template<class ELEMENT>
class oomph::TwoLayerSpineMesh< ELEMENT >
Two-layer spine mesh class derived from standard 2D mesh. The mesh contains two layers of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>).
This mesh paritions the elements into those above and below a notional interface and relabels boundaries so that the mesh is as follows
3
| | 4 | | 2
| 6 |
| | 5 | | 1
| |
0 Update information for the nodes in response to changes in spine length is given, but additional equations must be specified in order to completely specify the problem.
Definition at line 65 of file two_layer_spine_mesh.template.h.
Constructor & Destructor Documentation
TwoLayerSpineMesh() [1/3]
template<class ELEMENT >
oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers and pointer to timestepper (defaults to Steady timestepper)
Constuctor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, and pointer to timestepper (defaults to Static timestepper).
The mesh contains two layers of elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding Spine interface elements of type INTERFACE_ELEMENT, e.g. SpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
Definition at line 55 of file two_layer_spine_mesh.template.cc.
References oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::H1, oomph::TwoLayerSpineMesh< ELEMENT >::H2, oomph::TwoLayerSpineMesh< ELEMENT >::Ny1, and oomph::TwoLayerSpineMesh< ELEMENT >::Ny2.
TwoLayerSpineMesh() [2/3]
template<class ELEMENT >
oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, const bool & periodic_in_x, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, and pointer to timestepper (defaults to Steady timestepper)
Constuctor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, and pointer to timestepper (defaults to Static timestepper).
The mesh contains two layers of elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding Spine interface elements of type INTERFACE_ELEMENT, e.g. SpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
Definition at line 104 of file two_layer_spine_mesh.template.cc.
References oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::H1, oomph::TwoLayerSpineMesh< ELEMENT >::H2, oomph::TwoLayerSpineMesh< ELEMENT >::Ny1, and oomph::TwoLayerSpineMesh< ELEMENT >::Ny2.
TwoLayerSpineMesh() [3/3]
template<class ELEMENT >
oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, const bool & periodic_in_x, const bool & build_mesh, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, a boolean flag to specify whether or not to call the `build_two_layer_mesh` function, and pointer to timestepper (defaults to Steady timestepper)
Constuctor for spine 2D mesh: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, a boolean flag to make the mesh periodic in the x-direction, a boolean flag to specify whether or not to call the `build_two_layer_mesh` function, and pointer to timestepper (defaults to Static timestepper).
The mesh contains two layers of elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and an interfacial layer of corresponding Spine interface elements of type INTERFACE_ELEMENT, e.g. SpineLineFluidInterfaceElement<ELEMENT> for 2D planar problems.
Definition at line 154 of file two_layer_spine_mesh.template.cc.
References oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::H1, oomph::TwoLayerSpineMesh< ELEMENT >::H2, oomph::TwoLayerSpineMesh< ELEMENT >::Ny1, oomph::TwoLayerSpineMesh< ELEMENT >::Ny2, and oomph::TwoLayerSpineMesh< ELEMENT >::x_spacing_function().
Member Function Documentation
build_two_layer_mesh()
template<class ELEMENT >
void oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh (TimeStepper * time_stepper_pt) [protected], [virtual]
Helper function to actually build the two-layer spine mesh (called from various constructors)
Helper function that actually builds the two-layer spine mesh based on the parameters set in the various constructors
Definition at line 250 of file two_layer_spine_mesh.template.cc.
References oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::H1, oomph::TwoLayerSpineMesh< ELEMENT >::H2, oomph::TwoLayerSpineMesh< ELEMENT >::Interface_lower_boundary_element_pt, oomph::TwoLayerSpineMesh< ELEMENT >::Interface_upper_boundary_element_pt, oomph::TwoLayerSpineMesh< ELEMENT >::Lower_layer_element_pt, oomph::RectangularQuadMesh< ELEMENT >::Nx, oomph::TwoLayerSpineMesh< ELEMENT >::Ny1, oomph::TwoLayerSpineMesh< ELEMENT >::Ny2, oomph::TwoLayerSpineMesh< ELEMENT >::Upper_layer_element_pt, oomph::RectangularQuadMesh< ELEMENT >::Xperiodic, and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper(), and oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh().
interface_lower_boundary_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::TwoLayerSpineMesh< ELEMENT >::interface_lower_boundary_element_pt (const unsigned long & i) [inline]
Access functions for pointers to elements in bottom layer.
Definition at line 137 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Interface_lower_boundary_element_pt.
interface_lower_face_index_at_boundary()
template<class ELEMENT >
int oomph::TwoLayerSpineMesh< ELEMENT >::interface_lower_face_index_at_boundary (const unsigned & e) [inline]
Index of the face of the elements next to the interface in the lower region (always 2)
Definition at line 155 of file two_layer_spine_mesh.template.h.
interface_upper_boundary_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::TwoLayerSpineMesh< ELEMENT >::interface_upper_boundary_element_pt (const unsigned long & i) [inline]
Access functions for pointers to elements in upper layer.
Definition at line 133 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Interface_upper_boundary_element_pt.
interface_upper_face_index_at_boundary()
template<class ELEMENT >
int oomph::TwoLayerSpineMesh< ELEMENT >::interface_upper_face_index_at_boundary (const unsigned & e) [inline]
Index of the face of the elements next to the interface in the upper region (always -2)
Definition at line 150 of file two_layer_spine_mesh.template.h.
lower_layer_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::TwoLayerSpineMesh< ELEMENT >::lower_layer_element_pt (const unsigned long & i) [inline]
Access functions for pointers to elements in bottom layer.
Definition at line 123 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Lower_layer_element_pt.
ninterface_lower()
template<class ELEMENT >
unsigned long oomph::TwoLayerSpineMesh< ELEMENT >::ninterface_lower () const [inline]
Number of elements in top layer.
Definition at line 145 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Interface_lower_boundary_element_pt.
ninterface_upper()
template<class ELEMENT >
unsigned long oomph::TwoLayerSpineMesh< ELEMENT >::ninterface_upper () const [inline]
Number of elements in upper layer.
Definition at line 141 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Interface_upper_boundary_element_pt.
nlower()
template<class ELEMENT >
unsigned long oomph::TwoLayerSpineMesh< ELEMENT >::nlower () const [inline]
Number of elements in top layer.
Definition at line 130 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Lower_layer_element_pt.
nupper()
template<class ELEMENT >
unsigned long oomph::TwoLayerSpineMesh< ELEMENT >::nupper () const [inline]
Number of elements in upper layer.
Definition at line 127 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Upper_layer_element_pt.
spine_node_update()
template<class ELEMENT >
void oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update (SpineNode * spine_node_pt) [inline]
General node update function implements pure virtual function defined in SpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node.
Definition at line 161 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower(), and oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper().
spine_node_update_lower()
template<class ELEMENT >
void oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_lower (SpineNode * spine_node_pt) [inline], [protected]
Update function for the lower part of the domain.
Definition at line 226 of file two_layer_spine_mesh.template.h.
References oomph::RectangularQuadMesh< ELEMENT >::Ymin.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update().
spine_node_update_upper()
template<class ELEMENT >
void oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update_upper (SpineNode * spine_node_pt) [inline], [protected]
Update function for the upper part of the domain.
Definition at line 238 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::RectangularQuadMesh< ELEMENT >::Ymax, and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::spine_node_update().
upper_layer_element_pt()
template<class ELEMENT >
FiniteElement* & oomph::TwoLayerSpineMesh< ELEMENT >::upper_layer_element_pt (const unsigned long & i) [inline]
Access functions for pointers to elements in upper layer.
Definition at line 119 of file two_layer_spine_mesh.template.h.
References oomph::TwoLayerSpineMesh< ELEMENT >::Upper_layer_element_pt.
x_spacing_function()
template<class ELEMENT >
double oomph::TwoLayerSpineMesh< ELEMENT >::x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) [protected], [virtual]
The spacing function for the x co-ordinates with two regions.
The spacing function for the x co-ordinate, which is the same as the default function.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
Definition at line 197 of file two_layer_spine_mesh.template.cc.
References oomph::RectangularQuadMesh< ELEMENT >::Np, oomph::RectangularQuadMesh< ELEMENT >::Nx, oomph::RectangularQuadMesh< ELEMENT >::Xmax, oomph::RectangularQuadMesh< ELEMENT >::Xmin, and oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function().
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh().
y_spacing_function()
template<class ELEMENT >
double oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode) [protected], [virtual]
The spacing function for the y co-ordinates with three regions in each fluid.
The spacing function for the y co-ordinates, which splits the region into two regions (1 and 2), according to the heights H1 and H2, with Ny1 and Ny2 elements respectively.
Reimplemented from oomph::RectangularQuadMesh< ELEMENT >.
Definition at line 212 of file two_layer_spine_mesh.template.cc.
References oomph::TwoLayerSpineMesh< ELEMENT >::H1, oomph::TwoLayerSpineMesh< ELEMENT >::Ny1, oomph::TwoLayerSpineMesh< ELEMENT >::Ny2, oomph::RectangularQuadMesh< ELEMENT >::Ymax, and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::x_spacing_function().
Member Data Documentation
H1
template<class ELEMENT >
double oomph::TwoLayerSpineMesh< ELEMENT >::H1 [protected]
Height of the lower layer.
Definition at line 195 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function().
H2
template<class ELEMENT >
double oomph::TwoLayerSpineMesh< ELEMENT >::H2 [protected]
Height of the upper layer.
Definition at line 198 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh().
Interface_lower_boundary_element_pt
template<class ELEMENT >
Vector<FiniteElement*> oomph::TwoLayerSpineMesh< ELEMENT >::Interface_lower_boundary_element_pt [protected]
Vector of pointers to the elements adjacent to the interface on the lower layer.
Definition at line 208 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::interface_lower_boundary_element_pt(), and oomph::TwoLayerSpineMesh< ELEMENT >::ninterface_lower().
Interface_upper_boundary_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::TwoLayerSpineMesh< ELEMENT >::Interface_upper_boundary_element_pt [protected]
Vector of pointers to the element adjacent to the interface on the upper layer.
Definition at line 212 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::interface_upper_boundary_element_pt(), and oomph::TwoLayerSpineMesh< ELEMENT >::ninterface_upper().
Lower_layer_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::TwoLayerSpineMesh< ELEMENT >::Lower_layer_element_pt [protected]
Vector of pointers to element in the upper layer.
Definition at line 201 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::lower_layer_element_pt(), and oomph::TwoLayerSpineMesh< ELEMENT >::nlower().
Ny1
template<class ELEMENT >
unsigned oomph::TwoLayerSpineMesh< ELEMENT >::Ny1 [protected]
Number of elements in lower layer.
Definition at line 189 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function().
Ny2
template<class ELEMENT >
unsigned oomph::TwoLayerSpineMesh< ELEMENT >::Ny2 [protected]
Number of elements in upper layer.
Definition at line 192 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::TwoLayerSpineMesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function().
Upper_layer_element_pt
template<class ELEMENT >
Vector<FiniteElement *> oomph::TwoLayerSpineMesh< ELEMENT >::Upper_layer_element_pt [protected]
Vector of pointers to element in the lower layer.
Definition at line 204 of file two_layer_spine_mesh.template.h.
Referenced by oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::nupper(), and oomph::TwoLayerSpineMesh< ELEMENT >::upper_layer_element_pt().
The documentation for this class was generated from the following files:
two_layer_spine_mesh.template.h
two_layer_spine_mesh.template.cc