RefineableUnsteadyHeatProblem< ELEMENT > Class Template Reference
Unsteady heat problem in deformable ellipse domain.
Public Member Functions
RefineableUnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function and timestep.
~RefineableUnsteadyHeatProblem ()
Destructor: Close trace file.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_implicit_timestep ()
Update the problem specs after timestep (empty)
void actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed flux elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed flux elements.
double global_temporal_error_norm ()
Global error norm for adaptive time-stepping.
void set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
void create_flux_elements (const unsigned &b, Mesh *const &bulk_mesh_pt, Mesh *const &surface_mesh_pt)
Create UnsteadyHeat flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
void delete_flux_elements (Mesh *const &surface_mesh_pt)
Delete UnsteadyHeat flux elements and wipe the surface mesh.
void doc_solution ()
Doc the solution.
void dump_it (ofstream &dump_file)
Dump problem data to allow for later restart.
void restart (ifstream &restart_file)
Read problem data for restart.
RefineableQuarterCircleSectorMesh< ELEMENT > * bulk_mesh_pt ()
Pointer to bulk mesh.
double & epsilon_t ()
Target error for adaptive timestepping.
void write_trace_file_header ()
Write header for trace file.
double & next_dt ()
Private Attributes
DocInfo Doc_info
Doc info object.
double Next_dt
GeomObject * Boundary_pt
Pointer to GeomObject that specifies the domain bondary.
UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function.
RefineableQuarterCircleSectorMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the `bulk` mesh.
Mesh * Surface_mesh_pt
Pointer to the `surface` mesh.
Node * Doc_node_pt
Pointer to central node (exists at all refinement levels) for doc.
ofstream Trace_file
Trace file.
double Epsilon_t
Target error for adaptive timestepping.
Detailed Description
template<class ELEMENT>
class RefineableUnsteadyHeatProblem< ELEMENT >
Unsteady heat problem in deformable ellipse domain.
Definition at line 219 of file two_d_unsteady_heat_2adapt.cc.
Constructor & Destructor Documentation
RefineableUnsteadyHeatProblem()
template<class ELEMENT >
RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem (UnsteadyHeatEquations< 2 >::UnsteadyHeatSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function and timestep.
Constructor for UnsteadyHeat problem on deformable ellipse domain. Pass pointer to source function.
Definition at line 328 of file two_d_unsteady_heat_2adapt.cc.
References TanhSolnForUnsteadyHeat::Alpha, TanhSolnForUnsteadyHeat::Beta, RefineableUnsteadyHeatProblem< ELEMENT >::Boundary_pt, RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements(), RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info, RefineableUnsteadyHeatProblem< ELEMENT >::Doc_node_pt, RefineableUnsteadyHeatProblem< ELEMENT >::Epsilon_t, TanhSolnForUnsteadyHeat::Gamma, TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), RefineableUnsteadyHeatProblem< ELEMENT >::Source_fct_pt, RefineableUnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt, and TanhSolnForUnsteadyHeat::TanPhi.
 RefineableUnsteadyHeatProblem()
template<class ELEMENT >
RefineableUnsteadyHeatProblem< ELEMENT >::~RefineableUnsteadyHeatProblem ()
Destructor: Close trace file.
Definition at line 484 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Trace_file.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of prescribed flux elements.
Definition at line 548 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements(), TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary(), and RefineableUnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt.
actions_after_implicit_timestep()
template<class ELEMENT>
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_implicit_timestep () [inline]
Update the problem specs after timestep (empty)
Definition at line 238 of file two_d_unsteady_heat_2adapt.cc.
actions_after_newton_solve()
template<class ELEMENT>
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 232 of file two_d_unsteady_heat_2adapt.cc.
actions_before_adapt()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of prescribed flux elements.
Definition at line 532 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::delete_flux_elements(), and RefineableUnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt.
actions_before_implicit_timestep()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep ()
Update the problem specs before next timestep: Set Dirchlet boundary conditions from exact solution.
Actions before timestep: Update the domain shape, then set the boundary conditions for the current time.
Definition at line 496 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, and TanhSolnForUnsteadyHeat::get_exact_u().
actions_before_newton_solve()
template<class ELEMENT>
void RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 235 of file two_d_unsteady_heat_2adapt.cc.
bulk_mesh_pt()
template<class ELEMENT>
RefineableQuarterCircleSectorMesh<ELEMENT>* RefineableUnsteadyHeatProblem< ELEMENT >::bulk_mesh_pt () [inline]
Pointer to bulk mesh.
Definition at line 276 of file two_d_unsteady_heat_2adapt.cc.
Referenced by main().
create_flux_elements()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements (const unsigned & b, Mesh *const & bulk_mesh_pt, Mesh *const & surface_mesh_pt)
Create UnsteadyHeat flux elements on boundary b of the Mesh pointed to by bulk_mesh_pt and add them to the Mesh object pointed to by surface_mesh_pt.
Create UnsteadyHeat Flux Elements on the b-th boundary of the Mesh object pointed to by bulk_mesh_pt and add the elements to the Mesh object pointed to by surface_mesh_pt.
Definition at line 911 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::delete_flux_elements().
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_adapt(), RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
delete_flux_elements()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::delete_flux_elements (Mesh *const & surface_mesh_pt)
Delete UnsteadyHeat flux elements and wipe the surface mesh.
Delete UnsteadyHeat Flux Elements and wipe the surface mesh.
Definition at line 944 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_adapt(), and RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements().
doc_solution()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 768 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Boundary_pt, RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements(), RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info, RefineableUnsteadyHeatProblem< ELEMENT >::Doc_node_pt, RefineableUnsteadyHeatProblem< ELEMENT >::dump_it(), TanhSolnForUnsteadyHeat::get_exact_u(), RefineableUnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm(), TanhSolnForUnsteadyHeat::step_position(), and RefineableUnsteadyHeatProblem< ELEMENT >::Trace_file.
Referenced by main().
dump_it()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::dump_it (ofstream & dump_file)
Dump problem data to allow for later restart.
Dump the solution to disk.
Definition at line 1000 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info, and RefineableUnsteadyHeatProblem< ELEMENT >::Next_dt.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution().
epsilon_t()
template<class ELEMENT>
double& RefineableUnsteadyHeatProblem< ELEMENT >::epsilon_t () [inline]
Target error for adaptive timestepping.
Definition at line 282 of file two_d_unsteady_heat_2adapt.cc.
Referenced by main().
global_temporal_error_norm()
template<class ELEMENT >
double RefineableUnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm ()
Global error norm for adaptive time-stepping.
Global error norm for adaptive timestepping: RMS error, based on difference between predicted and actual value at all nodes.
Definition at line 967 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution().
next_dt()
template<class ELEMENT>
double& RefineableUnsteadyHeatProblem< ELEMENT >::next_dt () [inline]
Suggestion for next timestep (stored to allow it to be written to (or read from) restart file)
Definition at line 289 of file two_d_unsteady_heat_2adapt.cc.
Referenced by main().
restart()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::restart (ifstream & restart_file)
Read problem data for restart.
Read solution from disk.
Definition at line 1018 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info, and RefineableUnsteadyHeatProblem< ELEMENT >::Next_dt.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::set_initial_condition().
set_initial_condition()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
Set initial condition: Assign previous and current values from exact solution.
Definition at line 578 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt, TanhSolnForUnsteadyHeat::get_exact_u(), RefineableUnsteadyHeatProblem< ELEMENT >::Next_dt, and RefineableUnsteadyHeatProblem< ELEMENT >::restart().
Referenced by main().
write_trace_file_header()
template<class ELEMENT >
void RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header ()
Write header for trace file.
Write the tecplot header for the trace file.
Definition at line 727 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info, RefineableUnsteadyHeatProblem< ELEMENT >::Epsilon_t, and RefineableUnsteadyHeatProblem< ELEMENT >::Trace_file.
Referenced by main().
Member Data Documentation
Boundary_pt
template<class ELEMENT>
GeomObject* RefineableUnsteadyHeatProblem< ELEMENT >::Boundary_pt [private]
Pointer to GeomObject that specifies the domain bondary.
Definition at line 301 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
Bulk_mesh_pt
template<class ELEMENT>
RefineableQuarterCircleSectorMesh<ELEMENT>* RefineableUnsteadyHeatProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the `bulk` mesh.
Definition at line 307 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_adapt(), RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep(), RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::global_temporal_error_norm(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), and RefineableUnsteadyHeatProblem< ELEMENT >::set_initial_condition().
Doc_info
template<class ELEMENT>
DocInfo RefineableUnsteadyHeatProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 294 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::dump_it(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), RefineableUnsteadyHeatProblem< ELEMENT >::restart(), and RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header().
Doc_node_pt
template<class ELEMENT>
Node* RefineableUnsteadyHeatProblem< ELEMENT >::Doc_node_pt [private]
Pointer to central node (exists at all refinement levels) for doc.
Definition at line 313 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
Epsilon_t
template<class ELEMENT>
double RefineableUnsteadyHeatProblem< ELEMENT >::Epsilon_t [private]
Target error for adaptive timestepping.
Definition at line 319 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), and RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header().
Next_dt
template<class ELEMENT>
double RefineableUnsteadyHeatProblem< ELEMENT >::Next_dt [private]
Suggestion for next timestep (stored to allow it to be written to (or read from) restart file)
Definition at line 298 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::dump_it(), RefineableUnsteadyHeatProblem< ELEMENT >::restart(), and RefineableUnsteadyHeatProblem< ELEMENT >::set_initial_condition().
Source_fct_pt
template<class ELEMENT>
UnsteadyHeatEquations<2>::UnsteadyHeatSourceFctPt RefineableUnsteadyHeatProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 304 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
Surface_mesh_pt
template<class ELEMENT>
Mesh* RefineableUnsteadyHeatProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the `surface` mesh.
Definition at line 310 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::actions_after_adapt(), RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_adapt(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
Trace_file
template<class ELEMENT>
ofstream RefineableUnsteadyHeatProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 316 of file two_d_unsteady_heat_2adapt.cc.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header(), and RefineableUnsteadyHeatProblem< ELEMENT >::~RefineableUnsteadyHeatProblem().
The documentation for this class was generated from the following file:
two_d_unsteady_heat_2adapt.cc