MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D > Class Template Reference
2D Biharmonic problem.
Public Member Functions
MyBiharmonicProblem (typename MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt source_fct_pt, typename MyBiharmonicEquations< DIM, NNODE_1D >::ExactSolnPt exact_pt, const string &node_file_name, const string &element_file_name, const string &poly_file_name)
Constructor: Pass number of elements and pointer to source function.
~MyBiharmonicProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
void nodal_permutation ()
Perform a nodal permutation in curved elements.
Private Attributes
MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt Source_fct_pt
Pointer to source function.
MyBiharmonicEquations< DIM, NNODE_1D >::ExactSolnPt Exact_soln_pt
Pointer to the exact solution.
Detailed Description
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
class MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >
2D Biharmonic problem.
Definition at line 1174 of file unstructured_2d_biharmonic_curvedelement.cc.
Constructor & Destructor Documentation
MyBiharmonicProblem()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicProblem (typename MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt source_fct_pt, typename MyBiharmonicEquations< DIM, NNODE_1D >::ExactSolnPt exact_pt, const string & node_file_name, const string & element_file_name, const string & poly_file_name)
Constructor: Pass number of elements and pointer to source function.
Constructor for 2D Biharmonic problem. Discretise the 2D domain with n_element elements of type ELEMENT. Specify function pointer to source function.
Definition at line 1226 of file unstructured_2d_biharmonic_curvedelement.cc.
 MyBiharmonicProblem()
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::~MyBiharmonicProblem () [inline]
Destructor (empty)
Definition at line 1186 of file unstructured_2d_biharmonic_curvedelement.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 1196 of file unstructured_2d_biharmonic_curvedelement.cc.
actions_before_newton_solve()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
Update the problem specs before solve: (Re)set boundary values from the exact solution.
Definition at line 1502 of file unstructured_2d_biharmonic_curvedelement.cc.
References Physical_Variables::get_exact_u().
doc_solution()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::doc_solution (DocInfo & doc_info)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Doc the solution in tecplot format. Label files with label.
Definition at line 1542 of file unstructured_2d_biharmonic_curvedelement.cc.
References Physical_Variables::get_exact_u().
Referenced by main().
nodal_permutation()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::nodal_permutation ()
Perform a nodal permutation in curved elements.
Update the nodal permutation in curved elements: (Re)assign coordinates so that the first and the second nodes are associated with the lower and upper position on a boundary, respectively. The third node is off-boundary node. Permutation just for the curved elements
Definition at line 1359 of file unstructured_2d_biharmonic_curvedelement.cc.
Member Data Documentation
Exact_soln_pt
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
MyBiharmonicEquations<DIM,NNODE_1D>::ExactSolnPt MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::Exact_soln_pt [private]
Pointer to the exact solution.
Definition at line 1211 of file unstructured_2d_biharmonic_curvedelement.cc.
Source_fct_pt
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
MyBiharmonicEquations<DIM,NNODE_1D>::SourceFctPt MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::Source_fct_pt [private]
Pointer to source function.
Definition at line 1208 of file unstructured_2d_biharmonic_curvedelement.cc.
The documentation for this class was generated from the following file:
unstructured_2d_biharmonic_curvedelement.cc