SteadyCurvedTubeProblem< ELEMENT > Class Template Reference
Entry flow problem in tapered tube domain.
Public Member Functions
SteadyCurvedTubeProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target)
Constructor: Pass DocInfo object and target errors.
~SteadyCurvedTubeProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_adapt ()
After adaptation: Pin redudant pressure dofs.
void doc_solution ()
Doc the solution.
RefineableTubeMesh< ELEMENT > * mesh_pt ()
Overload generic access function by one that returns a pointer to the specific mesh.
Private Attributes
DocInfo Doc_info
Doc info object.
GeomObject * Volume_pt
Pointer to GeomObject that specifies the domain volume.
Detailed Description
template<class ELEMENT>
class SteadyCurvedTubeProblem< ELEMENT >
Entry flow problem in tapered tube domain.
Definition at line 103 of file curved_pipe.cc.
Constructor & Destructor Documentation
SteadyCurvedTubeProblem()
template<class ELEMENT >
SteadyCurvedTubeProblem< ELEMENT >::SteadyCurvedTubeProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
Definition at line 153 of file curved_pipe.cc.
References Global_Physical_Variables::Delta, SteadyCurvedTubeProblem< ELEMENT >::mesh_pt(), Global_Physical_Variables::Re, and SteadyCurvedTubeProblem< ELEMENT >::Volume_pt.
 SteadyCurvedTubeProblem()
template<class ELEMENT>
SteadyCurvedTubeProblem< ELEMENT >::~SteadyCurvedTubeProblem () [inline]
Destructor (empty)
Definition at line 113 of file curved_pipe.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT>
void SteadyCurvedTubeProblem< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Pin redudant pressure dofs.
Definition at line 119 of file curved_pipe.cc.
actions_before_newton_solve()
template<class ELEMENT >
void SteadyCurvedTubeProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
Set the inflow boundary conditions.
Definition at line 260 of file curved_pipe.cc.
References Global_Physical_Variables::Delta, and SteadyCurvedTubeProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void SteadyCurvedTubeProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 288 of file curved_pipe.cc.
References SteadyCurvedTubeProblem< ELEMENT >::Doc_info, SteadyCurvedTubeProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
Referenced by main().
mesh_pt()
template<class ELEMENT>
RefineableTubeMesh<ELEMENT>* SteadyCurvedTubeProblem< ELEMENT >::mesh_pt () [inline]
Overload generic access function by one that returns a pointer to the specific mesh.
Definition at line 131 of file curved_pipe.cc.
Referenced by SteadyCurvedTubeProblem< ELEMENT >::actions_before_newton_solve(), SteadyCurvedTubeProblem< ELEMENT >::doc_solution(), and SteadyCurvedTubeProblem< ELEMENT >::SteadyCurvedTubeProblem().
Member Data Documentation
Doc_info
template<class ELEMENT>
DocInfo SteadyCurvedTubeProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 139 of file curved_pipe.cc.
Referenced by SteadyCurvedTubeProblem< ELEMENT >::doc_solution().
Volume_pt
template<class ELEMENT>
GeomObject* SteadyCurvedTubeProblem< ELEMENT >::Volume_pt [private]
Pointer to GeomObject that specifies the domain volume.
Definition at line 142 of file curved_pipe.cc.
Referenced by SteadyCurvedTubeProblem< ELEMENT >::SteadyCurvedTubeProblem().
The documentation for this class was generated from the following file:
curved_pipe.cc