CantileverProblem< ELEMENT > Class Template Reference
Problem class for the cantilever `beam` structure.
Public Member Functions
CantileverProblem ()
Constructor:
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
ElasticRefineableRectangularQuadMesh< ELEMENT > *& solid_mesh_pt ()
Access function for the solid mesh.
SolidMesh *& traction_mesh_pt ()
Access function to the mesh of surface traction elements.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution ()
Doc the solution.
CantileverProblem (const bool &incompress, const bool &use_fd)
Constructor:
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
ElasticRefineableRectangularQuadMesh< ELEMENT > *& solid_mesh_pt ()
Access function for the solid mesh.
ElasticRectangularQuadMesh< ELEMENT > *& solid_mesh_pt ()
Access function for the solid mesh.
SolidMesh *& traction_mesh_pt ()
Access function to the mesh of surface traction elements.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution ()
Doc the solution.
void run_it (const unsigned &i_case)
Run the job -- doc in RESLTi_case.
Private Member Functions
void set_traction_pt ()
Pass pointer to traction function to the elements in the traction mesh.
void create_traction_elements ()
Create traction elements.
void delete_traction_elements ()
Delete traction elements.
void set_traction_pt ()
Pass pointer to traction function to the elements in the traction mesh.
void create_traction_elements ()
Create traction elements.
void delete_traction_elements ()
Delete traction elements.
Private Attributes
ofstream Trace_file
Trace file.
Node * Trace_node_pt
Pointers to node whose position we're tracing.
ElasticRefineableRectangularQuadMesh< ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
SolidMesh * Traction_mesh_pt
Pointer to mesh of traction elements.
DocInfo Doc_info
DocInfo object for output.
ElasticRectangularQuadMesh< ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
Detailed Description
template<class ELEMENT>
class CantileverProblem< ELEMENT >
Problem class for the cantilever `beam` structure.
Definition at line 209 of file airy_cantilever.cc.
Constructor & Destructor Documentation
CantileverProblem() [1/2]
template<class ELEMENT >
CantileverProblem< ELEMENT >::CantileverProblem ()
Constructor:
Definition at line 273 of file airy_cantilever.cc.
References Global_Physical_Variables::Constitutive_law_pt, Global_Physical_Variables::gravity(), Global_Physical_Variables::H, and Global_Physical_Variables::L.
CantileverProblem() [2/2]
template<class ELEMENT >
CantileverProblem< ELEMENT >::CantileverProblem (const bool & incompress, const bool & use_fd)
Constructor:
Definition at line 310 of file airy_cantilever2.cc.
References CantileverProblem< ELEMENT >::actions_after_adapt(), CantileverProblem< ELEMENT >::actions_before_adapt(), Global_Physical_Variables::constant_pressure(), Global_Physical_Variables::Constitutive_law_pt, CantileverProblem< ELEMENT >::create_traction_elements(), CantileverProblem< ELEMENT >::delete_traction_elements(), CantileverProblem< ELEMENT >::doc_solution(), Global_Physical_Variables::gravity(), Global_Physical_Variables::H, Global_Physical_Variables::L, Global_Physical_Variables::P, and CantileverProblem< ELEMENT >::set_traction_pt().
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 392 of file airy_cantilever.cc.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
actions_after_adapt() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
actions_after_newton_solve() [1/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 218 of file airy_cantilever.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 230 of file airy_cantilever2.cc.
actions_before_adapt() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 376 of file airy_cantilever.cc.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
actions_before_adapt() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
actions_before_newton_solve() [1/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 221 of file airy_cantilever.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 233 of file airy_cantilever2.cc.
create_traction_elements() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::create_traction_elements () [private]
Create traction elements.
Definition at line 441 of file airy_cantilever.cc.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
create_traction_elements() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::create_traction_elements () [private]
Create traction elements.
delete_traction_elements() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::delete_traction_elements () [private]
Delete traction elements.
Delete traction elements and wipe the traction meshes.
Definition at line 476 of file airy_cantilever.cc.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
delete_traction_elements() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::delete_traction_elements () [private]
Delete traction elements.
doc_solution() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 499 of file airy_cantilever.cc.
References Global_Physical_Variables::H, Global_Physical_Variables::L, and Global_Physical_Variables::P.
Referenced by CantileverProblem< ELEMENT >::CantileverProblem(), and main().
doc_solution() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::doc_solution ()
Doc the solution.
run_it()
template<class ELEMENT >
void CantileverProblem< ELEMENT >::run_it (const unsigned & i_case)
Run the job -- doc in RESLTi_case.
Run it.
Definition at line 676 of file airy_cantilever2.cc.
References Global_Physical_Variables::Gravity, and Global_Physical_Variables::P.
Referenced by main().
set_traction_pt() [1/2]
template<class ELEMENT >
void CantileverProblem< ELEMENT >::set_traction_pt () [private]
Pass pointer to traction function to the elements in the traction mesh.
Set pointer to traction function for the relevant elements in the traction mesh
Definition at line 417 of file airy_cantilever.cc.
References Global_Physical_Variables::constant_pressure().
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
set_traction_pt() [2/2]
template<class ELEMENT>
void CantileverProblem< ELEMENT >::set_traction_pt () [private]
Pass pointer to traction function to the elements in the traction mesh.
solid_mesh_pt() [1/3]
template<class ELEMENT>
ElasticRefineableRectangularQuadMesh<ELEMENT>*& CantileverProblem< ELEMENT >::solid_mesh_pt () [inline]
Access function for the solid mesh.
Definition at line 224 of file airy_cantilever.cc.
solid_mesh_pt() [2/3]
template<class ELEMENT>
ElasticRefineableRectangularQuadMesh<ELEMENT>*& CantileverProblem< ELEMENT >::solid_mesh_pt () [inline]
Access function for the solid mesh.
Definition at line 238 of file airy_cantilever2.cc.
solid_mesh_pt() [3/3]
template<class ELEMENT>
ElasticRectangularQuadMesh<ELEMENT>*& CantileverProblem< ELEMENT >::solid_mesh_pt () [inline]
Access function for the solid mesh.
Definition at line 244 of file airy_cantilever2.cc.
traction_mesh_pt() [1/2]
template<class ELEMENT>
SolidMesh*& CantileverProblem< ELEMENT >::traction_mesh_pt () [inline]
Access function to the mesh of surface traction elements.
Definition at line 228 of file airy_cantilever.cc.
traction_mesh_pt() [2/2]
template<class ELEMENT>
SolidMesh*& CantileverProblem< ELEMENT >::traction_mesh_pt () [inline]
Access function to the mesh of surface traction elements.
Definition at line 251 of file airy_cantilever2.cc.
Member Data Documentation
Doc_info
template<class ELEMENT>
DocInfo CantileverProblem< ELEMENT >::Doc_info [private]
DocInfo object for output.
Definition at line 264 of file airy_cantilever.cc.
Solid_mesh_pt [1/2]
template<class ELEMENT>
ElasticRefineableRectangularQuadMesh< ELEMENT > * CantileverProblem< ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 258 of file airy_cantilever.cc.
Solid_mesh_pt [2/2]
template<class ELEMENT>
ElasticRectangularQuadMesh<ELEMENT>* CantileverProblem< ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 292 of file airy_cantilever2.cc.
Trace_file
template<class ELEMENT>
ofstream CantileverProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 252 of file airy_cantilever.cc.
Trace_node_pt
template<class ELEMENT>
Node * CantileverProblem< ELEMENT >::Trace_node_pt [private]
Pointers to node whose position we're tracing.
Definition at line 255 of file airy_cantilever.cc.
Traction_mesh_pt
template<class ELEMENT>
SolidMesh * CantileverProblem< ELEMENT >::Traction_mesh_pt [private]
Pointer to mesh of traction elements.
Pointers to meshes of traction elements.
Definition at line 261 of file airy_cantilever.cc.
The documentation for this class was generated from the following files:
airy_cantilever.cc
airy_cantilever2.cc