AnnularDiskProblem< ELASTICITY_ELEMENT > Class Template Reference
Annular disk.
Public Member Functions
AnnularDiskProblem ()
Constructor:
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution ()
Doc the solution.
Private Member Functions
void create_traction_elements ()
Create traction elements.
void delete_traction_elements ()
Delete traction elements.
Private Attributes
TreeBasedRefineableMeshBase * Solid_mesh_pt
Pointer to refineable solid mesh.
Mesh * Solid_mesh_pt
Pointer to solid mesh.
Mesh * Traction_mesh_pt
Pointer to mesh of traction elements.
DocInfo Doc_info
DocInfo object for output.
Detailed Description
template<class ELASTICITY_ELEMENT>
class AnnularDiskProblem< ELASTICITY_ELEMENT >
Annular disk.
Definition at line 304 of file time_harmonic_elastic_annulus.cc.
Constructor & Destructor Documentation
AnnularDiskProblem()
template<class ELASTICITY_ELEMENT >
AnnularDiskProblem< ELASTICITY_ELEMENT >::AnnularDiskProblem ()
Constructor:
Definition at line 360 of file time_harmonic_elastic_annulus.cc.
References Global_Parameters::Directory, Global_Parameters::E(), Global_Parameters::H_annulus, Global_Parameters::Nr, Global_Parameters::Ntheta, Global_Parameters::Omega_sq, and Global_Parameters::solid_boundary_displacement().
Member Function Documentation
actions_after_adapt()
template<class ELASTICITY_ELEMENT >
void AnnularDiskProblem< ELASTICITY_ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 510 of file time_harmonic_elastic_annulus.cc.
actions_after_newton_solve()
template<class ELASTICITY_ELEMENT>
void AnnularDiskProblem< ELASTICITY_ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 313 of file time_harmonic_elastic_annulus.cc.
actions_before_adapt()
template<class ELASTICITY_ELEMENT >
void AnnularDiskProblem< ELASTICITY_ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 494 of file time_harmonic_elastic_annulus.cc.
actions_before_newton_solve()
template<class ELASTICITY_ELEMENT>
void AnnularDiskProblem< ELASTICITY_ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 316 of file time_harmonic_elastic_annulus.cc.
create_traction_elements()
template<class ELASTICITY_ELEMENT >
void AnnularDiskProblem< ELASTICITY_ELEMENT >::create_traction_elements () [private]
Create traction elements.
Definition at line 526 of file time_harmonic_elastic_annulus.cc.
References Global_Parameters::constant_pressure().
delete_traction_elements()
template<class ELASTICITY_ELEMENT >
void AnnularDiskProblem< ELASTICITY_ELEMENT >::delete_traction_elements () [private]
Delete traction elements.
Delete traction elements and wipe the traction meshes.
Definition at line 581 of file time_harmonic_elastic_annulus.cc.
doc_solution()
template<class ELASTICITY_ELEMENT >
void AnnularDiskProblem< ELASTICITY_ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 606 of file time_harmonic_elastic_annulus.cc.
References Global_Parameters::exact_u().
Referenced by main().
Member Data Documentation
Doc_info
template<class ELASTICITY_ELEMENT>
DocInfo AnnularDiskProblem< ELASTICITY_ELEMENT >::Doc_info [private]
DocInfo object for output.
Definition at line 351 of file time_harmonic_elastic_annulus.cc.
Solid_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT>
TreeBasedRefineableMeshBase* AnnularDiskProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt [private]
Pointer to refineable solid mesh.
Definition at line 338 of file time_harmonic_elastic_annulus.cc.
Solid_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT>
Mesh* AnnularDiskProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 343 of file time_harmonic_elastic_annulus.cc.
Traction_mesh_pt
template<class ELASTICITY_ELEMENT>
Mesh* AnnularDiskProblem< ELASTICITY_ELEMENT >::Traction_mesh_pt [private]
Pointer to mesh of traction elements.
Definition at line 348 of file time_harmonic_elastic_annulus.cc.
The documentation for this class was generated from the following file:
time_harmonic_elastic_annulus.cc