RingWithTRibProblem< ELASTICITY_ELEMENT > Class Template Reference
Annular disk.
Public Member Functions
RingWithTRibProblem ()
Constructor:
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution ()
Doc the solution.
Private Member Functions
void create_traction_elements ()
Create traction elements.
void delete_traction_elements ()
Delete traction elements.
void complete_problem_setup ()
Helper function to complete problem setup.
Private Attributes
RefineableTriangleMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to refineable solid mesh.
TriangleMesh< ELASTICITY_ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
Mesh * Traction_mesh_pt
Pointer to mesh of traction elements.
DocInfo Doc_info
DocInfo object for output.
unsigned Upper_symmetry_boundary_id
Boundary ID of upper symmetry boundary.
unsigned Lower_symmetry_boundary_id
Boundary ID of lower symmetry boundary.
unsigned Outer_boundary_id
Boundary ID of outer boundary.
Detailed Description
template<class ELASTICITY_ELEMENT>
class RingWithTRibProblem< ELASTICITY_ELEMENT >
Annular disk.
Definition at line 159 of file unstructured_time_harmonic_elastic_annulus.cc.
Constructor & Destructor Documentation
RingWithTRibProblem()
template<class ELASTICITY_ELEMENT >
RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem ()
Constructor:
Definition at line 227 of file unstructured_time_harmonic_elastic_annulus.cc.
References Global_Parameters::Directory, Global_Parameters::E_pt, Global_Parameters::H_annulus, and Global_Parameters::Nu.
Member Function Documentation
actions_after_adapt()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 668 of file unstructured_time_harmonic_elastic_annulus.cc.
actions_after_newton_solve()
template<class ELASTICITY_ELEMENT>
void RingWithTRibProblem< ELASTICITY_ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 168 of file unstructured_time_harmonic_elastic_annulus.cc.
actions_before_adapt()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 652 of file unstructured_time_harmonic_elastic_annulus.cc.
actions_before_newton_solve()
template<class ELASTICITY_ELEMENT>
void RingWithTRibProblem< ELASTICITY_ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 171 of file unstructured_time_harmonic_elastic_annulus.cc.
complete_problem_setup()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::complete_problem_setup () [private]
Helper function to complete problem setup.
Complete problem setup.
Definition at line 570 of file unstructured_time_harmonic_elastic_annulus.cc.
References Global_Parameters::E_pt, and Global_Parameters::Omega_sq_region().
create_traction_elements()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::create_traction_elements () [private]
Create traction elements.
Definition at line 687 of file unstructured_time_harmonic_elastic_annulus.cc.
References Global_Parameters::pressure_load().
delete_traction_elements()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::delete_traction_elements () [private]
Delete traction elements.
Delete traction elements and wipe the traction meshes.
Definition at line 732 of file unstructured_time_harmonic_elastic_annulus.cc.
doc_solution()
template<class ELASTICITY_ELEMENT >
void RingWithTRibProblem< ELASTICITY_ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 757 of file unstructured_time_harmonic_elastic_annulus.cc.
Referenced by main().
Member Data Documentation
Doc_info
template<class ELASTICITY_ELEMENT>
DocInfo RingWithTRibProblem< ELASTICITY_ELEMENT >::Doc_info [private]
DocInfo object for output.
Definition at line 209 of file unstructured_time_harmonic_elastic_annulus.cc.
Lower_symmetry_boundary_id
template<class ELASTICITY_ELEMENT>
unsigned RingWithTRibProblem< ELASTICITY_ELEMENT >::Lower_symmetry_boundary_id [private]
Boundary ID of lower symmetry boundary.
Definition at line 215 of file unstructured_time_harmonic_elastic_annulus.cc.
Outer_boundary_id
template<class ELASTICITY_ELEMENT>
unsigned RingWithTRibProblem< ELASTICITY_ELEMENT >::Outer_boundary_id [private]
Boundary ID of outer boundary.
Definition at line 218 of file unstructured_time_harmonic_elastic_annulus.cc.
Solid_mesh_pt [1/2]
template<class ELASTICITY_ELEMENT>
RefineableTriangleMesh<ELASTICITY_ELEMENT>* RingWithTRibProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt [private]
Pointer to refineable solid mesh.
Definition at line 196 of file unstructured_time_harmonic_elastic_annulus.cc.
Solid_mesh_pt [2/2]
template<class ELASTICITY_ELEMENT>
TriangleMesh<ELASTICITY_ELEMENT>* RingWithTRibProblem< ELASTICITY_ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 201 of file unstructured_time_harmonic_elastic_annulus.cc.
Traction_mesh_pt
template<class ELASTICITY_ELEMENT>
Mesh* RingWithTRibProblem< ELASTICITY_ELEMENT >::Traction_mesh_pt [private]
Pointer to mesh of traction elements.
Definition at line 206 of file unstructured_time_harmonic_elastic_annulus.cc.
Upper_symmetry_boundary_id
template<class ELASTICITY_ELEMENT>
unsigned RingWithTRibProblem< ELASTICITY_ELEMENT >::Upper_symmetry_boundary_id [private]
Boundary ID of upper symmetry boundary.
Definition at line 212 of file unstructured_time_harmonic_elastic_annulus.cc.
The documentation for this class was generated from the following file:
unstructured_time_harmonic_elastic_annulus.cc