RefineablePoissonProblem< ELEMENT > Class Template Reference
Public Member Functions
RefineablePoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~RefineablePoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
SimpleRefineableRectangularQuadMesh< ELEMENT > * mesh_pt ()
Overloaded version of the Problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Private Attributes
PoissonEquations< 2 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT>
class RefineablePoissonProblem< ELEMENT >
2D Poisson problem on rectangular domain, discretised with refineable 2D QPoisson elements. The specific type of element is specified via the template parameter.
Definition at line 131 of file two_d_poisson_adapt.cc.
Constructor & Destructor Documentation
RefineablePoissonProblem()
template<class ELEMENT >
RefineablePoissonProblem< ELEMENT >::RefineablePoissonProblem (PoissonEquations< 2 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
Constructor for Poisson problem: Pass pointer to source function.
Definition at line 178 of file two_d_poisson_adapt.cc.
References RefineablePoissonProblem< ELEMENT >::mesh_pt(), and RefineablePoissonProblem< ELEMENT >::Source_fct_pt.
 RefineablePoissonProblem()
template<class ELEMENT>
RefineablePoissonProblem< ELEMENT >::~RefineablePoissonProblem () [inline]
Destructor (empty)
Definition at line 141 of file two_d_poisson_adapt.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void RefineablePoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 148 of file two_d_poisson_adapt.cc.
actions_before_newton_solve()
template<class ELEMENT >
void RefineablePoissonProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the exact solution.
Update the problem specs before solve: (Re-)set boundary conditions to the values from the exact solution.
Definition at line 245 of file two_d_poisson_adapt.cc.
References TanhSolnForPoisson::get_exact_u(), and RefineablePoissonProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void RefineablePoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. DocInfo object stores flags/labels for where the output gets written to.
Doc the solution: doc_info contains labels/output directory etc.
Definition at line 283 of file two_d_poisson_adapt.cc.
References TanhSolnForPoisson::get_exact_u(), and RefineablePoissonProblem< ELEMENT >::mesh_pt().
Referenced by main().
mesh_pt()
template<class ELEMENT>
SimpleRefineableRectangularQuadMesh<ELEMENT>* RefineablePoissonProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the Problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 157 of file two_d_poisson_adapt.cc.
Referenced by RefineablePoissonProblem< ELEMENT >::actions_before_newton_solve(), RefineablePoissonProblem< ELEMENT >::doc_solution(), and RefineablePoissonProblem< ELEMENT >::RefineablePoissonProblem().
Member Data Documentation
Source_fct_pt
template<class ELEMENT>
PoissonEquations<2>::PoissonSourceFctPt RefineablePoissonProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 166 of file two_d_poisson_adapt.cc.
Referenced by RefineablePoissonProblem< ELEMENT >::RefineablePoissonProblem().
The documentation for this class was generated from the following file:
two_d_poisson_adapt.cc