TurekNonFSIProblem< ELEMENT > Class Template Reference
Flow around a cylinder with flag.
Public Member Functions
TurekNonFSIProblem (const double &length, const double &height)
Constructor: Pass length and height of domain.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_adapt ()
After adaptation: Unpin pressures and pin redudant pressure dofs.
void actions_before_implicit_timestep ()
Update the velocity boundary condition on the flag.
RefineableCylinderWithFlagMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
RefineableAlgebraicCylinderWithFlagMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
double Height
Height of channel.
Detailed Description
template<class ELEMENT>
class TurekNonFSIProblem< ELEMENT >
Flow around a cylinder with flag.
Definition at line 315 of file turek_flag_non_fsi.cc.
Constructor & Destructor Documentation
TurekNonFSIProblem()
template<class ELEMENT >
TurekNonFSIProblem< ELEMENT >::TurekNonFSIProblem (const double & length, const double & height)
Constructor: Pass length and height of domain.
Definition at line 375 of file turek_flag_non_fsi.cc.
References Flag_definition::Bottom_flag_pt, Flag_definition::Centre_x, Flag_definition::Centre_y, Flag_definition::Cylinder_pt, Flag_definition::H, TurekNonFSIProblem< ELEMENT >::Height, Flag_definition::L, TurekNonFSIProblem< ELEMENT >::mesh_pt(), Flag_definition::Radius, Global_Parameters::Re, Flag_definition::setup(), Flag_definition::Tip_flag_pt, and Flag_definition::Top_flag_pt.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void TurekNonFSIProblem< ELEMENT >::actions_after_adapt ()
After adaptation: Unpin pressures and pin redudant pressure dofs.
Actions after adapt.
Definition at line 507 of file turek_flag_non_fsi.cc.
References TurekNonFSIProblem< ELEMENT >::mesh_pt().
actions_after_newton_solve()
template<class ELEMENT>
void TurekNonFSIProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 325 of file turek_flag_non_fsi.cc.
actions_before_implicit_timestep()
template<class ELEMENT >
void TurekNonFSIProblem< ELEMENT >::actions_before_implicit_timestep ()
Update the velocity boundary condition on the flag.
Actions before implicit timestep: Update velocity boundary conditions.
Definition at line 524 of file turek_flag_non_fsi.cc.
References TurekNonFSIProblem< ELEMENT >::mesh_pt().
actions_before_newton_solve()
template<class ELEMENT>
void TurekNonFSIProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 328 of file turek_flag_non_fsi.cc.
doc_solution()
template<class ELEMENT >
void TurekNonFSIProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 551 of file turek_flag_non_fsi.cc.
References TurekNonFSIProblem< ELEMENT >::mesh_pt().
mesh_pt() [1/2]
template<class ELEMENT>
RefineableCylinderWithFlagMesh<ELEMENT>* TurekNonFSIProblem< ELEMENT >::mesh_pt () [inline]
Access function for the specific mesh.
Definition at line 340 of file turek_flag_non_fsi.cc.
Referenced by TurekNonFSIProblem< ELEMENT >::actions_after_adapt(), TurekNonFSIProblem< ELEMENT >::actions_before_implicit_timestep(), TurekNonFSIProblem< ELEMENT >::doc_solution(), and TurekNonFSIProblem< ELEMENT >::TurekNonFSIProblem().
mesh_pt() [2/2]
template<class ELEMENT>
RefineableAlgebraicCylinderWithFlagMesh<ELEMENT>* TurekNonFSIProblem< ELEMENT >::mesh_pt () [inline]
Access function for the specific mesh.
Definition at line 349 of file turek_flag_non_fsi.cc.
Member Data Documentation
Height
template<class ELEMENT>
double TurekNonFSIProblem< ELEMENT >::Height [private]
Height of channel.
Definition at line 364 of file turek_flag_non_fsi.cc.
Referenced by TurekNonFSIProblem< ELEMENT >::TurekNonFSIProblem().
The documentation for this class was generated from the following file:
turek_flag_non_fsi.cc