multi_domain_boussinesq_convection.cc File Reference
Classes
class ConvectionProblem< ELEMENT >
Namespaces
 Global_Physical_Variables
Namespace for the physical parameters in the problem.
Functions
Vector< double > Global_Physical_Variables::Direction_of_gravity (2)
Gravity vector.
int main (int argc, char **argv)
Driver code for 2D Boussinesq convection problem.
Function Documentation
main()
int main (int argc, char ** argv)
Driver code for 2D Boussinesq convection problem.
Definition at line 422 of file multi_domain_boussinesq_convection.cc.
References Global_Physical_Variables::Direction_of_gravity(), ConvectionProblem< ELEMENT >::doc_solution(), and ConvectionProblem< ELEMENT >::set_boundary_conditions().