FSIChannelWithLeafletProblem< ELEMENT > Class Template Reference
Public Member Functions
FSIChannelWithLeafletProblem (const unsigned &mesh_multiplier)
Constructor: Pass multiplier for uniform mesh refinement.
~FSIChannelWithLeafletProblem ()
Destructor empty.
void actions_after_newton_solve ()
Actions after solve (empty)
void actions_before_newton_solve ()
Actions before Newton solve: Reset the pseudo-elastic undeformed configuration.
void actions_before_newton_convergence_check ()
Update no slip before Newton convergence check.
void actions_before_implicit_timestep ()
Actions before implicit timestep: Update the inflow velocity.
void set_iterative_solver ()
Set iterative solver.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion by Lagrange multipliers.
void delete_lagrange_multiplier_elements ()
void doc_parameters ()
Doc parameters.
Private Member Functions
Node * tip_node_pt ()
Helper fct; returns the node at the tip of the wall mesh.
Private Attributes
PseudoElasticChannelWithLeafletMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the fluid mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * Wall_mesh_pt
Pointer to the `wall` mesh.
BDF< 2 > * Bulk_time_stepper_pt
Bulk timestepper.
Newmark< 2 > * Wall_time_stepper_pt
Wall time stepper pt.
SolidMesh * Lagrange_multiplier_mesh_pt
Pointers to mesh of Lagrange multiplier elements.
ConstitutiveLaw * Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
MeshAsGeomObject * Wall_geom_object_pt
Geometric object for the leaflet (to apply lagrange mult)
UndeformedLeaflet * Undeformed_wall_pt
Geom object for the leaflet.
Detailed Description
template<class ELEMENT>
class FSIChannelWithLeafletProblem< ELEMENT >
FSI leaflet in channel. Mesh update with pseudo-elasticity and solved with pseudo-elastic fsi preconditioner.
Definition at line 351 of file fsi_channel_with_leaflet_precond.cc.
Constructor & Destructor Documentation
FSIChannelWithLeafletProblem()
template<class ELEMENT >
FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem (const unsigned & mesh_multiplier)
Constructor: Pass multiplier for uniform mesh refinement.
Constructor.
Definition at line 494 of file fsi_channel_with_leaflet_precond.cc.
References Global_Parameters::Fluid_height, Global_Parameters::Fluid_length_left, Global_Parameters::Fluid_length_right, Global_Parameters::H, Global_Parameters::Lambda_sq, Global_Parameters::Lambda_sq_beam, Global_Parameters::Leaflet_height, Global_Parameters::Leaflet_x0, Global_Parameters::Mesh_nleft, Global_Parameters::Mesh_nright, Global_Parameters::Mesh_ny1, Global_Parameters::Mesh_ny2, Global_Parameters::Nu, Global_Parameters::Q, Global_Parameters::Re, and Global_Parameters::ReSt.
 FSIChannelWithLeafletProblem()
template<class ELEMENT >
FSIChannelWithLeafletProblem< ELEMENT >::~FSIChannelWithLeafletProblem () [inline]
Destructor empty.
Definition at line 360 of file fsi_channel_with_leaflet_precond.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve (empty)
Definition at line 373 of file fsi_channel_with_leaflet_precond.cc.
actions_before_implicit_timestep()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_implicit_timestep () [inline]
Actions before implicit timestep: Update the inflow velocity.
Definition at line 396 of file fsi_channel_with_leaflet_precond.cc.
References Global_Parameters::Fluid_height, and Global_Parameters::flux().
actions_before_newton_convergence_check()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Update no slip before Newton convergence check.
Definition at line 384 of file fsi_channel_with_leaflet_precond.cc.
actions_before_newton_solve()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before Newton solve: Reset the pseudo-elastic undeformed configuration.
Definition at line 377 of file fsi_channel_with_leaflet_precond.cc.
create_lagrange_multiplier_elements()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements ()
Create elements that enforce prescribed boundary motion by Lagrange multipliers.
Create elements that impose the prescribed boundary displacement by Lagrange multipliers
Definition at line 872 of file fsi_channel_with_leaflet_precond.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::delete_lagrange_multiplier_elements().
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver().
delete_lagrange_multiplier_elements()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::delete_lagrange_multiplier_elements ()
Delete elements that enforce prescribed boundary motion by Lagrange multipliers
Delete elements that impose the prescribed boundary displacement and wipe the associated mesh
Definition at line 947 of file fsi_channel_with_leaflet_precond.cc.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements().
doc_parameters()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::doc_parameters () [inline]
Doc parameters.
Definition at line 432 of file fsi_channel_with_leaflet_precond.cc.
References Global_Parameters::Lambda_sq_beam, Global_Parameters::Q, Global_Parameters::Re, and Global_Parameters::T.
doc_solution()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 970 of file fsi_channel_with_leaflet_precond.cc.
set_iterative_solver()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver ()
Set iterative solver.
Definition at line 737 of file fsi_channel_with_leaflet_precond.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), and LSC_Preconditioner_Helper::set_hypre_preconditioner().
tip_node_pt()
template<class ELEMENT >
Node* FSIChannelWithLeafletProblem< ELEMENT >::tip_node_pt () [inline], [private]
Helper fct; returns the node at the tip of the wall mesh.
Definition at line 455 of file fsi_channel_with_leaflet_precond.cc.
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
PseudoElasticChannelWithLeafletMesh<ELEMENT>* FSIChannelWithLeafletProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the fluid mesh.
Definition at line 463 of file fsi_channel_with_leaflet_precond.cc.
Bulk_time_stepper_pt
template<class ELEMENT >
BDF<2>* FSIChannelWithLeafletProblem< ELEMENT >::Bulk_time_stepper_pt [private]
Bulk timestepper.
Definition at line 469 of file fsi_channel_with_leaflet_precond.cc.
Constitutive_law_pt
template<class ELEMENT >
ConstitutiveLaw* FSIChannelWithLeafletProblem< ELEMENT >::Constitutive_law_pt [private]
Constitutive law used to determine the mesh deformation.
Definition at line 478 of file fsi_channel_with_leaflet_precond.cc.
Lagrange_multiplier_mesh_pt
template<class ELEMENT >
SolidMesh* FSIChannelWithLeafletProblem< ELEMENT >::Lagrange_multiplier_mesh_pt [private]
Pointers to mesh of Lagrange multiplier elements.
Definition at line 475 of file fsi_channel_with_leaflet_precond.cc.
Undeformed_wall_pt
template<class ELEMENT >
UndeformedLeaflet* FSIChannelWithLeafletProblem< ELEMENT >::Undeformed_wall_pt [private]
Geom object for the leaflet.
Definition at line 484 of file fsi_channel_with_leaflet_precond.cc.
Wall_geom_object_pt
template<class ELEMENT >
MeshAsGeomObject* FSIChannelWithLeafletProblem< ELEMENT >::Wall_geom_object_pt [private]
Geometric object for the leaflet (to apply lagrange mult)
Definition at line 481 of file fsi_channel_with_leaflet_precond.cc.
Wall_mesh_pt
template<class ELEMENT >
OneDLagrangianMesh<FSIHermiteBeamElement>* FSIChannelWithLeafletProblem< ELEMENT >::Wall_mesh_pt [private]
Pointer to the `wall` mesh.
Definition at line 466 of file fsi_channel_with_leaflet_precond.cc.
Wall_time_stepper_pt
template<class ELEMENT >
Newmark<2>* FSIChannelWithLeafletProblem< ELEMENT >::Wall_time_stepper_pt [private]
Wall time stepper pt.
Definition at line 472 of file fsi_channel_with_leaflet_precond.cc.
The documentation for this class was generated from the following file:
fsi_channel_with_leaflet_precond.cc