SteadyHelicalProblem< ELEMENT > Class Template Reference
Entry flow problem in tapered tube domain.
Public Member Functions
SteadyHelicalProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target)
Constructor: Pass DocInfo object and target errors.
~SteadyHelicalProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_after_adapt ()
After adaptation: Pin redudant pressure dofs.
void doc_solution ()
Doc the solution.
RefineableTubeMesh< ELEMENT > * mesh_pt ()
Overload generic access function by one that returns a pointer to the specific mesh.
Private Attributes
int Alpha
Exponent for bluntness of velocity profile.
DocInfo Doc_info
Doc info object.
GeomObject * Wall_pt
Pointer to GeomObject that specifies the domain boundary.
Detailed Description
template<class ELEMENT>
class SteadyHelicalProblem< ELEMENT >
Entry flow problem in tapered tube domain.
Definition at line 106 of file helical_pipe.cc.
Constructor & Destructor Documentation
SteadyHelicalProblem()
template<class ELEMENT >
SteadyHelicalProblem< ELEMENT >::SteadyHelicalProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
Definition at line 159 of file helical_pipe.cc.
References Global_Physical_Variables::Delta, SteadyHelicalProblem< ELEMENT >::mesh_pt(), Global_Physical_Variables::Pitch, Global_Physical_Variables::Re, and SteadyHelicalProblem< ELEMENT >::Wall_pt.
 SteadyHelicalProblem()
template<class ELEMENT>
SteadyHelicalProblem< ELEMENT >::~SteadyHelicalProblem () [inline]
Destructor (empty)
Definition at line 116 of file helical_pipe.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT>
void SteadyHelicalProblem< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Pin redudant pressure dofs.
Definition at line 122 of file helical_pipe.cc.
actions_before_newton_solve()
template<class ELEMENT >
void SteadyHelicalProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
Set the inflow boundary conditions.
Definition at line 276 of file helical_pipe.cc.
References Global_Physical_Variables::Delta, and SteadyHelicalProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void SteadyHelicalProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 303 of file helical_pipe.cc.
References SteadyHelicalProblem< ELEMENT >::Doc_info, SteadyHelicalProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
Referenced by main().
mesh_pt()
template<class ELEMENT>
RefineableTubeMesh<ELEMENT>* SteadyHelicalProblem< ELEMENT >::mesh_pt () [inline]
Overload generic access function by one that returns a pointer to the specific mesh.
Definition at line 134 of file helical_pipe.cc.
Referenced by SteadyHelicalProblem< ELEMENT >::actions_before_newton_solve(), SteadyHelicalProblem< ELEMENT >::doc_solution(), and SteadyHelicalProblem< ELEMENT >::SteadyHelicalProblem().
Member Data Documentation
Alpha
template<class ELEMENT>
int SteadyHelicalProblem< ELEMENT >::Alpha [private]
Exponent for bluntness of velocity profile.
Definition at line 142 of file helical_pipe.cc.
Doc_info
template<class ELEMENT>
DocInfo SteadyHelicalProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 145 of file helical_pipe.cc.
Referenced by SteadyHelicalProblem< ELEMENT >::doc_solution().
Wall_pt
template<class ELEMENT>
GeomObject* SteadyHelicalProblem< ELEMENT >::Wall_pt [private]
Pointer to GeomObject that specifies the domain boundary.
Definition at line 148 of file helical_pipe.cc.
Referenced by SteadyHelicalProblem< ELEMENT >::SteadyHelicalProblem().
The documentation for this class was generated from the following file:
helical_pipe.cc