SUPGAdvectionDiffusionProblem< ELEMENT > Class Template Reference
Public Member Functions
SUPGAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt, const bool &use_stabilisation)
Constructor: Pass pointer to source and wind functions, and flag to indicate if stabilisation is to be used.
~SUPGAdvectionDiffusionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the tanh solution and compute stabilisation parameter.
void actions_after_newton_solve ()
Update the problem after solve (empty)
void doc_solution ()
Doc the solution.
RectangularQuadMesh< ELEMENT > * mesh_pt ()
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Private Attributes
DocInfo Doc_info
DocInfo object.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function.
AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function.
bool Use_stabilisation
Flag to indicate if stabilisation is to be used.
Detailed Description
template<class ELEMENT>
class SUPGAdvectionDiffusionProblem< ELEMENT >
2D AdvectionDiffusion problem on rectangular domain, discretised with refineable 2D QAdvectionDiffusion elements. The specific type of element is specified via the template parameter.
Definition at line 97 of file two_d_adv_diff_SUPG.cc.
Constructor & Destructor Documentation
SUPGAdvectionDiffusionProblem()
template<class ELEMENT >
SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem (AdvectionDiffusionEquations< 2 >::AdvectionDiffusionSourceFctPt source_fct_pt, AdvectionDiffusionEquations< 2 >::AdvectionDiffusionWindFctPt wind_fct_pt, const bool & use_stabilisation)
Constructor: Pass pointer to source and wind functions, and flag to indicate if stabilisation is to be used.
Constructor for AdvectionDiffusion problem: Pass pointer to source function and wind functions and flag to indicate if stabilisation is to be used.
Definition at line 156 of file two_d_adv_diff_SUPG.cc.
References SUPGAdvectionDiffusionProblem< ELEMENT >::Doc_info, SUPGAdvectionDiffusionProblem< ELEMENT >::mesh_pt(), GlobalPhysicalParameters::Peclet, SUPGAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt, and SUPGAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt.
 SUPGAdvectionDiffusionProblem()
template<class ELEMENT>
SUPGAdvectionDiffusionProblem< ELEMENT >::~SUPGAdvectionDiffusionProblem () [inline]
Destructor. Empty.
Definition at line 110 of file two_d_adv_diff_SUPG.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT>
void SUPGAdvectionDiffusionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 118 of file two_d_adv_diff_SUPG.cc.
actions_before_newton_solve()
template<class ELEMENT >
void SUPGAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve: Reset boundary conditions to the values from the tanh solution and compute stabilisation parameter.
Update the problem specs before solve: (Re-)set boundary conditions.
Definition at line 237 of file two_d_adv_diff_SUPG.cc.
References GlobalPhysicalParameters::get_boundary_values(), SUPGAdvectionDiffusionProblem< ELEMENT >::mesh_pt(), and SUPGAdvectionDiffusionProblem< ELEMENT >::Use_stabilisation.
doc_solution()
template<class ELEMENT >
void SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 298 of file two_d_adv_diff_SUPG.cc.
References SUPGAdvectionDiffusionProblem< ELEMENT >::Doc_info, and SUPGAdvectionDiffusionProblem< ELEMENT >::mesh_pt().
Referenced by main().
mesh_pt()
template<class ELEMENT>
RectangularQuadMesh<ELEMENT>* SUPGAdvectionDiffusionProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 126 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve(), SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
Member Data Documentation
Doc_info
template<class ELEMENT>
DocInfo SUPGAdvectionDiffusionProblem< ELEMENT >::Doc_info [private]
DocInfo object.
Definition at line 135 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
Source_fct_pt
template<class ELEMENT>
AdvectionDiffusionEquations<2>::AdvectionDiffusionSourceFctPt SUPGAdvectionDiffusionProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 138 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
Use_stabilisation
template<class ELEMENT>
bool SUPGAdvectionDiffusionProblem< ELEMENT >::Use_stabilisation [private]
Flag to indicate if stabilisation is to be used.
Definition at line 144 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve().
Wind_fct_pt
template<class ELEMENT>
AdvectionDiffusionEquations<2>::AdvectionDiffusionWindFctPt SUPGAdvectionDiffusionProblem< ELEMENT >::Wind_fct_pt [private]
Pointer to wind function.
Definition at line 141 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
The documentation for this class was generated from the following file:
two_d_adv_diff_SUPG.cc