TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT > Class Template Reference
Problem class.
Public Member Functions
TurekProblem (const double &length, const double &height)
Constructor: Pass length and height of domain.
RefineableAlgebraicCylinderWithFlagMesh< FLUID_ELEMENT > * fluid_mesh_pt ()
Access function for the fluid mesh.
ElasticRefineableRectangularQuadMesh< SOLID_ELEMENT > *& solid_mesh_pt ()
Access function for the solid mesh.
SolidMesh *& traction_mesh_pt (const unsigned &i)
Access function for the i-th mesh of FSI traction elements.
void actions_after_adapt ()
Actions after adapt: Re-setup the fsi lookup scheme.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc the solution.
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
void actions_before_newton_convergence_check ()
Update the (enslaved) fluid node positions following the update of the solid variables before performing Newton convergence check.
void actions_before_implicit_timestep ()
Update the time-dependent influx.
Private Member Functions
void create_fsi_traction_elements ()
Create FSI traction elements.
Private Attributes
ElasticRefineableRectangularQuadMesh< SOLID_ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
RefineableAlgebraicCylinderWithFlagMesh< FLUID_ELEMENT > * Fluid_mesh_pt
Pointer to fluid mesh.
Vector< SolidMesh * > Traction_mesh_pt
Vector of pointers to mesh of FSI traction elements.
SolidMesh * Combined_traction_mesh_pt
Combined mesh of traction elements -- only used for documentation.
double Domain_height
Overall height of domain.
double Domain_length
Overall length of domain.
Node * Solid_control_node_pt
Pointer to solid control node.
Node * Fluid_control_node_pt
Pointer to fluid control node.
Detailed Description
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
class TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Problem class.
Definition at line 374 of file turek_flag.cc.
Constructor & Destructor Documentation
TurekProblem()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem (const double & length, const double & height)
Constructor: Pass length and height of domain.
Left point on centreline of flag so that the top and bottom vertices merge with the cylinder.
Definition at line 451 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check(), Global_Parameters::Centre_x, Global_Parameters::Centre_y, Global_Parameters::Constitutive_law_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Domain_height, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_control_node_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt, Global_Parameters::flux(), Global_Parameters::gravity(), Global_Parameters::H, Global_Parameters::Ignore_fluid_loading, Global_Parameters::Lambda_sq, Global_Parameters::Q, Global_Parameters::Radius, Global_Parameters::Re, Global_Parameters::ReSt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_control_node_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt(), Global_Parameters::St, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::traction_mesh_pt(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt.
Member Function Documentation
actions_after_adapt()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt ()
Actions after adapt: Re-setup the fsi lookup scheme.
Actions after adapt: Re-setup FSI.
Definition at line 899 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt, Global_Parameters::Ignore_fluid_loading, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt.
actions_after_newton_solve()
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 401 of file turek_flag.cc.
actions_before_implicit_timestep()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep ()
Update the time-dependent influx.
Actions before implicit timestep: Update inflow profile.
Definition at line 873 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Domain_height, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt, and Global_Parameters::flux().
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check().
actions_before_newton_convergence_check()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check ()
Update the (enslaved) fluid node positions following the update of the solid variables before performing Newton convergence check.
Update the (enslaved) fluid node positions following the update of the solid variables
Definition at line 861 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt().
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
actions_before_newton_solve()
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 404 of file turek_flag.cc.
create_fsi_traction_elements()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements () [private]
Create FSI traction elements.
Definition at line 957 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Combined_traction_mesh_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
doc_solution()
template<class FLUID_ELEMENT , class SOLID_ELEMENT >
void TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc the solution.
Definition at line 1012 of file turek_flag.cc.
References TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_control_node_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt(), Global_Parameters::flux(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_control_node_pt, TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt.
Referenced by main().
fluid_mesh_pt()
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
RefineableAlgebraicCylinderWithFlagMesh<FLUID_ELEMENT>* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::fluid_mesh_pt () [inline]
Access function for the fluid mesh.
Definition at line 383 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
solid_mesh_pt()
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
ElasticRefineableRectangularQuadMesh<SOLID_ELEMENT>*& TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::solid_mesh_pt () [inline]
Access function for the solid mesh.
Definition at line 387 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
traction_mesh_pt()
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
SolidMesh*& TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::traction_mesh_pt (const unsigned & i) [inline]
Access function for the i-th mesh of FSI traction elements.
Definition at line 391 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Member Data Documentation
Combined_traction_mesh_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
SolidMesh* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Combined_traction_mesh_pt [private]
Combined mesh of traction elements -- only used for documentation.
Definition at line 429 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements().
Domain_height
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
double TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Domain_height [private]
Overall height of domain.
Definition at line 432 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Domain_length
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
double TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Domain_length [private]
Overall length of domain.
Definition at line 435 of file turek_flag.cc.
Fluid_control_node_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
Node* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_control_node_pt [private]
Pointer to fluid control node.
Definition at line 441 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Fluid_mesh_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
RefineableAlgebraicCylinderWithFlagMesh<FLUID_ELEMENT>* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Fluid_mesh_pt [private]
Pointer to fluid mesh.
Definition at line 423 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_implicit_timestep(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Solid_control_node_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
Node* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_control_node_pt [private]
Pointer to solid control node.
Definition at line 438 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Solid_mesh_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
ElasticRefineableRectangularQuadMesh<SOLID_ELEMENT>* TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 420 of file turek_flag.cc.
Traction_mesh_pt
template<class FLUID_ELEMENT, class SOLID_ELEMENT>
Vector<SolidMesh*> TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::Traction_mesh_pt [private]
Vector of pointers to mesh of FSI traction elements.
Definition at line 426 of file turek_flag.cc.
Referenced by TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
The documentation for this class was generated from the following file:
turek_flag.cc